// ============================================
// bootstrap.js
// ORVUNO
// ============================================
import "./core/GlobalDarkThemeIntegration.js";
import "./core/DarkMainNavigationIntegration.js";
import "./core/DarkCommandCenterHeaderIntegration.js";
import "./core/HomeOperationsDashboardIntegration.js";
import "./core/HomeWarehouseAndPartialDeliveryIntegration.js";
import "./core/CustomerOrderProductIdCompatibilityIntegration.js";
import "./core/CustomerOrderRuntimeHydrationIntegration.js";
import "./core/HomeDashboardViewportIntegration.js";
import "./core/TransportVehicleCostIntegration.js";
import "./core/TransportFuelTimeIntegration.js";
import "./core/TransportGameplayIntegration.js";
import "./core/CompanyEconomyIntegration.js";
import "./core/WarehouseSpaceIntegration.js";
import "./core/LegacyEconomyWarehouseSpaceBridge.js";
import "./core/UnifiedOperationalStockBridge.js";
import "./core/WarehousePackDisplayIntegration.js";
import "./core/OperationalSupplyChainEquipmentIntegration.js";
import "./core/OperationalWarehouseVisualFixIntegration.js";
import "./core/MachineConditionProductionGuard.js";
import "./core/MachineMaintenanceSystem.js";
import "./core/MachineConditionVisibilityIntegration.js";
import "./core/MachineMaintenanceUIIntegration.js";
import "./core/ReputationSystem.js";
import "./core/UrgentCustomerOrderSystem.js";
import "./core/ReputationCustomerOrderIntegration.js";
import "./core/CustomerFreightEconomySystem.js";
import "./core/CustomerFreightDeliveryIntegration.js";
import "./core/CustomerOrderFreightPreviewIntegration.js";
import "./core/CustomerOrderProfitabilityIntegration.js";
import "./core/UniversalOperationsDialog.js";
import "./core/LandConstructionExpansionUIIntegration.js";
import "./core/WarehouseExpansionUIIntegration.js";
import "./core/ConstructionRuntimeCompletionIntegration.js";
import "./core/ExpansionRuntimeRegression.js";
import "./core/EconomyDashboardSetupIntegration.js";
import "./core/ConnectedEconomyGameplay.js";
import "./core/CustomerOrderCapacityByFleetIntegration.js";
import "./core/CustomerOrderCooldownUIIntegration.js";
import "./core/ReputationDashboardIntegration.js";
import "./core/UrgentCustomerOrderUIIntegration.js";
import "./core/LiveTrafficDeliveryIntegration.js";
import "./core/CustomerOrderPricingIntegration.js";
import "./core/CustomerFreightPricingUIIntegration.js";
import "./core/ProductionProgressIntegration.js";
import "./core/ProductionStockCreditRecoveryIntegration.js";
import "./core/ProductionDarkContrastIntegration.js";
import "./core/BottlingSizeSelectionIntegration.js";
import "./core/ProductionStatusBannerIntegration.js";
import "./core/MachineStaffingOverviewIntegration.js";
import "./core/MachineStaffingHireLinkIntegration.js";
import "./core/WorkforceMachineAssignmentIntegration.js";
import "./core/WorkforceAssignmentStatusIntegration.js";
import "./core/ProductionReadinessChecklistView.js";
import "./core/DashboardSummaryNavigationIntegration.js";
import "./core/DashboardFinishedGoodsSummaryIntegration.js";
import "./core/DashboardSummaryGradientIntegration.js";
import "./core/DashboardMainNavigationIntegration.js";
import "./core/OperationalDialogSectionPersistenceIntegration.js";
import "./core/OperationalDialogCloseGuardIntegration.js";
import "./core/BusinessPortfolioProductionUsabilityIntegration.js";
import "./core/BusinessQuickSwitcherIntegration.js";
import "./core/BusinessAttentionRouter.js";
import "./core/MachinePurchaseTabIntegration.js";
import "./core/WarehouseClearanceSaleIntegration.js";
import "./core/ProductionReadinessPremiumNavigationV2.js";
import "./core/ProductionQueueLimitIntegration.js";
import "./core/CommercialFulfillmentGameplayBridge.js";
import "./core/PlayerMarketDialog.js";
import "./core/VerticalIntegrationMarketUIIntegration.js";
import "./core/PlayerMarketGoodsDelivery.js";
import "./core/PlayerMarketDirectGoodsPurchase.js";
import "./core/PlayerMarketLocalPersistence.js";
import "./core/PlayerCoinMarketExchange.js";
import "./core/PlayerCoinMarketLocalPersistence.js";
import "./core/PlayerCoinMarketUIIntegration.js";
import "./core/AllianceExchangeSystem.js";
import "./core/PlayerMarketNavigationIntegration.js";
import "./core/PlayerMarketFleetBridgeIntegration.js";
import "./core/AdaptiveAiSupplyService.js";
import "./core/AdaptiveAiSupplyRuntimeIntegration.js";
import "./core/RegionalEconomyAdvisor.js";
import "./core/DashboardUsabilityIntegration.js";
import "./core/DashboardQuickActionsIntegration.js";
import "./core/DashboardPriorityHintsIntegration.js";
import "./core/DashboardFinanceLedgerIntegration.js";
import "./core/BusinessExpansionOperationalEffectsIntegration.js";
import "./core/LongDialogUsabilityIntegration.js";
import "./core/WarehouseSpaceRuntimeGuard.js";
import "./core/OperationalConsistencyGuard.js";
import "./core/GameActionFeedbackIntegration.js";
import "./core/OperationalAttentionFeedbackIntegration.js";
import "./core/GameActionFeedbackBridge.js";
import "./core/GameSaveStatusIntegration.js";
import "./core/ActiveOperationsOverviewUI.js";
import "./core/TimedBusinessUpgradeUI.js";
import "./core/RewardedAdUIIntegration.js";
import "./core/GameResumeRefreshIntegration.js";
import "./core/PremiumDailyCoinRuntimeIntegration.js";
import "./core/GameRuntimeErrorBoundary.js";
import "./core/GameFinishPolishRegression.js";
import "./core/PremiumPlanUIIntegration.js";
import "./core/PremiumExtraPackageUIIntegration.js";
import "./core/InGameAdminAccessIntegration.js";
import "./core/DeveloperSecondBusinessTestUnlock.js";
import "./core/BusinessPortfolioIsolationRegression.js";
import "./core/ConnectedIndustryEconomyRegression.js";
import "./core/SolarInvestmentUI.js";
import { runSolarInvestmentTest } from "./core/SolarInvestmentSystem.js";
import { runBusinessAttentionIndicatorTest } from "./core/BusinessAttentionIndicator.js";
import { runBusinessQuickSwitcherLogicTest } from "./core/BusinessQuickSwitcherIntegration.js";
import { runBusinessAttentionRouterTest } from "./core/BusinessAttentionRouter.js";
import { runBusinessPortfolioScaleRegression } from "./core/BusinessPortfolioScaleRegression.js";
import { runDevelopmentHealthPanelTest } from "./core/DevelopmentHealthPanel.js";
import { runMarketPriceAdvisorTest } from "./core/MarketPriceAdvisor.js";
import { runVerticalIntegrationAdvisorTest } from "./core/VerticalIntegrationAdvisor.js";
import { runVerticalIntegrationMarketUITest } from "./core/VerticalIntegrationMarketUIIntegration.js";
import { runIndustryChainPresentationTest } from "./core/IndustryChainPresentation.js";
import { runRegionalEconomyAdvisorTest } from "./core/RegionalEconomyAdvisor.js";
import "./core/CoreRegressionSuite.js";
import { runAllIndustryPlayabilityAudit } from "./core/AllIndustryPlayabilityAudit.js";
import { runAllIndustryEconomyHealth } from "./core/AllIndustryEconomyBootstrap.js";
import { gameAccessGate } from "./core/AccountMultiplayerIntegration.js";

function safeHealth(name,fn){try{return fn();}catch(error){console.error(`❌ HEALTH ${name}`,error);return{success:false,error:error?.message||String(error)};}}
async function startOrvuno(){
 await gameAccessGate.ensureAccess();console.log("✅ ORVUNO ACCOUNT FREIGEGEBEN – SPIEL WIRD GELADEN");
 window.worldSolarInvestmentHealth=safeHealth("Solar",runSolarInvestmentTest);window.worldBusinessAttentionHealth=safeHealth("Betriebsaufmerksamkeit",runBusinessAttentionIndicatorTest);window.worldBusinessQuickSwitcherHealth=safeHealth("Betriebswechsler",runBusinessQuickSwitcherLogicTest);window.worldBusinessAttentionRouterHealth=safeHealth("Aufmerksamkeitsrouter",runBusinessAttentionRouterTest);window.worldBusinessPortfolioScaleHealth=safeHealth("Mehrbetriebskalierung",runBusinessPortfolioScaleRegression);window.worldDevelopmentHealthPanelHealth=safeHealth("Health-Panel",runDevelopmentHealthPanelTest);window.worldMarketPriceAdvisorHealth=safeHealth("KI-Preisberater",runMarketPriceAdvisorTest);window.worldVerticalIntegrationHealth=safeHealth("Vertikale Integration",runVerticalIntegrationAdvisorTest);window.worldVerticalIntegrationMarketUIHealth=safeHealth("Vertikale Integration UI",runVerticalIntegrationMarketUITest);window.worldIndustryChainPresentationHealth=safeHealth("Lieferkettenanzeige",runIndustryChainPresentationTest);window.worldRegionalEconomyHealth=safeHealth("Regionalwirtschaft",runRegionalEconomyAdvisorTest);window.worldProjectIndustryHealth=safeHealth("Gewerbe-Spielbarkeit",runAllIndustryPlayabilityAudit);window.worldAllIndustryEconomyHealth=safeHealth("Gesamtwirtschaft",runAllIndustryEconomyHealth);await import("./main.js");
}
startOrvuno().catch(error=>{console.error("❌ ORVUNO SPIELSTART FEHLGESCHLAGEN",error);window.orvunoShowBootError?.(error?.message||String(error));});