// ORVUNO - sichtbare Supabase-Registrierung/Login
import { AuthApiClient } from "./AuthApiClient.js";

export class AccountAuthDialog {
    constructor({ accountSystem, api = new AuthApiClient(), parent = document.body, required = false, onAuthenticated = null } = {}) {this.accountSystem=accountSystem;this.api=api;this.parent=parent;this.overlay=null;this.backendOnline=false;this.currentUser=null;this.required=required;this.onAuthenticated=onAuthenticated;}
    el(tag,text=null){const e=document.createElement(tag);if(text!==null)e.textContent=text;return e;}
    input(type,placeholder){const i=this.el("input");i.type=type;i.placeholder=placeholder;Object.assign(i.style,{width:"100%",boxSizing:"border-box",padding:"14px 16px",margin:"7px 0 16px",borderRadius:"10px",border:"1px solid #465064",fontSize:"16px",background:"#111827",color:"#f8fafc",outline:"none"});return i;}
    button(text,onClick){const b=this.el("button",text);Object.assign(b.style,{padding:"13px 16px",border:"1px solid #465064",borderRadius:"10px",cursor:"pointer",fontWeight:"700",background:"#151e2f",color:"#f8fafc"});b.addEventListener("click",onClick);return b;}
    async detectBackend(){try{await this.api.health();this.backendOnline=true;}catch{this.backendOnline=false;}return this.backendOnline;}
    isMobile(){return window.matchMedia?.("(max-width: 760px)")?.matches||window.innerWidth<=760;}
    async open(mode="login"){
        if(this.overlay)return;
        await this.detectBackend();
        const mobile=this.isMobile();
        const overlay=this.el("div");
        Object.assign(overlay.style,{position:"fixed",inset:"0",zIndex:"20000",background:"radial-gradient(circle at 50% 15%,#17263d 0,#07101d 48%,#03070c 100%)",display:"flex",alignItems:mobile?"stretch":"center",justifyContent:"center",padding:mobile?"0":"28px",overflow:"auto",boxSizing:"border-box"});
        const shell=this.el("div");
        Object.assign(shell.style,mobile?{width:"100%",minHeight:"100dvh",display:"block",background:"#0c1422",border:"0",borderRadius:"0",overflow:"auto",boxShadow:"none",fontFamily:"Arial,sans-serif",color:"#fff"}:{width:"min(1420px,96vw)",minHeight:"min(820px,92vh)",display:"grid",gridTemplateColumns:"minmax(390px,.9fr) minmax(500px,1.1fr)",background:"#0c1422",border:"1px solid #394457",borderRadius:"24px",overflow:"hidden",boxShadow:"0 30px 100px rgba(0,0,0,.55)",fontFamily:"Arial,sans-serif",color:"#fff"});
        overlay.append(shell);this.parent.append(overlay);this.overlay=overlay;this.render(shell,mode);
    }
    close(){if(this.required&&!this.currentUser)return false;this.overlay?.remove();this.overlay=null;return true;}
    feature(icon,title,text){const row=this.el("div");Object.assign(row.style,{display:"grid",gridTemplateColumns:"52px 1fr",gap:"15px",margin:"25px 0"});const ico=this.el("div",icon);ico.style.fontSize="32px";const body=this.el("div"),h=this.el("strong",title),p=this.el("div",text);Object.assign(h.style,{display:"block",fontSize:"19px",color:"#f4bd43",marginBottom:"5px"});Object.assign(p.style,{fontSize:"15px",lineHeight:"1.5",color:"#dce3ed"});body.append(h,p);row.append(ico,body);return row;}
    renderBrand(shell){const left=this.el("section");Object.assign(left.style,{padding:"55px 62px",background:"linear-gradient(180deg,rgba(4,13,27,.78),rgba(5,16,31,.94)),radial-gradient(circle at 70% 70%,#263d5b,#06101d 65%)",borderRight:"1px solid #394457",display:"flex",flexDirection:"column"});const logo=this.el("div");const mark=this.el("div","◉");Object.assign(mark.style,{fontSize:"58px",color:"#f4bd43",fontWeight:"900"});const word=this.el("div");word.innerHTML='<b style="display:block;font-size:48px;line-height:1;letter-spacing:4px">ORVUNO</b><span style="display:block;margin-top:7px;color:#f4bd43;font-weight:800;letter-spacing:2px">ECONOMY SIMULATION</span>';Object.assign(logo.style,{display:"flex",alignItems:"center",gap:"18px",marginBottom:"22px"});logo.append(mark,word);const tag=this.el("div","Deine Welt. Deine Wirtschaft. Dein Erfolg.");Object.assign(tag.style,{fontSize:"20px",paddingBottom:"26px",borderBottom:"1px solid #314055"});left.append(logo,tag,this.feature("🏢","Dein Unternehmen","Baue Betriebe auf, optimiere Produktionen und entwickle deinen eigenen Konzern."),this.feature("📈","Echte Wirtschaft","Realistische Märkte, Lieferketten, Kosten und dynamische Preise."),this.feature("👥","Spielerwirtschaft","Handle und kooperiere mit anderen Spielern in einer verbundenen Wirtschaft."));const safe=this.el("div");Object.assign(safe.style,{marginTop:"auto",paddingTop:"20px",borderTop:"1px solid #314055"});safe.append(this.feature("🛡️","Sicher & Fair","Accountbasierter Spielstand und servergestützte Wirtschaft für ein faires Spielerlebnis."));left.append(safe);shell.append(left);}
    render(shell,mode="login"){
        shell.innerHTML="";
        const mobile=this.isMobile();
        if(!mobile)this.renderBrand(shell);
        const panel=this.el("section");
        Object.assign(panel.style,mobile?{minHeight:"100dvh",padding:"max(28px,env(safe-area-inset-top)) 22px max(28px,env(safe-area-inset-bottom))",display:"flex",flexDirection:"column",justifyContent:"center",background:"linear-gradient(160deg,#101a2b,#07101d)",boxSizing:"border-box"}:{padding:"62px 70px",display:"flex",flexDirection:"column",justifyContent:"center",background:"linear-gradient(135deg,#111a2a,#0c1422)"});
        if(mobile){
            const brand=this.el("div");
            brand.innerHTML='<div style="font-size:34px;font-weight:900;letter-spacing:3px">ORVUNO</div><div style="margin-top:5px;color:#f4bd43;font-size:12px;font-weight:800;letter-spacing:1.5px">ECONOMY SIMULATION</div>';
            Object.assign(brand.style,{textAlign:"center",marginBottom:"34px"});
            panel.append(brand);
        }
        const title=this.el("h1",mode==="login"?"👤  Anmelden":"👤  Registrieren");Object.assign(title.style,{margin:"0 0 8px",fontSize:mobile?"30px":"36px",textAlign:mobile?"center":"left"});
        const sub=this.el("div",mode==="login"?"Melde dich bei ORVUNO an":"Erstelle deinen ORVUNO-Account");Object.assign(sub.style,{color:"#aab4c5",fontSize:mobile?"16px":"18px",marginBottom:"25px",textAlign:mobile?"center":"left"});panel.append(title,sub);
        const status=this.el("div",this.backendOnline?"●  Spielserver verbunden":"●  Spielserver nicht erreichbar – Spielstart bleibt gesperrt");Object.assign(status.style,{padding:"14px 16px",borderRadius:"10px",border:`1px solid ${this.backendOnline?'#21663f':'#8b3030'}`,background:this.backendOnline?'rgba(21,92,55,.18)':'rgba(130,35,35,.18)',color:this.backendOnline?'#55df85':'#ff8585',fontWeight:"700",marginBottom:"24px",fontSize:mobile?"14px":"16px"});panel.append(status);
        if(mode==="login")this.renderLogin(panel);else this.renderRegister(panel);
        const divider=this.el("div","oder");Object.assign(divider.style,{textAlign:"center",color:"#9ba6b8",margin:"18px 0"});panel.append(divider);
        const switcher=this.button(mode==="login"?"Noch keinen Account? Registrieren":"Schon registriert? Anmelden",()=>this.render(shell,mode==="login"?"register":"login"));Object.assign(switcher.style,{width:"100%",borderColor:"#376bff",color:"#9cc0ff",background:"transparent"});panel.append(switcher);shell.append(panel);
    }
    async authenticated(user){this.currentUser=user;window.worldCurrentUser=user;if(this.onAuthenticated)await this.onAuthenticated(user);this.overlay?.remove();this.overlay=null;window.dispatchEvent(new CustomEvent("world:user-login",{detail:{user}}));}
    renderLogin(panel){const label1=this.el("strong","E-Mail-Adresse");const email=this.input("email","name@beispiel.de");const label2=this.el("strong","Passwort");const password=this.input("password","Dein Passwort");panel.append(label1,email,label2,password);const login=this.button("Anmelden",async()=>{try{if(!this.backendOnline)throw new Error("Der Spielserver ist derzeit nicht erreichbar.");const result=await this.api.login({email:email.value.trim(),password:password.value});if(["restricted","suspended","banned"].includes(result.user.status))throw new Error("Dieser Account ist derzeit nicht zum Spielen freigegeben.");if(result.user.status!=="active")throw new Error("Bitte zuerst deine E-Mail-Adresse bestätigen.");await this.authenticated(result.user);}catch(error){alert(error.message);}});Object.assign(login.style,{width:"100%",marginTop:"5px",background:"#3868ee",borderColor:"#4b78ff",color:"#fff",fontSize:"16px"});panel.append(login);const helpers=this.el("div");Object.assign(helpers.style,{display:"flex",gap:"8px",flexWrap:"wrap",marginTop:"10px"});const reset=this.button("Passwort vergessen",async()=>{try{if(!email.value.trim())throw new Error("Bitte zuerst die E-Mail-Adresse eingeben.");await this.api.requestPasswordReset(email.value.trim());alert("Wenn der Account existiert, wurde eine Reset-Mail versendet.");}catch(e){alert(e.message);}});const resend=this.button("Bestätigungsmail erneut senden",async()=>{try{if(!email.value.trim())throw new Error("Bitte zuerst die E-Mail-Adresse eingeben.");await this.api.resendVerification(email.value.trim());alert("Bestätigungsmail wurde erneut angefordert.");}catch(e){alert(e.message);}});helpers.append(reset,resend);panel.append(helpers);}
    renderRegister(panel){const username=this.input("text","Benutzername");const email=this.input("email","E-Mail-Adresse");const password=this.input("password","Passwort (mind. 10 Zeichen)");const country=this.input("text","Land (z. B. DE)");country.value="DE";const terms=this.el("label"),termsBox=this.input("checkbox","");termsBox.style.width="auto";terms.append(termsBox,document.createTextNode(" AGB akzeptieren"));const privacy=this.el("label"),privacyBox=this.input("checkbox","");privacyBox.style.width="auto";privacy.append(privacyBox,document.createTextNode(" Datenschutzerklärung akzeptieren"));panel.append(username,email,password,country,terms,privacy);const register=this.button("ORVUNO-Account erstellen",async()=>{try{if(!this.backendOnline)throw new Error("Der Spielserver ist derzeit nicht erreichbar.");if(!termsBox.checked||!privacyBox.checked)throw new Error("AGB und Datenschutzerklärung müssen akzeptiert werden.");if(username.value.trim().length<3)throw new Error("Benutzername muss mindestens 3 Zeichen haben.");if(password.value.length<10)throw new Error("Passwort muss mindestens 10 Zeichen haben.");const result=await this.api.register({username:username.value.trim(),email:email.value.trim(),password:password.value,countryCode:country.value||"DE",languageCode:"de",termsAccepted:true,privacyAccepted:true});if(result.session){const user=await this.api.me();await this.authenticated(user);return;}alert("Account erstellt. Bitte bestätige jetzt die E-Mail. Erst danach kannst du ORVUNO spielen.");this.render(panel,"login");}catch(error){alert(error.message);}});Object.assign(register.style,{width:"100%",marginTop:"12px",background:"#3868ee",borderColor:"#4b78ff"});panel.append(register);}
}
