// WorldProject – kompakte UI fuer alle laufenden Aktivitaeten.
import { activeOperationsSummary } from './ActiveOperationsOverview.js';
import { businessReadiness, nextBusinessReadinessStep } from './BusinessReadinessCenter.js';
import { humanStatus } from './HumanReadableStatus.js';
import { operationalHealth } from './OperationalConsistencyGuard.js';
import { transportTimeReductionQuote, reduceTransportTimeWithCoins } from './TransportCoinTimeReductionSystem.js';
import { customerDeliveryEconomics } from './CustomerFreightEconomySystem.js';
import { reputationSummary } from './ReputationSystem.js';
import { worldContentRegistry } from './ContentRegistry.js';
const labels={production:'🏭 Produktion',delivery:'🚚 Lieferung',construction:'🏗️ Bau',land:'🌍 Grundstück',warehouse_expansion:'🏬 Lagerausbau',machine_upgrade:'🔧 Maschinenupgrade',business_upgrade:'⚙️ Betriebsausbau',customer_order:'📦 Kundenauftrag'};
const mins=ms=>{if(ms===null||ms===undefined)return'—';let m=Math.max(0,Math.ceil(ms/60000));return m>=1440?`${Math.floor(m/1440)} T ${Math.ceil((m%1440)/60)} Std.`:m>=60?`${Math.floor(m/60)} Std. ${m%60} Min.`:`${m} Min.`;};
const money=v=>Number(v||0).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
const num=v=>Number(v||0).toLocaleString('de-DE',{maximumFractionDigits:2});
function company(){return window.worldPlayerCompany||window.worldEconomyGameplay?.company||window.worldEngine?.company||null;}
function close(){document.querySelector('[data-world-active-operations-overlay]')?.remove();}
function productLabel(id){if(!id)return'Unbekannte Ware';const x=worldContentRegistry.get('products',id)||worldContentRegistry.get('materials',id);return x?.label||x?.name||String(id).replace(/_/g,' ');}
function customerName(o={}){if(typeof o.customer==='string'&&o.customer.trim())return o.customer;return o.customer?.name||o.customerName||o.clientName||o.buyerName||o.recipientName||'Geschäftskunde';}
function orderProductId(o={}){return o.productId||o.product||o.itemId||o.material||null;}
function orderQuantity(o={}){return Math.max(0,Number(o.remainingQuantity??o.remaining??o.quantity??o.amount??0)||0);}
function urgentOrder(o={}){return Boolean(o.urgent||o.isUrgent||o.priority==='urgent'||String(o.type||o.orderType||'').toLowerCase().includes('urgent')||String(o.type||o.orderType||'').toLowerCase().includes('eil'));}
function deadlineMs(o={}){const v=o.dueAt??o.deliveryDeadline??o.deadline??o.expiresAt;if(v==null)return 0;const direct=Number(v);if(Number.isFinite(direct)&&direct>0)return direct;const parsed=Date.parse(v);return Number.isFinite(parsed)?parsed:0;}
function reputationReward(o={}){const v=Number(o.reputationReward??o.reputationPoints??o.reputationBonus??o.rufBonus);return Number.isFinite(v)&&v!==0?v:null;}
function detailFor(r){if(r.kind!=='business_upgrade')return'';const j=r.raw||{},helpers=Array.isArray(j.helpers)?j.helpers.length:0,max=Number(j.maxHelpers||0),phase=window.worldAccounts?.businessUpgrades?.phase?.(j)||'Umbauarbeiten laufen';return `<br><small>Aktuell: <b>${phase}</b>${max?` · Freundeshilfe ${helpers}/${max}`:''}</small>`;}
function applyFilter(box,kind=null){for(const row of box.querySelectorAll('[data-operation-kind]'))row.style.display=!kind||row.dataset.operationKind===kind?'':'none';for(const chip of box.querySelectorAll('[data-operation-filter]')){const active=(chip.dataset.operationFilter||'')===(kind||'');chip.setAttribute('aria-pressed',active?'true':'false');chip.style.outline=active?'2px solid #0f172a':'';chip.style.background=active?'#e2e8f0':'#f8fafc';}}
function actionButton(text,fn){const b=document.createElement('button');b.textContent=text;Object.assign(b.style,{padding:'7px 10px',borderRadius:'7px',border:'1px solid #64748b',background:'#1e293b',color:'#fff',fontWeight:'700',cursor:'pointer'});b.onclick=fn;return b;}
function openProduction(){close();const top=document.getElementById('world-production-button');if(top){top.click();return;}const d=window.worldOperationalSupplyChainDialog;if(d?.open){d.__worldFocusedSection='production';d.open();return;}alert('Produktionsbereich ist derzeit nicht verfügbar.');}
function openFleetCustomers(){close();const d=window.worldAccounts?.marketFleetDialog;if(d?.open){d.open();return;}document.querySelector('[data-world-market-fleet-button]')?.click?.();}
function appendCustomerOrderCard(row,r,c){
 const o=r.raw||{},pid=orderProductId(o),qty=orderQuantity(o),urgent=urgentOrder(o),deadline=deadlineMs(o),rep=reputationReward(o),currentRep=reputationSummary(c||{}),econ=customerDeliveryEconomics(c||{},o,{quantity:qty||1,urgent});
 row.innerHTML='';row.dataset.customerOrderCard='1';Object.assign(row.style,{border:urgent?'2px solid #f59e0b':'1px solid #64748b',background:urgent?'#2a1f0b':'#111827',color:'#f8fafc',padding:'14px'});
 const title=document.createElement('div');title.innerHTML=`<b style="font-size:17px">${urgent?'⚡ EILAUFTRAG':'📦 Kundenauftrag'} – ${customerName(o)}</b>`;row.append(title);
 const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:'6px 18px',marginTop:'10px',lineHeight:'1.45'});
 const entries=[
  ['Ware',productLabel(pid)],
  ['Menge',qty>0?`${num(qty)} Einheiten`:'nicht angegeben'],
  ['Entfernung',`${num(econ.distanceKm)} km`],
  ['Status',humanStatus(o.status||r.status)]
 ];
 if(econ.revenue>0)entries.push(['Auftragswert',money(econ.revenue)]);
 if(econ.external?.cost>0)entries.push(['Fremdspedition',`${money(econ.external.cost)} · ${econ.external.provider}`]);
 if(econ.own?.cost>0)entries.push(['Mit eigenem Fahrzeug',`${money(econ.own.cost)} Transportkosten`]);
 if(econ.own&&econ.savingWithOwnFleet>0)entries.push(['Ersparnis eigener Fuhrpark',money(econ.savingWithOwnFleet)]);
 if(econ.revenue>0&&Number.isFinite(econ.externalProfit))entries.push(['Gewinn nach Fremdtransport',money(econ.externalProfit)]);
 if(econ.own&&econ.revenue>0&&Number.isFinite(econ.ownProfit))entries.push(['Gewinn mit eigenem Fahrzeug',money(econ.ownProfit)]);
 if(deadline)entries.push(['Lieferfrist',deadline>Date.now()?`noch ${mins(deadline-Date.now())}`:'⚠️ überfällig']);
 if(rep!==null)entries.push(['Ruf bei Erfolg',`${rep>0?'+':''}${rep} Punkte`]);
 entries.push(['Aktueller Firmenruf',`${currentRep.score}/100 · ${currentRep.level.label}`]);
 for(const [k,v] of entries){const cell=document.createElement('div');cell.innerHTML=`<span style="color:#94a3b8">${k}:</span> <b>${v}</b>`;grid.append(cell);}row.append(grid);
 const hint=document.createElement('div');Object.assign(hint.style,{marginTop:'10px',padding:'8px 10px',borderRadius:'7px',background:'#0f172a',color:'#cbd5e1'});if(qty<=0)hint.textContent='⚠️ Für diesen Altauftrag fehlt noch eine Mengenangabe.';else if(econ.own)hint.textContent=`🚚 Eigener Fuhrpark verfügbar. Gegenüber der Fremdspedition sparst du bei diesem Auftrag ${money(econ.savingWithOwnFleet)}.`;else hint.textContent=`🚚 Ohne eigenes verfügbares Fahrzeug übernimmt die ${econ.external.provider} die Lieferung für ${money(econ.external.cost)}.`;row.append(hint);
 const actions=document.createElement('div');Object.assign(actions.style,{display:'flex',gap:'8px',flexWrap:'wrap',marginTop:'11px'});actions.append(actionButton('🏭 Produktion öffnen',openProduction),actionButton('🚚 Fuhrpark & Kunden',openFleetCustomers));row.append(actions);
}
function appendTransportCoinControl(row,r,c,rerender){if(r.kind!=='delivery'||!r.raw||r.remainingMs===null||r.remainingMs<=0)return;let q;try{q=transportTimeReductionQuote(c,r.raw,1);}catch{return;}const wrap=document.createElement('div');Object.assign(wrap.style,{display:'flex',gap:'7px',alignItems:'center',flexWrap:'wrap',marginTop:'8px',paddingTop:'8px',borderTop:'1px solid #e5e7eb'});const info=document.createElement('small');info.textContent=`🪙 Transport beschleunigen · Guthaben ${Number(c.coins||0)} Coins`;const select=document.createElement('select');Object.assign(select.style,{padding:'5px 7px',borderRadius:'6px'});const max=Math.max(1,Math.min(10,Math.ceil(r.remainingMs/3600000)));for(let h=1;h<=max;h++){const quote=transportTimeReductionQuote(c,r.raw,h),o=document.createElement('option');o.value=String(h);o.textContent=`bis ${h} Std. · ${quote.cost} Coins`;select.append(o);}const button=document.createElement('button');button.textContent='Beschleunigen';Object.assign(button.style,{padding:'6px 9px',borderRadius:'6px',border:'1px solid #9ca3af',cursor:'pointer'});const refresh=()=>{try{const quote=transportTimeReductionQuote(c,r.raw,Number(select.value));button.disabled=Number(c.coins||0)<quote.cost;button.title=`Neue Restzeit ca. ${mins(quote.newArrivalMs-Date.now())}`;}catch{button.disabled=true;}};select.onchange=refresh;button.onclick=()=>{try{const quote=transportTimeReductionQuote(c,r.raw,Number(select.value));const actual=(quote.reductionMs/3600000).toLocaleString('de-DE',{maximumFractionDigits:1});if(!confirm(`${quote.cost} Coins einsetzen und diese Lieferung um ${actual} Stunde${quote.reductionMs===3600000?'':'n'} beschleunigen?`))return;reduceTransportTimeWithCoins(c,r.raw,Number(select.value));rerender();}catch(e){alert(e.message);}};wrap.append(info,select,button);row.append(wrap);refresh();}
export function openActiveOperations(){
 if(typeof document==='undefined')return;close();const c=company(),s=activeOperationsSummary(c||{}),health=operationalHealth(c||{}),ready=businessReadiness(c||{}),next=nextBusinessReadinessStep(c||{}),overlay=document.createElement('div');overlay.dataset.worldActiveOperationsOverlay='1';Object.assign(overlay.style,{position:'fixed',inset:'0',zIndex:62000,background:'rgba(0,0,0,.58)',display:'grid',placeItems:'center',padding:'20px'});const box=document.createElement('section');Object.assign(box.style,{width:'min(900px,96vw)',maxHeight:'86vh',overflow:'auto',background:'#fff',color:'#111827',borderRadius:'14px',padding:'18px',boxShadow:'0 18px 50px rgba(0,0,0,.45)'});const head=document.createElement('div');Object.assign(head.style,{display:'flex',justifyContent:'space-between',alignItems:'center',position:'sticky',top:'-18px',background:'#fff',padding:'14px 0',zIndex:'2'});head.innerHTML=`<div><h2 style="margin:0">📋 Betrieb im Überblick</h2><small>${s.total} offene/laufende Vorgänge · nach Restzeit sortiert</small></div>`;const x=document.createElement('button');x.textContent='✕';x.title='Schließen';Object.assign(x.style,{fontSize:'20px',padding:'6px 11px'});x.onclick=close;head.append(x);box.append(head);
 if(health.attentionCount||health.maintenanceDue.length||health.maintenanceVehicles.length){const attention=document.createElement('div');Object.assign(attention.style,{padding:'10px 12px',border:'1px solid #f59e0b',background:'#fff7ed',borderRadius:'10px',marginBottom:'12px'});const parts=[];if(health.overdue.length)parts.push(`⏰ ${health.overdue.length} über Endzeit`);if(health.lateCustomers.length)parts.push(`🧾 ${health.lateCustomers.length} Kundenauftrag überfällig`);if(health.criticalMachines.length)parts.push(`🛠️ ${health.criticalMachines.length} Maschine kritisch`);if(health.maintenanceDue.length)parts.push(`🔧 ${health.maintenanceDue.length} Maschine bald warten`);if(health.criticalVehicles.length)parts.push(`🚛 ${health.criticalVehicles.length} Fahrzeug kritisch`);if(health.maintenanceVehicles.length)parts.push(`🔩 ${health.maintenanceVehicles.length} Fahrzeug bald warten`);attention.innerHTML=`<b>⚠️ Aufmerksamkeit nötig</b><br><small>${parts.join(' · ')}</small>`;box.append(attention);}
 const readiness=document.createElement('div');Object.assign(readiness.style,{padding:'12px',border:`1px solid ${ready.ready?'#86efac':'#f59e0b'}`,background:ready.ready?'#f0fdf4':'#fffbeb',borderRadius:'10px',marginBottom:'12px'});readiness.innerHTML=`<b>${ready.ready?'✅':'🧭'} Betriebsbereitschaft: ${ready.score}%</b>${next?`<br><span>Nächster sinnvoller Schritt: <b>${next.label}</b>${next.hint?` – ${next.hint}`:''}</span>`:'<br><span>Alle grundlegenden Voraussetzungen sind erfüllt.</span>'}`;if(ready.blockers.length){const details=document.createElement('details');details.innerHTML=`<summary>${ready.blockers.length} offene Voraussetzung${ready.blockers.length===1?'':'en'} anzeigen</summary>${ready.blockers.map(r=>`<div style="padding:5px 0">❌ <b>${r.label}</b>${r.hint?` – ${r.hint}`:''}</div>`).join('')}`;readiness.append(details);}box.append(readiness);
 const quick=document.createElement('div');Object.assign(quick.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:'8px',margin:'0 0 14px'});if(s.total){const all=document.createElement('button');all.dataset.operationFilter='';all.innerHTML=`<b>📋 Alle</b><br><small>${s.total} aktiv</small>`;Object.assign(all.style,{padding:'8px 10px',border:'1px solid #d1d5db',borderRadius:'9px',background:'#e2e8f0',textAlign:'left',cursor:'pointer',color:'#111827'});all.onclick=()=>applyFilter(box,null);quick.append(all);}for(const [kind,label] of Object.entries(labels)){const count=s.byType[kind]||0;if(!count)continue;const chip=document.createElement('button');chip.dataset.operationFilter=kind;chip.innerHTML=`<b>${label}</b><br><small>${count} aktiv</small>`;Object.assign(chip.style,{padding:'8px 10px',border:'1px solid #d1d5db',borderRadius:'9px',background:'#f8fafc',textAlign:'left',cursor:'pointer',color:'#111827'});chip.onclick=()=>applyFilter(box,kind);quick.append(chip);}if(quick.children.length)box.append(quick);
 const title=document.createElement('h3');title.textContent='Laufende & offene Vorgänge';box.append(title);if(!s.rows.length){box.insertAdjacentHTML('beforeend','<p>✅ Zurzeit läuft nichts und es sind keine offenen Vorgänge vorhanden.</p>');}for(const r of s.rows){const row=document.createElement('div');row.dataset.operationKind=r.kind;Object.assign(row.style,{border:'1px solid #d1d5db',borderRadius:'10px',padding:'10px 12px',margin:'8px 0'});if(r.kind==='customer_order'){appendCustomerOrderCard(row,r,c||{});box.append(row);continue;}const pct=r.progress===null?'':` · <b>${r.progress}%</b>`;row.innerHTML=`<b>${labels[r.kind]||'ℹ️ Vorgang'}: ${String(r.label)}</b><br><span>Status: ${humanStatus(r.status)}${pct}</span>${r.remainingMs!==null?`<br><small>Voraussichtlich noch ${mins(r.remainingMs)}</small>`:''}${detailFor(r)}`;window.worldRewardedAdUI?.appendTimeControl?.(row,r);appendTransportCoinControl(row,r,c||{},openActiveOperations);box.append(row);}overlay.append(box);overlay.onclick=e=>{if(e.target===overlay)close();};document.body.append(overlay);
}
export function installActiveOperationsButton(){if(typeof document==='undefined')return false;let b=document.querySelector('[data-world-active-operations-button]');if(b)return true;b=document.createElement('button');b.dataset.worldActiveOperationsButton='1';b.textContent='📋 Läuft gerade';Object.assign(b.style,{position:'fixed',left:'16px',bottom:'16px',zIndex:44000,padding:'8px 12px',borderRadius:'999px',border:'1px solid #475569',background:'#0f172a',color:'#fff',fontWeight:'800'});b.onclick=openActiveOperations;document.body.append(b);const update=()=>{const c=company()||{},summary=activeOperationsSummary(c),ready=businessReadiness(c),health=operationalHealth(c),next=summary.next;b.textContent=`📋 Betrieb${summary.total?` · ${summary.total} offen`:''}${health.attentionCount?` · ⚠️ ${health.attentionCount}`:''}${next?.remainingMs!==null&&next?.remainingMs!==undefined?` · nächstes ${mins(next.remainingMs)}`:''}${!ready.ready?` · ${ready.score}%`:''}`;};for(const ev of ['world:game-state-dirty','world:construction-completed','worldproject:company-switched','world:business-upgrade-started','world:business-upgrade-completed','world:rewarded-ad-updated','world:runtime-resumed'])window.addEventListener(ev,update);setInterval(update,15000);update();return true;}
export function runActiveOperationsUIFilterTest(){const host=document?.createElement?.('div');if(!host)return true;host.innerHTML='<div data-operation-kind="production"></div><div data-operation-kind="delivery"></div><button data-operation-filter="production"></button>';applyFilter(host,'production');if(host.querySelector('[data-operation-kind="delivery"]').style.display!=='none')throw new Error('Vorgangsfilter fehlerhaft');return true;}
if(typeof window!=='undefined'){window.worldActiveOperationsUI={open:openActiveOperations,install:installActiveOperationsButton,runFilterTest:runActiveOperationsUIFilterTest};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installActiveOperationsButton);else installActiveOperationsButton();}
