// WorldProject – kompakte UI fuer alle laufenden Aktivitaeten.
import { activeOperationsSummary } from './ActiveOperationsOverview.js';
import { businessReadiness, nextBusinessReadinessStep } from './BusinessReadinessCenter.js';
import { humanStatus } from './HumanReadableStatus.js';
const labels={production:'🏭 Produktion',delivery:'🚚 Lieferung',construction:'🏗️ Bau',land:'🌍 Grundstück',warehouse_expansion:'🏬 Lagerausbau',machine_upgrade:'🔧 Maschinenupgrade',business_upgrade:'⚙️ Betriebsausbau',customer_order:'📦 Kundenauftrag'};
const mins=ms=>{if(ms===null||ms===undefined)return'—';let m=Math.max(0,Math.ceil(ms/60000));return m>=1440?`${Math.floor(m/1440)} T ${Math.ceil((m%1440)/60)} Std.`:m>=60?`${Math.floor(m/60)} Std. ${m%60} Min.`:`${m} Min.`;};
function company(){return window.worldPlayerCompany||window.worldEconomyGameplay?.company||window.worldEngine?.company||null;}
function close(){document.querySelector('[data-world-active-operations-overlay]')?.remove();}
function detailFor(r){if(r.kind!=='business_upgrade')return'';const j=r.raw||{},helpers=Array.isArray(j.helpers)?j.helpers.length:0,max=Number(j.maxHelpers||0),phase=window.worldAccounts?.businessUpgrades?.phase?.(j)||'Umbauarbeiten laufen';return `<br><small>Aktuell: <b>${phase}</b>${max?` · Freundeshilfe ${helpers}/${max}`:''}</small>`;}
export function openActiveOperations(){
 if(typeof document==='undefined')return;close();const c=company(),s=activeOperationsSummary(c||{}),ready=businessReadiness(c||{}),next=nextBusinessReadinessStep(c||{}),overlay=document.createElement('div');overlay.dataset.worldActiveOperationsOverlay='1';Object.assign(overlay.style,{position:'fixed',inset:'0',zIndex:62000,background:'rgba(0,0,0,.58)',display:'grid',placeItems:'center',padding:'20px'});const box=document.createElement('section');Object.assign(box.style,{width:'min(820px,96vw)',maxHeight:'86vh',overflow:'auto',background:'#fff',color:'#111827',borderRadius:'14px',padding:'18px',boxShadow:'0 18px 50px rgba(0,0,0,.45)'});const head=document.createElement('div');Object.assign(head.style,{display:'flex',justifyContent:'space-between',alignItems:'center',position:'sticky',top:'-18px',background:'#fff',padding:'14px 0',zIndex:'2'});head.innerHTML=`<div><h2 style="margin:0">📋 Betrieb im Überblick</h2><small>${s.total} offene/laufende Vorgänge · nach Restzeit sortiert</small></div>`;const x=document.createElement('button');x.textContent='✕';x.title='Schließen';Object.assign(x.style,{fontSize:'20px',padding:'6px 11px'});x.onclick=close;head.append(x);box.append(head);
 const readiness=document.createElement('div');Object.assign(readiness.style,{padding:'12px',border:`1px solid ${ready.ready?'#86efac':'#f59e0b'}`,background:ready.ready?'#f0fdf4':'#fffbeb',borderRadius:'10px',marginBottom:'12px'});readiness.innerHTML=`<b>${ready.ready?'✅':'🧭'} Betriebsbereitschaft: ${ready.score}%</b>${next?`<br><span>Nächster sinnvoller Schritt: <b>${next.label}</b>${next.hint?` – ${next.hint}`:''}</span>`:'<br><span>Alle grundlegenden Voraussetzungen sind erfüllt.</span>'}`;if(ready.blockers.length){const details=document.createElement('details');details.innerHTML=`<summary>${ready.blockers.length} offene Voraussetzung${ready.blockers.length===1?'':'en'} anzeigen</summary>${ready.blockers.map(r=>`<div style="padding:5px 0">❌ <b>${r.label}</b>${r.hint?` – ${r.hint}`:''}</div>`).join('')}`;readiness.append(details);}box.append(readiness);
 const quick=document.createElement('div');Object.assign(quick.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'8px',margin:'0 0 14px'});for(const [kind,label] of Object.entries(labels)){const count=s.byType[kind]||0;if(!count)continue;const chip=document.createElement('div');chip.innerHTML=`<b>${label}</b><br><small>${count} aktiv</small>`;Object.assign(chip.style,{padding:'8px 10px',border:'1px solid #d1d5db',borderRadius:'9px',background:'#f8fafc'});quick.append(chip);}if(quick.children.length)box.append(quick);
 const title=document.createElement('h3');title.textContent='Laufende & offene Vorgänge';box.append(title);if(!s.rows.length){box.insertAdjacentHTML('beforeend','<p>✅ Zurzeit läuft nichts und es sind keine offenen Vorgänge vorhanden.</p>');}for(const r of s.rows){const row=document.createElement('div');Object.assign(row.style,{border:'1px solid #d1d5db',borderRadius:'10px',padding:'10px 12px',margin:'8px 0'});const pct=r.progress===null?'':` · <b>${r.progress}%</b>`;row.innerHTML=`<b>${labels[r.kind]||'ℹ️ Vorgang'}: ${String(r.label)}</b><br><span>Status: ${humanStatus(r.status)}${pct}</span>${r.remainingMs!==null?`<br><small>Voraussichtlich noch ${mins(r.remainingMs)}</small>`:''}${detailFor(r)}`;box.append(row);}overlay.append(box);overlay.onclick=e=>{if(e.target===overlay)close();};document.body.append(overlay);
}
export function installActiveOperationsButton(){if(typeof document==='undefined')return false;let b=document.querySelector('[data-world-active-operations-button]');if(b)return true;b=document.createElement('button');b.dataset.worldActiveOperationsButton='1';b.textContent='📋 Läuft gerade';Object.assign(b.style,{position:'fixed',left:'16px',bottom:'16px',zIndex:44000,padding:'8px 12px',borderRadius:'999px',border:'1px solid #475569',background:'#0f172a',color:'#fff',fontWeight:'800'});b.onclick=openActiveOperations;document.body.append(b);const update=()=>{const c=company()||{},summary=activeOperationsSummary(c),ready=businessReadiness(c),next=summary.next;b.textContent=`📋 Betrieb${summary.total?` · ${summary.total} offen`:''}${next?.remainingMs!==null&&next?.remainingMs!==undefined?` · nächstes ${mins(next.remainingMs)}`:''}${!ready.ready?` · ${ready.score}%`:''}`;};for(const ev of ['world:game-state-dirty','world:construction-completed','worldproject:company-switched','world:business-upgrade-started','world:business-upgrade-completed'])window.addEventListener(ev,update);setInterval(update,15000);update();return true;}
if(typeof window!=='undefined'){window.worldActiveOperationsUI={open:openActiveOperations,install:installActiveOperationsButton};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installActiveOperationsButton);else installActiveOperationsButton();}
