// WorldProject - KI-Angebote ziehen sich pro Ware und Region zurueck, sobald Spieler die Versorgung tragen.
// Die KI bleibt Sicherheitsnetz und kehrt automatisch zurueck, wenn Menge/Anbieterzahl/Zuverlaessigkeit absinken.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const open=o=>o?.side==="sell"&&["open","partial","active"].includes(o.status)&&n(o.remaining??o.quantity)>0;
const companyId=c=>String(c?.serverCompanyId??c?.id??"");
const regionOf=c=>c?.regionId??c?.region_id??c?.location?.regionId??c?.location?.region??null;
const coords=c=>{const x=c?.location||c;const lat=Number(x?.lat??x?.latitude),lon=Number(x?.lng??x?.lon??x?.longitude);return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon}:null;};
const distanceKm=(a,b)=>{const x=coords(a),y=coords(b);if(!x||!y)return null;const rad=v=>v*Math.PI/180,dLat=rad(y.lat-x.lat),dLon=rad(y.lon-x.lon),q=Math.sin(dLat/2)**2+Math.cos(rad(x.lat))*Math.cos(rad(y.lat))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));};
export const SUPPLY_ALIASES={malt_kg:"malt",hops_kg:"hops",yeast_kg:"yeast",water_l:"water",bottle_033:"bottles",bottle_050:"bottles_050",crown_cap:"caps",label_033:"labels",label_050:"labels_050",timber_spruce_m3:"softwood",timber_oak_m3:"hardwood",board_mdf_m2:"plywood",glue_kg:"glue",fittings_set:"screws",flour:"flour_wheat",spices:"spice_mix"};
export const canonicalSupplyId=id=>SUPPLY_ALIASES[id]||id;
const baselineFor=id=>{id=canonicalSupplyId(id);if(["bottles","bottles_050","caps","labels","labels_050","bakery_bag","meat_packaging"].includes(id))return 10000;if(["malt","flour_wheat","wheat","barley","sugar","animal_feed","fertilizer","steel_sheet","plastic_granulate"].includes(id))return 750;if(["hops","yeast","citric_acid","beverage_flavour"].includes(id))return 100;if(["softwood","hardwood","roundwood_soft","roundwood_hard"].includes(id))return 20;return 250;};

export class AdaptiveAiSupplyService{
 constructor({minPlayerSuppliers=2,coverageFactor=1.20,maxDistanceKm=250,minReliability=.80}={}){this.minPlayerSuppliers=minPlayerSuppliers;this.coverageFactor=coverageFactor;this.maxDistanceKm=maxDistanceKm;this.minReliability=minReliability;}
 nearbyPlayerOrders(itemId,buyer,orders=[]){const wanted=canonicalSupplyId(itemId),buyerRegion=regionOf(buyer),self=companyId(buyer);return orders.filter(o=>{if(!open(o)||canonicalSupplyId(o.productId??o.item)!==wanted)return false;if(self&&String(o.companyId)===self)return false;const seller=o.companyRef||o.sellerCompany||{},sellerRegion=regionOf(seller);if(buyerRegion&&sellerRegion&&String(buyerRegion)!==String(sellerRegion))return false;const km=n(o.distanceKm,NaN),geo=distanceKm(buyer,seller),distance=Number.isFinite(km)?km:geo;if(Number.isFinite(distance)&&distance>this.maxDistanceKm)return false;const reliability=n(o.reliability??seller.reliability??seller.reputation?.reliability,1);return reliability>=this.minReliability;});}
 evaluate(itemId,{buyer=null,orders=[],demand=0}={}){const playerOrders=this.nearbyPlayerOrders(itemId,buyer,orders),supplierIds=new Set(playerOrders.map(o=>String(o.companyId??o.sellerCompanyId??o.id))),playerQuantity=playerOrders.reduce((sum,o)=>sum+Math.max(0,n(o.remaining??o.quantity)),0),required=Math.max(baselineFor(itemId),Math.max(0,n(demand))*this.coverageFactor),supplierCount=supplierIds.size,coverage=required>0?playerQuantity/required:0,playerOnly=supplierCount>=this.minPlayerSuppliers&&playerQuantity>=required;return{itemId:canonicalSupplyId(itemId),supplierCount,playerQuantity,requiredQuantity:required,coverage,playerOnly,aiMode:playerOnly?"withdrawn":playerQuantity>0?"fallback":"primary",playerOrders};}
 filterAiSupplier(supplier,{buyer=null,orders=[],demandByItem={}}={}){if(!supplier)return null;const mats=[...(supplier.materials||[])],evaluations=mats.map(item=>this.evaluate(item,{buyer,orders,demand:demandByItem[item]||0})),visibleMaterials=mats.filter((item,i)=>!evaluations[i].playerOnly);if(!visibleMaterials.length)return null;const prices=Object.fromEntries(Object.entries(supplier.prices||{}).filter(([id])=>visibleMaterials.includes(id)));return{...supplier,materials:visibleMaterials,prices,sourceType:supplier.sourceType||"ai",aiFallback:true,supplyCoverage:evaluations};}
 mergeForItem(itemId,{buyer=null,orders=[],aiSuppliers=[],demand=0}={}){const state=this.evaluate(itemId,{buyer,orders,demand}),playerOffers=state.playerOrders.map(o=>({id:`player:${o.id}`,sourceType:"player",sourceOrderId:o.id,supplierId:o.companyId,supplierName:o.companyRef?.name||o.companyRef?.companyName||`Firma ${o.companyId??"–"}`,itemId:canonicalSupplyId(itemId),unitPrice:n(o.unitPrice),availableAmount:n(o.remaining??o.quantity),distanceKm:n(o.distanceKm,80),reliability:n(o.reliability??o.companyRef?.reliability,1),deliveryHours:Math.max(1,n(o.deliveryHours,Math.ceil(n(o.distanceKm,80)/55)))}));const ai=state.playerOnly?[]:aiSuppliers.filter(s=>(s.materials||[]).map(canonicalSupplyId).includes(canonicalSupplyId(itemId))).map(s=>({...s,sourceType:s.sourceType||"ai",aiFallback:state.playerQuantity>0,aiMode:state.aiMode}));return{...state,playerOffers,aiOffers:ai,offers:[...playerOffers,...ai]};}
}

export function runAdaptiveAiSupplyServiceTest(){const service=new AdaptiveAiSupplyService({minPlayerSuppliers:2,coverageFactor:1.2,maxDistanceKm:250}),buyer={id:"buyer",regionId:"OWL"},orders=[{id:"a",side:"sell",status:"open",companyId:"p1",companyRef:{regionId:"OWL"},productId:"bottles",remaining:8000,unitPrice:.15,reliability:.95},{id:"b",side:"sell",status:"open",companyId:"p2",companyRef:{regionId:"OWL"},productId:"bottles",remaining:7000,unitPrice:.16,reliability:.98}],covered=service.evaluate("bottle_033",{buyer,orders,demand:9000}),short=service.evaluate("malt",{buyer,orders:[{...orders[0],productId:"malt",remaining:100}],demand:1000});if(!covered.playerOnly||covered.aiMode!=="withdrawn"||short.playerOnly||short.aiMode!=="fallback")throw new Error("Dynamische KI-Versorgung reagiert nicht korrekt auf Spielerabdeckung");return{success:true,covered,short};}
if(typeof window!=="undefined")window.worldAdaptiveAiSupply=window.worldAdaptiveAiSupply||new AdaptiveAiSupplyService();
