// WorldProject – sichere Produkt-/Auszeichnungsaktionen in der bestehenden AdminConsoleUI.
import { AdminConsoleUI } from './AdminConsoleUI.js';
import { adminOperationalSection } from './AdminOperationsData.js';
import { setProductActive, setProductPriceBounds, setProductQualityRange, grantAward, revokeAward } from './AdminProductAwardControl.js';
const h=(tag,props={},...kids)=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(props||{})){if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on')&&typeof v==='function')e.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==undefined&&v!==null)e.setAttribute(k,String(v));}for(const x of kids.flat())if(x!==null&&x!==undefined)e.append(x?.nodeType?x:document.createTextNode(String(x)));return e;};
const btn=(text,onclick,danger=false)=>h('button',{class:`action${danger?' danger':''}`,text,onclick});
const reason=label=>{const r=prompt(`Begründung für „${label}“:`);return r===null?null:String(r).trim();};
const baseProducts=AdminConsoleUI.prototype.render_products;
AdminConsoleUI.prototype.render_products=function(){baseProducts?.call(this);if(!this.admin.can(this.actor,'products.write'))return;const catalog=adminOperationalSection('products',this.context)?.catalog||[];if(!catalog.length)return;const box=h('div',{class:'panel'},h('h3',{text:'Produkt-Schnellaktionen'}));for(const p of catalog.slice(0,100)){const id=p.id||p.productId||p.key,name=p.name||p.title||id,actions=h('div',{class:'toolbar'});actions.append(btn(p.active===false?'Aktivieren':'Deaktivieren',()=>{const r=reason('Produktstatus ändern');if(r===null)return;try{setProductActive(this.actor,this.world(),{productId:id,active:p.active===false,reason:r});this.toast('Produktstatus geändert');this.render();}catch(err){this.toast(err.message,true);}},p.active!==false));actions.append(btn('Preisgrenzen',()=>{const min=Number(prompt('Mindestpreis:',String(p.minPrice??0))),max=Number(prompt('Maximalpreis:',String(p.maxPrice??Math.max(1,min))));if(!Number.isFinite(min)||!Number.isFinite(max))return;const r=reason('Produktpreisgrenzen ändern');if(r===null)return;try{setProductPriceBounds(this.actor,this.world(),{productId:id,minPrice:min,maxPrice:max,reason:r});this.toast('Preisgrenzen geändert');this.render();}catch(err){this.toast(err.message,true);}}));actions.append(btn('Qualitätsbereich',()=>{const min=Number(prompt('Mindestqualität 0–100:',String(p.minQuality??0))),max=Number(prompt('Maximalqualität 0–100:',String(p.maxQuality??100)));if(!Number.isFinite(min)||!Number.isFinite(max))return;const r=reason('Qualitätsbereich ändern');if(r===null)return;try{setProductQualityRange(this.actor,this.world(),{productId:id,minQuality:min,maxQuality:max,reason:r});this.toast('Qualitätsbereich geändert');this.render();}catch(err){this.toast(err.message,true);}}));box.append(h('div',{class:'kv'},h('span',{text:`${name} · ${p.active===false?'Inaktiv':'Aktiv'}`}),actions));}this.body.append(box);};
const baseAwards=AdminConsoleUI.prototype.render_awards;
AdminConsoleUI.prototype.render_awards=function(){baseAwards?.call(this);if(!this.admin.can(this.actor,'awards.write'))return;const catalog=adminOperationalSection('awards',this.context)?.catalog||[],box=h('div',{class:'panel'},h('h3',{text:'Auszeichnung vergeben/entziehen'}));if(!catalog.length){box.append(h('div',{class:'muted',text:'Kein Auszeichnungskatalog geladen.'}));this.body.append(box);return;}const playerSelect=h('select');for(const p of this.players())playerSelect.append(h('option',{value:p.id||p.userId,text:p.username||p.name||p.id||p.userId}));const awardSelect=h('select');for(const a of catalog)awardSelect.append(h('option',{value:a.id||a.awardId||a.achievementId||a.key,text:a.name||a.title||a.id||a.awardId}));box.append(h('div',{class:'toolbar'},playerSelect,awardSelect,btn('🏆 Vergeben',()=>{const player=this.players().find(p=>(p.id||p.userId)===playerSelect.value),r=reason('Auszeichnung vergeben');if(r===null)return;try{grantAward(this.actor,this.world(),player,{awardId:awardSelect.value,reason:r});this.toast('Auszeichnung vergeben');this.render();}catch(err){this.toast(err.message,true);}}),btn('Entziehen',()=>{const player=this.players().find(p=>(p.id||p.userId)===playerSelect.value),r=reason('Auszeichnung entziehen');if(r===null)return;try{revokeAward(this.actor,player,{awardId:awardSelect.value,reason:r});this.toast('Auszeichnung entzogen');this.render();}catch(err){this.toast(err.message,true);}},true)));this.body.append(box);};
if(typeof window!=='undefined')window.worldAdminProductAwardActions=true;
