// WorldProject – prüft Admin-Eingaben vor Änderungen.
const clean=v=>String(v??'').trim();
export function validateAdminNumber(value,{min=-Infinity,max=Infinity,label='Wert',integer=false}={}){const n=Number(value);if(!Number.isFinite(n))return{valid:false,message:`${label} ist keine Zahl`};if(integer&&!Number.isInteger(n))return{valid:false,message:`${label} muss eine ganze Zahl sein`};if(n<min||n>max)return{valid:false,message:`${label} liegt außerhalb des erlaubten Bereichs`};return{valid:true,value:n};}
export function validateAdminText(value,{label='Text',minLength=1,maxLength=5000,allowEmpty=false}={}){const s=clean(value);if(!allowEmpty&&s.length<minLength)return{valid:false,message:`${label} fehlt oder ist zu kurz`};if(s.length>maxLength)return{valid:false,message:`${label} ist zu lang`};return{valid:true,value:s};}
export function validateAdminId(value,{label='ID'}={}){const s=clean(value);if(!s)return{valid:false,message:`${label} fehlt`};if(s.length>160)return{valid:false,message:`${label} ist zu lang`};if(!/^[A-Za-z0-9._:@-]+$/.test(s))return{valid:false,message:`${label} enthält unzulässige Zeichen`};return{valid:true,value:s};}
export function validateAdminEnum(value,allowed,{label='Auswahl'}={}){const values=Array.isArray(allowed)?allowed:[];if(!values.includes(value))return{valid:false,message:`${label} ist ungültig`,allowed:[...values]};return{valid:true,value};}
export function validateAdminReason(reason,{required=true,minLength=3,maxLength=1000}={}){return validateAdminText(reason,{label:'Begründung',minLength,maxLength,allowEmpty:!required});}
export function adminMutationRisk({entityType='',field='',before,after}={}){const token=`${entityType}.${field}`.toLowerCase();let level='normal',reasons=[];if(/money|coins|inventory|premium|role|permission|status|suspend|ban|delete|maintenance|registration|world|market|alliance|release/.test(token)){level='high';reasons.push('kritisches_feld');}const a=Number(after),b=Number(before);if(Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)>1000000){level='high';reasons.push('grosse_numerische_aenderung');}if(after===null||after===undefined){level='high';reasons.push('wert_entfernt');}return{level,reasons,requiresReason:level==='high',requiresConfirmation:level==='high'};}
export function adminMutationPreview({entityType,entityId,field,before,after,reason=''}){const risk=adminMutationRisk({entityType,field,before,after}),reasonCheck=validateAdminReason(reason,{required:risk.requiresReason});return{entityType:clean(entityType),entityId:clean(entityId),field:clean(field),before,after,reason:clean(reason),changed:JSON.stringify(before)!==JSON.stringify(after),risk,reasonValid:reasonCheck.valid,reasonMessage:reasonCheck.valid?null:reasonCheck.message};}
export function validateAdminMutation(input={}){const preview=adminMutationPreview(input),errors=[];if(!preview.entityType)errors.push('Entitätstyp fehlt');if(!preview.entityId)errors.push('Entitäts-ID fehlt');if(!preview.field)errors.push('Feld fehlt');if(!preview.changed)errors.push('Keine Änderung vorhanden');if(!preview.reasonValid)errors.push(preview.reasonMessage);return{valid:errors.length===0,errors,preview};}
if(typeof window!=='undefined')window.worldAdminMutationValidation={number:validateAdminNumber,text:validateAdminText,id:validateAdminId,enum:validateAdminEnum,reason:validateAdminReason,risk:adminMutationRisk,preview:adminMutationPreview,validate:validateAdminMutation};
