// WorldProject – Admin-Freigabeprozess für Builds, Wartung, Rollback und Feature-Rollouts.
import { adminControlSystem } from './AdminControlSystem.js';
const trim=(a,max=2000)=>{if(a.length>max)a.splice(0,a.length-max);};
const text=(v,label)=>{const s=String(v||'').trim();if(!s)throw new Error(`${label} fehlt`);return s;};
export function ensureAdminReleaseControl(world={}){world.adminReleaseControl??={requests:[],approvedBuild:null,maintenance:false,rollbacks:[],featureChanges:[]};for(const k of ['requests','rollbacks','featureChanges'])if(!Array.isArray(world.adminReleaseControl[k]))world.adminReleaseControl[k]=[];return world.adminReleaseControl;}
export function requestRelease(world,{buildId,actor=null,notes='',requiresSecondApproval=true}={}){adminControlSystem.requirePermission(actor,'system.write');const r=ensureAdminReleaseControl(world),id=text(buildId,'Build-ID'),row={id:`release-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,buildId:id,actorId:actor.id,notes:String(notes||'').trim(),requiresSecondApproval:!!requiresSecondApproval,status:'pending',approvals:[actor.id],createdAt:Date.now()};r.requests.push(row);trim(r.requests);adminControlSystem.log(actor,'release_requested',{requestId:row.id,buildId:id,requiresSecondApproval:row.requiresSecondApproval});return row;}
export function approveRelease(world,requestId,actor){adminControlSystem.requirePermission(actor,'system.write');const r=ensureAdminReleaseControl(world),q=r.requests.find(x=>x.id===requestId);if(!q)throw new Error('Release-Anfrage fehlt');if(q.status!=='pending')throw new Error('Release-Anfrage ist nicht mehr offen');if(q.requiresSecondApproval&&q.actorId===actor.id)throw new Error('Zweite Freigabe muss von einem anderen Admin kommen');if(!q.approvals.includes(actor.id))q.approvals.push(actor.id);const enough=!q.requiresSecondApproval||q.approvals.length>=2;if(enough){q.status='approved';q.approvedAt=Date.now();q.approvedBy=[...q.approvals];r.approvedBuild=q.buildId;}adminControlSystem.log(actor,'release_approved',{requestId:q.id,buildId:q.buildId,approvals:q.approvals.length,final:enough});return q;}
export function rejectRelease(world,requestId,actor,reason=''){adminControlSystem.requirePermission(actor,'system.write');const q=ensureAdminReleaseControl(world).requests.find(x=>x.id===requestId);if(!q)throw new Error('Release-Anfrage fehlt');if(q.status!=='pending')throw new Error('Release-Anfrage ist nicht mehr offen');q.status='rejected';q.rejectedBy=actor.id;q.reason=text(reason,'Begründung');q.rejectedAt=Date.now();adminControlSystem.log(actor,'release_rejected',{requestId:q.id,buildId:q.buildId,reason:q.reason});return q;}
export function setReleaseMaintenanceMode(world,enabled,{actor,reason=''}={}){adminControlSystem.requirePermission(actor,'system.write');const r=ensureAdminReleaseControl(world),before=r.maintenance;r.maintenance=!!enabled;r.maintenanceChangedAt=Date.now();r.maintenanceActor=actor.id;r.maintenanceReason=String(reason||'').trim();adminControlSystem.log(actor,'release_maintenance_changed',{before,after:r.maintenance,reason:r.maintenanceReason});return r.maintenance;}
export function recordRollback(world,{fromBuild,toBuild,actor,reason=''}={}){adminControlSystem.requirePermission(actor,'system.write');const r=ensureAdminReleaseControl(world),from=text(fromBuild,'Ausgangs-Build'),to=text(toBuild,'Ziel-Build'),cleanReason=text(reason,'Begründung'),row={fromBuild:from,toBuild:to,actorId:actor.id,reason:cleanReason,at:Date.now()};r.rollbacks.push(row);trim(r.rollbacks);r.approvedBuild=to;adminControlSystem.log(actor,'release_rollback',{fromBuild:from,toBuild:to,reason:cleanReason});return row;}
export function recordFeatureChange(world,{actor,feature,enabled,reason=''}={}){adminControlSystem.requirePermission(actor,'system.write');const r=ensureAdminReleaseControl(world),row={id:`feature-${Date.now()}-${Math.random().toString(36).slice(2,5)}`,feature:text(feature,'Feature'),enabled:!!enabled,reason:String(reason||'').trim(),actorId:actor.id,at:Date.now()};r.featureChanges.push(row);trim(r.featureChanges);adminControlSystem.log(actor,'release_feature_changed',row);return row;}
export function releaseControlKpis(world){const r=ensureAdminReleaseControl(world);return{pending:r.requests.filter(x=>x.status==='pending').length,approved:r.requests.filter(x=>x.status==='approved').length,rejected:r.requests.filter(x=>x.status==='rejected').length,maintenance:r.maintenance,rollbacks:r.rollbacks.length,featureChanges:r.featureChanges.length,approvedBuild:r.approvedBuild,lastRollback:r.rollbacks.at(-1)||null};}
if(typeof window!=='undefined')window.worldAdminReleaseControl={ensure:ensureAdminReleaseControl,request:requestRelease,approve:approveRelease,reject:rejectRelease,maintenance:setReleaseMaintenanceMode,rollback:recordRollback,feature:recordFeatureChange,kpis:releaseControlKpis};