// WorldProject – sichere Adminverwaltung der Spielwährungen.
import { adminControlSystem } from './AdminControlSystem.js';
import { CurrencyCatalog, ensureExchangeRates, setExchangeRate, currencyHealth } from './CurrencyLocalizationSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function currencyAdminSnapshot(actor,world={}){adminControlSystem.requirePermission(actor,'economy.write');const state=ensureExchangeRates(world);return{base:state.base,rates:Object.entries(CurrencyCatalog).map(([code,meta])=>({code,symbol:meta.symbol,locale:meta.locale,rate:n(state.rates[code],null)})),health:currencyHealth(world),updatedAt:state.updatedAt,source:state.source};}
export function adminSetExchangeRate(actor,world,{currency,rate,reason=''}={}){adminControlSystem.requirePermission(actor,'economy.write');const why=String(reason||'').trim();if(why.length<3)throw new Error('Begründung erforderlich');const state=ensureExchangeRates(world),code=String(currency||'').toUpperCase(),before=state.rates[code]??null,after=setExchangeRate(world,{currency:code,rate,source:'admin'});adminControlSystem.log(actor,'currency_rate_changed',{currency:code,before,after,reason:why});return after;}
export function adminSetExchangeRates(actor,world,{rates={},reason=''}={}){adminControlSystem.requirePermission(actor,'economy.write');const why=String(reason||'').trim();if(why.length<3)throw new Error('Begründung erforderlich');const changed=[];for(const[code,value]of Object.entries(rates||{})){const upper=String(code).toUpperCase();if(!(upper in CurrencyCatalog))continue;const state=ensureExchangeRates(world),before=state.rates[upper]??null,after=setExchangeRate(world,{currency:upper,rate:value,source:'admin-batch'});if(before!==after)changed.push({currency:upper,before,after});}if(!changed.length)throw new Error('Keine gültigen Wechselkurse geändert');adminControlSystem.log(actor,'currency_rates_changed',{count:changed.length,changes:changed,reason:why});return changed;}
export function setBaseCurrency(actor,world,{currency='EUR',reason=''}={}){adminControlSystem.requirePermission(actor,'economy.write');const code=String(currency||'').toUpperCase(),why=String(reason||'').trim();if(!(code in CurrencyCatalog))throw new Error('Unbekannte Basiswährung');if(why.length<3)throw new Error('Begründung erforderlich');const state=ensureExchangeRates(world),before=state.base;if(before===code)return code;const oldRates={...state.rates},baseRate=n(oldRates[code]);if(!baseRate||baseRate<=0)throw new Error(`Wechselkurs fehlt für neue Basiswährung ${code}`);for(const key of Object.keys(oldRates))state.rates[key]=n(oldRates[key])/baseRate;state.base=code;state.rates[code]=1;state.updatedAt=Date.now();state.source='admin-base-change';adminControlSystem.log(actor,'currency_base_changed',{before,after:code,reason:why});return code;}
if(typeof window!=='undefined')window.worldAdminCurrency={snapshot:currencyAdminSnapshot,setRate:adminSetExchangeRate,setRates:adminSetExchangeRates,setBase:setBaseCurrency};
