// WorldProject – Datenmodell für den später sichtbaren Adminbereich. Keine Spieler-UI.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function adminPlayerRow(p){return{id:p.id||p.userId,username:p.username||p.name||"",email:p.email||"",country:p.country||"",createdAt:p.createdAt||null,lastLoginAt:p.lastLoginAt||null,suspended:!!p.moderation?.suspended,muted:!!p.moderation?.muted,companyIds:(p.companyIds||[]),premium:!!p.premium};}
export function adminCompanyRow(c){return{id:c.id||c.companyId,name:c.name||c.companyName||"",ownerId:c.ownerId||c.playerId||null,type:c.type||c.company_type||"",branchKey:c.branchKey||"",money:n(c.money),employees:(c.employees||[]).length,machines:(c.buildingState?.equipment||[]).length,openJobs:(c.productionJobs||[]).filter(x=>!["done","completed","cancelled","admin_cancelled"].includes(x.status)).length,inventoryItems:Object.keys(c.inventory||{}).length,finishedItems:Object.keys(c.finishedGoods||{}).length};}
export function searchAdminPlayers(actor,players,{query="",suspended=null,limit=100}={}){adminControlSystem.requirePermission(actor,"players.read");const q=String(query).toLowerCase();return players.map(adminPlayerRow).filter(x=>(!q||[x.id,x.username,x.email].some(v=>String(v||"").toLowerCase().includes(q)))&&(suspended===null||x.suspended===!!suspended)).slice(0,Math.max(1,n(limit,100)));}
export function searchAdminCompanies(actor,companies,{query="",type=null,ownerId=null,limit=100}={}){adminControlSystem.requirePermission(actor,"companies.read");const q=String(query).toLowerCase();return companies.map(adminCompanyRow).filter(x=>(!q||[x.id,x.name,x.ownerId,x.type].some(v=>String(v||"").toLowerCase().includes(q)))&&(!type||x.type===type)&&(!ownerId||x.ownerId===ownerId)).slice(0,Math.max(1,n(limit,100)));}
export function adminCompanyDetail(actor,c){adminControlSystem.requirePermission(actor,"companies.read");return{summary:adminCompanyRow(c),inventory:{...(c.inventory||{})},finishedGoods:{...(c.finishedGoods||{})},employees:(c.employees||[]).map(e=>({...e})),machines:(c.buildingState?.equipment||[]).map(m=>({...m})),jobs:(c.productionJobs||[]).map(j=>({...j})),orders:(c.customerOrders||[]).map(o=>({...o})),salesLedger:(c.salesLedger||[]).slice(-200),costLedger:(c.costLedger||[]).slice(-200),sites:(c.sites||[]).map(s=>({...s})),contracts:c.contracts||null,finance:c.finance||null,growth:c.growth||null,risk:c.risk||null,sustainability:c.sustainability||null};}
export function adminWorldOverview(actor,{players=[],companies=[],world={}}={}){adminControlSystem.requirePermission(actor,"players.read");const totalMoney=companies.reduce((s,c)=>s+n(c.money),0),activeCompanies=companies.filter(c=>c.status!=="closed").length;return{players:players.length,companies:companies.length,activeCompanies,totalMoney,averageCompanyMoney:companies.length?totalMoney/companies.length:0,suspendedPlayers:players.filter(p=>p.moderation?.suspended).length,allianceCount:(world.alliances||[]).length,featureFlags:{...adminControlSystem.settings},worldTime:world.time||world.gameTime||null,economy:world.economy||null};}
export function adminSectionPayload(actor,section,ctx={}){switch(section){case"overview":return adminWorldOverview(actor,ctx);case"players":return searchAdminPlayers(actor,ctx.players||{},ctx.filters||{});case"companies":return searchAdminCompanies(actor,ctx.companies||[],ctx.filters||{});case"audit":return adminControlSystem.audit(actor,ctx.filters||{});default:return{section,available:true};}}
if(typeof window!=="undefined")window.worldAdminDashboardData={playerRow:adminPlayerRow,companyRow:adminCompanyRow,companyDetail:adminCompanyDetail,worldOverview:adminWorldOverview};
