// WorldProject – sichtbare Währungsverwaltung und serverseitiges Finanzprotokoll in der Admin-Wirtschaftsseite.
import { AdminConsoleUI } from './AdminConsoleUI.js';
import { currencyAdminSnapshot, adminSetExchangeRate } from './AdminCurrencySystem.js';
import { adminServerPersistence } from './AdminServerPersistenceBridge.js';
const h=(tag,props={},...kids)=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(props||{})){if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on')&&typeof v==='function')e.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==undefined&&v!==null)e.setAttribute(k,String(v));}for(const x of kids.flat())if(x!==null&&x!==undefined)e.append(x?.nodeType?x:document.createTextNode(String(x)));return e;};
const fmt=n=>Number(n||0).toLocaleString('de-DE');
const when=v=>v?new Date(v).toLocaleString('de-DE'):'—';
const statusText=s=>({completed:'✅ OK',failed:'❌ FEHLER',recovered:'🛟 BEHOBEN',legacy:'📜 ALT',pending:'⏳ OFFEN'}[s]||String(s||'—').toUpperCase());
async function appendFinancialLog(ui){
 const box=h('div',{class:'panel'},h('h3',{text:'💶 Server-Finanzprotokoll'}),h('div',{class:'section-note',text:'Coin-Tausch, serverseitige Geldbuchungen und erkannte Fehler. Nur ausdrücklich als wiederherstellbar markierte Fehler können hier gutgeschrieben werden.'}));
 const loading=h('div',{class:'muted',text:'Transaktionen werden geladen …'});box.append(loading);ui.body.append(box);
 try{
  const rows=await adminServerPersistence.financialTransactions({limit:100});loading.remove();
  if(!rows.length){box.append(h('div',{class:'muted',text:'Noch keine serverseitigen Finanztransaktionen vorhanden.'}));return;}
  const table=h('table'),head=h('tr');['Zeit','Spieler','Vorgang','Coins','Firmengeld','Status','Referenz','Aktion'].forEach(x=>head.append(h('th',{text:x})));table.append(head);
  for(const row of rows){
   const action=row.recoverable?h('button',{class:'action',text:'Wiederherstellen',onclick:async()=>{const reason=prompt(`Begründung zur Wiederherstellung von Transaktion #${row.id}:`);if(reason===null)return;if(!reason.trim())return ui.toast('Begründung ist erforderlich',true);if(!confirm(`Transaktion #${row.id} wirklich einmalig wiederherstellen?`))return;try{await adminServerPersistence.recoverFinancialTransaction(row.id,reason.trim());ui.toast(`Transaktion #${row.id} wiederhergestellt`);ui.render();}catch(err){ui.toast(err.message,true);}}}):h('span',{class:'muted',text:'—'});
   table.append(h('tr',{},h('td',{text:when(row.created_at)}),h('td',{text:`#${row.user_id}${row.username?` ${row.username}`:''}`}),h('td',{text:row.operation||row.transaction_type||'—'}),h('td',{text:`${Number(row.coin_delta)>0?'+':''}${fmt(row.coin_delta)}`}),h('td',{text:`${Number(row.money_delta)>0?'+':''}${fmt(row.money_delta)} €`}),h('td',{text:statusText(row.status)}),h('td',{text:row.reference_id||row.idempotency_key||'—'}),h('td',{},action)));
   if(row.error)table.append(h('tr',{},h('td',{colspan:'8',class:'bad',text:`Fehler #${row.id}: ${row.error}`})));
  }
  box.append(table);
 }catch(err){loading.textContent=`Finanzprotokoll konnte nicht geladen werden: ${err.message}`;loading.className='bad';}
}
const base=AdminConsoleUI.prototype.render_economy;
AdminConsoleUI.prototype.render_economy=function(){base?.call(this);if(!this.admin.can(this.actor,'economy.write'))return;let data;try{data=currencyAdminSnapshot(this.actor,this.world());}catch(err){this.body.append(h('div',{class:'panel bad',text:`Währungen: ${err.message}`}));appendFinancialLog(this);return;}const box=h('div',{class:'panel'},h('h3',{text:'🌍 Länder & Währungen'}),h('div',{class:'section-note',text:'Spielwerte bleiben intern stabil. Diese Kurse bestimmen nur die Umrechnung in die lokale Spielerwährung. Fehlende Kurse müssen vor globaler Freischaltung ergänzt werden.'}),h('div',{class:'cards'},h('div',{class:'card'},h('span',{class:'muted',text:'Basiswährung'}),h('strong',{text:data.base})),h('div',{class:'card'},h('span',{class:'muted',text:'Kurse vorhanden'}),h('strong',{text:String(data.rates.filter(x=>Number.isFinite(Number(x.rate))).length)})),h('div',{class:`card ${data.health.success?'':'bad'}`},h('span',{class:'muted',text:'Fehlende Kurse'}),h('strong',{text:String(data.health.missing.length)}))));const table=h('table'),head=h('tr');['Währung','Symbol','Kurs','Aktion'].forEach(x=>head.append(h('th',{text:x})));table.append(head);for(const row of data.rates){const input=h('input',{type:'number',step:'0.0001',value:Number.isFinite(Number(row.rate))?String(row.rate):'',placeholder:'Kurs'}),button=h('button',{class:'action',text:'Speichern',onclick:()=>{const rate=Number(input.value);if(!Number.isFinite(rate)||rate<=0)return this.toast('Ungültiger Wechselkurs',true);const reason=prompt(`Begründung für Wechselkurs ${row.code}:`);if(reason===null)return;try{adminSetExchangeRate(this.actor,this.world(),{currency:row.code,rate,reason});this.toast(`${row.code} aktualisiert`);this.render();}catch(err){this.toast(err.message,true);}}});table.append(h('tr',{},h('td',{text:row.code}),h('td',{text:row.symbol}),h('td',{},input),h('td',{},button)));}box.append(table);if(data.health.missing.length)box.append(h('div',{class:'warn',text:`⚠️ Noch ohne Wechselkurs: ${data.health.missing.join(', ')}`}));this.body.append(box);appendFinancialLog(this);};
if(typeof window!=='undefined')window.worldAdminCurrencyConsoleView=true;
