// WorldProject – Fachbereichsansichten für die bestehende AdminConsoleUI.
// Kein zweites Adminsystem: erweitert ausschließlich den vorhandenen Prototyp.
import { AdminConsoleUI } from './AdminConsoleUI.js';
import { adminOperationalSection } from './AdminOperationsData.js';
import { adminFleetHealth } from './AdminOperationsOverview.js';
import { supportKpis } from './SupportCaseSystem.js';
import { moderationKpis } from './ModerationCaseSystem.js';
import { liveOpsKpis } from './LiveOpsSystem.js';
import { balanceKpis } from './AdminBalancingSystem.js';

const h=(tag,props={},...kids)=>{const el=document.createElement(tag);for(const[k,v]of Object.entries(props||{})){if(k==='class')el.className=v;else if(k==='text')el.textContent=v;else if(k==='html')el.innerHTML=v;else if(k.startsWith('on')&&typeof v==='function')el.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==undefined&&v!==null)el.setAttribute(k,String(v));}for(const child of kids.flat()){if(child===null||child===undefined)continue;el.append(child?.nodeType?child:document.createTextNode(String(child)));}return el;};
const money=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v)||0);
const num=v=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(Number(v)||0);
const date=v=>v?new Date(Number(v)||v).toLocaleString('de-DE'):'—';
const cards=(rows=[])=>h('div',{class:'cards'},...rows.map(([label,value,cls=''])=>h('div',{class:`card ${cls}`},h('span',{class:'muted',text:label}),h('strong',{text:String(value)}))));
const panel=(title,...kids)=>h('div',{class:'panel'},h('h3',{text:title}),...kids);
const note=text=>h('div',{class:'section-note',text});
const table=(headers,rows)=>{const t=h('table'),head=h('tr');headers.forEach(x=>head.append(h('th',{text:x})));t.append(head);for(const row of rows){const tr=h('tr');for(const cell of row)tr.append(h('td',{},cell?.nodeType?cell:String(cell??'—')));t.append(tr);}return t;};
const safe=(ui,fn)=>{try{return fn();}catch(err){ui.toast?.(err.message,true);return null;}};

AdminConsoleUI.prototype.render_economy=function(){const d=adminOperationalSection('economy',this.context)||{},b=balanceKpis(this.world());this.body.append(note('Hier siehst du die globale Wirtschaftslage aller Betriebe. Änderungen am Balancing wirken spielweit und sollten nur mit Begründung vorgenommen werden.'),cards([['Betriebe',d.companies||0],['Firmenkapital',money(d.totalCompanyMoney)],['Umsatz',money(d.totalRevenue)],['Kosten',money(d.totalCosts)],['Ergebnis',money(d.net),d.net<0?'bad':'ok'],['Negative Konten',d.negativeCash||0,d.negativeCash?'bad':'ok']]));const rows=Object.entries(b.values||{}).map(([k,v])=>[k,num(v)]);this.body.append(panel('Aktuelle Balancing-Faktoren',table(['Faktor','Wert'],rows)),panel('Balancing-Verlauf',h('div',{class:'muted',text:`Änderungen: ${b.changes||0} · Presets: ${(b.presets||[]).join(', ')||'keine'}`}),b.lastChange?h('code',{text:JSON.stringify(b.lastChange,null,2)}):h('span',{class:'muted',text:'Noch keine Änderung.'})));};

AdminConsoleUI.prototype.render_production=function(){const d=adminOperationalSection('production',this.context)||{};this.body.append(note('Alle Produktionen aller Betriebe. „Festhängend“ bedeutet: Der erwartete Endzeitpunkt ist überschritten, der Auftrag meldet aber weiterhin Produktion.'),cards([['Produktionsaufträge',d.totalJobs||0],['Läuft',d.running||0],['Geplant/Wartend',d.queued||0],['Verdächtig festhängend',d.stuck||0,d.stuck?'bad':'ok']]));const rows=(d.jobs||[]).slice(0,300).map(j=>[j.companyName||j.companyId||'—',j.productName||j.productId||j.recipeId||'—',j.quantity??j.amount??'—',j.status||'—',j.progress!=null?`${Math.round(Number(j.progress)||0)} %`:'—',date(j.endsAt??j.endAt??j.busyUntil)]);this.body.append(panel(`Produktionen (${rows.length} angezeigt)`,table(['Betrieb','Produkt','Menge','Status','Fortschritt','Ende'],rows)));};

AdminConsoleUI.prototype.render_transport=function(){const d=adminOperationalSection('transport',this.context)||{};this.body.append(note('Globale Liefer- und Fahrzeugübersicht. Überfällige Lieferungen werden gesondert gezählt, damit festhängende Logistik schnell auffällt.'),cards([['Lieferungen',d.deliveries||0],['Offen',d.open||0],['Überfällig',d.late||0,d.late?'bad':'ok'],['Fahrzeuge',d.vehicles||0],['Verfügbar',d.availableVehicles||0],['Transportfaktor',num(d.worldTransportFactor||1)]]));const rows=(d.recentDeliveries||[]).slice(0,300).map(x=>[x.companyName||x.companyId||'—',x.supplierName||x.supplierId||'—',x.itemName||x.item||x.productId||'—',x.quantity??'—',x.status||'—',date(x.eta??x.arrivalAt??x.expectedAt)]);this.body.append(panel(`Letzte Lieferungen (${rows.length})`,table(['Betrieb','Lieferant','Ware','Menge','Status','ETA'],rows)));};

AdminConsoleUI.prototype.render_premium=function(){const d=adminOperationalSection('premium',this.context)||{};this.body.append(note('Premiumstatus aller Spieler. Einzelne Spieler kannst du im Bereich „Spieler“ öffnen und Premium dort direkt vergeben oder entfernen.'),cards([['Spieler',d.players||0],['Premium',d.premium||0],['Ohne Premium',d.free||0],['Premium-Anteil',`${Math.round((d.share||0)*100)} %`],['Läuft in 7 Tagen aus',d.expiring7d||0]]));const rows=(d.expiring||[]).map(p=>[p.name||p.id,p.id,date(p.until)]);this.body.append(panel('Bald auslaufendes Premium',rows.length?table(['Spieler','ID','Läuft aus'],rows):h('div',{class:'ok',text:'✅ Keine Premium-Laufzeiten innerhalb der nächsten 7 Tage.'})));};

AdminConsoleUI.prototype.render_coins=function(){const d=adminOperationalSection('coins',this.context)||{};this.body.append(note('Coin-Bestände dienen der Kontrolle und Fehlersuche. Änderungen an einzelnen Konten erfolgen im Spielerprofil und werden auditiert.'),cards([['Spieler',d.players||0],['Coins gesamt',num(d.totalCoins)],['Coin-Inhaber',d.holders||0],['Ø pro Spieler',num(d.average)]]));const rows=(d.top||[]).map((p,i)=>[i+1,p.name||p.id,p.id,num(p.coins)]);this.body.append(panel('Größte Coin-Bestände',table(['#','Spieler','ID','Coins'],rows)));};

AdminConsoleUI.prototype.render_products=function(){const d=adminOperationalSection('products',this.context)||{};this.body.append(note('Produktkatalog und aggregierte Fertigwarenbestände über alle Betriebe.'),cards([['Produkte im Katalog',d.catalogCount||0],['Fertigwarenarten im Umlauf',(d.finishedStock||[]).length]]));const rows=(d.finishedStock||[]).slice(0,300).map(x=>[x.product,num(x.quantity)]);this.body.append(panel('Fertigwarenbestände',rows.length?table(['Produkt','Gesamtbestand'],rows):h('div',{class:'muted',text:'Keine Fertigwaren gefunden.'})));};

AdminConsoleUI.prototype.render_languages=function(){const d=adminOperationalSection('languages',this.context)||{};this.body.append(note('Sprachverteilung der Spieler. „unknown“ bedeutet, dass beim Datensatz noch keine Sprache gespeichert wurde.'),cards([['Erkannte Sprachen',(d.playerLanguages||[]).length],['Technisch unterstützt',(d.supported||[]).length],['RTL-Sprachen',(d.rtl||[]).length]]));this.body.append(panel('Spielersprachen',table(['Sprache','Spieler'],(d.playerLanguages||[]).map(x=>[x.language,x.count]))),panel('Technische Sprachlisten',h('div',{class:'kv'},h('span',{text:'Unterstützt'}),h('span',{text:(d.supported||[]).join(', ')||'Noch keine Weltliste'})),h('div',{class:'kv'},h('span',{text:'RTL'}),h('span',{text:(d.rtl||[]).join(', ')||'Noch keine Weltliste'}))));};

AdminConsoleUI.prototype.render_npc=function(){const d=adminOperationalSection('npc',this.context)||{};this.body.append(note('NPC- und KI-Betriebe stabilisieren Nachfrage und Liquidität. Hier wird nur der globale Zustand überwacht; Detailsteuerung bleibt über die vorhandenen NPC-Systeme getrennt.'),cards([['NPC gesamt',d.total||0],['Aktiv',d.active||0],['Inaktiv',d.inactive||0],['Liquidität',d.liquidityEnabled?'Aktiv':'Aus',d.liquidityEnabled?'ok':'warn'],['Live-Events',d.liveOps?.activeEvents||0]]));const rows=(d.rows||[]).slice(0,300).map(x=>[x.name||x.id||'—',x.type||x.branchKey||'—',x.country||x.region||'—',x.active===false?'Inaktiv':'Aktiv']);this.body.append(panel('NPC-Liste',table(['NPC','Typ','Region','Status'],rows)));};

AdminConsoleUI.prototype.render_support=function(){const world=this.world(),state=world.supportState||{cases:[],messages:[],compensations:[]},k=supportKpis(world);this.body.append(note('Supportfälle, Wartezeiten und Kulanz. Kritische Kulanzbuchungen werden im Audit protokolliert.'),cards([['Offen',k.open||0],['Wartet auf Support',k.waitingStaff||0,k.waitingStaff?'warn':''],['Wartet auf Spieler',k.waitingPlayer||0],['Dringend',k.urgent||0,k.urgent?'bad':'ok'],['Kulanzbuchungen',k.compensations||0]]));const rows=(state.cases||[]).slice().sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).slice(0,300).map(c=>[c.id,c.playerId,c.subject,c.priority,c.status,date(c.updatedAt)]);this.body.append(panel('Supportfälle',table(['Fall','Spieler','Betreff','Priorität','Status','Aktualisiert'],rows)));};

AdminConsoleUI.prototype.render_moderation=function(){const world=this.world(),state=world.moderationState||{cases:[],sanctions:[]},k=moderationKpis(world);this.body.append(note('Moderationsfälle und aktive Sanktionen. Spielerbezogene Schnellaktionen befinden sich zusätzlich im Spielerprofil.'),cards([['Offene Fälle',k.openCases||0],['Kritisch offen',k.criticalOpen||0,k.criticalOpen?'bad':'ok'],['Aktive Sanktionen',k.activeSanctions||0],['Warnungen',k.warnings||0],['Mutes',k.mutes||0],['Sperren',k.suspensions||0,k.suspensions?'warn':'']]));const rows=(state.cases||[]).slice().reverse().slice(0,300).map(c=>[c.id,c.playerId,c.category,c.severity,c.status,date(c.createdAt)]);this.body.append(panel('Moderationsfälle',table(['Fall','Spieler','Kategorie','Schwere','Status','Erstellt'],rows)));};

AdminConsoleUI.prototype.render_liveops=function(){const world=this.world(),state=world.liveOps||{events:[],rollouts:[],announcements:[]},k=liveOpsKpis(world);this.body.append(note('Zeitgesteuerte Events, Rollouts und Ankündigungen. Änderungen werden über das LiveOps-System validiert und auditiert.'),cards([['Aktive Events',k.activeEvents||0],['Geplant',k.scheduledEvents||0],['Abgebrochen',k.cancelledEvents||0],['Rollouts',k.rollouts||0],['Ankündigungen',k.announcements||0]]));const eventRows=(state.events||[]).slice().reverse().slice(0,200).map(x=>[x.name,x.type,x.audience,x.status,date(x.startsAt),date(x.endsAt)]),rolloutRows=(state.rollouts||[]).slice().reverse().slice(0,200).map(x=>[x.feature,`${x.percentage}%`,x.status||'scheduled',date(x.startsAt),date(x.endsAt)]);this.body.append(panel('Events',table(['Name','Typ','Zielgruppe','Status','Start','Ende'],eventRows)),panel('Feature-Rollouts',table(['Feature','Anteil','Status','Start','Ende'],rolloutRows)));};

AdminConsoleUI.prototype.render_overview=function(){const model=this.frontend?.navigate?.('overview')?.data||null,fleet=model?.fleet||adminFleetHealth(this.companies()),s=this.admin.snapshot(this.actor,{players:this.players(),companies:this.companies()}),security=model?.security;this.body.append(cards([['Spieler',s.players],['Betriebe',s.companies],['Firmenkapital',money(s.totalCompanyMoney)],['Gesunde Betriebe',`${fleet.healthy}/${fleet.companies}`],['Ø Betriebs-Health',`${fleet.averageHealth}/100`,fleet.averageHealth<70?'bad':'ok'],['Kritische Probleme',fleet.criticalIssues||0,fleet.criticalIssues?'bad':'ok'],['Audit-Einträge',s.auditEntries],['Admin-Sicherheit',security?.success===false?'FEHLER':'OK',security?.success===false?'bad':'ok']]));const issues=(fleet.issues||[]).slice(0,100);this.body.append(panel('Betriebswarnungen',issues.length?table(['Schwere','Betrieb','Problem','Referenz'],issues.map(x=>[x.severity,x.companyName||x.companyId,x.message,x.jobId||x.deliveryId||x.machineId||'—'])):h('div',{class:'ok',text:'✅ Keine auffälligen Betriebsprobleme erkannt.'})));};

// Navigation ebenfalls an echte Berechtigungen koppeln.
const originalRenderNav=AdminConsoleUI.prototype.renderNav;
AdminConsoleUI.prototype.renderNav=function(){if(!this.frontend?.current)return originalRenderNav.call(this);const allowed=new Set((this.frontend.current().navigation||[]).map(x=>x.id));for(const id of [...allowed])if(!this.admin.can(this.actor,({players:'players.read',companies:'companies.read'}[id]||''))&&['players','companies'].includes(id))allowed.delete(id);this.nav.replaceChildren();const labels={overview:'📊 Übersicht',players:'👥 Spieler',companies:'🏭 Betriebe',economy:'💶 Wirtschaft',market:'📈 Markt',products:'📦 Produkte',suppliers:'🚚 Lieferanten',production:'⚙️ Produktion',transport:'🚛 Logistik',alliances:'🤝 Allianzen',premium:'⭐ Premium',coins:'🪙 Coins',awards:'🏆 Auszeichnungen',languages:'🌐 Sprachen',npc:'🤖 NPC',support:'🛟 Support',moderation:'🛡️ Moderation',liveops:'📡 LiveOps',system:'⚙️ System',audit:'📜 Audit'};for(const id of allowed){const b=h('button',{class:id===this.section?'active':'',onclick:()=>{this.section=id;this.selected=null;this.renderNav();this.render();}},h('span',{text:labels[id]||id}));this.nav.append(b);}};

if(typeof window!=='undefined')window.worldAdminConsoleSectionViews=true;
