// WorldProject – echte Datenmodelle für Admin-Fachbereiche ohne Spieler-UI.
import { balanceKpis } from './AdminBalancingSystem.js';
import { liveOpsKpis } from './LiveOpsSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const arr=v=>Array.isArray(v)?v:[];
const sum=(rows,fn)=>rows.reduce((s,x)=>s+n(fn(x)),0);
export function economyAdminData({companies=[],world={}}={}){const cs=arr(companies),money=sum(cs,c=>c.money),revenue=sum(cs,c=>c.revenue??c.finance?.revenue),costs=sum(cs,c=>c.costs??c.finance?.costs);return{companies:cs.length,totalCompanyMoney:money,totalRevenue:revenue,totalCosts:costs,net:revenue-costs,negativeCash:cs.filter(c=>n(c.money)<0).length,balance:balanceKpis(world)};}
export function productionAdminData({companies=[]}={}){const cs=arr(companies),jobs=cs.flatMap(c=>arr(c.productionJobs).map(j=>({...j,companyId:c.id||c.companyId,companyName:c.name||c.companyName||''}))),running=jobs.filter(j=>['running','active','in_progress','producing'].includes(j.status)),queued=jobs.filter(j=>['queued','planned','pending'].includes(j.status)),stuck=running.filter(j=>{const until=n(j.endsAt??j.endAt??j.busyUntil);return until&&until<Date.now()-60000;});return{totalJobs:jobs.length,running:running.length,queued:queued.length,stuck:stuck.length,jobs:jobs.slice(-500).reverse(),stuckJobs:stuck.slice(-100).reverse()};}
export function transportAdminData({companies=[],world={}}={}){const cs=arr(companies),deliveries=cs.flatMap(c=>arr(c.deliveries??c.shipments).map(d=>({...d,companyId:c.id||c.companyId,companyName:c.name||c.companyName||''}))),vehicles=cs.flatMap(c=>arr(c.vehicles??c.fleet).map(v=>({...v,companyId:c.id||c.companyId}))),open=deliveries.filter(d=>!['delivered','arrived','completed','cancelled'].includes(d.status)),late=open.filter(d=>{const eta=n(d.eta??d.arrivalAt??d.expectedAt);return eta&&eta<Date.now();});return{deliveries:deliveries.length,open:open.length,late:late.length,vehicles:vehicles.length,availableVehicles:vehicles.filter(v=>['available','idle','ready',undefined,null].includes(v.status)).length,recentDeliveries:deliveries.slice(-500).reverse(),lateDeliveries:late.slice(-100).reverse(),worldTransportFactor:n(world.adminWorld?.market?.transportPrice,1)};}
export function premiumAdminData({players=[]}={}){const ps=arr(players),premium=ps.filter(p=>p.premium||p.premiumActive),expiring=premium.filter(p=>{const until=n(p.premiumUntil);return until&&until>Date.now()&&until<Date.now()+7*86400000;});return{players:ps.length,premium:premium.length,free:ps.length-premium.length,share:ps.length?premium.length/ps.length:0,expiring7d:expiring.length,expiring:expiring.slice(0,100).map(p=>({id:p.id||p.userId,name:p.username||p.name||'',until:p.premiumUntil}))};}
export function coinsAdminData({players=[]}={}){const ps=arr(players),total=sum(ps,p=>p.coins),holders=ps.filter(p=>n(p.coins)>0);return{players:ps.length,totalCoins:total,holders:holders.length,average:ps.length?total/ps.length:0,top:holders.sort((a,b)=>n(b.coins)-n(a.coins)).slice(0,50).map(p=>({id:p.id||p.userId,name:p.username||p.name||'',coins:n(p.coins)}))};}
export function languageAdminData({players=[],world={}}={}){const counts={};for(const p of arr(players)){const lang=String(p.language||p.locale||'unknown');counts[lang]=(counts[lang]||0)+1;}return{playerLanguages:Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([language,count])=>({language,count})),supported:arr(world.languages??world.supportedLanguages),rtl:arr(world.rtlLanguages)};}
export function npcAdminData({world={}}={}){const npcs=arr(world.npcs??world.aiCompanies??world.aiPlayers),active=npcs.filter(x=>x.active!==false);return{total:npcs.length,active:active.length,inactive:npcs.length-active.length,liquidityEnabled:world.adminWorld?.market?.npcLiquidity!==0,liveOps:liveOpsKpis(world),rows:npcs.slice(0,500)};}
export function productsAdminData({companies=[],world={}}={}){const catalog=arr(world.products??world.productCatalog),finished={};for(const c of arr(companies))for(const[k,v]of Object.entries(c.finishedGoods||{}))finished[k]=(finished[k]||0)+n(v);return{catalogCount:catalog.length,catalog:catalog.slice(0,1000),finishedStock:Object.entries(finished).sort((a,b)=>b[1]-a[1]).map(([product,quantity])=>({product,quantity}))};}
export function adminOperationalSection(section,context={}){switch(section){case'economy':return economyAdminData(context);case'production':return productionAdminData(context);case'transport':return transportAdminData(context);case'premium':return premiumAdminData(context);case'coins':return coinsAdminData(context);case'languages':return languageAdminData(context);case'npc':return npcAdminData(context);case'products':return productsAdminData(context);default:return null;}}
