// WorldProject – sichere Produkt-/Auszeichnungsaktionen für Admins.
import { adminControlSystem } from './AdminControlSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const products=world=>Array.isArray(world?.products)?world.products:Array.isArray(world?.productCatalog)?world.productCatalog:[];
const awards=world=>Array.isArray(world?.awards)?world.awards:Array.isArray(world?.achievements)?world.achievements:Array.isArray(world?.badges)?world.badges:[];
export function findAdminProduct(world,id){const key=String(id||'');return products(world).find(x=>String(x.id||x.productId||x.key)===key)||null;}
export function setProductActive(actor,world,{productId,active,reason=''}={}){adminControlSystem.requirePermission(actor,'products.write');const why=String(reason||'').trim();if(why.length<3)throw new Error('Begründung erforderlich');const p=findAdminProduct(world,productId);if(!p)throw new Error('Produkt fehlt');const before=p.active;p.active=!!active;adminControlSystem.log(actor,'product_active_changed',{productId,before,after:p.active,reason:why});return p;}
export function setProductPriceBounds(actor,world,{productId,minPrice,maxPrice,reason=''}={}){adminControlSystem.requirePermission(actor,'products.write');const why=String(reason||'').trim(),min=Math.max(0,n(minPrice)),max=Math.max(0,n(maxPrice));if(why.length<3)throw new Error('Begründung erforderlich');if(max<min)throw new Error('Maximalpreis darf nicht unter Mindestpreis liegen');const p=findAdminProduct(world,productId);if(!p)throw new Error('Produkt fehlt');const before={minPrice:p.minPrice,maxPrice:p.maxPrice};p.minPrice=min;p.maxPrice=max;adminControlSystem.log(actor,'product_price_bounds_changed',{productId,before,after:{minPrice:min,maxPrice:max},reason:why});return p;}
export function setProductQualityRange(actor,world,{productId,minQuality=0,maxQuality=100,reason=''}={}){adminControlSystem.requirePermission(actor,'products.write');const why=String(reason||'').trim(),min=n(minQuality),max=n(maxQuality);if(why.length<3)throw new Error('Begründung erforderlich');if(min<0||max>100||max<min)throw new Error('Qualitätsbereich muss zwischen 0 und 100 liegen');const p=findAdminProduct(world,productId);if(!p)throw new Error('Produkt fehlt');const before={minQuality:p.minQuality,maxQuality:p.maxQuality};p.minQuality=min;p.maxQuality=max;adminControlSystem.log(actor,'product_quality_range_changed',{productId,before,after:{minQuality:min,maxQuality:max},reason:why});return p;}
export function findAdminAward(world,id){const key=String(id||'');return awards(world).find(x=>String(x.id||x.awardId||x.achievementId||x.key)===key)||null;}
export function grantAward(actor,world,player,{awardId,reason=''}={}){adminControlSystem.requirePermission(actor,'awards.write');const why=String(reason||'').trim();if(why.length<3)throw new Error('Begründung erforderlich');const award=findAdminAward(world,awardId);if(!award)throw new Error('Auszeichnung fehlt');if(!player)throw new Error('Spieler fehlt');player.awards??=[];const id=award.id||award.awardId||award.achievementId||award.key;if(player.awards.some(x=>(typeof x==='string'?x:(x.id||x.awardId||x.achievementId))===id))return{success:true,idempotent:true};const row={id,name:award.name||award.title||id,grantedAt:Date.now(),adminGranted:true};player.awards.push(row);adminControlSystem.log(actor,'award_granted',{playerId:player.id||player.userId,awardId:id,reason:why});return{success:true,award:row};}
export function revokeAward(actor,player,{awardId,reason=''}={}){adminControlSystem.requirePermission(actor,'awards.write');const why=String(reason||'').trim();if(why.length<3)throw new Error('Begründung erforderlich');if(!player)throw new Error('Spieler fehlt');const before=Array.isArray(player.awards)?player.awards.length:0;player.awards=(player.awards||[]).filter(x=>(typeof x==='string'?x:(x.id||x.awardId||x.achievementId))!==awardId);const removed=before-player.awards.length;if(removed)adminControlSystem.log(actor,'award_revoked',{playerId:player.id||player.userId,awardId,removed,reason:why});return{success:true,removed};}
if(typeof window!=='undefined')window.worldAdminProductAwardControl={findProduct:findAdminProduct,setProductActive,setProductPriceBounds,setProductQualityRange,findAward:findAdminAward,grantAward,revokeAward};
