// WorldProject – sichtbare Lieferanten- und Auszeichnungsansichten für die bestehende AdminConsoleUI.
import { AdminConsoleUI } from './AdminConsoleUI.js';
import { adminOperationalSection } from './AdminOperationsData.js';
const h=(tag,props={},...kids)=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(props||{})){if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on')&&typeof v==='function')e.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==undefined&&v!==null)e.setAttribute(k,String(v));}for(const x of kids.flat())if(x!==null&&x!==undefined)e.append(x?.nodeType?x:document.createTextNode(String(x)));return e;};
const cards=rows=>h('div',{class:'cards'},...rows.map(([label,value,cls=''])=>h('div',{class:`card ${cls}`},h('span',{class:'muted',text:label}),h('strong',{text:String(value)}))));
const table=(heads,rows)=>{const t=h('table'),tr=h('tr');heads.forEach(x=>tr.append(h('th',{text:x})));t.append(tr);for(const row of rows){const r=h('tr');row.forEach(x=>r.append(h('td',{text:String(x??'—')})));t.append(r);}return t;};
AdminConsoleUI.prototype.render_suppliers=function(){const d=adminOperationalSection('suppliers',this.context)||{};this.body.append(h('div',{class:'section-note',text:'Globale Lieferantenübersicht. Langsame, deaktivierte oder unzuverlässige Lieferanten fallen hier sofort auf.'}),cards([['Lieferanten',d.total||0],['Aktiv',d.active||0],['Inaktiv',d.inactive||0,d.inactive?'warn':''],['> 7 Tage Lieferzeit',d.slow||0,d.slow?'warn':''],['Unzuverlässig',d.unreliable||0,d.unreliable?'bad':'ok']]));const rows=(d.rows||[]).slice(0,500).map(x=>[x.name,x.country||'—',x.status,x.leadTimeHours?`${x.leadTimeHours} h`:'—',x.reliability?`${Math.round(x.reliability*100)} %`:'—',x.minimumOrder||'—',(x.items||[]).length]);this.body.append(h('div',{class:'panel'},h('h3',{text:`Lieferanten (${rows.length})`}),table(['Name','Land/Region','Status','Lieferzeit','Zuverlässigkeit','Mindestbestellung','Artikel'],rows)));};
AdminConsoleUI.prototype.render_awards=function(){const d=adminOperationalSection('awards',this.context)||{};this.body.append(h('div',{class:'section-note',text:'Auszeichnungen und Erfolge aller Spieler. Hier siehst du, welche Erfolge besonders häufig oder selten erreicht werden.'}),cards([['Katalog',d.catalogCount||0],['Vergebene Auszeichnungen',d.grants||0],['Spieler mit Auszeichnung',d.playersWithAwards||0]]));const top=(d.top||[]).map(x=>[x.award,x.count]);this.body.append(h('div',{class:'grid2'},h('div',{class:'panel'},h('h3',{text:'Häufigste Auszeichnungen'}),top.length?table(['Auszeichnung','Vergaben'],top):h('div',{class:'muted',text:'Noch keine Vergaben gefunden.'})),h('div',{class:'panel'},h('h3',{text:'Letzte Vergaben'}),table(['Spieler','Auszeichnung','Zeit'],(d.recent||[]).slice(0,100).map(x=>[x.playerName||x.playerId,x.name||x.awardId,x.grantedAt?new Date(x.grantedAt).toLocaleString('de-DE'):'—'])))));};
if(typeof window!=='undefined')window.worldAdminSupplierAwardViews=true;
