// WorldProject – sichere Adminaktionen für Lieferanten.
import { adminControlSystem } from './AdminControlSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const list=world=>Array.isArray(world?.suppliers)?world.suppliers:Array.isArray(world?.supplierCatalog)?world.supplierCatalog:Array.isArray(world?.vendorCatalog)?world.vendorCatalog:[];
export function findAdminSupplier(world,id){const key=String(id||'');return list(world).find(s=>String(s.id||s.supplierId||s.vendorId)===key)||null;}
export function setSupplierActive(actor,world,{supplierId,active,reason=''}={}){adminControlSystem.requirePermission(actor,'suppliers.write');const why=String(reason||'').trim();if(why.length<3)throw new Error('Begründung erforderlich');const s=findAdminSupplier(world,supplierId);if(!s)throw new Error('Lieferant fehlt');const before={active:s.active,status:s.status};s.active=!!active;s.status=active?(s.status==='disabled'?'active':s.status||'active'):'disabled';adminControlSystem.log(actor,'supplier_active_changed',{supplierId,before,after:{active:s.active,status:s.status},reason:why});return s;}
export function setSupplierLeadTime(actor,world,{supplierId,hours,reason=''}={}){adminControlSystem.requirePermission(actor,'suppliers.write');const why=String(reason||'').trim(),value=n(hours);if(why.length<3)throw new Error('Begründung erforderlich');if(value<0||value>24*365)throw new Error('Ungültige Lieferzeit');const s=findAdminSupplier(world,supplierId);if(!s)throw new Error('Lieferant fehlt');const before=s.leadTimeHours??s.deliveryHours??s.leadTime??null;s.leadTimeHours=value;adminControlSystem.log(actor,'supplier_lead_time_changed',{supplierId,before,after:value,reason:why});return s;}
export function setSupplierReliability(actor,world,{supplierId,reliability,reason=''}={}){adminControlSystem.requirePermission(actor,'suppliers.write');const why=String(reason||'').trim(),value=n(reliability);if(why.length<3)throw new Error('Begründung erforderlich');if(value<0||value>1)throw new Error('Zuverlässigkeit muss zwischen 0 und 1 liegen');const s=findAdminSupplier(world,supplierId);if(!s)throw new Error('Lieferant fehlt');const before=s.reliability??s.serviceLevel??s.rating??null;s.reliability=value;adminControlSystem.log(actor,'supplier_reliability_changed',{supplierId,before,after:value,reason:why});return s;}
export function supplierAdminHealth(world={}){const rows=list(world),inactive=rows.filter(s=>s.active===false||s.status==='disabled'),slow=rows.filter(s=>n(s.leadTimeHours??s.deliveryHours??s.leadTime)>168),bad=rows.filter(s=>{const r=n(s.reliability??s.serviceLevel??s.rating,-1);return r>=0&&r<.8;});return{total:rows.length,inactive:inactive.length,slow:slow.length,unreliable:bad.length,success:rows.length>0&&inactive.length<rows.length};}
if(typeof window!=='undefined')window.worldAdminSupplierControl={find:findAdminSupplier,setActive:setSupplierActive,setLeadTime:setSupplierLeadTime,setReliability:setSupplierReliability,health:supplierAdminHealth};
