// Admin-Frontendmodell. Wird nur vom separaten adminBootstrap geladen.
import { AdminSections } from './AdminControlSystem.js';
import { adminSectionPayload } from './AdminDashboardData.js';
import { moderationKpis } from './ModerationCaseSystem.js';
import { supportKpis } from './SupportCaseSystem.js';
import { liveOpsKpis } from './LiveOpsSystem.js';
import { worldControlSnapshot } from './AdminWorldControl.js';
import { adminOperationalSection } from './AdminOperationsData.js';
const SECTION_PERMISSION={players:'players.read',companies:'companies.read',economy:'economy.write',market:'market.write',products:'products.write',suppliers:'suppliers.write',production:'production.write',transport:'transport.write',alliances:'alliances.write',premium:'premium.write',coins:'coins.write',awards:'awards.write',languages:'languages.write',npc:'npc.write',support:'support.write',moderation:'moderation.write',liveops:'liveops.write',system:'system.write',audit:'audit.read'};
export function adminNavigation(actor,admin){admin.requireAdmin(actor);return Object.values(AdminSections).map(id=>({id,label:id[0].toUpperCase()+id.slice(1),allowed:!SECTION_PERMISSION[id]||admin.can(actor,SECTION_PERMISSION[id])})).filter(x=>x.allowed);}
export function adminPageModel(actor,admin,section,context={}){admin.requireAdmin(actor);const required=SECTION_PERMISSION[section];if(required&&!admin.can(actor,required))throw new Error(`Keine Berechtigung für Adminbereich: ${section}`);const world=context.world||{},base={section,navigation:adminNavigation(actor,admin),actor:{id:actor.id,name:actor.username||actor.name,role:actor.role},generatedAt:Date.now()};const operational=adminOperationalSection(section,context);if(operational)return{...base,data:operational};switch(section){case AdminSections.OVERVIEW:return{...base,data:adminSectionPayload(actor,'overview',context)};case AdminSections.PLAYERS:return{...base,data:adminSectionPayload(actor,'players',context)};case AdminSections.COMPANIES:return{...base,data:adminSectionPayload(actor,'companies',context)};case AdminSections.SYSTEM:return{...base,data:{settings:admin.getSettings(actor),liveOps:liveOpsKpis(world),world:worldControlSnapshot(world)}};case AdminSections.SUPPORT:return{...base,data:{kpis:supportKpis(world),state:world.supportState||{cases:[],messages:[],compensations:[]}}};case AdminSections.MODERATION:return{...base,data:{kpis:moderationKpis(world),state:world.moderationState||world.moderation||{}}};case AdminSections.LIVEOPS:return{...base,data:{kpis:liveOpsKpis(world),state:world.liveOps||{events:[],rollouts:[],announcements:[]}}};case AdminSections.AUDIT:return{...base,data:{audit:admin.audit(actor),moderation:moderationKpis(world),support:supportKpis(world)}};default:return{...base,data:adminSectionPayload(actor,section,context)};}}
export function adminRoute(path='/admin/overview'){const raw=String(path).replace(/^.*\/admin\/?/,'').split(/[?#]/)[0]||'overview';return Object.values(AdminSections).includes(raw)?raw:AdminSections.OVERVIEW;}
export function createAdminFrontend(actor,admin,context={}){const state={section:AdminSections.OVERVIEW};return{state,navigate(section){state.section=adminRoute(`/admin/${section}`);return adminPageModel(actor,admin,state.section,context);},current(){return adminPageModel(actor,admin,state.section,context);},world(){return worldControlSnapshot(context.world||{});}};}
