// WorldProject – sichere Direktaktionen für Lieferanten/NPC in der bestehenden AdminConsoleUI.
import { AdminConsoleUI } from './AdminConsoleUI.js';
import { adminOperationalSection } from './AdminOperationsData.js';
import { setSupplierActive, setSupplierLeadTime, setSupplierReliability } from './AdminSupplierControl.js';
import { setNpcActive, setNpcBudget, setNpcMarketWeight, setNpcLiquidity } from './AdminNpcControl.js';
const h=(tag,props={},...kids)=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(props||{})){if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on')&&typeof v==='function')e.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==undefined&&v!==null)e.setAttribute(k,String(v));}for(const x of kids.flat())if(x!==null&&x!==undefined)e.append(x?.nodeType?x:document.createTextNode(String(x)));return e;};
const btn=(text,onclick,danger=false)=>h('button',{class:`action${danger?' danger':''}`,text,onclick});
const reason=label=>{const r=prompt(`Begründung für „${label}“:`);return r===null?null:String(r).trim();};
const baseSuppliers=AdminConsoleUI.prototype.render_suppliers;
AdminConsoleUI.prototype.render_suppliers=function(){baseSuppliers?.call(this);if(!this.admin.can(this.actor,'suppliers.write'))return;const d=adminOperationalSection('suppliers',this.context)||{},box=h('div',{class:'panel'},h('h3',{text:'Lieferanten-Schnellaktionen'}));for(const s of (d.rows||[]).slice(0,100)){const actions=h('div',{class:'toolbar'});actions.append(btn(s.active?'Deaktivieren':'Aktivieren',()=>{const r=reason('Lieferant umschalten');if(r===null)return;try{setSupplierActive(this.actor,this.world(),{supplierId:s.id,active:!s.active,reason:r});this.toast('Lieferant geändert');this.render();}catch(err){this.toast(err.message,true);}},s.active));actions.append(btn('Lieferzeit',()=>{const hours=Number(prompt('Lieferzeit in Stunden:',String(s.leadTimeHours||0)));if(!Number.isFinite(hours))return;const r=reason('Lieferzeit ändern');if(r===null)return;try{setSupplierLeadTime(this.actor,this.world(),{supplierId:s.id,hours,reason:r});this.toast('Lieferzeit geändert');this.render();}catch(err){this.toast(err.message,true);}}));actions.append(btn('Zuverlässigkeit',()=>{const percent=Number(prompt('Zuverlässigkeit in % (0–100):',String(Math.round((s.reliability||1)*100))));if(!Number.isFinite(percent))return;const r=reason('Zuverlässigkeit ändern');if(r===null)return;try{setSupplierReliability(this.actor,this.world(),{supplierId:s.id,reliability:percent/100,reason:r});this.toast('Zuverlässigkeit geändert');this.render();}catch(err){this.toast(err.message,true);}}));box.append(h('div',{class:'kv'},h('span',{text:`${s.name} · ${s.country||'—'}`}),actions));}if((d.rows||[]).length) this.body.append(box);};
const baseNpc=AdminConsoleUI.prototype.render_npc;
AdminConsoleUI.prototype.render_npc=function(){baseNpc?.call(this);if(!this.admin.can(this.actor,'npc.write'))return;const d=adminOperationalSection('npc',this.context)||{},box=h('div',{class:'panel'},h('h3',{text:'NPC-Schnellaktionen'}),h('div',{class:'toolbar'},btn(this.admin.settings.npcLiquidityEnabled?'NPC-Liquidität ausschalten':'NPC-Liquidität einschalten',()=>{const r=reason('NPC-Liquidität ändern');if(r===null)return;try{setNpcLiquidity(this.actor,{enabled:!this.admin.settings.npcLiquidityEnabled,reason:r});this.toast('NPC-Liquidität geändert');this.render();}catch(err){this.toast(err.message,true);}},this.admin.settings.npcLiquidityEnabled)));for(const npc of (d.rows||[]).slice(0,100)){const id=npc.id||npc.npcId||npc.companyId,actions=h('div',{class:'toolbar'});actions.append(btn(npc.active===false?'Aktivieren':'Deaktivieren',()=>{const r=reason('NPC umschalten');if(r===null)return;try{setNpcActive(this.actor,this.world(),{npcId:id,active:npc.active===false,reason:r});this.toast('NPC geändert');this.render();}catch(err){this.toast(err.message,true);}},npc.active!==false));actions.append(btn('Budget',()=>{const value=Number(prompt('NPC-Budget:',String(npc.budget??npc.money??0)));if(!Number.isFinite(value))return;const r=reason('NPC-Budget ändern');if(r===null)return;try{setNpcBudget(this.actor,this.world(),{npcId:id,budget:value,reason:r});this.toast('NPC-Budget geändert');this.render();}catch(err){this.toast(err.message,true);}}));actions.append(btn('Marktgewicht',()=>{const value=Number(prompt('Marktgewicht 0–10:',String(npc.marketWeight??1)));if(!Number.isFinite(value))return;const r=reason('NPC-Marktgewicht ändern');if(r===null)return;try{setNpcMarketWeight(this.actor,this.world(),{npcId:id,weight:value,reason:r});this.toast('Marktgewicht geändert');this.render();}catch(err){this.toast(err.message,true);}}));box.append(h('div',{class:'kv'},h('span',{text:`${npc.name||id} · ${npc.active===false?'Inaktiv':'Aktiv'}`}),actions));}this.body.append(box);};
if(typeof window!=='undefined')window.worldAdminSupplierNpcActions=true;
