// WorldProject – Datenmodell für den sichtbaren Adminbereich. Keine Spieler-UI.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const arr=v=>Array.isArray(v)?v:[];
const limitOf=v=>Math.max(1,Math.min(1000,Math.floor(n(v,100))));
export function adminPlayerRow(p={}){return{id:p.id||p.userId||'',username:p.username||p.name||"",email:p.email||"",country:p.country||"",language:p.language||p.locale||'',createdAt:p.createdAt||null,lastLoginAt:p.lastLoginAt||null,suspended:!!p.moderation?.suspended,muted:!!p.moderation?.muted,companyIds:arr(p.companyIds),premium:!!(p.premium||p.premiumActive),premiumUntil:p.premiumUntil||null,coins:n(p.coins)};}
export function adminCompanyRow(c={}){const jobs=arr(c.productionJobs),deliveries=arr(c.inboundDeliveries??c.deliveries);return{id:c.id||c.companyId||c.serverCompanyId||'',name:c.name||c.companyName||"",ownerId:c.ownerId||c.playerId||null,type:c.type||c.company_type||"",branchKey:c.branchKey||"",status:c.status||'active',money:n(c.money),employees:arr(c.employees).length,machines:arr(c.buildingState?.equipment).length,vehicles:arr(c.vehicles??c.fleet).length,openJobs:jobs.filter(x=>!["done","finished","completed","cancelled","admin_cancelled"].includes(x.status)).length,openDeliveries:deliveries.filter(x=>!["delivered","arrived","completed","cancelled"].includes(x.status)).length,inventoryItems:Object.keys(c.inventory||{}).length,finishedItems:Object.keys(c.finishedGoods||{}).length};}
export function searchAdminPlayers(actor,players,{query="",suspended=null,muted=null,premium=null,country=null,limit=100,offset=0}={}){adminControlSystem.requirePermission(actor,"players.read");const q=String(query||'').trim().toLowerCase(),rows=arr(players).map(adminPlayerRow).filter(x=>(!q||[x.id,x.username,x.email,x.country,x.language].some(v=>String(v||"").toLowerCase().includes(q)))&&(suspended===null||suspended===undefined||x.suspended===!!suspended)&&(muted===null||muted===undefined||x.muted===!!muted)&&(premium===null||premium===undefined||x.premium===!!premium)&&(!country||String(x.country).toLowerCase()===String(country).toLowerCase()));const start=Math.max(0,Math.floor(n(offset)));return rows.slice(start,start+limitOf(limit));}
export function searchAdminCompanies(actor,companies,{query="",type=null,branchKey=null,status=null,ownerId=null,limit=100,offset=0}={}){adminControlSystem.requirePermission(actor,"companies.read");const q=String(query||'').trim().toLowerCase(),rows=arr(companies).map(adminCompanyRow).filter(x=>(!q||[x.id,x.name,x.ownerId,x.type,x.branchKey,x.status].some(v=>String(v||"").toLowerCase().includes(q)))&&(!type||x.type===type)&&(!branchKey||x.branchKey===branchKey)&&(!status||x.status===status)&&(!ownerId||String(x.ownerId)===String(ownerId)));const start=Math.max(0,Math.floor(n(offset)));return rows.slice(start,start+limitOf(limit));}
export function adminCompanyDetail(actor,c){adminControlSystem.requirePermission(actor,"companies.read");if(!c)throw new Error('Betrieb fehlt');return{summary:adminCompanyRow(c),inventory:{...(c.inventory||{})},finishedGoods:{...(c.finishedGoods||{})},employees:arr(c.employees).map(e=>({...e})),machines:arr(c.buildingState?.equipment).map(m=>({...m})),jobs:arr(c.productionJobs).map(j=>({...j})),orders:arr(c.customerOrders).map(o=>({...o})),deliveries:arr(c.inboundDeliveries??c.deliveries).map(d=>({...d})),vehicles:arr(c.vehicles??c.fleet).map(v=>({...v})),salesLedger:arr(c.salesLedger).slice(-500),costLedger:arr(c.costLedger).slice(-500),sites:arr(c.sites).map(s=>({...s})),contracts:c.contracts||null,finance:c.finance||null,growth:c.growth||null,risk:c.risk||null,sustainability:c.sustainability||null,lastIntegrityRepair:c.adminLastIntegrityRepair||null};}
export function adminPlayerDetail(actor,p){adminControlSystem.requirePermission(actor,"players.read");if(!p)throw new Error('Spieler fehlt');return{summary:adminPlayerRow(p),moderation:{...(p.moderation||{})},companies:arr(p.companyIds),profile:{country:p.country||'',language:p.language||p.locale||'',createdAt:p.createdAt||null,lastLoginAt:p.lastLoginAt||null},rawFlags:{loginLocked:!!p.loginLocked,failedLogins:n(p.failedLogins),premium:!!(p.premium||p.premiumActive)}};}
export function adminWorldOverview(actor,{players=[],companies=[],world={}}={}){adminControlSystem.requireAdmin(actor);const ps=arr(players),cs=arr(companies),totalMoney=cs.reduce((s,c)=>s+n(c.money),0),activeCompanies=cs.filter(c=>c.status!=="closed").length;return{players:ps.length,companies:cs.length,activeCompanies,totalMoney,averageCompanyMoney:cs.length?totalMoney/cs.length:0,suspendedPlayers:ps.filter(p=>p.moderation?.suspended).length,mutedPlayers:ps.filter(p=>p.moderation?.muted).length,premiumPlayers:ps.filter(p=>p.premium||p.premiumActive).length,allianceCount:arr(world.alliances).length,featureFlags:{...adminControlSystem.settings},worldTime:world.time||world.gameTime||null,economy:world.economy||null};}
export function adminSectionPayload(actor,section,ctx={}){switch(section){case"overview":return adminWorldOverview(actor,ctx);case"players":return searchAdminPlayers(actor,arr(ctx.players),ctx.filters||{});case"companies":return searchAdminCompanies(actor,arr(ctx.companies),ctx.filters||{});case"audit":return adminControlSystem.audit(actor,ctx.filters||{});default:return{section,available:true};}}
if(typeof window!=="undefined")window.worldAdminDashboardData={playerRow:adminPlayerRow,playerDetail:adminPlayerDetail,companyRow:adminCompanyRow,companyDetail:adminCompanyDetail,worldOverview:adminWorldOverview,searchPlayers:searchAdminPlayers,searchCompanies:searchAdminCompanies};
