// WorldProject – persistiert kritische Adminänderungen über serverseitig rollenprüfende RPCs.
const api=()=>window.worldAccounts?.authApi;
const id=x=>Number(x?.id||x?.user_id||x?.companyId||x?.serverCompanyId||0);
function notice(message,bad=false){if(typeof document==='undefined')return;const t=document.createElement('div');t.textContent=message;Object.assign(t.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:'100020',background:bad?'#8b1e24':'#176b36',color:'#fff',padding:'10px 14px',borderRadius:'8px',fontWeight:'800',boxShadow:'0 5px 18px rgba(0,0,0,.4)'});document.body.append(t);setTimeout(()=>t.remove(),3500);}
async function call(name,payload,label){const client=api();if(!client?.rpc)throw new Error('Server-API nicht verfügbar');try{const result=await client.rpc(name,payload);notice(`✅ ${label} serverseitig gespeichert`);window.dispatchEvent(new CustomEvent('world:admin-server-saved',{detail:{name,payload,result}}));return result;}catch(error){notice(`❌ ${label} NICHT gespeichert: ${error.message}`,true);window.dispatchEvent(new CustomEvent('world:admin-server-save-failed',{detail:{name,payload,error:error.message}}));throw error;}}
export async function persistCompanyMoney(company,amount,reason){const companyId=id(company);if(!companyId)throw new Error('Server-Betriebs-ID fehlt');const result=await call('admin_set_company_money',{p_company_id:companyId,p_amount:Number(amount),p_reason:String(reason||'')},'Firmenkapital');const row=Array.isArray(result)?result[0]:result;if(row&&company)Object.assign(company,row);return row;}
export async function persistPlayerPremium(player,{enabled,until=null,reason=''}){const userId=id(player);if(!userId)throw new Error('Server-Spieler-ID fehlt');const iso=until?new Date(Number(until)).toISOString():null,result=await call('admin_set_user_premium',{p_user_id:userId,p_enabled:!!enabled,p_until:iso,p_reason:String(reason||'')},'Premiumstatus'),row=Array.isArray(result)?result[0]:result;if(row&&player)Object.assign(player,row,{premium:!!enabled,premiumActive:!!enabled,premiumUntil:row.premium_until?new Date(row.premium_until).getTime():0});return row;}
export async function persistPlayerCoins(player,{delta,reason=''}){const userId=id(player);if(!userId)throw new Error('Server-Spieler-ID fehlt');const result=await call('admin_adjust_user_coins',{p_user_id:userId,p_delta:Math.trunc(Number(delta)),p_reason:String(reason||'')},'Coins'),value=Number(Array.isArray(result)?result[0]:result);if(Number.isFinite(value)&&player)player.coins=value;return value;}
export const adminServerPersistence={companyMoney:persistCompanyMoney,playerPremium:persistPlayerPremium,playerCoins:persistPlayerCoins};
if(typeof window!=='undefined')window.worldAdminServerPersistence=adminServerPersistence;
