// WorldProject – reine Admin-Übersichtsdaten und Betriebsdiagnose.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const arr=v=>Array.isArray(v)?v:[];
const idOf=c=>c?.serverCompanyId||c?.companyId||c?.id||'';
const openStatus=new Set(['queued','planned','pending','running','active','in_progress','producing']);
export function adminCompanySummary(company={}){const jobs=arr(company.productionJobs),deliveries=arr(company.inboundDeliveries??company.deliveries),equipment=arr(company.buildingState?.equipment),employees=arr(company.employees),vehicles=arr(company.vehicles??company.fleet),inventory=company.inventory||{},finished=company.finishedGoods||{};return{id:idOf(company),name:company.name||company.companyName||'',type:company.type||company.company_type||'',branchKey:company.branchKey||'',status:company.status||'active',setupPhase:company.setupPhase||null,money:n(company.money),employees:employees.length,vehicles:vehicles.length,machines:equipment.length,jobs:jobs.length,openJobs:jobs.filter(j=>openStatus.has(j.status)).length,deliveries:deliveries.length,openDeliveries:deliveries.filter(d=>!['delivered','arrived','completed','cancelled'].includes(d.status)).length,inventoryItems:Object.keys(inventory).length,finishedItems:Object.keys(finished).length,storageUsed:n(company.storageUsed??company.warehouse?.used),storageCapacity:n(company.storageCapacity??company.warehouse?.capacity),premium:!!(company.premium||company.premiumActive)};}
export function diagnoseCompany(company={},{now=Date.now()}={}){const summary=adminCompanySummary(company),issues=[],jobs=arr(company.productionJobs),deliveries=arr(company.inboundDeliveries??company.deliveries),equipment=arr(company.buildingState?.equipment),employees=arr(company.employees);if(!summary.id)issues.push({severity:'high',code:'missing_company_id',message:'Betriebs-ID fehlt'});if(summary.money<0)issues.push({severity:'critical',code:'negative_cash',message:'Firmenkonto ist negativ',value:summary.money});if(summary.storageCapacity>0&&summary.storageUsed>summary.storageCapacity)issues.push({severity:'high',code:'storage_overflow',message:'Lagerkapazität überschritten',value:summary.storageUsed,capacity:summary.storageCapacity});for(const job of jobs.filter(j=>['running','active','in_progress','producing'].includes(j.status))){const end=n(job.endsAt??job.endAt??job.busyUntil);if(end&&end<now-60000)issues.push({severity:'high',code:'stuck_production',message:'Produktion scheint überfällig',jobId:job.id,end});}for(const d of deliveries.filter(x=>!['delivered','arrived','completed','cancelled'].includes(x.status))){const eta=n(d.eta??d.arrivalAt??d.expectedAt);if(eta&&eta<now)issues.push({severity:'medium',code:'late_delivery',message:'Lieferung ist überfällig',deliveryId:d.id,eta});}for(const m of equipment){const condition=n(m.condition,100);if(condition<=0||['broken','defect','failed'].includes(m.status))issues.push({severity:'high',code:'broken_machine',message:'Maschine ist defekt',machineId:m.instanceId||m.id});else if(condition<20)issues.push({severity:'medium',code:'machine_condition_low',message:'Maschinenzustand kritisch',machineId:m.instanceId||m.id,condition});}for(const e of employees){if(['blocked','invalid'].includes(e.status))issues.push({severity:'medium',code:'employee_invalid_status',message:'Mitarbeiterstatus auffällig',employeeId:e.id||e.employeeId,status:e.status});}const severityWeight={critical:4,high:3,medium:2,low:1},score=Math.max(0,100-issues.reduce((s,i)=>s+(severityWeight[i.severity]||1)*5,0));return{summary,healthScore:score,healthy:issues.length===0,issues,critical:issues.filter(i=>i.severity==='critical').length,high:issues.filter(i=>i.severity==='high').length,medium:issues.filter(i=>i.severity==='medium').length};}
export function adminFleetHealth(companies=[],opts={}){const rows=arr(companies).map(c=>diagnoseCompany(c,opts)),issues=rows.flatMap(r=>r.issues.map(i=>({...i,companyId:r.summary.id,companyName:r.summary.name})));return{companies:rows.length,healthy:rows.filter(r=>r.healthy).length,unhealthy:rows.filter(r=>!r.healthy).length,averageHealth:rows.length?Math.round(rows.reduce((s,r)=>s+r.healthScore,0)/rows.length):100,criticalIssues:issues.filter(i=>i.severity==='critical').length,highIssues:issues.filter(i=>i.severity==='high').length,issues:issues.sort((a,b)=>({critical:4,high:3,medium:2,low:1}[b.severity]-({critical:4,high:3,medium:2,low:1}[a.severity])).slice(0,500),rows};}
if(typeof window!=='undefined')window.worldAdminOperationsOverview={summary:adminCompanySummary,diagnose:diagnoseCompany,fleet:adminFleetHealth};
