// WorldProject – persistiert kritische Adminänderungen über serverseitig rollenprüfende RPCs.
const api=()=>window.worldAccounts?.authApi;
const id=x=>Number(x?.id||x?.user_id||x?.companyId||x?.serverCompanyId||0);
function notice(message,bad=false){if(typeof document==='undefined')return;const t=document.createElement('div');t.textContent=message;Object.assign(t.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:'100020',background:bad?'#8b1e24':'#176b36',color:'#fff',padding:'10px 14px',borderRadius:'8px',fontWeight:'800',boxShadow:'0 5px 18px rgba(0,0,0,.4)'});document.body.append(t);setTimeout(()=>t.remove(),3500);}
async function query(name,payload={}){const client=api();if(!client?.rpc)throw new Error('Server-API nicht verfügbar');return client.rpc(name,payload);}
async function call(name,payload,label){try{const result=await query(name,payload);notice(`✅ ${label} serverseitig gespeichert`);window.dispatchEvent(new CustomEvent('world:admin-server-saved',{detail:{name,payload,result}}));return result;}catch(error){notice(`❌ ${label} NICHT gespeichert: ${error.message}`,true);window.dispatchEvent(new CustomEvent('world:admin-server-save-failed',{detail:{name,payload,error:error.message}}));throw error;}}
const rowOf=r=>Array.isArray(r)?r[0]:r;
export async function persistCompanyMoney(company,amount,reason){const companyId=id(company);if(!companyId)throw new Error('Server-Betriebs-ID fehlt');const row=rowOf(await call('admin_set_company_money',{p_company_id:companyId,p_amount:Number(amount),p_reason:String(reason||'')},'Firmenkapital'));if(row&&company)Object.assign(company,row);return row;}
export async function persistPlayerPremium(player,{enabled,until=null,reason=''}){const userId=id(player);if(!userId)throw new Error('Server-Spieler-ID fehlt');const iso=until?new Date(Number(until)).toISOString():null,row=rowOf(await call('admin_set_user_premium',{p_user_id:userId,p_enabled:!!enabled,p_until:iso,p_reason:String(reason||'')},'Premiumstatus'));if(row&&player)Object.assign(player,row,{premium:!!enabled,premiumActive:!!enabled,premiumUntil:row.premium_until?new Date(row.premium_until).getTime():0});return row;}
export async function persistPlayerCoins(player,{delta,reason=''}){const userId=id(player);if(!userId)throw new Error('Server-Spieler-ID fehlt');const result=await call('admin_adjust_user_coins',{p_user_id:userId,p_delta:Math.trunc(Number(delta)),p_reason:String(reason||'')},'Coins'),value=Number(rowOf(result));if(Number.isFinite(value)&&player)player.coins=value;return value;}
export async function persistPlayerStatus(player,{status,reason=''}){const userId=id(player);if(!userId)throw new Error('Server-Spieler-ID fehlt');const row=rowOf(await call('admin_set_user_status',{p_user_id:userId,p_status:String(status),p_reason:String(reason||'')},'Spielerstatus'));if(row&&player)Object.assign(player,row);return row;}
export async function persistPlayerUnlock(player,reason=''){const userId=id(player);if(!userId)throw new Error('Server-Spieler-ID fehlt');const row=rowOf(await call('admin_unlock_user',{p_user_id:userId,p_reason:String(reason||'')},'Login-Sperre'));if(row&&player)Object.assign(player,row);return row;}
export async function persistCompanyName(company,name,reason=''){const companyId=id(company);if(!companyId)throw new Error('Server-Betriebs-ID fehlt');const row=rowOf(await call('admin_rename_company',{p_company_id:companyId,p_name:String(name),p_reason:String(reason||'')},'Firmenname'));if(row&&company)Object.assign(company,row,{companyName:row.name});return row;}
export async function listFinancialTransactions({limit=100,userId=null}={}){const rows=await query('admin_list_financial_transactions',{p_limit:Math.max(1,Math.min(250,Math.trunc(Number(limit)||100))),p_user_id:userId?Number(userId):null});return Array.isArray(rows)?rows:[];}
export async function recoverFinancialTransaction(transactionId,reason=''){const txId=Number(transactionId);if(!txId)throw new Error('Transaktions-ID fehlt');return rowOf(await call('admin_recover_financial_transaction',{p_transaction_id:txId,p_reason:String(reason||'')},'Finanztransaktion'));}
export const adminServerPersistence={companyMoney:persistCompanyMoney,playerPremium:persistPlayerPremium,playerCoins:persistPlayerCoins,playerStatus:persistPlayerStatus,playerUnlock:persistPlayerUnlock,companyName:persistCompanyName,financialTransactions:listFinancialTransactions,recoverFinancialTransaction};
if(typeof window!=='undefined')window.worldAdminServerPersistence=adminServerPersistence;
