// WorldProject – Sicherheits-/Integrationsschicht für Admin und versteckte Allianzen.
import { adminControlSystem } from "./AdminControlSystem.js";
import { AllianceFeatureFlags, setAllianceFeatureFlag } from "./AllianceSystem.js";
const critical=new Set(["maintenanceMode","registrationEnabled","alliancesEnabled","premiumEnabled","globalChatEnabled"]);
const text=v=>String(v||"").trim();
export function adminSafetyCheck(actor,{action,target,value=null,reason=""}={}){adminControlSystem.requireAdmin(actor);const warnings=[];let allowed=true;if(action==="setting"&&critical.has(target)){warnings.push("kritische_systemeinstellung");if(!text(reason)){warnings.push("begruendung_fehlt");allowed=false;}}if(action==="money"&&Math.abs(Number(value)||0)>1000000000)warnings.push("extreme_geldmenge");if(action==="suspend"&&target===actor.id){warnings.push("selbstsperre");allowed=false;}if(action==="alliance_release"&&value?.creation&&!value?.visible){warnings.push("allianzgruendung_ohne_sichtbarkeit");allowed=false;}if(action==="alliance_release"&&value?.applications&&!value?.visible){warnings.push("allianzbewerbung_ohne_sichtbarkeit");allowed=false;}return{allowed,warnings,critical:warnings.length>0};}
export function safeAdminSetting(actor,key,value,{reason=""}={}){const check=adminSafetyCheck(actor,{action:"setting",target:key,value,reason});if(!check.allowed)throw new Error(`Admin-Sicherheitsprüfung fehlgeschlagen: ${check.warnings.join(", ")}`);const result=adminControlSystem.updateSetting(actor,key,value);adminControlSystem.log(actor,"safe_setting_applied",{key,value,reason:text(reason),warnings:check.warnings});return{...result,warnings:check.warnings};}
export function adminAllianceRelease(actor,{visible=false,creation=false,applications=false,ranking=false,reason=""}={}){adminControlSystem.requirePermission(actor,"alliances.write");const payload={visible:!!visible,creation:!!creation,applications:!!applications,ranking:!!ranking},check=adminSafetyCheck(actor,{action:"alliance_release",target:"alliances",value:payload,reason});if(!check.allowed)throw new Error(`Allianz-Freigabe unzulässig: ${check.warnings.join(", ")}`);if((payload.visible||payload.creation||payload.applications||payload.ranking)&&!text(reason))throw new Error("Begründung für Allianz-Freigabe erforderlich");safeAdminSetting(actor,"alliancesEnabled",payload.visible,{reason:text(reason)||"Allianzen deaktiviert"});setAllianceFeatureFlag("playerVisible",payload.visible);setAllianceFeatureFlag("creationEnabled",payload.visible&&payload.creation);setAllianceFeatureFlag("applicationsEnabled",payload.visible&&payload.applications);setAllianceFeatureFlag("publicRanking",payload.visible&&payload.ranking);adminControlSystem.log(actor,"alliance_release_changed",{...payload,reason:text(reason),warnings:check.warnings});return{adminEnabled:adminControlSystem.settings.alliancesEnabled,flags:{...AllianceFeatureFlags},warnings:check.warnings};}
export function disableAlliancesImmediately(actor,{reason="emergency disable"}={}){return adminAllianceRelease(actor,{visible:false,creation:false,applications:false,ranking:false,reason:text(reason)||"emergency disable"});}
export function validateAdminConfiguration(){const issues=[];if(AllianceFeatureFlags.playerVisible&&!adminControlSystem.settings.alliancesEnabled)issues.push("Allianz sichtbar, aber Admin-Flag deaktiviert");if(AllianceFeatureFlags.creationEnabled&&!AllianceFeatureFlags.playerVisible)issues.push("Allianzgründung aktiv, obwohl Spieleransicht verborgen");if(AllianceFeatureFlags.applicationsEnabled&&!AllianceFeatureFlags.playerVisible)issues.push("Allianzbewerbungen aktiv, obwohl Spieleransicht verborgen");if(AllianceFeatureFlags.publicRanking&&!AllianceFeatureFlags.playerVisible)issues.push("Allianzranking aktiv, obwohl Spieleransicht verborgen");if(!adminControlSystem.settings.registrationEnabled&&adminControlSystem.settings.maintenanceMode)issues.push("Registrierung und Wartungsmodus gleichzeitig blockieren regulären Spielerzugang");return{success:issues.length===0,issues,allianceFlags:{...AllianceFeatureFlags},adminSettings:{...adminControlSystem.settings}};}
export function adminAuditIntegrity(){const log=adminControlSystem.auditLog||[],ids=log.map(x=>x.id),duplicates=ids.filter((id,i)=>ids.indexOf(id)!==i),missingActor=log.filter(x=>!x.actorId&&x.action!=="system_init"),invalidTime=log.filter(x=>!x.at||Number.isNaN(Date.parse(x.at)));return{success:duplicates.length===0&&missingActor.length===0&&invalidTime.length===0,entries:log.length,duplicateIds:[...new Set(duplicates)],missingActor:missingActor.length,invalidTime:invalidTime.length};}
export function adminHealthSnapshot(){const config=validateAdminConfiguration(),audit=adminAuditIntegrity();return{success:config.success&&audit.success,config,audit,staff:adminControlSystem.staff.filter(x=>x.active).length,allianceHidden:!AllianceFeatureFlags.playerVisible,checkedAt:Date.now()};}
if(typeof window!=="undefined")window.worldAdminSecurity={health:adminHealthSnapshot,allianceRelease:adminAllianceRelease,safety:adminSafetyCheck};
