// WorldProject – Analyse- und Suchschicht für das bestehende Admin-Auditlog.
import { adminControlSystem } from './AdminControlSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const text=v=>String(v??'').toLowerCase();
export function searchAdminAudit(actor,{query='',action=null,actorId=null,role=null,from=null,to=null,limit=500,offset=0}={}){adminControlSystem.requirePermission(actor,'audit.read');const q=text(query),start=from==null?null:new Date(from).getTime(),end=to==null?null:new Date(to).getTime(),rows=adminControlSystem.auditLog.filter(x=>{const at=Date.parse(x.at);if(action&&x.action!==action)return false;if(actorId&&String(x.actorId)!==String(actorId))return false;if(role&&x.role!==role)return false;if(start!==null&&Number.isFinite(start)&&at<start)return false;if(end!==null&&Number.isFinite(end)&&at>end)return false;if(q&&!text(`${x.action} ${x.actorId} ${x.actorName} ${x.role} ${JSON.stringify(x.details||{})}`).includes(q))return false;return true;}).reverse();const begin=Math.max(0,Math.floor(n(offset))),take=Math.max(1,Math.min(2000,Math.floor(n(limit,500))));return{total:rows.length,offset:begin,limit:take,rows:rows.slice(begin,begin+take),hasMore:begin+take<rows.length};}
export function adminAuditKpis(actor,{hours=24}={}){adminControlSystem.requirePermission(actor,'audit.read');const now=Date.now(),since=now-Math.max(1,n(hours,24))*3600000,rows=adminControlSystem.auditLog.filter(x=>Date.parse(x.at)>=since),byAction={},byActor={},byRole={};for(const x of rows){byAction[x.action]=(byAction[x.action]||0)+1;const who=x.actorName||x.actorId||'unbekannt';byActor[who]=(byActor[who]||0)+1;byRole[x.role||'unbekannt']=(byRole[x.role||'unbekannt']||0)+1;}const sort=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]).map(([key,count])=>({key,count}));return{hours:Math.max(1,n(hours,24)),entries:rows.length,totalEntries:adminControlSystem.auditLog.length,actions:sort(byAction),actors:sort(byActor),roles:sort(byRole),lastEntry:adminControlSystem.auditLog.at(-1)||null};}
export function adminAuditAnomalies(actor,{hours=24,actionThreshold=50,actorThreshold=100}={}){const k=adminAuditKpis(actor,{hours}),alerts=[];for(const row of k.actions.filter(x=>x.count>=actionThreshold))alerts.push({severity:'medium',code:'action_spike',message:`Viele Adminaktionen „${row.key}“`,count:row.count});for(const row of k.actors.filter(x=>x.count>=actorThreshold))alerts.push({severity:'high',code:'actor_spike',message:`Sehr viele Adminaktionen durch ${row.key}`,count:row.count});const sensitive=/money|coins|inventory|premium|suspend|ban|market|world|release|rollback|maintenance|alliance/i,recent=adminControlSystem.auditLog.filter(x=>Date.parse(x.at)>=Date.now()-Math.max(1,n(hours,24))*3600000&&sensitive.test(x.action));if(recent.length>=Math.max(10,actionThreshold))alerts.push({severity:'high',code:'sensitive_spike',message:'Viele kritische Adminänderungen im Zeitraum',count:recent.length});return{success:alerts.length===0,alerts,kpis:k};}
export function exportAdminAudit(actor,filters={}){const result=searchAdminAudit(actor,{...filters,limit:2000,offset:0});return{exportedAt:new Date().toISOString(),filters:{...filters},totalMatched:result.total,rows:result.rows.map(x=>({...x,details:JSON.parse(JSON.stringify(x.details||{}))}))};}
if(typeof window!=='undefined')window.worldAdminAuditAnalytics={search:searchAdminAudit,kpis:adminAuditKpis,anomalies:adminAuditAnomalies,export:exportAdminAudit};
