// WorldProject – sichere Adminsteuerung für NPC/AI-Wirtschaft.
import { adminControlSystem } from './AdminControlSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const rows=world=>Array.isArray(world?.npcs)?world.npcs:Array.isArray(world?.aiCompanies)?world.aiCompanies:Array.isArray(world?.aiPlayers)?world.aiPlayers:[];
export function findNpc(world,id){const key=String(id||'');return rows(world).find(x=>String(x.id||x.npcId||x.companyId)===key)||null;}
export function setNpcActive(actor,world,{npcId,active,reason=''}={}){adminControlSystem.requirePermission(actor,'npc.write');const why=String(reason||'').trim();if(why.length<3)throw new Error('Begründung erforderlich');const npc=findNpc(world,npcId);if(!npc)throw new Error('NPC fehlt');const before=npc.active;npc.active=!!active;adminControlSystem.log(actor,'npc_active_changed',{npcId,before,after:npc.active,reason:why});return npc;}
export function setNpcBudget(actor,world,{npcId,budget,reason=''}={}){adminControlSystem.requirePermission(actor,'npc.write');const why=String(reason||'').trim(),value=n(budget);if(why.length<3)throw new Error('Begründung erforderlich');if(value<0||value>1e12)throw new Error('Ungültiges NPC-Budget');const npc=findNpc(world,npcId);if(!npc)throw new Error('NPC fehlt');const before=npc.budget??npc.money??0;if('budget' in npc)npc.budget=value;else npc.money=value;adminControlSystem.log(actor,'npc_budget_changed',{npcId,before,after:value,reason:why});return npc;}
export function setNpcMarketWeight(actor,world,{npcId,weight,reason=''}={}){adminControlSystem.requirePermission(actor,'npc.write');const why=String(reason||'').trim(),value=n(weight);if(why.length<3)throw new Error('Begründung erforderlich');if(value<0||value>10)throw new Error('Marktgewicht muss zwischen 0 und 10 liegen');const npc=findNpc(world,npcId);if(!npc)throw new Error('NPC fehlt');const before=npc.marketWeight??1;npc.marketWeight=value;adminControlSystem.log(actor,'npc_market_weight_changed',{npcId,before,after:value,reason:why});return npc;}
export function setNpcLiquidity(actor,{enabled,reason=''}={}){adminControlSystem.requirePermission(actor,'npc.write');const why=String(reason||'').trim();if(why.length<3)throw new Error('Begründung erforderlich');const before=adminControlSystem.settings.npcLiquidityEnabled;adminControlSystem.settings.npcLiquidityEnabled=!!enabled;adminControlSystem.log(actor,'npc_liquidity_changed',{before,after:!!enabled,reason:why});return !!enabled;}
export function npcControlHealth(world={}){const all=rows(world),active=all.filter(x=>x.active!==false),invalid=all.filter(x=>n(x.marketWeight,1)<0||n(x.marketWeight,1)>10||n(x.budget??x.money,0)<0);return{total:all.length,active:active.length,inactive:all.length-active.length,invalid:invalid.length,liquidityEnabled:adminControlSystem.settings.npcLiquidityEnabled,success:invalid.length===0};}
if(typeof window!=='undefined')window.worldAdminNpcControl={find:findNpc,setActive:setNpcActive,setBudget:setNpcBudget,setMarketWeight:setNpcMarketWeight,setLiquidity:setNpcLiquidity,health:npcControlHealth};
