// WorldProject – kontrollierte Weltsteuerung durch Admins.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureWorldControl(world={}){world.adminWorld??={timeScale:1,paused:false,market:{demand:1,rawMaterialPrice:1,energyPrice:1,transportPrice:1,npcLiquidity:1},regions:{},history:[]};return world.adminWorld;}
const history=(w,entry)=>{w.history.push({...entry,at:Date.now()});if(w.history.length>5000)w.history.splice(0,w.history.length-5000);};
export function setWorldPause(world,{actor,paused,reason=""}={}){adminControlSystem.requirePermission(actor,"world.write");const w=ensureWorldControl(world),before=w.paused;w.paused=!!paused;history(w,{kind:"pause",before,after:w.paused,reason,actorId:actor.id});adminControlSystem.log(actor,"world_pause",{before,after:w.paused,reason});return w.paused;}
export function setWorldTimeScale(world,{actor,scale,reason=""}={}){adminControlSystem.requirePermission(actor,"world.write");const w=ensureWorldControl(world),before=w.timeScale,after=Math.max(0,Math.min(20,n(scale,1)));w.timeScale=after;history(w,{kind:"time_scale",before,after,reason,actorId:actor.id});adminControlSystem.log(actor,"world_time_scale",{before,after,reason});return after;}
export function setMarketFactor(world,{actor,key,value,reason=""}={}){adminControlSystem.requirePermission(actor,"market.write");const w=ensureWorldControl(world);if(!(key in w.market))throw new Error("Unbekannter Weltmarktfaktor");const before=w.market[key],after=Math.max(.05,Math.min(10,n(value,1)));w.market[key]=after;history(w,{kind:"market",key,before,after,reason,actorId:actor.id});adminControlSystem.log(actor,"world_market_factor",{key,before,after,reason});return after;}
export function setRegionState(world,{actor,regionId,changes={},reason=""}={}){adminControlSystem.requirePermission(actor,"world.write");if(!regionId)throw new Error("Region fehlt");const w=ensureWorldControl(world),r=w.regions[regionId]??={demand:1,wages:1,landPrice:1,energyPrice:1,active:true},before={...r};for(const[k,v]of Object.entries(changes)){if(k==="active")r.active=!!v;else if(k in r)r[k]=Math.max(.05,Math.min(10,n(v,1)));}w.regions[regionId]=r;history(w,{kind:"region",regionId,before,after:{...r},reason,actorId:actor.id});adminControlSystem.log(actor,"world_region_changed",{regionId,before,after:{...r},reason});return r;}
export function resetNpcLiquidity(world,{actor,factor=1,reason=""}={}){adminControlSystem.requirePermission(actor,"market.write");return setMarketFactor(world,{actor,key:"npcLiquidity",value:factor,reason});}
export function worldControlSnapshot(world){const w=ensureWorldControl(world);return{paused:w.paused,timeScale:w.timeScale,market:{...w.market},regions:Object.entries(w.regions).map(([id,r])=>({id,...r})),changes:w.history.length,lastChange:w.history.at(-1)||null};}
