// WorldProject – sichere Direktaktionen für die bestehende AdminConsoleUI.
// Läuft nur im separaten Admin-Bootstrap.
import { AdminConsoleUI } from './AdminConsoleUI.js';
import { adminOperationalSection } from './AdminOperationsData.js';
import { applyBalance } from './AdminBalancingSystem.js';
import { resetStuckDelivery } from './AdminEntityActions.js';
import { assignSupportCase, closeSupportCase, setSupportPriority } from './SupportCaseSystem.js';
import { closeModerationCase, revokeSanction } from './ModerationCaseSystem.js';
import { createLiveEvent, cancelLiveEvent, createLiveAnnouncement, scheduleRollout } from './LiveOpsSystem.js';
import { safeAdminSetting, adminAllianceRelease } from './AdminSecurityIntegration.js';
import { worldControlSnapshot, setWorldPause, setWorldTimeScale } from './AdminWorldControl.js';

const h=(tag,props={},...kids)=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(props||{})){if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on')&&typeof v==='function')e.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==undefined&&v!==null)e.setAttribute(k,String(v));}for(const x of kids.flat())if(x!==null&&x!==undefined)e.append(x?.nodeType?x:document.createTextNode(String(x)));return e;};
const panel=(title,...kids)=>h('div',{class:'panel'},h('h3',{text:title}),...kids);
const btn=(text,onclick,danger=false)=>h('button',{class:`action${danger?' danger':''}`,text,onclick});
const askReason=label=>{const r=prompt(`Begründung für „${label}“:`);return r===null?null:String(r).trim();};
const findCompany=(ui,id)=>ui.companies().find(c=>String(c.id||c.companyId||c.serverCompanyId)===String(id));
const wrap=(name,enhance)=>{const base=AdminConsoleUI.prototype[name];AdminConsoleUI.prototype[name]=function(){base?.call(this);enhance.call(this);};};

wrap('render_economy',function(){if(!this.admin.can(this.actor,'economy.write'))return;const factors=['materialPrice','wages','energy','transport','demand','productionTime','maintenance','tax','marketFee','startCapital','loanInterest','experience'];const select=h('select');for(const f of factors)select.append(h('option',{value:f,text:f}));const value=h('input',{type:'number',step:'0.01',placeholder:'Neuer Wert'});const apply=btn('Balancing ändern',()=>{const v=Number(value.value);if(!Number.isFinite(v))return this.toast('Ungültiger Wert',true);const reason=askReason('Balancing ändern');if(reason===null)return;try{applyBalance(this.world(),{actor:this.actor,changes:{[select.value]:v},reason});this.toast('Balancing geändert');this.render();}catch(err){this.toast(err.message,true);}});this.body.append(panel('Balancing-Schnelländerung',h('div',{class:'section-note',text:'Nur gezielt ändern. Die erlaubten Grenzen werden vom Balancing-System automatisch geprüft.'}),h('div',{class:'toolbar'},select,value,apply)));});

wrap('render_production',function(){if(!this.admin.can(this.actor,'production.write'))return;const d=adminOperationalSection('production',this.context)||{},stuck=(d.stuckJobs||[]).slice(0,50);if(!stuck.length)return;const box=panel('Festhängende Produktionen reparieren');for(const j of stuck){box.append(h('div',{class:'kv'},h('span',{text:`${j.companyName||j.companyId} · ${j.productName||j.productId||j.id}`}),btn('Auftrag abbrechen',()=>{const reason=askReason('Produktion abbrechen');if(reason===null)return;const c=findCompany(this,j.companyId);if(!c)return this.toast('Betrieb nicht gefunden',true);try{this.admin.cancelProduction(this.actor,c,j.id,{reason});this.toast('Produktion abgebrochen');this.render();}catch(err){this.toast(err.message,true);}},true)));}this.body.append(box);});

wrap('render_transport',function(){if(!this.admin.can(this.actor,'transport.write'))return;const d=adminOperationalSection('transport',this.context)||{},late=(d.lateDeliveries||[]).slice(0,50);if(!late.length)return;const box=panel('Überfällige Lieferungen reparieren');for(const x of late){box.append(h('div',{class:'kv'},h('span',{text:`${x.companyName||x.companyId} · ${x.itemName||x.item||x.id}`}),btn('Als angekommen wiederherstellen',()=>{const reason=askReason('Lieferung wiederherstellen');if(reason===null)return;const c=findCompany(this,x.companyId),list=c?(c.inboundDeliveries||c.deliveries||[]):[],real=list.find(d=>String(d.id||d.deliveryId)===String(x.id||x.deliveryId));if(!real)return this.toast('Echte Lieferung nicht gefunden',true);try{resetStuckDelivery(this.actor,real,{reason});this.toast('Lieferung wiederhergestellt');this.render();}catch(err){this.toast(err.message,true);}})));}this.body.append(box);});

wrap('render_support',function(){if(!this.admin.can(this.actor,'support.write'))return;const cases=(this.world().supportState?.cases||[]).filter(c=>c.status!=='closed').slice(0,100);if(!cases.length)return;const box=panel('Support-Schnellaktionen');for(const c of cases){const actions=h('div',{class:'toolbar'});actions.append(btn('Mir zuweisen',()=>{try{assignSupportCase(this.world(),{actor:this.actor,caseId:c.id});this.toast('Fall übernommen');this.render();}catch(err){this.toast(err.message,true);}}),btn('Priorität hoch',()=>{try{setSupportPriority(this.world(),{actor:this.actor,caseId:c.id,priority:'high'});this.toast('Priorität geändert');this.render();}catch(err){this.toast(err.message,true);}}),btn('Schließen',()=>{const r=prompt('Lösung / Abschlussgrund:','Gelöst');if(r===null)return;try{closeSupportCase(this.world(),{actor:this.actor,caseId:c.id,resolution:r});this.toast('Fall geschlossen');this.render();}catch(err){this.toast(err.message,true);}},true));box.append(h('div',{class:'kv'},h('span',{text:`${c.subject} · ${c.playerId} · ${c.status}`}),actions));}this.body.append(box);});

wrap('render_moderation',function(){if(!this.admin.can(this.actor,'moderation.write'))return;const state=this.world().moderationState||{},cases=(state.cases||[]).filter(c=>c.status==='open').slice(0,50),sanctions=(state.sanctions||[]).filter(s=>s.status==='active').slice(0,50);const box=panel('Moderations-Schnellaktionen');for(const c of cases)box.append(h('div',{class:'kv'},h('span',{text:`Fall ${c.id} · ${c.playerId} · ${c.severity}`}),btn('Fall schließen',()=>{const r=prompt('Abschlussgrund:','Gelöst');if(r===null)return;try{closeModerationCase(this.world(),{actor:this.actor,caseId:c.id,resolution:r});this.toast('Moderationsfall geschlossen');this.render();}catch(err){this.toast(err.message,true);}})));for(const s of sanctions)box.append(h('div',{class:'kv'},h('span',{text:`${s.type} · ${s.playerId} · ${s.id}`}),btn('Sanktion widerrufen',()=>{const r=askReason('Sanktion widerrufen');if(r===null)return;const p=this.players().find(x=>String(x.id||x.userId)===String(s.playerId));try{revokeSanction(this.world(),{actor:this.actor,sanctionId:s.id,player:p,reason:r});this.toast('Sanktion widerrufen');this.render();}catch(err){this.toast(err.message,true);}},true));if(cases.length||sanctions.length)this.body.append(box);});

wrap('render_liveops',function(){if(!this.admin.can(this.actor,'liveops.write'))return;const actions=h('div',{class:'toolbar'});actions.append(btn('➕ Event',()=>{const name=prompt('Eventname:');if(!name)return;const factor=Number(prompt('Nachfragefaktor (1 = normal):','1.1'));if(!Number.isFinite(factor))return;try{createLiveEvent(this.world(),{actor:this.actor,name,effects:{demand:factor}});this.toast('Event angelegt');this.render();}catch(err){this.toast(err.message,true);}}),btn('📢 Ankündigung',()=>{const title=prompt('Titel:');if(!title)return;const message=prompt('Nachricht:');if(!message)return;try{createLiveAnnouncement(this.world(),{actor:this.actor,title,message});this.toast('Ankündigung angelegt');this.render();}catch(err){this.toast(err.message,true);}}),btn('🧪 Rollout',()=>{const feature=prompt('Feature-ID:');if(!feature)return;const percentage=Number(prompt('Anteil 0–100:','10'));if(!Number.isFinite(percentage))return;try{scheduleRollout(this.world(),{actor:this.actor,feature,percentage});this.toast('Rollout angelegt');this.render();}catch(err){this.toast(err.message,true);}}));const box=panel('LiveOps-Aktionen',actions);for(const e of (this.world().liveOps?.events||[]).filter(x=>['scheduled','active'].includes(x.status)).slice(0,50))box.append(h('div',{class:'kv'},h('span',{text:`${e.name} · ${e.status}`}),btn('Event abbrechen',()=>{const r=askReason('Live-Event abbrechen');if(r===null)return;try{cancelLiveEvent(this.world(),{actor:this.actor,eventId:e.id,reason:r});this.toast('Event abgebrochen');this.render();}catch(err){this.toast(err.message,true);}},true)));this.body.append(box);});

AdminConsoleUI.prototype.render_system=function(){if(!this.admin.can(this.actor,'system.write'))return this.body.append(panel('Keine Berechtigung','Dieser Admin darf Systemeinstellungen nicht verändern.'));const w=worldControlSnapshot(this.world()),settings=panel('Sichere Systemschalter');for(const [key,label] of [['maintenanceMode','Wartungsmodus'],['registrationEnabled','Registrierung'],['premiumEnabled','Premiumsystem'],['globalChatEnabled','Globaler Chat']]){const current=!!this.admin.settings[key];settings.append(h('div',{class:'kv'},h('span',{text:`${label}: ${current?'Aktiv':'Aus'}`}),btn(current?'Ausschalten':'Einschalten',()=>{const r=askReason(`${label} ändern`);if(r===null)return;try{safeAdminSetting(this.actor,key,!current,{reason:r});this.toast(`${label} geändert`);this.render();}catch(err){this.toast(err.message,true);}},key==='maintenanceMode'&&!current)));}const worldBox=panel('Weltsteuerung',h('div',{class:'kv'},h('span',{text:'Status'}),h('b',{class:w.paused?'bad':'ok',text:w.paused?'PAUSIERT':'LÄUFT'})),h('div',{class:'kv'},h('span',{text:'Geschwindigkeit'}),h('span',{text:`${w.timeScale}×`})),h('div',{class:'toolbar'},btn(w.paused?'▶ Fortsetzen':'⏸ Pausieren',()=>{const r=askReason('Weltstatus ändern');if(r===null)return;try{setWorldPause(this.world(),{actor:this.actor,paused:!w.paused,reason:r});this.toast('Weltstatus geändert');this.render();}catch(err){this.toast(err.message,true);}}),btn('⏱ Geschwindigkeit ändern',()=>{const scale=Number(prompt('Spielgeschwindigkeit 0–20:',String(w.timeScale)));if(!Number.isFinite(scale))return;const r=askReason('Spielgeschwindigkeit ändern');if(r===null)return;try{setWorldTimeScale(this.world(),{actor:this.actor,scale,reason:r});this.toast('Spielgeschwindigkeit geändert');this.render();}catch(err){this.toast(err.message,true);}})));this.body.append(h('div',{class:'grid2'},settings,worldBox));};

AdminConsoleUI.prototype.render_alliances=function(){if(!this.admin.can(this.actor,'alliances.write'))return this.body.append(panel('Keine Berechtigung','Dieser Admin darf Allianzen nicht freischalten.'));const flags=window.worldAllianceSystem?.featureFlags||{},enabled=!!this.admin.settings.alliancesEnabled;this.body.append(h('div',{class:'section-note',text:'Allianzen bleiben für Spieler verborgen, bis sie hier vollständig freigeschaltet werden. Keine Teilfreigabe über unsichere Einzelbuttons.'}),panel('Allianzstatus',h('p',{class:enabled?'ok':'warn',text:enabled?'✅ Für Spieler freigeschaltet':'🔒 Für Spieler verborgen'}),h('div',{class:'toolbar'},btn('Allianzen vollständig freischalten',()=>{const r=askReason('Allianzen freischalten');if(r===null)return;try{adminAllianceRelease(this.actor,{visible:true,creation:true,applications:true,ranking:true,reason:r});this.toast('Allianzen freigeschaltet');this.render();}catch(err){this.toast(err.message,true);}}),btn('Allianzen vollständig verbergen',()=>{const r=askReason('Allianzen verbergen');if(r===null)return;try{adminAllianceRelease(this.actor,{visible:false,creation:false,applications:false,ranking:false,reason:r||'Allianzen verborgen'});this.toast('Allianzen verborgen');this.render();}catch(err){this.toast(err.message,true);}},true)),h('code',{text:JSON.stringify(flags,null,2)})));};

if(typeof window!=='undefined')window.worldAdminConsoleActionViews=true;
