// WorldProject – konkrete Admin-Reparaturaktionen für Spieler- und Firmendaten.
import { adminControlSystem } from "./AdminControlSystem.js";
import { validateAdminText, validateAdminReason } from './AdminMutationValidation.js';
import { persistPlayerPremium, persistPlayerCoins } from './AdminServerPersistenceBridge.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const reason=(v,label='Begründung')=>{const r=validateAdminReason(v,{required:true,minLength:3});if(!r.valid)throw new Error(`${label}: ${r.message}`);return r.value;};
const playerId=p=>p?.id||p?.userId||null,companyId=c=>c?.id||c?.companyId||null;
export function setPlayerPremium(actor,player,{enabled,until=null,reason:why=""}={}){adminControlSystem.requirePermission(actor,"players.write");if(!player)throw new Error("Spieler fehlt");const cleanReason=reason(why),before={premium:player.premium,premiumUntil:player.premiumUntil},now=Date.now();let cleanUntil=null;if(enabled&&until!=null){cleanUntil=n(until);if(!cleanUntil||cleanUntil<=now)throw new Error("Premium-Endzeit muss in der Zukunft liegen");}player.premium=!!enabled;player.premiumUntil=enabled?cleanUntil:null;adminControlSystem.log(actor,"player_premium_set",{playerId:playerId(player),before,after:{premium:player.premium,premiumUntil:player.premiumUntil},reason:cleanReason});void persistPlayerPremium(player,{enabled:!!enabled,until:cleanUntil,reason:cleanReason}).catch(error=>console.error('Premium konnte serverseitig nicht gespeichert werden',error));return player;}
export function adjustPlayerCoins(actor,player,{delta,reason:why=""}={}){adminControlSystem.requirePermission(actor,"players.write");if(!player)throw new Error("Spieler fehlt");const cleanReason=reason(why),change=n(delta);if(!change)throw new Error("Coin-Änderung ist 0");const before=n(player.coins),after=Math.max(0,before+change);player.coins=after;adminControlSystem.log(actor,"player_coins_adjust",{playerId:playerId(player),before,after,delta:change,reason:cleanReason});void persistPlayerCoins(player,{delta:change,reason:cleanReason}).catch(error=>console.error('Coins konnten serverseitig nicht gespeichert werden',error));return after;}
export function resetPlayerLoginLocks(actor,player,{reason:why=""}={}){adminControlSystem.requirePermission(actor,"players.write");if(!player)throw new Error("Spieler fehlt");const cleanReason=reason(why),before={loginLocked:player.loginLocked,failedLogins:player.failedLogins};player.loginLocked=false;player.failedLogins=0;adminControlSystem.log(actor,"player_login_unlock",{playerId:playerId(player),before,reason:cleanReason});return player;}
export function renameCompany(actor,company,{name,reason:why=""}={}){adminControlSystem.requirePermission(actor,"companies.write");if(!company)throw new Error("Betrieb fehlt");const nameCheck=validateAdminText(name,{label:'Firmenname',minLength:2,maxLength:120});if(!nameCheck.valid)throw new Error(nameCheck.message);const cleanReason=reason(why),before=company.name||company.companyName;company.name=nameCheck.value;company.companyName=nameCheck.value;adminControlSystem.log(actor,"company_renamed",{companyId:companyId(company),before,after:nameCheck.value,reason:cleanReason});return company;}
export function setCompanyStatus(actor,company,{status,reason:why=""}={}){adminControlSystem.requirePermission(actor,"companies.write");if(!company)throw new Error("Betrieb fehlt");const allowed=new Set(['active','paused','closed','suspended','setup']);if(!allowed.has(status))throw new Error("Unbekannter Betriebsstatus");const cleanReason=reason(why),before=company.status;company.status=status;adminControlSystem.log(actor,"company_status_set",{companyId:companyId(company),before,after:status,reason:cleanReason});return company;}
export function repairCompanyIntegrity(actor,company,{reason:why="integrity repair"}={}){adminControlSystem.requirePermission(actor,"companies.write");if(!company)throw new Error("Betrieb fehlt");const cleanReason=reason(why),changes=[];company.inventory??={};company.finishedGoods??={};company.productionJobs??=[];company.customerOrders??=[];company.employees??=[];company.buildingState??={equipment:[]};company.buildingState.equipment??=[];for(const [bagName,bag] of [['inventory',company.inventory],['finishedGoods',company.finishedGoods]])for(const k of Object.keys(bag)){const before=bag[k],after=Math.max(0,n(before));if(before!==after)changes.push({kind:'quantity_normalized',bag:bagName,item:k,before,after});bag[k]=after;}const seen=new Set(),beforeJobs=company.productionJobs.length;company.productionJobs=company.productionJobs.filter(j=>{const key=j.requestId||j.id;if(!key||seen.has(key))return false;seen.add(key);return true;});if(beforeJobs!==company.productionJobs.length)changes.push({kind:'duplicate_jobs_removed',count:beforeJobs-company.productionJobs.length});for(const m of company.buildingState.equipment){const before={condition:m.condition,status:m.status},condition=Math.max(0,Math.min(100,n(m.condition,100)));m.condition=condition;if(!m.status)m.status=condition<=0?'broken':'available';if(before.condition!==m.condition||before.status!==m.status)changes.push({kind:'machine_normalized',machineId:m.instanceId||m.id,before,after:{condition:m.condition,status:m.status}});}company.adminLastIntegrityRepair={at:Date.now(),actorId:actor.id,reason:cleanReason,changes};adminControlSystem.log(actor,"company_integrity_repaired",{companyId:companyId(company),reason:cleanReason,changes});return company;}
export function resetVehicle(actor,company,vehicleId,{reason:why=""}={}){adminControlSystem.requirePermission(actor,"transport.write");const cleanReason=reason(why),v=(company?.vehicles||company?.fleet||[]).find(x=>(x.id||x.vehicleId)===vehicleId);if(!v)throw new Error("Fahrzeug fehlt");const before={status:v.status,busyUntil:v.busyUntil,condition:v.condition};v.status="available";v.busyUntil=0;v.condition=Math.max(50,Math.min(100,n(v.condition,100)));adminControlSystem.log(actor,"vehicle_reset",{companyId:companyId(company),vehicleId,before,after:{status:v.status,busyUntil:0,condition:v.condition},reason:cleanReason});return v;}
export function resetStuckDelivery(actor,delivery,{reason:why=""}={}){adminControlSystem.requirePermission(actor,"transport.write");if(!delivery)throw new Error("Lieferung fehlt");const cleanReason=reason(why);if(['delivered','arrived','completed'].includes(delivery.status)){delivery.adminRecoveryIdempotent=true;return delivery;}const before={status:delivery.status,eta:delivery.eta||delivery.arrivalAt},now=Date.now();delivery.status="arrived";delivery.arrivalAt=now;delivery.eta=now;delivery.adminRecovered=true;delivery.adminRecoveredAt=now;delivery.adminRecoveryIdempotent=false;adminControlSystem.log(actor,"delivery_recovered",{deliveryId:delivery.id,before,after:{status:delivery.status,arrivalAt:now},reason:cleanReason});return delivery;}
export function refundOrder(actor,company,order,{amount=null,reason:why=""}={}){adminControlSystem.requirePermission(actor,"economy.write");if(!company||!order)throw new Error("Betrieb oder Auftrag fehlt");const cleanReason=reason(why);if(order.adminRefunded)return{success:true,idempotent:true,amount:0};const base=amount==null?(order.total??order.cost??order.amount??0):amount,q=Math.max(0,n(base));if(q<=0)throw new Error("Erstattungsbetrag muss größer als 0 sein");company.money=n(company.money)+q;order.adminRefunded=true;order.adminRefundAmount=q;order.adminRefundedAt=Date.now();order.adminRefundReason=cleanReason;adminControlSystem.log(actor,"order_refunded",{orderId:order.id,companyId:companyId(company),amount:q,reason:cleanReason});return{success:true,amount:q};}
