// WorldProject – konkrete Admin-Reparaturaktionen für Spieler- und Firmendaten.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function setPlayerPremium(actor,player,{enabled,until=null,reason=""}={}){adminControlSystem.requirePermission(actor,"players.write");const before={premium:player.premium,premiumUntil:player.premiumUntil};player.premium=!!enabled;player.premiumUntil=enabled?until:null;adminControlSystem.log(actor,"player_premium_set",{playerId:player.id||player.userId,before,after:{premium:player.premium,premiumUntil:player.premiumUntil},reason});return player;}
export function adjustPlayerCoins(actor,player,{delta,reason=""}={}){adminControlSystem.requirePermission(actor,"players.write");const before=n(player.coins),after=Math.max(0,before+n(delta));player.coins=after;adminControlSystem.log(actor,"player_coins_adjust",{playerId:player.id||player.userId,before,after,delta:n(delta),reason});return after;}
export function resetPlayerLoginLocks(actor,player,{reason=""}={}){adminControlSystem.requirePermission(actor,"players.write");const before={loginLocked:player.loginLocked,failedLogins:player.failedLogins};player.loginLocked=false;player.failedLogins=0;adminControlSystem.log(actor,"player_login_unlock",{playerId:player.id||player.userId,before,reason});return player;}
export function renameCompany(actor,company,{name,reason=""}={}){adminControlSystem.requirePermission(actor,"companies.write");const before=company.name||company.companyName;company.name=name;company.companyName=name;adminControlSystem.log(actor,"company_renamed",{companyId:company.id||company.companyId,before,after:name,reason});return company;}
export function setCompanyStatus(actor,company,{status,reason=""}={}){adminControlSystem.requirePermission(actor,"companies.write");const before=company.status;company.status=status;adminControlSystem.log(actor,"company_status_set",{companyId:company.id||company.companyId,before,after:status,reason});return company;}
export function repairCompanyIntegrity(actor,company,{reason="integrity repair"}={}){adminControlSystem.requirePermission(actor,"companies.write");company.inventory??={};company.finishedGoods??={};company.productionJobs??=[];company.customerOrders??=[];company.employees??=[];company.buildingState??={equipment:[]};for(const bag of [company.inventory,company.finishedGoods])for(const k of Object.keys(bag))bag[k]=Math.max(0,n(bag[k]));const seen=new Set();company.productionJobs=company.productionJobs.filter(j=>{const key=j.requestId||j.id;if(!key||seen.has(key))return false;seen.add(key);return true;});for(const m of company.buildingState.equipment){m.condition=Math.max(0,Math.min(100,n(m.condition,100)));if(!m.status)m.status="available";}adminControlSystem.log(actor,"company_integrity_repaired",{companyId:company.id||company.companyId,reason});return company;}
export function resetVehicle(actor,company,vehicleId,{reason=""}={}){adminControlSystem.requirePermission(actor,"transport.write");const v=(company.vehicles||company.fleet||[]).find(x=>(x.id||x.vehicleId)===vehicleId);if(!v)throw new Error("Fahrzeug fehlt");const before={status:v.status,busyUntil:v.busyUntil,condition:v.condition};v.status="available";v.busyUntil=0;v.condition=Math.max(50,n(v.condition,100));adminControlSystem.log(actor,"vehicle_reset",{vehicleId,before,after:{status:v.status,busyUntil:0,condition:v.condition},reason});return v;}
export function resetStuckDelivery(actor,delivery,{reason=""}={}){adminControlSystem.requirePermission(actor,"transport.write");const before={status:delivery.status,eta:delivery.eta||delivery.arrivalAt};delivery.status="arrived";delivery.arrivalAt=Date.now();delivery.eta=delivery.arrivalAt;delivery.adminRecovered=true;adminControlSystem.log(actor,"delivery_recovered",{deliveryId:delivery.id,before,after:{status:delivery.status,arrivalAt:delivery.arrivalAt},reason});return delivery;}
export function refundOrder(actor,company,order,{amount=null,reason=""}={}){adminControlSystem.requirePermission(actor,"economy.write");if(order.adminRefunded)return{success:true,idempotent:true,amount:0};const q=Math.max(0,n(amount,order.total||order.cost||0));company.money=n(company.money)+q;order.adminRefunded=true;order.adminRefundAmount=q;adminControlSystem.log(actor,"order_refunded",{orderId:order.id,companyId:company.id||company.companyId,amount:q,reason});return{success:true,amount:q};}
