// WorldProject – Balancingregler mit Vorschau und Rollback.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export const DefaultBalance={materialPrice:1,wages:1,energy:1,transport:1,demand:1,productionTime:1,maintenance:1,tax:1,marketFee:.005,startCapital:50000,loanInterest:1,experience:1};
export function ensureBalance(world={}){world.balance??={values:{...DefaultBalance},history:[],presets:{normal:{...DefaultBalance}}};return world.balance;}
export function balancePreview(world,changes={}){const b=ensureBalance(world),before={...b.values},after={...before};for(const[k,v]of Object.entries(changes))if(k in after)after[k]=n(v,after[k]);return{before,after,diff:Object.fromEntries(Object.keys(after).filter(k=>after[k]!==before[k]).map(k=>[k,{before:before[k],after:after[k]}]))};}
export function applyBalance(world,{actor,changes={},reason="",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"economy.write");const b=ensureBalance(world),preview=balancePreview(world,changes),row={id:`balance-${now}-${Math.random().toString(36).slice(2,6)}`,before:preview.before,after:preview.after,changes:preview.diff,reason,actorId:actor.id,at:now};b.values=preview.after;b.history.push(row);adminControlSystem.log(actor,"balance_applied",{changeId:row.id,changes:row.changes,reason});return row;}
export function rollbackBalance(world,{actor,changeId,reason="rollback",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"economy.write");const b=ensureBalance(world),row=b.history.find(x=>x.id===changeId);if(!row)throw new Error("Balancing-Änderung fehlt");const before={...b.values};b.values={...row.before};const rollback={id:`balance-${now}-rollback`,before,after:{...b.values},reason,actorId:actor.id,rollbackOf:changeId,at:now};b.history.push(rollback);adminControlSystem.log(actor,"balance_rollback",{changeId,rollbackId:rollback.id});return rollback;}
export function saveBalancePreset(world,{actor,name,values=null}={}){adminControlSystem.requirePermission(actor,"economy.write");const b=ensureBalance(world);b.presets[name]={...(values||b.values)};return b.presets[name];}
export function applyBalancePreset(world,{actor,name,reason="preset"}={}){const b=ensureBalance(world),p=b.presets[name];if(!p)throw new Error("Balancing-Preset fehlt");return applyBalance(world,{actor,changes:p,reason:`${reason}:${name}`});}
export function balancedValue(world,key,value){const b=ensureBalance(world);return n(value)*n(b.values[key],1);}
export function balanceKpis(world){const b=ensureBalance(world);return{values:{...b.values},changes:b.history.length,presets:Object.keys(b.presets),lastChange:b.history.at(-1)||null};}
