// WorldProject – Balancingregler mit Vorschau und Rollback.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,n(v)));
const trim=(a,max=2000)=>{if(a.length>max)a.splice(0,a.length-max);};
export const DefaultBalance={materialPrice:1,wages:1,energy:1,transport:1,demand:1,productionTime:1,maintenance:1,tax:1,marketFee:.005,startCapital:50000,loanInterest:1,experience:1};
const LIMITS={materialPrice:[.05,10],wages:[.05,10],energy:[.05,10],transport:[.05,10],demand:[.05,10],productionTime:[.05,10],maintenance:[.05,10],tax:[0,1],marketFee:[0,.25],startCapital:[0,1e9],loanInterest:[0,10],experience:[.05,10]};
export function ensureBalance(world={}){world.balance??={values:{...DefaultBalance},history:[],presets:{normal:{...DefaultBalance}}};world.balance.values={...DefaultBalance,...(world.balance.values||{})};if(!Array.isArray(world.balance.history))world.balance.history=[];if(!world.balance.presets||typeof world.balance.presets!=="object")world.balance.presets={normal:{...DefaultBalance}};return world.balance;}
export function normalizeBalanceChanges(changes={}){const clean={};for(const[k,v]of Object.entries(changes||{})){if(!(k in DefaultBalance))continue;const [min,max]=LIMITS[k]||[-Infinity,Infinity];clean[k]=clamp(v,min,max);}return clean;}
export function balancePreview(world,changes={}){const b=ensureBalance(world),before={...b.values},after={...before},clean=normalizeBalanceChanges(changes);for(const[k,v]of Object.entries(clean))after[k]=v;return{before,after,diff:Object.fromEntries(Object.keys(after).filter(k=>after[k]!==before[k]).map(k=>[k,{before:before[k],after:after[k]}]))};}
export function applyBalance(world,{actor,changes={},reason="",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"economy.write");const b=ensureBalance(world),preview=balancePreview(world,changes);if(!Object.keys(preview.diff).length)throw new Error("Keine Balancing-Änderung vorhanden");const cleanReason=String(reason||"").trim()||"Balancing-Anpassung",row={id:`balance-${now}-${Math.random().toString(36).slice(2,6)}`,before:preview.before,after:preview.after,changes:preview.diff,reason:cleanReason,actorId:actor.id,at:now};b.values=preview.after;b.history.push(row);trim(b.history);adminControlSystem.log(actor,"balance_applied",{changeId:row.id,changes:row.changes,reason:cleanReason});return row;}
export function rollbackBalance(world,{actor,changeId,reason="rollback",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"economy.write");const b=ensureBalance(world),row=b.history.find(x=>x.id===changeId);if(!row)throw new Error("Balancing-Änderung fehlt");if(row.rollbackOf)throw new Error("Ein Rollback kann nicht erneut zurückgerollt werden");const before={...b.values};b.values={...DefaultBalance,...row.before};const rollback={id:`balance-${now}-rollback-${Math.random().toString(36).slice(2,5)}`,before,after:{...b.values},reason:String(reason||"rollback").trim()||"rollback",actorId:actor.id,rollbackOf:changeId,at:now};b.history.push(rollback);trim(b.history);adminControlSystem.log(actor,"balance_rollback",{changeId,rollbackId:rollback.id,reason:rollback.reason});return rollback;}
export function saveBalancePreset(world,{actor,name,values=null}={}){adminControlSystem.requirePermission(actor,"economy.write");const b=ensureBalance(world),key=String(name||"").trim();if(!key)throw new Error("Preset-Name fehlt");if(key.length>80)throw new Error("Preset-Name zu lang");const normalized={...b.values,...normalizeBalanceChanges(values||b.values)};b.presets[key]=normalized;adminControlSystem.log(actor,"balance_preset_saved",{name:key});return b.presets[key];}
export function deleteBalancePreset(world,{actor,name}={}){adminControlSystem.requirePermission(actor,"economy.write");const b=ensureBalance(world),key=String(name||"").trim();if(key==="normal")throw new Error("Standard-Preset kann nicht gelöscht werden");if(!b.presets[key])throw new Error("Balancing-Preset fehlt");delete b.presets[key];adminControlSystem.log(actor,"balance_preset_deleted",{name:key});return true;}
export function applyBalancePreset(world,{actor,name,reason="preset"}={}){const b=ensureBalance(world),p=b.presets[name];if(!p)throw new Error("Balancing-Preset fehlt");return applyBalance(world,{actor,changes:p,reason:`${String(reason||"preset").trim()}:${name}`});}
export function balancedValue(world,key,value){const b=ensureBalance(world);return n(value)*n(b.values[key],1);}
export function balanceKpis(world){const b=ensureBalance(world);return{values:{...b.values},changes:b.history.length,presets:Object.keys(b.presets),lastChange:b.history.at(-1)||null,limits:{...LIMITS}};}
