// WorldProject – Support-SLA, Eskalation und Wartezeitdiagnose.
import { adminControlSystem } from './AdminControlSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export const SupportSlaHours=Object.freeze({low:72,normal:48,high:12,urgent:4});
export function supportCaseAgeHours(c,now=Date.now()){return Math.max(0,(now-n(c.createdAt,now))/3600000);}
export function supportWaitingHours(c,now=Date.now()){return Math.max(0,(now-n(c.updatedAt??c.createdAt,now))/3600000);}
export function supportSlaForCase(c,now=Date.now()){const priority=SupportSlaHours[c?.priority]?c.priority:'normal',limit=SupportSlaHours[priority],waiting=supportWaitingHours(c,now),open=c?.status!=='closed',breached=open&&waiting>limit;return{priority,limitHours:limit,waitingHours:waiting,ageHours:supportCaseAgeHours(c,now),breached,remainingHours:open?Math.max(0,limit-waiting):0,status:c?.status||'open'};}
export function supportSlaSnapshot(world={},now=Date.now()){const cases=Array.isArray(world.supportState?.cases)?world.supportState.cases:[],open=cases.filter(c=>c.status!=='closed'),rows=open.map(c=>({...supportSlaForCase(c,now),caseId:c.id,playerId:c.playerId,subject:c.subject,assignedTo:c.assignedTo})).sort((a,b)=>(b.breached-a.breached)||(b.waitingHours-a.waitingHours));return{open:open.length,breached:rows.filter(x=>x.breached).length,unassigned:open.filter(x=>!x.assignedTo).length,urgent:open.filter(x=>x.priority==='urgent').length,averageWaitHours:rows.length?rows.reduce((s,x)=>s+x.waitingHours,0)/rows.length:0,rows};}
export function escalateSupportCase(actor,world,{caseId,priority='urgent',reason=''}={}){adminControlSystem.requirePermission(actor,'support.write');const why=String(reason||'').trim();if(why.length<3)throw new Error('Begründung erforderlich');if(!SupportSlaHours[priority])throw new Error('Unbekannte Priorität');const c=(world.supportState?.cases||[]).find(x=>x.id===caseId);if(!c)throw new Error('Supportfall fehlt');if(c.status==='closed')throw new Error('Geschlossener Supportfall kann nicht eskaliert werden');const before={priority:c.priority,escalated:c.escalated};c.priority=priority;c.escalated=true;c.escalatedAt=Date.now();c.escalatedBy=actor.id;c.escalationReason=why;c.updatedAt=Date.now();adminControlSystem.log(actor,'support_escalated',{caseId,before,after:{priority,escalated:true},reason:why});return c;}
export function bulkAssignOverdueSupport(actor,world,{staffId=null,reason='SLA-Zuweisung',now=Date.now()}={}){adminControlSystem.requirePermission(actor,'support.write');const why=String(reason||'').trim();if(why.length<3)throw new Error('Begründung erforderlich');const snap=supportSlaSnapshot(world,now),target=snap.rows.filter(x=>x.breached&&!x.assignedTo),assigned=[];for(const row of target){const c=world.supportState.cases.find(x=>x.id===row.caseId);c.assignedTo=staffId||actor.id;c.status='in_progress';c.updatedAt=now;assigned.push(c.id);}if(assigned.length)adminControlSystem.log(actor,'support_overdue_bulk_assigned',{count:assigned.length,caseIds:assigned,staffId:staffId||actor.id,reason:why});return assigned;}
if(typeof window!=='undefined')window.worldAdminSupportSla={hours:SupportSlaHours,case: supportSlaForCase,snapshot:supportSlaSnapshot,escalate:escalateSupportCase,assignOverdue:bulkAssignOverdueSupport};
