// WorldProject – Sicherheits-/Integrationsschicht für Admin und versteckte Allianzen.
import { adminControlSystem } from "./AdminControlSystem.js";
import { AllianceFeatureFlags, setAllianceFeatureFlag } from "./AllianceSystem.js";
const critical=new Set(["maintenanceMode","registrationEnabled","alliancesEnabled"]);
export function adminSafetyCheck(actor,{action,target,value=null}={}){adminControlSystem.requireAdmin(actor);const warnings=[];if(action==="setting"&&critical.has(target))warnings.push("kritische_systemeinstellung");if(action==="money"&&Number(value)>1000000000)warnings.push("extreme_geldmenge");if(action==="suspend"&&target===actor.id)warnings.push("selbstsperre");return{allowed:!warnings.includes("selbstsperre"),warnings};}
export function safeAdminSetting(actor,key,value,{reason=""}={}){const check=adminSafetyCheck(actor,{action:"setting",target:key,value});if(!check.allowed)throw new Error("Admin-Sicherheitsprüfung fehlgeschlagen");const result=adminControlSystem.updateSetting(actor,key,value);adminControlSystem.log(actor,"safe_setting_applied",{key,value,reason,warnings:check.warnings});return{...result,warnings:check.warnings};}
export function adminAllianceRelease(actor,{visible=false,creation=false,applications=false,ranking=false,reason=""}={}){adminControlSystem.requirePermission(actor,"alliances.write");safeAdminSetting(actor,"alliancesEnabled",!!visible,{reason});setAllianceFeatureFlag("playerVisible",!!visible);setAllianceFeatureFlag("creationEnabled",!!creation);setAllianceFeatureFlag("applicationsEnabled",!!applications);setAllianceFeatureFlag("publicRanking",!!ranking);adminControlSystem.log(actor,"alliance_release_changed",{visible,creation,applications,ranking,reason});return{adminEnabled:adminControlSystem.settings.alliancesEnabled,flags:{...AllianceFeatureFlags}};}
export function disableAlliancesImmediately(actor,{reason="emergency disable"}={}){return adminAllianceRelease(actor,{visible:false,creation:false,applications:false,ranking:false,reason});}
export function validateAdminConfiguration(){const issues=[];if(AllianceFeatureFlags.playerVisible&&!adminControlSystem.settings.alliancesEnabled)issues.push("Allianz sichtbar, aber Admin-Flag deaktiviert");if(AllianceFeatureFlags.creationEnabled&&!AllianceFeatureFlags.playerVisible)issues.push("Allianzgründung aktiv, obwohl Spieleransicht verborgen");if(!adminControlSystem.settings.registrationEnabled&&adminControlSystem.settings.maintenanceMode)issues.push("Registrierung und Wartungsmodus gleichzeitig deaktivieren Spielerzugang vollständig");return{success:issues.length===0,issues,allianceFlags:{...AllianceFeatureFlags},adminSettings:{...adminControlSystem.settings}};}
export function adminAuditIntegrity(){const log=adminControlSystem.auditLog||[],ids=log.map(x=>x.id),duplicates=ids.filter((id,i)=>ids.indexOf(id)!==i),missingActor=log.filter(x=>!x.actorId&&x.action!=="system_init");return{success:duplicates.length===0,entries:log.length,duplicateIds:[...new Set(duplicates)],missingActor:missingActor.length};}
export function adminHealthSnapshot(){const config=validateAdminConfiguration(),audit=adminAuditIntegrity();return{success:config.success&&audit.success,config,audit,staff:adminControlSystem.staff.filter(x=>x.active).length,allianceHidden:!AllianceFeatureFlags.playerVisible};}
if(typeof window!=="undefined")window.worldAdminSecurity={health:adminHealthSnapshot,allianceRelease:adminAllianceRelease};
