// WorldProject – Standortvergleich, Ausbau- und Expansionsplanung.
import { companyGroupKpis } from './MultiSiteCompanySystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureSitePlanner(c={}){c.sitePlanner??={candidates:[],projects:[],decisions:[]};return c.sitePlanner;}
export function addSiteCandidate(c,{region,name,buyPrice=0,rentMonthly=0,capacity=1,demandIndex=1,wageIndex=1,logisticsIndex=1}={}){const s=ensureSitePlanner(c),row={id:`candidate-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,region,name,buyPrice:n(buyPrice),rentMonthly:n(rentMonthly),capacity:n(capacity,1),demandIndex:n(demandIndex,1),wageIndex:n(wageIndex,1),logisticsIndex:n(logisticsIndex,1)};s.candidates.push(row);return row;}
export function scoreSiteCandidate(c,candidate,{years=5}={}){const acquisition=Math.min(n(candidate.buyPrice),n(candidate.rentMonthly)*12*Math.max(1,n(years,5))||Infinity),benefit=n(candidate.capacity,1)*n(candidate.demandIndex,1)*100000,costPressure=(n(candidate.wageIndex,1)*.55+n(candidate.logisticsIndex,1)*.45),score=benefit/Math.max(1,acquisition*costPressure);return{candidateId:candidate.id,score,acquisition,costPressure,benefit};}
export function rankSiteCandidates(c,opts={}){return ensureSitePlanner(c).candidates.map(x=>({...x,...scoreSiteCandidate(c,x,opts)})).sort((a,b)=>b.score-a.score);}
export function planSiteExpansion(c,{candidateId,mode='rent',capacityTarget=1,startAt=Date.now(),durationDays=90}={}){const s=ensureSitePlanner(c),candidate=s.candidates.find(x=>x.id===candidateId);if(!candidate)throw new Error('Standortkandidat fehlt');const investment=mode==='buy'?candidate.buyPrice:candidate.rentMonthly*3;const project={id:`site-project-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,candidateId,mode,capacityTarget:n(capacityTarget,1),investment,startAt,endAt:startAt+Math.max(1,n(durationDays))*86400000,status:'planned'};s.projects.push(project);return project;}
export function approveSiteExpansion(c,projectId,{now=Date.now()}={}){const s=ensureSitePlanner(c),p=s.projects.find(x=>x.id===projectId);if(!p)throw new Error('Standortprojekt fehlt');if(p.status!=='planned')return{success:true,idempotent:true,project:p};if(n(c.money)<p.investment)throw new Error('Nicht genug Kapital');c.money-=p.investment;p.status='building';p.approvedAt=now;return{success:true,project:p};}
export function completeSiteExpansion(c,projectId,{now=Date.now(),force=false}={}){const s=ensureSitePlanner(c),p=s.projects.find(x=>x.id===projectId),candidate=s.candidates.find(x=>x.id===p?.candidateId);if(!p||!candidate)throw new Error('Standortprojekt fehlt');if(!force&&now<p.endAt)throw new Error('Standortprojekt noch nicht fertig');c.sites??=[];const site={id:`site-${Date.now()}-${Math.random().toString(36).slice(2,5)}`,name:candidate.name,region:candidate.region,capacity:p.capacityTarget,mode:p.mode,status:'active',openedAt:now,inventory:{},money:0};c.sites.push(site);p.status='done';p.completedAt=now;s.decisions.push({kind:'site_opened',siteId:site.id,projectId:p.id,at:now});return site;}
export function siteExpansionKpis(c){const s=ensureSitePlanner(c);return{candidates:s.candidates.length,projectsPlanned:s.projects.filter(x=>x.status==='planned').length,projectsBuilding:s.projects.filter(x=>x.status==='building').length,sites:(c.sites||[]).length,group:(c.sites?.length?companyGroupKpis(c):null)};}
