// WorldProject – Standortvergleich, Ausbau- und Expansionsplanung mit Grundstuecken.
import { companyGroupKpis } from './MultiSiteCompanySystem.js';
import { propertyNeed,createLandParcel,buyLand } from './LandPropertySystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureSitePlanner(c={}){c.sitePlanner??={candidates:[],projects:[],decisions:[]};return c.sitePlanner;}
export function addSiteCandidate(c,{region,name,buyPrice=0,rentMonthly=0,capacity=1,demandIndex=1,wageIndex=1,logisticsIndex=1,zone=null,areaM2=0}={}){const s=ensureSitePlanner(c),need=propertyNeed(c),resolvedZone=zone||need.zone?.[0]||'commercial',parcel=areaM2>0?createLandParcel({regionId:region||'default',zone:resolvedZone,areaM2,pricePerM2:buyPrice>0?buyPrice/areaM2:null}):null,row={id:`candidate-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,region,name,buyPrice:parcel?parcel.price:n(buyPrice),rentMonthly:n(rentMonthly),capacity:n(capacity,1),demandIndex:n(demandIndex,1),wageIndex:n(wageIndex,1),logisticsIndex:n(logisticsIndex,1),zone:resolvedZone,areaM2:n(areaM2),parcel};s.candidates.push(row);return row;}
export function scoreSiteCandidate(c,candidate,{years=5}={}){const acquisition=Math.min(n(candidate.buyPrice),n(candidate.rentMonthly)*12*Math.max(1,n(years,5))||Infinity),benefit=n(candidate.capacity,1)*n(candidate.demandIndex,1)*100000,costPressure=(n(candidate.wageIndex,1)*.55+n(candidate.logisticsIndex,1)*.45),score=benefit/Math.max(1,acquisition*costPressure);return{candidateId:candidate.id,score,acquisition,costPressure,benefit};}
export function rankSiteCandidates(c,opts={}){return ensureSitePlanner(c).candidates.map(x=>({...x,...scoreSiteCandidate(c,x,opts)})).sort((a,b)=>b.score-a.score);}
export function planSiteExpansion(c,{candidateId,mode='rent',capacityTarget=1,startAt=Date.now(),durationDays=90}={}){const s=ensureSitePlanner(c),candidate=s.candidates.find(x=>x.id===candidateId);if(!candidate)throw new Error('Standortkandidat fehlt');const need=propertyNeed(c);if(candidate.zone&&!need.zone.includes(candidate.zone))throw new Error('Grundstück hat nicht die passende Nutzungsart für dieses Gewerbe');if(mode==='buy'&&candidate.areaM2>0&&candidate.areaM2<need.minM2)throw new Error(`Grundstück zu klein: mindestens ${need.minM2} m² erforderlich`);const investment=mode==='buy'?candidate.buyPrice:candidate.rentMonthly*3,project={id:`site-project-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,candidateId,mode,capacityTarget:n(capacityTarget,1),investment,startAt,endAt:startAt+Math.max(1,n(durationDays))*86400000,status:'planned',zone:candidate.zone,areaM2:candidate.areaM2};s.projects.push(project);return project;}
export function approveSiteExpansion(c,projectId,{now=Date.now()}={}){const s=ensureSitePlanner(c),p=s.projects.find(x=>x.id===projectId),candidate=s.candidates.find(x=>x.id===p?.candidateId);if(!p||!candidate)throw new Error('Standortprojekt fehlt');if(p.status!=='planned')return{success:true,idempotent:true,project:p};if(p.mode==='buy'&&candidate.parcel){const land=buyLand(c,candidate.parcel,{ownerId:c.id||c.serverCompanyId});if(!land.success)throw new Error(land.reason);p.landParcelId=land.parcel.id;p.investment=land.parcel.price;}else{if(n(c.money)<p.investment)throw new Error('Nicht genug Kapital');c.money-=p.investment;}p.status='building';p.approvedAt=now;return{success:true,project:p};}
export function completeSiteExpansion(c,projectId,{now=Date.now(),force=false}={}){const s=ensureSitePlanner(c),p=s.projects.find(x=>x.id===projectId),candidate=s.candidates.find(x=>x.id===p?.candidateId);if(!p||!candidate)throw new Error('Standortprojekt fehlt');if(!force&&now<p.endAt)throw new Error('Standortprojekt noch nicht fertig');c.sites??=[];const site={id:`site-${Date.now()}-${Math.random().toString(36).slice(2,5)}`,name:candidate.name,region:candidate.region,capacity:p.capacityTarget,mode:p.mode,status:'active',openedAt:now,inventory:{},money:0,landParcelId:p.landParcelId||null,zone:candidate.zone||null,areaM2:n(candidate.areaM2)};c.sites.push(site);p.status='done';p.completedAt=now;s.decisions.push({kind:'site_opened',siteId:site.id,projectId:p.id,landParcelId:p.landParcelId||null,at:now});return site;}
export function siteExpansionKpis(c){const s=ensureSitePlanner(c);return{candidates:s.candidates.length,projectsPlanned:s.projects.filter(x=>x.status==='planned').length,projectsBuilding:s.projects.filter(x=>x.status==='building').length,sites:(c.sites||[]).length,ownedExpansionLand:s.projects.filter(x=>x.landParcelId).length,group:(c.sites?.length?companyGroupKpis(c):null)};}
