// WorldProject – vollständiger Beschaffungsworkflow für alle Gewerbe.
import { supplierCanProvide } from './UniversalIndustryCycle.js';
import { supplierKpis } from './SupplierManagementSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureProcurementWorkflow(c={}){c.procurementWorkflow??={requests:[],quotes:[],orders:[],receipts:[]};return c.procurementWorkflow;}
export function createPurchaseRequest(c,{item,quantity,requiredAt,reason='Bedarf'}={}){const w=ensureProcurementWorkflow(c),row={id:`pr-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,item,quantity:Math.max(0,n(quantity)),requiredAt:n(requiredAt,Date.now()),reason,status:'open',createdAt:Date.now()};w.requests.push(row);return row;}
export function sourceQuotes(c,requestId){const w=ensureProcurementWorkflow(c),r=w.requests.find(x=>x.id===requestId);if(!r)throw new Error('Bestellanforderung fehlt');const suppliers=supplierCanProvide(c,r.item),quotes=suppliers.map((s,i)=>({id:`quote-${requestId}-${i}`,requestId,supplierId:s.id,item:r.item,quantity:r.quantity,unitPrice:n(s.prices?.[r.item]),transport:n(s.deliveryBase)+n(s.deliveryPerKm)*n(s.distanceKm),deliveryHours:n(s.deliveryHours),quality:n(s.quality,1),reliability:n(s.reliability,1),total:r.quantity*n(s.prices?.[r.item])+n(s.deliveryBase)+n(s.deliveryPerKm)*n(s.distanceKm),status:'open'})).sort((a,b)=>(a.total+(1-a.reliability)*500+(1-a.quality)*300+a.deliveryHours*2)-(b.total+(1-b.reliability)*500+(1-b.quality)*300+b.deliveryHours*2));w.quotes.push(...quotes);return quotes;}
export function approveQuote(c,quoteId,{requestId}={}){const w=ensureProcurementWorkflow(c),q=w.quotes.find(x=>x.id===quoteId);if(!q)throw new Error('Angebot fehlt');c.purchaseApprovalIds??=[];if(requestId&&c.purchaseApprovalIds.includes(requestId))return{success:true,idempotent:true};if(n(c.money)<q.total)throw new Error('Firmenkonto reicht nicht');c.money-=q.total;q.status='accepted';const order={id:`po-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,quoteId:q.id,supplierId:q.supplierId,item:q.item,quantity:q.quantity,total:q.total,orderedAt:Date.now(),eta:Date.now()+q.deliveryHours*3600000,status:'ordered'};w.orders.push(order);const r=w.requests.find(x=>x.id===q.requestId);if(r)r.status='ordered';if(requestId)c.purchaseApprovalIds.push(requestId);return{success:true,order};}
export function receivePurchaseOrder(c,orderId,{acceptedQuantity,quality=1,now=Date.now()}={}){const w=ensureProcurementWorkflow(c),o=w.orders.find(x=>x.id===orderId);if(!o)throw new Error('Bestellung fehlt');if(o.status==='received')return{success:true,idempotent:true};const q=Math.min(o.quantity,Math.max(0,n(acceptedQuantity,o.quantity)));c.inventory??={};c.inventory[o.item]=n(c.inventory[o.item])+q;o.receivedQuantity=q;o.rejectedQuantity=Math.max(0,o.quantity-q);o.quality=n(quality,1);o.receivedAt=now;o.status='received';const receipt={id:`gr-${now}-${Math.random().toString(36).slice(2,5)}`,orderId,item:o.item,accepted:q,rejected:o.rejectedQuantity,quality:o.quality,at:now};w.receipts.push(receipt);return{success:true,receipt};}
export function procurementWorkflowKpis(c){const w=ensureProcurementWorkflow(c);return{requestsOpen:w.requests.filter(x=>x.status==='open').length,ordersOpen:w.orders.filter(x=>x.status==='ordered').length,lateOrders:w.orders.filter(x=>x.status==='ordered'&&x.eta<Date.now()).length,receipts:w.receipts.length,supplierHealth:supplierKpis(c)};}
