// WorldProject – fortgeschrittene Maschinen-/Produktionssteuerung.
import { industryRecipes } from './UniversalIndustryCycle.js';
import { maintenanceDue } from './IndustryMaintenanceEngine.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function machineWindows(company,{from=Date.now(),to=Date.now()+7*86400000}={}){const machines=company.buildingState?.equipment||[],jobs=company.productionJobs||[];return machines.map(m=>{const id=m.instanceId||m.id,blocks=jobs.filter(j=>j.machineId===id&&j.status!=='done').map(j=>({from:n(j.startedAt),to:n(j.endsAt),kind:'job',id:j.id}));if(m.maintenanceEndsAt&&m.maintenanceEndsAt>from)blocks.push({from, to:n(m.maintenanceEndsAt),kind:'maintenance'});return{id,name:m.name||m.id,blocks:blocks.filter(b=>b.to>=from&&b.from<=to).sort((a,b)=>a.from-b.from),condition:n(m.condition,100),maintenanceDue:maintenanceDue(company,m)};});}
export function setupFamily(recipe){return recipe.setupFamily||recipe.product||recipe.machineType||recipe.id;}
export function optimizeRecipeSequence(company,recipeIds=[]){const recipes=recipeIds.map(id=>industryRecipes(company).find(r=>r.id===id)).filter(Boolean);recipes.sort((a,b)=>setupFamily(a).localeCompare(setupFamily(b))||n(a.durationMinutes)-n(b.durationMinutes));let setupChanges=0;for(let i=1;i<recipes.length;i++)if(setupFamily(recipes[i])!==setupFamily(recipes[i-1]))setupChanges++;return{recipeIds:recipes.map(r=>r.id),setupChanges};}
export function findMachineBottlenecks(company){const recipes=industryRecipes(company),machines=company.buildingState?.equipment||[],rows=[];for(const r of recipes){const capable=machines.filter(m=>m.id===r.machineType||(m.capabilities||[]).includes(r.machineType));const available=capable.filter(m=>!['broken','maintenance'].includes(m.status)&&n(m.condition,100)>=20);rows.push({recipeId:r.id,machineType:r.machineType,capable:capable.length,available:available.length,bottleneck:available.length===0});}return rows;}
export function productionWindow(company,recipeId,amount,{now=Date.now(),setupMinutes=15,cleaningMinutes=10}={}){const r=industryRecipes(company).find(x=>x.id===recipeId);if(!r)throw new Error('Rezept fehlt');const run=Math.max(1,n(r.durationMinutes))*Math.max(0,n(amount))/Math.max(1,n(r.output,1)),total=run+n(setupMinutes)+n(cleaningMinutes);return{recipeId,amount:n(amount),setupMinutes:n(setupMinutes),runMinutes:run,cleaningMinutes:n(cleaningMinutes),totalMinutes:total,startAt:now,endAt:now+total*60000};}
export function machineProductionKpis(company){const bottlenecks=findMachineBottlenecks(company),windows=machineWindows(company);return{machines:windows.length,maintenanceDue:windows.filter(x=>x.maintenanceDue).length,bottlenecks:bottlenecks.filter(x=>x.bottleneck).length,recipes:bottlenecks.length};}
