// WorldProject – Schicht-/Personalplanung für alle Gewerbe.
import { workforceKpis } from './IndustryWorkforceDevelopment.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureShiftPlanning(c={}){c.shiftPlanning??={shifts:[],assignments:[],requirements:[],absences:[]};return c.shiftPlanning;}
export function defineShift(c,{id,name,startHour,endHour,premiumRate=0}={}){const s=ensureShiftPlanning(c),row={id:id||`shift-${s.shifts.length+1}`,name:name||'Schicht',startHour:n(startHour),endHour:n(endHour),premiumRate:Math.max(0,n(premiumRate))};s.shifts.push(row);return row;}
export function setRoleRequirement(c,{role,shiftId,count=1,skills=[]}={}){const s=ensureShiftPlanning(c),row={role,shiftId,count:Math.max(0,n(count)),skills:[...skills]};s.requirements=s.requirements.filter(x=>!(x.role===role&&x.shiftId===shiftId));s.requirements.push(row);return row;}
export function recordAbsence(c,{employeeId,from,to,kind='absence'}={}){const s=ensureShiftPlanning(c),row={id:`absence-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,employeeId,from:n(from),to:n(to),kind};s.absences.push(row);return row;}
export function employeeAvailable(c,e,shiftId,dayStart){const s=ensureShiftPlanning(c),shift=s.shifts.find(x=>x.id===shiftId);if(!shift)return false;const from=dayStart+shift.startHour*3600000,to=dayStart+shift.endHour*3600000;return !s.absences.some(a=>a.employeeId===e.id&&from<a.to&&to>a.from)&&!['sick','training','notice'].includes(e.status);}
export function assignEmployeeToShift(c,{employeeId,shiftId,dayStart=Date.now()}={}){const s=ensureShiftPlanning(c),e=(c.employees||[]).find(x=>x.id===employeeId);if(!e)throw new Error('Mitarbeiter fehlt');if(!employeeAvailable(c,e,shiftId,dayStart))throw new Error('Mitarbeiter nicht verfügbar');const row={id:`assign-${dayStart}-${employeeId}-${shiftId}`,employeeId,shiftId,dayStart,status:'assigned'};s.assignments.push(row);return row;}
export function staffingGaps(c,{dayStart=Date.now()}={}){const s=ensureShiftPlanning(c),out=[];for(const r of s.requirements){const assigned=s.assignments.filter(a=>a.shiftId===r.shiftId&&a.dayStart===dayStart).map(a=>(c.employees||[]).find(e=>e.id===a.employeeId)).filter(Boolean),qualified=assigned.filter(e=>(r.skills||[]).every(skill=>(e.skills||e.training||[]).includes(skill))||!(r.skills||[]).length);if(qualified.length<r.count)out.push({...r,assigned:qualified.length,missing:r.count-qualified.length});}return out;}
export function laborCostForShift(c,shiftId,dayStart){const s=ensureShiftPlanning(c),shift=s.shifts.find(x=>x.id===shiftId),ids=s.assignments.filter(a=>a.shiftId===shiftId&&a.dayStart===dayStart).map(a=>a.employeeId);return ids.reduce((sum,id)=>{const e=(c.employees||[]).find(x=>x.id===id);return sum+(n(e?.wageMonthly)/173)*(1+n(shift?.premiumRate));},0);}
export function shiftPlanningKpis(c,{dayStart=Date.now()}={}){const gaps=staffingGaps(c,{dayStart}),base=workforceKpis(c);return{...base,shifts:ensureShiftPlanning(c).shifts.length,assignments:ensureShiftPlanning(c).assignments.filter(a=>a.dayStart===dayStart).length,gaps:gaps.length,missingPeople:gaps.reduce((s,x)=>s+n(x.missing),0)};}
