// WorldProject – Vertriebstrichter, Angebote, Zahlungsziele und Kundenbindung.
import { pricingKpis } from './PricingPromotionSystem.js';
import { crmKpis } from './CustomerRelationshipSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureSales(c={}){c.salesEngine??={leads:[],quotes:[],orders:[],interactions:[]};return c.salesEngine;}
export function createLead(c,{customerId,segment='standard',productId,quantity=1,budget=null}={}){const s=ensureSales(c),row={id:`lead-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,customerId,segment,productId,quantity:Math.max(1,n(quantity)),budget:budget==null?null:n(budget),status:'new',createdAt:Date.now()};s.leads.push(row);return row;}
export function qualifyLead(c,leadId,{score=50,notes=''}={}){const s=ensureSales(c),l=s.leads.find(x=>x.id===leadId);if(!l)throw new Error('Lead fehlt');l.score=Math.max(0,Math.min(100,n(score,50)));l.notes=notes;l.status=l.score>=40?'qualified':'cold';return l;}
export function createSalesQuote(c,leadId,{unitPrice,validDays=7,paymentDays=14,discountRate=0}={}){const s=ensureSales(c),l=s.leads.find(x=>x.id===leadId);if(!l)throw new Error('Lead fehlt');const price=Math.max(0,n(unitPrice))*(1-Math.max(0,Math.min(.5,n(discountRate))));const q={id:`sq-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,leadId,customerId:l.customerId,productId:l.productId,quantity:l.quantity,unitPrice:price,total:price*l.quantity,validUntil:Date.now()+Math.max(1,n(validDays))*86400000,paymentDays:Math.max(0,n(paymentDays)),status:'open',createdAt:Date.now()};s.quotes.push(q);l.status='quoted';return q;}
export function acceptSalesQuote(c,quoteId,{now=Date.now()}={}){const s=ensureSales(c),q=s.quotes.find(x=>x.id===quoteId);if(!q)throw new Error('Angebot fehlt');if(q.status==='accepted')return{success:true,idempotent:true,order:s.orders.find(x=>x.quoteId===quoteId)};if(now>q.validUntil)throw new Error('Angebot abgelaufen');q.status='accepted';const order={id:`so-${now}-${Math.random().toString(36).slice(2,6)}`,quoteId:q.id,customerId:q.customerId,productId:q.productId,quantity:q.quantity,unitPrice:q.unitPrice,total:q.total,dueAt:now+7*86400000,paymentDueAt:now+q.paymentDays*86400000,status:'open',createdAt:now};s.orders.push(order);c.customerOrders??=[];c.customerOrders.push({...order});return{success:true,order};}
export function recordSalesInteraction(c,{customerId,kind='call',result='neutral',at=Date.now()}={}){const s=ensureSales(c),row={id:`interaction-${at}-${Math.random().toString(36).slice(2,5)}`,customerId,kind,result,at};s.interactions.push(row);return row;}
export function salesKpis(c){const s=ensureSales(c),leads=s.leads.length,qualified=s.leads.filter(x=>x.status==='qualified'||x.status==='quoted').length,quotes=s.quotes.length,accepted=s.quotes.filter(x=>x.status==='accepted').length;return{leads,qualified,quotes,accepted,leadToQuote:leads?quotes/leads:0,quoteWinRate:quotes?accepted/quotes:0,openOrders:s.orders.filter(x=>x.status==='open').length,crm:crmKpis(c),pricing:pricingKpis(c)};}
