// WorldProject – Fuhrparkdisposition mit Fahrerzeit, Rückladung und Tourkosten.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureFleetDispatch(c={}){c.fleetDispatch??={routes:[],assignments:[],drivers:[]};c.vehicles??=[];return c.fleetDispatch;}
export function registerDriver(c,{id,name,maxDailyHours=9}={}){const f=ensureFleetDispatch(c),d={id:id||`driver-${f.drivers.length+1}`,name:name||'Fahrer',maxDailyHours:n(maxDailyHours,9),hoursToday:0,status:'available'};f.drivers.push(d);return d;}
export function planRoute(c,{stops=[],distanceKm=0,cargoKg=0,returnCargoKg=0,startAt=Date.now(),avgSpeedKmh=55,serviceMinutesPerStop=20}={}){const f=ensureFleetDispatch(c),driveHours=Math.max(0,n(distanceKm))/Math.max(1,n(avgSpeedKmh,55)),serviceHours=stops.length*Math.max(0,n(serviceMinutesPerStop))/60,totalHours=driveHours+serviceHours,route={id:`route-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,stops:[...stops],distanceKm:n(distanceKm),cargoKg:n(cargoKg),returnCargoKg:n(returnCargoKg),startAt,totalHours,endAt:startAt+totalHours*3600000,status:'planned'};f.routes.push(route);return route;}
export function eligibleVehicles(c,route){return (c.vehicles||[]).filter(v=>!['broken','maintenance','busy'].includes(v.status)&&n(v.payloadKg,v.capacityKg)>=Math.max(n(route.cargoKg),n(route.returnCargoKg)));}
export function eligibleDrivers(c,route){const f=ensureFleetDispatch(c);return f.drivers.filter(d=>d.status==='available'&&n(d.hoursToday)+n(route.totalHours)<=n(d.maxDailyHours,9));}
export function dispatchRoute(c,routeId,{vehicleId,driverId,now=Date.now()}={}){const f=ensureFleetDispatch(c),r=f.routes.find(x=>x.id===routeId);if(!r)throw new Error('Tour fehlt');if(r.status!=='planned')return{success:true,idempotent:true,route:r};const v=(c.vehicles||[]).find(x=>(x.id||x.vehicleId)===vehicleId),d=f.drivers.find(x=>x.id===driverId);if(!v||!eligibleVehicles(c,r).includes(v))throw new Error('Fahrzeug ungeeignet oder nicht verfügbar');if(!d||!eligibleDrivers(c,r).includes(d))throw new Error('Fahrer ungeeignet oder Lenkzeit überschritten');v.status='busy';v.busyUntil=r.endAt;d.status='busy';d.busyUntil=r.endAt;r.vehicleId=vehicleId;r.driverId=driverId;r.startedAt=now;r.status='running';f.assignments.push({routeId:r.id,vehicleId,driverId,at:now});return{success:true,route:r};}
export function finishRoute(c,routeId,{now=Date.now(),dieselPrice=1.55}={}){const f=ensureFleetDispatch(c),r=f.routes.find(x=>x.id===routeId);if(!r)throw new Error('Tour fehlt');if(r.status==='done')return{success:true,idempotent:true,route:r};const v=(c.vehicles||[]).find(x=>(x.id||x.vehicleId)===r.vehicleId),d=f.drivers.find(x=>x.id===r.driverId);const liters=n(r.distanceKm)/100*n(v?.consumptionL100km,25),fuelCost=liters*n(dieselPrice),driverCost=n(r.totalHours)*n(d?.hourlyCost,22),cost=fuelCost+driverCost;if(v){v.status='available';v.km=n(v.km)+n(r.distanceKm);v.busyUntil=0;}if(d){d.status='available';d.hoursToday=n(d.hoursToday)+n(r.totalHours);d.busyUntil=0;}r.status='done';r.finishedAt=now;r.liters=liters;r.cost=cost;r.backhaulUtilization=n(v?.payloadKg,v?.capacityKg)?Math.min(1,n(r.returnCargoKg)/n(v?.payloadKg,v?.capacityKg)):0;c.costLedger??=[];c.costLedger.push({kind:'transport',amount:cost,routeId:r.id,at:now});return{success:true,route:r,cost};}
export function fleetDispatchKpis(c){const f=ensureFleetDispatch(c),routes=f.routes;return{planned:routes.filter(x=>x.status==='planned').length,running:routes.filter(x=>x.status==='running').length,done:routes.filter(x=>x.status==='done').length,totalKm:routes.filter(x=>x.status==='done').reduce((s,x)=>s+n(x.distanceKm),0),totalCost:routes.filter(x=>x.status==='done').reduce((s,x)=>s+n(x.cost),0),averageBackhaul:routes.filter(x=>x.status==='done').length?routes.filter(x=>x.status==='done').reduce((s,x)=>s+n(x.backhaulUtilization),0)/routes.filter(x=>x.status==='done').length:0};}
