// WorldProject – mehrstufige Produktion/Leistung, Losgrößen, Rüstzeiten, Reinigung, Teilfertigung, Nacharbeit.
import { industryRecipes, recipeScale } from "./UniversalIndustryCycle.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureAdvancedProduction(c={}){c.advancedProduction??={routes:[],jobs:[],setups:[],rework:[],history:[]};return c.advancedProduction;}
export function defineProductionRoute(c,{id,productId,stages=[]}={}){const s=ensureAdvancedProduction(c),row={id:id||`route-${productId}`,productId,stages:stages.map((x,i)=>({sequence:i+1,minBatch:1,maxBatch:Infinity,setupMinutes:0,cleaningMinutes:0,...x}))};const old=s.routes.find(x=>x.id===row.id);if(old)Object.assign(old,row);else s.routes.push(row);return row;}
export function routeForProduct(c,productId){return ensureAdvancedProduction(c).routes.find(x=>x.productId===productId)||null;}
export function optimalBatchSize({demand,setupCost=0,holdingCostPerUnit=0.1,minBatch=1,maxBatch=Infinity}={}){const d=Math.max(1,n(demand)),h=Math.max(.0001,n(holdingCostPerUnit,.1)),s=Math.max(0,n(setupCost));const eoq=Math.sqrt(2*d*s/h);return Math.max(n(minBatch,1),Math.min(Number.isFinite(maxBatch)?maxBatch:d,Math.round(eoq||d)));}
export function createProductionLots(c,{recipeId,amount,minBatch=1,maxBatch=Infinity,setupCost=0,holdingCostPerUnit=.1,priority=0,dueAt=null,now=Date.now()}={}){const s=ensureAdvancedProduction(c),recipe=industryRecipes(c).find(x=>x.id===recipeId);if(!recipe)throw new Error("Rezept fehlt");let left=Math.max(0,n(amount)),batch=optimalBatchSize({demand:left,setupCost,holdingCostPerUnit,minBatch,maxBatch}),lots=[];while(left>1e-9){const q=Math.min(left,batch),lot={id:`lotjob-${now}-${lots.length}-${Math.random().toString(36).slice(2,5)}`,recipeId,productId:recipe.product,quantity:q,completed:0,scrap:0,status:"planned",priority:n(priority),dueAt,createdAt:now};lots.push(lot);s.jobs.push(lot);left-=q;}return lots;}
export function calculateStageDuration(stage,quantity,{previousProductId=null,nextProductId=null}={}){const q=Math.max(0,n(quantity)),base=Math.max(0,n(stage.minutesPerUnit))*q+n(stage.fixedMinutes),setup=n(stage.setupMinutes)+(previousProductId&&stage.productId&&previousProductId!==stage.productId?n(stage.changeoverMinutes):0),cleaning=n(stage.cleaningMinutes)+(nextProductId&&stage.cleaningOnChange&&nextProductId!==stage.productId?n(stage.changeCleaningMinutes):0);return{processMinutes:base,setupMinutes:setup,cleaningMinutes:cleaning,totalMinutes:base+setup+cleaning};}
export function stageMaterialNeed(c,recipeId,quantity){const r=industryRecipes(c).find(x=>x.id===recipeId);if(!r)throw new Error("Rezept fehlt");return recipeScale(r,quantity);}
export function startAdvancedLot(c,lotId,{now=Date.now()}={}){const s=ensureAdvancedProduction(c),lot=s.jobs.find(x=>x.id===lotId);if(!lot)throw new Error("Los fehlt");if(lot.status==="running")return{success:true,idempotent:true,lot};if(!["planned","paused","rework_planned"].includes(lot.status))throw new Error("Los kann nicht gestartet werden");lot.status="running";lot.startedAt??=now;lot.lastResumeAt=now;return{success:true,lot};}
export function pauseAdvancedLot(c,lotId,{now=Date.now()}={}){const lot=ensureAdvancedProduction(c).jobs.find(x=>x.id===lotId);if(!lot)throw new Error("Los fehlt");if(lot.status!=="running")return lot;lot.status="paused";lot.pausedAt=now;return lot;}
export function partialCompleteLot(c,lotId,quantity,{scrapRate=0,now=Date.now()}={}){const s=ensureAdvancedProduction(c),lot=s.jobs.find(x=>x.id===lotId);if(!lot)throw new Error("Los fehlt");const remaining=Math.max(0,n(lot.quantity)-n(lot.completed)-n(lot.scrap)),gross=Math.min(remaining,Math.max(0,n(quantity))),scrap=gross*Math.max(0,Math.min(1,n(scrapRate))),good=gross-scrap;lot.completed=n(lot.completed)+good;lot.scrap=n(lot.scrap)+scrap;c.finishedGoods??={};c.finishedGoods[lot.productId]=n(c.finishedGoods[lot.productId])+good;if(lot.completed+lot.scrap>=lot.quantity-1e-9){lot.status="completed";lot.completedAt=now;}else lot.status="partial";s.history.push({kind:"partial_complete",lotId,good,scrap,at:now});return{good,scrap,remaining:Math.max(0,lot.quantity-lot.completed-lot.scrap),status:lot.status};}
export function createRework(c,lotId,quantity,{machineId=null,laborHours=1,costPerHour=25,now=Date.now()}={}){const s=ensureAdvancedProduction(c),lot=s.jobs.find(x=>x.id===lotId);if(!lot)throw new Error("Los fehlt");const q=Math.min(Math.max(0,n(quantity)),n(lot.scrap)),row={id:`rework-${now}-${Math.random().toString(36).slice(2,6)}`,lotId,productId:lot.productId,quantity:q,machineId,laborHours:Math.max(0,n(laborHours)),cost:Math.max(0,n(laborHours))*Math.max(0,n(costPerHour)),status:"planned",createdAt:now};s.rework.push(row);return row;}
export function finishRework(c,reworkId,{recoveryRate=.8,now=Date.now()}={}){const s=ensureAdvancedProduction(c),r=s.rework.find(x=>x.id===reworkId);if(!r)throw new Error("Nacharbeit fehlt");if(r.status==="done")return{success:true,idempotent:true,recovered:r.recovered};const lot=s.jobs.find(x=>x.id===r.lotId),recovered=r.quantity*Math.max(0,Math.min(1,n(recoveryRate,.8)));lot.scrap=Math.max(0,n(lot.scrap)-recovered);lot.completed=n(lot.completed)+recovered;c.finishedGoods??={};c.finishedGoods[r.productId]=n(c.finishedGoods[r.productId])+recovered;c.money=n(c.money)-r.cost;c.costLedger??=[];c.costLedger.push({kind:"rework",amount:r.cost,at:now,reworkId:r.id});r.status="done";r.recovered=recovered;r.finishedAt=now;return{success:true,recovered,cost:r.cost};}
export function productionDeviationKpis(c){const h=ensureAdvancedProduction(c).history,jobs=ensureAdvancedProduction(c).jobs,completed=jobs.filter(x=>x.status==="completed");const scrap=jobs.reduce((s,x)=>s+n(x.scrap),0),qty=jobs.reduce((s,x)=>s+n(x.quantity),0);return{jobs:jobs.length,completed:completed.length,partial:jobs.filter(x=>x.status==="partial").length,paused:jobs.filter(x=>x.status==="paused").length,scrapRate:qty?scrap/qty:0,history:h.length};}
