// Lädt ausschließlich Diagnosen/Tests und gemeinsame Integrationsbrücken. Keine zweite Oberfläche.
import { runIndustryContentCoverageAudit } from "./IndustryContentCoverageAudit.js";
import { runAllIndustryEconomyRegression } from "./AllIndustryEconomyRegression.js";
import { runAllIndustryLifecycleRegression } from "./AllIndustryLifecycleRegression.js";
import { runIndustryDeepSimulationRegression } from "./IndustryDeepSimulationRegression.js";
import "./IndustryEconomyDiagnostics.js";
import "./IndustryManagementDashboardData.js";
import "./BusinessCommandCenter.js";
import "./CustomerOrderLifecycle.js";
import "./AdvancedProductionFlow.js";
import "./InboundInventoryAndLogistics.js";
import "./WorkforceOrganizationSystem.js";
import "./CorporateStrategyAndExpansion.js";
import "./ExistingUIIntegrationAdapters.js";
import "./IndustryEquipmentMarketplace.js";
import "./ProductionReadinessAssistant.js";
import "./OperationsActionBridge.js";
import "./OperationsPersistenceCoordinator.js";
import "./IndustryOperationalDashboardVM.js";
import "./OperationsSectionRegistry.js";
import "./AdvancedMachineProductionControl.js";
import "./AdvancedWorkforceScheduling.js";
import "./AdvancedProcurementWorkflow.js";
import "./AdvancedFleetDispatch.js";
import "./AdvancedSalesEngine.js";
import "./IntegratedFinanceController.js";
import "./AdvancedSiteExpansionPlanner.js";
import "./WorldEconomySimulation.js";
import "./IndustryBusinessRules.js";
import "./NPCCompanySimulation.js";
import "./PlayerMarketExchange.js";
import "./TenderContractSystem.js";
import "./BrandReputationSystem.js";
import "./InnovationPipelineSystem.js";
import "./CompanyProgressionAchievements.js";
import "./DynamicBusinessEventSystem.js";
import "./InterCompanyTradeNetwork.js";
import "./BusinessRestructuringSystem.js";
import "./InsuranceClaimsSystem.js";
import "./TaxAndRegulationSystem.js";
import "./WarehouseAutomationSystem.js";
import "./DemandForecastingEngine.js";
import "./ProcurementAuctionSystem.js";
import "./LogisticsHubNetwork.js";
import "./PlayerNotificationCenter.js";
import "./OperationalOnboardingAdvisor.js";
import "./EconomyTelemetryDiagnostics.js";
import "./ReleaseReadinessSystem.js";
import "./RuntimePerformanceBudget.js";
import "./MobileOperationsPresentation.js";
import "./OperationsLocalizationRegistry.js";
import "./OfflineActionQueue.js";
import "./CompanyDataIntegrityAuditor.js";
import "./SavegameMigrationPlanner.js";
import "./MarketFairnessGuard.js";
import "./WorldPopulationScaler.js";
import "./ContextualPlayerActions.js";
import "./PlayerFacingErrorResolver.js";
import "./OperationTransactionCoordinator.js";
import "./OperationsUIStateCoordinator.js";
import "./AllianceLaunchGuard.js";
import "./WorldLoadScenarioGenerator.js";
import "./SystemOperationsMonitor.js";
import "./OperationsAccessibilityModel.js";
import { runIntegratedGameplayHealthCheck } from "./IntegratedGameplayHealthCheck.js";
import { runIntegrated1000Health } from "./Integrated1000Health.js";
import { runIntegratedThird1000Health } from "./IntegratedThird1000Health.js";
import { runIntegratedFourth1000Health } from "./IntegratedFourth1000Health.js";
import { runIntegratedFifth1000Health } from "./IntegratedFifth1000Health.js";
import { runIntegrated2500CompletionHealth } from "./Integrated2500CompletionHealth.js";
import { runLongTermAllIndustrySimulation } from "./LongTermCompanySimulator.js";
export function runAllIndustryEconomyHealth(){
 const coverage=runIndustryContentCoverageAudit();
 const regression=runAllIndustryEconomyRegression();
 const lifecycle=runAllIndustryLifecycleRegression();
 const deepSimulation=runIndustryDeepSimulationRegression();
 const report={success:coverage.success&&regression.success&&lifecycle.success&&deepSimulation.success,coverage,regression,lifecycle,deepSimulation,runIntegratedGameplayHealth:()=>runIntegratedGameplayHealthCheck(),runIntegrated1000Health:(options={})=>runIntegrated1000Health(options),runThird1000Health:()=>runIntegratedThird1000Health(),runFourth1000Health:()=>runIntegratedFourth1000Health(),runFifth1000Health:()=>runIntegratedFifth1000Health(),run2500CompletionHealth:()=>runIntegrated2500CompletionHealth(),runLongTermSimulation:(years=5)=>runLongTermAllIndustrySimulation({years}),ranAt:Date.now()};
 if(typeof window!=="undefined")window.worldAllIndustryEconomyHealth=report;
 console[report.success?"log":"error"](`WORLDPROJECT ALLE-GEWERBE HEALTH ${report.success?'GRÜN':'FEHLER'} · DEEP ${deepSimulation.passed}/250`,report);
 return report;
}
