// WorldProject – Allianzsystem. Standardmäßig unsichtbar für normale Spieler.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export const AllianceFeatureFlags={playerVisible:false,creationEnabled:false,applicationsEnabled:false,publicRanking:false};
export const AllianceRoles={leader:{label:"Allianzleiter",permissions:["manage_members","manage_roles","manage_treasury","manage_projects","manage_diplomacy","manage_settings"]},officer:{label:"Offizier",permissions:["manage_members","manage_projects","manage_logistics"]},treasurer:{label:"Kassenwart",permissions:["manage_treasury"]},member:{label:"Mitglied",permissions:["contribute","view_members","view_projects"]}};
export function ensureAllianceState(world={}){world.alliances??=[];world.allianceInvites??=[];world.allianceApplications??=[];world.allianceEvents??=[];return world;}
export function allianceVisibleForPlayer(){return !!AllianceFeatureFlags.playerVisible;}
export function setAllianceFeatureFlag(flag,value){if(!(flag in AllianceFeatureFlags))throw new Error("Unbekanntes Allianz-Feature");AllianceFeatureFlags[flag]=!!value;return AllianceFeatureFlags[flag];}
export function createAlliance(world,{name,tag,founderPlayerId,founderCompanyId,language="de",description="",now=Date.now(),force=false}={}){ensureAllianceState(world);if(!force&&!AllianceFeatureFlags.creationEnabled)throw new Error("Allianzgründung ist noch nicht freigeschaltet");if(!name||!tag)throw new Error("Name und Kürzel erforderlich");if(world.alliances.some(a=>a.name.toLowerCase()===String(name).toLowerCase()||a.tag.toLowerCase()===String(tag).toLowerCase()))throw new Error("Allianzname oder Kürzel bereits vergeben");const a={id:`alliance-${now}-${Math.random().toString(36).slice(2,7)}`,name,tag,language,description,createdAt:now,status:"active",settings:{joinMode:"invite",minCompanyLevel:1,maxMembers:50},members:[{playerId:founderPlayerId,companyId:founderCompanyId,role:"leader",joinedAt:now,contribution:0}],treasury:{money:0,ledger:[]},projects:[],logistics:[],messages:[],diplomacy:[],stats:{xp:0,level:1}};world.alliances.push(a);return a;}
export function findAlliance(world,id){return ensureAllianceState(world).alliances.find(a=>a.id===id)||null;}
export function memberOf(a,playerId){return a?.members?.find(m=>m.playerId===playerId)||null;}
export function hasAlliancePermission(a,playerId,permission){const m=memberOf(a,playerId);return !!m&&((AllianceRoles[m.role]?.permissions||[]).includes(permission));}
export function inviteToAlliance(world,allianceId,{actorPlayerId,targetPlayerId,expiresDays=7,now=Date.now()}={}){const a=findAlliance(world,allianceId);if(!a)throw new Error("Allianz fehlt");if(!hasAlliancePermission(a,actorPlayerId,"manage_members"))throw new Error("Keine Berechtigung");if(memberOf(a,targetPlayerId))return{success:true,idempotent:true};const old=world.allianceInvites.find(x=>x.allianceId===allianceId&&x.targetPlayerId===targetPlayerId&&x.status==="open");if(old)return{success:true,idempotent:true,invite:old};const row={id:`ainvite-${now}-${Math.random().toString(36).slice(2,6)}`,allianceId,targetPlayerId,actorPlayerId,status:"open",createdAt:now,expiresAt:now+Math.max(1,n(expiresDays,7))*86400000};world.allianceInvites.push(row);return{success:true,invite:row};}
export function acceptAllianceInvite(world,inviteId,{playerId,companyId,now=Date.now()}={}){ensureAllianceState(world);const i=world.allianceInvites.find(x=>x.id===inviteId);if(!i||i.targetPlayerId!==playerId)throw new Error("Einladung fehlt");if(i.status==="accepted")return{success:true,idempotent:true};if(i.status!=="open"||i.expiresAt<now)throw new Error("Einladung nicht mehr gültig");const a=findAlliance(world,i.allianceId);if(!a||a.members.length>=a.settings.maxMembers)throw new Error("Allianz nicht verfügbar");a.members.push({playerId,companyId,role:"member",joinedAt:now,contribution:0});i.status="accepted";i.acceptedAt=now;return{success:true,alliance:a};}
export function applyToAlliance(world,allianceId,{playerId,companyId,message="",now=Date.now()}={}){if(!AllianceFeatureFlags.applicationsEnabled)throw new Error("Bewerbungen sind noch nicht freigeschaltet");const a=findAlliance(world,allianceId);if(!a)throw new Error("Allianz fehlt");const old=world.allianceApplications.find(x=>x.allianceId===allianceId&&x.playerId===playerId&&x.status==="open");if(old)return old;const row={id:`aapply-${now}-${Math.random().toString(36).slice(2,6)}`,allianceId,playerId,companyId,message,status:"open",createdAt:now};world.allianceApplications.push(row);return row;}
export function setAllianceRole(a,{actorPlayerId,targetPlayerId,role}={}){if(!AllianceRoles[role])throw new Error("Allianzrolle fehlt");if(!hasAlliancePermission(a,actorPlayerId,"manage_roles"))throw new Error("Keine Berechtigung");const target=memberOf(a,targetPlayerId);if(!target)throw new Error("Mitglied fehlt");if(target.role==="leader"&&actorPlayerId!==targetPlayerId)throw new Error("Allianzleiter kann nicht direkt überschrieben werden");target.role=role;return target;}
export function contributeAllianceMoney(a,{playerId,amount,company,now=Date.now()}={}){const m=memberOf(a,playerId);if(!m)throw new Error("Kein Allianzmitglied");const q=Math.max(0,n(amount));if(q<=0||n(company?.money)<q)throw new Error("Beitrag nicht möglich");company.money-=q;a.treasury.money=n(a.treasury.money)+q;m.contribution=n(m.contribution)+q;a.treasury.ledger.push({kind:"contribution",playerId,amount:q,at:now});return{success:true,amount:q,balance:a.treasury.money};}
export function spendAllianceMoney(a,{actorPlayerId,amount,purpose="",now=Date.now()}={}){if(!hasAlliancePermission(a,actorPlayerId,"manage_treasury"))throw new Error("Keine Kassenberechtigung");const q=Math.max(0,n(amount));if(n(a.treasury.money)<q)throw new Error("Allianzkasse reicht nicht");a.treasury.money-=q;a.treasury.ledger.push({kind:"spend",actorPlayerId,amount:q,purpose,at:now});return{success:true,balance:a.treasury.money};}
export function createAllianceProject(a,{actorPlayerId,title,type="community",target=100000,deadline=null,now=Date.now()}={}){if(!hasAlliancePermission(a,actorPlayerId,"manage_projects"))throw new Error("Keine Projektberechtigung");const p={id:`aproject-${now}-${Math.random().toString(36).slice(2,6)}`,title,type,target:Math.max(1,n(target)),progress:0,status:"active",createdAt:now,deadline,contributions:[]};a.projects.push(p);return p;}
export function contributeAllianceProject(a,projectId,{playerId,value,now=Date.now()}={}){const p=a.projects.find(x=>x.id===projectId);if(!p||p.status!=="active")throw new Error("Allianzprojekt nicht aktiv");if(!memberOf(a,playerId))throw new Error("Kein Allianzmitglied");const q=Math.max(0,n(value));p.progress=Math.min(p.target,n(p.progress)+q);p.contributions.push({playerId,value:q,at:now});if(p.progress>=p.target){p.status="completed";p.completedAt=now;a.stats.xp=n(a.stats.xp)+100;}return p;}
export function allianceKpis(a){return{members:a.members.length,treasury:n(a.treasury.money),activeProjects:a.projects.filter(x=>x.status==="active").length,completedProjects:a.projects.filter(x=>x.status==="completed").length,level:n(a.stats.level,1),xp:n(a.stats.xp)};}
if(typeof window!=="undefined"){window.worldAllianceSystem={featureFlags:AllianceFeatureFlags,visible:allianceVisibleForPlayer,setFeatureFlag:setAllianceFeatureFlag};}
