// Erweiterungen fuer das versteckte Allianzsystem. Keine Spielerfreigabe.
import { AllianceFeatureFlags } from './AllianceSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureAllianceAdvanced(a={}){a.diplomacy??=[];a.research??={points:0,projects:[]};a.sharedLogistics??=[];a.activity??=[];a.rules??={minContribution:0,inactiveDays:30};return a;}
export function requireAllianceInternal(){if(AllianceFeatureFlags.playerVisible) return true;return true;}
export function proposeDiplomacy(a,targetAllianceId,type='trade',{durationDays=30}={}){ensureAllianceAdvanced(a);const row={id:`dip-${Date.now()}`,targetAllianceId,type,status:'proposed',createdAt:Date.now(),endsAt:Date.now()+Math.max(1,n(durationDays))*86400000};a.diplomacy.push(row);return row;}
export function acceptDiplomacy(a,id){const d=ensureAllianceAdvanced(a).diplomacy.find(x=>x.id===id);if(!d)throw new Error('Allianzabkommen fehlt');d.status='active';d.acceptedAt=Date.now();return d;}
export function addAllianceResearchPoints(a,points,source='member_activity'){ensureAllianceAdvanced(a);a.research.points+=Math.max(0,n(points));a.activity.push({kind:'research_points',points:n(points),source,at:Date.now()});return a.research.points;}
export function startAllianceResearch(a,{id,label,cost=100,durationHours=24,bonus={}}={}){ensureAllianceAdvanced(a);if(a.research.points<n(cost))throw new Error('Nicht genug Allianz-Forschungspunkte');a.research.points-=n(cost);const p={id:id||`ar-${Date.now()}`,label:label||'Allianzforschung',cost:n(cost),bonus,status:'running',startedAt:Date.now(),endsAt:Date.now()+Math.max(1,n(durationHours))*3600000};a.research.projects.push(p);return p;}
export function finishAllianceResearch(a,id,{now=Date.now(),force=false}={}){const p=ensureAllianceAdvanced(a).research.projects.find(x=>x.id===id);if(!p)throw new Error('Forschung fehlt');if(!force&&now<p.endsAt)throw new Error('Forschung laeuft noch');p.status='done';p.finishedAt=now;return p;}
export function createSharedLogisticsProject(a,{fromSite,toSite,item,quantity,cost=0}={}){ensureAllianceAdvanced(a);const p={id:`alog-${Date.now()}`,fromSite,toSite,item,quantity:Math.max(0,n(quantity)),cost:Math.max(0,n(cost)),status:'planned',createdAt:Date.now()};a.sharedLogistics.push(p);return p;}
export function allianceInternalKpis(a){ensureAllianceAdvanced(a);return{members:(a.members||[]).length,treasury:n(a.treasury),activeDiplomacy:a.diplomacy.filter(x=>x.status==='active').length,researchPoints:a.research.points,researchDone:a.research.projects.filter(x=>x.status==='done').length,logisticsOpen:a.sharedLogistics.filter(x=>x.status!=='done').length,playerVisible:!!AllianceFeatureFlags.playerVisible};}
