// WorldProject - unsichtbarer Allianz-Austausch-Unterbau.
// Kein UI, solange ALLIANCE_EXCHANGE_ENABLED=false.
export const ALLIANCE_EXCHANGE_ENABLED=false;
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureAllianceState(world={}){world.alliances??={alliances:[],exchange:{orders:[],trades:[],feesCollected:0}};world.alliances.exchange??={orders:[],trades:[],feesCollected:0};return world.alliances;}
export function allianceById(world,id){return ensureAllianceState(world).alliances.find(a=>String(a.id)===String(id))||null;}
export function allianceMembership(world,company){const cid=String(company?.serverCompanyId||company?.id||'');for(const a of ensureAllianceState(world).alliances){const m=(a.members||[]).find(x=>String(x.companyId||x.id)===cid);if(m)return{alliance:a,member:m};}return null;}
export function canAllianceTrade(world,company){const m=allianceMembership(world,company);return !!m&&!['suspended','banned'].includes(String(m.member.status||'active'));}
export function createAlliance(world,{id=`alliance-${Date.now()}`,name,founderCompanyId}={}){if(!name||!founderCompanyId)throw new Error('Allianzname und Gründerbetrieb erforderlich');const s=ensureAllianceState(world);if(s.alliances.some(a=>String(a.id)===String(id)))throw new Error('Allianz existiert bereits');const a={id,name,createdAt:Date.now(),members:[{companyId:founderCompanyId,role:'leader',status:'active',joinedAt:Date.now()}],settings:{exchangeEnabled:true}};s.alliances.push(a);return a;}
export function addAllianceMember(world,allianceId,{companyId,role='member'}={}){const a=allianceById(world,allianceId);if(!a)throw new Error('Allianz nicht gefunden');if((a.members||[]).some(m=>String(m.companyId)===String(companyId)))return{success:true,idempotent:true};a.members??=[];a.members.push({companyId,role,status:'active',joinedAt:Date.now()});return{success:true};}
export function placeAllianceOffer(world,company,{productId,quantity,unitPrice}={}){const m=allianceMembership(world,company);if(!m||!m.alliance.settings?.exchangeEnabled)throw new Error('Kein Allianz-Austausch verfügbar');const q=Math.max(0,n(quantity)),p=Math.max(0,n(unitPrice));if(!productId||q<=0||p<0)throw new Error('Ungültiges Allianz-Angebot');const ex=ensureAllianceState(world).exchange,order={id:`ax-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,allianceId:m.alliance.id,companyId:company.serverCompanyId||company.id,productId,quantity:q,remaining:q,unitPrice:p,status:'open',createdAt:Date.now()};ex.orders.push(order);return{success:true,order};}
export function allianceOrderBook(world,company,productId=null){const m=allianceMembership(world,company);if(!m)return[];return ensureAllianceState(world).exchange.orders.filter(o=>String(o.allianceId)===String(m.alliance.id)&&['open','partial'].includes(o.status)&&(!productId||o.productId===productId));}
export function runAllianceExchangeSystemTest(){const w={},a=createAlliance(w,{id:'a1',name:'Test Allianz',founderCompanyId:'c1'});addAllianceMember(w,a.id,{companyId:'c2'});const c1={id:'c1'},c2={id:'c2'};if(!canAllianceTrade(w,c1)||!canAllianceTrade(w,c2))throw new Error('Allianz-Mitgliedschaft fehlerhaft');placeAllianceOffer(w,c1,{productId:'malt',quantity:100,unitPrice:1});if(allianceOrderBook(w,c2,'malt').length!==1)throw new Error('Allianz-Austausch isoliert nicht korrekt');return true;}
if(typeof window!=='undefined')window.worldAllianceExchange={enabled:ALLIANCE_EXCHANGE_ENABLED,ensure:ensureAllianceState,membership:allianceMembership,book:allianceOrderBook,test:runAllianceExchangeSystemTest};
