// WorldProject - Supabase Auth + Data API Client
const SUPABASE_URL = "https://ojhaeccyulyrwoxgeurf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_JZH6Ker5-yZoNY6sQFhVTA_YKnImI3z";
const SESSION_KEY = "worldproject_supabase_session";

export class AuthApiClient {
    constructor({ baseUrl = SUPABASE_URL, publishableKey = SUPABASE_PUBLISHABLE_KEY } = {}) { this.baseUrl=baseUrl.replace(/\/$/,"");this.publishableKey=publishableKey;this.session=this.loadSession();this.captureSessionFromUrl(); }
    loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null");}catch{return null;}}
    saveSession(session){this.session=session||null;if(session)localStorage.setItem(SESSION_KEY,JSON.stringify(session));else localStorage.removeItem(SESSION_KEY);}
    captureSessionFromUrl(){const raw=location.hash?.replace(/^#/,"");if(!raw)return null;const p=new URLSearchParams(raw),access_token=p.get("access_token"),refresh_token=p.get("refresh_token");if(!access_token)return null;const session={access_token,refresh_token,expires_in:Number(p.get("expires_in")||3600),token_type:p.get("token_type")||"bearer",expires_at:Math.floor(Date.now()/1000)+Number(p.get("expires_in")||3600),type:p.get("type")||null};this.saveSession(session);history.replaceState(null,document.title,location.pathname+location.search);return session;}
    headers({auth=false,json=true}={}){const h={apikey:this.publishableKey};if(json)h["Content-Type"]="application/json";if(auth&&this.session?.access_token)h.Authorization=`Bearer ${this.session.access_token}`;return h;}
    async parse(response){const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.msg||body.message||body.error_description||body.error||`HTTP ${response.status}`);return body;}
    async health(){const r=await fetch(`${this.baseUrl}/auth/v1/health`,{headers:this.headers({json:false})});if(!r.ok)throw new Error("Supabase nicht erreichbar");return{success:true,mode:"supabase"};}

    async register(data){const r=await fetch(`${this.baseUrl}/auth/v1/signup`,{method:"POST",headers:this.headers(),body:JSON.stringify({email:data.email,password:data.password,data:{username:data.username,country_code:data.countryCode||"DE",language_code:data.languageCode||"de",terms_version:"1.0",privacy_version:"1.0"}})});const body=await this.parse(r);if(body.access_token)this.saveSession(body);return{success:true,user:body.user,session:body.access_token?body:null,confirmationRequired:!body.access_token};}
    async login({email,password,emailOrUsername}={}){const r=await fetch(`${this.baseUrl}/auth/v1/token?grant_type=password`,{method:"POST",headers:this.headers(),body:JSON.stringify({email:email||emailOrUsername,password})});const body=await this.parse(r);this.saveSession(body);return{success:true,user:await this.me()};}
    async refreshSession(){const token=this.session?.refresh_token;if(!token)throw new Error("Keine Sitzung vorhanden");const r=await fetch(`${this.baseUrl}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:this.headers(),body:JSON.stringify({refresh_token:token})});const body=await this.parse(r);this.saveSession(body);return body;}
    async ensureAccessToken(){if(!this.session?.access_token)return null;const exp=Number(this.session.expires_at||0);if(exp&&exp-60>Math.floor(Date.now()/1000))return this.session.access_token;try{await this.refreshSession();return this.session?.access_token||null;}catch{this.saveSession(null);return null;}}
    async authRequest(path,options={}){const token=await this.ensureAccessToken();if(!token)throw new Error("Nicht angemeldet");const r=await fetch(`${this.baseUrl}${path}`,{...options,headers:{...this.headers({auth:true}),...(options.headers||{})}});return this.parse(r);}
    async rest(path,options={}){return this.authRequest(`/rest/v1/${path}`,options);}
    async rpc(name,data={}){return this.rest(`rpc/${name}`,{method:"POST",body:JSON.stringify(data)});}

    async me(){const token=await this.ensureAccessToken();if(!token)throw new Error("Nicht angemeldet");const ar=await fetch(`${this.baseUrl}/auth/v1/user`,{headers:this.headers({auth:true,json:false})}),authUser=await this.parse(ar),rows=await this.rest(`users?auth_user_id=eq.${encodeURIComponent(authUser.id)}&select=id,public_id,auth_user_id,username,email,status,country_code,language_code,email_verified_at,display_name,profile_image_url,created_at`),profile=rows?.[0];if(!profile)throw new Error("Spielerprofil wurde noch nicht angelegt");return{...profile,authId:authUser.id,emailConfirmedAt:authUser.email_confirmed_at||null};}
    async logout(){try{if(this.session?.access_token)await fetch(`${this.baseUrl}/auth/v1/logout`,{method:"POST",headers:this.headers({auth:true})});}finally{this.saveSession(null);}return{success:true};}
    async resendVerification(email){const r=await fetch(`${this.baseUrl}/auth/v1/resend`,{method:"POST",headers:this.headers(),body:JSON.stringify({type:"signup",email})});await this.parse(r);return{success:true};}
    async requestPasswordReset(email){const r=await fetch(`${this.baseUrl}/auth/v1/recover`,{method:"POST",headers:this.headers(),body:JSON.stringify({email})});await this.parse(r);return{success:true};}
    async resetPassword(_token,password){const r=await fetch(`${this.baseUrl}/auth/v1/user`,{method:"PUT",headers:this.headers({auth:true}),body:JSON.stringify({password})});await this.parse(r);return{success:true};}

    async listCompanies(){return this.rest(`companies?select=id,name,industry,company_type,money,game_state,saved_at,created_at,slot_no,setup_phase,building_state,is_primary&order=slot_no.asc`);}
    async accountOverview(){const user=await this.me();const[walletRows,companies,txRows]=await Promise.all([this.rest(`coin_wallets?select=balance,updated_at`),this.listCompanies(),this.rest(`coin_transactions?select=id,amount,balance_after,transaction_type,reference_type,reference_id,note,created_at&order=created_at.desc&limit=30`)]);return{success:true,user,wallet:walletRows?.[0]||{balance:0},companies:companies||[],company:companies?.find(x=>x.slot_no===1)||companies?.[0]||null,transactions:txRows||[]};}

    async updateProfile(data){const user=await this.me(),allowed={};if(data.countryCode!==undefined)allowed.country_code=data.countryCode;if(data.languageCode!==undefined)allowed.language_code=data.languageCode;if(data.displayName!==undefined)allowed.display_name=data.displayName;if(data.profileImageUrl!==undefined)allowed.profile_image_url=data.profileImageUrl;const rows=await this.rest(`users?auth_user_id=eq.${encodeURIComponent(user.auth_user_id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(allowed)});return{success:true,user:rows?.[0]||null};}

    async ensureCompany(data={}){const result=await this.rpc("ensure_player_company",{p_name:data.name||null,p_industry:data.industry||null,p_company_type:data.companyType||data.type||null});return{success:true,company:Array.isArray(result)?result[0]:result};}
    async createBusiness(data={}){const result=await this.rpc("create_player_business",{p_name:data.name||null,p_industry:data.industry||null,p_company_type:data.companyType||data.type||null,p_slot_no:Number(data.slotNo)});return{success:true,company:Array.isArray(result)?result[0]:result};}
    async saveGameState(state){const result=await this.rpc("save_player_game_state",{p_state:state||{}});return{success:true,company:Array.isArray(result)?result[0]:result};}
    async saveBusinessState(companyId,state){const result=await this.rpc("save_player_business_state",{p_company_id:Number(companyId),p_state:state||{}});return{success:true,company:Array.isArray(result)?result[0]:result};}
    async updateBusinessSetup(companyId,setupPhase,buildingState){const result=await this.rpc("update_player_business_setup",{p_company_id:Number(companyId),p_setup_phase:setupPhase,p_building_state:buildingState||{}});return{success:true,company:Array.isArray(result)?result[0]:result};}
    async transferBusinessMoney(fromCompanyId,toCompanyId,amount){const result=await this.rpc("transfer_business_money",{p_from_company_id:Number(fromCompanyId),p_to_company_id:Number(toCompanyId),p_amount:Number(amount)});return{success:true,balances:Array.isArray(result)?result[0]:result};}

    async listCoinOrders(){return this.rest("coin_market_orders?status=eq.open&select=id,seller_user_id,original_amount,remaining_amount,price_per_coin,status,created_at&order=price_per_coin.asc,created_at.asc");}
    async createCoinSellOrder(amount,pricePerCoin){const result=await this.rpc("create_coin_sell_order",{p_amount:Number(amount),p_price_per_coin:Number(pricePerCoin)});return{success:true,orderId:Array.isArray(result)?result[0]:result};}
    async cancelCoinSellOrder(orderId){const result=await this.rpc("cancel_coin_sell_order",{p_order_id:Number(orderId)});return{success:true,balance:Array.isArray(result)?result[0]:result};}
    async buyCoinOrder(orderId,amount){const result=await this.rpc("buy_coin_market_order",{p_order_id:Number(orderId),p_amount:Number(amount)});window.dispatchEvent(new CustomEvent("world:server-balances-changed",{detail:result}));return{success:true,trade:Array.isArray(result)?result[0]:result};}
}
