// WorldProject - Supabase Auth + Data API Client
const SUPABASE_URL = "https://ojhaeccyulyrwoxgeurf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_JZH6Ker5-yZoNY6sQFhVTA_YKnImI3z";
const SESSION_KEY = "worldproject_supabase_session";
export class AuthApiClient {
 constructor({baseUrl=SUPABASE_URL,publishableKey=SUPABASE_PUBLISHABLE_KEY}={}){this.baseUrl=baseUrl.replace(/\/$/,"");this.publishableKey=publishableKey;this.session=this.loadSession();this.captureSessionFromUrl();}
 loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null");}catch{return null;}} saveSession(s){this.session=s||null;if(s)localStorage.setItem(SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(SESSION_KEY);}
 captureSessionFromUrl(){const raw=location.hash?.replace(/^#/,"");if(!raw)return null;const p=new URLSearchParams(raw),access_token=p.get("access_token"),refresh_token=p.get("refresh_token");if(!access_token)return null;const s={access_token,refresh_token,expires_in:Number(p.get("expires_in")||3600),token_type:p.get("token_type")||"bearer",expires_at:Math.floor(Date.now()/1000)+Number(p.get("expires_in")||3600),type:p.get("type")||null};this.saveSession(s);history.replaceState(null,document.title,location.pathname+location.search);return s;}
 headers({auth=false,json=true}={}){const h={apikey:this.publishableKey};if(json)h["Content-Type"]="application/json";if(auth&&this.session?.access_token)h.Authorization=`Bearer ${this.session.access_token}`;return h;}async parse(r){const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.msg||b.message||b.error_description||b.error||`HTTP ${r.status}`);return b;}
 async health(){const r=await fetch(`${this.baseUrl}/auth/v1/health`,{headers:this.headers({json:false})});if(!r.ok)throw new Error("Supabase nicht erreichbar");return{success:true,mode:"supabase"};}
 async register(d){const r=await fetch(`${this.baseUrl}/auth/v1/signup`,{method:"POST",headers:this.headers(),body:JSON.stringify({email:d.email,password:d.password,data:{username:d.username,country_code:d.countryCode||"DE",language_code:d.languageCode||"de",terms_version:"1.0",privacy_version:"1.0"}})}),b=await this.parse(r);if(b.access_token)this.saveSession(b);return{success:true,user:b.user,session:b.access_token?b:null,confirmationRequired:!b.access_token};}
 async login({email,password,emailOrUsername}={}){const r=await fetch(`${this.baseUrl}/auth/v1/token?grant_type=password`,{method:"POST",headers:this.headers(),body:JSON.stringify({email:email||emailOrUsername,password})}),b=await this.parse(r);this.saveSession(b);return{success:true,user:await this.me()};}
 async refreshSession(){const token=this.session?.refresh_token;if(!token)throw new Error("Keine Sitzung vorhanden");const r=await fetch(`${this.baseUrl}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:this.headers(),body:JSON.stringify({refresh_token:token})}),b=await this.parse(r);this.saveSession(b);return b;}async ensureAccessToken(){if(!this.session?.access_token)return null;const exp=Number(this.session.expires_at||0);if(exp&&exp-60>Math.floor(Date.now()/1000))return this.session.access_token;try{await this.refreshSession();return this.session?.access_token||null;}catch{this.saveSession(null);return null;}}
 async authRequest(path,o={}){if(!await this.ensureAccessToken())throw new Error("Nicht angemeldet");const r=await fetch(`${this.baseUrl}${path}`,{...o,headers:{...this.headers({auth:true}),...(o.headers||{})}});return this.parse(r);}async rest(path,o={}){return this.authRequest(`/rest/v1/${path}`,o);}async rpc(n,d={}){return this.rest(`rpc/${n}`,{method:"POST",body:JSON.stringify(d)});}
 async me(){if(!await this.ensureAccessToken())throw new Error("Nicht angemeldet");const ar=await fetch(`${this.baseUrl}/auth/v1/user`,{headers:this.headers({auth:true,json:false})}),au=await this.parse(ar),rows=await this.rest(`users?auth_user_id=eq.${encodeURIComponent(au.id)}&select=*`),p=rows?.[0];if(!p)throw new Error("Spielerprofil wurde noch nicht angelegt");return{...p,authId:au.id,emailConfirmedAt:au.email_confirmed_at||null,premiumUntil:p.premium_until?new Date(p.premium_until).getTime():0,premiumPlan:p.premium_plan||null,premiumAutoRenew:!!p.premium_auto_renew};}
 async accountOverview(){const user=await this.me();const companies=await this.rest(`companies?user_id=eq.${encodeURIComponent(user.id)}&select=*&order=slot_no.asc,created_at.asc`);let wallet={balance:0};try{const rows=await this.rest(`coin_wallets?user_id=eq.${encodeURIComponent(user.id)}&select=balance&limit=1`);if(rows?.[0])wallet={balance:Number(rows[0].balance||0)};}catch(error){console.warn("Coin-Wallet konnte nicht geladen werden",error);}return{success:true,user,companies:Array.isArray(companies)?companies:[],wallet};}
 async logout(){try{if(this.session?.access_token)await fetch(`${this.baseUrl}/auth/v1/logout`,{method:"POST",headers:this.headers({auth:true})});}finally{this.saveSession(null);}return{success:true};}async resendVerification(email){const r=await fetch(`${this.baseUrl}/auth/v1/resend`,{method:"POST",headers:this.headers(),body:JSON.stringify({type:"signup",email})});await this.parse(r);return{success:true};}async requestPasswordReset(email){const r=await fetch(`${this.baseUrl}/auth/v1/recover`,{method:"POST",headers:this.headers(),body:JSON.stringify({email})});await this.parse(r);return{success:true};}async resetPassword(_t,password){const r=await fetch(`${this.baseUrl}/auth/v1/user`,{method:"PUT",headers:this.headers({auth:true}),body:JSON.stringify({password})});await this.parse(r);return{success:true};}
 async updateProfile(d){const u=await this.me(),a={};if(d.countryCode!==undefined)a.country_code=d.countryCode;if(d.languageCode!==undefined)a.language_code=d.languageCode;if(d.displayName!==undefined)a.display_name=d.displayName;if(d.profileImageUrl!==undefined)a.profile_image_url=d.profileImageUrl;const r=await this.rest(`users?auth_user_id=eq.${encodeURIComponent(u.auth_user_id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(a)}),user=r?.[0]||null;if(user&&typeof window!=="undefined"){window.worldCurrentUser={...(window.worldCurrentUser||{}),...user};window.dispatchEvent(new CustomEvent("world:profile-updated",{detail:{user:window.worldCurrentUser}}));}return{success:true,user};}
 async getPremiumStatus(){const u=await this.me();return{success:true,premium:{plan:u.premiumPlan,until:u.premiumUntil,autoRenew:u.premiumAutoRenew,active:Number(u.premiumUntil||0)>Date.now()}};}
 async savePremiumStatus({plan=null,until=0,autoRenew=false}={}){const u=await this.me(),payload={premium_plan:plan||null,premium_until:Number(until)>0?new Date(Number(until)).toISOString():null,premium_auto_renew:!!autoRenew};const r=await this.rest(`users?auth_user_id=eq.${encodeURIComponent(u.auth_user_id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)}),row=r?.[0]||{};return{success:true,premium:{plan:row.premium_plan||null,until:row.premium_until?new Date(row.premium_until).getTime():0,autoRenew:!!row.premium_auto_renew}};}
 async ensureCompany(d={}){const r=await this.rpc("ensure_player_company",{p_name:d.name||null,p_industry:d.industry||null,p_company_type:d.companyType||d.type||null});return{success:true,company:Array.isArray(r)?r[0]:r};}async createBusiness(d={}){const r=await this.rpc("create_player_business",{p_name:d.name||null,p_industry:d.industry||null,p_company_type:d.companyType||d.type||null,p_slot_no:Number(d.slotNo)});return{success:true,company:Array.isArray(r)?r[0]:r};}
 async saveGameState(s){const r=await this.rpc("save_player_game_state",{p_state:s||{}});return{success:true,company:Array.isArray(r)?r[0]:r};}async saveBusinessState(id,s){const r=await this.rpc("save_player_business_state",{p_company_id:Number(id),p_state:s||{}});return{success:true,company:Array.isArray(r)?r[0]:r};}async updateBusinessSetup(id,p,b){const r=await this.rpc("update_player_business_setup",{p_company_id:Number(id),p_setup_phase:p,p_building_state:b||{}});return{success:true,company:Array.isArray(r)?r[0]:r};}
 async transferBusinessMoney(a,b,x){const r=await this.rpc("transfer_business_money",{p_from_company_id:Number(a),p_to_company_id:Number(b),p_amount:Number(x)});return{success:true,balances:Array.isArray(r)?r[0]:r};}async listInternalTransfers(){return this.rest(`business_internal_transfers?select=*&order=created_at.desc&limit=100`);}async listExpansionLoans(){return this.rest(`business_expansion_loans?select=*&order=created_at.desc`);}async takeExpansionLoan(companyId,offer){const r=await this.rpc("take_expansion_loan",{p_company_id:Number(companyId),p_amount:Number(offer.amount),p_annual_rate:Number(offer.annualRate),p_term_months:Number(offer.termMonths),p_monthly_payment:Number(offer.monthlyPayment)});return{success:true,loan:Array.isArray(r)?r[0]:r};}
 async listCoinOrders(){return this.rest("coin_market_orders?status=eq.open&select=*&order=price_per_coin.asc,created_at.asc");}async createCoinSellOrder(a,p){return{success:true,orderId:await this.rpc("create_coin_sell_order",{p_amount:Number(a),p_price_per_coin:Number(p)})};}async cancelCoinSellOrder(id){return{success:true,balance:await this.rpc("cancel_coin_sell_order",{p_order_id:Number(id)})};}async buyCoinOrder(id,a){const r=await this.rpc("buy_coin_market_order",{p_order_id:Number(id),p_amount:Number(a)});window.dispatchEvent(new CustomEvent("world:server-balances-changed",{detail:r}));return{success:true,trade:Array.isArray(r)?r[0]:r};}
}
