// ORVUNO – Echtgeld-Checkout über Braintree/PayPal.
// Private Braintree-Zugangsdaten liegen ausschließlich in Supabase Edge-Function-Secrets.
const DROPIN_CLIENT='https://js.braintreegateway.com/web/3.144.0/js/client.min.js';
const PAYPAL_V6='https://js.braintreegateway.com/web/3.144.0/js/paypal-checkout-v6.min.js';
const loaded=new Map();
const money=v=>Number(v||0).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
function api(){const a=window.worldAccounts?.authApi;if(!a)throw new Error('Zahlungssystem ist noch nicht bereit');return a;}
async function edge(action,data={}){const a=api(),token=await a.ensureAccessToken();if(!token)throw new Error('Bitte zuerst anmelden');const r=await fetch(`${a.baseUrl}/functions/v1/world-payments`,{method:'POST',headers:{apikey:a.publishableKey,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const b=await r.json().catch(()=>({}));if(!r.ok||b.success===false)throw new Error(b.error||b.message||`Zahlung fehlgeschlagen (${r.status})`);return b;}
function load(src){if(loaded.has(src))return loaded.get(src);const p=new Promise((resolve,reject)=>{const old=[...document.scripts].find(s=>s.src===src);if(old){if(window.braintree)return resolve(true);old.addEventListener('load',()=>resolve(true),{once:true});old.addEventListener('error',()=>reject(new Error('Braintree konnte nicht geladen werden')),{once:true});return;}const s=document.createElement('script');s.src=src;s.async=true;s.onload=()=>resolve(true);s.onerror=()=>reject(new Error('Braintree konnte nicht geladen werden'));document.head.append(s);});loaded.set(src,p);return p;}
async function sdk(){await load(DROPIN_CLIENT);await load(PAYPAL_V6);if(!window.braintree?.client||!window.braintree?.paypalCheckoutV6)throw new Error('Braintree PayPal SDK ist nicht verfügbar');return window.braintree;}
function close(){document.querySelector('[data-orvuno-payment-overlay]')?.remove();}
function overlay(label,price){close();const ov=document.createElement('div');ov.dataset.orvunoPaymentOverlay='1';Object.assign(ov.style,{position:'fixed',inset:'0',zIndex:99000,background:'rgba(0,0,0,.72)',display:'grid',placeItems:'center',padding:'18px'});const card=document.createElement('section');Object.assign(card.style,{width:'min(520px,94vw)',background:'#111827',color:'#fff',border:'1px solid #334155',borderRadius:'16px',padding:'20px',boxShadow:'0 24px 70px rgba(0,0,0,.55)'});const x=document.createElement('button');x.textContent='✕';Object.assign(x.style,{float:'right',padding:'5px 9px'});x.onclick=close;const h=document.createElement('h2');h.textContent='Sicher bezahlen';const p=document.createElement('p');p.innerHTML=`<b>${label}</b><br><span style="font-size:24px;font-weight:900">${money(price)} €</span>`;const status=document.createElement('div');status.dataset.paymentStatus='1';status.textContent='PayPal wird vorbereitet …';Object.assign(status.style,{margin:'12px 0',padding:'10px',borderRadius:'8px',background:'#0f172a'});const mount=document.createElement('div');mount.dataset.paymentMount='1';card.append(x,h,p,status,mount);ov.append(card);ov.onclick=e=>{if(e.target===ov)close();};document.body.append(ov);return{ov,card,status,mount};}
async function finish(sku,nonce,deviceData=null){const result=await edge('checkout',{sku,paymentMethodNonce:nonce,deviceData});window.dispatchEvent(new CustomEvent('world:server-balances-changed',{detail:result}));try{await window.worldAccounts?.gameStateSync?.refreshBalances?.();await window.worldAccounts?.premiumLifecycle?.refreshAccount?.(window.worldAccounts.authApi);}catch(e){console.warn('Zahlungsstatus konnte nicht sofort neu geladen werden',e);}return result;}
function assertCheckoutContext(sku){const guard=window.worldBusinessSwitchPaymentGuard;if(guard?.blocked?.())throw new Error('Während eines Betriebswechsels kann keine Zahlung gestartet werden');if(!guard?.consumePurchaseIntent?.(sku))throw new Error('Zahlung wurde blockiert: Bitte den gewünschten Kauf direkt über den Kaufbutton starten.');}
function explainStartError(error){const message=error?.message||String(error||'Unbekannter PayPal-Fehler');if(/Could not create PayPal order/i.test(message)&&location.protocol!=='https:')return `${message} Der PayPal-v6-Checkout benötigt eine HTTPS-Webadresse. Diese Seite läuft aktuell über ${location.origin}.`;return message;}
export async function beginBraintreePurchase({sku,label,priceEuro}={}){assertCheckoutContext(sku);if(!sku||!(Number(priceEuro)>0))throw new Error('Ungültiges Kaufprodukt');const ui=overlay(label||sku,priceEuro);try{const auth=await edge('client_token'),bt=await sdk(),client=await bt.client.create({authorization:auth.clientToken}),paypal=await bt.paypalCheckoutV6.create({client});await paypal.loadPayPalSDK();ui.status.textContent=auth.environment==='production'?'🔒 Live-Zahlung über PayPal':'🧪 Sandbox-Zahlung über PayPal';const button=document.createElement('paypal-button');button.setAttribute('type','pay');button.id=`orvuno-paypal-${Date.now()}`;ui.mount.append(button);const session=paypal.createOneTimePaymentSession({amount:Number(priceEuro).toFixed(2),currency:'EUR',intent:'capture',onApprove:async data=>{try{ui.status.textContent='PayPal bestätigt – Zahlungsfreigabe wird übernommen …';console.info('ORVUNO PayPal onApprove',{orderId:data?.orderId,payerId:data?.payerId});const payload=await paypal.tokenizePayment({payerID:data?.payerId||data?.payerID,orderID:data?.orderId||data?.orderID});if(!payload?.nonce)throw new Error('PayPal hat keine Zahlungsfreigabe zurückgegeben');ui.status.textContent='Zahlung wird serverseitig bestätigt …';console.info('ORVUNO PayPal tokenisiert; starte Server-Checkout');const result=await finish(sku,payload.nonce,payload.deviceData||null);ui.status.textContent='✅ Zahlung erfolgreich. Kauf wurde gutgeschrieben.';setTimeout(close,1200);return result;}catch(error){const message=error?.message||String(error||'Unbekannter Zahlungsfehler');ui.status.textContent=`❌ ${message}`;console.error('PayPal-Zahlungsbestätigung fehlgeschlagen',{message,error,data});throw error;}}});button.addEventListener('click',async()=>{try{await session.start();}catch(error){const message=explainStartError(error);ui.status.textContent=`❌ ${message}`;console.error('PayPal-Zahlungsstart fehlgeschlagen',{message,error,origin:location.origin,protocol:location.protocol});}});return{success:true,opened:true,environment:auth.environment};}catch(error){ui.status.textContent=`❌ ${error.message||error}`;throw error;}}
export function beginCoinPurchase(request={}){return beginBraintreePurchase({sku:request.packageId,label:`${Number(request.coins||0).toLocaleString('de-DE')} Coins`,priceEuro:request.priceEuro});}
export function beginPremiumPurchase(plan={}){return beginBraintreePurchase({sku:plan.id||plan.planId,label:plan.label||'Premium',priceEuro:plan.priceEuro});}
function install(){
  // Käufe werden ausschließlich von expliziten Kaufbuttons gestartet. Ein generisches
  // "plan-selected"-Event darf niemals automatisch einen Echtgeld-Checkout öffnen.
  window.worldPaymentProviders??={};
  window.worldPaymentProviders.braintree={id:'braintree',label:'PayPal / Braintree',beginCoinPurchase,beginPremiumPurchase,begin:beginBraintreePurchase};
  window.worldPaymentCheckout=window.worldPaymentProviders.braintree;
}
if(typeof window!=='undefined')install();
