// WorldProject – Markenstärke und Reputation.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureBrand(c={}){c.brandState??={awareness:10,qualityImage:50,priceImage:50,serviceImage:50,trust:50,regions:{},campaigns:[],incidents:[],history:[]};return c.brandState;}
export function brandScore(c){const b=ensureBrand(c);return b.awareness*.2+b.qualityImage*.25+b.serviceImage*.2+b.trust*.25+(100-Math.abs(50-b.priceImage))*.1;}
export function runMarketingCampaign(c,{budget=0,region='central',focus='awareness',days=14}={}){const b=ensureBrand(c),cost=Math.max(0,n(budget));if(n(c.money)<cost)throw new Error('Budget reicht nicht');c.money-=cost;const impact=Math.log10(1+cost)*2.5,cam={id:`campaign-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,budget:cost,region,focus,days:n(days),impact,startedAt:Date.now(),status:'active'};b.campaigns.push(cam);b.regions[region]??={awareness:5,trust:50};b.regions[region].awareness=clamp(n(b.regions[region].awareness)+impact,0,100);if(focus==='awareness')b.awareness=clamp(b.awareness+impact*.5,0,100);if(focus==='quality')b.qualityImage=clamp(b.qualityImage+impact*.3,0,100);if(focus==='service')b.serviceImage=clamp(b.serviceImage+impact*.3,0,100);return cam;}
export function recordBrandExperience(c,{quality=1,onTime=true,service=1,priceFairness=1,region='central'}={}){const b=ensureBrand(c);b.qualityImage=clamp(b.qualityImage+(n(quality,1)-.8)*4,0,100);b.serviceImage=clamp(b.serviceImage+(n(service,1)-.8)*3+(onTime?1:-3),0,100);b.trust=clamp(b.trust+(onTime?1:-4)+(n(quality,1)>=.8?1:-3),0,100);b.priceImage=clamp(b.priceImage+(n(priceFairness,1)-.8)*2,0,100);b.awareness=clamp(b.awareness+.05,0,100);b.regions[region]??={awareness:5,trust:50};b.regions[region].trust=clamp(n(b.regions[region].trust,50)+(onTime?1:-2),0,100);b.history.push({at:Date.now(),score:brandScore(c),quality:b.qualityImage,service:b.serviceImage,trust:b.trust});if(b.history.length>365)b.history.shift();return b;}
export function brandIncident(c,{severity=.3,kind='quality',region='central',description='Vorfall'}={}){const b=ensureBrand(c),s=clamp(n(severity,.3),0,1),loss=s*15;b.trust=clamp(b.trust-loss,0,100);if(kind==='quality')b.qualityImage=clamp(b.qualityImage-loss*1.2,0,100);if(kind==='service')b.serviceImage=clamp(b.serviceImage-loss,0,100);b.incidents.push({id:`brand-${Date.now()}`,kind,severity:s,region,description,at:Date.now()});return b;}
export function brandDemandMultiplier(c,region='central'){const b=ensureBrand(c),regional=b.regions[region]||{awareness:b.awareness,trust:b.trust};return clamp(.5+brandScore(c)/100*.7+n(regional.awareness)/500+n(regional.trust)/600,.45,1.8);}
if(typeof window!=='undefined')window.worldBrandReputation={ensure:ensureBrand,score:brandScore,campaign:runMarketingCampaign,experience:recordBrandExperience,incident:brandIncident,demandMultiplier:brandDemandMultiplier};
