// Gebaeude-, Bau- und Erweiterungssystem fuer alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureBuildings(c={}){c.buildings??={plots:[],projects:[],assets:[],utilities:{powerKw:0,waterLph:0,wasteCapacity:0}};return c.buildings;}
export function addPlot(c,{id,region='default',areaM2=1000,purchasePrice=0,rentMonthly=0,status='owned'}={}){const b=ensureBuildings(c),row={id:id||`plot-${Date.now()}`,region,areaM2:Math.max(0,n(areaM2)),purchasePrice:Math.max(0,n(purchasePrice)),rentMonthly:Math.max(0,n(rentMonthly)),status};b.plots.push(row);return row;}
export function startBuildingProject(c,{plotId,type='production',areaM2=500,costPerM2=800,durationDays=60,utilityDemand={}}={}){const b=ensureBuildings(c),plot=b.plots.find(x=>x.id===plotId);if(!plot)throw new Error('Grundstueck fehlt');const area=Math.max(1,n(areaM2)),cost=area*Math.max(0,n(costPerM2));if(n(c.money)<cost)throw new Error('Nicht genug Kapital');c.money-=cost;const row={id:`build-${Date.now()}`,plotId,type,areaM2:area,cost,durationDays:Math.max(1,n(durationDays)),startedAt:Date.now(),endsAt:Date.now()+Math.max(1,n(durationDays))*86400000,status:'building',progress:0,utilityDemand};b.projects.push(row);return row;}
export function buildingProgress(project,{now=Date.now()}={}){if(project.status==='done')return 1;const span=Math.max(1,project.endsAt-project.startedAt);project.progress=Math.max(0,Math.min(1,(now-project.startedAt)/span));if(project.progress>=1)project.status='ready';return project.progress;}
export function finishBuildingProject(c,id,{now=Date.now(),force=false}={}){const b=ensureBuildings(c),p=b.projects.find(x=>x.id===id);if(!p)throw new Error('Bauprojekt fehlt');buildingProgress(p,{now});if(!force&&p.status!=='ready')throw new Error('Bauprojekt noch nicht fertig');p.status='done';p.completedAt=now;const asset={id:`asset-${p.id}`,plotId:p.plotId,type:p.type,areaM2:p.areaM2,capacityMultiplier:1+p.areaM2/5000,status:'active',createdAt:now};b.assets.push(asset);return asset;}
export function upgradeUtilities(c,{powerKw=0,waterLph=0,wasteCapacity=0,cost=0}={}){const b=ensureBuildings(c);if(n(c.money)<n(cost))throw new Error('Nicht genug Kapital');c.money-=n(cost);b.utilities.powerKw+=Math.max(0,n(powerKw));b.utilities.waterLph+=Math.max(0,n(waterLph));b.utilities.wasteCapacity+=Math.max(0,n(wasteCapacity));return b.utilities;}
export function buildingCapacity(c,type){const b=ensureBuildings(c);return b.assets.filter(x=>x.status==='active'&&x.type===type).reduce((s,x)=>s+n(x.capacityMultiplier,1),0);}
export function buildingKpis(c){const b=ensureBuildings(c);return{plots:b.plots.length,projects:b.projects.filter(x=>x.status!=='done').length,assets:b.assets.length,productionCapacity:buildingCapacity(c,'production'),warehouseCapacity:buildingCapacity(c,'warehouse'),utilities:{...b.utilities}};}
