// WorldProject - Betriebsauswahl, Langzeit-Expansion und beliebig viele Betriebe
import { IndustryGroups, IndustryProfiles } from "./IndustryCatalog.js";
import { industryChainSummary, chainSummaryText } from "./IndustryChainPresentation.js";
import { UpgradeTracks, getUpgradeState, upgradeCost, upgradeBonus, applyUpgrade } from "./BusinessExpansionSystem.js";
import { LocationClasses, propertyOffer } from "./BusinessLocationSystem.js";

const SetupPhaseLabels={
 empty_building:"Leeres Betriebsgebäude",
 setup:"Einrichtung läuft",
 setup_in_progress:"Einrichtung läuft",
 ready:"Betriebsbereit",
 active:"In Betrieb",
 construction:"Bau läuft",
 installing:"Montage läuft"
};

export class BusinessPortfolioDialog {
 constructor({portfolio,parent=document.body}={}){this.portfolio=portfolio;this.parent=parent;this.overlay=null;}
 el(tag,text=null){const e=document.createElement(tag);if(text!==null)e.textContent=text;return e;}
 input(value=""){const i=this.el("input");i.value=value;Object.assign(i.style,{width:"100%",boxSizing:"border-box",padding:"10px 11px",margin:"4px 0",borderRadius:"8px",border:"1px solid #bbb"});return i;}
 button(text,fn){const b=this.el("button",text);Object.assign(b.style,{padding:"8px 10px",margin:"4px",border:0,borderRadius:"7px",fontWeight:"700",cursor:"pointer"});b.addEventListener("click",fn);return b;}
 select(values){const s=this.el("select");Object.assign(s.style,{width:"100%",padding:"9px",margin:"4px 0",borderRadius:"8px"});for(const v of values){const o=this.el("option",typeof v==="string"?v:(v.label||v.id));o.value=typeof v==="string"?v:v.id;s.append(o);}return s;}
 money(v){return Number(v||0).toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
 phaseLabel(v){return SetupPhaseLabels[v]||String(v||"Unbekannt").replaceAll("_"," ");}
 companyLabel(c){const key=c?.company_type||c?.industry||"";return IndustryProfiles[key]?.label||key||"-";}
 async open(){if(this.overlay)return;const overlay=this.el("div");Object.assign(overlay.style,{position:"fixed",inset:0,zIndex:20500,background:"rgba(0,0,0,.75)",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px"});const panel=this.el("div");Object.assign(panel.style,{width:"min(1050px,96vw)",maxHeight:"92vh",overflow:"auto",background:"#fff",color:"#111",borderRadius:"14px",padding:"22px",fontFamily:"Arial,sans-serif"});overlay.append(panel);this.parent.append(overlay);this.overlay=overlay;await this.render(panel);}
 close(){this.overlay?.remove();this.overlay=null;}
 industryCatalog(parent,onSelect){
  const groups=Object.entries(IndustryGroups).filter(([,types])=>Array.isArray(types)&&types.length);const all=[...new Set(groups.flatMap(([,types])=>types))];let selected=all[0]||"";
  const wrap=this.el("div");Object.assign(wrap.style,{border:"1px solid #d8d8d8",borderRadius:"12px",padding:"12px",margin:"10px 0",background:"#fafafa"});
  const title=this.el("div",`Gewerbekatalog · ${all.length} Betriebe`);Object.assign(title.style,{fontWeight:"800",fontSize:"16px",marginBottom:"8px"});
  const search=this.input("");search.placeholder="Gewerbe oder Ware suchen, z. B. Mühle, Malz, Flaschen …";
  const tabs=this.el("div");Object.assign(tabs.style,{display:"flex",flexWrap:"wrap",gap:"5px",margin:"8px 0"});
  const grid=this.el("div");Object.assign(grid.style,{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(210px,1fr))",gap:"8px",maxHeight:"360px",overflow:"auto",padding:"4px"});
  const detail=this.el("div");Object.assign(detail.style,{marginTop:"10px",padding:"10px",borderRadius:"8px",background:"#eef5ff"});
  let activeGroup="Alle";
  const render=()=>{grid.innerHTML="";const q=search.value.trim().toLocaleLowerCase("de");const visible=all.filter(type=>{const inGroup=activeGroup==="Alle"||IndustryGroups[activeGroup]?.includes(type);const profile=IndustryProfiles[type]||{},chain=chainSummaryText(type);const hay=`${type} ${profile.label||""} ${profile.branchKey||""} ${chain}`.toLocaleLowerCase("de");return inGroup&&(!q||hay.includes(q));});for(const type of visible){const profile=IndustryProfiles[type]||{},chain=industryChainSummary(type);const card=this.el("button");card.type="button";Object.assign(card.style,{textAlign:"left",padding:"10px",border:selected===type?"2px solid #1d63d8":"1px solid #ccc",borderRadius:"9px",background:selected===type?"#eaf2ff":"#fff",cursor:"pointer"});const strong=this.el("strong",profile.label||type),meta=this.el("div",`${(profile.requiredEquipment||[]).length} Pflichtmaschinen · ${(profile.products||[]).length} Produkte`),flow=this.el("div",chainSummaryText(type));Object.assign(meta.style,{fontSize:"12px",color:"#555",marginTop:"4px"});Object.assign(flow.style,{fontSize:"11px",color:"#345",marginTop:"5px",lineHeight:"1.3"});card.append(strong,meta,flow);card.onclick=()=>{selected=type;onSelect(type);render();};grid.append(card);}if(!visible.length){const empty=this.el("div","Kein Gewerbe für diese Suche gefunden.");Object.assign(empty.style,{padding:"12px",color:"#666"});grid.append(empty);}const p=IndustryProfiles[selected]||{},s=industryChainSummary(selected);detail.innerHTML="";if(selected){detail.append(this.el("strong",`Ausgewählt: ${p.label||selected}`),this.el("div",chainSummaryText(selected)),this.el("div",`Mögliche Vorlieferanten: ${s.upstream.join(', ')||'KI/Grundstoffmarkt'} · mögliche Abnehmer: ${s.downstream.join(', ')||'Endkunden/Handel'}`));}else detail.textContent="Bitte Gewerbe auswählen";};
  const addTab=(name)=>{const b=this.button(name,()=>{activeGroup=name;for(const x of tabs.querySelectorAll("button"))x.style.background=x.dataset.group===name?"#dbe9ff":"#eee";render();});b.dataset.group=name;b.style.background=name==="Alle"?"#dbe9ff":"#eee";tabs.append(b);};addTab("Alle");for(const [name] of groups)addTab(name);search.addEventListener("input",render);wrap.append(title,search,tabs,grid,detail);parent.append(wrap);if(selected)onSelect(selected);render();return()=>selected;
 }
 async render(panel){
  panel.innerHTML="";const overview=await this.portfolio.refresh(),companies=overview.companies||[];const head=this.el("div");Object.assign(head.style,{display:"flex",justifyContent:"space-between",alignItems:"center"});head.append(this.el("h2","🏢 Meine Betriebe"),this.button("✕",()=>this.close()));panel.append(head,this.el("div",`${companies.length} Betriebe · keine feste Obergrenze`));
  for(const c of companies){const card=this.el("div");Object.assign(card.style,{border:"1px solid #ddd",borderRadius:"10px",padding:"12px",margin:"10px 0"});const trade=Object.values(c.game_state?.tradeInventory||{}).reduce((a,b)=>a+Number(b||0),0),finished=Object.values(c.game_state?.finishedGoods||{}).reduce((a,b)=>a+Number(b||0),0),active=String((this.portfolio.activeCompany||window.worldPlayerCompany)?.serverCompanyId||"")===String(c.id),property=c.game_state?.property||{},locationLabel=LocationClasses[property.locationClass]?.label||null,modeLabel=property.mode==="buy"?"Kauf":property.mode==="rent"?"Miete":null;card.append(this.el("strong",`${active?"✅ ":""}Betrieb ${c.slot_no}: ${c.name}`),this.el("div",`${this.companyLabel(c)} · ${this.money(c.money)} · Phase: ${this.phaseLabel(c.setup_phase)}`));if(locationLabel||modeLabel)card.append(this.el("div",`${locationLabel||"Standort unbekannt"}${modeLabel?` · ${modeLabel}`:""}${Number(property.monthlyRent||0)>0?` · Monatsmiete ${this.money(property.monthlyRent)}`:""}`));card.append(this.el("div",chainSummaryText(c.company_type||c.industry)),this.el("div",`Fertigware: ${finished} · Handelsbestand: ${trade}`),this.button(active?"Aktiver Betrieb":"Diesen Betrieb öffnen",()=>{if(active)return;this.portfolio.activate(c,window.worldPlayerCompany||{});this.close();}));panel.append(card);}
  if(companies.length){const active=this.portfolio.activeCompany||window.worldPlayerCompany||{};const u=getUpgradeState(active),upgradeBox=this.el("div");Object.assign(upgradeBox.style,{borderTop:"2px solid #ddd",marginTop:"18px",paddingTop:"16px"});upgradeBox.append(this.el("h3","Betrieb ausbauen"),this.el("div","Viele kleine Ausbaustufen verbessern den Betrieb langfristig. Werte sind bis zum Balancing vorläufig."));for(const [key,cfg] of Object.entries(UpgradeTracks)){const lvl=u[key],row=this.el("div");Object.assign(row.style,{padding:"7px",margin:"5px 0",background:"#f5f5f5",borderRadius:"7px"});row.append(this.el("span",`${cfg.label}: Stufe ${lvl}/${cfg.maxLevel} · Bonus ${(upgradeBonus(key,lvl)*100).toFixed(2)} % · nächste Stufe ${this.money(upgradeCost(key,lvl))}`),this.button("Ausbauen",()=>{try{applyUpgrade(active,key);this.render(panel);}catch(e){alert(e.message);}}));upgradeBox.append(row);}panel.append(upgradeBox);}
  const box=this.el("div");Object.assign(box.style,{borderTop:"2px solid #ddd",marginTop:"18px",paddingTop:"16px"});box.append(this.el("h3",companies.length?"Weiteren Betrieb gründen":"Ersten Betrieb gründen"));
  if(companies.length){const testUnlocked=companies.length===1&&window.worldSecondBusinessTestUnlock?.active;const st=this.portfolio.getExpansionStatus(this.portfolio.activeCompany||window.worldPlayerCompany),r=st.requirements;if(testUnlocked){const note=this.el("div","🧪 Entwicklungsfreigabe aktiv: Der zweite Betrieb kann für den Mehrbetriebstest ohne Expansionsvoraussetzungen gegründet werden.");Object.assign(note.style,{padding:"9px",background:"#fff4cc",borderRadius:"8px",marginBottom:"8px"});box.append(note);}else{box.append(this.el("div",`Nächste Expansion: Gründung ${this.money(r.creationCost)}, notwendige Reserve ${this.money(r.requiredCashReserve)}, Mindest-Unternehmenswert ${this.money(r.requiredNetWorth)}, Managementbedarf ${r.requiredManagement}.`));if(!st.allowed)box.append(this.el("div",`Noch gesperrt: ${st.reasons.join(" · ")}`));}}
  const name=this.input("Neuer Betrieb");let selectedType="";this.industryCatalog(box,type=>selectedType=type);const location=this.select(Object.entries(LocationClasses).map(([id,cfg])=>({id,label:cfg?.label||id}))),mode=this.select([{id:"rent",label:"Mieten"},{id:"buy",label:"Kaufen"}]),offer=this.el("div");const updateOffer=()=>{const x=propertyOffer(location.value,mode.value,1);offer.textContent=`Standort: ${LocationClasses[location.value].label} · ${mode.value==="buy"?"Kauf":"Miete"} · Start ${this.money(x.upfront)}${x.monthly?` · monatlich ${this.money(x.monthly)}`:""}`;};location.onchange=mode.onchange=updateOffer;updateOffer();box.append(name,location,mode,offer,this.button("Ausgewählten Betrieb anlegen",async()=>{try{if(!selectedType)throw new Error("Bitte zuerst ein Gewerbe auswählen");const industry=Object.entries(IndustryGroups).find(([,types])=>types.includes(selectedType))?.[0]||"Sonstige";await this.portfolio.createBusiness({name:name.value,industry,companyType:selectedType,locationClass:location.value,propertyMode:mode.value});await this.render(panel);}catch(e){alert(e.message);}}));panel.append(box);
  if(companies.length>1){const transfer=this.el("div");Object.assign(transfer.style,{borderTop:"2px solid #ddd",marginTop:"18px",paddingTop:"16px"});transfer.append(this.el("h3","Spielgeld zwischen eigenen Betrieben übertragen"));const labels=companies.map(c=>`${c.slot_no} · ${c.name}`),from=this.select(labels),to=this.select(labels),amount=this.input("10000"),byLabel=label=>companies.find(c=>label.startsWith(`${c.slot_no} ·`));transfer.append(from,to,amount,this.button("Übertragen",async()=>{try{const a=byLabel(from.value),b=byLabel(to.value);if(!a||!b||a.id===b.id)throw new Error("Bitte zwei verschiedene Betriebe wählen");await this.portfolio.transferMoney(a.id,b.id,Number(amount.value));await this.render(panel);}catch(e){alert(e.message);}}));panel.append(transfer);
   const goods=this.el("div");Object.assign(goods.style,{borderTop:"2px solid #ddd",marginTop:"18px",paddingTop:"16px"});goods.append(this.el("h3","Waren zwischen eigenen Betrieben verschieben"),this.el("div","Eigene Betriebe können sich damit direkt entlang der Produktionskette beliefern."));const source=this.select(labels),target=this.select(labels),product=this.select([]),qty=this.input("100");const refreshProducts=()=>{product.innerHTML="";const c=byLabel(source.value),state=c?.game_state||{},all={...(state.finishedGoods||{}),...(state.tradeInventory||{})};for(const [id,n] of Object.entries(all).filter(([,n])=>Number(n)>0)){const o=this.el("option",`${id} · Bestand ${n}`);o.value=id;product.append(o);}};source.onchange=refreshProducts;refreshProducts();goods.append(source,target,product,qty,this.button("Ware übertragen",async()=>{try{const a=byLabel(source.value),b=byLabel(target.value);if(!a||!b||a.id===b.id)throw new Error("Bitte zwei verschiedene Betriebe wählen");if(!product.value)throw new Error("Im Quellbetrieb ist keine Ware verfügbar");await this.portfolio.transferGoods(a.id,b.id,{product:product.value,quantity:Number(qty.value)});await this.render(panel);}catch(e){alert(e.message);}}));panel.append(goods);}
 }
}
