// WorldProject - langfristige, zeitbasierte Betriebsausbaustufen
// Ein einziges Ausbausystem fuer die operativ wirksamen Sparten.
// Bezahlte Ausbauten wirken NIE sofort. Erst nach Ablauf von Umbau/Schulung/Abnahme
// wird die neue Stufe in company.upgrades aktiviert. Freunde koennen lange Projekte begrenzt beschleunigen.

export const UpgradeTracks={
 production:{label:"Produktionsleistung",baseCost:6500,growth:1.075,effectPerLevel:.0125,maxLevel:100,baseHours:4,durationGrowth:1.10,maxHours:504,workLabels:["Maschinen werden umgebaut","Produktionsablauf wird neu abgestimmt","Personal wird an der neuen Linie geschult","Testlauf und Feinabstimmung laufen"]},
 storage:{label:"Lagerkapazität",baseCost:4200,growth:1.07,effectPerLevel:.015,maxLevel:100,baseHours:3,durationGrowth:1.095,maxHours:504,workLabels:["Lagertechnik wird erweitert","Regale und Wege werden angepasst","Lagerplätze werden neu organisiert","Abnahme der Lagererweiterung läuft"]},
 efficiency:{label:"Betriebseffizienz",baseCost:7200,growth:1.08,effectPerLevel:.006,maxLevel:100,baseHours:5,durationGrowth:1.105,maxHours:504,workLabels:["Arbeitsabläufe werden analysiert","Maschinenparameter werden optimiert","Personal wird auf neue Prozesse geschult","Effizienztest und Abnahme laufen"]},
 quality:{label:"Qualität",baseCost:8000,growth:1.08,effectPerLevel:.004,maxLevel:100,baseHours:5.5,durationGrowth:1.108,maxHours:504,workLabels:["Qualitätssicherung wird erweitert","Prüfabläufe werden angepasst","Mitarbeiter werden nachgeschult","Qualitätsprüfung und Freigabe laufen"]},
 logistics:{label:"Logistik",baseCost:5500,growth:1.075,effectPerLevel:.0075,maxLevel:100,baseHours:4.5,durationGrowth:1.102,maxHours:504,workLabels:["Touren- und Ladeprozesse werden überarbeitet","Fuhrparkabläufe werden abgestimmt","Fahrer und Disposition werden geschult","Logistiktest und Abnahme laufen"]},
 administration:{label:"Verwaltung",baseCost:6000,growth:1.08,effectPerLevel:.0075,maxLevel:100,baseHours:4,durationGrowth:1.10,maxHours:504,workLabels:["Verwaltungsabläufe werden analysiert","Software und Prozesse werden angepasst","Büropersonal wird geschult","Systemtest und Freigabe laufen"]}
};

const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const nowMs=v=>v instanceof Date?v.getTime():Number.isFinite(Number(v))?Number(v):Date.now();

export class BusinessUpgradeSystem{
 constructor({tracks=UpgradeTracks,friendReduction=.04,maxFriendReduction=.32}={}){this.tracks=tracks;this.friendReduction=friendReduction;this.maxFriendReduction=maxFriendReduction;}
 ensure(company){company.upgrades=company.upgrades||{};company.upgradeJobs=Array.isArray(company.upgradeJobs)?company.upgradeJobs:[];company.upgradeHistory=Array.isArray(company.upgradeHistory)?company.upgradeHistory:[];return company.upgrades;}
 level(company,track){return Number(this.ensure(company)[track]||0);}
 activeJobs(company){this.ensure(company);return company.upgradeJobs.filter(j=>j.status==='running');}
 activeJob(company,track){return this.activeJobs(company).find(j=>j.track===track)||null;}
 durationHours(track,nextLevel){const c=this.tracks[track];if(!c)throw new Error("Unbekannter Ausbauzweig");return Math.min(c.maxHours||504,Math.max(.25,(c.baseHours||1)*Math.pow(c.durationGrowth||1.1,Math.max(0,nextLevel-1))));}
 maxHelpers(nextLevel){return clamp(2+Math.floor(Math.max(1,nextLevel)/10),2,8);}
 quote(company,track){const c=this.tracks[track];if(!c)throw new Error("Unbekannter Ausbauzweig");const current=this.level(company,track);if(current>=Number(c.maxLevel||100))return{track,label:c.label,nextLevel:current,cost:null,effectTotal:c.effectPerLevel*current,effectGain:0,durationHours:0,durationMs:0,maxHelpers:0,maxed:true,activeJob:this.activeJob(company,track)};const next=current+1,hours=this.durationHours(track,next),active=this.activeJob(company,track);return{track,label:c.label,nextLevel:next,cost:Math.round(c.baseCost*Math.pow(c.growth,next-1)),effectTotal:c.effectPerLevel*next,effectGain:c.effectPerLevel,durationHours:hours,durationMs:Math.round(hours*3600000),maxHelpers:this.maxHelpers(next),maxed:false,activeJob:active};}
 startUpgrade(company,track,{now=Date.now()}={}){this.ensure(company);this.process(company,now);const existing=this.activeJob(company,track);if(existing)throw new Error(`${this.tracks[track]?.label||track} wird bereits ausgebaut`);const q=this.quote(company,track);if(q.maxed)throw new Error("Maximale Ausbaustufe erreicht");if(Number(company.money||0)<q.cost)throw new Error("Nicht genug Betriebsgeld");company.money-=q.cost;const start=nowMs(now),finish=start+q.durationMs;const job={id:`upgrade-${track}-${start}-${Math.random().toString(36).slice(2,8)}`,track,label:q.label,targetLevel:q.nextLevel,cost:q.cost,effectGain:q.effectGain,effectTotal:q.effectTotal,status:'running',startedAt:start,baseFinishAt:finish,finishAt:finish,baseDurationMs:q.durationMs,helpers:[],maxHelpers:q.maxHelpers,friendReduction:0,workLabels:[...(this.tracks[track].workLabels||[])],completedAt:null};company.upgradeJobs.push(job);return{success:true,pending:true,...q,job};}
 upgrade(company,track,options={}){return this.startUpgrade(company,track,options);}
 applyFriendHelp(company,jobId,{friendId,friendName=null,now=Date.now()}={}){this.ensure(company);this.process(company,now);const job=company.upgradeJobs.find(j=>j.id===jobId);if(!job||job.status!=='running')throw new Error("Ausbauauftrag ist nicht aktiv");const id=String(friendId||'').trim();if(!id)throw new Error("Freund fehlt");if(job.helpers.some(h=>h.friendId===id))throw new Error("Dieser Freund hat bei diesem Ausbau bereits geholfen");if(job.helpers.length>=job.maxHelpers)throw new Error("Maximale Freundeshilfe für diesen Ausbau erreicht");const currentReduction=job.friendReduction||0,remainingReduction=Math.max(0,this.maxFriendReduction-currentReduction),applied=Math.min(this.friendReduction,remainingReduction);if(applied<=0)throw new Error("Maximale Zeitverkürzung bereits erreicht");const cut=Math.round(job.baseDurationMs*applied);job.friendReduction=currentReduction+applied;job.finishAt=Math.max(nowMs(now),job.finishAt-cut);job.helpers.push({friendId:id,friendName:String(friendName||id),helpedAt:nowMs(now),reductionMs:cut,reductionRate:applied});return{success:true,job,reductionMs:cut,reductionRate:applied,remainingMs:Math.max(0,job.finishAt-nowMs(now))};}
 phase(job,now=Date.now()){if(!job)return null;if(job.status==='completed')return 'Ausbau abgeschlossen';const labels=job.workLabels||[];if(!labels.length)return 'Ausbauarbeiten laufen';const elapsed=Math.max(0,nowMs(now)-job.startedAt),duration=Math.max(1,job.finishAt-job.startedAt),ratio=clamp(elapsed/duration,0,.9999);return labels[Math.min(labels.length-1,Math.floor(ratio*labels.length))];}
 progress(job,now=Date.now()){if(!job)return 0;if(job.status==='completed')return 100;const duration=Math.max(1,job.finishAt-job.startedAt);return clamp(Math.round((nowMs(now)-job.startedAt)/duration*100),0,99);}
 process(company,now=Date.now()){this.ensure(company);const ts=nowMs(now),completed=[];for(const job of company.upgradeJobs){if(job.status!=='running'||ts<job.finishAt)continue;job.status='completed';job.completedAt=ts;this.ensure(company)[job.track]=Math.max(this.level(company,job.track),job.targetLevel);company.upgradeHistory.push({...job,helpers:[...(job.helpers||[])]});completed.push(job);}return completed;}
 status(company,track,now=Date.now()){this.process(company,now);const job=this.activeJob(company,track),q=this.quote(company,track);return{track,label:q.label,level:this.level(company,track),modifier:this.modifier(company,track),active:!!job,job,phase:job?this.phase(job,now):null,progress:job?this.progress(job,now):100,remainingMs:job?Math.max(0,job.finishAt-nowMs(now)):0,next:q};}
 modifier(company,track,now=Date.now()){this.process(company,now);const c=this.tracks[track];return c?1+this.level(company,track)*c.effectPerLevel:1;}
}

export function runBusinessUpgradeTest(){const start=1_000_000,c={money:100000},u=new BusinessUpgradeSystem(),a=u.upgrade(c,"production",{now:start});if(u.level(c,"production")!==0||u.modifier(c,"production",start)!==1)throw new Error("Ausbau wirkt fälschlich sofort");const before=a.job.finishAt,help=u.applyFriendHelp(c,a.job.id,{friendId:'friend-1',friendName:'Anna',now:start+1000});if(!(help.job.finishAt<before))throw new Error("Freundeshilfe verkürzt Ausbau nicht");u.process(c,a.job.finishAt);if(u.level(c,"production")!==1||u.modifier(c,"production",a.job.finishAt)<=1)throw new Error("Fertiger Ausbau wird nicht aktiviert");const b=u.quote(c,"production");if(b.cost<=a.cost||b.durationHours<=a.durationHours)throw new Error("Höhere Ausbaustufe wird nicht teurer/länger");for(const track of ['storage','efficiency','quality','logistics','administration'])if(!u.quote(c,track)?.label)throw new Error(`Ausbauzweig fehlt: ${track}`);console.log("🏭 ZEITBASIERTER BETRIEBSAUSBAU ERFOLGREICH");return true;}
