// WorldProject – Insolvenz, Sanierung und Restrukturierung.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureRestructuring(c={}){c.restructuring??={status:'healthy',cases:[],plans:[],creditors:[]};return c.restructuring;}
export function solvencyStatus(c){const r=ensureRestructuring(c),cash=n(c.money),payables=(c.finance?.payables||[]).filter(x=>x.status==='open').reduce((s,x)=>s+n(x.amount),0),debt=(c.financing?.loans||[]).reduce((s,x)=>s+n(x.outstanding),0),assets=(c.buildingState?.equipment||[]).reduce((s,x)=>s+n(x.purchasePrice||x.price)*.5,0)+Object.values(c.inventoryValue||{}).reduce((s,x)=>s+n(x),0),liquidityRatio=payables?Math.max(0,cash)/payables:Infinity,netPosition=cash+assets-payables-debt,status=cash<0&&liquidityRatio<.5?'distressed':netPosition<0?'warning':'healthy';r.status=status;return{status,cash,payables,debt,assets,liquidityRatio,netPosition};}
export function openRestructuringCase(c,{reason='liquidity'}={}){const r=ensureRestructuring(c),s=solvencyStatus(c);if(s.status==='healthy')throw new Error('Keine Restrukturierung erforderlich');const row={id:`restructure-${Date.now()}`,reason,status:'open',openedAt:Date.now(),snapshot:s,actions:[]};r.cases.push(row);r.status='restructuring';return row;}
export function proposeTurnaroundPlan(c,caseId,{costCut=.15,assetSales=0,newEquity=0,creditorHaircut=0,months=12}={}){const r=ensureRestructuring(c),x=r.cases.find(a=>a.id===caseId);if(!x)throw new Error('Sanierungsfall fehlt');const plan={id:`plan-${Date.now()}`,caseId,costCut:Math.max(0,n(costCut)),assetSales:Math.max(0,n(assetSales)),newEquity:Math.max(0,n(newEquity)),creditorHaircut:Math.max(0,Math.min(.8,n(creditorHaircut))),months:Math.max(1,n(months)),status:'proposed',createdAt:Date.now()};r.plans.push(plan);return plan;}
export function executeTurnaroundPlan(c,planId){const r=ensureRestructuring(c),p=r.plans.find(x=>x.id===planId);if(!p)throw new Error('Sanierungsplan fehlt');c.money=n(c.money)+p.assetSales+p.newEquity;if(c.monthlyCosts){for(const k of Object.keys(c.monthlyCosts))if(k!=='total')c.monthlyCosts[k]=n(c.monthlyCosts[k])*(1-p.costCut);c.monthlyCosts.total=Object.entries(c.monthlyCosts).filter(([k])=>k!=='total').reduce((s,[,v])=>s+n(v),0);}for(const x of c.finance?.payables||[])if(x.status==='open')x.amount=n(x.amount)*(1-p.creditorHaircut);p.status='active';p.startedAt=Date.now();r.status='restructuring';return{success:true,plan:p,status:solvencyStatus(c)};}
export function closeRestructuringCase(c,caseId){const r=ensureRestructuring(c),x=r.cases.find(a=>a.id===caseId);if(!x)throw new Error('Fall fehlt');const s=solvencyStatus(c);if(s.status!=='healthy')throw new Error('Unternehmen noch nicht saniert');x.status='closed';x.closedAt=Date.now();r.status='healthy';return x;}
export function liquidateBusiness(c,{discount=.35}={}){const r=ensureRestructuring(c),gross=(c.buildingState?.equipment||[]).reduce((s,x)=>s+n(x.purchasePrice||x.price),0),proceeds=gross*Math.max(0,Math.min(1,n(discount,.35)));c.money=n(c.money)+proceeds;c.buildingState.equipment=[];r.status='liquidated';return{success:true,proceeds,status:r.status};}
