// WorldProject – Finanzierung für alle Unternehmen: Kredit, Leasing, Tilgung, Zins, Sicherheiten.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureFinancing(c={}){c.financing??={loans:[],leases:[],history:[],creditScore:70};return c.financing;}
export function monthlyPayment(principal,annualRate,months){const p=Math.max(0,n(principal)),m=Math.max(1,Math.round(n(months,1))),r=Math.max(0,n(annualRate))/12;if(!r)return p/m;return p*r/(1-Math.pow(1+r,-m));}
export function financingCapacity(c){const f=ensureFinancing(c),annualProfit=n(c.lastAnnualProfit,0),cash=n(c.money),existing=f.loans.filter(x=>x.status==="active").reduce((s,x)=>s+n(x.balance),0),score=Math.max(0,Math.min(100,n(f.creditScore,70))),base=Math.max(0,cash*.8+annualProfit*2.5),limit=base*(.45+score/125);return{creditScore:score,currentDebt:existing,limit:Math.max(0,limit),available:Math.max(0,limit-existing)};}
export function takeLoan(c,{principal,annualRate=.06,months=60,purpose="Betriebsmittel",requestId}={}){const f=ensureFinancing(c),q=Math.max(0,n(principal));f.requestIds??=[];if(requestId&&f.requestIds.includes(requestId))return{success:true,idempotent:true};const cap=financingCapacity(c);if(q<=0||q>cap.available+1e-9)throw new Error("Kreditrahmen reicht nicht");const loan={id:`loan-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,principal:q,balance:q,annualRate:Math.max(0,n(annualRate)),months:Math.max(1,Math.round(n(months,60))),paymentMonthly:monthlyPayment(q,annualRate,months),purpose,status:"active",createdAt:Date.now(),paymentsMade:0};f.loans.push(loan);c.money=n(c.money)+q;f.history.push({kind:"loan_drawdown",loanId:loan.id,amount:q,at:Date.now()});if(requestId)f.requestIds.push(requestId);return{success:true,loan,balance:c.money};}
export function payLoanInstallment(c,loanId,{now=Date.now()}={}){const f=ensureFinancing(c),l=f.loans.find(x=>x.id===loanId);if(!l)throw new Error("Kredit fehlt");if(l.status==="paid")return{success:true,idempotent:true};const interest=l.balance*l.annualRate/12,scheduled=Math.min(l.balance+interest,l.paymentMonthly),principal=Math.max(0,scheduled-interest);if(n(c.money)<scheduled)throw new Error("Liquidität reicht nicht für Rate");c.money-=scheduled;l.balance=Math.max(0,l.balance-principal);l.paymentsMade++;l.lastPaymentAt=now;if(l.balance<=.01)l.status="paid";f.history.push({kind:"loan_payment",loanId,amount:scheduled,principal,interest,at:now});return{success:true,amount:scheduled,principal,interest,balance:l.balance,status:l.status};}
export function leaseAsset(c,{assetType,assetId,value,months=48,factor=.025,depositRate=.1}={}){const f=ensureFinancing(c),v=Math.max(0,n(value)),deposit=v*Math.max(0,Math.min(1,n(depositRate,.1))),monthly=v*Math.max(.001,n(factor,.025));if(n(c.money)<deposit)throw new Error("Leasinganzahlung nicht finanzierbar");c.money-=deposit;const row={id:`lease-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,assetType,assetId,value:v,deposit,monthly,months:Math.max(1,Math.round(n(months,48))),paymentsMade:0,status:"active",createdAt:Date.now()};f.leases.push(row);return row;}
export function payLease(c,leaseId,{now=Date.now()}={}){const f=ensureFinancing(c),l=f.leases.find(x=>x.id===leaseId);if(!l)throw new Error("Leasingvertrag fehlt");if(l.status==="completed")return{success:true,idempotent:true};if(n(c.money)<l.monthly)throw new Error("Liquidität reicht nicht");c.money-=l.monthly;l.paymentsMade++;l.lastPaymentAt=now;if(l.paymentsMade>=l.months)l.status="completed";return{success:true,amount:l.monthly,status:l.status};}
export function financingKpis(c){const f=ensureFinancing(c),activeLoans=f.loans.filter(x=>x.status==="active"),activeLeases=f.leases.filter(x=>x.status==="active");return{creditScore:f.creditScore,debt:activeLoans.reduce((s,x)=>s+n(x.balance),0),loanPaymentsMonthly:activeLoans.reduce((s,x)=>s+n(x.paymentMonthly),0),leasePaymentsMonthly:activeLeases.reduce((s,x)=>s+n(x.monthly),0),activeLoans:activeLoans.length,activeLeases:activeLeases.length,...financingCapacity(c)};}
