// ORVUNO – kompakte Betriebsgelände-/Gebäudeübersicht.
// Nutzt ausschließlich die bestehende Ausbau- und Gebäudelogik.
import { UniversalOperationsDialog } from './UniversalOperationsDialog.js';
import { ensureExpansionState, expansionOverview } from './LandConstructionExpansionSystem.js';
import { constructionSlotState } from './ConstructionPremiumCoinSystem.js';

const company=()=>window.worldPlayerCompany||window.worldEconomyGameplay?.company||window.worldEngine?.company;
const account=()=>window.worldCurrentUser||window.worldAccount||{};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mins=m=>{m=Math.max(0,Math.round(Number(m||0)));return m>=60?`${Math.floor(m/60)} Std. ${m%60} Min.`:`${m} Min.`;};
function el(tag,html=''){const n=document.createElement(tag);n.innerHTML=html;return n;}
function pct(used,total){return total>0?Math.max(0,Math.min(100,Math.round(used/total*100))):0;}
function injectCss(){if(document.getElementById('orvuno-premises-css'))return;const s=document.createElement('style');s.id='orvuno-premises-css';s.textContent=`
.orv-prem-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap;margin-bottom:15px}.orv-prem-head h2{margin:0 0 4px}.orv-prem-muted{color:#94a3b8}.orv-prem-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:9px;margin:12px 0 18px}.orv-prem-kpi{background:#0b1422;border:1px solid #293950;border-radius:10px;padding:12px}.orv-prem-kpi small{display:block;color:#8fa0b7;font-weight:800;text-transform:uppercase;font-size:10px;letter-spacing:.04em}.orv-prem-kpi b{display:block;font-size:20px;margin-top:4px}.orv-prem-progress{height:6px;background:#202e42;border-radius:99px;overflow:hidden;margin-top:8px}.orv-prem-progress>i{display:block;height:100%;background:#7c8fb0}.orv-prem-section{margin:18px 0 9px;font-size:15px;font-weight:900;color:#eef4fc}.orv-prem-jobs{display:grid;gap:8px}.orv-prem-job{background:#171b20;border:1px solid #4a3d27;border-radius:10px;padding:11px 12px}.orv-prem-job-top{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}.orv-prem-buildings{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:10px}.orv-prem-building{background:linear-gradient(180deg,#101b2c,#0b1422);border:1px solid #293950;border-radius:11px;padding:13px;min-height:116px}.orv-prem-building-head{display:flex;justify-content:space-between;gap:10px}.orv-prem-building h3{font-size:15px;margin:0}.orv-prem-stage{font-size:11px;padding:4px 7px;border-radius:99px;background:#16243a;color:#cbd8e9;white-space:nowrap}.orv-prem-meta{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:12px;font-size:12px}.orv-prem-meta span{background:#0a1220;border:1px solid #223149;border-radius:7px;padding:7px}.orv-prem-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.orv-prem-actions button{padding:9px 12px!important}.orv-prem-empty{border:1px dashed #334155;border-radius:10px;padding:18px;color:#94a3b8;text-align:center}@media(max-width:650px){.orv-prem-meta{grid-template-columns:1fr}}
`;document.head.append(s);}
function openExpansion(dialog){dialog.tab='expansion';dialog.render();}
function renderPremises(body,c,dialog){injectCss();ensureExpansionState(c);const o=expansionOverview(c),slots=constructionSlotState(c,account()),jobs=(o.constructionSite?.jobs||[]).filter(j=>j.status!=='finished'),buildings=o.buildings||[],used=Number(o.land?.usedSqm||0),total=Number(o.land?.totalSqm||0),free=Number(o.land?.freeSqm||0);body.innerHTML='';
 const head=el('div',`<div><h2>🏭 Betriebsgelände</h2><div class="orv-prem-muted">Alles, was auf diesem Betrieb tatsächlich steht – ohne Baukatalog und Maschinenlisten dazwischen.</div></div>`);head.className='orv-prem-head';body.append(head);
 const k=el('div');k.className='orv-prem-kpis';k.innerHTML=`<div class="orv-prem-kpi"><small>Grundstück</small><b>${total.toLocaleString('de-DE')} m²</b><div class="orv-prem-progress"><i style="width:${pct(used,total)}%"></i></div></div><div class="orv-prem-kpi"><small>Belegt</small><b>${used.toLocaleString('de-DE')} m²</b><span class="orv-prem-muted">${free.toLocaleString('de-DE')} m² frei</span></div><div class="orv-prem-kpi"><small>Gebäude</small><b>${buildings.length}</b><span class="orv-prem-muted">fertig und im Bau</span></div><div class="orv-prem-kpi"><small>Bauplätze</small><b>${slots.running} / ${slots.limit}</b><span class="orv-prem-muted">${slots.premium?'⭐ Premium':'Standard'}</span></div>`;body.append(k);
 body.append(el('div','🚧 Laufende Bauarbeiten')).lastElementChild.className='orv-prem-section';const jl=el('div');jl.className='orv-prem-jobs';if(!jobs.length)jl.innerHTML='<div class="orv-prem-empty">Keine laufenden Bauarbeiten.</div>';for(const j of jobs){const rem=mins(Math.max(0,(Number(j.finishAt||Date.now())-Date.now())/60000)),row=el('div',`<div class="orv-prem-job-top"><b>${esc(j.label||'Bauauftrag')}</b><span>${Math.round(Number(j.progress||0))}% · ⏱️ ${rem}</span></div><div class="orv-prem-progress"><i style="width:${Math.max(0,Math.min(100,Number(j.progress||0)))}%"></i></div>`);row.className='orv-prem-job';jl.append(row);}body.append(jl);
 body.append(el('div','🏢 Meine Gebäude')).lastElementChild.className='orv-prem-section';const grid=el('div');grid.className='orv-prem-buildings';if(!buildings.length)grid.innerHTML='<div class="orv-prem-empty">Noch keine zusätzlichen Gebäude gebaut.</div>';for(const b of buildings){const finished=b.status==='finished',card=el('article',`<div class="orv-prem-building-head"><h3>${esc(b.label||b.id||'Gebäude')}</h3><span class="orv-prem-stage">Stufe ${Number(b.stage||1)}</span></div><div class="orv-prem-meta"><span>📐 <b>${Number(b.sqm||0).toLocaleString('de-DE')} m²</b><br><small class="orv-prem-muted">Fläche</small></span><span>${finished?'✅':'🏗️'} <b>${finished?'Betriebsbereit':`${Math.round(Number(b.progress||0))}%`}</b><br><small class="orv-prem-muted">Status</small></span></div>`);card.className='orv-prem-building';grid.append(card);}body.append(grid);
 const actions=el('div');actions.className='orv-prem-actions';const manage=el('button','🏗️ Bauen & erweitern');manage.onclick=()=>openExpansion(dialog);actions.append(manage);const machines=el('button','⚙️ Maschinen verwalten');machines.onclick=()=>{dialog.tab='machines';dialog.render();};actions.append(machines);body.append(actions);
}
const oldRender=UniversalOperationsDialog.prototype.render;
UniversalOperationsDialog.prototype.render=function(){oldRender.call(this);const bar=this.root?.querySelector('[data-tabs]');if(!bar)return;if(!bar.querySelector('[data-premises-tab]')){const b=el('button','🏭 Gelände');b.dataset.premisesTab='1';b.style.fontWeight=this.tab==='premises'?'800':'500';b.onclick=()=>{this.tab='premises';this.render();};bar.prepend(b);}if(this.tab==='premises')renderPremises(this.root.querySelector('[data-body]'),company(),this);};
if(typeof window!=='undefined'){window.worldBusinessPremisesOverview={open(){const d=window.worldUniversalOperations;if(!d)throw new Error('Betriebsdialog ist noch nicht bereit.');d.open('premises');return d;}};}
