// WorldProject – zentrale Management-/Warnschicht. Keine neue UI, nur Daten/Aktionen für vorhandene Ansichten.
import { companyGroupKpis } from "./MultiSiteCompanySystem.js";
import { financingKpis } from "./BusinessFinancingSystem.js";
import { crmKpis } from "./CustomerRelationshipSystem.js";
import { supplierKpis } from "./SupplierManagementSystem.js";
import { pricingKpis } from "./PricingPromotionSystem.js";
import { transportNetworkKpis } from "./TransportNetworkPlanner.js";
import { schedulerKpis } from "./ProductionQueueScheduler.js";
import { complianceKpis } from "./CompliancePermitSystem.js";
import { operationalWarehouseKpis } from "./OperationalInventoryBridge.js";
import { maintenanceKpis } from "./IndustryMaintenanceEngine.js";
import { workforceKpis } from "./IndustryWorkforceDevelopment.js";
import { procurementSuggestions } from "./IndustryProcurementPlanning.js";
import { managementDashboardData } from "./IndustryManagementDashboardData.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function commandCenterSnapshot(c){const base=managementDashboardData(c),warehouse=operationalWarehouseKpis(c),maintenance=maintenanceKpis(c),workforce=workforceKpis(c),financing=financingKpis(c),crm=crmKpis(c),suppliers=supplierKpis(c),pricing=pricingKpis(c),transport=transportNetworkKpis(c),scheduler=schedulerKpis(c),compliance=complianceKpis(c),group=(c.sites?.length?companyGroupKpis(c):null),procurement=procurementSuggestions(c);return{base,warehouse,maintenance,workforce,financing,crm,suppliers,pricing,transport,scheduler,compliance,group,procurement,alerts:buildBusinessAlerts({base,warehouse,maintenance,workforce,financing,crm,suppliers,pricing,transport,scheduler,compliance,procurement}),generatedAt:Date.now()};}
export function buildBusinessAlerts(x){const out=[],push=(severity,code,title,detail,action)=>out.push({severity,code,title,detail,action});if(x.compliance.blocked||!x.compliance.compliant)push("critical","compliance","Betriebsgenehmigung prüfen",`${x.compliance.missing} fehlend, ${x.compliance.expired} abgelaufen`,"compliance");else if(x.compliance.expiring)push("warning","permit_expiring","Genehmigung läuft bald ab",`${x.compliance.expiring} Nachweis(e)`,"compliance");for(const zone of x.warehouse.criticalZones||[])push("warning","warehouse_capacity",`Lager ${zone} fast voll`,"Mindestens 90 % Auslastung","warehouse");if(x.maintenance.due)push("warning","maintenance_due","Maschinenwartung fällig",`${x.maintenance.due} Maschine(n)`,"maintenance");if(x.maintenance.unavailable)push("critical","machine_unavailable","Maschinen nicht verfügbar",`${x.maintenance.unavailable} Maschine(n)`,"machines");if(x.scheduler.late)push("critical","late_jobs","Aufträge drohen verspätet",`${x.scheduler.late} Auftrag/Aufträge`,"production");if(x.financing.available<=0&&x.financing.debt>0)push("warning","credit_limit","Kreditrahmen ausgeschöpft",`Schulden ${Math.round(x.financing.debt)} €`,"finance");if(n(x.base.finance.forecast)<0)push("critical","liquidity","Liquiditätsengpass erwartet",`${Math.round(x.base.finance.forecast)} € Prognose`,"finance");if(x.suppliers.highRisk)push("warning","supplier_risk","Lieferantenrisiko erhöht",`${x.suppliers.highRisk} Hochrisiko-Lieferant(en)`,"procurement");if(x.procurement.some(a=>a.critical))push("warning","stock_shortage","Kritischer Materialbedarf",`${x.procurement.filter(a=>a.critical).length} Materialposition(en)`,"procurement");if(x.workforce.averageFatigue>=70)push("warning","fatigue","Personal stark belastet",`${Math.round(x.workforce.averageFatigue)} % Ermüdung`,"workforce");if(x.crm.openReminders)push("info","receivables","Offene Mahnungen",`${x.crm.openReminders} Vorgang/Vorgänge`,"crm");return out.sort((a,b)=>({critical:0,warning:1,info:2}[a.severity]-({critical:0,warning:1,info:2}[b.severity]));}
export function nextBestActions(c,{limit=5}={}){const s=commandCenterSnapshot(c),map={compliance:"Genehmigungen/Prüfungen bearbeiten",warehouse:"Lagerkapazität schaffen",maintenance:"Wartung einplanen",machines:"Maschinenverfügbarkeit herstellen",production:"Produktionsplan neu priorisieren",finance:"Liquidität/Kosten prüfen",procurement:"Material beschaffen oder Alternativlieferant wählen",workforce:"Personal entlasten/Schichten anpassen",crm:"Forderungen nachfassen"};return s.alerts.slice(0,Math.max(1,n(limit,5))).map((a,i)=>({priority:i+1,severity:a.severity,title:a.title,recommendation:map[a.action]||"Problem prüfen",code:a.code}));}
if(typeof window!=="undefined"){window.worldBusinessCommandCenter=commandCenterSnapshot;window.worldBusinessNextActions=nextBestActions;}
