// WorldProject - Betriebsauswahl, Langzeit-Expansion und beliebig viele Betriebe
import { IndustryGroups } from "./IndustryCatalog.js";
import { UpgradeTracks, getUpgradeState, upgradeCost, upgradeBonus, applyUpgrade } from "./BusinessExpansionSystem.js";
import { LocationClasses, propertyOffer } from "./BusinessLocationSystem.js";

export class BusinessPortfolioDialog {
 constructor({portfolio,parent=document.body}={}){this.portfolio=portfolio;this.parent=parent;this.overlay=null;}
 el(tag,text=null){const e=document.createElement(tag);if(text!==null)e.textContent=text;return e;}
 input(value=""){const i=this.el("input");i.value=value;Object.assign(i.style,{width:"100%",boxSizing:"border-box",padding:"9px",margin:"4px 0",borderRadius:"7px",border:"1px solid #bbb"});return i;}
 button(text,fn){const b=this.el("button",text);Object.assign(b.style,{padding:"8px 10px",margin:"4px",border:0,borderRadius:"7px",fontWeight:"700",cursor:"pointer"});b.addEventListener("click",fn);return b;}
 select(values){const s=this.el("select");Object.assign(s.style,{width:"100%",padding:"9px",margin:"4px 0"});for(const v of values){const o=this.el("option",v);o.value=v;s.append(o);}return s;}
 money(v){return Number(v||0).toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
 async open(){if(this.overlay)return;const overlay=this.el("div");Object.assign(overlay.style,{position:"fixed",inset:0,zIndex:20500,background:"rgba(0,0,0,.75)",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px"});const panel=this.el("div");Object.assign(panel.style,{width:"min(850px,96vw)",maxHeight:"92vh",overflow:"auto",background:"#fff",color:"#111",borderRadius:"14px",padding:"22px",fontFamily:"Arial,sans-serif"});overlay.append(panel);this.parent.append(overlay);this.overlay=overlay;await this.render(panel);}
 close(){this.overlay?.remove();this.overlay=null;}
 async render(panel){
  panel.innerHTML="";const overview=await this.portfolio.refresh(),companies=overview.companies||[];const head=this.el("div");Object.assign(head.style,{display:"flex",justifyContent:"space-between",alignItems:"center"});head.append(this.el("h2","🏢 Meine Betriebe"),this.button("✕",()=>this.close()));panel.append(head,this.el("div",`${companies.length} Betriebe · keine feste Obergrenze`));
  for(const c of companies){const card=this.el("div");Object.assign(card.style,{border:"1px solid #ddd",borderRadius:"10px",padding:"12px",margin:"10px 0"});card.append(this.el("strong",`Betrieb ${c.slot_no}: ${c.name}`),this.el("div",`${c.company_type||c.industry||"-"} · ${this.money(c.money)} · Phase: ${c.setup_phase}`),this.button("Diesen Betrieb öffnen",()=>{this.portfolio.activate(c,window.worldPlayerCompany||{});this.close();}));panel.append(card);}
  if(companies.length){const active=this.portfolio.activeCompany||window.worldPlayerCompany||{};const u=getUpgradeState(active),upgradeBox=this.el("div");Object.assign(upgradeBox.style,{borderTop:"2px solid #ddd",marginTop:"18px",paddingTop:"16px"});upgradeBox.append(this.el("h3","Betrieb ausbauen"),this.el("div","Viele kleine Ausbaustufen verbessern den Betrieb langfristig. Werte sind bis zum Balancing vorläufig."));for(const [key,cfg] of Object.entries(UpgradeTracks)){const lvl=u[key],row=this.el("div");Object.assign(row.style,{padding:"7px",margin:"5px 0",background:"#f5f5f5",borderRadius:"7px"});row.append(this.el("span",`${cfg.label}: Stufe ${lvl}/${cfg.maxLevel} · Bonus ${(upgradeBonus(key,lvl)*100).toFixed(2)} % · nächste Stufe ${this.money(upgradeCost(key,lvl))}`),this.button("Ausbauen",()=>{try{applyUpgrade(active,key);this.render(panel);}catch(e){alert(e.message);}}));upgradeBox.append(row);}panel.append(upgradeBox);}
  const box=this.el("div");Object.assign(box.style,{borderTop:"2px solid #ddd",marginTop:"18px",paddingTop:"16px"});box.append(this.el("h3",companies.length?"Weiteren Betrieb gründen":"Ersten Betrieb gründen"));
  if(companies.length){const st=this.portfolio.getExpansionStatus(this.portfolio.activeCompany||window.worldPlayerCompany),r=st.requirements;box.append(this.el("div",`Nächste Expansion: Gründung ${this.money(r.creationCost)}, notwendige Reserve ${this.money(r.requiredCashReserve)}, Mindest-Unternehmenswert ${this.money(r.requiredNetWorth)}, Managementbedarf ${r.requiredManagement}.`));if(!st.allowed)box.append(this.el("div",`Noch gesperrt: ${st.reasons.join(" · ")}`));}
  const name=this.input("Neuer Betrieb"),industry=this.select(Object.keys(IndustryGroups)),type=this.select(IndustryGroups[industry.value]||[]),location=this.select(Object.keys(LocationClasses)),mode=this.select(["rent","buy"]);industry.addEventListener("change",()=>{type.innerHTML="";for(const v of IndustryGroups[industry.value]||[]){const o=this.el("option",v);o.value=v;type.append(o);}});const offer=this.el("div");const updateOffer=()=>{const x=propertyOffer(location.value,mode.value,1);offer.textContent=`Standort: ${LocationClasses[location.value].label} · ${mode.value==="buy"?"Kauf":"Miete"} · Start ${this.money(x.upfront)}${x.monthly?` · monatlich ${this.money(x.monthly)}`:""}`;};location.onchange=mode.onchange=updateOffer;updateOffer();box.append(name,industry,type,location,mode,offer,this.button("Betrieb anlegen",async()=>{try{await this.portfolio.createBusiness({name:name.value,industry:industry.value,companyType:type.value,locationClass:location.value,propertyMode:mode.value});await this.render(panel);}catch(e){alert(e.message);}}));panel.append(box);
  if(companies.length>1){const transfer=this.el("div");Object.assign(transfer.style,{borderTop:"2px solid #ddd",marginTop:"18px",paddingTop:"16px"});transfer.append(this.el("h3","Spielgeld zwischen eigenen Betrieben übertragen"));const labels=companies.map(c=>`${c.slot_no} · ${c.name}`),from=this.select(labels),to=this.select(labels),amount=this.input("10000"),byLabel=label=>companies.find(c=>label.startsWith(`${c.slot_no} ·`));transfer.append(from,to,amount,this.button("Übertragen",async()=>{try{const a=byLabel(from.value),b=byLabel(to.value);if(!a||!b||a.id===b.id)throw new Error("Bitte zwei verschiedene Betriebe wählen");await this.portfolio.transferMoney(a.id,b.id,Number(amount.value));await this.render(panel);}catch(e){alert(e.message);}}));panel.append(transfer);}
 }
}
