// WorldProject - Spielerboerse: Coins gegen Spielgeld
// Coins werden nicht erzeugt: jeder Kauf uebertraegt vorhandene Coins zwischen Spielern.
export class CoinExchangeSystem{
 constructor(){this.orders=[];this.trades=[];this.seq=1;}
 createSellOrder({accountId,coins,pricePerCoin}={}){const o={id:this.seq++,side:"sell",accountId,coins:Number(coins),remaining:Number(coins),pricePerCoin:Number(pricePerCoin),status:"active",createdAt:Date.now()};if(o.coins<=0||o.pricePerCoin<=0)throw new Error("Coins und Preis muessen positiv sein");this.orders.push(o);return o;}
 createBuyOrder({accountId,coins,maxPricePerCoin}={}){const o={id:this.seq++,side:"buy",accountId,coins:Number(coins),remaining:Number(coins),pricePerCoin:Number(maxPricePerCoin),status:"active",createdAt:Date.now()};if(o.coins<=0||o.pricePerCoin<=0)throw new Error("Coins und Preis muessen positiv sein");this.orders.push(o);return o;}
 orderBook(){return{sell:this.orders.filter(o=>o.status==="active"&&o.side==="sell").sort((a,b)=>a.pricePerCoin-b.pricePerCoin||a.createdAt-b.createdAt),buy:this.orders.filter(o=>o.status==="active"&&o.side==="buy").sort((a,b)=>b.pricePerCoin-a.pricePerCoin||a.createdAt-b.createdAt)};}
 match({transfer}={}){const done=[];while(true){const b=this.orderBook(),sell=b.sell[0],buy=b.buy[0];if(!sell||!buy||buy.pricePerCoin<sell.pricePerCoin)break;if(sell.accountId===buy.accountId){const newer=sell.createdAt>=buy.createdAt?sell:buy;newer.status="cancelled_self_match";continue;}const coins=Math.min(sell.remaining,buy.remaining),price=sell.createdAt<=buy.createdAt?sell.pricePerCoin:buy.pricePerCoin,trade={id:this.trades.length+1,sellerId:sell.accountId,buyerId:buy.accountId,coins,pricePerCoin:price,gameMoney:coins*price,createdAt:Date.now()};if(typeof transfer==="function")transfer(trade);sell.remaining-=coins;buy.remaining-=coins;if(sell.remaining<=0)sell.status="filled";if(buy.remaining<=0)buy.status="filled";this.trades.push(trade);done.push(trade);}return done;}
 cancel(id,accountId){const o=this.orders.find(x=>x.id===id&&x.accountId===accountId&&x.status==="active");if(!o)return false;o.status="cancelled";return true;}
}
export function runCoinExchangeTest(){const e=new CoinExchangeSystem();e.createSellOrder({accountId:1,coins:10,pricePerCoin:1000});e.createBuyOrder({accountId:2,coins:4,maxPricePerCoin:1100});const t=e.match();if(t.length!==1||t[0].coins!==4||t[0].gameMoney!==4000)throw new Error("Coinboersen-Test fehlgeschlagen");console.log("🪙 COIN/SPIELGELD-BOERSE ERFOLGREICH");return true;}
