// WorldProject – Gewerbeimmobilien, Miete/Kauf, Wertentwicklung und Standortkosten.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureRealEstate(c={}){c.realEstate??={properties:[],leases:[],history:[]};return c.realEstate;}
export function acquireProperty(c,{region='default',sizeM2=1000,pricePerM2=350,now=Date.now()}={}){const r=ensureRealEstate(c),price=Math.max(0,n(sizeM2)*n(pricePerM2));if(n(c.money)<price)throw new Error('Nicht genug Kapital für Grundstück/Immobilie');c.money-=price;const p={id:`property-${now}-${Math.random().toString(36).slice(2,6)}`,region,sizeM2:n(sizeM2),purchasePrice:price,currentValue:price,purchasedAt:now,status:'owned'};r.properties.push(p);return p;}
export function leaseProperty(c,{region='default',sizeM2=1000,monthlyPerM2=8,durationMonths=36,depositMonths=3,now=Date.now()}={}){const r=ensureRealEstate(c),monthly=Math.max(0,n(sizeM2)*n(monthlyPerM2)),deposit=monthly*Math.max(0,n(depositMonths));if(n(c.money)<deposit)throw new Error('Nicht genug Geld für Mietkaution');c.money-=deposit;const l={id:`lease-${now}-${Math.random().toString(36).slice(2,6)}`,region,sizeM2:n(sizeM2),monthlyRent:monthly,deposit,durationMonths:n(durationMonths),startsAt:now,endsAt:now+n(durationMonths)*2629800000,status:'active'};r.leases.push(l);return l;}
export function payMonthlyRent(c,{now=Date.now()}={}){const r=ensureRealEstate(c),total=r.leases.filter(x=>x.status==='active').reduce((s,x)=>s+n(x.monthlyRent),0);if(n(c.money)<total)throw new Error('Liquidität reicht nicht für Standortmieten');c.money-=total;c.costLedger??=[];if(total)c.costLedger.push({kind:'rent',amount:total,at:now});return{total};}
export function revalueProperties(c,{regionalGrowth=.02}={}){const r=ensureRealEstate(c);for(const p of r.properties.filter(x=>x.status==='owned'))p.currentValue=Math.max(0,n(p.currentValue)*(1+n(regionalGrowth)));return r.properties;}
export function sellProperty(c,id,{saleMultiplier=1,now=Date.now()}={}){const r=ensureRealEstate(c),p=r.properties.find(x=>x.id===id&&x.status==='owned');if(!p)throw new Error('Immobilie fehlt');const sale=Math.max(0,n(p.currentValue)*n(saleMultiplier,1));p.status='sold';p.soldAt=now;p.salePrice=sale;c.money=n(c.money)+sale;return{success:true,salePrice:sale,gainLoss:sale-n(p.purchasePrice)};}
export function realEstateKpis(c){const r=ensureRealEstate(c);return{owned:r.properties.filter(x=>x.status==='owned').length,leased:r.leases.filter(x=>x.status==='active').length,propertyValue:r.properties.filter(x=>x.status==='owned').reduce((s,x)=>s+n(x.currentValue),0),monthlyRent:r.leases.filter(x=>x.status==='active').reduce((s,x)=>s+n(x.monthlyRent),0)};}
