// WorldProject – Genehmigungen, Prüfungen und Compliance-Sperren je Gewerbe.
import { getIndustryProfile } from "./IndustryCatalog.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const REQUIREMENTS={brewery:["food_hygiene","production_registration"],beverage:["food_hygiene","production_registration"],bakery:["food_hygiene"],butcher:["food_hygiene","cold_chain"],food:["food_hygiene","production_registration"],livestock:["animal_welfare"],orchard:["agri_registration"],farm:["agri_registration"],mechanical:["work_safety"],metal:["work_safety"],plastic:["work_safety"],retail:["trade_registration"],wholesale:["trade_registration"],online_retail:["trade_registration"],carpentry:["work_safety"]};
export function ensureCompliance(c={}){c.compliance??={permits:[],inspections:[],incidents:[]};return c.compliance;}
export function requiredPermits(c){return [...(REQUIREMENTS[getIndustryProfile(c).branchKey]||["trade_registration"])];}
export function grantPermit(c,{id,validDays=365,now=Date.now()}={}){const s=ensureCompliance(c),existing=s.permits.find(x=>x.id===id);if(existing){existing.validUntil=now+Math.max(1,n(validDays))*86400000;existing.status="valid";return existing;}const row={id,status:"valid",grantedAt:now,validUntil:now+Math.max(1,n(validDays))*86400000};s.permits.push(row);return row;}
export function complianceStatus(c,{now=Date.now()}={}){const s=ensureCompliance(c),required=requiredPermits(c),missing=[],expired=[],expiring=[];for(const id of required){const p=s.permits.find(x=>x.id===id);if(!p)missing.push(id);else if(n(p.validUntil)<=now)expired.push(id);else if(n(p.validUntil)-now<=30*86400000)expiring.push(id);}return{required,missing,expired,expiring,compliant:!missing.length&&!expired.length,blocked:missing.length>0||expired.length>0};}
export function scheduleInspection(c,{permitId,daysUntil=30,now=Date.now()}={}){const s=ensureCompliance(c),row={id:`insp-${now}-${Math.random().toString(36).slice(2,6)}`,permitId,dueAt:now+Math.max(0,n(daysUntil))*86400000,status:"planned"};s.inspections.push(row);return row;}
export function completeInspection(c,id,{passed=true,validDays=365,now=Date.now()}={}){const s=ensureCompliance(c),i=s.inspections.find(x=>x.id===id);if(!i)throw new Error("Prüfung fehlt");if(i.status==="done")return{success:true,idempotent:true};i.status="done";i.passed=!!passed;i.completedAt=now;if(passed)grantPermit(c,{id:i.permitId,validDays,now});else{s.incidents.push({kind:"inspection_failed",permitId:i.permitId,at:now});const p=s.permits.find(x=>x.id===i.permitId);if(p)p.status="suspended";}return{success:true,inspection:i};}
export function assertOperationalCompliance(c){const status=complianceStatus(c);if(status.blocked)throw Object.assign(new Error("Betrieb wegen fehlender/abgelaufener Genehmigung gesperrt"),{compliance:status});return status;}
export function complianceKpis(c){const s=ensureCompliance(c),st=complianceStatus(c);return{compliant:st.compliant,required:st.required.length,missing:st.missing.length,expired:st.expired.length,expiring:st.expiring.length,plannedInspections:s.inspections.filter(x=>x.status==="planned").length,incidents:s.incidents.length};}
