// WorldProject – Vertragsverhandlung mit Gegenangeboten, Nutzenwert und Abschluss.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureNegotiations(c={}){c.negotiations??={sessions:[]};return c.negotiations;}
export function openNegotiation(c,{counterpartyId,kind='customer',productId,quantity=0,unitPrice=0,paymentDays=14,durationDays=90,sla=.95,bonus=0,penalty=0,now=Date.now()}={}){const s=ensureNegotiations(c),row={id:`neg-${now}-${Math.random().toString(36).slice(2,6)}`,counterpartyId,kind,productId,status:'open',round:0,offers:[{side:'company',quantity:n(quantity),unitPrice:n(unitPrice),paymentDays:n(paymentDays),durationDays:n(durationDays),sla:clamp(n(sla,.95),0,1),bonus:n(bonus),penalty:n(penalty),at:now}]};s.sessions.push(row);return row;}
export function scoreOffer(offer,{targetPrice,targetQuantity=0,maxPaymentDays=30,targetSla=.95}={}){const priceBase=Math.max(.01,n(targetPrice,n(offer.unitPrice,1))),priceScore=1-Math.min(1,Math.abs(n(offer.unitPrice)-priceBase)/priceBase),qtyScore=n(targetQuantity)>0?1-Math.min(1,Math.abs(n(offer.quantity)-n(targetQuantity))/Math.max(1,n(targetQuantity))):1,payScore=1-Math.min(1,n(offer.paymentDays)/Math.max(1,n(maxPaymentDays,30))),slaScore=1-Math.min(1,Math.abs(n(offer.sla,.95)-n(targetSla,.95)));return clamp(priceScore*.4+qtyScore*.25+payScore*.15+slaScore*.2,0,1);}
export function counterOffer(c,id,offer,{side='counterparty',now=Date.now()}={}){const s=ensureNegotiations(c),x=s.sessions.find(a=>a.id===id);if(!x||x.status!=='open')throw new Error('Verhandlung nicht offen');x.round++;x.offers.push({side,...offer,at:now});return x;}
export function acceptNegotiation(c,id,{now=Date.now()}={}){const s=ensureNegotiations(c),x=s.sessions.find(a=>a.id===id);if(!x)throw new Error('Verhandlung fehlt');if(x.status==='accepted')return{success:true,idempotent:true,deal:x.deal};const offer=x.offers.at(-1);x.status='accepted';x.acceptedAt=now;x.deal={...offer,negotiationId:x.id,counterpartyId:x.counterpartyId,kind:x.kind,productId:x.productId,status:'active'};return{success:true,deal:x.deal};}
export function rejectNegotiation(c,id,{reason='abgelehnt',now=Date.now()}={}){const x=ensureNegotiations(c).sessions.find(a=>a.id===id);if(!x)throw new Error('Verhandlung fehlt');x.status='rejected';x.rejectedAt=now;x.reason=reason;return x;}
export function negotiationKpis(c){const a=ensureNegotiations(c).sessions;return{open:a.filter(x=>x.status==='open').length,accepted:a.filter(x=>x.status==='accepted').length,rejected:a.filter(x=>x.status==='rejected').length,averageRounds:a.length?a.reduce((s,x)=>s+n(x.round),0)/a.length:0};}
