// WorldProject - gebuendelter, nicht-interaktiver Kernregressionstest.
// Keine Dialoge; nur reproduzierbare Logiktests mit klarer Fehlerliste.
import "../content/ContentBootstrap.js";
import { runTransportGameplayIntegrationTest } from "./TransportGameplayIntegration.js";
import { runAdvancedEconomyTest } from "./AdvancedEconomySystem.js";
import { SupplyOrderSystem, WarehouseSystem } from "./OperationalSupplyChainSystem.js";
import { runOperationalSupplyChainRegressionTest } from "./OperationalSupplyChainRegressionTest.js";
import { runOperationalSupplyTransactionTest } from "./OperationalSupplyTransactions.js";
import { runExtendedCoreRegression } from "./ExtendedCoreRegression.js";
import { persistenceReloadHealth } from "./PersistenceReloadHealth.js";
import { worldContentRegistry } from "./ContentRegistry.js";
import { runBusinessExpansionOperationalEffectsTest } from "./BusinessExpansionOperationalEffectsIntegration.js";
import { runBusinessExpansionTest } from "./BusinessExpansionSystem.js";
import { runIndustryEquipmentCatalogSupplementTest } from "./IndustryEquipmentCatalogSupplement.js";
import { machineRequirementSatisfied } from "./IndustryMachineCompatibility.js";
import { visibleEquipmentMarketplace,repairDuplicateIndustryEquipment } from "./IndustryEquipmentMarketplace.js";
import { runDashboardFinanceLedgerTest } from "./DashboardFinanceLedgerIntegration.js";
import { runDashboardPriorityHintsTest } from "./DashboardPriorityHintsIntegration.js";
import { runWorkforceMachineAssignmentTest } from "./WorkforceMachineAssignmentIntegration.js";
import { runCustomerOrderPresentationTest } from "./CustomerOrderFulfillmentUIBridge.js";
import { runWarehouseClearanceSaleTest } from "./WarehouseClearanceSaleIntegration.js";
import { runWarehouseSpaceRuntimeGuardTest } from "./WarehouseSpaceRuntimeGuard.js";
import { runPlayerMarketOperationalStockTest } from "./PlayerMarketExchange.js";
import { runPlayerMarketDialogShapeTest } from "./PlayerMarketDialog.js";
import { runLandConstructionExpansionTest } from "./LandConstructionExpansionSystem.js";
import { runWarehouseConstructionExpansionTest } from "./WarehouseConstructionExpansionSystem.js";
import { runProgressiveBuildingExpansionTest } from "./ProgressiveBuildingExpansionSystem.js";
import { runPremiumEntitlementTest } from "./PremiumEntitlementSystem.js";
import { runConstructionQueueTest } from "./ConstructionQueueSystem.js";
import { runConstructionPremiumCoinTest } from "./ConstructionPremiumCoinSystem.js";
import { runLiveTrafficRoutingTest } from "./LiveTrafficRoutingSystem.js";
import { runLiveTrafficDeliveryIntegrationTest } from "./LiveTrafficDeliveryIntegration.js";
import { runBusinessUpgradeTest } from "./BusinessUpgradeSystem.js";
import { runRewardedAdSystemTest } from "./RewardedAdSystem.js";
import { runRewardedAdUIIntegrationTest } from "./RewardedAdUIIntegration.js";
import { runTimeValueUtilsTest } from "./TimeValueUtils.js";
import { runActiveOperationsOverviewTest } from "./ActiveOperationsOverview.js";
import { runActiveOperationsUIFilterTest } from "./ActiveOperationsOverviewUI.js";
import { runOperationalConsistencyGuardTest } from "./OperationalConsistencyGuard.js";
import { runOperationalAttentionFeedbackTest } from "./OperationalAttentionFeedbackIntegration.js";
import { runMachineConditionProductionGuardTest } from "./MachineConditionProductionGuard.js";
import { runMachineConditionVisibilityTest } from "./MachineConditionVisibilityIntegration.js";
import { runMachineMaintenanceTest } from "./MachineMaintenanceSystem.js";
import { runMachineMaintenanceUITest } from "./MachineMaintenanceUIIntegration.js";
import { runReputationSystemTest } from "./ReputationSystem.js";
import { runUrgentCustomerOrderTest } from "./UrgentCustomerOrderSystem.js";
import { runRegularCustomerReputationTest } from "./ReputationCustomerOrderIntegration.js";
import { runCustomerFreightEconomyTest } from "./CustomerFreightEconomySystem.js";

function runBottleWasherCompatibilityTest(){runIndustryEquipmentCatalogSupplementTest();const small={type:"Brauerei",buildingState:{equipment:[{id:"micro_bottle_washer"}]}},fillerOnly={type:"Brauerei",buildingState:{equipment:[{id:"filling_line"}]}};if(!machineRequirementSatisfied(small,"bottle_washer"))throw new Error("Kleine Flaschenwaschanlage erfüllt Waschmaschinenbedarf nicht");if(machineRequirementSatisfied(fillerOnly,"bottle_washer"))throw new Error("Abfüllanlage darf Flaschenwaschanlage nicht ersetzen");return true;}
function runEquipmentLevelVisibilityTest(){runIndustryEquipmentCatalogSupplementTest();const company={type:"Brauerei",money:50000,growth:{xp:0,level:1,researchPoints:0,research:[],expansions:[],milestones:[]},buildingState:{equipment:[]}};const visible=visibleEquipmentMarketplace(company).map(x=>x.id);if(!visible.includes("micro_bottle_washer"))throw new Error("Kleine Flaschenwaschanlage fehlt auf Betriebslevel 1");if(visible.includes("bottle_washer"))throw new Error("Große Flaschenwaschanlage ist vor Betriebslevel 5 sichtbar");return true;}
function runDuplicateEquipmentRepairTest(){const company={money:1000,buildingState:{equipment:[{id:"micro_bottle_washer",purchasePrice:1800},{id:"micro_bottle_washer",purchasePrice:1800}]},financialLog:[],costLedger:[]};const result=repairDuplicateIndustryEquipment(company,{now:12345});if(!result.repaired||result.removed.length!==1||company.buildingState.equipment.length!==1||company.money!==2800)throw new Error("Doppelte Maschinen werden nicht sicher bereinigt/zurückerstattet");return true;}

export function runCoreRegressionSuite(){
 const results=[],run=(name,fn)=>{try{const value=fn();const success=value===true||value?.success===true;results.push({name,success,value});if(!success)console.error(`❌ CORE-REGRESSION ${name}`,value);}catch(error){results.push({name,success:false,error:error?.message||String(error)});console.error(`❌ CORE-REGRESSION ${name}`,error);}};
 run("Transport",()=>runTransportGameplayIntegrationTest());
 run("Advanced Economy",()=>runAdvancedEconomyTest());
 run("Operational Supply 25",()=>runOperationalSupplyChainRegressionTest());
 run("Supply Transactions",()=>runOperationalSupplyTransactionTest({SupplyOrderSystem,WarehouseSystem,supplier:worldContentRegistry.get("suppliers","brew_malt_regional")}));
 run("Operational Consistency",()=>runOperationalConsistencyGuardTest());
 run("Operational Attention Feedback",()=>runOperationalAttentionFeedbackTest());
 run("Machine Condition Production",()=>runMachineConditionProductionGuardTest());
 run("Machine Condition Visibility",()=>runMachineConditionVisibilityTest());
 run("Machine Maintenance",()=>runMachineMaintenanceTest());
 run("Machine Maintenance UI",()=>runMachineMaintenanceUITest());
 run("Reputation",()=>runReputationSystemTest());
 run("Urgent Customer Orders",()=>runUrgentCustomerOrderTest());
 run("Regular Customer Reputation",()=>runRegularCustomerReputationTest());
 run("Customer Freight Economy",()=>runCustomerFreightEconomyTest());
 run("Business Expansion Effects",()=>runBusinessExpansionOperationalEffectsTest());
 run("Unified Expansion Entry",()=>runBusinessExpansionTest());
 run("Timed Business Upgrades",()=>runBusinessUpgradeTest());
 run("Persisted Timer Values",()=>runTimeValueUtilsTest());
 run("Active Operations Reload",()=>runActiveOperationsOverviewTest());
 run("Active Operations Filter",()=>runActiveOperationsUIFilterTest());
 run("Rewarded Ads",()=>runRewardedAdSystemTest());
 run("Rewarded Ads Reload UI",()=>runRewardedAdUIIntegrationTest());
 run("Dashboard Priority Hints",()=>runDashboardPriorityHintsTest());
 run("Land Construction",()=>runLandConstructionExpansionTest());
 run("Warehouse Construction",()=>runWarehouseConstructionExpansionTest());
 run("Progressive Building Expansion",()=>runProgressiveBuildingExpansionTest());
 run("Premium Entitlements",()=>runPremiumEntitlementTest());
 run("Premium Construction Queue",()=>runConstructionQueueTest());
 run("Coin Time Reduction",()=>runConstructionPremiumCoinTest());
 run("Verified Live Traffic",()=>runLiveTrafficRoutingTest());
 run("Live Delivery Routing",()=>runLiveTrafficDeliveryIntegrationTest());
 run("Bottle Washer Compatibility",()=>runBottleWasherCompatibilityTest());
 run("Equipment Level Visibility",()=>runEquipmentLevelVisibilityTest());
 run("Duplicate Equipment Repair",()=>runDuplicateEquipmentRepairTest());
 run("Workforce Machine Assignment",()=>runWorkforceMachineAssignmentTest());
 run("Customer Delivery Quantity",()=>runCustomerOrderPresentationTest());
 run("Warehouse Clearance Sale",()=>runWarehouseClearanceSaleTest());
 run("Warehouse Pack Space",()=>runWarehouseSpaceRuntimeGuardTest());
 run("Player Market Operational Stock",()=>runPlayerMarketOperationalStockTest());
 run("Player Market Categories",()=>runPlayerMarketDialogShapeTest());
 run("Finance Ledger",()=>runDashboardFinanceLedgerTest());
 run("Extended Core",()=>runExtendedCoreRegression());
 const activeCompany=window.worldPlayerCompany;if(activeCompany&&typeof activeCompany==="object"&&Object.keys(activeCompany).length>0)run("Persistence Reload",()=>persistenceReloadHealth(activeCompany));
 const failed=results.filter(r=>!r.success),success=failed.length===0,passed=results.length-failed.length,score=Math.round(passed/Math.max(1,results.length)*100);const summary={success,score,passed,total:results.length,failed:failed.map(x=>({name:x.name,error:x.error||x.value?.failed||null})),results,ranAt:Date.now()};console[success?"log":"error"](success?`✅ WORLDPROJECT CORE HEALTH ${score}/100`:`❌ WORLDPROJECT CORE HEALTH ${score}/100`,summary);window.worldCoreRegression=summary;window.worldProjectHealth=summary;return summary;
}
runCoreRegressionSuite();window.addEventListener("worldproject:company-switched",()=>setTimeout(()=>runCoreRegressionSuite(),0));
