// WorldProject – Unternehmensstrategie: Bewertung, ROI, Standorte, Bau, Regionen, Konjunktur.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureCorporateStrategy(c={}){c.strategy??={sites:[],projects:[],regions:{},milestones:[],goals:[],events:[],history:[]};return c.strategy;}
export function enterpriseValue(c){const cash=n(c.money),inventory=Object.values(c.inventoryValue||{}).reduce((a,x)=>a+n(x),0),equipment=(c.buildingState?.equipment||[]).reduce((a,x)=>a+n(x.purchasePrice??x.price)*clamp(n(x.condition,100)/100,.1,1),0),sites=(c.strategy?.sites||[]).reduce((a,x)=>a+n(x.marketValue),0),debt=(c.financing?.loans||[]).reduce((a,x)=>a+n(x.balance),0),profit=(c.salesLedger||[]).reduce((a,x)=>a+n(x.revenue),0)-(c.costLedger||[]).reduce((a,x)=>a+n(x.amount??x.cost),0),earningValue=Math.max(0,profit)*3;return{cash,inventory,equipment,sites,debt,earningValue,equityValue:cash+inventory+equipment+sites+earningValue-debt};}
export function equityRatio(c){const v=enterpriseValue(c),assets=v.cash+v.inventory+v.equipment+v.sites;return assets>0?clamp((assets-v.debt)/assets,-5,1):0;}
export function debtRatio(c){const v=enterpriseValue(c),equity=Math.max(1,Math.abs(v.equityValue));return v.debt/equity;}
export function roi({profit=0,investment=0}={}){return n(investment)>0?n(profit)/n(investment):0;}
export function roiByMachine(c){return(c.buildingState?.equipment||[]).map(m=>({id:m.instanceId||m.id,investment:n(m.purchasePrice??m.price),profit:n(m.generatedProfit),roi:roi({profit:n(m.generatedProfit),investment:n(m.purchasePrice??m.price)})}));}
export function roiBySite(c){return ensureCorporateStrategy(c).sites.map(s=>({id:s.id,investment:n(s.investment),profit:n(s.profit),roi:roi({profit:s.profit,investment:s.investment})}));}
export function roiByProduct(c){const groups={};for(const x of c.salesLedger||[]){const k=x.productId||"unknown";(groups[k]??={revenue:0,cost:0}).revenue+=n(x.revenue);}for(const x of c.costLedger||[]){const k=x.productId||x.item||"unknown";(groups[k]??={revenue:0,cost:0}).cost+=n(x.amount??x.cost);}return Object.entries(groups).map(([id,x])=>({id,...x,profit:x.revenue-x.cost,margin:x.revenue?(x.revenue-x.cost)/x.revenue:0}));}
export function roiByCustomer(c){const groups={};for(const x of c.salesLedger||[]){const k=x.customerId||"unknown";(groups[k]??={revenue:0,cost:0}).revenue+=n(x.revenue);}for(const x of c.costLedger||[]){if(!x.customerId)continue;(groups[x.customerId]??={revenue:0,cost:0}).cost+=n(x.amount??x.cost);}return Object.entries(groups).map(([id,x])=>({id,...x,profit:x.revenue-x.cost,margin:x.revenue?(x.revenue-x.cost)/x.revenue:0}));}
export function addRegion(c,{id,name,demandIndex=1,laborIndex=1,landIndex=1,logisticsIndex=1,competitionIndex=1}={}){const s=ensureCorporateStrategy(c),row={id,name,demandIndex:n(demandIndex,1),laborIndex:n(laborIndex,1),landIndex:n(landIndex,1),logisticsIndex:n(logisticsIndex,1),competitionIndex:n(competitionIndex,1),economyIndex:1,energyIndex:1,interestIndex:1};s.regions[id]=row;return row;}
export function compareRentBuy({purchasePrice,rentMonthly,years=10,interestRate=.05,maintenanceRate=.015}={}){const buy=n(purchasePrice)*(1+n(maintenanceRate)*n(years)),rent=n(rentMonthly)*12*n(years),capitalCost=n(purchasePrice)*n(interestRate)*n(years);return{buyCost:buy+capitalCost,rentCost:rent,recommendation:buy+capitalCost<=rent?"buy":"rent"};}
export function acquireSite(c,{name,regionId,mode="buy",purchasePrice=0,rentMonthly=0,capacity=1,now=Date.now()}={}){const s=ensureCorporateStrategy(c),upfront=mode==="buy"?Math.max(0,n(purchasePrice)):Math.max(0,n(rentMonthly))*3;if(n(c.money)<upfront)throw new Error("Nicht genug Kapital");c.money-=upfront;const row={id:`site-${now}-${Math.random().toString(36).slice(2,6)}`,name,regionId,mode,purchasePrice:n(purchasePrice),rentMonthly:n(rentMonthly),capacity:n(capacity,1),investment:upfront,marketValue:mode==="buy"?n(purchasePrice):0,status:"active",openedAt:now,profit:0};s.sites.push(row);return row;}
export function closeSite(c,siteId,{sell=false,now=Date.now()}={}){const s=ensureCorporateStrategy(c),x=s.sites.find(a=>a.id===siteId);if(!x)throw new Error("Standort fehlt");if(x.status==="closed")return{success:true,idempotent:true};x.status="closed";x.closedAt=now;let proceeds=0;if(sell&&x.mode==="buy"){proceeds=Math.max(0,n(x.marketValue)*.92);c.money=n(c.money)+proceeds;x.soldAt=now;}return{success:true,proceeds};}
export function createExpansionProject(c,{siteId,kind="production",cost=25000,durationDays=30,capacityBonus=.2,now=Date.now()}={}){const s=ensureCorporateStrategy(c);if(n(c.money)<n(cost))throw new Error("Nicht genug Geld");c.money-=n(cost);const p={id:`project-${now}-${Math.random().toString(36).slice(2,6)}`,siteId,kind,cost:n(cost),durationDays:n(durationDays,30),capacityBonus:n(capacityBonus,.2),startsAt:now,endsAt:now+n(durationDays,30)*86400000,status:"building"};s.projects.push(p);return p;}
export function advanceProjects(c,{now=Date.now()}={}){const s=ensureCorporateStrategy(c),done=[];for(const p of s.projects.filter(x=>x.status==="building"&&x.endsAt<=now)){p.status="completed";p.completedAt=now;const site=s.sites.find(x=>x.id===p.siteId);if(site)site.capacity=n(site.capacity,1)*(1+n(p.capacityBonus));done.push(p);}return done;}
export function updateMacroEnvironment(c,{economy=1,rawMaterials=1,energy=1,interest=1,season=1}={}){const s=ensureCorporateStrategy(c);for(const r of Object.values(s.regions)){r.economyIndex=n(economy,1);r.rawMaterialIndex=n(rawMaterials,1);r.energyIndex=n(energy,1);r.interestIndex=n(interest,1);r.seasonIndex=n(season,1);}s.events.push({kind:"macro",economy,rawMaterials,energy,interest,season,at:Date.now()});return s.regions;}
export function triggerStrategicEvent(c,{kind,severity=.2,regionId=null,now=Date.now()}={}){const s=ensureCorporateStrategy(c),sev=clamp(n(severity,.2),0,1),effects={economic_crisis:{demand:-.3,cost:.1},boom:{demand:.25,cost:.08},supply_crisis:{demand:0,cost:.3},major_customer_loss:{demand:-.15,cost:0},machine_failure:{demand:0,cost:.12},labor_shortage:{demand:0,cost:.18}}[kind]||{demand:0,cost:0},row={id:`event-${now}-${Math.random().toString(36).slice(2,6)}`,kind,severity:sev,regionId,effects:{demand:effects.demand*sev,cost:effects.cost*sev},at:now,status:"active"};s.events.push(row);return row;}
export function addCorporateGoal(c,{id,label,target,metric,deadline=null}={}){const s=ensureCorporateStrategy(c),row={id:id||`goal-${Date.now()}`,label,target:n(target),metric,deadline,status:"active",createdAt:Date.now()};s.goals.push(row);return row;}
export function evaluateCorporateGoals(c,metrics={}){const s=ensureCorporateStrategy(c);for(const g of s.goals.filter(x=>x.status==="active")){const value=n(metrics[g.metric]);if(value>=g.target){g.status="completed";g.completedAt=Date.now();s.milestones.push({kind:"goal",goalId:g.id,label:g.label,at:g.completedAt});}else if(g.deadline&&Date.now()>g.deadline)g.status="failed";}return s.goals;}
export function strategyKpis(c){const s=ensureCorporateStrategy(c),v=enterpriseValue(c);return{enterpriseValue:v.equityValue,equityRatio:equityRatio(c),debtRatio:debtRatio(c),sitesActive:s.sites.filter(x=>x.status==="active").length,projectsBuilding:s.projects.filter(x=>x.status==="building").length,goalsActive:s.goals.filter(x=>x.status==="active").length,milestones:s.milestones.length,eventsActive:s.events.filter(x=>x.status==="active").length};}
