// Konzern-/Mehrstandortsteuerung fuer alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureCorporateGroup(c={}){c.corporateGroup??={sites:[],transfers:[],costCenters:{},profitCenters:{}};return c.corporateGroup;}
export function addGroupSite(c,{id,name,region,type,status='active'}={}){const g=ensureCorporateGroup(c);if(g.sites.some(x=>x.id===id))throw new Error('Standort existiert bereits');const s={id:id||`site-${Date.now()}`,name:name||'Standort',region:region||'default',type:type||c.type,status,revenue:0,cost:0,inventory:{},capacity:1,createdAt:Date.now()};g.sites.push(s);return s;}
export function postSiteResult(c,siteId,{revenue=0,cost=0}={}){const g=ensureCorporateGroup(c),s=g.sites.find(x=>x.id===siteId);if(!s)throw new Error('Standort fehlt');s.revenue+=Math.max(0,n(revenue));s.cost+=Math.max(0,n(cost));return s;}
export function intercompanyTransfer(c,{fromSite,toSite,item,quantity,transferPrice=0}={}){const g=ensureCorporateGroup(c),from=g.sites.find(x=>x.id===fromSite),to=g.sites.find(x=>x.id===toSite);if(!from||!to)throw new Error('Standort fehlt');const q=Math.max(0,n(quantity));if(n(from.inventory?.[item])<q)throw new Error('Standortbestand reicht nicht');from.inventory[item]=n(from.inventory[item])-q;to.inventory[item]=n(to.inventory[item])+q;const row={id:`ict-${Date.now()}`,fromSite,toSite,item,quantity:q,transferPrice:Math.max(0,n(transferPrice)),value:q*Math.max(0,n(transferPrice)),at:Date.now()};g.transfers.push(row);return row;}
export function setCostCenter(c,id,{label,budget=0}={}){const g=ensureCorporateGroup(c);g.costCenters[id]={id,label:label||id,budget:Math.max(0,n(budget)),spent:0};return g.costCenters[id];}
export function postCostCenter(c,id,amount){const g=ensureCorporateGroup(c),cc=g.costCenters[id];if(!cc)throw new Error('Kostenstelle fehlt');cc.spent+=Math.max(0,n(amount));return cc;}
export function siteProfitability(c){return ensureCorporateGroup(c).sites.map(s=>({...s,profit:n(s.revenue)-n(s.cost),margin:n(s.revenue)?(n(s.revenue)-n(s.cost))/n(s.revenue):0})).sort((a,b)=>b.profit-a.profit);}
export function closeGroupSite(c,siteId){const s=ensureCorporateGroup(c).sites.find(x=>x.id===siteId);if(!s)throw new Error('Standort fehlt');s.status='closed';s.closedAt=Date.now();return s;}
export function corporateGroupKpis(c){const g=ensureCorporateGroup(c),rows=siteProfitability(c);return{sites:g.sites.length,active:g.sites.filter(x=>x.status==='active').length,revenue:rows.reduce((s,x)=>s+n(x.revenue),0),cost:rows.reduce((s,x)=>s+n(x.cost),0),profit:rows.reduce((s,x)=>s+n(x.profit),0),transfers:g.transfers.length};}
