// WorldProject – zentrale Länder-/Währungslogik.
// Speichert intern weiterhin Basiswerte; Anzeige erfolgt lokalisiert pro Spieler/Land.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export const CurrencyCatalog=Object.freeze({
 EUR:{code:'EUR',symbol:'€',locale:'de-DE',decimals:2},USD:{code:'USD',symbol:'$',locale:'en-US',decimals:2},GBP:{code:'GBP',symbol:'£',locale:'en-GB',decimals:2},JPY:{code:'JPY',symbol:'¥',locale:'ja-JP',decimals:0},CNY:{code:'CNY',symbol:'¥',locale:'zh-CN',decimals:2},KRW:{code:'KRW',symbol:'₩',locale:'ko-KR',decimals:0},CHF:{code:'CHF',symbol:'CHF',locale:'de-CH',decimals:2},PLN:{code:'PLN',symbol:'zł',locale:'pl-PL',decimals:2},CZK:{code:'CZK',symbol:'Kč',locale:'cs-CZ',decimals:2},SEK:{code:'SEK',symbol:'kr',locale:'sv-SE',decimals:2},NOK:{code:'NOK',symbol:'kr',locale:'nb-NO',decimals:2},DKK:{code:'DKK',symbol:'kr',locale:'da-DK',decimals:2},CAD:{code:'CAD',symbol:'CA$',locale:'en-CA',decimals:2},AUD:{code:'AUD',symbol:'A$',locale:'en-AU',decimals:2},BRL:{code:'BRL',symbol:'R$',locale:'pt-BR',decimals:2},INR:{code:'INR',symbol:'₹',locale:'en-IN',decimals:2},TRY:{code:'TRY',symbol:'₺',locale:'tr-TR',decimals:2}});
export const CountryCurrency=Object.freeze({DE:'EUR',AT:'EUR',FR:'EUR',ES:'EUR',IT:'EUR',NL:'EUR',BE:'EUR',IE:'EUR',PT:'EUR',FI:'EUR',GR:'EUR',LU:'EUR',SK:'EUR',SI:'EUR',EE:'EUR',LV:'EUR',LT:'EUR',HR:'EUR',CY:'EUR',MT:'EUR',US:'USD',GB:'GBP',JP:'JPY',CN:'CNY',KR:'KRW',CH:'CHF',PL:'PLN',CZ:'CZK',SE:'SEK',NO:'NOK',DK:'DKK',CA:'CAD',AU:'AUD',BR:'BRL',IN:'INR',TR:'TRY'});
export function currencyForCountry(country='DE'){return CountryCurrency[String(country||'DE').toUpperCase()]||'EUR';}
export function resolvePlayerCurrency(player={},world={}){const explicit=String(player.currency||player.currencyCode||'').toUpperCase();if(CurrencyCatalog[explicit])return explicit;const country=player.country||player.countryCode||player.regionCountry||world.defaultCountry||'DE';return currencyForCountry(country);}
export function ensureExchangeRates(world={}){world.currency??={base:'EUR',rates:{EUR:1},updatedAt:null,source:'game'};world.currency.base=world.currency.base||'EUR';world.currency.rates??={EUR:1};if(!Number.isFinite(Number(world.currency.rates[world.currency.base])))world.currency.rates[world.currency.base]=1;return world.currency;}
export function setExchangeRate(world,{currency,rate,updatedAt=Date.now(),source='admin'}={}){const state=ensureExchangeRates(world),code=String(currency||'').toUpperCase();if(!CurrencyCatalog[code])throw new Error('Unbekannte Währung');const value=n(rate);if(value<=0||value>1000000)throw new Error('Ungültiger Wechselkurs');state.rates[code]=value;state.updatedAt=updatedAt;state.source=source;return value;}
export function convertCurrency(amount,{from='EUR',to='EUR',world={}}={}){const state=ensureExchangeRates(world),a=String(from).toUpperCase(),b=String(to).toUpperCase();if(a===b)return n(amount);const ar=n(state.rates[a],a===state.base?1:NaN),br=n(state.rates[b],b===state.base?1:NaN);if(!Number.isFinite(ar)||ar<=0)throw new Error(`Wechselkurs fehlt: ${a}`);if(!Number.isFinite(br)||br<=0)throw new Error(`Wechselkurs fehlt: ${b}`);return n(amount)/ar*br;}
export function formatCurrency(amount,{currency='EUR',locale=null}={}){const code=CurrencyCatalog[currency]?currency:'EUR',meta=CurrencyCatalog[code],loc=locale||meta.locale;try{return new Intl.NumberFormat(loc,{style:'currency',currency:code,minimumFractionDigits:meta.decimals,maximumFractionDigits:meta.decimals}).format(n(amount));}catch{return `${n(amount).toFixed(meta.decimals)} ${code}`;}}
export function playerMoneyDisplay(baseAmount,{player={},world={},baseCurrency='EUR'}={}){const currency=resolvePlayerCurrency(player,world),converted=convertCurrency(baseAmount,{from:baseCurrency,to:currency,world});return{baseAmount:n(baseAmount),baseCurrency,currency,amount:converted,formatted:formatCurrency(converted,{currency,locale:player.locale||player.language||null})};}
export function currencyHealth(world={}){const state=ensureExchangeRates(world),missing=Object.keys(CurrencyCatalog).filter(code=>!Number.isFinite(Number(state.rates[code]))||Number(state.rates[code])<=0);return{base:state.base,rates:Object.keys(state.rates).length,missing,updatedAt:state.updatedAt,source:state.source,success:missing.length===0};}
if(typeof window!=='undefined')window.worldCurrencyLocalization={catalog:CurrencyCatalog,countryCurrency:CountryCurrency,currencyForCountry,resolvePlayerCurrency,formatCurrency,convertCurrency,playerMoneyDisplay,health:currencyHealth};
