// WorldProject - KI-Auftraege werden gegen Herstellkosten + Fremdfracht kalkuliert.
// Ziel: normale Auftraege sollen bei vernuenftigem Betrieb auch ohne eigenen Lkw einen positiven Deckungsbeitrag bieten.
import { AdvancedEconomySystem } from './AdvancedEconomySystem.js';
import { customerDistanceKm,minimumProfitableCustomerPrice,customerDeliveryEconomics } from './CustomerFreightEconomySystem.js';
const p=AdvancedEconomySystem.prototype;
if(!p.__worldCustomerOrderProfitability){p.__worldCustomerOrderProfitability=true;const old=p.createCustomerOrder;p.createCustomerOrder=function(company,options={}){const result=old.call(this,company,options);if(!result?.success||!result.order)return result;const o=result.order;o.distanceKm??=customerDistanceKm(o);const cost=Number(company?.costAccounting?.productCosts?.[o.productId]?.costPerUnit)||0;if(cost>0){const minimum=minimumProfitableCustomerPrice(company,{productId:o.productId,amount:o.amount,distanceKm:o.distanceKm,targetMarginPercent:12,urgent:false}),before=Number(o.unitPrice)||0;if(before<minimum){o.originalOfferedUnitPrice=before;o.unitPrice=minimum;o.priceAdjustedForProfitability=true;}const economics=customerDeliveryEconomics(company,o);o.expectedExternalFreight=EconomicsSafe(economics.external?.cost);o.expectedProfitExternal=EconomicsSafe(economics.externalProfit);o.expectedMarginExternal=EconomicsSafe(economics.externalMarginPercent);}return result;};}
function EconomicsSafe(v){return Number.isFinite(Number(v))?Number(v):0;}
export function runCustomerOrderProfitabilityTest(){const s=new AdvancedEconomySystem(),c={money:1000,costAccounting:{productCosts:{lager033_bottle:{costPerUnit:.80}}}};s.ensureCompany(c);const r=s.createCustomerOrder(c,{productId:'lager033_bottle',amount:500,unitPrice:.82,customer:'REWE Test'});if(!r.success||!r.order.priceAdjustedForProfitability||!(r.order.unitPrice>.82)||!(r.order.expectedProfitExternal>0))throw new Error('KI-Auftrag wird nicht gegen Herstellkosten und Fremdfracht abgesichert');return true;}
if(typeof window!=='undefined')window.worldCustomerOrderProfitability={test:runCustomerOrderProfitabilityTest};
