// WorldProject – Kunden-/Auftragslebenszyklus für alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureCustomerLifecycle(c={}){c.customerLifecycle??={customers:[],quotes:[],orders:[],complaints:[],credits:[],events:[]};return c.customerLifecycle;}
export const CustomerSegments={private:{label:"Privatkunde",budget:1,priceSensitivity:1.15,qualityDemand:.75,leadTimeDemand:.8},small_business:{label:"Kleingewerbe",budget:1.8,priceSensitivity:1,qualityDemand:.82,leadTimeDemand:.9},large_business:{label:"Großkunde",budget:4,priceSensitivity:.9,qualityDemand:.9,leadTimeDemand:1.05},retail:{label:"Händlerkunde",budget:3,priceSensitivity:1.1,qualityDemand:.85,leadTimeDemand:1},industrial:{label:"Industriekunde",budget:5,priceSensitivity:.85,qualityDemand:.93,leadTimeDemand:1.1},public:{label:"Öffentlicher Auftraggeber",budget:4.5,priceSensitivity:.95,qualityDemand:.92,leadTimeDemand:1.15}};
export function upsertCustomer(c,{id,name,segment="small_business",region="local",creditScore=75,paymentDays=14}={}){const s=ensureCustomerLifecycle(c),existing=s.customers.find(x=>x.id===id);const row={id:id||`customer-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,name:name||"Kunde",segment:CustomerSegments[segment]?segment:"small_business",region,creditScore:clamp(n(creditScore,75),0,100),paymentDays:Math.max(0,n(paymentDays,14)),loyalty:50,satisfaction:75,lifetimeRevenue:0,lastOrderAt:null,active:true};if(existing){Object.assign(existing,row,{id:existing.id,lifetimeRevenue:existing.lifetimeRevenue,loyalty:existing.loyalty,satisfaction:existing.satisfaction,lastOrderAt:existing.lastOrderAt});return existing;}s.customers.push(row);return row;}
export function customerDemandProfile(c,customerId){const s=ensureCustomerLifecycle(c),x=s.customers.find(a=>a.id===customerId);if(!x)throw new Error("Kunde fehlt");return{...CustomerSegments[x.segment],creditScore:x.creditScore,paymentDays:x.paymentDays,loyalty:x.loyalty,satisfaction:x.satisfaction,region:x.region};}
export function repeatOrderProbability(c,customerId){const x=ensureCustomerLifecycle(c).customers.find(a=>a.id===customerId);if(!x)return 0;return clamp((n(x.loyalty,50)*.45+n(x.satisfaction,75)*.45+n(x.creditScore,75)*.1)/100,0.05,.98);}
export function createQuote(c,{customerId,productId,quantity,unitPrice,validDays=14,deliveryDays=7,discountRate=0,minimumMargin=null,costPerUnit=0,now=Date.now()}={}){const s=ensureCustomerLifecycle(c),q=Math.max(0,n(quantity)),price=Math.max(0,n(unitPrice))*(1-clamp(n(discountRate),0,.8)),margin=price?((price-n(costPerUnit))/price):0,row={id:`quote-${now}-${Math.random().toString(36).slice(2,7)}`,customerId,productId,quantity:q,unitPrice:price,discountRate:n(discountRate),costPerUnit:n(costPerUnit),margin,lossMaking:price<n(costPerUnit),minimumMargin,validUntil:now+Math.max(1,n(validDays,14))*86400000,proposedDeliveryAt:now+Math.max(0,n(deliveryDays,7))*86400000,status:"open",createdAt:now};if(minimumMargin!==null&&margin<n(minimumMargin))row.warning="Mindestmarge unterschritten";s.quotes.push(row);return row;}
export function rejectQuote(c,quoteId,reason="abgelehnt"){const q=ensureCustomerLifecycle(c).quotes.find(x=>x.id===quoteId);if(!q)throw new Error("Angebot fehlt");if(q.status!=="open")return q;q.status="rejected";q.rejectionReason=reason;q.closedAt=Date.now();return q;}
export function acceptQuote(c,quoteId,{priority=0,allowLoss=false,now=Date.now()}={}){const s=ensureCustomerLifecycle(c),q=s.quotes.find(x=>x.id===quoteId);if(!q)throw new Error("Angebot fehlt");if(q.status==="accepted")return{success:true,idempotent:true,order:s.orders.find(x=>x.quoteId===quoteId)};if(q.status!=="open"||q.validUntil<now)throw new Error("Angebot nicht mehr gültig");if(q.lossMaking&&!allowLoss)throw new Error("Verlustauftrag muss ausdrücklich bestätigt werden");q.status="accepted";q.acceptedAt=now;const order={id:`order-${now}-${Math.random().toString(36).slice(2,7)}`,quoteId:q.id,customerId:q.customerId,productId:q.productId,quantity:q.quantity,delivered:0,unitPrice:q.unitPrice,dueAt:q.proposedDeliveryAt,priority:n(priority),status:"open",createdAt:now,lossAccepted:!!(q.lossMaking&&allowLoss)};s.orders.push(order);return{success:true,order};}
export function orderContribution(order,costPerUnit=0){const revenue=n(order.quantity)*n(order.unitPrice),cost=n(order.quantity)*n(costPerUnit);return{revenue,cost,contribution:revenue-cost,margin:revenue?(revenue-cost)/revenue:0};}
export function customerOrderPriority(order,{contractValueWeight=.001,now=Date.now()}={}){const lateness=Math.max(0,now-n(order.dueAt))/86400000,daysLeft=(n(order.dueAt,now)-now)/86400000,value=n(order.quantity)*n(order.unitPrice);return n(order.priority)*1000+lateness*500+Math.max(0,7-daysLeft)*20+value*n(contractValueWeight,.001);}
export function sortCustomerLifecycleOrders(c){return [...ensureCustomerLifecycle(c).orders].filter(x=>!["completed","cancelled"].includes(x.status)).sort((a,b)=>customerOrderPriority(b)-customerOrderPriority(a));}
export function deliverCustomerOrder(c,orderId,quantity,{now=Date.now()}={}){const s=ensureCustomerLifecycle(c),o=s.orders.find(x=>x.id===orderId);if(!o)throw new Error("Auftrag fehlt");if(o.status==="completed")return{success:true,idempotent:true,delivered:0};const q=Math.min(Math.max(0,n(quantity)),Math.max(0,n(o.quantity)-n(o.delivered)));o.delivered=n(o.delivered)+q;o.status=o.delivered>=o.quantity?"completed":"partial";if(o.status==="completed")o.completedAt=now;const customer=s.customers.find(x=>x.id===o.customerId);if(customer){customer.lastOrderAt=now;customer.lifetimeRevenue=n(customer.lifetimeRevenue)+q*n(o.unitPrice);customer.satisfaction=clamp(n(customer.satisfaction,75)+(now<=o.dueAt?2:-6)+(o.status==="completed"?1:0),0,100);customer.loyalty=clamp(n(customer.loyalty,50)+(now<=o.dueAt?1:-2),0,100);}return{success:true,delivered:q,remaining:Math.max(0,o.quantity-o.delivered),status:o.status,revenue:q*n(o.unitPrice)};}
export function createComplaint(c,{orderId,reason="quality",quantity=1,description="",now=Date.now()}={}){const s=ensureCustomerLifecycle(c),o=s.orders.find(x=>x.id===orderId);if(!o)throw new Error("Auftrag fehlt");const row={id:`complaint-${now}-${Math.random().toString(36).slice(2,6)}`,orderId,customerId:o.customerId,reason,quantity:Math.max(0,n(quantity)),description,status:"open",createdAt:now};s.complaints.push(row);const customer=s.customers.find(x=>x.id===o.customerId);if(customer){customer.satisfaction=clamp(n(customer.satisfaction,75)-(reason==="quality"?8:reason==="late"?6:4),0,100);customer.loyalty=clamp(n(customer.loyalty,50)-3,0,100);}return row;}
export function resolveComplaint(c,complaintId,{resolution="credit",amount=0,replacementQuantity=0,now=Date.now()}={}){const s=ensureCustomerLifecycle(c),x=s.complaints.find(a=>a.id===complaintId);if(!x)throw new Error("Reklamation fehlt");if(x.status==="resolved")return{success:true,idempotent:true};x.status="resolved";x.resolution=resolution;x.resolvedAt=now;if(resolution==="credit"||resolution==="partial_credit"){const credit={id:`credit-${now}-${Math.random().toString(36).slice(2,6)}`,customerId:x.customerId,complaintId:x.id,amount:Math.max(0,n(amount)),createdAt:now,status:"open"};s.credits.push(credit);x.creditId=credit.id;}if(resolution==="replacement")x.replacementQuantity=Math.max(0,n(replacementQuantity));const customer=s.customers.find(a=>a.id===x.customerId);if(customer){customer.satisfaction=clamp(n(customer.satisfaction,75)+3,0,100);customer.loyalty=clamp(n(customer.loyalty,50)+1,0,100);}return{success:true,complaint:x};}
export function customerLifecycleKpis(c){const s=ensureCustomerLifecycle(c),active=s.customers.filter(x=>x.active);return{customers:active.length,quotesOpen:s.quotes.filter(x=>x.status==="open").length,ordersOpen:s.orders.filter(x=>!["completed","cancelled"].includes(x.status)).length,complaintsOpen:s.complaints.filter(x=>x.status==="open").length,averageSatisfaction:active.length?active.reduce((a,x)=>a+n(x.satisfaction,75),0)/active.length:0,averageLoyalty:active.length?active.reduce((a,x)=>a+n(x.loyalty,50),0)/active.length:0,lifetimeRevenue:active.reduce((a,x)=>a+n(x.lifetimeRevenue),0)};}
