// WorldProject – CRM für alle Gewerbe: Kundensegmente, Loyalität, Bonität, Zahlungsziele, Mahnungen.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureCrm(c={}){c.crm??={customers:[],history:[],reminders:[]};return c.crm;}
export function createCustomer(c,{name,type="business",creditScore=75,paymentDays=14,priceSensitivity=.5,loyalty=40}={}){const crm=ensureCrm(c),row={id:`cust-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,name:name||"Kunde",type,creditScore:clamp(n(creditScore,75),0,100),paymentDays:Math.max(0,n(paymentDays,14)),priceSensitivity:clamp(n(priceSensitivity,.5),0,1),loyalty:clamp(n(loyalty,40),0,100),orders:0,revenue:0,latePayments:0,status:"active",createdAt:Date.now()};crm.customers.push(row);return row;}
export function customerById(c,id){return ensureCrm(c).customers.find(x=>x.id===id)||null;}
export function customerDiscount(customer,{base=0,max=.12}={}){const loyalty=clamp(n(customer?.loyalty),0,100),revenue=n(customer?.revenue),tier=Math.min(1,revenue/100000),discount=n(base)+loyalty/100*.05+tier*.05;return clamp(discount,0,n(max,.12));}
export function recordCustomerOrder(c,customerId,{revenue=0,onTime=true,complete=true,quality=1}={}){const crm=ensureCrm(c),cust=customerById(c,customerId);if(!cust)throw new Error("Kunde fehlt");cust.orders++;cust.revenue+=Math.max(0,n(revenue));cust.loyalty=clamp(cust.loyalty+(onTime?2:-5)+(complete?1:-3)+(n(quality,1)-.8)*6,0,100);crm.history.push({kind:"order",customerId,revenue:n(revenue),onTime,complete,quality:n(quality,1),at:Date.now()});return cust;}
export function paymentTerms(customer,orderValue){const score=clamp(n(customer?.creditScore,75),0,100),days=score>=85?30:score>=65?14:score>=45?7:0,depositRate=score<45?.5:score<60?.25:0,limit=Math.max(500,score*200+n(customer?.revenue)*.1);return{days:Math.min(days,n(customer?.paymentDays,days)),depositRate,creditLimit:limit,requiresPrepayment:n(orderValue)>limit||score<30};}
export function recordLatePayment(c,customerId,{daysLate=1}={}){const crm=ensureCrm(c),cust=customerById(c,customerId);if(!cust)throw new Error("Kunde fehlt");cust.latePayments++;cust.creditScore=clamp(cust.creditScore-Math.min(15,Math.max(1,n(daysLate))*.5),0,100);cust.loyalty=clamp(cust.loyalty-1,0,100);crm.history.push({kind:"late_payment",customerId,daysLate:n(daysLate),at:Date.now()});return cust;}
export function createReminder(c,{customerId,reference,amount,dueAt,level=1,now=Date.now()}={}){const crm=ensureCrm(c),row={id:`rem-${now}-${Math.random().toString(36).slice(2,6)}`,customerId,reference,amount:Math.max(0,n(amount)),dueAt:n(dueAt),level:Math.max(1,n(level,1)),fee:[0,5,15,35][Math.min(3,Math.max(0,n(level,1)))],status:"open",createdAt:now};crm.reminders.push(row);return row;}
export function closeReminder(c,id){const r=ensureCrm(c).reminders.find(x=>x.id===id);if(!r)throw new Error("Mahnung fehlt");r.status="paid";r.closedAt=Date.now();return r;}
export function crmKpis(c){const crm=ensureCrm(c),active=crm.customers.filter(x=>x.status==="active"),revenue=active.reduce((s,x)=>s+n(x.revenue),0);return{customers:active.length,revenue,averageLoyalty:active.length?active.reduce((s,x)=>s+n(x.loyalty),0)/active.length:0,averageCreditScore:active.length?active.reduce((s,x)=>s+n(x.creditScore),0)/active.length:0,openReminders:crm.reminders.filter(x=>x.status==="open").length,repeatCustomers:active.filter(x=>x.orders>=2).length};}
