// Kommerzieller Kundenkern fuer alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureCommercial(c={}){c.customerCommercial??={accounts:{},contracts:[],claims:[],events:[]};return c.customerCommercial;}
export function ensureCustomerAccount(c,customerId,{segment='business',creditLimit=10000,paymentDays=14}={}){const s=ensureCommercial(c);s.accounts[customerId]??={customerId,segment,creditLimit:Math.max(0,n(creditLimit)),paymentDays:Math.max(0,n(paymentDays)),openExposure:0,revenue:0,cost:0,orders:0,lateDeliveries:0,claims:0,satisfaction:75};return s.accounts[customerId];}
export function createCommercialContract(c,{customerId,productId,unitPrice,monthlyQuantity=0,minQuantity=0,durationDays=180,deliveryWindowHours=24,penaltyPerDay=0,bonusOnTime=0}={}){const s=ensureCommercial(c),a=ensureCustomerAccount(c,customerId);const row={id:`contract-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,customerId,productId,unitPrice:Math.max(0,n(unitPrice)),monthlyQuantity:Math.max(0,n(monthlyQuantity)),minQuantity:Math.max(0,n(minQuantity)),startsAt:Date.now(),endsAt:Date.now()+Math.max(1,n(durationDays))*86400000,deliveryWindowHours:Math.max(1,n(deliveryWindowHours)),penaltyPerDay:Math.max(0,n(penaltyPerDay)),bonusOnTime:Math.max(0,n(bonusOnTime)),status:'active'};s.contracts.push(row);a.contracts=(a.contracts||0)+1;return row;}
export function canAcceptCreditOrder(c,customerId,value){const a=ensureCustomerAccount(c,customerId);return{ok:a.openExposure+n(value)<=a.creditLimit,available:Math.max(0,a.creditLimit-a.openExposure)};}
export function bookCustomerOrderExposure(c,customerId,value){const a=ensureCustomerAccount(c,customerId),check=canAcceptCreditOrder(c,customerId,value);if(!check.ok)throw new Error('Kundenkreditlimit ueberschritten');a.openExposure+=Math.max(0,n(value));a.orders++;return a;}
export function settleCommercialDelivery(c,{customerId,revenue,cost=0,onTime=true,complete=true}={}){const a=ensureCustomerAccount(c,customerId),r=Math.max(0,n(revenue));a.openExposure=Math.max(0,a.openExposure-r);a.revenue+=r;a.cost+=Math.max(0,n(cost));if(!onTime)a.lateDeliveries++;a.satisfaction=clamp(a.satisfaction+(onTime?1:-5)+(complete?1:-3),0,100);ensureCommercial(c).events.push({kind:'delivery',customerId,revenue:r,onTime,complete,at:Date.now()});return a;}
export function fileCustomerClaim(c,{customerId,orderId,reason='quality',quantity=0,requested='credit',estimatedCost=0}={}){const s=ensureCommercial(c),a=ensureCustomerAccount(c,customerId),claim={id:`claim-${Date.now()}`,customerId,orderId,reason,quantity:Math.max(0,n(quantity)),requested,estimatedCost:Math.max(0,n(estimatedCost)),status:'open',createdAt:Date.now()};s.claims.push(claim);a.claims++;a.satisfaction=clamp(a.satisfaction-4,0,100);return claim;}
export function resolveCustomerClaim(c,id,{resolution='credit',amount=0}={}){const s=ensureCommercial(c),claim=s.claims.find(x=>x.id===id);if(!claim)throw new Error('Reklamation fehlt');claim.status='resolved';claim.resolution=resolution;claim.amount=Math.max(0,n(amount));claim.resolvedAt=Date.now();return claim;}
export function customerLifetimeValue(c,customerId){const a=ensureCustomerAccount(c,customerId);return{customerId,revenue:a.revenue,cost:a.cost,profit:a.revenue-a.cost,orders:a.orders,claims:a.claims,lateDeliveries:a.lateDeliveries,satisfaction:a.satisfaction};}
