// WorldProject - zieht bei echter Kundenlieferung die Logistikkosten ab.
// Ohne freien eigenen Lkw wird automatisch eine regionale Fremdspedition genutzt.
// Mit eigenem Lkw werden echte Diesel-, Verschleiss- und anteilige Fixkosten gebucht und Fahrzeugwerte aktualisiert.
import { AdvancedEconomySystem } from './AdvancedEconomySystem.js';
import { FleetOperatingCostSystem } from './FleetOperatingCostSystem.js';
import { customerDeliveryEconomics } from './CustomerFreightEconomySystem.js';
const fleetCosts=new FleetOperatingCostSystem();
function record(system,company,type,amount,details){if(typeof system.record==='function')system.record(company,type,amount,details);else{company.financialLog??=[];company.financialLog.push({time:new Date(),type,amount,details});}}
function executeOwnTrip(company,quote){const vehicle=quote?.vehicle;if(!vehicle)return null;const trip=fleetCosts.calculateTrip(vehicle,quote.distanceKm);if(!trip.success)return null;const monthly=fleetCosts.calculateMonthly(vehicle),fixedShare=monthly.success?monthly.total/120:0,total=Math.round((trip.totalOperatingCost+fixedShare)*100)/100;return{vehicle,trip,fixedShare,total};}
const p=AdvancedEconomySystem.prototype;
if(!p.__worldCustomerFreightDelivery){p.__worldCustomerFreightDelivery=true;const old=p.deliverCustomerOrder;p.deliverCustomerOrder=function(company,orderId,amount){const order=(company?.customerOrders||[]).find(x=>x.id===orderId),requested=Math.max(0,Number(amount)||0);if(!order)return old.call(this,company,orderId,amount);const before=Math.max(0,Number(order.delivered)||0),result=old.call(this,company,orderId,amount);if(!result?.success)return result;const delivered=Math.max(0,Number(result.accepted)||Number(order.delivered||0)-before),actual=customerDeliveryEconomics(company,order,{quantity:delivered}),ownExecution=actual.own?executeOwnTrip(company,actual.own):null,mode=ownExecution?'own':'external',freight=ownExecution?ownExecution.total:Math.max(0,Number(actual.external?.cost)||0),provider=mode==='own'?'Eigener Fuhrpark':actual.external.provider;company.money=Number(company.money||0)-freight;if(mode==='own'){record(this,company,'customer_delivery_own_fleet',-freight,{orderId:order.id,qty:delivered,distanceKm:actual.distanceKm,vehicleId:ownExecution.vehicle.id,fuelCost:ownExecution.trip.fuelCost,maintenanceCost:ownExecution.trip.maintenanceCost,refuelCost:ownExecution.trip.refuelCost,fixedCostShare:ownExecution.fixedShare,liters:ownExecution.trip.liters,wearPercent:ownExecution.trip.wearPercent});}else record(this,company,'customer_delivery_external_freight',-freight,{orderId:order.id,qty:delivered,distanceKm:actual.distanceKm,provider});result.freight={mode,cost:freight,distanceKm:actual.distanceKm,provider,vehicle:ownExecution?.vehicle||null,costBreakdown:ownExecution?{fuel:ownExecution.trip.fuelCost,maintenance:ownExecution.trip.maintenanceCost,refuel:ownExecution.trip.refuelCost,fixedCostShare:ownExecution.fixedShare,liters:ownExecution.trip.liters,wearPercent:ownExecution.trip.wearPercent}:null};result.netRevenue=Number(result.revenue||0)-freight;result.freightSaving=mode==='own'?Math.max(0,actual.external.cost-freight):0;return result;};}
export function runCustomerFreightDeliveryTest(){const s=new AdvancedEconomySystem(),externalCompany={money:1000,finishedGoods:{lager033_bottle:500},vehicles:[],costAccounting:{productCosts:{lager033_bottle:{costPerUnit:.55}}}};s.ensureCompany(externalCompany);const created=s.createCustomerOrder(externalCompany,{productId:'lager033_bottle',amount:100,unitPrice:1,customer:'REWE Test'});created.order.distanceKm=15;const before=externalCompany.money,r=s.deliverCustomerOrder(externalCompany,created.order.id,100);if(!r.success||r.freight?.mode!=='external'||!(r.freight.cost>0)||!(externalCompany.money<before+100))throw new Error('Fremdfracht wird bei Kundenlieferung nicht abgezogen');const ownCompany={money:1000,finishedGoods:{lager033_bottle:100},vehicles:[{id:'t1',type:'truck18',status:'available',condition:100,fuelLiters:300,odometerKm:0,ownership:'owned'}],costAccounting:{productCosts:{lager033_bottle:{costPerUnit:.55}}}};s.ensureCompany(ownCompany);const ownOrder=s.createCustomerOrder(ownCompany,{productId:'lager033_bottle',amount:100,unitPrice:1,customer:'REWE Eigen'});ownOrder.order.distanceKm=20;const v=ownCompany.vehicles[0],fuelBefore=v.fuelLiters,kmBefore=v.odometerKm,own=s.deliverCustomerOrder(ownCompany,ownOrder.order.id,100);if(!own.success||own.freight?.mode!=='own'||!(own.freight.cost>0)||!(v.fuelLiters<fuelBefore)||!(v.odometerKm>kmBefore)||!(v.condition<100))throw new Error('Eigener Lkw verbraucht bei Kundenlieferung nicht korrekt Diesel/Verschleiss');return true;}
if(typeof window!=='undefined')window.worldCustomerFreightDelivery={test:runCustomerFreightDeliveryTest};
