// WorldProject - zieht bei echter Kundenlieferung die Logistikkosten ab.
// Ohne freien eigenen Lkw wird automatisch eine regionale Fremdspedition genutzt.
import { AdvancedEconomySystem } from './AdvancedEconomySystem.js';
import { customerDeliveryEconomics } from './CustomerFreightEconomySystem.js';
function record(system,company,type,amount,details){if(typeof system.record==='function')system.record(company,type,amount,details);else{company.financialLog??=[];company.financialLog.push({time:new Date(),type,amount,details});}}
const p=AdvancedEconomySystem.prototype;
if(!p.__worldCustomerFreightDelivery){p.__worldCustomerFreightDelivery=true;const old=p.deliverCustomerOrder;p.deliverCustomerOrder=function(company,orderId,amount){const order=(company?.customerOrders||[]).find(x=>x.id===orderId),requested=Math.max(0,Number(amount)||0);if(!order)return old.call(this,company,orderId,amount);const before=Math.max(0,Number(order.delivered)||0),economics=customerDeliveryEconomics(company,order,{quantity:requested}),result=old.call(this,company,orderId,amount);if(!result?.success)return result;const delivered=Math.max(0,Number(result.accepted)||Number(order.delivered||0)-before),actual=customerDeliveryEconomics(company,order,{quantity:delivered}),quote=actual.own||actual.external,freight=Math.max(0,Number(quote?.cost)||0);company.money=Number(company.money||0)-freight;record(this,company,quote.mode==='own'?'customer_delivery_own_fleet':'customer_delivery_external_freight',-freight,{orderId:order.id,qty:delivered,distanceKm:actual.distanceKm,provider:quote.provider||null,vehicleId:quote.vehicle?.id||null});result.freight={mode:quote.mode,cost:freight,distanceKm:actual.distanceKm,provider:quote.provider||'Eigener Fuhrpark',vehicle:quote.vehicle||null};result.netRevenue=Number(result.revenue||0)-freight;result.freightSaving=actual.own?actual.savingWithOwnFleet:0;return result;};}
export function runCustomerFreightDeliveryTest(){const s=new AdvancedEconomySystem(),c={money:1000,finishedGoods:{lager033_bottle:500},vehicles:[],costAccounting:{productCosts:{lager033_bottle:{costPerUnit:.55}}}};s.ensureCompany(c);const created=s.createCustomerOrder(c,{productId:'lager033_bottle',amount:100,unitPrice:1,customer:'REWE Test'});created.order.distanceKm=15;const before=c.money,r=s.deliverCustomerOrder(c,created.order.id,100);if(!r.success||r.freight?.mode!=='external'||!(r.freight.cost>0)||!(c.money<before+100))throw new Error('Fremdfracht wird bei Kundenlieferung nicht abgezogen');return true;}
if(typeof window!=='undefined')window.worldCustomerFreightDelivery={test:runCustomerFreightDeliveryTest};
