// WorldProject - eigener Lkw und Premium erweitern die normale Kundenauftragsauswahl.
// Ohne Lkw: 2 regional. Mit Lkw: 2 regional + 1 fern. Mit Lkw+Premium: 3 regional + 2 fern.
import { ConnectedEconomyGameplay } from './ConnectedEconomyGameplay.js';
import { PremiumEntitlementSystem } from './PremiumEntitlementSystem.js';
import { getIndustryProfile } from './IndustryCatalog.js';
import { minimumProfitableCustomerPrice } from './CustomerFreightEconomySystem.js';
import { TruckTypes } from './TruckTypes.js';
const premium=new PremiumEntitlementSystem();
const accountFor=()=>window.worldCurrentUser||window.worldAccount||window.worldPlayerAccount||{};
const ownedVehicles=company=>(company?.vehicles||[]).filter(v=>v&&v.status!=='sold');
const hasOwnedTruck=company=>ownedVehicles(company).length>0;
export function customerOrderCapacity(company,account=accountFor()){const truck=hasOwnedTruck(company),premiumActive=truck&&premium.state(account,Date.now()).active;return premiumActive?{total:5,regional:3,distant:2,truck:true,premium:true}:truck?{total:3,regional:2,distant:1,truck:true,premium:false}:{total:2,regional:2,distant:0,truck:false,premium:false};}
function productFor(company,index=0){const products=getIndustryProfile(company)?.products||[];return products[index%Math.max(1,products.length)]||'lager033_bottle';}
function branchKey(company){return getIndustryProfile(company)?.branchKey||'generic';}
const unitsPerPalletByBranch={brewery:720,beverage:720,bakery:300,butcher:240,carpentry:45,farm:900,mechanical:120,metal:100,plastic:160,generic:120};
function unitsPerPallet(company){return unitsPerPalletByBranch[branchKey(company)]||unitsPerPalletByBranch.generic;}
function bestTruck(company){return ownedVehicles(company).map(v=>({vehicle:v,def:v.definition||TruckTypes[v.type]})).filter(x=>x.def).sort((a,b)=>(Number(b.def.maxPallets)||0)-(Number(a.def.maxPallets)||0))[0]||null;}
export function distantLoadPlan(company,index=0){const truck=bestTruck(company),pallets=Math.max(1,Number(truck?.def?.maxPallets)||4),loadFactor=index%2===0?.92:.84,targetPallets=Math.max(1,Math.round(pallets*loadFactor)),amount=Math.max(1,Math.round(targetPallets*unitsPerPallet(company)));return{truck:truck?.vehicle||null,truckType:truck?.def?.id||null,maxPallets:pallets,targetPallets,loadFactor,amount,unitsPerPallet:unitsPerPallet(company)};}
function regionalTemplate(company,index){const names=['Regionalmarkt','Nahversorger','Lokaler Fachhandel','Gastronomie Regional'];const distanceKm=10+((index*17+String(company?.name||'').length)%51),amount=500+((index*350)%1000),productId=productFor(company,index),base=Number(company?.salesPrices?.[productId])||.95,min=minimumProfitableCustomerPrice(company,{productId,amount,distanceKm,targetMarginPercent:12});return{customer:`${names[index%names.length]} ${index+1}`,productId,amount,unitPrice:Math.max(base,min),dueHours:72,distanceKm,routeClass:'regional'};}
function distantTemplate(company,index){const names=['Überregionaler Handelsmarkt','Großkunde Fernregion','Zentrallager Handel','Getränkegroßhandel Fern'],load=distantLoadPlan(company,index),distanceKm=140+((index*73+String(company?.name||'').length*3)%181),amount=load.amount,productId=productFor(company,index+1),base=Number(company?.salesPrices?.[productId])||.95,min=minimumProfitableCustomerPrice(company,{productId,amount,distanceKm,targetMarginPercent:18});return{customer:`${names[index%names.length]} ${index+1}`,productId,amount,unitPrice:Math.max(base*1.10,min),dueHours:96,distanceKm,routeClass:'distant',truckLoad:load};}
function addOrder(game,company,t){const r=game.createCustomerOrder(company,t);if(r?.success){Object.assign(r.order,{distanceKm:t.distanceKm,routeClass:t.routeClass,truckLoad:t.truckLoad||null});return r.order;}return null;}
const p=ConnectedEconomyGameplay.prototype;
if(!p.__worldCustomerOrderCapacityByFleet){p.__worldCustomerOrderCapacityByFleet=true;const old=p.ensureCustomerOrders;p.ensureCustomerOrders=function(company){this.ensureCompany(company);if(company.setupPhase&&company.setupPhase!=='operating')return[];if(company.microBusiness?.stage==='micro')return old.call(this,company);old.call(this,company);const cap=customerOrderCapacity(company),open=()=>company.customerOrders.filter(x=>x.status==='open'),byClass=kind=>open().filter(x=>(x.routeClass||'regional')===kind);let guard=0;while(byClass('regional').length<cap.regional&&open().length<cap.total&&guard++<10){const t=regionalTemplate(company,byClass('regional').length);if(company.customerOrders.some(x=>x.status==='open'&&x.customer===t.customer))break;addOrder(this,company,t);}guard=0;while(byClass('distant').length<cap.distant&&open().length<cap.total&&guard++<10){const t=distantTemplate(company,byClass('distant').length);if(company.customerOrders.some(x=>x.status==='open'&&x.customer===t.customer))break;addOrder(this,company,t);}return open();};}
export function runCustomerOrderCapacityByFleetTest(){const std={},truck={type:'Brauerei',vehicles:[{id:'t1',type:'truck18',status:'available'}]},a={premiumUntil:0};if(customerOrderCapacity(std,a).total!==2||customerOrderCapacity(truck,a).total!==3)throw new Error('Lkw-Auftragslimit fehlerhaft');const load=distantLoadPlan(truck,0);if(load.maxPallets!==20||load.targetPallets<16||load.amount<10000)throw new Error('Fernauftrag nutzt Lkw-Kapazität nicht sinnvoll');const now=Date.now(),prem={premiumUntil:now+86400000};if(customerOrderCapacity(truck,prem).total!==5||customerOrderCapacity(truck,prem).distant!==2)throw new Error('Premium-Lkw-Auftragslimit fehlerhaft');return true;}
if(typeof window!=='undefined')window.worldCustomerOrderCapacity={state:customerOrderCapacity,loadPlan:distantLoadPlan,test:runCustomerOrderCapacityByFleetTest};
