// WorldProject - wirtschaftliche Kundenlogistik: Fremdspedition als Startweg, eigener Fuhrpark als Vorteil.
// Preise sind bewusst spielerisch regional balanciert, nicht als reale Speditionspreisliste gedacht.
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function customerDistanceKm(order={}){const explicit=Number(order.distanceKm??order.customerDistanceKm??order.deliveryDistanceKm);if(Number.isFinite(explicit)&&explicit>0)return explicit;const seed=String(order.customer||order.customerName||order.id||'regional').split('').reduce((s,c)=>s+c.charCodeAt(0),0);return 8+(seed%68);}
export function externalFreightQuote({distanceKm=20,quantity=1,urgent=false}={}){const km=clamp(Number(distanceKm)||20,1,500),qty=Math.max(1,Number(quantity)||1),size=qty<=100?'Kleintransporter':qty<=750?'Transporter':qty<=2500?'7,5-t-Lkw':'Lkw',base=qty<=100?5:qty<=750?8:qty<=2500?14:22,perKm=qty<=100?.18:qty<=750?.24:qty<=2500?.34:.48,handling=Math.min(18,Math.max(0,qty-50)*.006),rush=urgent?1.18:1,cost=Math.round((base+km*perKm+handling)*rush*100)/100;return{mode:'external',provider:'Regionale Fremdspedition',vehicleClass:size,distanceKm:km,quantity:qty,urgent,cost:Math.max(6,cost),pickupDelayHours:urgent?1:2+Math.min(4,km/50),estimatedDriveHours:Math.max(.25,km/55)};}
export function ownFleetQuote(company,{distanceKm=20,quantity=1}={}){const available=(company?.vehicles||[]).find(v=>String(v.status||'available')==='available');if(!available)return null;const km=clamp(Number(distanceKm)||20,1,500),qty=Math.max(1,Number(quantity)||1),operating=Math.round(Math.max(3,km*.22+qty*.002)*100)/100;return{mode:'own',vehicle:available,distanceKm:km,quantity:qty,cost:operating,pickupDelayHours:.15,estimatedDriveHours:Math.max(.25,km/55)};}
export function customerDeliveryEconomics(company,order,{quantity=null,urgent=false}={}){const qty=Math.max(1,Number(quantity??order?.amount??order?.quantity)||1),distanceKm=customerDistanceKm(order),external=externalFreightQuote({distanceKm,quantity:qty,urgent}),own=ownFleetQuote(company,{distanceKm,quantity:qty}),unitPrice=Math.max(0,Number(order?.unitPrice??order?.pricePerUnit??order?.price)||0),productId=order?.productId||order?.product||order?.itemId,costPerUnit=Math.max(0,Number(company?.costAccounting?.productCosts?.[productId]?.costPerUnit)||0),revenue=unitPrice*qty,productionCost=costPerUnit*qty,externalProfit=revenue-productionCost-external.cost,ownProfit=own?revenue-productionCost-own.cost:null;return{quantity:qty,distanceKm,revenue,productionCost,costPerUnit,external,own,externalProfit,externalMarginPercent:revenue>0?externalProfit/revenue*100:0,ownProfit,ownMarginPercent:own&&revenue>0?ownProfit/revenue*100:null,savingWithOwnFleet:own?Math.max(0,external.cost-own.cost):0};}
export function minimumProfitableCustomerPrice(company,{productId,amount=1,distanceKm=20,targetMarginPercent=12,urgent=false}={}){const qty=Math.max(1,Number(amount)||1),cost=Math.max(0,Number(company?.costAccounting?.productCosts?.[productId]?.costPerUnit)||0),freight=externalFreightQuote({distanceKm,quantity:qty,urgent}).cost,margin=clamp(Number(targetMarginPercent)||12,5,35)/100;return Math.round(((cost+freight/qty)/(1-margin))*100)/100;}
export function runCustomerFreightEconomyTest(){const c={vehicles:[],costAccounting:{productCosts:{x:{costPerUnit:.55}}}},o={id:'rewe',productId:'x',amount:500,unitPrice:1,distanceKm:20},e=customerDeliveryEconomics(c,o);if(e.external.cost<6||e.external.cost>40||e.externalProfit<=0||e.own!==null)throw new Error('Fremdspedition falsch balanciert');c.vehicles=[{id:'truck1',status:'available'}];const withTruck=customerDeliveryEconomics(c,o);if(!withTruck.own||withTruck.own.cost>=withTruck.external.cost||withTruck.savingWithOwnFleet<=0)throw new Error('Eigener Fuhrpark bietet keinen Kostenvorteil');return true;}
if(typeof window!=='undefined')window.worldCustomerFreight={quote:externalFreightQuote,economics:customerDeliveryEconomics,minimumPrice:minimumProfitableCustomerPrice,test:runCustomerFreightEconomyTest};
