// WorldProject - UI-Brücke für bestehende Kundenauftragserfüllung.
// Nutzt ausschließlich EconomyDashboard + ConnectedEconomyGameplay.deliverCustomerOrder().
import { EconomyDashboard } from "./EconomyDashboard.js";
import { i18n } from "./InternationalizationSystem.js";

i18n.addDictionary("de",{"customer.deliverable_title":"Auslieferbare Fertigware","customer.deliver_available":"{customer}: {quantity} {product} ausliefern","customer.delivery_success":"{quantity} erfolgreich ausgeliefert und abgerechnet.","customer.delivery_failed":"Auslieferung nicht möglich: {reason}","customer.deadline":"Lieferfrist: {date}","customer.deadline_remaining":"Noch {time} bis zur Lieferfrist","customer.deadline_late":"Verspätet seit {time}","customer.late_penalty":"Verspätungsabzug: {amount} je fehlender Einheit","customer.remaining":"Noch zu liefern: {remaining} von {total}","customer.unit_price":"Preis je Einheit: {price}","customer.order_value":"Auftragswert: {value}","customer.remaining_value":"Noch offener Erlös: {value}"});
i18n.addDictionary("en",{"customer.deliverable_title":"Finished goods ready for delivery","customer.deliver_available":"Deliver {quantity} {product} to {customer}","customer.delivery_success":"{quantity} delivered and settled successfully.","customer.delivery_failed":"Delivery failed: {reason}","customer.deadline":"Delivery deadline: {date}","customer.deadline_remaining":"{time} remaining until deadline","customer.deadline_late":"Overdue by {time}","customer.late_penalty":"Late deduction: {amount} per missing unit","customer.remaining":"Still to deliver: {remaining} of {total}","customer.unit_price":"Unit price: {price}","customer.order_value":"Order value: {value}","customer.remaining_value":"Outstanding revenue: {value}"});
i18n.addDictionary("es",{"customer.deliverable_title":"Productos terminados listos para entregar","customer.deliver_available":"Entregar {quantity} {product} a {customer}","customer.delivery_success":"{quantity} entregados y liquidados correctamente.","customer.delivery_failed":"No se pudo realizar la entrega: {reason}","customer.deadline":"Fecha límite de entrega: {date}","customer.deadline_remaining":"Quedan {time} hasta la fecha límite","customer.deadline_late":"Retraso de {time}","customer.late_penalty":"Deducción por retraso: {amount} por unidad faltante","customer.remaining":"Pendiente de entrega: {remaining} de {total}","customer.unit_price":"Precio por unidad: {price}","customer.order_value":"Valor del pedido: {value}","customer.remaining_value":"Ingresos pendientes: {value}"});
i18n.addDictionary("zh",{"customer.deliverable_title":"可交付成品","customer.deliver_available":"向 {customer} 交付 {quantity} {product}","customer.delivery_success":"已成功交付并结算 {quantity}。","customer.delivery_failed":"无法交付：{reason}","customer.deadline":"交付期限：{date}","customer.deadline_remaining":"距离交付期限还有 {time}","customer.deadline_late":"已逾期 {time}","customer.late_penalty":"逾期扣款：每缺少一单位 {amount}","customer.remaining":"待交付：{remaining} / {total}","customer.unit_price":"单价：{price}","customer.order_value":"订单金额：{value}","customer.remaining_value":"待收收入：{value}"});

function finishedAvailable(dashboard,order){const state=dashboard.operationsOverview.state(),product=order?.product||order?.productId||order?.itemId;return Math.max(0,Number(state.company?.operationalSupplyState?.warehouseStock?.finished?.[product]||0));}
function validTime(value){if(value instanceof Date)return Number.isFinite(value.getTime())?value.getTime():null;const numeric=Number(value);if(Number.isFinite(numeric)&&numeric>0)return numeric;const parsed=Date.parse(value);return Number.isFinite(parsed)&&parsed>0?parsed:null;}
function duration(ms){const mins=Math.max(1,Math.ceil(Math.abs(ms)/60000)),days=Math.floor(mins/1440),hours=Math.floor((mins%1440)/60),rest=mins%60;if(days)return `${days} d ${hours} h`;if(hours)return `${hours} h ${rest} min`;return `${rest} min`;}
function deadline(order){const due=validTime(order?.dueAt??order?.deliveryDeadline??order?.deadline);if(!due)return null;const delta=due-Date.now();return{due,delta,late:delta<0,penalty:Number(order?.penaltyPerMissing??order?.latePenaltyPerUnit??0)||0};}
export function customerOrderPresentation(order={}){const total=Math.max(0,Number(order.quantity??order.amount??0)||0),delivered=Math.max(0,Number(order.delivered??order.deliveredQuantity??order.fulfilledQuantity??order.deliveredAmount??0)||0),reserved=Math.max(0,Number(order.reserved||0)||0),remaining=Math.max(0,total-delivered-reserved),unitPrice=Math.max(0,Number(order.unitPrice??order.pricePerUnit??order.price??0)||0);return{total,delivered,reserved,remaining,unitPrice,totalValue:total*unitPrice,remainingValue:remaining*unitPrice};}
async function deliverAvailable(dashboard,order,amount){const state=dashboard.operationsOverview.state(),company=state.company;if(!company||!order?.id||!(amount>0))return;const result=await dashboard.controller.deliverCustomerOrder(company,order.id,amount);if(!result?.success){alert(i18n.t("customer.delivery_failed",{reason:result?.reason||i18n.t("time.unknown")}));return;}alert(i18n.t("customer.delivery_success",{quantity:dashboard.amount(result.accepted??amount)}));const panel=dashboard.overlay?.firstElementChild;if(panel)dashboard.render(panel);}

const originalRender=EconomyDashboard.prototype.render;
EconomyDashboard.prototype.render=function(panel){
  originalRender.call(this,panel);
  if(this.company?.setupPhase&&this.company.setupPhase!=="operating")return;
  const card=this.overlay?.querySelector?.("#dashboard-customer-orders");if(!card)return;
  const orders=this.operationsOverview.openCustomerOrders(),deliverable=[];
  for(const order of orders){
    const summary=customerOrderPresentation(order),available=Math.min(summary.remaining,finishedAvailable(this,order)),info=deadline(order);
    const detail=this.small(`${i18n.t("customer.remaining",{remaining:this.amount(summary.remaining),total:this.amount(summary.total)})} · ${i18n.t("customer.unit_price",{price:`${this.money(summary.unitPrice)} €`})}`);detail.style.opacity=.92;card.append(detail);
    const valueRow=this.small(`${i18n.t("customer.order_value",{value:`${this.money(summary.totalValue)} €`})} · ${i18n.t("customer.remaining_value",{value:`${this.money(summary.remainingValue)} €`})}`);valueRow.style.opacity=.92;card.append(valueRow);
    if(info){const customer=order.customerName||order.customer?.name||order.customer||"Kunde",product=this.label(order.product||order.productId||order.itemId),date=new Intl.DateTimeFormat(i18n.locale,{dateStyle:"short",timeStyle:"short"}).format(new Date(info.due)),row=this.small(`${customer} · ${product} · ${i18n.t("customer.deadline",{date})}`);row.style.color=info.late?"#ff8a80":"#b9f6ca";card.append(row);const stateRow=this.small(i18n.t(info.late?"customer.deadline_late":"customer.deadline_remaining",{time:duration(info.delta)}));stateRow.style.color=row.style.color;card.append(stateRow);if(info.late&&info.penalty>0)card.append(this.small(i18n.t("customer.late_penalty",{amount:`${this.money(info.penalty)} €`})));
    }
    if(available>0)deliverable.push({order,available});
  }
  if(!deliverable.length)return;
  const title=this.el("div",i18n.t("customer.deliverable_title"));Object.assign(title.style,{fontWeight:700,marginTop:"12px"});card.append(title);
  for(const {order,available} of deliverable){const product=this.label(order.product||order.productId||order.itemId),customer=order.customerName||order.customer?.name||order.customer||"Kunde";card.append(this.button(i18n.t("customer.deliver_available",{customer,quantity:this.amount(available),product}),()=>deliverAvailable(this,order,available)));}
};

export function runCustomerOrderPresentationTest(){const row=customerOrderPresentation({amount:100,delivered:35,reserved:5,unitPrice:1.25});const success=row.total===100&&row.remaining===60&&row.totalValue===125&&row.remainingValue===75;if(!success)throw new Error("Kundenauftrags-Anzeige berechnet Restmenge oder Erlös falsch");return true;}
if(typeof window!=="undefined")window.runCustomerOrderPresentationTest=runCustomerOrderPresentationTest;
