// WorldProject - eigener Lkw und Premium erweitern die normale Kundenauftragsauswahl.
// Ohne Lkw: 2 regional. Mit Lkw: 2 regional + 1 fern. Mit Lkw+Premium: 3 regional + 2 fern.
import { ConnectedEconomyGameplay } from './ConnectedEconomyGameplay.js';
import { PremiumEntitlementSystem } from './PremiumEntitlementSystem.js';
import { getIndustryProfile } from './IndustryCatalog.js';
import { minimumProfitableCustomerPrice } from './CustomerFreightEconomySystem.js';
const premium=new PremiumEntitlementSystem();
const accountFor=()=>window.worldCurrentUser||window.worldAccount||window.worldPlayerAccount||{};
const hasOwnedTruck=company=>(company?.vehicles||[]).some(v=>v&&v.status!=='sold');
export function customerOrderCapacity(company,account=accountFor()){const truck=hasOwnedTruck(company),premiumActive=truck&&premium.state(account,Date.now()).active;return premiumActive?{total:5,regional:3,distant:2,truck:true,premium:true}:truck?{total:3,regional:2,distant:1,truck:true,premium:false}:{total:2,regional:2,distant:0,truck:false,premium:false};}
function productFor(company,index=0){const products=getIndustryProfile(company)?.products||[];return products[index%Math.max(1,products.length)]||'lager033_bottle';}
function regionalTemplate(company,index){const names=['Regionalmarkt','Nahversorger','Lokaler Fachhandel','Gastronomie Regional'];const distanceKm=10+((index*17+String(company?.name||'').length)%51),amount=500+((index*350)%1000),productId=productFor(company,index),base=Number(company?.salesPrices?.[productId])||.95,min=minimumProfitableCustomerPrice(company,{productId,amount,distanceKm,targetMarginPercent:12});return{customer:`${names[index%names.length]} ${index+1}`,productId,amount,unitPrice:Math.max(base,min),dueHours:72,distanceKm,routeClass:'regional'};}
function distantTemplate(company,index){const names=['Überregionaler Handelsmarkt','Großkunde Fernregion','Zentrallager Handel','Getränkegroßhandel Fern'];const distanceKm=140+((index*73+String(company?.name||'').length*3)%181),amount=1200+((index*700)%1800),productId=productFor(company,index+1),base=Number(company?.salesPrices?.[productId])||.95,min=minimumProfitableCustomerPrice(company,{productId,amount,distanceKm,targetMarginPercent:18});return{customer:`${names[index%names.length]} ${index+1}`,productId,amount,unitPrice:Math.max(base*1.10,min),dueHours:96,distanceKm,routeClass:'distant'};}
function addOrder(game,company,t){const r=game.createCustomerOrder(company,t);if(r?.success){Object.assign(r.order,{distanceKm:t.distanceKm,routeClass:t.routeClass});return r.order;}return null;}
const p=ConnectedEconomyGameplay.prototype;
if(!p.__worldCustomerOrderCapacityByFleet){p.__worldCustomerOrderCapacityByFleet=true;const old=p.ensureCustomerOrders;p.ensureCustomerOrders=function(company){this.ensureCompany(company);if(company.setupPhase&&company.setupPhase!=='operating')return[];if(company.microBusiness?.stage==='micro')return old.call(this,company);old.call(this,company);const cap=customerOrderCapacity(company),open=()=>company.customerOrders.filter(x=>x.status==='open'),byClass=kind=>open().filter(x=>(x.routeClass||'regional')===kind);let guard=0;while(byClass('regional').length<cap.regional&&open().length<cap.total&&guard++<10){const t=regionalTemplate(company,byClass('regional').length);if(company.customerOrders.some(x=>x.status==='open'&&x.customer===t.customer))break;addOrder(this,company,t);}guard=0;while(byClass('distant').length<cap.distant&&open().length<cap.total&&guard++<10){const t=distantTemplate(company,byClass('distant').length);if(company.customerOrders.some(x=>x.status==='open'&&x.customer===t.customer))break;addOrder(this,company,t);}return open();};}
export function runCustomerOrderCapacityByFleetTest(){const std={},truck={vehicles:[{id:'t1',status:'available'}]},a={premiumUntil:0};if(customerOrderCapacity(std,a).total!==2||customerOrderCapacity(truck,a).total!==3)throw new Error('Lkw-Auftragslimit fehlerhaft');const now=Date.now(),prem={premiumUntil:now+86400000};if(customerOrderCapacity(truck,prem).total!==5||customerOrderCapacity(truck,prem).distant!==2)throw new Error('Premium-Lkw-Auftragslimit fehlerhaft');return true;}
if(typeof window!=='undefined')window.worldCustomerOrderCapacity={state:customerOrderCapacity,test:runCustomerOrderCapacityByFleetTest};
