// WorldProject - eigener Lkw und Premium erweitern die normale Kundenauftragsauswahl.
// Ohne Lkw: 2 regional. Mit Lkw: 2 regional + 1 fern. Mit Lkw+Premium: 3 regional + 2 fern.
// Freie Auftragsplaetze werden sofort wieder aufgefuellt; Produktion und Logistik sind die natuerliche Begrenzung.
import { ConnectedEconomyGameplay } from './ConnectedEconomyGameplay.js';
import { PremiumEntitlementSystem } from './PremiumEntitlementSystem.js';
import { getIndustryProfile } from './IndustryCatalog.js';
import { chooseCustomerOrderProduct } from './CustomerOrderVarietyIntegration.js';
import { minimumProfitableCustomerPrice } from './CustomerFreightEconomySystem.js';
import { TruckTypes } from './TruckTypes.js';
const premium=new PremiumEntitlementSystem();
export const CUSTOMER_ORDER_REFILL_COOLDOWN_MS=0;
const accountFor=()=>window.worldCurrentUser||window.worldAccount||window.worldPlayerAccount||{};
const ownedVehicles=company=>(company?.vehicles||[]).filter(v=>v&&v.status!=='sold');
const hasOwnedTruck=company=>ownedVehicles(company).length>0;
export function customerOrderCapacity(company,account=accountFor()){const truck=hasOwnedTruck(company),premiumActive=truck&&premium.state(account,Date.now()).active;return premiumActive?{total:5,regional:3,distant:2,truck:true,premium:true}:truck?{total:3,regional:2,distant:1,truck:true,premium:false}:{total:2,regional:2,distant:0,truck:false,premium:false};}
export function customerOrderCooldown(company,account=accountFor(),now=Date.now()){return{active:false,remainingMs:0,until:0,premiumBypass:premium.state(account,now).active};}
function productFor(company,index=0){const selected=chooseCustomerOrderProduct(company,index);if(selected?.productId)return selected.productId;const products=getIndustryProfile(company)?.products||[];return products[index%Math.max(1,products.length)]||null;}
function branchKey(company){return getIndustryProfile(company)?.branchKey||'generic';}
const unitsPerPalletByBranch={brewery:720,beverage:720,bakery:300,butcher:240,carpentry:45,farm:900,mechanical:120,metal:100,plastic:160,generic:120};
function unitsPerPallet(company){return unitsPerPalletByBranch[branchKey(company)]||unitsPerPalletByBranch.generic;}
function bestTruck(company){return ownedVehicles(company).map(v=>({vehicle:v,def:v.definition||TruckTypes[v.type]})).filter(x=>x.def).sort((a,b)=>(Number(b.def.maxPallets)||0)-(Number(a.def.maxPallets)||0))[0]||null;}
export function distantLoadPlan(company,index=0){const truck=bestTruck(company),pallets=Math.max(1,Number(truck?.def?.maxPallets)||4),loadFactor=index%2===0?.92:.84,targetPallets=Math.max(1,Math.round(pallets*loadFactor)),amount=Math.max(1,Math.round(targetPallets*unitsPerPallet(company)));return{truck:truck?.vehicle||null,truckType:truck?.def?.id||null,maxPallets:pallets,targetPallets,loadFactor,amount,unitsPerPallet:unitsPerPallet(company)};}
function regionalTemplate(company,index){const names=['Regionalmarkt','Nahversorger','Lokaler Fachhandel','Gastronomie Regional','Verein & Veranstaltung'],distanceKm=8+((index*17+String(company?.name||'').length+company.customerOrders.length*7)%58),baseAmount=[180,420,720,1050,1380][(index+company.customerOrders.length)%5],amount=baseAmount+((String(company?.name||'').length*13)%90),productId=productFor(company,index);if(!productId)return null;const base=Number(company?.salesPrices?.[productId])||.95,min=minimumProfitableCustomerPrice(company,{productId,amount,distanceKm,targetMarginPercent:12}),dueHours=[36,48,60,72,84][(index+company.customerOrders.length)%5];return{customer:`${names[index%names.length]} ${index+1}`,productId,amount,unitPrice:Math.max(base,min),dueHours,distanceKm,routeClass:'regional'};}
function distantTemplate(company,index){const names=['Überregionaler Handelsmarkt','Großkunde Fernregion','Zentrallager Handel','Getränkegroßhandel Fern'],load=distantLoadPlan(company,index),distanceKm=140+((index*73+String(company?.name||'').length*3+company.customerOrders.length*11)%181),amount=load.amount,productId=productFor(company,index+1);if(!productId)return null;const base=Number(company?.salesPrices?.[productId])||.95,min=minimumProfitableCustomerPrice(company,{productId,amount,distanceKm,targetMarginPercent:18}),dueHours=[72,84,96,108][(index+company.customerOrders.length)%4];return{customer:`${names[index%names.length]} ${index+1}`,productId,amount,unitPrice:Math.max(base*1.10,min),dueHours,distanceKm,routeClass:'distant',truckLoad:load};}
function addOrder(game,company,t){if(!t?.productId)return null;const r=game.createCustomerOrder(company,t);if(r?.success){Object.assign(r.order,{distanceKm:t.distanceKm,routeClass:t.routeClass,truckLoad:t.truckLoad||null});return r.order;}return null;}
const p=ConnectedEconomyGameplay.prototype;
if(!p.__worldCustomerOrderCapacityByFleet){p.__worldCustomerOrderCapacityByFleet=true;const old=p.ensureCustomerOrders;p.ensureCustomerOrders=function(company){this.ensureCompany(company);if(company.setupPhase&&company.setupPhase!=='operating')return[];if(company.microBusiness?.stage==='micro')return old.call(this,company);const open=()=>company.customerOrders.filter(x=>x.status==='open'),cap=customerOrderCapacity(company),byClass=kind=>open().filter(x=>(x.routeClass||'regional')===kind);let guard=0;while(byClass('regional').length<cap.regional&&open().length<cap.total&&guard++<10){const t=regionalTemplate(company,byClass('regional').length);if(!t)break;if(company.customerOrders.some(x=>x.status==='open'&&x.customer===t.customer))break;addOrder(this,company,t);}guard=0;while(byClass('distant').length<cap.distant&&open().length<cap.total&&guard++<10){const t=distantTemplate(company,byClass('distant').length);if(!t)break;if(company.customerOrders.some(x=>x.status==='open'&&x.customer===t.customer))break;addOrder(this,company,t);}return open();};}
export function runCustomerOrderCapacityByFleetTest(){const now=Date.now(),std={completedCustomerOrders:[]},truck={type:'Brauerei',vehicles:[{id:'t1',type:'truck18',status:'available'}],completedCustomerOrders:[]},a={premiumUntil:0};if(customerOrderCapacity(std,a).total!==2||customerOrderCapacity(truck,a).total!==3)throw new Error('Lkw-Auftragslimit fehlerhaft');const load=distantLoadPlan(truck,0);if(load.maxPallets!==20||load.targetPallets<16||load.amount<10000)throw new Error('Fernauftrag nutzt Lkw-Kapazität nicht sinnvoll');std.completedCustomerOrders=[{completedAt:now-60000}];const cd=customerOrderCooldown(std,a,now);if(cd.active||cd.remainingMs!==0)throw new Error('Kundenauftraege duerfen keinen Cooldown mehr haben');const prem={premiumUntil:now+86400000};if(customerOrderCapacity(truck,prem).total!==5||customerOrderCapacity(truck,prem).distant!==2||customerOrderCapacity(std,prem).total!==2||customerOrderCooldown(std,prem,now).active)throw new Error('Premium-Auftragslogik fehlerhaft');const variety={type:'Brauerei',vehicles:[],customerOrders:[],salesPrices:{lager033_bottle:.95,pils033_bottle:.99}};const p1=productFor(variety,0);variety.customerOrders.push({productId:p1,status:'open'});const p2=productFor(variety,1);if(!p1||!p2||p1===p2)throw new Error('Kundenauftragsprodukte wechseln nicht trotz Alternative');return true;}
if(typeof window!=='undefined')window.worldCustomerOrderCapacity={state:customerOrderCapacity,cooldown:customerOrderCooldown,loadPlan:distantLoadPlan,test:runCustomerOrderCapacityByFleetTest};
