// WorldProject - taegliche Einnahmen, Forderungen und Kundenzahlungen fuer alle Betriebe
export const RevenueProfiles={retail:{label:"Einzelhandel",cashShare:.75,cardShare:.2,invoiceShare:.05,invoiceDays:[1,3],dailyDemandFactor:1},craft:{label:"Handwerk",cashShare:.1,cardShare:.1,invoiceShare:.8,invoiceDays:[7,30],dailyDemandFactor:.7},gastronomy:{label:"Gastronomie",cashShare:.45,cardShare:.5,invoiceShare:.05,invoiceDays:[1,7],dailyDemandFactor:1.15},manufacturing:{label:"Herstellung",cashShare:.02,cardShare:.03,invoiceShare:.95,invoiceDays:[7,30],dailyDemandFactor:.8},services:{label:"Dienstleistung",cashShare:.15,cardShare:.25,invoiceShare:.6,invoiceDays:[7,14],dailyDemandFactor:.9}};
export class DailyRevenueSettlementSystem{
 constructor({profiles=RevenueProfiles}={}){this.profiles=profiles;this.sales=[];this.receivables=[];this.payments=[];this.seq=1;}
 profile(type){return this.profiles[type]||this.profiles.manufacturing;}
 generateDailySales({company,date=Date.now(),profileType="manufacturing",baseDailyRevenue=0,demandFactor=1,qualityFactor=1,reputationFactor=1,stockFactor=1,randomFactor=1}={}){const p=this.profile(profileType),gross=Math.max(0,Number(baseDailyRevenue)*p.dailyDemandFactor*Number(demandFactor)*Number(qualityFactor)*Number(reputationFactor)*Number(stockFactor)*Number(randomFactor)),sale={id:this.seq++,companyId:company.id,date:Number(date),profileType,gross,status:"booked"};this.sales.push(sale);const immediate=gross*(p.cashShare+p.cardShare),invoice=gross*p.invoiceShare;if(immediate>0)this.payments.push({id:this.seq++,companyId:company.id,saleId:sale.id,amount:immediate,dueAt:Number(date),paidAt:Number(date),status:"paid",type:"immediate"});if(invoice>0){const [min,max]=p.invoiceDays,days=Math.round((Number(min)+Number(max))/2),r={id:this.seq++,companyId:company.id,saleId:sale.id,amount:invoice,createdAt:Number(date),dueAt:Number(date)+days*86400000,status:"open"};this.receivables.push(r);}company.money=Number(company.money||0)+immediate;return{sale,immediate,invoiced:invoice,companyMoney:company.money};}
 settleDue(now=Date.now(),companyResolver=null){const paid=[];for(const r of this.receivables.filter(x=>x.status==="open"&&x.dueAt<=Number(now))){const company=typeof companyResolver==="function"?companyResolver(r.companyId):null;if(!company)continue;company.money=Number(company.money||0)+r.amount;r.status="paid";r.paidAt=Number(now);const p={id:this.seq++,companyId:r.companyId,saleId:r.saleId,receivableId:r.id,amount:r.amount,dueAt:r.dueAt,paidAt:Number(now),status:"paid",type:"invoice"};this.payments.push(p);paid.push(p);}return paid;}
 dailySummary(companyId,date){const start=new Date(date);start.setHours(0,0,0,0);const from=start.getTime(),to=from+86400000,sales=this.sales.filter(s=>s.companyId===companyId&&s.date>=from&&s.date<to),payments=this.payments.filter(p=>p.companyId===companyId&&p.paidAt>=from&&p.paidAt<to);return{date:from,sales:sales.reduce((s,x)=>s+x.gross,0),cashIn:payments.reduce((s,x)=>s+x.amount,0),payments,openReceivables:this.receivables.filter(r=>r.companyId===companyId&&r.status==="open").reduce((s,x)=>s+x.amount,0)};}
}
export function runDailyRevenueSettlementTest(){const s=new DailyRevenueSettlementSystem(),retail={id:1,money:1000},craft={id:2,money:1000},t=Date.UTC(2026,7,12);const a=s.generateDailySales({company:retail,date:t,profileType:"retail",baseDailyRevenue:1000}),b=s.generateDailySales({company:craft,date:t,profileType:"craft",baseDailyRevenue:1000});if(!(a.immediate>b.immediate&&b.invoiced>a.invoiced))throw new Error("Branchen-Zahlungsprofil fehlerhaft");s.settleDue(t+40*86400000,id=>id===1?retail:craft);if(retail.money<=1000||craft.money<=1000||s.dailySummary(1,t).sales<=0)throw new Error("Taegliche Einnahmen/Zahlungseingaenge fehlerhaft");console.log("💶 TAEGLICHE UMSAETZE/FORDERUNGEN/KUNDENZAHLUNGEN ERFOLGREICH");return true;}
