// WorldProject - taeglicher Betriebsumsatz, Forderungen und Zahlungseingaenge
export const BusinessPaymentProfiles={retail:{immediateRate:.92,termsDays:2},gastronomy:{immediateRate:.96,termsDays:1},craft:{immediateRate:.25,termsDays:14},manufacturing:{immediateRate:.15,termsDays:14},services:{immediateRate:.55,termsDays:7}};
export class DailyBusinessCashflowSystem{
 constructor({profiles=BusinessPaymentProfiles}={}){this.profiles=profiles;this.sales=[];this.receivables=[];this.payments=[];this.seq=1;}
 recordDailySales({companyId,businessType="retail",grossSales,date=Date.now(),creditRate=null}={}){const p=this.profiles[businessType]||this.profiles.retail,gross=Math.max(0,Number(grossSales)),immediateRate=creditRate==null?p.immediateRate:1-Number(creditRate),immediate=gross*immediateRate,credit=gross-immediate,sale={id:this.seq++,companyId,businessType,grossSales:gross,immediate,credit,date};this.sales.push(sale);if(immediate>0)this.payments.push({companyId,amount:immediate,type:"daily_customer_payment",saleId:sale.id,paidAt:date});if(credit>0)this.receivables.push({id:this.seq++,companyId,saleId:sale.id,amount:credit,remaining:credit,dueAt:date+p.termsDays*86400000,status:"open"});return sale;}
 processPayments({now=Date.now(),payProbability=1,random=Math.random,onPayment=null}={}){const paid=[];for(const r of this.receivables){if(r.status!=="open"||now<r.dueAt||random()>payProbability)continue;const payment={companyId:r.companyId,amount:r.remaining,type:"receivable_payment",receivableId:r.id,paidAt:now};r.remaining=0;r.status="paid";this.payments.push(payment);paid.push(payment);if(typeof onPayment==="function")onPayment(payment);}return paid;}
 dailySummary(companyId,from,to){const sales=this.sales.filter(x=>x.companyId===companyId&&x.date>=from&&x.date<to),payments=this.payments.filter(x=>x.companyId===companyId&&x.paidAt>=from&&x.paidAt<to);return{revenue:sales.reduce((s,x)=>s+x.grossSales,0),cashIn:payments.reduce((s,x)=>s+x.amount,0),openReceivables:this.receivables.filter(x=>x.companyId===companyId&&x.status==="open").reduce((s,x)=>s+x.remaining,0)};}
}
export function runDailyBusinessCashflowTest(){const s=new DailyBusinessCashflowSystem(),day=Date.UTC(2026,7,12),sale=s.recordDailySales({companyId:1,businessType:"craft",grossSales:10000,date:day});if(sale.immediate!==2500||sale.credit!==7500)throw new Error("Tagesumsatz-Aufteilung fehlerhaft");s.processPayments({now:day+15*86400000});const x=s.dailySummary(1,day,day+20*86400000);if(x.revenue!==10000||x.cashIn!==10000)throw new Error("Zahlungseingang fehlerhaft");console.log("💳 TAGESUMSATZ/FORDERUNGEN/UEBERWEISUNGEN ERFOLGREICH");return true;}
