// WorldProject - kompakte Prioritaetshinweise im Wirtschaftsdashboard.
// Maximal drei relevante Hinweise; keine dauerhafte Aufgabenwand.
import { EconomyDashboard } from './EconomyDashboard.js';
import { activeOperationsSummary } from './ActiveOperationsOverview.js';

const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const mins=ms=>{let m=Math.max(0,Math.ceil(n(ms)/60000));return m>=1440?`${Math.floor(m/1440)} T ${Math.ceil((m%1440)/60)} Std.`:m>=60?`${Math.floor(m/60)} Std. ${m%60} Min.`:`${m} Min.`;};
function priorityHints(dashboard){
 const c=dashboard.company||{},h=[];
 if(c.setupPhase&&c.setupPhase!=='operating')h.push({level:100,icon:'🧭',text:'Betrieb ist noch nicht vollständig eingerichtet.',action:'Einrichtung öffnen',run:()=>dashboard.render?.(dashboard.overlay?.firstElementChild)});
 const deliveries=[...(c.operationalSupplyState?.orders||[]),...(c.supplierOrders||[])];
 const arrived=deliveries.filter(o=>['arrived','waiting_storage'].includes(String(o?.status||'')));if(arrived.length)h.push({level:96,icon:'📦',text:`${arrived.length} Lieferung${arrived.length===1?'':'en'} wartet${arrived.length===1?'':'n'} auf Einlagerung.`,action:'Lieferungen',run:()=>dashboard.openOperationalSupplyChain?.('deliveries')});
 const delayed=deliveries.filter(o=>String(o?.status||'')==='delayed');if(delayed.length)h.push({level:90,icon:'🚚',text:`${delayed.length} Lieferung${delayed.length===1?' ist':'en sind'} verspätet.`,action:'Verkehr / Lieferungen',run:()=>window.worldLiveTraffic?.open?.()||dashboard.openOperationalSupplyChain?.('deliveries')});
 let storage=null;try{storage=dashboard.controller?.getStorageStatus?.(c);}catch{}if(storage&&n(storage.capacity)>0&&n(storage.used)/n(storage.capacity)>=.85){const pct=Math.round(n(storage.used)/n(storage.capacity)*100);h.push({level:pct>=100?94:80,icon:'🏬',text:`Lager ist zu ${pct} % belegt.`,action:'Lager prüfen',run:()=>dashboard.jumpTo?.('dashboard-storage')});}
 const queued=(c.productionQueue||[]).filter(p=>p?.status==='queued'),running=(c.productionQueue||[]).filter(p=>p?.status==='running');if(queued.length&&!running.length)h.push({level:78,icon:'🏭',text:queued.length===1?'1 Produktionsauftrag wartet auf Start.':`${queued.length} Produktionsaufträge warten auf Start.`,action:'Produktion',run:()=>dashboard.openOperationalSupplyChain?.('production')});
 const customer=(c.customerOrders||[]).filter(o=>String(o?.status||'').toLowerCase()==='open');if(customer.length)h.push({level:65,icon:'🧾',text:customer.length===1?'1 offener Kundenauftrag im Betrieb.':`${customer.length} offene Kundenaufträge im Betrieb.`,action:'Aufträge',run:()=>dashboard.jumpTo?.('dashboard-customer-orders')});
 const active=activeOperationsSummary(c),next=active.next;if(next?.remainingMs!==null&&next?.remainingMs!==undefined&&next.remainingMs<=60*60*1000)h.push({level:55,icon:'⏱️',text:`${next.label} endet voraussichtlich in ${mins(next.remainingMs)}.`,action:'Laufende Vorgänge',run:()=>window.worldActiveOperationsUI?.open?.()});
 return h.sort((a,b)=>b.level-a.level).slice(0,3);
}
function addHints(dashboard,panel){if(!panel||panel.querySelector('[data-world-priority-hints]'))return;const hints=priorityHints(dashboard);if(!hints.length)return;const wrap=document.createElement('div');wrap.dataset.worldPriorityHints='1';Object.assign(wrap.style,{display:'grid',gap:'6px',margin:'0 0 14px'});for(const hint of hints){const row=document.createElement('div');Object.assign(row.style,{display:'flex',alignItems:'center',justifyContent:'space-between',gap:'10px',padding:'8px 10px',border:'1px solid #475569',borderRadius:'9px',background:'rgba(15,23,42,.55)',fontSize:'13px'});const text=document.createElement('span');text.textContent=`${hint.icon} ${hint.text}`;row.append(text);if(hint.run){const b=document.createElement('button');b.textContent=hint.action;Object.assign(b.style,{padding:'5px 8px',borderRadius:'7px',border:'1px solid #64748b',cursor:'pointer',fontWeight:'700',whiteSpace:'nowrap'});b.onclick=hint.run;row.append(b);}wrap.append(row);}const quick=panel.querySelector('[data-world-dashboard-quick-actions]');if(quick?.nextSibling)panel.insertBefore(wrap,quick.nextSibling);else if(quick)quick.after(wrap);else panel.prepend(wrap);}
const originalRender=EconomyDashboard.prototype.render;EconomyDashboard.prototype.render=function(panel){const r=originalRender.call(this,panel);addHints(this,panel);return r;};
export function runDashboardPriorityHintsTest(){const fake={company:{supplierOrders:[{status:'arrived'},{status:'delayed'}],productionQueue:[{status:'queued'},{status:'queued'}]},controller:{getStorageStatus:()=>({used:90,capacity:100})},openOperationalSupplyChain(){},jumpTo(){}};const hints=priorityHints(fake);if(hints.length!==3||!hints.some(x=>x.text.includes('verspätet'))||!hints.some(x=>x.text.includes('Einlagerung')))throw new Error('Prioritaetshinweise fehlen');return true;}
if(typeof window!=='undefined')window.worldDashboardPriorityHints={test:runDashboardPriorityHintsTest};
