// WorldProject – Absatzprognose aus Historie, Preis, Saison, Marke und Ereignissen.
import { brandDemandMultiplier } from './BrandReputationSystem.js';
import { effectiveEventMultipliers } from './DynamicBusinessEventSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureDemandForecast(c={}){c.demandForecast??={history:[],forecasts:[],accuracy:[]};return c.demandForecast;}
export function recordDemandObservation(c,{productId,quantity,unitPrice,region='central',at=Date.now()}={}){const s=ensureDemandForecast(c),row={productId,quantity:Math.max(0,n(quantity)),unitPrice:Math.max(0,n(unitPrice)),region,at};s.history.push(row);if(s.history.length>5000)s.history.splice(0,s.history.length-5000);return row;}
function weightedAverage(rows,now){let total=0,w=0;for(const x of rows){const age=Math.max(0,(now-x.at)/86400000),weight=Math.exp(-age/30);total+=n(x.quantity)*weight;w+=weight;}return w?total/w:0;}
export function forecastProductDemand(c,productId,{days=7,region='central',price=null,referencePrice=null,season=1,world=null,now=Date.now()}={}){const s=ensureDemandForecast(c),rows=s.history.filter(x=>x.productId===productId&&x.region===region&&now-x.at<=120*86400000),base=weightedAverage(rows,now),brand=brandDemandMultiplier(c,region),priceFactor=price&&referencePrice?Math.max(.4,Math.min(1.8,n(referencePrice)/n(price))):1,event=world?effectiveEventMultipliers(world,c).demand:1,seasonFactor=Math.max(.4,Math.min(1.8,n(season,1))),daily=Math.max(0,base*brand*priceFactor*event*seasonFactor),forecast={id:`forecast-${productId}-${now}`,productId,region,days:n(days),daily,quantity:daily*Math.max(1,n(days)),confidence:Math.min(.95,.35+rows.length/40),factors:{brand,price:priceFactor,event,season:seasonFactor},createdAt:now};s.forecasts.push(forecast);if(s.forecasts.length>1000)s.forecasts.shift();return forecast;}
export function evaluateForecast(c,forecastId,actualQuantity){const s=ensureDemandForecast(c),f=s.forecasts.find(x=>x.id===forecastId);if(!f)throw new Error('Prognose fehlt');const actual=Math.max(0,n(actualQuantity)),error=f.quantity?Math.abs(actual-f.quantity)/f.quantity:actual?1:0,row={forecastId,actual,forecast:f.quantity,error,accuracy:Math.max(0,1-error),at:Date.now()};s.accuracy.push(row);return row;}
export function demandForecastKpis(c){const s=ensureDemandForecast(c),acc=s.accuracy.slice(-50);return{observations:s.history.length,forecasts:s.forecasts.length,averageAccuracy:acc.length?acc.reduce((a,x)=>a+n(x.accuracy),0)/acc.length:null,lastForecast:s.forecasts.at(-1)||null};}
if(typeof window!=='undefined')window.worldDemandForecast={record:recordDemandObservation,forecast:forecastProductDemand,evaluate:evaluateForecast,kpis:demandForecastKpis};
