// WorldProject - dynamische Nachfrage, Tagesauftraege und Sonderauftraege
export class DemandAndOrderSystem{
 constructor({profiles={}}={}){this.profiles=profiles;this.orders=[];this.seq=1;}
 registerProduct(product,profile={}){this.profiles[product]={baseDailyDemand:10,volatility:.2,qualityWeight:.25,reputationWeight:.2,...profile};}
 demand({product,quality=1,reputation=50,regionalFactor=1,dayFactor=1,random=Math.random}={}){const p=this.profiles[product]||{baseDailyDemand:10,volatility:.2,qualityWeight:.25,reputationWeight:.2},noise=1+(random()*2-1)*p.volatility,q=1+(Number(quality)-1)*p.qualityWeight,r=1+((Number(reputation)-50)/50)*p.reputationWeight;return Math.max(0,Math.round(p.baseDailyDemand*noise*q*r*regionalFactor*dayFactor));}
 createDailyOrder({buyerId=null,sellerCompanyId=null,product,qualityMin=.8,quantity,unitPrice,dueAt,source="npc_customer",createdAt=Date.now()}={}){const o={id:this.seq++,kind:"daily",buyerId,sellerCompanyId,product,qualityMin,quantity:Number(quantity),remaining:Number(quantity),unitPrice:Number(unitPrice),dueAt,status:"open",source,createdAt};this.orders.push(o);return o;}
 createSpecialOrder(data={}){const o=this.createDailyOrder({...data});o.kind="special";return o;}
 fulfill(id,{quantity,quality,transfer=null,now=Date.now()}={}){const o=this.orders.find(x=>x.id===id&&x.status==="open");if(!o)throw new Error("Auftrag nicht offen");if(Number(quality)<o.qualityMin)throw new Error("Qualitaet reicht fuer Auftrag nicht");const q=Math.min(o.remaining,Math.max(0,Number(quantity)));if(q<=0)throw new Error("Ungueltige Liefermenge");const payment=q*o.unitPrice,result={orderId:o.id,quantity:q,quality:Number(quality),payment,at:now};if(typeof transfer==="function")transfer(result,o);o.remaining-=q;if(o.remaining<=0)o.status="fulfilled";return result;}
 expire(now=Date.now()){for(const o of this.orders)if(o.status==="open"&&o.dueAt&&now>o.dueAt)o.status="missed";return this.orders.filter(o=>o.status==="missed");}
}
export function runDemandAndOrderTest(){const s=new DemandAndOrderSystem();s.registerProduct("beer",{baseDailyDemand:100,volatility:0});if(s.demand({product:"beer",quality:1,reputation:50,random:()=>.5})!==100)throw new Error("Nachfrage-Test fehlgeschlagen");const o=s.createSpecialOrder({product:"beer",qualityMin:1,quantity:500,unitPrice:3,dueAt:999999});const r=s.fulfill(o.id,{quantity:200,quality:1.1,now:1});if(r.payment!==600||o.remaining!==300)throw new Error("Auftrags-Test fehlgeschlagen");console.log("📈 NACHFRAGE/TAGESAUFTRAEGE/SONDERAUFTRAEGE ERFOLGREICH");return true;}
