// WorldProject – kompakte sichtbare Testübersicht für die Aufbauphase.
const row=(label,value,ok=null)=>({label,value,ok});
export function collectDevelopmentHealth(){
 const all=window.worldAllIndustryEconomyHealth||{},life=all.lifecycle||window.worldAllIndustryLifecycleRegression||{},first=life.firstSale||window.worldAllIndustryFirstSaleTest||{},deep=all.deepSimulation||window.worldIndustryDeepSimulationRegression||{},core=window.worldCoreRegression||{},brew=window.worldBreweryEconomicLoopRegression||null;
 const operational=(core.results||[]).find(x=>/Operational Supply 25/i.test(x.name||''));
 const opValue=operational?`${operational.success?'25':'FEHLER'}/25`:'noch nicht verfügbar';
 const firstValue=Number.isFinite(first.passed)?`${first.passed}/${first.total||35}`:(Array.isArray(first.rows)?`${first.rows.filter(x=>x.success).length}/${first.rows.length}`:'noch nicht verfügbar');
 const lifeValue=Number.isFinite(life.passed)?`${life.passed}/${life.total||100}`:'noch nicht verfügbar';
 const deepValue=Number.isFinite(deep.passed)?`${deep.passed}/${deep.total||250}`:'noch nicht verfügbar';
 const brewValue=brew?`${brew.checks?.length||0}/${brew.checks?.length||0}`:'noch nicht verfügbar';
 return [row('Operational Supply',opValue,operational?.success??null),row('Erster Verkauf',firstValue,first.success??null),row('Industry Lifecycle',lifeValue,life.success??null),row('Deep Simulation',deepValue,deep.success??null),row('Brewery Economic Loop',brewValue,brew?.success??null)];
}
export class DevelopmentHealthPanel{
 constructor(){this.overlay=null;} open(){if(this.overlay)return;const ov=document.createElement('div');Object.assign(ov.style,{position:'fixed',inset:0,zIndex:30000,background:'rgba(0,0,0,.78)',display:'flex',alignItems:'center',justifyContent:'center',padding:'18px'});const p=document.createElement('div');Object.assign(p.style,{width:'min(650px,96vw)',background:'#111827',color:'#fff',borderRadius:'14px',padding:'18px',fontFamily:'Arial,sans-serif'});const h=document.createElement('div');Object.assign(h.style,{display:'flex',justifyContent:'space-between',alignItems:'center'});const title=document.createElement('h2');title.textContent='🧪 WorldProject Health';const close=document.createElement('button');close.textContent='✕';close.onclick=()=>this.close();h.append(title,close);p.append(h);for(const r of collectDevelopmentHealth()){const x=document.createElement('div');Object.assign(x.style,{display:'flex',justifyContent:'space-between',gap:'12px',padding:'10px',margin:'5px 0',borderRadius:'8px',background:r.ok===true?'rgba(22,101,52,.5)':r.ok===false?'rgba(127,29,29,.55)':'rgba(71,85,105,.55)'});x.append(Object.assign(document.createElement('strong'),{textContent:r.label}),Object.assign(document.createElement('span'),{textContent:r.value}));p.append(x);}const note=document.createElement('div');note.textContent='Grau bedeutet: Testwert ist in dieser Browser-Sitzung noch nicht verfügbar. Es wird nichts künstlich als bestanden angezeigt.';note.style.fontSize='12px';note.style.opacity='.8';note.style.marginTop='10px';p.append(note);ov.append(p);document.body.append(ov);this.overlay=ov;}close(){this.overlay?.remove();this.overlay=null;}}
if(typeof window!=='undefined'){window.worldDevelopmentHealthPanel=window.worldDevelopmentHealthPanel||new DevelopmentHealthPanel();window.openWorldDevelopmentHealth=()=>window.worldDevelopmentHealthPanel.open();}
export function runDevelopmentHealthPanelTest(){const rows=collectDevelopmentHealth();if(rows.length!==5||!rows.some(x=>x.label==='Deep Simulation'))throw new Error('Health-Panel sammelt Referenztests nicht korrekt');return true;}
