// WorldProject – dynamische Welt-/Branchenereignisse mit realen Effekten.
import { getIndustryProfile } from './IndustryCatalog.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const EventCatalog={energy_spike:{label:'Energiepreissprung',scope:'world',days:14,effects:{energy:1.35}},supplier_disruption:{label:'Lieferkettenstörung',scope:'industry',days:10,effects:{leadTime:1.5,material:1.12}},demand_boom:{label:'Nachfrageboom',scope:'industry',days:21,effects:{demand:1.3}},recession:{label:'Rezession',scope:'world',days:45,effects:{demand:.78,credit:1.15}},labor_shortage:{label:'Fachkräftemangel',scope:'industry',days:30,effects:{labor:1.15,productivity:.9}},quality_scare:{label:'Branchenweiter Qualitätsvorfall',scope:'industry',days:12,effects:{demand:.85,qualityRequirement:1.12}},harvest_good:{label:'Sehr gute Ernte',scope:'farm',days:45,effects:{material:.82,demand:.95}},harvest_bad:{label:'Schlechte Ernte',scope:'farm',days:45,effects:{material:1.35,demand:1.05}}};
export function ensureBusinessEvents(world={}){world.businessEvents??={active:[],history:[]};return world.businessEvents;}
export function startBusinessEvent(world,eventId,{branchKey=null,severity=1,now=Date.now()}={}){const s=ensureBusinessEvents(world),d=EventCatalog[eventId];if(!d)throw new Error('Ereignis unbekannt');const row={id:`event-${eventId}-${now}`,eventId,label:d.label,scope:d.scope,branchKey,severity:clamp(n(severity,1),.25,2),startsAt:now,endsAt:now+n(d.days)*86400000,status:'active',effects:d.effects};s.active.push(row);return row;}
export function resolveExpiredBusinessEvents(world,{now=Date.now()}={}){const s=ensureBusinessEvents(world),done=s.active.filter(x=>x.endsAt<=now);for(const e of done){e.status='ended';s.history.push(e);}s.active=s.active.filter(x=>x.endsAt>now);return done;}
export function eventMultipliers(world,company){const s=ensureBusinessEvents(world),key=company?.branchKey||getIndustryProfile(company).branchKey,out={demand:1,energy:1,material:1,labor:1,leadTime:1,credit:1,productivity:1,qualityRequirement:1};for(const e of s.active){if(e.scope==='industry'&&e.branchKey&&e.branchKey!==key)continue;if(e.scope==='farm'&&!['farm','orchard','livestock'].includes(key))continue;for(const[k,v]of Object.entries(e.effects||{}))out[k]*=1+(n(v,1)-1)*e.severity;}return out;}
export function mitigateBusinessEvent(company,event,{action='buffer_stock',cost=5000}={}){if(n(company.money)<n(cost))throw new Error('Nicht genug Geld für Gegenmaßnahme');company.money-=n(cost);company.eventMitigations??=[];const row={eventId:event.id,action,cost:n(cost),effectReduction:action==='buffer_stock'?.35:action==='overtime'?.25:action==='hedge'?.4:.2,at:Date.now()};company.eventMitigations.push(row);return row;}
export function effectiveEventMultipliers(world,company){const m=eventMultipliers(world,company),active=ensureBusinessEvents(world).active,mit=company.eventMitigations||[];for(const x of mit){const e=active.find(a=>a.id===x.eventId);if(!e)continue;const r=clamp(n(x.effectReduction),0,.8);for(const[k,v]of Object.entries(e.effects||{})){const raw=1+(n(v,1)-1)*e.severity;m[k]=m[k]/raw*(1+(raw-1)*(1-r));}}return m;}
if(typeof window!=='undefined')window.worldBusinessEvents={catalog:EventCatalog,start:startBusinessEvent,expire:resolveExpiredBusinessEvents,multipliers:effectiveEventMultipliers,mitigate:mitigateBusinessEvent};
