// WorldProject – lokale Betriebs-/Modultelemetrie für Diagnose und Balancing.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureTelemetry(c={}){c.telemetry??={events:[],snapshots:[],errors:[],counters:{}};return c.telemetry;}
export function recordTelemetryEvent(c,{module='core',type='event',severity='info',data={},at=Date.now()}={}){const t=ensureTelemetry(c),row={id:`telemetry-${at}-${Math.random().toString(36).slice(2,6)}`,module,type,severity,data,at};t.events.push(row);t.counters[`${module}:${type}`]=n(t.counters[`${module}:${type}`])+1;if(severity==='error')t.errors.push(row);if(t.events.length>5000)t.events.splice(0,t.events.length-5000);if(t.errors.length>1000)t.errors.splice(0,t.errors.length-1000);return row;}
export function captureEconomySnapshot(c,{at=Date.now()}={}){const t=ensureTelemetry(c),snap={at,money:n(c.money),inventoryValue:Object.values(c.inventoryValue||{}).reduce((s,x)=>s+n(x),0),employees:(c.employees||[]).length,machines:(c.buildingState?.equipment||[]).length,runningJobs:(c.productionJobs||[]).filter(x=>x.status==='running').length,finishedJobs:(c.productionJobs||[]).filter(x=>x.status==='done').length,openOrders:(c.customerOrders||[]).filter(x=>!['done','completed','cancelled'].includes(x.status)).length,revenue:(c.salesLedger||[]).reduce((s,x)=>s+n(x.revenue),0),costs:(c.costLedger||[]).reduce((s,x)=>s+n(x.amount??x.cost),0),notifications:(c.notifications?.items||[]).length};t.snapshots.push(snap);if(t.snapshots.length>1000)t.snapshots.shift();return snap;}
export function moduleHealth(c){const t=ensureTelemetry(c),recentErrors=t.errors.filter(x=>Date.now()-x.at<24*3600000),byModule={};for(const e of recentErrors){byModule[e.module]??={errors:0,last:null};byModule[e.module].errors++;byModule[e.module].last=e;}return{healthy:recentErrors.length===0,recentErrors:recentErrors.length,modules:byModule,counters:{...t.counters},lastSnapshot:t.snapshots.at(-1)||null};}
export function detectEconomyAnomalies(c){const s=c.telemetry?.snapshots||[],out=[];if(s.length>=2){const a=s.at(-2),b=s.at(-1);if(b.money<a.money*.5&&a.money>1000)out.push({severity:'warning',code:'cash_drop',detail:`Liquidität fiel von ${Math.round(a.money)} auf ${Math.round(b.money)}`});if(b.revenue<a.revenue&&b.revenue>0)out.push({severity:'warning',code:'revenue_counter_regressed',detail:'Umsatzcounter ist rückwärts gelaufen'});if(b.runningJobs>1000)out.push({severity:'critical',code:'job_explosion',detail:`${b.runningJobs} laufende Jobs`});}for(const[k,v]of Object.entries(c.inventory||{}))if(n(v)<0)out.push({severity:'critical',code:'negative_inventory',detail:`${k}: ${v}`});return out;}
export function telemetryReport(c){return{health:moduleHealth(c),anomalies:detectEconomyAnomalies(c),latest:c.telemetry?.snapshots?.at(-1)||captureEconomySnapshot(c),errors:(c.telemetry?.errors||[]).slice(-20)}}
if(typeof window!=='undefined')window.worldEconomyTelemetry={record:recordTelemetryEvent,snapshot:captureEconomySnapshot,health:moduleHealth,anomalies:detectEconomyAnomalies,report:telemetryReport};
