// WorldProject - Personalabwesenheiten und Vertretungsvorschlaege
export class EmployeeAbsenceSystem{
 constructor({workforce=null,tempAgency=null}={}){this.workforce=workforce;this.tempAgency=tempAgency;this.absences=[];this.seq=1;}
 add({employeeId,type,startAt,endAt,reason=""}={}){if(!["training","vacation","sickness"].includes(type))throw new Error("Unbekannte Abwesenheitsart");const a={id:this.seq++,employeeId,type,startAt:Number(startAt),endAt:Number(endAt),reason,active:true};this.absences.push(a);return a;}
 isAbsent(employeeId,at=Date.now()){return this.absences.find(a=>a.active&&a.employeeId===employeeId&&Number(at)>=a.startAt&&Number(at)<=a.endAt)||null;}
 availableEmployees({skill=null,excludeEmployeeId=null,at=Date.now()}={}){if(!this.workforce)return[];return this.workforce.employees.filter(e=>e.active&&e.id!==excludeEmployeeId&&!this.isAbsent(e.id,at)&&(!skill||this.workforce.employeeSkills(e).includes(skill)));}
 suggestReplacement({employeeId,skill=null,at=Date.now()}={}){const own=this.availableEmployees({skill,excludeEmployeeId:employeeId,at});if(own.length)return {type:"own",employee:own.sort((a,b)=>Number(b.qualification||1)-Number(a.qualification||1))[0]};const offers=this.tempAgency?.offers?.filter?.(o=>!skill||(o.skills||[]).includes(skill))||[];if(offers.length)return {type:"temp",offer:offers.sort((a,b)=>Number(a.hourlyRate||0)-Number(b.hourlyRate||0))[0]};return {type:"none",reason:"Keine passende Vertretung verfuegbar"};}
 productionCheck({employeeId,skill,at=Date.now()}={}){const absence=this.isAbsent(employeeId,at);if(!absence)return {ok:true};const replacement=this.suggestReplacement({employeeId,skill,at});return {ok:false,reason:`Mitarbeiter fehlt: ${absence.type}`,absence,replacement};}
}
export function runEmployeeAbsenceTest(){const wf={employees:[{id:1,active:true,qualification:1},{id:2,active:true,qualification:1.4}],employeeSkills:e=>e.id===2?["machine"]:["machine"]},s=new EmployeeAbsenceSystem({workforce:wf}),now=Date.now();s.add({employeeId:1,type:"sickness",startAt:now-1000,endAt:now+86400000});const r=s.productionCheck({employeeId:1,skill:"machine",at:now});if(r.ok||r.replacement.type!=="own"||r.replacement.employee.id!==2)throw new Error("Abwesenheits-/Vertretungstest fehlgeschlagen");console.log("✅ PERSONALABWESENHEIT/VERTRTETUNGSTEST ERFOLGREICH");return true;}
