// WorldProject - Mitarbeiter umsetzen und schrittweise schulen
export class EmployeeWorkAssignmentSystem{
 constructor(){this.assignments=[];this.training=[];this.seq=1;}
 assign({employeeId,workstationId,requiredSkill=null,employeeSkills=[]}={}){if(requiredSkill&&!employeeSkills.includes(requiredSkill))throw new Error("Mitarbeiter ist fuer diesen Arbeitsplatz nicht qualifiziert");const current=this.assignments.find(a=>a.employeeId===employeeId&&a.active);if(current)current.active=false;const a={id:this.seq++,employeeId,workstationId,requiredSkill,active:true,assignedAt:Date.now()};this.assignments.push(a);return a;}
 startTraining({employeeId,skill,weeks=4,dayOfWeek=2,costPerDay=250,startAt=Date.now()}={}){const t={id:this.seq++,employeeId,skill,weeks:Number(weeks),dayOfWeek:Number(dayOfWeek),costPerDay:Number(costPerDay),startAt:Number(startAt),completedDays:0,status:"active",progress:0};this.training.push(t);return t;}
 trainingDay(t,at=Date.now()){const d=new Date(at);return t.status==="active"&&d.getUTCDay()===t.dayOfWeek&&at>=t.startAt&&t.completedDays<t.weeks;}
 attend({trainingId,company,employee,at=Date.now()}={}){const t=this.training.find(x=>x.id===trainingId&&x.status==="active");if(!t)throw new Error("Schulung nicht aktiv");if(!this.trainingDay(t,at))throw new Error("Heute ist kein Schulungstag");if(Number(company?.money||0)<t.costPerDay)throw new Error("Nicht genug Betriebsgeld fuer Schulung");company.money-=t.costPerDay;t.completedDays++;t.progress=t.completedDays/t.weeks;employee.skills=employee.skills||{};employee.skills[t.skill]=Math.min(2,Number(employee.skills[t.skill]||1)+.05);employee.unavailableUntil=at+24*3600000;if(t.completedDays>=t.weeks)t.status="completed";return{training:t,employee};}
 isUnavailable(employee,at=Date.now()){return Number(employee?.unavailableUntil||0)>at;}
}
export function runEmployeeWorkAssignmentTest(){const s=new EmployeeWorkAssignmentSystem(),e={id:1,skills:{machine:1}},c={money:5000};s.assign({employeeId:1,workstationId:"A",requiredSkill:"machine",employeeSkills:["machine"]});const t=s.startTraining({employeeId:1,skill:"machine",weeks:4,dayOfWeek:2,startAt:Date.UTC(2026,7,11)});s.attend({trainingId:t.id,company:c,employee:e,at:Date.UTC(2026,7,11)});if(t.completedDays!==1||e.skills.machine<=1||!s.isUnavailable(e,Date.UTC(2026,7,11)+1000))throw new Error("Mitarbeiter-/Schulungstest fehlgeschlagen");console.log("👷 MITARBEITERUMSETZUNG + SCHRITTWEISE SCHULUNG ERFOLGREICH");return true;}
