// WorldProject – universeller Personalregel-/Payroll-Kern für alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const EmploymentTypes={full_time:{hoursWeek:40,leaveDays:24,employerCostRate:.22,noticeDays:28},part_time:{hoursWeek:20,leaveDays:24,employerCostRate:.22,noticeDays:28},temporary:{hoursWeek:40,leaveDays:20,employerCostRate:.18,noticeDays:14},mini:{hoursWeek:10,leaveDays:20,employerCostRate:.16,noticeDays:14}};
export function ensureEmployment(c={}){c.employment??={contracts:[],leaveRequests:[],payrollRuns:[]};c.employees??=[];return c.employment;}
export function createEmploymentContract(c,employee,{type='full_time',monthlyGross=3000,probationDays=180,startAt=Date.now()}={}){const e=ensureEmployment(c),def=EmploymentTypes[type];if(!def)throw new Error('Unbekannte Vertragsart');const id=employee.id||employee.employeeId,row={id:`contract-${id}-${startAt}`,employeeId:id,type,monthlyGross:Math.max(0,n(monthlyGross)),hoursWeek:def.hoursWeek,leaveDays:def.leaveDays,leaveTaken:0,probationUntil:startAt+Math.max(0,n(probationDays))*86400000,noticeDays:def.noticeDays,employerCostRate:def.employerCostRate,startAt,status:'active',overtimeHours:0,sickDays:0};e.contracts.push(row);employee.contractId=row.id;employee.wageMonthly=row.monthlyGross;return row;}
export function requestLeave(c,employeeId,{days=1,from=Date.now()}={}){const e=ensureEmployment(c),contract=e.contracts.find(x=>x.employeeId===employeeId&&x.status==='active');if(!contract)throw new Error('Arbeitsvertrag fehlt');const q=Math.max(1,n(days));if(contract.leaveTaken+q>contract.leaveDays)throw new Error('Urlaubsanspruch reicht nicht');const row={id:`leave-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,employeeId,days:q,from,to:from+(q-1)*86400000,status:'approved'};contract.leaveTaken+=q;e.leaveRequests.push(row);return row;}
export function recordSickDay(c,employeeId,days=1){const e=ensureEmployment(c),contract=e.contracts.find(x=>x.employeeId===employeeId&&x.status==='active');if(!contract)throw new Error('Arbeitsvertrag fehlt');contract.sickDays+=Math.max(0,n(days));return contract;}
export function recordOvertime(c,employeeId,hours,{premium=.25}={}){const e=ensureEmployment(c),contract=e.contracts.find(x=>x.employeeId===employeeId&&x.status==='active');if(!contract)throw new Error('Arbeitsvertrag fehlt');contract.overtimeHours+=Math.max(0,n(hours));contract.overtimePremium=clamp(n(premium,.25),0,2);return contract;}
export function payrollCost(contract){const hourly=n(contract.monthlyGross)/(Math.max(1,n(contract.hoursWeek))*4.33),ot=n(contract.overtimeHours)*hourly*(1+n(contract.overtimePremium,.25)),gross=n(contract.monthlyGross)+ot,employer=gross*n(contract.employerCostRate,.22);return{gross,overtime:ot,employerCost:employer,total:gross+employer};}
export function runPayroll(c,{now=Date.now()}={}){const e=ensureEmployment(c),rows=e.contracts.filter(x=>x.status==='active').map(x=>({contractId:x.id,employeeId:x.employeeId,...payrollCost(x)})),total=rows.reduce((s,x)=>s+x.total,0);if(n(c.money)<total)throw new Error('Liquidität reicht nicht für Lohnlauf');c.money-=total;c.costLedger??=[];c.costLedger.push({kind:'payroll',amount:total,at:now});for(const x of e.contracts)x.overtimeHours=0;const run={id:`payroll-${now}`,at:now,total,rows};e.payrollRuns.push(run);return run;}
export function employmentKpis(c){const e=ensureEmployment(c),active=e.contracts.filter(x=>x.status==='active');return{contracts:active.length,monthlyEmployerCost:active.reduce((s,x)=>s+payrollCost(x).total,0),leaveOpen:active.reduce((s,x)=>s+Math.max(0,n(x.leaveDays)-n(x.leaveTaken)),0),sickDays:active.reduce((s,x)=>s+n(x.sickDays),0)};}
