// WorldProject - Arbeitsvertraege und Urlaubsanspruch (keine Krankheitsmechanik)
export class EmploymentContractVacationSystem{
 constructor({minimumAdvanceDays=14}={}){this.contracts=[];this.vacations=[];this.seq=1;this.minimumAdvanceDays=minimumAdvanceDays;}
 createContract({companyId,employeeId,jobTitle,startAt=Date.now(),weeklyHours=40,salary=0,vacationDaysPerYear=24,noticeDays=28}={}){if(!companyId||!employeeId)throw new Error("Betrieb und Mitarbeiter erforderlich");if(Number(vacationDaysPerYear)<0)throw new Error("Urlaubstage ungueltig");const c={id:this.seq++,companyId,employeeId,jobTitle,startAt,weeklyHours:Number(weeklyHours),salary:Number(salary),vacationDaysPerYear:Number(vacationDaysPerYear),noticeDays:Number(noticeDays),status:"active",createdAt:Date.now()};this.contracts.push(c);return c;}
 contractFor(employeeId){return this.contracts.find(c=>c.employeeId===employeeId&&c.status==="active")||null;}
 usedDays(employeeId,year){return this.vacations.filter(v=>v.employeeId===employeeId&&["approved","taken"].includes(v.status)&&v.year===year).reduce((s,v)=>s+v.days,0);}
 reservedDays(employeeId,year){return this.vacations.filter(v=>v.employeeId===employeeId&&v.status==="requested"&&v.year===year).reduce((s,v)=>s+v.days,0);}
 entitlement(employeeId,year=new Date().getFullYear()){const c=this.contractFor(employeeId);if(!c)throw new Error("Kein aktiver Arbeitsvertrag");const used=this.usedDays(employeeId,year),reserved=this.reservedDays(employeeId,year);return{granted:c.vacationDaysPerYear,used,reserved,remaining:Math.max(0,c.vacationDaysPerYear-used-reserved)};}
 requestVacation({employeeId,startAt,endAt,requestedAt=Date.now()}={}){const c=this.contractFor(employeeId);if(!c)throw new Error("Kein aktiver Arbeitsvertrag");const start=new Date(startAt),end=new Date(endAt);if(end<start)throw new Error("Urlaubszeitraum ungueltig");const advanceMs=Number(start)-Number(new Date(requestedAt)),minimumMs=this.minimumAdvanceDays*86400000;if(advanceMs<minimumMs)throw new Error(`Urlaub muss mindestens ${this.minimumAdvanceDays} Tage vorher beantragt werden`);let days=0,d=new Date(start);while(d<=end){const wd=d.getDay();if(wd!==0&&wd!==6)days++;d.setDate(d.getDate()+1);}const year=start.getFullYear(),e=this.entitlement(employeeId,year);if(days>e.remaining)throw new Error(`Nicht genug Urlaubstage. Verfuegbar: ${e.remaining}`);const v={id:this.seq++,contractId:c.id,companyId:c.companyId,employeeId,startAt:Number(start),endAt:Number(end),year,days,status:"requested",requestedAt:Number(new Date(requestedAt)),createdAt:Date.now()};this.vacations.push(v);return v;}
 approveVacation(id,{approvedAt=Date.now()}={}){const v=this.vacations.find(x=>x.id===id&&x.status==="requested");if(!v)throw new Error("Urlaubsantrag nicht offen");v.status="approved";v.approvedAt=approvedAt;return v;}
 rejectVacation(id,{reason="betriebliche Gruende",rejectedAt=Date.now()}={}){const v=this.vacations.find(x=>x.id===id&&x.status==="requested");if(!v)throw new Error("Urlaubsantrag nicht offen");v.status="rejected";v.reason=reason;v.rejectedAt=rejectedAt;return v;}
 isAvailable(employeeId,at=Date.now()){return !this.vacations.some(v=>v.employeeId===employeeId&&v.status==="approved"&&at>=v.startAt&&at<=v.endAt);}
 pendingRequests(companyId){return this.vacations.filter(v=>v.companyId===companyId&&v.status==="requested").sort((a,b)=>a.startAt-b.startAt);}
 contractSummary(employeeId,year=new Date().getFullYear()){const c=this.contractFor(employeeId);if(!c)return null;return{...c,vacation:this.entitlement(employeeId,year),vacationNotice:`Urlaubsanspruch: ${c.vacationDaysPerYear} Tage pro Jahr. Urlaub muss mindestens ${this.minimumAdvanceDays} Tage vorher beantragt und genehmigt werden.`};}
}
export function runEmploymentContractVacationTest(){const s=new EmploymentContractVacationSystem({minimumAdvanceDays:14});s.createContract({companyId:1,employeeId:10,jobTitle:"Brauer",vacationDaysPerYear:24});const requestedAt=Date.UTC(2026,7,1),v=s.requestVacation({employeeId:10,startAt:"2026-08-17",endAt:"2026-08-21",requestedAt});if(v.status!=="requested"||s.isAvailable(10,Date.UTC(2026,7,18))!==true)throw new Error("Urlaub darf vor Genehmigung nicht blockieren");s.approveVacation(v.id,{approvedAt:Date.UTC(2026,7,2)});const e=s.entitlement(10,2026);if(e.used!==5||e.remaining!==19||s.isAvailable(10,Date.UTC(2026,7,18))!==false)throw new Error("Urlaubsfreigabe fehlerhaft");let blocked=false;try{s.requestVacation({employeeId:10,startAt:"2026-08-10",endAt:"2026-08-11",requestedAt:Date.UTC(2026,7,5)});}catch{blocked=true;}if(!blocked)throw new Error("Kurzfristiger Urlaub wurde faelschlich akzeptiert");console.log("🏖️ URLAUBSANTRAG/VORLAUF/GENEHMIGUNG ERFOLGREICH");return true;}
