// WorldProject - Personalabwesenheiten, Vertretung und direkte Zeitarbeit
export class EmployeeAbsenceSystem{
 constructor({workforce=null,tempAgency=null}={}){this.workforce=workforce;this.tempAgency=tempAgency;this.absences=[];this.seq=1;}
 add({employeeId,type,startAt,endAt,reason=""}={}){if(!["training","vacation","sickness"].includes(type))throw new Error("Unbekannte Abwesenheitsart");const a={id:this.seq++,employeeId,type,startAt:Number(startAt),endAt:Number(endAt),reason,active:true};this.absences.push(a);return a;}
 isAbsent(employeeId,at=Date.now()){return this.absences.find(a=>a.active&&a.employeeId===employeeId&&Number(at)>=a.startAt&&Number(at)<=a.endAt)||null;}
 availableEmployees({skill=null,excludeEmployeeId=null,at=Date.now()}={}){return(this.workforce?.employees||[]).filter(e=>e.active&&e.id!==excludeEmployeeId&&!this.isAbsent(e.id,at)&&(!skill||this.workforce.employeeSkills(e).includes(skill)));}
 tempOffers({industry,date=new Date(),skill=null}={}){if(!this.tempAgency?.offers)return[];return this.tempAgency.offers({industry,date}).filter(o=>!skill||(o.skills||[]).includes(skill));}
 suggestReplacement({employeeId,skill=null,at=Date.now(),industry="*"}={}){const own=this.availableEmployees({skill,excludeEmployeeId:employeeId,at});if(own.length)return{type:"own",employee:own.sort((a,b)=>Number(b.qualification||1)-Number(a.qualification||1))[0]};const offers=this.tempOffers({industry,date:new Date(at),skill});if(offers.length)return{type:"temp",offer:offers.sort((a,b)=>Number(a.totalDailyCost||0)-Number(b.totalDailyCost||0))[0]};return{type:"none",reason:"Keine passende Vertretung verfuegbar"};}
 bookSuggestedTemp({employeeId,skill,industry,date=new Date(),shiftId="early",machineId=null,company=null}={}){const s=this.suggestReplacement({employeeId,skill,at:new Date(date).getTime(),industry});if(s.type!=="temp")throw new Error("Keine passende Zeitarbeitskraft vorgeschlagen");const hire=this.tempAgency.hire({roleId:s.offer.id,industry,date,shiftId,machineId});if(company){if(Number(company.money||0)<hire.cost){hire.active=false;throw new Error("Nicht genug Betriebsgeld fuer Zeitarbeit");}company.money-=hire.cost;}return hire;}
 productionCheck({employeeId,skill,at=Date.now(),industry="*"}={}){const absence=this.isAbsent(employeeId,at);if(!absence)return{ok:true};return{ok:false,reason:`Mitarbeiter fehlt: ${absence.type}`,absence,replacement:this.suggestReplacement({employeeId,skill,at,industry})};}
}
export function runEmployeeAbsenceTest(){const wf={employees:[{id:1,active:true,qualification:1},{id:2,active:true,qualification:1.4}],employeeSkills:()=>["machine"]},s=new EmployeeAbsenceSystem({workforce:wf}),now=Date.now();s.add({employeeId:1,type:"sickness",startAt:now-1000,endAt:now+86400000});const r=s.productionCheck({employeeId:1,skill:"machine",at:now});if(r.ok||r.replacement.type!=="own"||r.replacement.employee.id!==2)throw new Error("Abwesenheits-/Vertretungstest fehlgeschlagen");console.log("✅ PERSONALABWESENHEIT/VERTRETUNG/ZEITARBEITS-TEST ERFOLGREICH");return true;}
