// WorldProject - Arbeitsvertraege und Urlaubsanspruch (keine Krankheitsmechanik)
export class EmploymentContractVacationSystem{
 constructor(){this.contracts=[];this.vacations=[];this.seq=1;}
 createContract({companyId,employeeId,jobTitle,startAt=Date.now(),weeklyHours=40,salary=0,vacationDaysPerYear=24,noticeDays=28}={}){if(!companyId||!employeeId)throw new Error("Betrieb und Mitarbeiter erforderlich");if(Number(vacationDaysPerYear)<0)throw new Error("Urlaubstage ungueltig");const c={id:this.seq++,companyId,employeeId,jobTitle,startAt,weeklyHours:Number(weeklyHours),salary:Number(salary),vacationDaysPerYear:Number(vacationDaysPerYear),noticeDays:Number(noticeDays),status:"active",createdAt:Date.now()};this.contracts.push(c);return c;}
 contractFor(employeeId){return this.contracts.find(c=>c.employeeId===employeeId&&c.status==="active")||null;}
 usedDays(employeeId,year){return this.vacations.filter(v=>v.employeeId===employeeId&&v.status!=="cancelled"&&v.year===year).reduce((s,v)=>s+v.days,0);}
 entitlement(employeeId,year=new Date().getFullYear()){const c=this.contractFor(employeeId);if(!c)throw new Error("Kein aktiver Arbeitsvertrag");const used=this.usedDays(employeeId,year);return{granted:c.vacationDaysPerYear,used,remaining:Math.max(0,c.vacationDaysPerYear-used)};}
 requestVacation({employeeId,startAt,endAt}={}){const c=this.contractFor(employeeId);if(!c)throw new Error("Kein aktiver Arbeitsvertrag");const start=new Date(startAt),end=new Date(endAt);if(end<start)throw new Error("Urlaubszeitraum ungueltig");let days=0,d=new Date(start);while(d<=end){const wd=d.getDay();if(wd!==0&&wd!==6)days++;d.setDate(d.getDate()+1);}const year=start.getFullYear(),e=this.entitlement(employeeId,year);if(days>e.remaining)throw new Error(`Nicht genug Urlaubstage. Verfuegbar: ${e.remaining}`);const v={id:this.seq++,contractId:c.id,companyId:c.companyId,employeeId,startAt:Number(start),endAt:Number(end),year,days,status:"approved",createdAt:Date.now()};this.vacations.push(v);return v;}
 isAvailable(employeeId,at=Date.now()){return !this.vacations.some(v=>v.employeeId===employeeId&&v.status==="approved"&&at>=v.startAt&&at<=v.endAt);}
 contractSummary(employeeId,year=new Date().getFullYear()){const c=this.contractFor(employeeId);if(!c)return null;return{...c,vacation:this.entitlement(employeeId,year),vacationNotice:`Urlaubsanspruch: ${c.vacationDaysPerYear} Tage pro Jahr`};}
}
export function runEmploymentContractVacationTest(){const s=new EmploymentContractVacationSystem(),c=s.createContract({companyId:1,employeeId:10,jobTitle:"Brauer",vacationDaysPerYear:24});if(!s.contractSummary(10,2026).vacationNotice.includes("24"))throw new Error("Urlaubshinweis fehlt");s.requestVacation({employeeId:10,startAt:"2026-08-17",endAt:"2026-08-21"});const e=s.entitlement(10,2026);if(e.used!==5||e.remaining!==19)throw new Error("Urlaubsberechnung fehlerhaft");console.log("🏖️ ARBEITSVERTRAG + URLAUBSANSPRUCH ERFOLGREICH");return true;}
