// WorldProject – Maschinenansicht für bestehende UI.
import { equipmentSetupVM,equipmentForMachineRequirement,buyIndustryEquipment,persistIndustryEquipment } from './IndustryEquipmentMarketplace.js';
import { maintenanceKpis,maintenanceDue,breakdownRisk } from './IndustryMaintenanceEngine.js';
import { industryRecipes } from './UniversalIndustryCycle.js';
import { formatMoney } from './CurrencyPresentationBridge.js';
const priced=x=>({...x,priceFormatted:Number.isFinite(Number(x?.price))?formatMoney(Number(x.price)):null,costFormatted:Number.isFinite(Number(x?.cost))?formatMoney(Number(x.cost)):null});
export function equipmentPanelState(company){const setup=equipmentSetupVM(company),recipes=industryRecipes(company),owned=company.buildingState?.equipment||[];return{setup:{...setup,missingRequired:(setup.missingRequired||[]).map(priced),optional:(setup.optional||[]).map(priced)},maintenance:maintenanceKpis(company),owned:owned.map(m=>({machine:m,due:maintenanceDue(company,m),breakdownRisk:breakdownRisk(m),recipes:recipes.filter(r=>equipmentForMachineRequirement(company,r.machineType).some(x=>x.id===m.id)).map(r=>r.id)})),missingRequired:setup.missingRequired.map(x=>({...priced(x),action:'buy'})),optional:setup.optional.map(x=>({...priced(x),action:x.owned?null:'buy'})),canBuyRequired:setup.missingRequired.some(x=>x.affordable)};}
export async function buyFromEquipmentPanel(company,equipmentId){const result=buyIndustryEquipment(company,equipmentId,{requestId:`equipment-panel-${equipmentId}-${Date.now()}`});await persistIndustryEquipment(company).catch(()=>null);if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason:'equipment-panel-purchase',equipmentId}}));return result;}
if(typeof window!=='undefined')window.worldEquipmentPanel={state:equipmentPanelState,buy:buyFromEquipmentPanel};
