// WorldProject – Smokecheck ausschließlich für die offenen Reststellen des exklusiven 1000ers.
import { operationalStockAmount } from './OperationalInventoryBridge.js';
import { procurementPanelState } from './ProcurementPanelController.js';
import { fleetPanelState } from './FleetPanelController.js';
import { salesPanelState } from './SalesPanelController.js';
import { equipmentSetupVM } from './IndustryEquipmentMarketplace.js';
import { contextualPlayerActions } from './ContextualPlayerActions.js';
import { companyOperationalHealth } from './SystemOperationsMonitor.js';
import { releaseReadiness } from './ReleaseReadinessSystem.js';
export function runExclusiveLeftovers1000Health(company=window.worldPlayerCompany){const checks=[];const add=(name,success,detail=null)=>checks.push({name,success:!!success,detail});if(!company)return{success:false,total:1,passed:0,failed:[{name:'Aktiver Betrieb',success:false}]};try{add('Operativer Lagerzugriff',operationalStockAmount(company,'malt')!==undefined);}catch(e){add('Operativer Lagerzugriff',false,e.message);}try{const p=procurementPanelState(company);add('Einkaufsmodell',Array.isArray(p.suggestions)&&typeof p.canOrder==='boolean');}catch(e){add('Einkaufsmodell',false,e.message);}try{const f=fleetPanelState(company);add('Liefermodell',Array.isArray(f.deliveries)&&Number.isFinite(f.awaitingReceipt));}catch(e){add('Liefermodell',false,e.message);}try{const s=salesPanelState(company);add('CustomerLifecycle-Vertrieb',Array.isArray(s.orders)&&!!s.kpis);}catch(e){add('CustomerLifecycle-Vertrieb',false,e.message);}try{const e=equipmentSetupVM(company);add('Maschinenquelle',Array.isArray(e.missingRequired)&&Array.isArray(e.owned));}catch(err){add('Maschinenquelle',false,err.message);}try{add('Kontextaktionen',Array.isArray(contextualPlayerActions(company)));}catch(e){add('Kontextaktionen',false,e.message);}try{const h=companyOperationalHealth(company);add('Systemmonitor',typeof h.healthy==='boolean'&&Number.isFinite(h.missingEquipment)&&Number.isFinite(h.missingSpecialists));}catch(e){add('Systemmonitor',false,e.message);}try{const gate=releaseReadiness({}, {company});add('Release-Gate',typeof gate.go==='boolean'&&Array.isArray(gate.operationalBlockers));}catch(e){add('Release-Gate',false,e.message);}const failed=checks.filter(x=>!x.success);return{success:!failed.length,total:checks.length,passed:checks.length-failed.length,failed,checks,ranAt:Date.now()};}
if(typeof window!=='undefined')window.runExclusiveLeftovers1000Health=runExclusiveLeftovers1000Health;
