// WorldProject - erweiterte Regression fuer Transport, Lager, Produktion und Kundenauftraege.
import "../content/ContentBootstrap.js";
import { SupplyOrderSystem, WarehouseSystem, ProductionPlanner } from "./OperationalSupplyChainSystem.js";
import { purchaseSupplyOrder, receiveSupplyOrder } from "./OperationalSupplyTransactions.js";
import { runTransportOrderWorkflowTest } from "./TransportOrderWorkflow.js";
import { runFleetTripAccountingTest } from "./FleetTripAccounting.js";
import { runWarehouseHealthTest } from "./WarehouseHealthSystem.js";
import { runProductionSafetyTest } from "./ProductionSafetySystem.js";
import { fulfillCustomerOrder, restoreCustomerOrder } from "./CustomerOrderSafetySystem.js";
import { worldContentRegistry } from "./ContentRegistry.js";

function assert(v,m){if(!v)throw new Error(m);}
function runCustomerSafetyTest(){const company={money:0,finishedGoods:{pils:100},financialLog:[],completedCustomerOrders:[]},order={id:1,productId:"pils",amount:80,delivered:0,unitPrice:1.2,status:"open"};const first=fulfillCustomerOrder({company,order,quantity:30,requestId:"d1",now:1000}),dup=fulfillCustomerOrder({company,order,quantity:30,requestId:"d1",now:1001});assert(first.success&&dup.deduplicated&&order.delivered===30&&company.finishedGoods.pils===70,"Kunden-Deduplizierung fehlerhaft");const second=fulfillCustomerOrder({company,order,quantity:100,requestId:"d2",now:2000});assert(second.accepted===50&&second.completed&&order.delivered===80&&company.finishedGoods.pils===20,"Kunden-Teillieferung/Überlieferung fehlerhaft");const restored=restoreCustomerOrder(JSON.parse(JSON.stringify(order)));assert(restored.status==="completed","Kundenauftrag Reload fehlerhaft");return{success:true};}

function runBreweryEndToEnd(){const supplier=worldContentRegistry.get("suppliers","brew_malt_regional");assert(supplier,"Malzlieferant fehlt");const company={id:"e2e",branchKey:"brewery",money:100000,finishedGoods:{},financialLog:[]},orders=new SupplyOrderSystem(),warehouse=new WarehouseSystem({raw:5000,packaging:5000,finished:5000,cold:5000});const bought=purchaseSupplyOrder({orders,company,supplier,material:"malt",quantity:500,requestId:"e2e-buy",now:1000});assert(bought.success&&company.money<100000,"Einkauf fehlgeschlagen");orders.advance(bought.order.eta);const received=receiveSupplyOrder({warehouse,order:bought.order,now:bought.order.eta});assert(received.success&&warehouse.stock.raw.malt===500,"Wareneingang fehlgeschlagen");warehouse.stock.raw.water=1000;warehouse.stock.raw.hops=10;warehouse.stock.cold.yeast=10;warehouse.stock.packaging.bottles=1000;warehouse.stock.packaging.caps=1000;warehouse.stock.packaging.labels=1000;const machines=[{id:1,type:"brewhouse",status:"available",busy:false,capacity:1000},{id:2,type:"filling_line",status:"available",busy:false,capacity:1200}],planner=new ProductionPlanner({warehouse,machines}),brew={id:"e2e_brew",product:"beer_bulk_pils",materials:{malt:50,hops:.5,yeast:.25,water:300},machineType:"brewhouse",durationMinutes:60,output:330};const brewJob=planner.startForOutput(brew,330,2000);planner.advance(brewJob.finishAt);assert(warehouse.stock.finished.beer_bulk_pils===330,"Brauen erzeugt keine Bulkware");const fill={id:"e2e_fill",product:"pils033_bottle",materials:{beer_bulk_pils:330,bottles:1000,caps:1000,labels:1000},machineType:"filling_line",durationMinutes:60,output:1000,productionStage:"bottling",bottleSizeLiters:.33};const fillJob=planner.startForOutput(fill,1000,brewJob.finishAt+1);planner.advance(fillJob.finishAt);assert(warehouse.stock.finished.pils033_bottle===1000,"Abfüllung erzeugt keine Flaschen");company.finishedGoods.pils033_bottle=warehouse.stock.finished.pils033_bottle;const customer={id:"cust",productId:"pils033_bottle",amount:600,delivered:0,unitPrice:1.1,status:"open"},delivery=fulfillCustomerOrder({company,order:customer,quantity:600,requestId:"e2e-customer",now:fillJob.finishAt+2});assert(delivery.success&&delivery.completed&&company.money>0&&company.finishedGoods.pils033_bottle===400,"Kundenlieferung fehlgeschlagen");const snapshot=JSON.parse(JSON.stringify({company,orders:orders.orders,stock:warehouse.stock,queue:planner.queue,customer}));assert(snapshot.orders[0].status==="stored"&&snapshot.stock.finished.pils033_bottle===1000&&snapshot.customer.status==="completed","E2E Reload-Snapshot fehlerhaft");return{success:true};}

function runLegacyCompatibility(){const legacy={inventory:{malt_kg:100,hops_kg:2,yeast_kg:1,water_l:500,bottle_033:500,crown_cap:500,label_033:500},supplierOrders:[{id:"old-1",itemId:"malt_kg",amount:50,status:"delivered"}]};const converted={malt:legacy.inventory.malt_kg,hops:legacy.inventory.hops_kg,yeast:legacy.inventory.yeast_kg,water:legacy.inventory.water_l,bottles:legacy.inventory.bottle_033,caps:legacy.inventory.crown_cap,labels:legacy.inventory.label_033};assert(converted.malt===100&&converted.bottles===500&&legacy.supplierOrders[0].status==="delivered","Legacy-Kompatibilität fehlerhaft");return{success:true};}

export function runExtendedCoreRegression(){const tests=[
 ["Transport workflow",runTransportOrderWorkflowTest],
 ["Fleet accounting",runFleetTripAccountingTest],
 ["Warehouse health",runWarehouseHealthTest],
 ["Production safety",()=>runProductionSafetyTest({ProductionPlanner,WarehouseSystem})],
 ["Customer safety",runCustomerSafetyTest],
 ["Brewery E2E",runBreweryEndToEnd],
 ["Legacy compatibility",runLegacyCompatibility]
],results=[];for(const[name,fn]of tests){try{const value=fn();results.push({name,success:value===true||value?.success===true});}catch(error){results.push({name,success:false,error:error?.message||String(error)});}}const failed=results.filter(x=>!x.success);console[failed.length?"error":"log"](failed.length?"❌ EXTENDED-CORE-REGRESSION FEHLER":"✅ EXTENDED-CORE-REGRESSION ALLES GRUEN",{passed:results.length-failed.length,total:results.length,failed,results});return{success:failed.length===0,results,failed};}
