// Finanzplanung: Fälligkeiten, Schulden, Steuerreserve und Abschlüsse.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureFinancePlanning(c={}){c.financePlanning??={obligations:[],closings:[],tax:{rate:.3,reserve:0},history:[]};return c.financePlanning;}
export function addFinancialObligation(c,{kind='loan',amount,dueAt,interest=0,reference=null}={}){const f=ensureFinancePlanning(c),row={id:`obl-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,kind,amount:Math.max(0,n(amount)),interest:Math.max(0,n(interest)),dueAt:n(dueAt,Date.now()),reference,status:'open'};f.obligations.push(row);return row;}
export function dueObligations(c,{until=Date.now()}={}){return ensureFinancePlanning(c).obligations.filter(x=>x.status==='open'&&x.dueAt<=until).sort((a,b)=>a.dueAt-b.dueAt);}
export function payFinancialObligation(c,id){const f=ensureFinancePlanning(c),o=f.obligations.find(x=>x.id===id);if(!o)throw new Error('Finanzverpflichtung fehlt');if(o.status==='paid')return{success:true,idempotent:true};const total=o.amount+o.interest;if(n(c.money)<total)throw new Error('Liquiditaet reicht nicht');c.money-=total;o.status='paid';o.paidAt=Date.now();f.history.push({kind:'payment',obligationId:id,amount:total,at:o.paidAt});return{success:true,total};}
export function reserveTax(c,{profit,rate=null}={}){const f=ensureFinancePlanning(c),r=rate==null?n(f.tax.rate,.3):Math.max(0,n(rate));const reserve=Math.max(0,n(profit)*r);f.tax.reserve=Math.max(f.tax.reserve,reserve);return f.tax.reserve;}
export function financeForecast(c,{days=90,now=Date.now()}={}){const f=ensureFinancePlanning(c),until=now+Math.max(1,n(days))*86400000,outgoing=f.obligations.filter(x=>x.status==='open'&&x.dueAt<=until).reduce((s,x)=>s+x.amount+x.interest,0),incoming=(c.finance?.receivables||[]).filter(x=>x.status==='open'&&x.dueAt<=until).reduce((s,x)=>s+n(x.amount),0);return{cash:n(c.money),incoming,outgoing,taxReserve:n(f.tax.reserve),forecast:n(c.money)+incoming-outgoing-n(f.tax.reserve),days};}
export function closeFinancialPeriod(c,{period='month',from=0,to=Date.now()}={}){const f=ensureFinancePlanning(c),revenue=(c.salesLedger||[]).filter(x=>n(x.at)>=from&&n(x.at)<=to).reduce((s,x)=>s+n(x.revenue??x.amount),0),cost=(c.costLedger||[]).filter(x=>n(x.at)>=from&&n(x.at)<=to).reduce((s,x)=>s+n(x.cost??x.amount),0),profit=revenue-cost,tax=reserveTax(c,{profit}),row={id:`closing-${period}-${to}`,period,from,to,revenue,cost,profit,taxReserve:tax,cash:n(c.money),createdAt:Date.now()};f.closings.push(row);return row;}
export function financePlanningKpis(c){const f=ensureFinancePlanning(c),forecast=financeForecast(c);return{openObligations:f.obligations.filter(x=>x.status==='open').length,debt:f.obligations.filter(x=>x.status==='open').reduce((s,x)=>s+x.amount+x.interest,0),taxReserve:f.tax.reserve,forecast:forecast.forecast,closings:f.closings.length};}
