// Fuhrparknetz, Fahrerzeiten und Kostenoptimierung.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureFleetNetwork(c={}){c.fleetNetwork??={routes:[],driverLogs:[],backhauls:[],assignments:[]};c.vehicles??=[];c.employees??=[];return c.fleetNetwork;}
export function vehicleSuitability(v,{weightKg=0,volumeM3=0,pallets=0,distanceKm=0}={}){const payload=n(v.payloadKg,v.capacityKg||0),volume=n(v.volumeM3,Infinity),pal=n(v.pallets,Infinity),fuel=n(v.fuelLevelLiters,Infinity),cons=n(v.consumptionL100km,25),fuelNeed=n(distanceKm)*cons/100;const reasons=[];if(weightKg>payload)reasons.push('payload');if(volumeM3>volume)reasons.push('volume');if(pallets>pal)reasons.push('pallets');if(fuel<fuelNeed)reasons.push('fuel');if(['broken','maintenance'].includes(v.status))reasons.push('status');return{ok:!reasons.length,reasons,fuelNeed,utilization:payload?weightKg/payload:0};}
export function driverCompliance(driver,{driveMinutes=0,workMinutes=0}={}){const driven=n(driver.driveMinutesToday),worked=n(driver.workMinutesToday),driveAfter=driven+n(driveMinutes),workAfter=worked+n(workMinutes);return{ok:driveAfter<=540&&workAfter<=600,driveAfter,workAfter,remainingDrive:Math.max(0,540-driven),remainingWork:Math.max(0,600-worked)};}
export function optimizeFleetAssignment(c,job){const f=ensureFleetNetwork(c),drivers=c.employees.filter(e=>(e.skills||[]).includes('driving')||e.jobId==='driver').filter(e=>!['sick','vacation','training'].includes(e.status)),vehicles=c.vehicles||c.fleet||[];const candidates=[];for(const v of vehicles){const vs=vehicleSuitability(v,job);if(!vs.ok)continue;for(const d of drivers){const dc=driverCompliance(d,{driveMinutes:n(job.distanceKm)/70*60,workMinutes:n(job.distanceKm)/70*60+n(job.serviceMinutes)});if(!dc.ok)continue;const cost=n(job.distanceKm)*n(v.costPerKm,.55)+vs.fuelNeed*n(job.fuelPrice,1.6)+n(d.hourlyCost,24)*(dc.driveAfter-n(d.driveMinutesToday))/60;candidates.push({vehicle:v,driver:d,cost,utilization:vs.utilization,fuelNeed:vs.fuelNeed});}}candidates.sort((a,b)=>a.cost-b.cost||b.utilization-a.utilization);return candidates[0]||null;}
export function assignFleetJob(c,job){const f=ensureFleetNetwork(c),best=optimizeFleetAssignment(c,job);if(!best)throw new Error('Kein geeignetes Fahrzeug/Fahrer verfuegbar');const row={id:`fleet-${Date.now()}`,jobId:job.id,vehicleId:best.vehicle.id||best.vehicle.instanceId,driverId:best.driver.id,cost:best.cost,fuelNeed:best.fuelNeed,status:'assigned',createdAt:Date.now()};f.assignments.push(row);best.vehicle.status='reserved';best.driver.status='assigned';return row;}
export function registerBackhaul(c,{routeId,from,to,weightKg,revenue=0}={}){const f=ensureFleetNetwork(c),b={id:`back-${Date.now()}`,routeId,from,to,weightKg:Math.max(0,n(weightKg)),revenue:Math.max(0,n(revenue)),status:'planned'};f.backhauls.push(b);return b;}
export function completeFleetAssignment(c,id,{distanceKm=0,driveMinutes=0}={}){const f=ensureFleetNetwork(c),a=f.assignments.find(x=>x.id===id);if(!a)throw new Error('Fuhrparkauftrag fehlt');a.status='done';a.completedAt=Date.now();const v=(c.vehicles||c.fleet||[]).find(x=>(x.id||x.instanceId)===a.vehicleId),d=c.employees.find(x=>x.id===a.driverId);if(v){v.status='available';v.mileageKm=n(v.mileageKm)+n(distanceKm);}if(d){d.status='available';d.driveMinutesToday=n(d.driveMinutesToday)+n(driveMinutes);d.workMinutesToday=n(d.workMinutesToday)+n(driveMinutes);}return a;}
export function fleetNetworkKpis(c){const f=ensureFleetNetwork(c);return{assignments:f.assignments.length,running:f.assignments.filter(x=>x.status==='assigned').length,backhauls:f.backhauls.length,totalCost:f.assignments.reduce((s,x)=>s+n(x.cost),0)};}
