// WorldProject – einheitliche, nicht-blockierende Rueckmeldung fuer Spieleraktionen.
const MAX_VISIBLE=4;
function ensureHost(){let h=document.querySelector('[data-world-action-feedback]');if(h)return h;h=document.createElement('div');h.dataset.worldActionFeedback='1';Object.assign(h.style,{position:'fixed',right:'16px',bottom:'16px',zIndex:65000,display:'flex',flexDirection:'column',gap:'8px',maxWidth:'360px',pointerEvents:'none'});document.body.append(h);return h;}
function palette(type){if(type==='error')return{bg:'#7f1d1d',icon:'❌'};if(type==='warning')return{bg:'#78350f',icon:'⚠️'};if(type==='info')return{bg:'#1e3a8a',icon:'ℹ️'};return{bg:'#14532d',icon:'✅'};}
export function showActionFeedback(message,{type='success',title='',duration=3200}={}){if(typeof document==='undefined'||!message)return null;const h=ensureHost(),p=palette(type),box=document.createElement('div');Object.assign(box.style,{background:p.bg,color:'#fff',padding:'10px 12px',borderRadius:'10px',boxShadow:'0 6px 20px rgba(0,0,0,.35)',fontSize:'13px',lineHeight:'1.4',pointerEvents:'auto'});box.innerHTML=`<b>${p.icon}${title?` ${title}`:''}</b>${title?'<br>':' '}${String(message)}`;h.prepend(box);while(h.children.length>MAX_VISIBLE)h.lastElementChild?.remove();const remove=()=>box.remove();box.onclick=remove;setTimeout(remove,Math.max(1200,Number(duration)||3200));return box;}
export function installActionFeedback(){if(typeof window==='undefined')return false;window.addEventListener('world:action-feedback',e=>showActionFeedback(e.detail?.message||'',e.detail||{}));return true;}
export function feedback(message,options={}){if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('world:action-feedback',{detail:{message,...options}}));}
export function runActionFeedbackTest(){return palette('success').icon==='✅'&&palette('error').icon==='❌';}
if(typeof window!=='undefined'){window.worldActionFeedback={show:showActionFeedback,feedback,install:installActionFeedback,runTest:runActionFeedbackTest};installActionFeedback();}
