// WorldProject – prozedural erzeugte externe Bautrupp-Angebote.
// Kein LLM-Aufruf im Spiel nötig: deterministische Generierung aus Zeitfenster und Firmen-ID.
import { ensureWarehouseExpansion } from './WarehouseConstructionExpansionSystem.js';
const first=['Bau','Projekt','Montage','Industriebau','Hochbau','Werk','BauService','BauTeam'];
const second=['Nord','West','Mitte','Regional','Partner','Profi','Direkt','Express','Konzept','Werk'];
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function hash(s){let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function rng(seed){let x=seed>>>0;return()=>{x=(Math.imul(x,1664525)+1013904223)>>>0;return x/4294967296;};}
export function crewMarketWindow(now=Date.now()){return Math.floor(Number(now)/(60*60*1000));}
export function generatedCrewOffers(company={},now=Date.now(),count=6){const windowId=crewMarketWindow(now),seed=hash(`${company.id||company.serverCompanyId||company.name||'company'}:${windowId}`),r=rng(seed),rows=[];for(let i=0;i<count;i++){const workers=3+Math.floor(r()*14),speed=Number((.82+r()*.95).toFixed(2)),reliability=Number((.84+r()*.155).toFixed(3)),travel=8+Math.floor(r()*48),base=850+workers*255,scarcity=.88+r()*.42,daily=Math.round(base*scarcity*(.85+speed*.28));rows.push({id:`ai-crew-${windowId}-${i}`,label:`${first[Math.floor(r()*first.length)]} ${second[Math.floor(r()*second.length)]} ${100+Math.floor(r()*900)}`,workers,dailyCost:daily,speedFactor:speed,reliability,availabilityMinutes:travel,generated:true,marketWindow:windowId});}return rows.sort((a,b)=>a.dailyCost-b.dailyCost);}
export function bestCrewOffer(company,preference='balanced',now=Date.now()){const offers=generatedCrewOffers(company,now);if(preference==='cheap')return offers[0];if(preference==='fast')return [...offers].sort((a,b)=>b.speedFactor-a.speedFactor)[0];if(preference==='reliable')return [...offers].sort((a,b)=>b.reliability-a.reliability)[0];return [...offers].sort((a,b)=>(b.speedFactor*b.reliability/b.dailyCost)-(a.speedFactor*a.reliability/a.dailyCost))[0];}
export function createCrewBookingFromOffer(offer,now=Date.now()){if(!offer)throw new Error('Bautrupp-Angebot fehlt');return{id:`crew-booking-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,crewId:offer.id,label:offer.label,workers:n(offer.workers),dailyCost:n(offer.dailyCost),speedFactor:n(offer.speedFactor,1),reliability:n(offer.reliability,1),bookedAt:Number(now),availableAt:Number(now)+n(offer.availabilityMinutes)*60000,status:'booked',generated:true,marketWindow:offer.marketWindow};}
export function bookGeneratedCrew(company,offer,{now=Date.now()}={}){ensureWarehouseExpansion(company);const active=company.warehouseExpansion.crewBookings.filter(x=>['booked','assigned'].includes(x.status));if(active.some(x=>x.crewId===offer?.id))throw new Error('Dieser Bautrupp ist bereits gebucht');if(active.length>=5)throw new Error('Maximal 5 Bautrupps können gleichzeitig gebucht oder eingesetzt werden');const booking=createCrewBookingFromOffer(offer,now);company.warehouseExpansion.crewBookings.push(booking);return booking;}
export function runGeneratedConstructionCrewMarketTest(){const c={id:1},a=generatedCrewOffers(c,0),b=generatedCrewOffers(c,0);if(a.length!==6||JSON.stringify(a)!==JSON.stringify(b)||a.some(x=>x.dailyCost<=0||x.workers<3||x.speedFactor<=0))throw new Error('Bautrupp-Markt nicht reproduzierbar');const company={warehouseExpansion:{level:0,extraSlots:0,jobs:[],crewBookings:[]},constructionSite:{materials:{},jobs:[],deliveries:[]}};const booking=bookGeneratedCrew(company,a[0],{now:0});bookGeneratedCrew(company,a[1],{now:0});if(!booking.generated||company.warehouseExpansion.crewBookings.length!==2)throw new Error('Mehrere generierte Bautrupps nicht buchbar');return true;}
if(typeof window!=='undefined')window.worldGeneratedConstructionCrews={offers:generatedCrewOffers,best:bestCrewOffer,book:bookGeneratedCrew,runTest:runGeneratedConstructionCrewMarketTest};
