// WorldProject – Startseite: Kundenaufträge, laufende Zeiten und Produktion statt leerer Weltkarte.
import { worldContentRegistry } from './ContentRegistry.js';
import { OperationalSupplyChainDialog } from './OperationalSupplyChainDialog.js';
import { applyFocus } from './OperationalDialogSectionPersistenceIntegration.js';
import { activeOperationsSummary } from './ActiveOperationsOverview.js';
import { AdvancedEconomySystem } from './AdvancedEconomySystem.js';

const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const customerEconomy=new AdvancedEconomySystem();
const activeCompany=()=>window.worldPlayerCompany||window.worldActiveServerCompany||window.worldEngine?.company||null;
function fallbackProductLabel(id){const raw=String(id||'Ware');const fixed={lager033_bottle:'Lagerbier 0,33 l',pils033_bottle:'Pils 0,33 l',lager050_bottle:'Lagerbier 0,50 l',pils050_bottle:'Pils 0,50 l'};if(fixed[raw])return fixed[raw];return raw.replace(/lager/gi,'Lagerbier ').replace(/pils/gi,'Pils ').replace(/033/g,'0,33 l').replace(/050/g,'0,50 l').replace(/_?bottle/gi,' Flasche').replace(/_/g,' ').replace(/\s+/g,' ').trim();}
const productLabel=id=>worldContentRegistry.get('products',id)?.label||worldContentRegistry.get('materials',id)?.label||fallbackProductLabel(id);
const money=v=>`${n(v).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})} €`;
const statusLabel=s=>({open:'Offen',partial:'Teilweise geliefert',running:'In Produktion',queued:'Geplant',finished:'Fertig',paused:'Pausiert',in_transit:'Unterwegs',upgrading:'Im Ausbau'}[String(s||'').toLowerCase()]||String(s||'Offen'));
const kindLabel={production:'🏭 Produktion',delivery:'🚚 Lieferung',construction:'🏗️ Bau/Ausbau',land:'🌍 Grundstück',warehouse_expansion:'🏬 Lagerausbau',machine_upgrade:'🔧 Maschinenupgrade',business_upgrade:'⚙️ Betriebsausbau'};
function remaining(order={}){return Math.max(0,n(order.quantity??order.amount)-n(order.delivered??order.deliveredQuantity??order.fulfilledQuantity));}
function orderProduct(order={}){return order.productId||order.product||order.itemId||order.outputId||'';}
function dueText(order={}){const raw=order.dueAt??order.deliveryDeadline??order.deadline;if(!raw)return'Keine feste Frist';const ms=Number(raw)||Date.parse(raw);if(!Number.isFinite(ms))return'Keine feste Frist';const diff=ms-Date.now(),m=Math.ceil(Math.abs(diff)/60000),h=Math.floor(m/60),rest=m%60;return diff<0?`⚠️ ${h?h+' Std. ':''}${rest} Min. überfällig`:`Noch ${h?h+' Std. ':''}${rest} Min.`;}
function durationText(ms){if(ms===null||ms===undefined)return'—';let min=Math.max(0,Math.ceil(ms/60000));const d=Math.floor(min/1440);min%=1440;const h=Math.floor(min/60),m=min%60;return[d?`${d} T`:null,h?`${h} Std.`:null,`${m} Min.`].filter(Boolean).join(' ');}
function availableFinished(c,product){try{if(window.worldUnifiedOperationalStock?.has?.(c))return Math.max(0,n(window.worldUnifiedOperationalStock.amount(c,product,{finished:true})));}catch{}return Math.max(0,n(c?.finishedGoods?.[product]));}
async function openProduction(section='production'){
 let dialog=window.worldOperationalSupplyChainDialog;
 if(!dialog){dialog=new OperationalSupplyChainDialog({companyProvider:activeCompany,parent:document.body});window.worldOperationalSupplyChainDialog=dialog;}
 if(dialog.overlay)dialog.close();dialog.__worldFocusedSection=section;dialog.loadedCompanyId=null;await dialog.open();applyFocus(dialog,section);requestAnimationFrame(()=>applyFocus(dialog,section));
}
function openAllOperations(){if(window.worldActiveOperationsUI?.open)return window.worldActiveOperationsUI.open();}
function button(text,fn){const b=document.createElement('button');b.textContent=text;Object.assign(b.style,{padding:'9px 12px',borderRadius:'8px',border:'1px solid #475569',background:'#1e293b',color:'#fff',fontWeight:'800',cursor:'pointer'});b.onclick=fn;return b;}
function card(){const x=document.createElement('div');Object.assign(x.style,{background:'#111827',border:'1px solid #334155',borderRadius:'12px',padding:'14px',boxShadow:'0 8px 24px rgba(0,0,0,.16)'});return x;}
function closeCustomerOverlay(){document.querySelector('[data-world-customer-orders-overlay]')?.remove();}
function deliverCustomerOrder(order,{rerender=renderHomeOperationsDashboard,closeAfter=false}={}){
 const c=activeCompany();if(!c||!order)return;const product=orderProduct(order),open=remaining(order),available=availableFinished(c,product),qty=Math.min(open,available);
 if(!(qty>0)){alert(`Keine lieferbare Ware vorhanden.\nBenötigt: ${open.toLocaleString('de-DE')}\nIm Fertigwarenlager: ${available.toLocaleString('de-DE')}\n\nBitte zuerst produzieren.`);return;}
 const full=qty>=open,question=full?`${open.toLocaleString('de-DE')} ${productLabel(product)} jetzt an ${order.customerName||order.customer?.name||order.customer||'den Kunden'} liefern?`:`Es sind nur ${qty.toLocaleString('de-DE')} von ${open.toLocaleString('de-DE')} verfügbar.\nDiese Teilmenge jetzt liefern?`;
 if(!confirm(question))return;
 try{
  const result=customerEconomy.deliverCustomerOrder(c,order.id,qty);if(!result?.success)throw new Error(result?.reason||'Lieferung konnte nicht gestartet werden.');
  const freight=result.freight,mode=freight?.mode==='own'?'eigener Fuhrpark':'Fremdspedition',lines=[`${Number(result.accepted||qty).toLocaleString('de-DE')} Einheiten geliefert.`];
  if(freight)lines.push(`Transport: ${mode} · ${money(freight.cost)}`);if(Number.isFinite(Number(result.revenue)))lines.push(`Umsatz: ${money(result.revenue)}`);if(Number.isFinite(Number(result.netRevenue)))lines.push(`Nach Transport: ${money(result.netRevenue)}`);if(result.completed)lines.push('✅ Auftrag vollständig erledigt.');
  window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason:'home-customer-order-delivery',orderId:order.id}}));alert(lines.join('\n'));if(closeAfter)closeCustomerOverlay();rerender();
 }catch(e){alert(e?.message||String(e));}
}
function customerOrderCard(o,{rerender=renderHomeOperationsDashboard,compact=false}={}){
 const c=activeCompany(),box=card(),urgent=Boolean(o.urgent||o.isUrgent||String(o.kind||'').includes('urgent')),product=orderProduct(o),rem=remaining(o),available=availableFinished(c,product),price=n(o.unitPrice??o.pricePerUnit??o.price),customer=o.customerName||o.customer?.name||o.customer||'Kunde';
 const title=document.createElement('div');title.innerHTML=`<b>${urgent?'⚡ Eilauftrag':'📦 Kundenauftrag'} – ${customer}</b>`;title.style.fontSize='17px';const facts=document.createElement('div');Object.assign(facts.style,{lineHeight:'1.55',marginTop:'8px',color:'#dbeafe'});facts.innerHTML=`Ware: <b>${productLabel(product)}</b><br>Menge offen: <b>${rem.toLocaleString('de-DE')}</b><br>Fertigware verfügbar: <b>${available.toLocaleString('de-DE')}</b><br>Auftragswert offen: <b>${money(rem*price)}</b><br>Lieferfrist: <b>${dueText(o)}</b><br>Status: <b>${statusLabel(o.status)}</b>`;
 const actions=document.createElement('div');Object.assign(actions.style,{display:'flex',gap:'7px',flexWrap:'wrap',marginTop:'10px'});const send=button(available>=rem&&rem>0?'🚚 Auftrag liefern':available>0?'🚚 Teilmenge liefern':'🚚 Ware fehlt',()=>deliverCustomerOrder(o,{rerender}));if(available<=0){send.disabled=true;Object.assign(send.style,{opacity:'.5',cursor:'not-allowed'});}else Object.assign(send.style,{background:'#166534',borderColor:'#22c55e'});actions.append(send,button('🏭 Produktion',()=>openProduction('production')));if(!compact)actions.append(button('📋 Betrieb im Überblick',openAllOperations));box.append(title,facts,actions);return box;
}
function openCustomers(){
 closeCustomerOverlay();const c=activeCompany(),overlay=document.createElement('div'),panel=document.createElement('section');overlay.dataset.worldCustomerOrdersOverlay='1';Object.assign(overlay.style,{position:'fixed',inset:'0',zIndex:'65000',background:'rgba(0,0,0,.72)',display:'grid',placeItems:'center',padding:'18px'});Object.assign(panel.style,{width:'min(1050px,96vw)',maxHeight:'88vh',overflow:'auto',background:'#0f172a',color:'#fff',border:'1px solid #334155',borderRadius:'14px',padding:'18px',boxShadow:'0 22px 60px rgba(0,0,0,.5)'});const head=document.createElement('div');Object.assign(head.style,{display:'flex',justifyContent:'space-between',alignItems:'center',position:'sticky',top:'-18px',zIndex:'2',background:'#0f172a',padding:'14px 0'});const h=document.createElement('h2');h.textContent='📦 Alle Kundenaufträge';h.style.margin='0';head.append(h,button('✕ Schließen',closeCustomerOverlay));panel.append(head);const orders=(c?.customerOrders||[]).filter(o=>!['completed','cancelled','delivered','closed'].includes(String(o.status||'').toLowerCase())&&remaining(o)>0);if(!orders.length){const empty=document.createElement('div');empty.textContent='Aktuell keine offenen Kundenaufträge.';empty.style.padding='18px 0';panel.append(empty);}else{const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(330px,1fr))',gap:'12px'});const rerender=()=>{closeCustomerOverlay();renderHomeOperationsDashboard();openCustomers();};for(const o of orders)grid.append(customerOrderCard(o,{rerender,compact:true}));panel.append(grid);}overlay.append(panel);overlay.onclick=e=>{if(e.target===overlay)closeCustomerOverlay();};document.body.append(overlay);const esc=e=>{if(e.key==='Escape'){closeCustomerOverlay();window.removeEventListener('keydown',esc);}};window.addEventListener('keydown',esc);
}
function renderCustomerOrders(section,c){section.innerHTML='';const head=document.createElement('div');Object.assign(head.style,{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'10px',flexWrap:'wrap'});const h=document.createElement('h2');h.textContent='📦 Kundenaufträge';h.style.margin='0';head.append(h,button('Alle Kundenaufträge öffnen',openCustomers));section.append(head);
 const orders=(c?.customerOrders||[]).filter(o=>!['completed','cancelled','delivered','closed'].includes(String(o.status||'').toLowerCase())&&remaining(o)>0);
 if(!orders.length){const empty=document.createElement('div');empty.textContent='Aktuell keine offenen Kundenaufträge.';Object.assign(empty.style,{padding:'14px 0',color:'#94a3b8'});section.append(empty);return;}
 const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(290px,1fr))',gap:'10px',marginTop:'12px'});for(const o of orders.slice(0,6))grid.append(customerOrderCard(o));section.append(grid);
}
function renderTimedOperations(section,c){section.innerHTML='';const summary=activeOperationsSummary(c||{}),rows=summary.rows.filter(r=>r.remainingMs!==null&&r.kind!=='customer_order');const head=document.createElement('div');Object.assign(head.style,{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'10px',flexWrap:'wrap'});const h=document.createElement('h2');h.textContent='⏱️ Läuft gerade';h.style.margin='0';head.append(h,button('Alle Vorgänge',openAllOperations));section.append(head);const sub=document.createElement('div');sub.textContent=rows.length?`${rows.length} zeitlich laufende Vorgänge · nächstes Ende zuerst`:'Keine zeitlich laufenden Vorgänge.';Object.assign(sub.style,{color:'#94a3b8',marginTop:'4px'});section.append(sub);if(!rows.length)return;
 const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:'10px',marginTop:'12px'});for(const r of rows.slice(0,8)){const box=card(),title=document.createElement('div'),name=productLabel(r.label);title.innerHTML=`<b>${kindLabel[r.kind]||'⏱️ Vorgang'} · ${name}</b>`;const info=document.createElement('div');Object.assign(info.style,{marginTop:'8px',lineHeight:'1.55',color:'#dbeafe'});info.innerHTML=`Status: <b>${statusLabel(r.status)}</b><br>Restzeit: <b>${durationText(r.remainingMs)}</b>${r.progress!==null?`<br>Fortschritt: <b>${r.progress}%</b>`:''}`;const bar=document.createElement('div');Object.assign(bar.style,{height:'7px',marginTop:'9px',background:'#1e293b',borderRadius:'999px',overflow:'hidden'});const fill=document.createElement('div');Object.assign(fill.style,{height:'100%',width:`${Math.max(2,r.progress??2)}%`,background:'#3b82f6'});bar.append(fill);box.append(title,info,bar);grid.append(box);}section.append(grid);
}
function renderProduction(section,c){section.innerHTML='';const head=document.createElement('div');Object.assign(head.style,{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'10px',flexWrap:'wrap'});const h=document.createElement('h2');h.textContent='🏭 Produktion';h.style.margin='0';head.append(h,button('Produktion planen',()=>openProduction('production')));section.append(head);
 const rows=[...(c?.productionJobs||[]),...(c?.productionQueue||[]),...(c?.operationalSupplyState?.productionQueue||[])].filter((j,i,a)=>!['finished','completed','cancelled'].includes(String(j.status||'').toLowerCase())&&a.findIndex(x=>String(x.id??x)===String(j.id??j))===i);if(!rows.length){const empty=document.createElement('div');empty.textContent='Zurzeit läuft keine Produktion. Du kannst sofort eine neue Charge planen.';Object.assign(empty.style,{padding:'14px 0',color:'#94a3b8'});section.append(empty,button('➕ Neue Produktion starten',()=>openProduction('production')));return;}
 const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:'10px',marginTop:'12px'});for(const j of rows.slice(0,6)){const box=card(),product=j.recipe?.label||j.product||j.recipe?.product||j.recipeId||'Produktion',qty=n(j.plan?.output??j.output??j.quantity),t=document.createElement('div');t.innerHTML=`<b>${productLabel(product)}</b>`;const f=document.createElement('div');Object.assign(f.style,{lineHeight:'1.55',marginTop:'7px',color:'#dbeafe'});f.innerHTML=`Status: <b>${statusLabel(j.status)}</b>${qty?`<br>Menge: <b>${qty.toLocaleString('de-DE')}</b>`:''}`;box.append(t,f);grid.append(box);}section.append(grid);
}
export function renderHomeOperationsDashboard(){if(typeof document==='undefined')return false;let root=document.getElementById('world-home-dashboard');if(!root){root=document.createElement('main');root.id='world-home-dashboard';document.body.append(root);}Object.assign(document.body.style,{margin:'0',background:'#020617',color:'#f8fafc',minHeight:'100vh'});Object.assign(root.style,{position:'relative',zIndex:'1',maxWidth:'1180px',margin:'0 auto',padding:'105px 18px 40px',fontFamily:'Arial,sans-serif'});root.innerHTML='';const c=activeCompany(),title=document.createElement('section');Object.assign(title.style,{marginBottom:'14px'});const h=document.createElement('h1');h.textContent=c?.name?`🏢 ${c.name}`:'🏢 Mein Betrieb';h.style.margin='0 0 4px';const sub=document.createElement('div');sub.textContent=`${c?.type||c?.industry||'Betrieb'} · Spielgeld ${money(c?.money||0)} · Coins ${n(c?.coins)}`;sub.style.color='#94a3b8';title.append(h,sub);const timed=card(),customers=card(),production=card();renderTimedOperations(timed,c);renderCustomerOrders(customers,c);renderProduction(production,c);const gap=()=>{const g=document.createElement('div');g.style.height='14px';return g;};root.append(title,timed,gap(),customers,gap(),production);return true;}
export function installHomeOperationsDashboard(){if(typeof window==='undefined')return false;const run=()=>renderHomeOperationsDashboard();for(const ev of ['worldproject:company-loaded','worldproject:company-activated','worldproject:company-switched','world:game-state-dirty','world:customer-order-updated','world:construction-completed','world:business-upgrade-started','world:business-upgrade-completed'])window.addEventListener(ev,()=>setTimeout(run,0));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();setInterval(run,15000);return true;}
if(typeof window!=='undefined'){window.worldHomeOperationsDashboard={render:renderHomeOperationsDashboard,install:installHomeOperationsDashboard,openCustomers};installHomeOperationsDashboard();}