// WorldProject – Lager direkt auf der Startseite + frei waehlbare Teillieferungen.
import { AdvancedEconomySystem } from './AdvancedEconomySystem.js';
import { OperationalSupplyChainDialog } from './OperationalSupplyChainDialog.js';
import { applyFocus } from './OperationalDialogSectionPersistenceIntegration.js';
import { worldContentRegistry } from './ContentRegistry.js';

const economy=new AdvancedEconomySystem();
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const company=()=>window.worldPlayerCompany||window.worldActiveServerCompany||window.worldEngine?.company||null;
const orderProduct=o=>o?.productId||o?.product||o?.itemId||o?.outputId||'';
const productAliases=id=>{const raw=String(id||'');const set=new Set([raw]);if(raw.endsWith('_bottle'))set.add(raw.replace(/_bottle$/,' bottle'));if(raw.endsWith(' bottle'))set.add(raw.replace(/ bottle$/,'_bottle'));if(raw==='lager033')set.add('lager033_bottle');if(raw==='lager033 bottle')set.add('lager033_bottle');if(raw==='pils033')set.add('pils033_bottle');return[...set].filter(Boolean);};
const finishedAmount=(c,id)=>{const stock=c?.operationalSupplyState?.warehouseStock?.finished||{};let best=0;for(const key of productAliases(id)){best=Math.max(best,n(stock?.[key]),n(c?.finishedGoods?.[key]));try{if(window.worldUnifiedOperationalStock?.has?.(c))best=Math.max(best,n(window.worldUnifiedOperationalStock.amount(c,key,{finished:true})));}catch{}}return Math.max(0,best);};
const cleanLabel=id=>{const raw=String(id||'Ware');const fixed={lager033_bottle:'Lagerbier 0,33 l',pils033_bottle:'Pils 0,33 l',lager050_bottle:'Lagerbier 0,50 l',pils050_bottle:'Pils 0,50 l'};return worldContentRegistry.get('products',raw)?.label||worldContentRegistry.get('materials',raw)?.label||fixed[raw]||raw.replace(/033/g,'0,33').replace(/050/g,'0,50').replace(/_?bottle/gi,' Flasche').replace(/_/g,' ').trim();};
const openQty=o=>Math.max(0,n(o?.quantity??o?.amount)-n(o?.delivered??o?.deliveredQuantity??o?.fulfilledQuantity));

async function openWarehouse(){let dialog=window.worldOperationalSupplyChainDialog;if(!dialog){dialog=new OperationalSupplyChainDialog({companyProvider:company,parent:document.body});window.worldOperationalSupplyChainDialog=dialog;}if(dialog.overlay)dialog.close();dialog.__worldFocusedSection='warehouse';dialog.loadedCompanyId=null;await dialog.open();applyFocus(dialog,'warehouse');requestAnimationFrame(()=>applyFocus(dialog,'warehouse'));}
function button(text,fn){const b=document.createElement('button');b.type='button';b.textContent=text;Object.assign(b.style,{padding:'9px 12px',borderRadius:'8px',border:'1px solid #475569',background:'#1e293b',color:'#fff',fontWeight:'800',cursor:'pointer'});b.onclick=fn;return b;}
function zoneEntries(stock,zone){return Object.entries(stock?.[zone]||{}).filter(([,v])=>n(v)>0).sort((a,b)=>n(b[1])-n(a[1]));}
function zoneBlock(title,entries){const box=document.createElement('div');Object.assign(box.style,{background:'#0f172a',border:'1px solid #334155',borderRadius:'10px',padding:'11px',minHeight:'90px'});const h=document.createElement('strong');h.textContent=title;box.append(h);if(!entries.length){const e=document.createElement('div');e.textContent='Leer';Object.assign(e.style,{marginTop:'7px',color:'#64748b'});box.append(e);return box;}for(const[id,qty]of entries.slice(0,8)){const r=document.createElement('div');Object.assign(r.style,{display:'flex',justifyContent:'space-between',gap:'10px',marginTop:'6px',color:'#dbeafe'});const l=document.createElement('span');l.textContent=cleanLabel(id);const q=document.createElement('b');q.textContent=n(qty).toLocaleString('de-DE',{maximumFractionDigits:2});r.append(l,q);box.append(r);}if(entries.length>8){const more=document.createElement('small');more.textContent=`+ ${entries.length-8} weitere`;Object.assign(more.style,{display:'block',marginTop:'7px',color:'#94a3b8'});box.append(more);}return box;}
function buildWarehouseCard(){const c=company(),wrap=document.createElement('section');wrap.dataset.worldHomeWarehouse='1';Object.assign(wrap.style,{background:'#111827',border:'1px solid #334155',borderRadius:'12px',padding:'14px',boxShadow:'0 8px 24px rgba(0,0,0,.16)'});const head=document.createElement('div');Object.assign(head.style,{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'10px',flexWrap:'wrap'});const h=document.createElement('h2');h.textContent='🏬 Lager';h.style.margin='0';head.append(h,button('Lager öffnen',openWarehouse));wrap.append(head);const stock=c?.operationalSupplyState?.warehouseStock||{raw:c?.inventory||{},packaging:{},cold:{},finished:c?.finishedGoods||{}};const raw=zoneEntries(stock,'raw'),pack=zoneEntries(stock,'packaging'),cold=zoneEntries(stock,'cold'),finished=zoneEntries(stock,'finished');const total=raw.reduce((s,[,v])=>s+n(v),0)+pack.reduce((s,[,v])=>s+n(v),0)+cold.reduce((s,[,v])=>s+n(v),0)+finished.reduce((s,[,v])=>s+n(v),0);const summary=document.createElement('div');summary.textContent=`Gesamtbestand: ${total.toLocaleString('de-DE',{maximumFractionDigits:2})} Einheiten`;Object.assign(summary.style,{color:'#94a3b8',marginTop:'4px'});wrap.append(summary);const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:'10px',marginTop:'12px'});grid.append(zoneBlock('🌾 Rohstoffe',raw),zoneBlock('📦 Verpackung',pack),zoneBlock('🧪 Zwischenprodukte / Kühlung',cold),zoneBlock('🍺 Fertigwaren',finished));wrap.append(grid);return wrap;}
function injectWarehouse(){const root=document.getElementById('world-home-dashboard');if(!root||root.querySelector('[data-world-home-warehouse]'))return false;const card=buildWarehouseCard();const sections=[...root.children];const customerIndex=sections.findIndex(x=>/Kundenaufträge/.test(x.textContent||''));if(customerIndex>=0)root.insertBefore(card,sections[customerIndex]);else root.append(card);return true;}
function deliverExact(order,qty){const c=company(),product=orderProduct(order),open=openQty(order),available=finishedAmount(c,product),amount=Math.floor(Math.min(Math.max(n(qty),0),open,available));if(!(amount>0)){alert(`Keine lieferbare Menge vorhanden.\n${cleanLabel(product)} im Fertigwarenlager: ${available.toLocaleString('de-DE')}`);return;}if(!confirm(`${amount.toLocaleString('de-DE')} ${cleanLabel(product)} jetzt liefern?`))return;try{const result=economy.deliverCustomerOrder(c,order.id,amount);if(!result?.success)throw new Error(result?.reason||'Lieferung fehlgeschlagen');window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason:'partial-customer-delivery',orderId:order.id,quantity:amount}}));alert(`${Number(result.accepted||amount).toLocaleString('de-DE')} geliefert${result.completed?' – Auftrag erledigt.':''}`);window.worldHomeOperationsDashboard?.render?.();}catch(e){alert(e?.message||String(e));}}
function customerSection(root){return [...root.children].find(el=>el.querySelector?.(':scope > div:first-child > h2')&&/Kundenaufträge/i.test(el.querySelector(':scope > div:first-child > h2')?.textContent||''))||null;}
function customerCards(section){if(!section)return[];const grid=[...section.children].find(el=>el.tagName==='DIV'&&el!==section.firstElementChild&&[...el.children].some(card=>/Kundenauftrag|Eilauftrag/.test(card.querySelector?.(':scope > div:first-child')?.textContent||'')));return grid?[...grid.children].filter(card=>/Kundenauftrag|Eilauftrag/.test(card.querySelector?.(':scope > div:first-child')?.textContent||'')):[];}
function injectPartialDeliveryControls(){const root=document.getElementById('world-home-dashboard'),c=company();if(!root||!c)return false;const orders=(c.customerOrders||[]).filter(o=>openQty(o)>0&&!['completed','cancelled','delivered','closed'].includes(String(o.status||'').toLowerCase()));const section=customerSection(root),cards=customerCards(section);if(!cards.length)return false;let changed=false;for(let i=0;i<Math.min(cards.length,orders.length);i++){const card=cards[i];if(card.querySelector('[data-world-partial-delivery]'))continue;const o=orders[i],product=orderProduct(o),max=Math.floor(Math.min(openQty(o),finishedAmount(c,product)));const actions=[...card.children].find(x=>x.querySelector?.(':scope > button'));if(!actions)continue;const box=document.createElement('div');box.dataset.worldPartialDelivery='1';Object.assign(box.style,{display:'flex',gap:'7px',alignItems:'center',flexWrap:'wrap',marginTop:'10px',padding:'9px',background:'#0b1220',border:'1px solid #334155',borderRadius:'8px'});const lab=document.createElement('span');lab.textContent='Teillieferung:';lab.style.fontWeight='700';const input=document.createElement('input');input.type='number';input.min='1';input.step='1';input.max=String(Math.max(0,max));input.value=max>0?String(max):'0';Object.assign(input.style,{width:'100px',padding:'8px',borderRadius:'7px',border:'1px solid #475569',background:'#111827',color:'#fff'});const send=button('🚚 Menge liefern',()=>deliverExact(o,input.value));if(max<=0){send.disabled=true;Object.assign(send.style,{opacity:'.5',cursor:'not-allowed'});}box.append(lab,input,document.createTextNode(` von max. ${max.toLocaleString('de-DE')}`),send);card.insertBefore(box,actions);changed=true;}return changed;}
function apply(){injectWarehouse();injectPartialDeliveryControls();}
export function installHomeWarehouseAndPartialDelivery(){if(typeof document==='undefined')return false;const run=()=>setTimeout(apply,0);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();for(const ev of ['worldproject:company-loaded','worldproject:company-switched','worldproject:company-activated','world:game-state-dirty','world:customer-order-updated'])window.addEventListener(ev,run);const observer=new MutationObserver(()=>apply());observer.observe(document.documentElement,{childList:true,subtree:true});return true;}
if(typeof window!=='undefined'){window.worldHomeWarehouseAndPartialDelivery={install:installHomeWarehouseAndPartialDelivery,openWarehouse};installHomeWarehouseAndPartialDelivery();}
