// ORVUNO – zeigt auf der Startseite den naechsten sinnvollen Schritt: abfuellen.
import { OperationalSupplyChainDialog } from './OperationalSupplyChainDialog.js';
import { applyFocus } from './OperationalDialogSectionPersistenceIntegration.js';

const n=v=>Number.isFinite(Number(v))?Number(v):0;
const company=()=>window.worldPlayerCompany||window.worldActiveServerCompany||window.worldEngine?.company||null;
const BULK_PRODUCTS={
 beer_bulk_lager:{label:'Lagerbier',target:'beer_lager_033'},
 beer_bulk_pils:{label:'Pils',target:'beer_pils_033'}
};
function bulkEntries(c){const cold=c?.operationalSupplyState?.warehouseStock?.cold||{};const finished=c?.operationalSupplyState?.warehouseStock?.finished||{};const out=[];for(const[id,meta]of Object.entries(BULK_PRODUCTS)){const qty=Math.max(n(cold[id]),n(finished[id]),n(c?.inventory?.[id]));if(qty>0)out.push({id,qty,...meta});}return out;}
function signature(entries){return entries.map(x=>`${x.id}:${x.qty}`).join('|');}
async function openBottling(){let dialog=window.worldOperationalSupplyChainDialog;if(!dialog){dialog=new OperationalSupplyChainDialog({companyProvider:company,parent:document.body});window.worldOperationalSupplyChainDialog=dialog;}if(dialog.overlay)dialog.close();dialog.__worldFocusedSection='production';dialog.loadedCompanyId=null;await dialog.open();applyFocus(dialog,'production');requestAnimationFrame(()=>{applyFocus(dialog,'production');const root=dialog.overlay||document;const candidates=[...root.querySelectorAll('button,[role="button"],h3,h4,strong,div')];const hit=candidates.find(el=>/abfüll|abfuell|bottl/i.test(el.textContent||''));hit?.scrollIntoView?.({behavior:'smooth',block:'center'});hit?.focus?.();});}
function buildCard(entries){const box=document.createElement('section');box.dataset.orvunoBottlingCta='1';box.dataset.signature=signature(entries);Object.assign(box.style,{background:'linear-gradient(135deg,#172033,#101827)',border:'1px solid #b7791f',borderRadius:'12px',padding:'14px',marginBottom:'14px',boxShadow:'0 8px 24px rgba(0,0,0,.18)'});const head=document.createElement('div');Object.assign(head.style,{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'12px',flexWrap:'wrap'});const left=document.createElement('div');const title=document.createElement('div');title.textContent='🍺 Abfüllung bereit';Object.assign(title.style,{fontSize:'19px',fontWeight:'800',color:'#fbbf24'});const lines=document.createElement('div');lines.textContent=entries.map(x=>`${x.qty.toLocaleString('de-DE',{minimumFractionDigits:0,maximumFractionDigits:2})} l ${x.label} bereit zur Abfüllung`).join(' · ');Object.assign(lines.style,{marginTop:'5px',color:'#e5e7eb'});const hint=document.createElement('div');hint.textContent='Das Getränk ist fertig, aber noch keine verkaufsfertige Flaschenware.';Object.assign(hint.style,{marginTop:'4px',fontSize:'13px',color:'#94a3b8'});left.append(title,lines,hint);const btn=document.createElement('button');btn.textContent='Jetzt abfüllen';Object.assign(btn.style,{padding:'10px 15px',borderRadius:'8px',border:'1px solid #f59e0b',background:'#92400e',color:'#fff',fontWeight:'800',cursor:'pointer'});btn.onclick=openBottling;head.append(left,btn);box.append(head);return box;}
function inject(){const root=document.getElementById('world-home-dashboard');if(!root)return false;const entries=bulkEntries(company()),existing=root.querySelector('[data-orvuno-bottling-cta]');if(!entries.length){if(existing)existing.remove();return false;}const sig=signature(entries);if(existing?.dataset.signature===sig)return true;const card=buildCard(entries);if(existing){existing.replaceWith(card);return true;}const firstSection=root.querySelector('section');if(firstSection?.nextSibling)root.insertBefore(card,firstSection.nextSibling);else root.prepend(card);return true;}
let scheduled=false;function schedule(){if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;inject();},50);}
for(const ev of ['worldproject:company-loaded','worldproject:company-switched','worldproject:company-activated','world:game-state-dirty','world:production-completed','world:customer-order-updated'])window.addEventListener(ev,schedule);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
// Absichtlich KEIN globaler MutationObserver: der CTA darf niemals durch eigene DOM-Aenderungen eine Render-Endlosschleife ausloesen.
export function runHomeBottlingCallToActionTest(){const c={operationalSupplyState:{warehouseStock:{cold:{beer_bulk_lager:99.84},finished:{}}}};const rows=bulkEntries(c);if(rows.length!==1||rows[0].qty!==99.84||rows[0].label!=='Lagerbier')throw new Error('Abfüll-Hinweis erkennt fertiges Tankprodukt nicht');return true;}
if(typeof window!=='undefined')window.worldHomeBottlingCTA={inject,open:openBottling,test:runHomeBottlingCallToActionTest};
