// WorldProject – Wareneingang, Lieferantenreklamation, Inventur, Schwund und interne Logistik.
import { ensureWarehouse, receiveLot } from "./IndustryWarehouseEngine.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureInbound(c={}){c.inbound??={receipts:[],claims:[],inventoryCounts:[],losses:[],transfers:[]};return c.inbound;}
export function inspectInbound(c,{deliveryId,item,orderedQty,deliveredQty,acceptedQty=null,quality=.95,damagedQty=0,wrongItem=false,zone="raw",unit="kg",expiresAt=null,supplierId=null,now=Date.now()}={}){const s=ensureInbound(c),ordered=Math.max(0,n(orderedQty)),delivered=Math.max(0,n(deliveredQty)),damaged=Math.min(delivered,Math.max(0,n(damagedQty))),autoAccepted=Math.max(0,delivered-damaged),accepted=acceptedQty===null?autoAccepted:Math.min(autoAccepted,Math.max(0,n(acceptedQty))),status=wrongItem?"rejected":accepted<=0?"rejected":accepted<delivered?"partial":"accepted",receipt={id:`receipt-${now}-${Math.random().toString(36).slice(2,6)}`,deliveryId,item,orderedQty:ordered,deliveredQty:delivered,acceptedQty:wrongItem?0:accepted,damagedQty:damaged,wrongItem,quality:clamp(n(quality,.95),0,1),supplierId,status,shortage:Math.max(0,ordered-delivered),overage:Math.max(0,delivered-ordered),createdAt:now};s.receipts.push(receipt);if(receipt.acceptedQty>0)receiveLot(c,{item,quantity:receipt.acceptedQty,zone,unit,expiresAt,quality:receipt.quality,source:deliveryId,now});if(status!=="accepted"||damaged>0||receipt.shortage>0||wrongItem)createSupplierClaim(c,{receiptId:receipt.id,supplierId,item,reason:wrongItem?"wrong_item":damaged>0?"damaged":receipt.shortage>0?"short_delivery":"partial_rejection",quantity:wrongItem?delivered:damaged+receipt.shortage,now});return receipt;}
export function createSupplierClaim(c,{receiptId,supplierId,item,reason,quantity,now=Date.now()}={}){const s=ensureInbound(c),row={id:`claim-${now}-${Math.random().toString(36).slice(2,6)}`,receiptId,supplierId,item,reason,quantity:Math.max(0,n(quantity)),status:"open",createdAt:now};s.claims.push(row);return row;}
export function settleSupplierClaim(c,claimId,{resolution="credit",creditAmount=0,replacementQty=0,now=Date.now()}={}){const x=ensureInbound(c).claims.find(a=>a.id===claimId);if(!x)throw new Error("Lieferantenreklamation fehlt");if(x.status==="resolved")return{success:true,idempotent:true};x.status="resolved";x.resolution=resolution;x.creditAmount=Math.max(0,n(creditAmount));x.replacementQty=Math.max(0,n(replacementQty));x.resolvedAt=now;if(x.creditAmount>0){c.money=n(c.money)+x.creditAmount;c.salesLedger??=[];c.salesLedger.push({kind:"supplier_credit",revenue:x.creditAmount,at:now,claimId:x.id});}return{success:true,claim:x};}
export function runInventoryCount(c,{counts={},reason="inventory",now=Date.now()}={}){const s=ensureInbound(c),differences=[];c.inventory??={};for(const[item,countedRaw]of Object.entries(counts)){const book=n(c.inventory[item]),counted=Math.max(0,n(countedRaw)),difference=counted-book;if(Math.abs(difference)>1e-9){differences.push({item,book,counted,difference});c.inventory[item]=counted;c.costLedger??=[];c.salesLedger??=[];if(difference<0)c.costLedger.push({kind:"inventory_loss",amount:Math.abs(difference),quantity:Math.abs(difference),item,at:now});else c.salesLedger.push({kind:"inventory_gain",revenue:0,quantity:difference,item,at:now});}}const row={id:`inventory-${now}`,reason,differences,createdAt:now};s.inventoryCounts.push(row);return row;}
export function recordShrinkage(c,item,quantity,{reason="shrinkage",unitCost=0,now=Date.now()}={}){const s=ensureInbound(c),q=Math.min(Math.max(0,n(quantity)),n(c.inventory?.[item]));c.inventory[item]=Math.max(0,n(c.inventory[item])-q);const loss={id:`loss-${now}-${Math.random().toString(36).slice(2,5)}`,item,quantity:q,reason,cost:q*Math.max(0,n(unitCost)),at:now};s.losses.push(loss);c.costLedger??=[];c.costLedger.push({kind:"inventory_loss",amount:loss.cost,item,quantity:q,reason,at:now});return loss;}
export function classifyInventoryVelocity(c,item,{days=30,now=Date.now()}={}){const movements=ensureWarehouse(c).movements.filter(x=>x.item===item&&x.kind==="consume"&&x.at>=now-days*86400000),used=movements.reduce((a,x)=>a+n(x.quantity),0),stock=n(c.inventory?.[item]),turnover=stock>0?used/stock:used>0?Infinity:0;return{item,used,stock,turnover,class:turnover>=2?"fast":turnover>=.3?"normal":"slow"};}
export function deadStock(c,{days=90,now=Date.now()}={}){const w=ensureWarehouse(c),last={};for(const m of w.movements)last[m.item]=Math.max(n(last[m.item]),n(m.at));return Object.keys(c.inventory||{}).filter(item=>n(c.inventory[item])>0&&(!last[item]||last[item]<now-days*86400000)).map(item=>({item,quantity:n(c.inventory[item]),lastMovement:last[item]||null}));}
export function transferInventory(c,{fromSiteId,toSiteId,item,quantity,costPerKm=0,distanceKm=0,now=Date.now()}={}){const s=ensureInbound(c),sites=c.sites||[],from=sites.find(x=>x.id===fromSiteId),to=sites.find(x=>x.id===toSiteId);if(!from||!to)throw new Error("Standort fehlt");const q=Math.max(0,n(quantity));from.inventory??={};to.inventory??={};if(n(from.inventory[item])<q)throw new Error("Quellstandort hat zu wenig Bestand");from.inventory[item]-=q;to.inventory[item]=n(to.inventory[item])+q;const cost=Math.max(0,n(distanceKm))*Math.max(0,n(costPerKm));c.money=n(c.money)-cost;const row={id:`transfer-${now}-${Math.random().toString(36).slice(2,6)}`,fromSiteId,toSiteId,item,quantity:q,distanceKm:n(distanceKm),cost,status:"completed",at:now};s.transfers.push(row);return row;}
export function logisticsKpis(c){const s=ensureInbound(c),receipts=s.receipts,accepted=receipts.filter(x=>x.status==="accepted").length,onSpec=receipts.filter(x=>x.status==="accepted"&&x.quality>=.9&&!x.damagedQty&&!x.shortage&&!x.wrongItem).length;return{receipts:receipts.length,acceptanceRate:receipts.length?accepted/receipts.length:1,onSpecRate:receipts.length?onSpec/receipts.length:1,openClaims:s.claims.filter(x=>x.status==="open").length,inventoryAdjustments:s.inventoryCounts.reduce((a,x)=>a+x.differences.length,0),shrinkageEvents:s.losses.length,internalTransfers:s.transfers.length,internalTransferCost:s.transfers.reduce((a,x)=>a+n(x.cost),0)};}
