// WorldProject – Finanzen für alle Gewerbe: GuV, Cashflow, Steuerreserve, Forderungen/Verbindlichkeiten.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureFinance(c={}){c.finance??={receivables:[],payables:[],taxReserve:0,loans:[],periods:[]};c.salesLedger??=[];c.costLedger??=[];return c.finance;}
export function postReceivable(c,{customerId,amount,dueAt,reference}={}){const f=ensureFinance(c),row={id:`ar-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,customerId,amount:Math.max(0,n(amount)),dueAt:n(dueAt,Date.now()),reference,status:"open"};f.receivables.push(row);return row;}
export function collectReceivable(c,id,{now=Date.now()}={}){const f=ensureFinance(c),r=f.receivables.find(x=>x.id===id);if(!r)throw new Error("Forderung fehlt");if(r.status==="paid")return{success:true,idempotent:true};r.status="paid";r.paidAt=now;c.money=n(c.money)+r.amount;c.salesLedger.push({kind:"receivable",revenue:r.amount,at:now,reference:r.reference});return{success:true,amount:r.amount};}
export function postPayable(c,{supplierId,amount,dueAt,reference}={}){const f=ensureFinance(c),row={id:`ap-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,supplierId,amount:Math.max(0,n(amount)),dueAt:n(dueAt,Date.now()),reference,status:"open"};f.payables.push(row);return row;}
export function payPayable(c,id,{now=Date.now()}={}){const f=ensureFinance(c),r=f.payables.find(x=>x.id===id);if(!r)throw new Error("Verbindlichkeit fehlt");if(r.status==="paid")return{success:true,idempotent:true};if(n(c.money)<r.amount)throw new Error("Liquidität reicht nicht");c.money-=r.amount;r.status="paid";r.paidAt=now;c.costLedger.push({kind:"payable",amount:r.amount,at:now,reference:r.reference});return{success:true,amount:r.amount};}
export function profitAndLoss(c,{from=0,to=Infinity}={}){const revenue=(c.salesLedger||[]).filter(x=>n(x.at)>=from&&n(x.at)<=to).reduce((s,x)=>s+n(x.revenue??x.amount),0),cost=(c.costLedger||[]).filter(x=>n(x.at)>=from&&n(x.at)<=to).reduce((s,x)=>s+n(x.cost??x.amount),0);return{revenue,cost,profit:revenue-cost,margin:revenue?(revenue-cost)/revenue:0};}
export function reserveTaxes(c,{rate=.3,from=0,to=Infinity}={}){const f=ensureFinance(c),p=profitAndLoss(c,{from,to}),reserve=Math.max(0,p.profit*n(rate,.3));f.taxReserve=Math.max(n(f.taxReserve),reserve);return{profit:p.profit,rate:n(rate,.3),reserve};}
export function liquidityForecast(c,{days=30,now=Date.now()}={}){const f=ensureFinance(c),until=now+days*86400000,incoming=f.receivables.filter(x=>x.status==="open"&&n(x.dueAt)<=until).reduce((s,x)=>s+n(x.amount),0),outgoing=f.payables.filter(x=>x.status==="open"&&n(x.dueAt)<=until).reduce((s,x)=>s+n(x.amount),0),loanPayments=f.loans.reduce((s,x)=>s+n(x.paymentMonthly)*(days/30),0);return{cash:n(c.money),incoming,outgoing,loanPayments,taxReserve:n(f.taxReserve),forecast:n(c.money)+incoming-outgoing-loanPayments-n(f.taxReserve)};}
export function closeFinancePeriod(c,{period="month",from=0,to=Date.now(),taxRate=.3}={}){const f=ensureFinance(c),p=profitAndLoss(c,{from,to}),tax=reserveTaxes(c,{rate:taxRate,from,to}),liq=liquidityForecast(c);const row={id:`finance-${period}-${to}`,period,from,to,...p,taxReserve:tax.reserve,liquidity:liq.forecast};f.periods.push(row);return row;}
