// WorldProject – Energie, Emissionen, Abfall und Nachhaltigkeit für alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureSustainability(c={}){c.sustainability??={energyKwh:0,co2Kg:0,wasteKg:0,recycledKg:0,waterL:0,investments:[],score:50};return c.sustainability;}
export function recordOperationFootprint(c,{energyKwh=0,waterL=0,wasteKg=0,recycledKg=0,gridCo2KgPerKwh=.35}={}){const s=ensureSustainability(c);s.energyKwh+=Math.max(0,n(energyKwh));s.waterL+=Math.max(0,n(waterL));s.wasteKg+=Math.max(0,n(wasteKg));s.recycledKg+=Math.max(0,Math.min(n(recycledKg),n(wasteKg)));s.co2Kg+=Math.max(0,n(energyKwh))*Math.max(0,n(gridCo2KgPerKwh));recalculateScore(s);return s;}
function recalculateScore(s){const recycle=s.wasteKg?s.recycledKg/s.wasteKg:0,penalty=Math.min(35,s.co2Kg/10000*10+s.wasteKg/5000*10),bonus=recycle*25+s.investments.reduce((a,x)=>a+n(x.scoreBonus),0);s.score=Math.max(0,Math.min(100,50-penalty+bonus));return s.score;}
export const SustainabilityInvestments={solar:{label:"Photovoltaik",price:30000,energyReduction:.18,scoreBonus:6},heat_recovery:{label:"Wärmerückgewinnung",price:18000,energyReduction:.12,scoreBonus:4},water_reuse:{label:"Wasser-Rückgewinnung",price:14000,waterReduction:.2,scoreBonus:5},recycling:{label:"Recyclingkonzept",price:8000,wasteReduction:.18,scoreBonus:5}};
export function buySustainabilityInvestment(c,id){const s=ensureSustainability(c),d=SustainabilityInvestments[id];if(!d)throw new Error("Investition fehlt");if(s.investments.some(x=>x.id===id))return{success:true,idempotent:true};if(n(c.money)<d.price)throw new Error("Nicht genug Kapital");c.money-=d.price;s.investments.push({id,...d,boughtAt:Date.now()});recalculateScore(s);return{success:true,investment:d,score:s.score};}
export function sustainabilityMultipliers(c){const s=ensureSustainability(c);return{energy:Math.max(.4,1-s.investments.reduce((a,x)=>a+n(x.energyReduction),0)),water:Math.max(.4,1-s.investments.reduce((a,x)=>a+n(x.waterReduction),0)),waste:Math.max(.4,1-s.investments.reduce((a,x)=>a+n(x.wasteReduction),0)),score:s.score};}
export function sustainabilityKpis(c){const s=ensureSustainability(c);return{energyKwh:s.energyKwh,co2Kg:s.co2Kg,waterL:s.waterL,wasteKg:s.wasteKg,recyclingRate:s.wasteKg?s.recycledKg/s.wasteKg:0,score:s.score,investments:s.investments.length};}
