// Prüft, ob jedes angebotene Gewerbe tatsächlich Inhalte für Einkauf -> Leistung -> Verkauf besitzt.
import { IndustryProfiles } from "./IndustryCatalog.js";
import { worldContentRegistry } from "./ContentRegistry.js";
import { compatibleMachineIds } from "./IndustryMachineCompatibility.js";
import { requiredRolesForCompany, availableCandidates } from "./IndustryRecruitmentAvailability.js";
const list=(type,key)=>worldContentRegistry.list(type).filter(x=>(x.industries||[]).includes(key));
const depth={brewery:[6,4,4],beverage:[4,3,3],carpentry:[5,5,3],farm:[20,20,3],livestock:[6,6,3],orchard:[8,8,3],bakery:[8,8,3],butcher:[7,7,3],food:[8,8,3],mechanical:[7,7,3],metal:[7,7,3],plastic:[7,7,3],retail:[4,4,4],wholesale:[4,4,4],online_retail:[4,4,4]};
export function auditIndustryContent(type){
 const p=IndustryProfiles[type],key=p.branchKey,company={type,branchKey:key,buildingState:{equipment:(p.equipment||[]).map(x=>({id:x.id}))},employees:[],workforceState:{employees:[]}};
 const suppliers=list("suppliers",key),recipes=list("recipes",key).filter(x=>!x.deprecated),allProducts=list("products",key),products=allProducts.filter(x=>x.sellable!==false),materials=new Set(suppliers.flatMap(x=>x.materials||[])),productIds=new Set(allProducts.map(x=>x.id));
 const recipeCoverage=recipes.map(recipe=>{const missingInputs=Object.keys(recipe.materials||{}).filter(id=>!materials.has(id)&&!productIds.has(id)),machineIds=new Set((p.equipment||[]).map(x=>x.id)),machineOk=!recipe.machineType||compatibleMachineIds(company,recipe.machineType).some(x=>machineIds.has(x)),productOk=!recipe.product||!!worldContentRegistry.get("products",recipe.product);return{recipeId:recipe.id,label:recipe.label||recipe.id,missingInputs,machineType:recipe.machineType||null,machineOk,product:recipe.product||null,productOk,success:!missingInputs.length&&machineOk&&productOk};});
 const missingInputs=[...new Set(recipeCoverage.flatMap(x=>x.missingInputs))],missingMachines=[...new Set(recipeCoverage.filter(x=>!x.machineOk).map(x=>x.machineType).filter(Boolean))],missingProducts=[...new Set(recipeCoverage.filter(x=>!x.productOk).map(x=>x.product).filter(Boolean))],requiredRoles=requiredRolesForCompany(company),candidates=availableCandidates(company,{count:16}),missingCandidates=requiredRoles.filter(role=>!candidates.some(x=>x.role===role)),target=depth[key]||[3,3,2];
 const issues=[];if(!suppliers.length)issues.push("keine Lieferanten");if(!recipes.length)issues.push("kein Leistungs-/Produktionsrezept");if(!products.length)issues.push("kein verkaufbares Produkt/Leistung");if(recipes.length<target[0])issues.push(`zu wenig Rezepttiefe: ${recipes.length}/${target[0]}`);if(products.length<target[1])issues.push(`zu wenig Produktvielfalt: ${products.length}/${target[1]}`);if(suppliers.length<target[2])issues.push(`zu wenig Lieferantenauswahl: ${suppliers.length}/${target[2]}`);if(missingInputs.length)issues.push(`nicht beschaffbare Inputs: ${missingInputs.join(", ")}`);if(missingMachines.length)issues.push(`Rezeptmaschinen nicht im Betriebskatalog: ${missingMachines.join(", ")}`);if(missingProducts.length)issues.push(`Ausgabeprodukte fehlen: ${missingProducts.join(", ")}`);if(missingCandidates.length)issues.push(`Pflichtfachkräfte nicht verfügbar: ${missingCandidates.join(", ")}`);
 return{type,branchKey:key,suppliers:suppliers.length,recipes:recipes.length,products:products.length,target:{recipes:target[0],products:target[1],suppliers:target[2]},requiredRoles,missingCandidates,missingInputs,missingMachines,missingProducts,recipeCoverage,issues,success:issues.length===0};
}
export function runIndustryContentCoverageAudit(){const rows=Object.keys(IndustryProfiles).map(auditIndustryContent),failed=rows.filter(x=>!x.success),report={success:failed.length===0,total:rows.length,passed:rows.length-failed.length,failed,rows};if(typeof window!=="undefined")window.worldIndustryContentCoverage=report;console[report.success?"log":"warn"](`${report.success?'✅':'⚠️'} GEWERBE-INHALT ${report.passed}/${report.total}`,report);return report;}
