// WorldProject – Wachstum: Erfahrung, Betriebslevel, Forschung, Erweiterungen und Kapazitätsboni.
import { getIndustryProfile } from "./IndustryCatalog.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureGrowth(c={}){c.growth??={xp:0,level:1,researchPoints:0,research:[],expansions:[],milestones:[]};return c.growth;}
export function levelThreshold(level){return Math.round(1000*Math.pow(Math.max(1,n(level)),1.45));}
export function addExperience(c,xp,{source="operation"}={}){const g=ensureGrowth(c);g.xp+=Math.max(0,n(xp));let levels=0;while(g.xp>=levelThreshold(g.level)){g.xp-=levelThreshold(g.level);g.level++;g.researchPoints+=1;levels++;g.milestones.push({kind:"level",level:g.level,source,at:Date.now()});}return{level:g.level,xp:g.xp,next:levelThreshold(g.level),levelsGained:levels,researchPoints:g.researchPoints};}
export const ResearchCatalog={efficiency:{label:"Prozesseffizienz",maxLevel:5,cost:l=>l+1,bonus:l=>({variableCostMultiplier:1-l*.04})},capacity:{label:"Kapazitätsplanung",maxLevel:5,cost:l=>l+1,bonus:l=>({capacityMultiplier:1+l*.08})},quality:{label:"Qualitätsmanagement",maxLevel:5,cost:l=>l+1,bonus:l=>({qualityBonus:l*2})},logistics:{label:"Logistikoptimierung",maxLevel:5,cost:l=>l+1,bonus:l=>({transportCostMultiplier:1-l*.04})}};
export function researchLevel(c,id){return ensureGrowth(c).research.find(x=>x.id===id)?.level||0;}
export function buyResearch(c,id){const g=ensureGrowth(c),def=ResearchCatalog[id];if(!def)throw new Error("Forschung fehlt");const current=researchLevel(c,id);if(current>=def.maxLevel)throw new Error("Maximale Forschungsstufe erreicht");const cost=def.cost(current);if(g.researchPoints<cost)throw new Error("Nicht genug Forschungspunkte");g.researchPoints-=cost;const row=g.research.find(x=>x.id===id)||{id,level:0};if(!g.research.includes(row))g.research.push(row);row.level++;return{...row,bonus:def.bonus(row.level)};}
export function expansionOptions(c){const p=getIndustryProfile(c),g=ensureGrowth(c),base=25000+g.expansions.length*15000;return[{id:"storage",label:"Lager erweitern",price:base,capacityBonus:.25},{id:"production",label:`${p.label} Produktions-/Arbeitsfläche`,price:Math.round(base*1.3),capacityBonus:.2},{id:"office",label:"Verwaltung erweitern",price:Math.round(base*.7),capacityBonus:.1}];}
export function buyExpansion(c,id){const g=ensureGrowth(c),o=expansionOptions(c).find(x=>x.id===id);if(!o)throw new Error("Erweiterung fehlt");if(n(c.money)<o.price)throw new Error("Nicht genug Kapital");c.money-=o.price;const row={...o,id:`${id}-${g.expansions.length+1}`,boughtAt:Date.now()};g.expansions.push(row);return row;}
export function growthBonuses(c){const g=ensureGrowth(c),bonus={variableCostMultiplier:1,capacityMultiplier:1,qualityBonus:0,transportCostMultiplier:1};for(const r of g.research){const b=ResearchCatalog[r.id]?.bonus(r.level)||{};for(const[k,v]of Object.entries(b)){if(k.endsWith("Multiplier"))bonus[k]*=v;else bonus[k]+=v;}}bonus.capacityMultiplier*=1+g.expansions.reduce((s,x)=>s+n(x.capacityBonus),0);return bonus;}
