// WorldProject – Kundenauftrag orchestriert Material, Reservierung, Produktion und Verkauf.
import { industryRecipes, productionReadiness, startIndustryJob, finishIndustryJob, sellIndustryOutput } from "./UniversalIndustryCycle.js";
import { procurementSuggestions } from "./IndustryProcurementPlanning.js";
import { reserveStock } from "./IndustryWarehouseEngine.js";
import { orderCapacityPlan } from "./IndustryCapacityPlanner.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureOrderOrchestration(c={}){c.orderOrchestration??={plans:[],events:[]};return c.orderOrchestration;}
export function planCustomerOrder(c,order,{workers=1,workHoursPerDay=8,now=Date.now()}={}){const s=ensureOrderOrchestration(c),r=industryRecipes(c).find(x=>x.product===order.productId);if(!r)return{success:false,reason:"no_recipe",orderId:order.id};const ready=productionReadiness(c,r.id,order.quantity),capacity=orderCapacityPlan(c,r.id,order.quantity,{workers,workHoursPerDay}),procurement=Object.keys(ready.missing).length?procurementSuggestions(c,{orders:[order]}):[],estimatedFinish=now+capacity.effectiveMinutes*60000,plan={id:`plan-${order.id}-${now}`,orderId:order.id,recipeId:r.id,quantity:n(order.quantity),unitPrice:n(order.unitPrice),ready:ready.ready,missing:ready.missing,machineMissing:ready.machineMissing,procurement,capacity,estimatedFinish,dueAt:n(order.dueAt),onTime:!order.dueAt||estimatedFinish<=n(order.dueAt),status:ready.ready?"ready":"blocked",createdAt:now};s.plans.push(plan);return{success:true,plan};}
export function reserveOrderMaterials(c,planId){const s=ensureOrderOrchestration(c),p=s.plans.find(x=>x.id===planId);if(!p)throw new Error("Auftragsplan fehlt");const r=industryRecipes(c).find(x=>x.id===p.recipeId);const factor=p.quantity/Math.max(1,n(r.output,1)),reservations=[];for(const[id,q]of Object.entries(r.materials||{}))reservations.push(reserveStock(c,id,n(q)*factor,{reference:p.orderId}));p.reservations=reservations.map(x=>x.id);return reservations;}
export function startPlannedOrder(c,planId,{now=Date.now()}={}){const s=ensureOrderOrchestration(c),p=s.plans.find(x=>x.id===planId);if(!p)throw new Error("Auftragsplan fehlt");const out=startIndustryJob(c,p.recipeId,p.quantity,{requestId:`order-${p.orderId}`,now});p.jobId=out.job?.id;p.status="running";return out;}
export function completePlannedOrder(c,planId,{now=Date.now(),force=false}={}){const s=ensureOrderOrchestration(c),p=s.plans.find(x=>x.id===planId);if(!p?.jobId)throw new Error("Produktionsauftrag fehlt");finishIndustryJob(c,p.jobId,{now,force});const sale=sellIndustryOutput(c,industryRecipes(c).find(x=>x.id===p.recipeId).product,p.quantity,p.unitPrice,{requestId:`sale-${p.orderId}`,now});p.status="completed";p.completedAt=now;p.revenue=sale.revenue;return{success:true,plan:p,sale};}
