// WorldProject – Betriebsrisiken, Versicherung und Ereignisse für alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureRisk(c={}){c.risk??={insurance:[],events:[],safetyScore:75,riskScore:25};return c.risk;}
export const Policies={property:{label:"Betriebsversicherung",premiumMonthly:180,deductible:1000,coverage:.8},machine:{label:"Maschinenversicherung",premiumMonthly:240,deductible:1500,coverage:.85},transport:{label:"Transportversicherung",premiumMonthly:140,deductible:750,coverage:.8},business:{label:"Betriebsunterbrechung",premiumMonthly:220,deductible:1200,coverage:.75}};
export function insure(c,policyId){const r=ensureRisk(c),p=Policies[policyId];if(!p)throw new Error("Versicherung fehlt");if(r.insurance.some(x=>x.policyId===policyId&&x.status==="active"))return{success:true,idempotent:true};const row={policyId,status:"active",startedAt:Date.now(),...p};r.insurance.push(row);return{success:true,policy:row};}
export function monthlyPremium(c){return ensureRisk(c).insurance.filter(x=>x.status==="active").reduce((s,x)=>s+n(x.premiumMonthly),0);}
export function createRiskEvent(c,{kind="machine",severity=.3,baseLoss=5000,description="Betriebsereignis",at=Date.now()}={}){const r=ensureRisk(c),sev=clamp(n(severity,.3),0,1),gross=Math.round(Math.max(0,n(baseLoss))*sev),policy=r.insurance.find(x=>x.policyId===kind&&x.status==="active")||r.insurance.find(x=>x.policyId==="business"&&x.status==="active"),covered=policy?Math.max(0,(gross-n(policy.deductible))*n(policy.coverage)):0,net=Math.max(0,gross-covered),event={id:`risk-${at}-${Math.random().toString(36).slice(2,6)}`,kind,severity:sev,description,grossLoss:gross,insuranceRecovery:covered,netLoss:net,at,status:"resolved"};r.events.push(event);c.money=n(c.money)-net;c.costLedger??=[];c.costLedger.push({kind:"risk_event",amount:net,at,eventId:event.id});r.riskScore=clamp(r.riskScore+sev*5,0,100);return event;}
export function improveSafety(c,{cost=1000,points=5}={}){const r=ensureRisk(c);if(n(c.money)<n(cost))throw new Error("Nicht genug Geld");c.money-=n(cost);r.safetyScore=clamp(r.safetyScore+n(points),0,100);r.riskScore=clamp(r.riskScore-n(points)*.6,0,100);return{success:true,safetyScore:r.safetyScore,riskScore:r.riskScore};}
export function riskKpis(c){const r=ensureRisk(c),loss=r.events.reduce((s,x)=>s+n(x.netLoss),0),recovered=r.events.reduce((s,x)=>s+n(x.insuranceRecovery),0);return{safetyScore:r.safetyScore,riskScore:r.riskScore,activePolicies:r.insurance.filter(x=>x.status==="active").length,monthlyPremium:monthlyPremium(c),events:r.events.length,netLoss:loss,recovered};}
