// WorldProject – robuste Persistenz für universelle Gewerbezyklen.
import { ensureIndustryState } from "./UniversalIndustryCycle.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const clone=v=>JSON.parse(JSON.stringify(v));
export function industryStateSnapshot(company){ensureIndustryState(company);return clone({inventory:company.inventory,finishedGoods:company.finishedGoods,productionJobs:company.productionJobs,salesLedger:company.salesLedger,costLedger:company.costLedger,operationRequestIds:company.operationRequestIds,saleRequestIds:company.saleRequestIds||[],money:n(company.money)});}
export function hydrateIndustryState(company,snapshot={}){ensureIndustryState(company);for(const k of ["inventory","finishedGoods","productionJobs","salesLedger","costLedger","operationRequestIds","saleRequestIds"]){if(snapshot[k]!=null)company[k]=clone(snapshot[k]);}if(snapshot.money!=null)company.money=n(snapshot.money);sanitizeIndustryState(company);return company;}
export function sanitizeIndustryState(company){ensureIndustryState(company);for(const bag of [company.inventory,company.finishedGoods])for(const[k,v]of Object.entries(bag||{}))bag[k]=Math.max(0,n(v));company.productionJobs=dedupe(company.productionJobs,"id");company.salesLedger=dedupe(company.salesLedger,x=>x.requestId||`${x.productId}|${x.at}|${x.quantity}`);company.costLedger=dedupe(company.costLedger,x=>x.jobId?`job:${x.jobId}`:`${x.kind}|${x.item||""}|${x.at}|${x.amount||x.cost}`);company.operationRequestIds=[...new Set(company.operationRequestIds||[])];company.saleRequestIds=[...new Set(company.saleRequestIds||[])];return company;}
function dedupe(rows=[],key="id"){const seen=new Set(),out=[];for(const row of rows||[]){const id=typeof key==="function"?key(row):row?.[key];if(id!=null&&seen.has(id))continue;if(id!=null)seen.add(id);out.push(row);}return out;}
export function reconcileRunningJobs(company,now=Date.now()){sanitizeIndustryState(company);const ready=[],running=[];for(const job of company.productionJobs){if(job.status==="running"&&n(job.endsAt)<=now)ready.push(job);else if(job.status==="running")running.push(job);}return{ready,running,completed:company.productionJobs.filter(x=>x.status==="done")};}
export function persistenceRoundTrip(company){const snap=industryStateSnapshot(company),copy={};hydrateIndustryState(copy,JSON.parse(JSON.stringify(snap)));return{snapshot:snap,copy,success:JSON.stringify(industryStateSnapshot(copy))===JSON.stringify(snap)};}
export function ledgerTotals(company){sanitizeIndustryState(company);const revenue=(company.salesLedger||[]).reduce((s,x)=>s+n(x.revenue),0),costs=(company.costLedger||[]).reduce((s,x)=>s+n(x.amount??x.cost),0);return{revenue,costs,profit:revenue-costs};}
