// WorldProject – universeller Nachfrage-/Kundenmarkt für alle Gewerbe.
import { industryProducts, industryRecipes } from "./UniversalIndustryCycle.js";
import { recipeCostBreakdown } from "./IndustryEconomicsEngine.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureMarketState(c={}){c.marketState??={day:0,reputation:50,customers:{},priceHistory:{},demandHistory:[],orders:[]};return c.marketState;}
export function demandIndex(c,productId,{price,referencePrice,season=1,competition=1,economy=1}={}){const m=ensureMarketState(c),rep=.6+n(m.reputation,50)/125,priceFactor=referencePrice&&price?clamp(referencePrice/n(price),.35,1.8):1,noise=.95+((String(productId).length+m.day*17)%11)/100;return clamp(rep*priceFactor*n(season,1)*n(competition,1)*n(economy,1)*noise,.1,3);}
export function suggestedMarketPrice(c,recipeId,{margin=.28}={}){const r=industryRecipes(c).find(x=>x.id===recipeId);if(!r)return null;const cost=recipeCostBreakdown(c,recipeId,Math.max(1,n(r.output,1))),base=cost.unitCost/Math.max(.05,1-margin),rep=ensureMarketState(c).reputation;return Math.max(cost.unitCost,base*(.9+rep/500));}
export function generateMarketOrders(c,{count=5,now=Date.now()}={}){const m=ensureMarketState(c),products=industryProducts(c).filter(x=>x.sellable!==false),recipes=industryRecipes(c),orders=[];for(let i=0;i<count&&products.length;i++){const p=products[(m.day+i)%products.length],r=recipes.find(x=>x.product===p.id),price=r?suggestedMarketPrice(c,r.id):10,base=r?Math.max(1,n(r.output,1)):10,qty=Math.max(1,Math.round(base*(.2+((i*13+m.day)%50)/100))),demand=demandIndex(c,p.id,{price,referencePrice:price});orders.push({id:`market-${m.day}-${i}-${now}`,productId:p.id,quantity:qty,unitPrice:Math.round(price*demand*100)/100,dueAt:now+(1+i%5)*86400000,status:"open",customerId:`customer-${(m.day+i)%12}`,createdAt:now});}m.orders.push(...orders);return orders;}
export function acceptMarketOrder(c,orderId){const m=ensureMarketState(c),o=m.orders.find(x=>x.id===orderId);if(!o)throw new Error("Marktauftrag nicht gefunden");if(o.status!=="open")return{success:true,idempotent:true,order:o};o.status="accepted";o.acceptedAt=Date.now();c.customerOrders??=[];c.customerOrders.push({...o});return{success:true,order:o};}
export function settleCustomerExperience(c,{onTime=true,complete=true,quality=1}={}){const m=ensureMarketState(c);m.reputation=clamp(n(m.reputation,50)+(onTime?1:-3)+(complete?1:-2)+(n(quality,1)-.8)*5,0,100);return m.reputation;}
export function advanceMarketDay(c,{season=1,economy=1}={}){const m=ensureMarketState(c);m.day++;m.demandHistory.push({day:m.day,reputation:m.reputation,season,economy,at:Date.now()});if(m.demandHistory.length>365)m.demandHistory.splice(0,m.demandHistory.length-365);return generateMarketOrders(c,{count:3});}
