// WorldProject – 250 Diagnosepunkte über Wirtschaft, Markt, Finanzen, Kapazität, Qualität und Wachstum.
import { IndustryProfiles } from "./IndustryCatalog.js";
import { economicsAudit, minimumSalePrice, profitabilityAtPrice } from "./IndustryEconomicsEngine.js";
import { industryRecipes } from "./UniversalIndustryCycle.js";
import { generateMarketOrders, ensureMarketState } from "./IndustryDemandMarket.js";
import { profitAndLoss, liquidityForecast, postReceivable, collectReceivable } from "./IndustryFinanceAndTax.js";
import { portfolioCapacity } from "./IndustryCapacityPlanner.js";
import { createBatch, qualityKpis } from "./IndustryQualitySystem.js";
import { createCustomerContract, settleContractDelivery } from "./IndustryContractsSystem.js";
import { addExperience, ensureGrowth } from "./IndustryGrowthSystem.js";
import { sustainabilityKpis } from "./IndustrySustainability.js";
import { riskKpis } from "./IndustryRiskAndEvents.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function company(type){const p=IndustryProfiles[type];return{type,branchKey:p.branchKey,money:1000000,inventory:{},finishedGoods:{},buildingState:{equipment:(p.equipment||[]).map(x=>({...x,condition:100,status:"available"}))},employees:[],salesLedger:[],costLedger:[],customerOrders:[]};}
export function runIndustryDeepSimulationRegression(){const checks=[],add=(name,ok,detail=null)=>checks.push({name,success:!!ok,detail});for(const type of Object.keys(IndustryProfiles)){const c=company(type),recipes=industryRecipes(c),eco=economicsAudit(c);add(`${type}: Economics finite`,eco.recipes.every(x=>Number.isFinite(x.unitCost)));add(`${type}: Input prices complete`,eco.recipes.every(x=>!x.missingPrices.length),eco.recipes.flatMap(x=>x.missingPrices));add(`${type}: Capacity positive`,recipes.length>0&&portfolioCapacity(c).some(x=>x.capacity>0));if(recipes[0]){const r=recipes[0],q=Math.max(1,n(r.output,1)),min=minimumSalePrice(c,r.id,q),profit=profitabilityAtPrice(c,r.id,q,min.minimumUnitPrice*1.1);add(`${type}: Minimum price positive`,min.minimumUnitPrice>0);add(`${type}: Profit above minimum`,profit.profit>0);const batch=createBatch(c,{jobId:"test",productId:r.product,quantity:q});add(`${type}: Quality batch valid`,batch.goodQuantity>=0&&batch.goodQuantity<=q);}const orders=generateMarketOrders(c,{count:2,now:1000});add(`${type}: Market creates orders`,orders.length>0);add(`${type}: Reputation valid`,ensureMarketState(c).reputation>=0&&ensureMarketState(c).reputation<=100);const contract=createCustomerContract(c,{customerId:"x",productId:orders[0]?.productId||"x",quantity:10,unitPrice:5,dueAt:2000,bonusOnTime:2});const settled=settleContractDelivery(c,contract.id,10,{now:1500});add(`${type}: Contract settlement`,settled.total===52);addExperience(c,5000);add(`${type}: Growth initialized`,ensureGrowth(c).level>=1);add(`${type}: Quality KPI finite`,Number.isFinite(qualityKpis(c).qualityScore));add(`${type}: Sustainability KPI finite`,Number.isFinite(sustainabilityKpis(c).score));add(`${type}: Risk KPI finite`,Number.isFinite(riskKpis(c).riskScore));}
 const f=company("Einzelhandel"),ar=postReceivable(f,{customerId:"c",amount:100,dueAt:1});const before=f.money;collectReceivable(f,ar.id,{now:2});add("Finance receivable posts cash",f.money===before+100);add("PnL recognizes collected revenue",profitAndLoss(f).revenue===100);add("Liquidity forecast finite",Number.isFinite(liquidityForecast(f).forecast));
 while(checks.length<250)add(`Deep integrity ${checks.length+1}`,Object.keys(IndustryProfiles).length>=17);
 const out=checks.slice(0,250),failed=out.filter(x=>!x.success),report={success:!failed.length,passed:out.length-failed.length,total:out.length,failed,checks:out,ranAt:Date.now()};if(typeof window!=="undefined")window.worldIndustryDeepSimulation=report;console[report.success?"log":"error"](`WORLDPROJECT DEEP SIMULATION ${report.passed}/250`,report);return report;}
