// WorldProject – Kapazitäts-/Engpassplanung für Produktion, Handel und Leistungen.
import { industryRecipes, recipeScale } from "./UniversalIndustryCycle.js";
import { machineRequirementDetails } from "./IndustryMachineCompatibility.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function machineCountFor(company,recipe){const d=machineRequirementDetails(company,recipe.machineType);return d?.ownedMatches?.length||d?.matches?.length||(d?.satisfied?1:0);}
export function orderCapacityPlan(company,recipeId,amount,{workHoursPerDay=8,workers=1}={}){const r=industryRecipes(company).find(x=>x.id===recipeId);if(!r)throw new Error("Rezept fehlt");const factor=Math.max(0,n(amount))/Math.max(1,n(r.output,1)),machineCount=Math.max(0,machineCountFor(company,r)),baseMinutes=Math.max(1,n(r.durationMinutes))*factor,parallel=Math.max(1,Math.min(Math.max(1,machineCount),Math.max(1,n(workers,1)))),effectiveMinutes=baseMinutes/parallel,days=effectiveMinutes/Math.max(1,n(workHoursPerDay,8)*60),need=recipeScale(r,amount);return{recipeId,amount:n(amount),machineType:r.machineType,machineCount,workers:Math.max(1,n(workers,1)),parallel,effectiveMinutes,days,need,bottleneck:machineCount<1?"machine":n(workers)<1?"workforce":null};}
export function portfolioCapacity(company,{hours=8,workers=1}={}){return industryRecipes(company).map(r=>{const machines=Math.max(1,machineCountFor(company,r)),parallel=Math.max(1,Math.min(machines,Math.max(1,n(workers)))),cycles=n(hours)*60/Math.max(1,n(r.durationMinutes))*parallel;return{recipeId:r.id,product:r.product,capacity:Math.floor(cycles*Math.max(1,n(r.output,1))),hours:n(hours),machines};});}
export function capacityAgainstOrders(company,orders=[],opts={}){const plans=[];for(const o of orders.filter(x=>!["done","completed","cancelled"].includes(x.status))){const r=industryRecipes(company).find(x=>x.product===o.productId);if(!r){plans.push({orderId:o.id,feasible:false,reason:"no_recipe"});continue;}const p=orderCapacityPlan(company,r.id,o.quantity,opts),availableDays=Math.max(0,(n(o.dueAt,Date.now())-Date.now())/86400000);plans.push({orderId:o.id,recipeId:r.id,feasible:!p.bottleneck&&p.days<=availableDays,availableDays,...p});}return plans;}
export function bottleneckSummary(company,orders=[],opts={}){const p=capacityAgainstOrders(company,orders,opts),late=p.filter(x=>!x.feasible),machine=late.filter(x=>x.bottleneck==="machine"),deadline=late.filter(x=>!x.bottleneck&&x.reason!=="no_recipe");return{total:p.length,feasible:p.length-late.length,late:late.length,machineBottlenecks:machine.length,deadlineBottlenecks:deadline.length,noRecipe:late.filter(x=>x.reason==="no_recipe").length,plans:p};}
