// WorldProject – universeller Maschinen-/Ausstattungsmarkt für ALLE Gewerbe.
// Verwendet ausschließlich den bestehenden IndustryCatalog und buildingState.
import { equipmentFor, requiredEquipmentFor, setupProgress } from './IndustryCatalog.js';
import { compatibleMachineIds } from './IndustryMachineCompatibility.js';
import { ensureGrowth } from './IndustryGrowthSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const equipmentList=c=>{c.buildingState??=c.building_state??{rooms:[],equipment:[]};c.buildingState.equipment??=[];return c.buildingState.equipment;};
const equipmentKeys=x=>typeof x==='string'?[x]:[x?.id,x?.equipmentId,x?.type,x?.machineType].filter(Boolean).map(String);
const ownedIds=c=>[...new Set(equipmentList(c).flatMap(equipmentKeys))];
export const equipmentUnlockLevel=item=>Math.max(1,Math.floor(n(item?.requiredLevel,1)));
export const companyEquipmentLevel=company=>Math.max(1,Math.floor(n(ensureGrowth(company).level,1)));
export function equipmentMarketplace(company){const owned=ownedIds(company),required=new Set(requiredEquipmentFor(company)),level=companyEquipmentLevel(company);return equipmentFor(company).map(item=>{const keys=equipmentKeys(item),isOwned=keys.some(id=>owned.includes(id)),requiredLevel=equipmentUnlockLevel(item),unlocked=level>=requiredLevel;return{...item,required:required.has(item.id),owned:isOwned,requiredLevel,unlocked,affordable:unlocked&&n(company.money)>=n(item.price),missing:!isOwned};});}
export function visibleEquipmentMarketplace(company){return equipmentMarketplace(company).filter(item=>item.owned||item.unlocked);}
export function equipmentForMachineRequirement(company,machineType){const choices=new Set(compatibleMachineIds(company,machineType));return visibleEquipmentMarketplace(company).filter(x=>choices.has(x.id));}
export function buyIndustryEquipment(company,equipmentId,{requestId=null,now=Date.now()}={}){const item=equipmentFor(company).find(x=>x.id===equipmentId);if(!item)throw new Error('Ausstattung ist für dieses Gewerbe nicht verfügbar');const level=companyEquipmentLevel(company),requiredLevel=equipmentUnlockLevel(item);if(level<requiredLevel)throw new Error(`${item.name} wird erst ab Betriebslevel ${requiredLevel} freigeschaltet`);company.equipmentPurchaseRequestIds??=[];if(requestId&&company.equipmentPurchaseRequestIds.includes(requestId))return{success:true,idempotent:true,item:equipmentList(company).find(x=>equipmentKeys(x).includes(String(equipmentId)))||null,progress:setupProgress(company)};if(ownedIds(company).includes(String(equipmentId)))throw new Error(`${item.name} ist bereits vorhanden`);const price=Math.max(0,n(item.price));if(n(company.money)<price)throw new Error(`Nicht genug Geld: ${item.name} kostet ${price.toLocaleString('de-DE')} €`);const previousPhase=company.setupPhase??company.setup_phase??null,wasOperating=previousPhase==='operating';const instance={...item,instanceId:`eq-${equipmentId}-${now}-${Math.random().toString(36).slice(2,6)}`,status:'available',condition:100,purchasedAt:now,purchasePrice:price};equipmentList(company).push(instance);company.money=n(company.money)-price;company.costLedger??=[];company.costLedger.push({kind:'equipment_purchase',equipmentId,instanceId:instance.instanceId,label:item.name||item.id,amount:price,at:now,requestId});if(requestId)company.equipmentPurchaseRequestIds.push(requestId);const progress=setupProgress(company);company.setupPhase=wasOperating?'operating':progress.complete?'ready':'furnishing';company.buildingState.ready=wasOperating||progress.complete;return{success:true,item:instance,price,balance:company.money,progress,previousPhase};}
export function equipmentSetupVM(company){const market=visibleEquipmentMarketplace(company),progress=setupProgress(company);return{progress,required:market.filter(x=>x.required),optional:market.filter(x=>!x.required),missingRequired:market.filter(x=>x.required&&!x.owned),owned:market.filter(x=>x.owned),totalMissingCost:market.filter(x=>x.required&&!x.owned).reduce((s,x)=>s+n(x.price),0),canComplete:progress.complete};}
function validSetupPhase(company){const raw=company.setupPhase??company.setup_phase??null;if(['empty_building','furnishing','ready','operating'].includes(raw))return raw;if(raw==='operational')return'operating';if(raw==='equipment_setup')return'furnishing';return company.buildingState?.ready?'operating':'furnishing';}
export async function persistIndustryEquipment(company){const api=window.worldAccounts?.authApi,id=company.serverCompanyId;if(!api||!id)return{success:false,persisted:false,reason:'Server-API/Betrieb fehlt'};const phase=validSetupPhase(company);company.setupPhase=phase;if(typeof api.updateBusinessSetup==='function')await api.updateBusinessSetup(id,phase,company.buildingState);if(typeof api.saveBusinessState==='function'){const state={};for(const[k,v]of Object.entries(company))if(!['buildingState','gigaTransportService','constructionManagers','market','transportSystem'].includes(k)&&typeof v!=='function')state[k]=v;await api.saveBusinessState(id,state);}window.worldActiveServerCompany={...(window.worldActiveServerCompany||{}),building_state:company.buildingState,setup_phase:phase};return{success:true,persisted:true};}
if(typeof window!=='undefined')window.worldIndustryEquipment={marketplace:equipmentMarketplace,visibleMarketplace:visibleEquipmentMarketplace,forRequirement:equipmentForMachineRequirement,buy:buyIndustryEquipment,setupVM:equipmentSetupVM,persist:persistIndustryEquipment};
