// WorldProject – einheitliches Betriebs-Dashboard für alle Gewerbe, ohne neue Parallelzustände.
import { equipmentSetupVM } from './IndustryEquipmentMarketplace.js';
import { allProductionReadinessVM } from './ProductionReadinessAssistant.js';
import { industryRecipes,industrySuppliers } from './UniversalIndustryCycle.js';
import { availableFarmCrops,agricultureEnvironment,expectedFarmYield } from './SeasonalBusinessCalendar.js';
import { operationsOverviewVM,machinePanelVM,workforcePanelVM,procurementPanelVM,salesPanelVM,financePanelVM } from './ExistingUIIntegrationAdapters.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function operationalDashboardVM(company,{amountByRecipe={}}={}){const production=allProductionReadinessVM(company,amountByRecipe),recipes=industryRecipes(company),isFarm=(company.branchKey==='farm'||company.type==='Landwirtschaftsbetrieb'),cropRows=isFarm?availableFarmCrops(company,{includeMarginal:true}).map(x=>({recipeId:x.recipe.id,label:x.recipe.label||x.recipe.id,product:x.recipe.product,allowed:x.allowed,score:x.score,sowing:x.sowing,harvest:x.harvest,reasons:x.reasons,expected:expectedFarmYield(company,x.recipe,1)})):[];return{company:{id:company.serverCompanyId||company.id,name:company.name,type:company.type,industry:company.industry,money:n(company.money),setupPhase:company.setupPhase},overview:operationsOverviewVM(company),equipment:equipmentSetupVM(company),machines:machinePanelVM(company),workforce:workforcePanelVM(company),procurement:{...procurementPanelVM(company),supplierCount:industrySuppliers(company).length},production:{recipes,readiness:production,ready:production.filter(x=>x.ready).length,blocked:production.filter(x=>!x.ready).length,jobs:company.productionJobs||[]},agriculture:isFarm?{environment:agricultureEnvironment(company),crops:cropRows,suitableNow:cropRows.filter(x=>x.allowed).length,marginal:cropRows.filter(x=>!x.allowed&&x.score>=.45).length}:null,sales:salesPanelVM(company),finance:financePanelVM(company),inventory:{raw:{...(company.inventory||{})},finished:{...(company.finishedGoods||{})},operational:{...(company.operationalInventory||{})}},fleet:{vehicles:company.vehicles||[],deliveries:company.inboundDeliveries||company.deliveries||[]},generatedAt:Date.now()};}
export function operationalBadgeCounts(company){const d=operationalDashboardVM(company);return{equipmentMissing:d.equipment.missingRequired.length,productionRunning:d.production.jobs.filter(x=>x.status==='running').length,productionBlocked:d.production.blocked,employees:d.workforce.employees.length,deliveries:d.fleet.deliveries.filter(x=>!['received','completed','cancelled'].includes(x.status)).length,customerOrders:(d.sales.orders||[]).filter(x=>!['completed','cancelled'].includes(x.status)).length,suitableCrops:d.agriculture?.suitableNow||0};}
if(typeof window!=='undefined')window.worldOperationalDashboard={view:operationalDashboardVM,badges:operationalBadgeCounts};
