// WorldProject – einheitliches Betriebs-Dashboard für alle Gewerbe, ohne neue Parallelzustände.
import { equipmentSetupVM } from './IndustryEquipmentMarketplace.js';
import { allProductionReadinessVM } from './ProductionReadinessAssistant.js';
import { industryRecipes,industrySuppliers } from './UniversalIndustryCycle.js';
import { operationsOverviewVM,machinePanelVM,workforcePanelVM,procurementPanelVM,salesPanelVM,financePanelVM } from './ExistingUIIntegrationAdapters.js';
import { cropSuitability } from './SeasonalBusinessCalendar.js';
import { formatMoney } from './CurrencyPresentationBridge.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function agricultureDashboard(company){if((company?.branchKey||'')!=='farm')return null;const recipes=industryRecipes(company).filter(r=>r.cropMeta),rows=recipes.map(recipe=>cropSuitability(company,recipe,{now:new Date()}));return{location:{region:company.agricultureState?.region||null,climateZone:company.agricultureState?.climateZone||'temperate',soilType:company.agricultureState?.soilType||'loam',irrigation:n(company.agricultureState?.irrigation)},crops:rows,suitable:rows.filter(x=>x.suitable),borderline:rows.filter(x=>x.yieldFactor<1&&x.yieldFactor>=.65),sowableNow:rows.filter(x=>x.sowWindow&&x.suitable),harvestableNow:rows.filter(x=>x.harvestWindow),best:[...rows].sort((a,b)=>b.expectedYield-a.expectedYield).slice(0,6)};}
export function operationalDashboardVM(company,{amountByRecipe={}}={}){const production=allProductionReadinessVM(company,amountByRecipe),money=n(company.money);return{company:{id:company.serverCompanyId||company.id,name:company.name,type:company.type,industry:company.industry,money,moneyFormatted:formatMoney(money),setupPhase:company.setupPhase},overview:operationsOverviewVM(company),equipment:equipmentSetupVM(company),machines:machinePanelVM(company),workforce:workforcePanelVM(company),procurement:{...procurementPanelVM(company),supplierCount:industrySuppliers(company).length},production:{recipes:industryRecipes(company),readiness:production,ready:production.filter(x=>x.ready).length,blocked:production.filter(x=>!x.ready).length,jobs:company.productionJobs||[]},sales:salesPanelVM(company),finance:financePanelVM(company),inventory:{raw:{...(company.inventory||{})},finished:{...(company.finishedGoods||{})},operational:{...(company.operationalInventory||{})}},fleet:{vehicles:company.vehicles||[],deliveries:company.inboundDeliveries||company.deliveries||[]},agriculture:agricultureDashboard(company),generatedAt:Date.now()};}
export function operationalBadgeCounts(company){const d=operationalDashboardVM(company);return{equipmentMissing:d.equipment.missingRequired.length,productionRunning:d.production.jobs.filter(x=>x.status==='running').length,productionBlocked:d.production.blocked,employees:d.workforce.employees.length,deliveries:d.fleet.deliveries.filter(x=>!['received','completed','cancelled'].includes(x.status)).length,customerOrders:(d.sales.orders||[]).filter(x=>!['completed','cancelled'].includes(x.status)).length,sowableCrops:d.agriculture?.sowableNow?.length||0};}
if(typeof window!=='undefined')window.worldOperationalDashboard={view:operationalDashboardVM,badges:operationalBadgeCounts};
