// WorldProject – Personalentwicklung für alle Gewerbe: Skills, Erfahrung, Schulung, Moral, Produktivität.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureWorkforceDevelopment(c={}){c.workforceDevelopment??={training:[],events:[]};c.employees??=[];for(const e of c.employees){e.experience??=0;e.skillLevel??=1;e.morale??=75;e.fatigue??=0;e.training??=[];}return c.workforceDevelopment;}
export function employeeProductivity(e){return clamp((.65+n(e.skillLevel,1)*.08)*(0.7+n(e.morale,75)/250)*(1-clamp(n(e.fatigue),0,100)/180),.35,1.6);}
export function addEmployeeExperience(c,employeeId,hours){ensureWorkforceDevelopment(c);const e=c.employees.find(x=>(x.id||x.employeeId)===employeeId);if(!e)throw new Error("Mitarbeiter fehlt");e.experience=n(e.experience)+Math.max(0,n(hours));const target=250*Math.pow(n(e.skillLevel,1),1.35);if(e.experience>=target&&e.skillLevel<5){e.experience-=target;e.skillLevel++;}e.fatigue=clamp(n(e.fatigue)+n(hours)*1.5,0,100);return e;}
export function restEmployee(c,employeeId,hours=8){ensureWorkforceDevelopment(c);const e=c.employees.find(x=>(x.id||x.employeeId)===employeeId);if(!e)throw new Error("Mitarbeiter fehlt");e.fatigue=clamp(n(e.fatigue)-Math.max(0,n(hours))*7,0,100);e.morale=clamp(n(e.morale)+Math.min(4,n(hours)/3),0,100);return e;}
export function startTraining(c,employeeId,{skill="general",hours=8,cost=250,now=Date.now()}={}){const w=ensureWorkforceDevelopment(c),e=c.employees.find(x=>(x.id||x.employeeId)===employeeId);if(!e)throw new Error("Mitarbeiter fehlt");if(n(c.money)<n(cost))throw new Error("Nicht genug Geld");c.money-=n(cost);const row={id:`training-${now}-${Math.random().toString(36).slice(2,6)}`,employeeId,skill,hours:Math.max(1,n(hours)),cost:n(cost),startsAt:now,endsAt:now+Math.max(1,n(hours))*3600000,status:"running"};w.training.push(row);e.status="training";return row;}
export function finishTraining(c,trainingId,{now=Date.now(),force=false}={}){const w=ensureWorkforceDevelopment(c),t=w.training.find(x=>x.id===trainingId);if(!t)throw new Error("Schulung fehlt");if(t.status==="done")return t;if(!force&&now<t.endsAt)throw new Error("Schulung läuft noch");const e=c.employees.find(x=>(x.id||x.employeeId)===t.employeeId);if(e){e.training??=[];if(!e.training.includes(t.skill))e.training.push(t.skill);e.skillLevel=clamp(n(e.skillLevel,1)+.25,1,5);e.morale=clamp(n(e.morale,75)+3,0,100);e.status="available";}t.status="done";t.finishedAt=now;return t;}
export function workforceKpis(c){ensureWorkforceDevelopment(c);const a=c.employees;return{employees:a.length,averageProductivity:a.length?a.reduce((s,e)=>s+employeeProductivity(e),0)/a.length:0,averageMorale:a.length?a.reduce((s,e)=>s+n(e.morale,75),0)/a.length:0,averageFatigue:a.length?a.reduce((s,e)=>s+n(e.fatigue),0)/a.length:0,inTraining:a.filter(e=>e.status==="training").length};}
