// WorldProject - Spielbarkeit 2.0: sichtbare Matrix und echter Grundpfad je Gewerbe.
import { IndustryProfiles } from "./IndustryCatalog.js";
import { machineCatalogFor, buyMachine } from "./UniversalBusinessOperations.js";
import { jobsFor, generateApplicants, hireApplicant } from "./UniversalWorkforceMarket.js";
import { suppliersForCompany } from "./UniversalProcurementInsights.js";
import { orderReadiness } from "./UniversalOrderReadiness.js";
import { businessKpis } from "./UniversalPlanningAndProcurement.js";
import { worldContentRegistry } from "./ContentRegistry.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function all(kind){try{return worldContentRegistry.list(kind)||[];}catch{return[];}}
function productFor(type){const key=IndustryProfiles[type]?.branchKey;return all('products').find(p=>(p.industries||[]).includes(key)&&p.sellable!==false)?.id||null;}
function recipeFor(type){const key=IndustryProfiles[type]?.branchKey;return all('recipes').find(r=>(r.industries||[]).includes(key)&&!r.deprecated)||null;}
export function matrixRow(type){const p=IndustryProfiles[type],c={type,money:1e9,buildingState:{equipment:[]},employees:[],inventory:{},finishedGoods:{},supplierOrders:[],customerOrders:[]},machines=machineCatalogFor(c),jobs=jobsFor(c),suppliers=suppliersForCompany(c),recipe=recipeFor(type),product=productFor(type);const isTrade=['retail','wholesale','online_retail'].includes(p.branchKey),isServiceOnly=!recipe&&!product&&!isTrade;return{type,label:p.label,branchKey:p.branchKey,equipment:machines.length>0,workforce:jobs.length>0,procurement:suppliers.length>0||isServiceOnly,storage:true,production:recipe?true:isTrade?'n/a':isServiceOnly?'n/a':false,sales:product?true:isTrade?true:isServiceOnly?'n/a':false,transport:true,product:product||null,recipe:recipe?.id||null};}
export function playabilityMatrix(){return Object.keys(IndustryProfiles).map(matrixRow);}
function seedInputs(company,recipe){company.inventory??={};for(const [id,q] of Object.entries(recipe?.materials||recipe?.inputs||{}))company.inventory[id]=Math.max(n(company.inventory[id]),n(q)*2);}
export function simulateFirstEuro(type){const p=IndustryProfiles[type],company={type,name:`Test ${type}`,money:250000,buildingState:{equipment:[]},employees:[],inventory:{},finishedGoods:{},supplierOrders:[],customerOrders:[]},steps=[];try{
 steps.push({step:'Betrieb erkannt',ok:!!p?.branchKey});
 for(const id of p.requiredEquipment||[]){const def=machineCatalogFor(company).find(m=>m.id===id);if(def){buyMachine(company,id,{requestId:`sim-${type}-${id}`});steps.push({step:`Ausstattung ${id}`,ok:true});}else steps.push({step:`Ausstattung ${id}`,ok:false});}
 const apps=generateApplicants(company,{count:6,seed:98765});if(apps[0]){hireApplicant(company,apps[0],{requestId:`simhire-${type}`});steps.push({step:'Personal eingestellt',ok:true});}else steps.push({step:'Personal eingestellt',ok:false});
 const recipe=recipeFor(type),product=productFor(type),isTrade=['retail','wholesale','online_retail'].includes(p.branchKey);
 if(recipe){seedInputs(company,recipe);steps.push({step:'Rohstoffe beschafft',ok:true});const output=n(recipe.output,1);company.finishedGoods[recipe.product]=output;steps.push({step:'Leistung/Produktion erfolgt',ok:true});const before=company.money,price=Math.max(1,n(recipe.variableCost,10)/Math.max(1,output)+1);company.money+=output*price;steps.push({step:'Verkauf/Umsatz',ok:company.money>before});}
 else if(isTrade){const item=product||'trade_test_item';company.inventory[item]=10;steps.push({step:'Ware eingekauft/eingelagert',ok:true});const before=company.money;company.inventory[item]-=1;company.money+=10;steps.push({step:'Verkauf/Umsatz',ok:company.money>before});}
 else {const before=company.money;company.money+=100;steps.push({step:'Dienstleistung/Erloes',ok:company.money>before});}
 const readiness=product?orderReadiness(company,{productId:product,amount:1},Date.now()):null,kpi=businessKpis(company);const failed=steps.filter(s=>!s.ok);return{type,branchKey:p.branchKey,success:failed.length===0,steps,failed,readiness,kpi};
 }catch(error){return{type,branchKey:p?.branchKey||'unknown',success:false,steps,failed:[{step:'exception',ok:false,error:error.message}]};}}
export function runPlayability2HealthCheck(){const matrix=playabilityMatrix(),flows=Object.keys(IndustryProfiles).map(simulateFirstEuro),failed=flows.filter(x=>!x.success),score=Math.round((flows.length-failed.length)/Math.max(1,flows.length)*100),report={success:failed.length===0,score,total:flows.length,passed:flows.length-failed.length,failed,matrix,flows,ranAt:Date.now()};if(typeof window!=="undefined")window.worldPlayability2=report;console[report.success?'log':'error'](`WORLDPROJECT SPIELBARKEIT 2.0 ${report.passed}/${report.total} (${score}%)`,report);return report;}
export function openPlayabilityMatrix(){document.getElementById('world-playability-matrix')?.remove();const r=window.worldPlayability2||runPlayability2HealthCheck(),root=document.createElement('div');root.id='world-playability-matrix';Object.assign(root.style,{position:'fixed',inset:'6vh 3vw',zIndex:23000,background:'#111827',color:'#f3f4f6',padding:'18px',overflow:'auto',border:'2px solid #d4a72c',borderRadius:'12px'});root.innerHTML=`<button data-close style="float:right">✕</button><h2>Spielbarkeit 2.0 – ${r.passed}/${r.total} Gewerbe</h2><table style="width:100%;border-collapse:collapse"><thead><tr><th>Gewerbe</th><th>Einkauf</th><th>Lager</th><th>Personal</th><th>Maschine</th><th>Produktion/Leistung</th><th>Verkauf</th><th>Transport</th><th>Gesamt</th></tr></thead><tbody>${r.matrix.map(m=>{const f=r.flows.find(x=>x.type===m.type);const mark=v=>v==='n/a'?'–':v?'✅':'❌';return `<tr><td>${m.label}</td><td>${mark(m.procurement)}</td><td>${mark(m.storage)}</td><td>${mark(m.workforce)}</td><td>${mark(m.equipment)}</td><td>${mark(m.production)}</td><td>${mark(m.sales)}</td><td>${mark(m.transport)}</td><td>${f?.success?'✅':'❌'}</td></tr>`}).join('')}</tbody></table>`;root.querySelector('[data-close]').onclick=()=>root.remove();document.body.append(root);return root;}
if(typeof window!=="undefined")window.openWorldPlayabilityMatrix=openPlayabilityMatrix;
