// WorldProject – Verbrauchsprognose, Meldebestand, Sicherheitsbestand und automatische Einkaufsvorschläge.
import { industryRecipes, supplierCanProvide } from "./UniversalIndustryCycle.js";
import { operationalStockAmount } from "./OperationalInventoryBridge.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureProcurementPlanning(c={}){c.procurementPlanning??={consumptionHistory:[],policies:{},suggestions:[]};return c.procurementPlanning;}
export function recordConsumption(c,item,quantity,{at=Date.now()}={}){const p=ensureProcurementPlanning(c);p.consumptionHistory.push({item,quantity:Math.max(0,n(quantity)),at});if(p.consumptionHistory.length>5000)p.consumptionHistory.splice(0,p.consumptionHistory.length-5000);return p;}
export function averageDailyConsumption(c,item,{days=30,now=Date.now()}={}){const p=ensureProcurementPlanning(c),from=now-Math.max(1,n(days,30))*86400000,total=p.consumptionHistory.filter(x=>x.item===item&&x.at>=from&&x.at<=now).reduce((s,x)=>s+n(x.quantity),0);return total/Math.max(1,n(days,30));}
export function setInventoryPolicy(c,item,{leadDays=2,safetyDays=3,targetDays=14,minOrder=1}={}){const p=ensureProcurementPlanning(c);p.policies[item]={leadDays:Math.max(0,n(leadDays)),safetyDays:Math.max(0,n(safetyDays)),targetDays:Math.max(1,n(targetDays)),minOrder:Math.max(0,n(minOrder))};return p.policies[item];}
export function reorderPoint(c,item){const p=ensureProcurementPlanning(c),policy=p.policies[item]||setInventoryPolicy(c,item,{}),daily=averageDailyConsumption(c,item);return{item,daily,reorderPoint:daily*(policy.leadDays+policy.safetyDays),target:daily*policy.targetDays,...policy};}
export function projectedRecipeDemand(c,orders=[]){const demand={};for(const o of orders.filter(x=>!["done","cancelled","completed"].includes(x.status))){const r=industryRecipes(c).find(x=>x.product===o.productId);if(!r)continue;const factor=Math.max(0,n(o.quantity))/Math.max(1,n(r.output,1));for(const[id,q]of Object.entries(r.materials||{}))demand[id]=n(demand[id])+n(q)*factor;}return demand;}
export function procurementSuggestions(c,{orders=c.customerLifecycle?.orders||c.customerOrders||[]}={}){const p=ensureProcurementPlanning(c),projected=projectedRecipeDemand(c,orders),items=new Set([...Object.keys(projected),...Object.keys(p.policies)]),out=[];for(const item of items){const suppliers=supplierCanProvide(c,item);if(!suppliers.length)continue;const policy=reorderPoint(c,item),stock=c.operationalSupplyState?.warehouseStock?n(operationalStockAmount(c,item)):n(c.inventory?.[item]),required=Math.max(n(projected[item]),policy.target),qty=Math.max(0,required-stock);if(qty>0)out.push({item,stock,projected:n(projected[item]),quantity:Math.max(qty,policy.minOrder),supplierId:suppliers[0]?.id||null,unitPrice:suppliers[0]?.prices?.[item]??null,critical:stock<policy.reorderPoint});}p.suggestions=out;return out;}
