// WorldProject – Maschinenverschleiß, Wartungsintervalle, Störung und Ausfallzeit.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureMaintenance(c={}){c.maintenance??={records:[],incidents:[],plans:[]};c.buildingState??={equipment:[]};c.buildingState.equipment??=[];return c.maintenance;}
export function machineWear(c,machineId,{runtimeHours=1,load=1,now=Date.now()}={}){const m=ensureMaintenance(c),machine=c.buildingState.equipment.find(x=>(x.instanceId||x.id)===machineId||x.id===machineId);if(!machine)throw new Error("Maschine fehlt");machine.condition=clamp(n(machine.condition,100)-Math.max(0,n(runtimeHours))*clamp(n(load,1),.1,2)*.08,0,100);machine.runtimeHours=n(machine.runtimeHours)+Math.max(0,n(runtimeHours));machine.lastUsedAt=now;if(machine.condition<25)machine.status="maintenance_required";return machine;}
export function maintenanceDue(c,machine,{now=Date.now(),intervalHours=250}={}){ensureMaintenance(c);const last=n(machine.lastMaintenanceRuntime,0);return n(machine.runtimeHours)-last>=n(machine.maintenanceIntervalHours,intervalHours)||n(machine.condition,100)<35;}
export function scheduleMaintenance(c,machineId,{durationHours=4,cost=250,now=Date.now()}={}){const m=ensureMaintenance(c),machine=c.buildingState.equipment.find(x=>(x.instanceId||x.id)===machineId||x.id===machineId);if(!machine)throw new Error("Maschine fehlt");if(machine.maintenanceEndsAt&&machine.maintenanceEndsAt>now)return{success:true,idempotent:true,machine};if(n(c.money)<n(cost))throw new Error("Nicht genug Geld für Wartung");c.money-=n(cost);machine.status="maintenance";machine.maintenanceEndsAt=now+Math.max(.1,n(durationHours))*3600000;m.records.push({machineId,cost:n(cost),startedAt:now,endsAt:machine.maintenanceEndsAt,status:"running"});return{success:true,machine};}
export function finishMaintenance(c,machineId,{now=Date.now(),force=false}={}){const m=ensureMaintenance(c),machine=c.buildingState.equipment.find(x=>(x.instanceId||x.id)===machineId||x.id===machineId);if(!machine)throw new Error("Maschine fehlt");if(!force&&n(machine.maintenanceEndsAt)>now)throw new Error("Wartung noch nicht fertig");machine.condition=clamp(n(machine.condition,100)+30,0,100);machine.status="available";machine.lastMaintenanceRuntime=n(machine.runtimeHours);machine.maintenanceEndsAt=null;const r=[...m.records].reverse().find(x=>x.machineId===machineId&&x.status==="running");if(r){r.status="done";r.finishedAt=now;}return machine;}
export function breakdownRisk(machine){const condition=clamp(n(machine.condition,100),0,100),hoursSince=Math.max(0,n(machine.runtimeHours)-n(machine.lastMaintenanceRuntime));return clamp((100-condition)/180+hoursSince/5000,0,.85);}
export function maintenanceKpis(c){const m=ensureMaintenance(c),machines=c.buildingState.equipment||[];return{machines:machines.length,due:machines.filter(x=>maintenanceDue(c,x)).length,unavailable:machines.filter(x=>["maintenance","broken"].includes(x.status)).length,averageCondition:machines.length?machines.reduce((s,x)=>s+n(x.condition,100),0)/machines.length:100,records:m.records.length,incidents:m.incidents.length};}
