// WorldProject – branchenspezifische Bewerberverfügbarkeit für bestehende Personalansichten.
import { worldContentRegistry } from './ContentRegistry.js';
import { recipesForCompany } from './OperationalSupplyChainSystem.js';
import { getIndustryProfile } from './IndustryCatalog.js';
const roleOf=e=>e?.role||e?.jobId||e?.profession||null;
const activeEmployee=e=>e&&e.active!==false&&!['notice','dismissed','terminated','inactive','fired'].includes(String(e.status||'').toLowerCase());
const DEFAULT_REQUIRED_ROLE={brewery:'brew_master',carpentry:'carpenter',bakery:'baker',butcher:'butcher',farm:'farmer',livestock:'farmer',orchard:'farmer',food:'machine_operator',mechanical:'machine_operator',metal:'machine_operator',plastic:'machine_operator'};
const machineId=m=>m?.sourceType||m?.type||m?.equipmentId||m?.id||null;
const machineLabel=m=>m?.name||m?.label||worldContentRegistry.get('machines',machineId(m))?.label||'';
function ownedMachines(company){const all=[...(company?.buildingState?.equipment||[]),...(company?.workforceState?.machines||[]),...(company?.workforceOperationsState?.machines||[]),...(company?.machines||[])],seen=new Set(),out=[];for(const m of all){if(!m||m.status==='sold')continue;const id=machineId(m),label=machineLabel(m),key=String(id||label).toLowerCase().replace(/[^a-z0-9äöüß]+/g,'');if(!key||seen.has(key))continue;seen.add(key);out.push(m);}return out;}
function machineRole(company,m){const key=getIndustryProfile(company)?.branchKey||company?.branchKey,raw=String(machineId(m)||'').toLowerCase(),text=`${raw} ${String(machineLabel(m)).toLowerCase()}`;if(key==='brewery'){if(['brew_kettle','brewhouse','brew_house','sudwerk','sudhaus'].includes(raw)||/sud|brew|kessel/.test(text))return'brew_master';if(['fermentation_tank','fermenter','lager_tank','fermentation'].includes(raw)||/gär|gaer|ferment|lager.?tank/.test(text))return'cellar_worker';if(['filling_line','bottling_line'].includes(raw)||/abfüll|abfuell|füll|fuell|bottl|pack/.test(text))return'packaging_operator';if(['cooling','cooling_system','refrigeration'].includes(raw)||/kühl|kuehl|cool|refrig/.test(text))return'maintenance_tech';if(raw==='production_line'||/produktion|production/.test(text))return'machine_operator';}if(key==='beverage'&&(['filling_line','bottling_line'].includes(raw)||/abfüll|abfuell|bottl|pack/.test(text)))return'packaging_operator';return null;}
export function machineRequiredRoles(company){return[...new Set(ownedMachines(company).map(m=>machineRole(company,m)).filter(Boolean))];}
export function jobRolesForCompany(company){const key=getIndustryProfile(company)?.branchKey||company?.branchKey;return worldContentRegistry.list('jobs').filter(job=>{const industries=job.industries||[];return industries.includes('*')||industries.includes(key);});}
export function requiredRolesForCompany(company){const roles=new Set(recipesForCompany(company).map(r=>r.requiredRole).filter(Boolean)),key=getIndustryProfile(company)?.branchKey||company?.branchKey,defaultRole=DEFAULT_REQUIRED_ROLE[key];for(const role of machineRequiredRoles(company))roles.add(role);if(defaultRole)roles.add(defaultRole);return [...roles];}
export function missingRequiredRoles(company){const employees=(company?.workforceState?.employees||company?.workforceOperationsState?.employees||company?.employees||[]).filter(activeEmployee),owned=new Set(employees.flatMap(e=>[roleOf(e),...(e.roles||[])].filter(Boolean)));return requiredRolesForCompany(company).filter(role=>!owned.has(role));}
export function availableCandidates(company,{count=8}={}){const jobs=jobRolesForCompany(company),required=new Set(missingRequiredRoles(company)),rows=[];for(const role of required){const job=jobs.find(x=>x.id===role)||worldContentRegistry.get('jobs',role);if(job)rows.push({id:`candidate-${job.id}-required`,role:job.id,label:job.label||job.id,baseWage:Number(job.baseWageMonthly??job.baseWage??0),skills:[...(job.skills||[])],tags:[...(job.tags||[])],required:true});}for(const job of jobs){if(rows.length>=count)break;if(rows.some(x=>x.role===job.id))continue;rows.push({id:`candidate-${job.id}`,role:job.id,label:job.label||job.id,baseWage:Number(job.baseWageMonthly??job.baseWage??0),skills:[...(job.skills||[])],tags:[...(job.tags||[])],required:false});}return rows;}
if(typeof window!=='undefined')window.worldIndustryRecruitment={roles:jobRolesForCompany,required:requiredRolesForCompany,machineRequired:machineRequiredRoles,missing:missingRequiredRoles,candidates:availableCandidates};
