// WorldProject – Lagerkern für alle Gewerbe: Zonen, Kapazität, Chargen, FIFO/FEFO, Haltbarkeit.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureWarehouse(c={}){c.warehouse??={zones:{raw:{capacity:10000},cold:{capacity:5000},packaging:{capacity:10000},finished:{capacity:10000}},lots:[],movements:[],reservations:[]};return c.warehouse;}
export function zoneUsage(c,zone){const w=ensureWarehouse(c),lots=w.lots.filter(x=>x.zone===zone&&x.quantity>0),used=lots.reduce((s,x)=>s+n(x.quantity)*n(x.volumePerUnit,1),0),capacity=n(w.zones[zone]?.capacity);return{zone,used,capacity,free:Math.max(0,capacity-used),utilization:capacity?used/capacity:0};}
export function receiveLot(c,{item,quantity,zone="raw",unit="kg",volumePerUnit=1,expiresAt=null,quality=1,source=null,now=Date.now()}={}){const w=ensureWarehouse(c),q=Math.max(0,n(quantity)),u=zoneUsage(c,zone);if(!w.zones[zone])throw new Error("Lagerzone fehlt");if(q*n(volumePerUnit,1)>u.free+1e-9)throw new Error("Lagerkapazität reicht nicht");const lot={id:`lot-${now}-${Math.random().toString(36).slice(2,7)}`,item,quantity:q,zone,unit,volumePerUnit:n(volumePerUnit,1),expiresAt:expiresAt?Number(expiresAt):null,quality:n(quality,1),source,receivedAt:now};w.lots.push(lot);c.inventory??={};c.inventory[item]=n(c.inventory[item])+q;w.movements.push({kind:"receive",lotId:lot.id,item,quantity:q,at:now});return lot;}
export function availableLots(c,item,{now=Date.now()}={}){return ensureWarehouse(c).lots.filter(x=>x.item===item&&x.quantity>0&&(!x.expiresAt||x.expiresAt>now)).sort((a,b)=>(a.expiresAt||Infinity)-(b.expiresAt||Infinity)||a.receivedAt-b.receivedAt);}
export function reserveStock(c,item,quantity,{reference,now=Date.now()}={}){const w=ensureWarehouse(c),q=Math.max(0,n(quantity)),already=w.reservations.filter(x=>x.item===item&&x.status==="active").reduce((s,x)=>s+n(x.quantity),0),available=Math.max(0,n(c.inventory?.[item])-already);if(available+1e-9<q)throw new Error("Nicht genug freier Lagerbestand");const r={id:`res-${now}-${Math.random().toString(36).slice(2,6)}`,item,quantity:q,reference,status:"active",createdAt:now};w.reservations.push(r);return r;}
export function consumeStock(c,item,quantity,{reference,now=Date.now()}={}){const w=ensureWarehouse(c),q=Math.max(0,n(quantity));if(n(c.inventory?.[item])+1e-9<q)throw new Error("Nicht genug Bestand");let left=q;for(const lot of availableLots(c,item,{now})){const take=Math.min(left,n(lot.quantity));lot.quantity-=take;left-=take;w.movements.push({kind:"consume",lotId:lot.id,item,quantity:take,reference,at:now});if(left<=1e-9)break;}c.inventory[item]=Math.max(0,n(c.inventory[item])-q);return{success:true,quantity:q};}
export function expireLots(c,{now=Date.now()}={}){const w=ensureWarehouse(c),expired=[];for(const lot of w.lots.filter(x=>x.quantity>0&&x.expiresAt&&x.expiresAt<=now)){const q=n(lot.quantity);lot.quantity=0;c.inventory??={};c.inventory[lot.item]=Math.max(0,n(c.inventory[lot.item])-q);expired.push({item:lot.item,quantity:q,lotId:lot.id});w.movements.push({kind:"expired",lotId:lot.id,item:lot.item,quantity:q,at:now});}return expired;}
export function warehouseKpis(c){const w=ensureWarehouse(c),zones=Object.keys(w.zones).map(z=>zoneUsage(c,z));return{zones,lots:w.lots.filter(x=>x.quantity>0).length,reserved:w.reservations.filter(x=>x.status==="active").reduce((s,x)=>s+n(x.quantity),0),criticalZones:zones.filter(x=>x.utilization>=.9).map(x=>x.zone)};}
