// WorldProject – universeller Maschinen-/Ausstattungsmarkt für ALLE Gewerbe.
// Verwendet ausschließlich den bestehenden IndustryCatalog und buildingState.
import { equipmentFor, requiredEquipmentFor, setupProgress } from './IndustryCatalog.js';
import { compatibleMachineIds } from './IndustryMachineCompatibility.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const equipmentList=c=>{c.buildingState??={rooms:[],equipment:[]};c.buildingState.equipment??=[];return c.buildingState.equipment;};
const ownedIds=c=>equipmentList(c).map(x=>typeof x==='string'?x:x.id).filter(Boolean);
export function equipmentMarketplace(company){const owned=ownedIds(company),required=new Set(requiredEquipmentFor(company));return equipmentFor(company).map(item=>({...item,required:required.has(item.id),owned:owned.includes(item.id),affordable:n(company.money)>=n(item.price),missing:!owned.includes(item.id)}));}
export function equipmentForMachineRequirement(company,machineType){const choices=new Set(compatibleMachineIds(company,machineType));return equipmentMarketplace(company).filter(x=>choices.has(x.id));}
export function buyIndustryEquipment(company,equipmentId,{requestId=null,now=Date.now()}={}){const item=equipmentFor(company).find(x=>x.id===equipmentId);if(!item)throw new Error('Ausstattung ist für dieses Gewerbe nicht verfügbar');company.equipmentPurchaseRequestIds??=[];if(requestId&&company.equipmentPurchaseRequestIds.includes(requestId))return{success:true,idempotent:true,item:equipmentList(company).find(x=>(typeof x==='string'?x:x.id)===equipmentId)||null,progress:setupProgress(company)};if(ownedIds(company).includes(equipmentId))throw new Error(`${item.name} ist bereits vorhanden`);const price=Math.max(0,n(item.price));if(n(company.money)<price)throw new Error(`Nicht genug Geld: ${item.name} kostet ${price.toLocaleString('de-DE')} €`);const instance={...item,instanceId:`eq-${equipmentId}-${now}-${Math.random().toString(36).slice(2,6)}`,status:'available',condition:100,purchasedAt:now,purchasePrice:price};equipmentList(company).push(instance);company.money=n(company.money)-price;company.costLedger??=[];company.costLedger.push({kind:'equipment_purchase',equipmentId,instanceId:instance.instanceId,amount:price,at:now,requestId});if(requestId)company.equipmentPurchaseRequestIds.push(requestId);const progress=setupProgress(company);company.setupPhase=progress.complete?'operational':'equipment_setup';company.buildingState.ready=progress.complete;return{success:true,item:instance,price,balance:company.money,progress};}
export function equipmentSetupVM(company){const market=equipmentMarketplace(company),progress=setupProgress(company);return{progress,required:market.filter(x=>x.required),optional:market.filter(x=>!x.required),missingRequired:market.filter(x=>x.required&&!x.owned),owned:market.filter(x=>x.owned),totalMissingCost:market.filter(x=>x.required&&!x.owned).reduce((s,x)=>s+n(x.price),0),canComplete:progress.complete};}
export async function persistIndustryEquipment(company){const api=window.worldAccounts?.authApi,id=company.serverCompanyId;if(!api||!id)return{success:false,persisted:false,reason:'Server-API/Betrieb fehlt'};if(typeof api.updateBusinessSetup==='function')await api.updateBusinessSetup(id,company.setupPhase||'equipment_setup',company.buildingState);if(typeof api.saveBusinessState==='function'){const state={};for(const[k,v]of Object.entries(company))if(!['buildingState','gigaTransportService','constructionManagers','market','transportSystem'].includes(k)&&typeof v!=='function')state[k]=v;await api.saveBusinessState(id,state);}window.worldActiveServerCompany={...(window.worldActiveServerCompany||{}),building_state:company.buildingState,setup_phase:company.setupPhase};return{success:true,persisted:true};}
if(typeof window!=='undefined')window.worldIndustryEquipment={marketplace:equipmentMarketplace,forRequirement:equipmentForMachineRequirement,buy:buyIndustryEquipment,setupVM:equipmentSetupVM,persist:persistIndustryEquipment};
