// WorldProject - spielbare Vorlieferanten und Verarbeiter für die geschlossene Wirtschaftskette.
import { IndustryProfiles, IndustryGroups } from "./IndustryCatalog.js";
const roomsDefault=[{id:"production",name:"Produktionsbereich",areaM2:180},{id:"storage",name:"Lager",areaM2:100},{id:"office",name:"Büro",areaM2:20}];
const add=(type,branchKey,label,equipment,allowedItems=[],products=[],recipes=[],rooms=roomsDefault)=>{if(IndustryProfiles[type])return;const requiredEquipment=equipment.filter(x=>x.required!==false).map(x=>x.id);IndustryProfiles[type]={branchKey,label,starterBuilding:{name:`Leerer Betrieb – ${label}`,areaM2:rooms.reduce((s,r)=>s+r.areaM2,0),rooms:rooms.map(r=>({...r}))},equipment,requiredEquipment,allowedItems,products,recipes};};
const machine=(id,name,price,required=true,room="production")=>({id,name,price,required,room});
add("Forstbetrieb","forestry","Forstbetrieb",[machine("forestry_harvester","Forstmaschine",42000),machine("forwarder","Rückezug",31000,false)],["forest_seedlings","diesel"],["roundwood_soft","roundwood_hard"],["forestry_softwood","forestry_hardwood"],[{id:"yard",name:"Forsthof",areaM2:220},{id:"forest",name:"Bewirtschaftete Waldfläche",areaM2:1500},{id:"storage",name:"Holzlager",areaM2:240},{id:"office",name:"Büro",areaM2:20}]);
add("Sägewerk","sawmill","Sägewerk",[machine("sawmill_line","Sägewerkslinie",26000),machine("log_loader","Rundholz-Lader",14500,false)],["roundwood_soft","roundwood_hard"],["softwood","hardwood","wood_chips"],["saw_softwood","saw_hardwood","sawmill_fiberwood"]);
add("Mühle","mill","Mühle",[machine("grain_mill","Getreidemühle",22000),machine("grain_cleaner","Getreidereinigung",8500)],["wheat"],["flour_wheat"],["mill_wheat"]);
add("Mälzerei","maltster","Mälzerei",[machine("malting_line","Mälzereianlage",34000),machine("malt_silo","Malzsilo",11000)],["barley","water"],["malt"],["malt_barley"]);
add("Hopfenbaubetrieb","hops_farm","Hopfenbaubetrieb",[machine("hop_harvester","Hopfenerntetechnik",26000),machine("hop_dryer","Hopfendarre",14500)],["fertilizer","diesel"],["hops"],["grow_hops"],[{id:"yard",name:"Betriebshof",areaM2:220},{id:"fields",name:"Hopfenflächen",areaM2:1200},{id:"storage",name:"Hopfenlager",areaM2:160},{id:"office",name:"Büro",areaM2:20}]);
add("Zuckerfabrik","sugar_factory","Zuckerfabrik",[machine("sugar_line","Zuckerraffinerie",39000),machine("sugar_silo","Zuckersilo",12000)],["sugar_beet","water"],["sugar"],["refine_sugar"]);
add("Futtermühle","feed_mill","Futtermühle",[machine("feed_mixer","Futtermischanlage",21000),machine("feed_silo","Futtersilo",9500)],["corn","wheat","barley"],["animal_feed"],["feed_mix"]);
add("Molkerei","dairy","Molkerei",[machine("dairy_line","Molkereianlage",31000),machine("dairy_cooling","Milchkühlung",13000)],["milk"],["butter","cream"],["dairy_butter","dairy_cream"]);
add("Schlachthof","slaughterhouse","Schlachthof",[machine("slaughter_line","Verarbeitungslinie",42000),machine("cold_room","Kühlhaus",18000)],["cattle","pigs"],["beef","pork"],["slaughter_beef","slaughter_pork"]);
add("Glaswerk","glassworks","Glaswerk / Flaschenhersteller",[machine("glass_furnace","Glasschmelzofen",52000),machine("bottle_former","Flaschenformmaschine",33000)],["silica_sand","soda_ash","limestone"],["bottles","bottles_050"],["glass_033","glass_050"]);
add("Verschlusshersteller","closures","Verschlusshersteller",[machine("cap_press","Kronkorkenpresse",28000),machine("cap_coater","Beschichtungsanlage",11500,false)],["steel_sheet"],["caps"],["caps_make"]);
add("Papierfabrik","paper_mill","Papierfabrik",[machine("paper_machine","Papiermaschine",43000),machine("pulp_prep","Stoffaufbereitung",16500)],["wood_chips","water"],["paper_roll","cardboard"],["paper_make","cardboard_make"]);
add("Etikettendruckerei","label_print","Etikettendruckerei",[machine("label_press","Etikettendruckmaschine",24000),machine("die_cutter","Stanzanlage",9000)],["paper_roll","printing_ink"],["labels","labels_050"],["labels_033_make","labels_050_make"]);
add("Verpackungshersteller","packaging_maker","Verpackungshersteller",[machine("packaging_line","Verpackungslinie",27000),machine("cardboard_cutter","Kartonstanze",10500)],["cardboard","paper_roll","plastic_granulate","softwood"],["shipping_box","bakery_bag","meat_packaging","fruit_crate"],["shipping_boxes_make","bakery_bags_make","meat_pack_make","fruit_crates_make"]);
add("Stahlwerk","steelworks","Stahlwerk",[machine("rolling_mill","Walzwerk",56000),machine("steel_furnace","Stahlofen",48000,false)],["steel_coil"],["steel_sheet","steel_bar"],["steel_sheet_make","steel_bar_make"]);
add("Kunststoffrohstoffwerk","polymer","Kunststoffrohstoffwerk",[machine("polymer_line","Polymeranlage",49000),machine("pelletizer","Granulieranlage",19000)],["plastic_feedstock"],["plastic_granulate"],["plastic_granulate_make"]);
add("Lebensmittelchemie","food_chemicals","Lebensmittelchemie",[machine("chemical_mixer","Lebensmittel-Mischreaktor",32000),machine("lab_station","Qualitätslabor",12000)],["water"],["citric_acid","beverage_flavour","bottle_wash_chem"],["citric_acid_make","flavour_make","wash_chem_make"]);
add("Agrarchemie","agri_chemicals","Agrarchemie",[machine("fertilizer_line","Düngeranlage",36000),machine("bulk_loader","Schüttgutverladung",9000,false)],["water"],["fertilizer"],["fertilizer_make"]);
const addGroup=(name,types)=>{IndustryGroups[name]??=[];for(const type of types)if(!IndustryGroups[name].includes(type))IndustryGroups[name].push(type);};
addGroup("Rohstoffgewinnung",["Forstbetrieb","Hopfenbaubetrieb"]);addGroup("Agrarverarbeitung",["Mühle","Mälzerei","Zuckerfabrik","Futtermühle","Molkerei","Schlachthof"]);addGroup("Grundstoffindustrie",["Sägewerk","Glaswerk","Stahlwerk","Kunststoffrohstoffwerk","Papierfabrik","Lebensmittelchemie","Agrarchemie"]);addGroup("Verpackung",["Verschlusshersteller","Etikettendruckerei","Verpackungshersteller"]);
export function runIndustryChainCatalogTest(){const required=["Forstbetrieb","Sägewerk","Mühle","Mälzerei","Hopfenbaubetrieb","Glaswerk","Verschlusshersteller","Etikettendruckerei","Futtermühle","Molkerei","Schlachthof","Stahlwerk","Kunststoffrohstoffwerk"],missing=required.filter(x=>!IndustryProfiles[x]);const success=missing.length===0&&IndustryProfiles["Mühle"].products.includes("flour_wheat")&&IndustryProfiles["Mälzerei"].products.includes("malt")&&IndustryProfiles.Glaswerk.products.includes("bottles")&&IndustryProfiles.Verschlusshersteller.products.includes("caps");if(!success)throw new Error(`Wirtschaftsketten-Gewerbe fehlen oder sind nicht verbunden: ${missing.join(", ")}`);return{success,count:required.length};}
