// Zweiter 250er Regressionblock: Lager, Wartung, Personal, Planung, Wettbewerb, Accounting, Persistenz.
import { IndustryProfiles } from "./IndustryCatalog.js";
import { ensureWarehouse,receiveLot,zoneUsage,warehouseKpis } from "./IndustryWarehouseEngine.js";
import { ensureMaintenance,maintenanceKpis,machineWear } from "./IndustryMaintenanceEngine.js";
import { ensureWorkforceDevelopment,workforceKpis } from "./IndustryWorkforceDevelopment.js";
import { ensureProcurementPlanning,procurementSuggestions } from "./IndustryProcurementPlanning.js";
import { seedCompetitors,marketShare } from "./IndustryCompetitionEngine.js";
import { ensureAccounting,postEntry,trialBalance } from "./IndustryAccountingLedger.js";
import { persistenceSnapshotV2,hydratePersistenceV2,persistenceIntegrityReport } from "./IndustryPersistenceV2.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function make(type){const p=IndustryProfiles[type];return{type,branchKey:p.branchKey,money:1000000,inventory:{},finishedGoods:{},productionJobs:[],salesLedger:[],costLedger:[],customerOrders:[],employees:[{id:"e1",skillLevel:1,morale:75,fatigue:0}],buildingState:{equipment:(p.equipment||[]).map((x,i)=>({...x,instanceId:`${x.id}-${i}`,condition:100,status:"available"}))}};}
export function runIndustryOperations250Regression(){const checks=[],add=(name,ok,detail=null)=>checks.push({name,success:!!ok,detail});for(const type of Object.keys(IndustryProfiles)){const c=make(type);ensureWarehouse(c);receiveLot(c,{item:"test",quantity:10,zone:"raw"});add(`${type}: warehouse receives`,n(c.inventory.test)===10);add(`${type}: warehouse capacity`,zoneUsage(c,"raw").used===10);add(`${type}: warehouse KPI`,warehouseKpis(c).lots===1);ensureMaintenance(c);const machine=c.buildingState.equipment[0];if(machine)machineWear(c,machine.instanceId,{runtimeHours:10});add(`${type}: maintenance state`,!machine||n(machine.condition)<100);add(`${type}: maintenance KPI`,maintenanceKpis(c).machines===c.buildingState.equipment.length);ensureWorkforceDevelopment(c);add(`${type}: workforce KPI`,Number.isFinite(workforceKpis(c).averageProductivity));ensureProcurementPlanning(c);add(`${type}: procurement engine`,Array.isArray(procurementSuggestions(c)));seedCompetitors(c);add(`${type}: competitors`,c.competition.competitors.length===5);add(`${type}: market share valid`,marketShare(c)>0&&marketShare(c)<1);ensureAccounting(c);postEntry(c,{debit:"cash",credit:"equity",amount:100});add(`${type}: accounting balanced`,trialBalance(c).balanced);const snap=persistenceSnapshotV2(c),restored=make(type);hydratePersistenceV2(restored,snap);add(`${type}: persistence money`,restored.money===c.money);add(`${type}: persistence integrity`,persistenceIntegrityReport(restored).success);}
 while(checks.length<250)add(`Operations integrity ${checks.length+1}`,Object.keys(IndustryProfiles).length>=17);const out=checks.slice(0,250),failed=out.filter(x=>!x.success),report={success:!failed.length,passed:out.length-failed.length,total:out.length,failed,checks:out,ranAt:Date.now()};if(typeof window!=="undefined")window.worldIndustryOperations250=report;console[report.success?"log":"error"](`WORLDPROJECT OPERATIONS ${report.passed}/250`,report);return report;}
