// WorldProject – Forschung/Innovation als Projektpipeline.
import { getIndustryProfile } from './IndustryCatalog.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const THEMES={brewery:['process_efficiency','new_recipe','packaging'],beverage:['new_recipe','energy_efficiency','packaging'],bakery:['recipe_quality','energy_efficiency','automation'],butcher:['quality_control','cold_chain','automation'],food:['recipe_quality','automation','packaging'],farm:['yield','fuel_efficiency','crop_quality'],livestock:['animal_health','feed_efficiency','yield'],orchard:['yield','storage_quality','harvest_efficiency'],carpentry:['material_efficiency','automation','design'],mechanical:['precision','automation','new_product'],metal:['material_efficiency','automation','precision'],plastic:['material_efficiency','energy_efficiency','new_product'],retail:['analytics','store_efficiency','customer_service'],wholesale:['warehouse_efficiency','analytics','logistics'],online_retail:['fulfillment','analytics','automation']};
export function ensureInnovation(c={}){c.innovation??={projects:[],unlocks:[],patents:[],knowledge:0,failures:0};return c.innovation;}
export function innovationThemes(c){const key=c.branchKey||getIndustryProfile(c).branchKey;return THEMES[key]||['efficiency','quality','automation'];}
export function startInnovationProject(c,{theme,cost=10000,durationDays=30,risk=.2}={}){const s=ensureInnovation(c);if(!innovationThemes(c).includes(theme))throw new Error('Forschungsthema für Branche nicht verfügbar');if(n(c.money)<n(cost))throw new Error('Forschungsbudget reicht nicht');c.money-=n(cost);const p={id:`rd-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,theme,cost:n(cost),durationDays:n(durationDays),risk:clamp(n(risk,.2),0,.8),progress:0,status:'running',startedAt:Date.now(),endsAt:Date.now()+n(durationDays)*86400000,prototypeQuality:0};s.projects.push(p);return p;}
export function advanceInnovation(c,projectId,{days=1,engineeringSkill=1}={}){const s=ensureInnovation(c),p=s.projects.find(x=>x.id===projectId);if(!p)throw new Error('Forschungsprojekt fehlt');if(p.status!=='running')return p;p.progress=clamp(p.progress+n(days)/Math.max(1,p.durationDays)*Math.max(.5,n(engineeringSkill,1)),0,1);p.prototypeQuality=clamp(p.prototypeQuality+n(days)*.8*n(engineeringSkill,1),0,100);if(p.progress>=1){const deterministic=((p.id.length*13+Math.round(p.cost))%100)/100;p.status=deterministic<p.risk?'failed':'prototype';if(p.status==='failed')s.failures++;else s.knowledge+=Math.max(1,Math.round(p.cost/5000));}return p;}
export function testPrototype(c,projectId,{testBudget=2000}={}){const s=ensureInnovation(c),p=s.projects.find(x=>x.id===projectId);if(!p||p.status!=='prototype')throw new Error('Kein testbarer Prototyp');if(n(c.money)<n(testBudget))throw new Error('Testbudget reicht nicht');c.money-=n(testBudget);const score=clamp(p.prototypeQuality+Math.log10(1+n(testBudget))*8,0,100);p.testScore=score;p.status=score>=60?'validated':'failed';if(p.status==='failed')s.failures++;return p;}
export function commercializeInnovation(c,projectId){const s=ensureInnovation(c),p=s.projects.find(x=>x.id===projectId);if(!p||p.status!=='validated')throw new Error('Innovation noch nicht freigegeben');const unlock={id:`unlock-${p.theme}-${Date.now()}`,theme:p.theme,quality:p.testScore,unlockedAt:Date.now(),effects:effectsFor(p.theme,p.testScore)};s.unlocks.push(unlock);p.status='commercialized';return unlock;}
function effectsFor(theme,score){const q=clamp(n(score)/100,.5,1);if(theme.includes('quality')||theme==='precision')return{qualityBonus:.08*q};if(theme.includes('energy')||theme.includes('fuel'))return{energyMultiplier:1-.1*q};if(theme.includes('material')||theme.includes('feed'))return{materialMultiplier:1-.08*q};if(theme.includes('automation')||theme==='fulfillment')return{timeMultiplier:1-.1*q};if(theme.includes('yield'))return{outputMultiplier:1+.1*q};return{demandMultiplier:1+.05*q};}
export function filePatent(c,projectId,{fee=3000,durationDays=3650}={}){const s=ensureInnovation(c),p=s.projects.find(x=>x.id===projectId);if(!p||p.status!=='commercialized')throw new Error('Nur kommerzialisierte Innovation patentierbar');if(n(c.money)<fee)throw new Error('Patentgebühr nicht verfügbar');c.money-=fee;const patent={id:`pat-${Date.now()}`,projectId,theme:p.theme,startsAt:Date.now(),endsAt:Date.now()+durationDays*86400000,status:'active'};s.patents.push(patent);return patent;}
if(typeof window!=='undefined')window.worldInnovation={themes:innovationThemes,start:startInnovationProject,advance:advanceInnovation,test:testPrototype,commercialize:commercializeInnovation,patent:filePatent};
