// WorldProject – Versicherungsfälle auf Basis bestehender Policen/Risiken.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureClaims(c={}){c.insuranceClaims??={claims:[],history:[],fraudScore:0};return c.insuranceClaims;}
function activePolicy(c,kind){return(c.risk?.insurance||[]).find(x=>x.status==='active'&&(x.policyId===kind||x.policyId==='business'))||null;}
export function fileInsuranceClaim(c,{kind='machine',grossLoss=0,description='',evidenceScore=.8,at=Date.now()}={}){const s=ensureClaims(c),policy=activePolicy(c,kind);if(!policy)throw new Error('Kein passender Versicherungsschutz');const row={id:`claim-${at}-${Math.random().toString(36).slice(2,6)}`,kind,grossLoss:Math.max(0,n(grossLoss)),description,evidenceScore:clamp(n(evidenceScore,.8),0,1),policyId:policy.policyId,status:'submitted',submittedAt:at,requested:Math.max(0,n(grossLoss)-n(policy.deductible))*n(policy.coverage,0)};s.claims.push(row);return row;}
export function assessInsuranceClaim(c,claimId,{manualRisk=0}={}){const s=ensureClaims(c),x=s.claims.find(a=>a.id===claimId);if(!x)throw new Error('Schadenfall fehlt');if(!['submitted','review'].includes(x.status))return x;const policy=activePolicy(c,x.kind),fraudRisk=clamp((1-x.evidenceScore)*.7+n(manualRisk)*.3+s.fraudScore/200,0,1);x.fraudRisk=fraudRisk;if(!policy){x.status='denied';x.reason='Policy nicht mehr aktiv';return x;}if(fraudRisk>.7){x.status='review';x.reason='Zusätzliche Prüfung erforderlich';return x;}const reduction=fraudRisk*.25;x.approvedAmount=Math.max(0,x.requested*(1-reduction));x.status=x.approvedAmount>0?'approved':'denied';x.assessedAt=Date.now();return x;}
export function settleInsuranceClaim(c,claimId){const s=ensureClaims(c),x=s.claims.find(a=>a.id===claimId);if(!x)throw new Error('Schadenfall fehlt');if(x.status==='paid')return{success:true,idempotent:true,amount:x.paidAmount};if(x.status!=='approved')throw new Error('Schaden nicht freigegeben');c.money=n(c.money)+n(x.approvedAmount);x.status='paid';x.paidAmount=n(x.approvedAmount);x.paidAt=Date.now();s.history.push({...x});return{success:true,amount:x.paidAmount,balance:c.money};}
export function denyInsuranceClaim(c,claimId,{reason='Nicht gedeckt',fraud=false}={}){const s=ensureClaims(c),x=s.claims.find(a=>a.id===claimId);if(!x)throw new Error('Schadenfall fehlt');x.status='denied';x.reason=reason;x.deniedAt=Date.now();if(fraud)s.fraudScore=clamp(s.fraudScore+15,0,100);return x;}
export function insuranceClaimsKpis(c){const s=ensureClaims(c);return{open:s.claims.filter(x=>['submitted','review','approved'].includes(x.status)).length,paid:s.claims.filter(x=>x.status==='paid').length,denied:s.claims.filter(x=>x.status==='denied').length,paidTotal:s.claims.reduce((a,x)=>a+n(x.paidAmount),0),fraudScore:s.fraudScore};}
