// WorldProject – realistische Integrationschecks über Kernpfade. Keine künstlichen Platzhalterchecks.
import { IndustryProfiles } from './IndustryCatalog.js';
import { industryRecipes, procureInstantForTest, startIndustryJob, finishIndustryJob, sellIndustryOutput } from './UniversalIndustryCycle.js';
import { machineCatalogFor, buyMachine } from './UniversalBusinessOperations.js';
import { persistenceSnapshotV2, hydratePersistenceV2, persistenceIntegrityReport } from './IndustryPersistenceV2.js';
import { createPurchaseRequest, sourceQuotes } from './AdvancedProcurementWorkflow.js';
import { machineProductionKpis } from './AdvancedMachineProductionControl.js';
import { shiftPlanningKpis } from './AdvancedWorkforceScheduling.js';
import { financeControlKpis } from './IntegratedFinanceController.js';
import { worldEconomyKpis, tickEconomy } from './WorldEconomySimulation.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function fresh(type){const p=IndustryProfiles[type];return{type,branchKey:p.branchKey,money:1000000,inventory:{},finishedGoods:{},productionJobs:[],salesLedger:[],costLedger:[],buildingState:{equipment:[]},employees:[],customerOrders:[]};}
export function checkIndustryCorePath(type){const checks=[],add=(name,ok,detail=null)=>checks.push({name,success:!!ok,detail});const c=fresh(type),recipes=industryRecipes(c),catalog=machineCatalogFor(c);add('recipe_available',recipes.length>0);add('machine_catalog_available',catalog.length>0);for(const id of IndustryProfiles[type].requiredEquipment||[]){const def=catalog.find(x=>x.id===id);if(def){try{buyMachine(c,id,{requestId:`hc-${type}-${id}`});}catch(e){add(`buy_${id}`,false,e.message);}}}
 const r=recipes[0];if(r){for(const[item,q]of Object.entries(r.materials||{})){try{procureInstantForTest(c,item,Math.max(1,n(q)));add(`procure_${item}`,true);}catch(e){add(`procure_${item}`,false,e.message);}}try{const job=startIndustryJob(c,r.id,Math.max(1,n(r.output,1)),{requestId:`hc-job-${type}`,now:1000});add('job_start',!!job.job);finishIndustryJob(c,job.job.id,{force:true,now:2000});add('job_finish',n(c.finishedGoods[r.product])>0);const before=c.money,sale=sellIndustryOutput(c,r.product,Math.max(1,n(r.output,1)),Math.max(1,n(r.variableCost,10)/Math.max(1,n(r.output,1))+5),{requestId:`hc-sale-${type}`,now:3000});add('sale',sale.revenue>0&&c.money>before);}catch(e){add('job_or_sale',false,e.message);}}
 const snap=persistenceSnapshotV2(c),restored=fresh(type);hydratePersistenceV2(restored,snap);add('persistence_integrity',persistenceIntegrityReport(restored).success);add('money_persisted',restored.money===c.money);try{const pr=createPurchaseRequest(c,{item:Object.keys(r?.materials||{})[0]||'x',quantity:1});add('purchase_request',!!pr.id);const quotes=sourceQuotes(c,pr.id);add('supplier_quotes',Array.isArray(quotes));}catch(e){add('procurement_workflow',false,e.message);}add('machine_kpis',Number.isFinite(machineProductionKpis(c).machines));add('shift_kpis',Number.isFinite(shiftPlanningKpis(c).gaps));add('finance_kpis',Number.isFinite(financeControlKpis(c).cash));const failed=checks.filter(x=>!x.success);return{type,success:!failed.length,checks,failed};}
export function runIntegratedGameplayHealthCheck(){const types=Object.keys(IndustryProfiles),industryResults=types.map(checkIndustryCorePath),world={};tickEconomy(world,{days:90});const worldKpi=worldEconomyKpis(world),worldChecks=[{name:'world_day_progress',success:worldKpi.day===90},{name:'world_indices_finite',success:['gdpIndex','inflation','interestRate','energyIndex','commodityIndex','consumerConfidence'].every(k=>Number.isFinite(worldKpi[k]))}];const failedIndustries=industryResults.filter(x=>!x.success),failedWorld=worldChecks.filter(x=>!x.success),report={success:!failedIndustries.length&&!failedWorld.length,totalIndustries:types.length,passedIndustries:types.length-failedIndustries.length,failedIndustries,industryResults,worldChecks,worldKpi,ranAt:Date.now()};if(typeof window!=='undefined')window.worldIntegratedGameplayHealth=report;console[report.success?'log':'error'](`WORLDPROJECT INTEGRATED GAMEPLAY ${report.passedIndustries}/${report.totalIndustries} Gewerbe`,report);return report;}
