// WorldProject – direkte Handelsbeziehungen zwischen Betrieben.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureTradeNetwork(world={}){world.tradeNetwork??={agreements:[],shipments:[],history:[]};return world.tradeNetwork;}
export function createSupplyAgreement(world,{seller,buyer,productId,quantityPerCycle,unitPrice,cycleDays=7,minBuyerStock=0,startsAt=Date.now(),endsAt=null,internal=false}={}){const s=ensureTradeNetwork(world);if(!seller||!buyer||seller===buyer)throw new Error('Ungültige Vertragspartner');const row={id:`supply-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,sellerId:seller.serverCompanyId||seller.id,buyerId:buyer.serverCompanyId||buyer.id,sellerRef:seller,buyerRef:buyer,productId,quantityPerCycle:Math.max(0,n(quantityPerCycle)),unitPrice:Math.max(0,n(unitPrice)),cycleDays:Math.max(1,n(cycleDays)),minBuyerStock:Math.max(0,n(minBuyerStock)),startsAt,endsAt,status:'active',internal,nextDueAt:startsAt};s.agreements.push(row);return row;}
function stock(c,id){return n(c.finishedGoods?.[id])+n(c.inventory?.[id])+n(c.tradeInventory?.[id]);}
function take(c,id,q){c.finishedGoods??={};c.inventory??={};c.tradeInventory??={};let left=q;for(const bag of [c.finishedGoods,c.tradeInventory,c.inventory]){const x=Math.min(left,n(bag[id]));bag[id]=n(bag[id])-x;left-=x;if(!left)break;}return left<=0;}
export function executeSupplyCycle(world,agreementId,{now=Date.now()}={}){const s=ensureTradeNetwork(world),a=s.agreements.find(x=>x.id===agreementId);if(!a||a.status!=='active')throw new Error('Liefervertrag nicht aktiv');if(a.endsAt&&now>a.endsAt){a.status='ended';return{success:false,reason:'Vertrag beendet'};}if(now<a.nextDueAt)return{success:true,notDue:true};const buyerStock=stock(a.buyerRef,a.productId);if(buyerStock>a.minBuyerStock&&a.minBuyerStock>0){a.nextDueAt=now+a.cycleDays*86400000;return{success:true,skipped:'buyer_stock_sufficient'};}const q=Math.min(a.quantityPerCycle,stock(a.sellerRef,a.productId));if(q<=0)return{success:false,reason:'Verkäufer hat keinen Bestand'};const total=q*a.unitPrice;if(!a.internal&&n(a.buyerRef.money)<total)return{success:false,reason:'Käufer nicht liquide'};take(a.sellerRef,a.productId,q);a.buyerRef.inventory??={};a.buyerRef.inventory[a.productId]=n(a.buyerRef.inventory[a.productId])+q;if(!a.internal){a.buyerRef.money=n(a.buyerRef.money)-total;a.sellerRef.money=n(a.sellerRef.money)+total;}const shipment={id:`supply-shipment-${Date.now()}`,agreementId:a.id,productId:a.productId,quantity:q,total,from:a.sellerId,to:a.buyerId,at:now,status:'received'};s.shipments.push(shipment);s.history.push(shipment);a.nextDueAt=now+a.cycleDays*86400000;return{success:true,shipment};}
export function processDueAgreements(world,{now=Date.now()}={}){const s=ensureTradeNetwork(world),out=[];for(const a of s.agreements.filter(x=>x.status==='active'&&x.nextDueAt<=now)){try{out.push({agreementId:a.id,...executeSupplyCycle(world,a.id,{now})});}catch(error){out.push({agreementId:a.id,success:false,error:error.message});}}return out;}
export function tradeNetworkKpis(world){const s=ensureTradeNetwork(world);return{activeAgreements:s.agreements.filter(x=>x.status==='active').length,shipments:s.shipments.length,volume:s.shipments.reduce((x,y)=>x+n(y.total),0),internal:s.agreements.filter(x=>x.internal&&x.status==='active').length};}
