// WorldProject - Grundstuecke/Land zuerst kaufen, dann Betrieb bauen.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const ZONES={
 commercial:{label:'Gewerbegebiet',basePerM2:42,uses:['retail','wholesale','online_retail','bakery','butcher','food','beverage']},
 craft:{label:'Misch-/Handwerksgebiet',basePerM2:30,uses:['carpentry','mechanical','metal','plastic','bakery','butcher']},
 industrial:{label:'Industriegebiet',basePerM2:25,uses:['mechanical','metal','plastic','food','beverage','brewery']},
 rural:{label:'Ländliches Gewerbegebiet',basePerM2:16,uses:['brewery','beverage','carpentry','food','orchard','livestock','farm']},
 agricultural:{label:'Landwirtschaftsfläche',basePerM2:2.2,uses:['farm','orchard','livestock']}
};
const STARTER_NEEDS={
 brewery:{zone:['rural','industrial'],minM2:350},beverage:{zone:['rural','industrial','commercial'],minM2:280},carpentry:{zone:['craft','rural'],minM2:250},bakery:{zone:['commercial','craft'],minM2:160},butcher:{zone:['commercial','craft'],minM2:180},food:{zone:['craft','industrial'],minM2:250},farm:{zone:['agricultural'],minM2:10000},livestock:{zone:['agricultural','rural'],minM2:7000},orchard:{zone:['agricultural'],minM2:10000},mechanical:{zone:['craft','industrial'],minM2:300},metal:{zone:['craft','industrial'],minM2:300},plastic:{zone:['industrial','craft'],minM2:280},retail:{zone:['commercial'],minM2:120},wholesale:{zone:['commercial','industrial'],minM2:350},online_retail:{zone:['commercial','craft'],minM2:120}
};
export function propertyNeed(company={}){const branch=company.branchKey||company.industryKey||company.industry||({Brauerei:'brewery',Getränkehersteller:'beverage',Mineralbrunnen:'beverage',Schreinerei:'carpentry',Tischlerei:'carpentry',Bäckerei:'bakery',Metzgerei:'butcher',Lebensmittelhersteller:'food',Landwirtschaftsbetrieb:'farm',Tierhaltung:'livestock',Obstbau:'orchard',Maschinenbau:'mechanical',Metallverarbeitung:'metal',Kunststoffverarbeitung:'plastic',Einzelhandel:'retail',Großhandel:'wholesale',Onlinehandel:'online_retail'}[company.type||company.company_type]);return{branch,...(STARTER_NEEDS[branch]||{zone:['commercial','craft','industrial','rural'],minM2:150})};}
export function createLandParcel({regionId='default',zone='rural',areaM2=500,pricePerM2=null,roadAccess=true,utilities=true,soilQuality=.7,buildable=true}={}){const z=ZONES[zone]||ZONES.rural,ppm=pricePerM2==null?z.basePerM2:n(pricePerM2,z.basePerM2),area=Math.max(1,n(areaM2));return{id:uid('land'),regionId,zone,zoneLabel:z.label,areaM2:area,hectares:area/10000,pricePerM2:ppm,price:Math.round(area*ppm),roadAccess:Boolean(roadAccess),utilities:Boolean(utilities),soilQuality:Math.max(0,Math.min(1,n(soilQuality,.7))),buildable:Boolean(buildable),ownerId:null,status:'for_sale'};}
export function generateStarterParcels(company={},regionId='default'){const need=propertyNeed(company),zones=need.zone||['rural'];return zones.flatMap((zone,zi)=>[1,1.5,2].map((mult,i)=>createLandParcel({regionId,zone,areaM2:Math.round(need.minM2*mult),pricePerM2:(ZONES[zone]?.basePerM2||20)*(0.82+zi*.06+i*.08),utilities:zone!=='agricultural'||i>0,roadAccess:true,soilQuality:zone==='agricultural'?.55+i*.15:.7}))).sort((a,b)=>a.price-b.price);}
export function ensurePropertyState(owner={}){owner.propertyState??={owned:[],leased:[],history:[]};return owner.propertyState;}
export function buyLand(owner,parcel,{ownerId=null}={}){const s=ensurePropertyState(owner),money=n(owner.money);if(!parcel||parcel.status!=='for_sale')return{success:false,reason:'Grundstück ist nicht verfügbar'};if(money<n(parcel.price))return{success:false,reason:'Nicht genug Geld für dieses Grundstück',price:n(parcel.price),money};owner.money=money-n(parcel.price);parcel.status='owned';parcel.ownerId=ownerId||owner.id||owner.serverCompanyId||'player';parcel.boughtAt=Date.now();s.owned.push({...parcel});s.history.push({kind:'purchase',parcelId:parcel.id,price:parcel.price,at:Date.now()});return{success:true,parcel:{...parcel},money:owner.money};}
export function ownedBuildableLand(owner={},company={}){const s=ensurePropertyState(owner),need=propertyNeed(company);return s.owned.filter(p=>p.buildable!==false&&n(p.areaM2)>=n(need.minM2)&&need.zone.includes(p.zone));}
export function assignLandToCompany(owner,company,parcelId){const s=ensurePropertyState(owner),p=s.owned.find(x=>x.id===parcelId);if(!p)return{success:false,reason:'Grundstück gehört dir nicht'};const need=propertyNeed(company);if(!need.zone.includes(p.zone))return{success:false,reason:`Zonierung ${p.zoneLabel||p.zone} ist für diesen Betrieb nicht geeignet`};if(n(p.areaM2)<n(need.minM2))return{success:false,reason:`Grundstück ist zu klein. Benötigt werden mindestens ${need.minM2} m²`};if(p.assignedCompanyId&&p.assignedCompanyId!==(company.id||company.serverCompanyId))return{success:false,reason:'Grundstück ist bereits einem anderen Betrieb zugewiesen'};p.assignedCompanyId=company.id||company.serverCompanyId||uid('company');company.landPropertyId=p.id;company.landProperty={...p};company.setupPhase=company.setupPhase||'land_owned';return{success:true,parcel:{...p},company};}
export function canBuildBusiness(company={}){const p=company.landProperty;if(company.landLegacyGrandfathered)return{ok:true,legacy:true};if(!p)return{ok:false,reason:'Zuerst ein geeignetes Grundstück kaufen und dem Betrieb zuweisen'};const need=propertyNeed(company);if(!need.zone.includes(p.zone))return{ok:false,reason:'Grundstück hat nicht die passende Nutzungsart'};if(n(p.areaM2)<n(need.minM2))return{ok:false,reason:'Grundstück ist für diesen Betrieb zu klein'};return{ok:true,parcel:p};}
export function grandfatherExistingBusiness(company={}){if(company.landProperty||company.landPropertyId||company.landLegacyGrandfathered)return company;const alreadyEstablished=Boolean(company.buildingState||company.building_state||company.setupPhase==='operating'||company.createdAt||company.serverCompanyId);if(alreadyEstablished)company.landLegacyGrandfathered=true;return company;}
export function landKpis(owner={}){const s=ensurePropertyState(owner),area=s.owned.reduce((sum,p)=>sum+n(p.areaM2),0),value=s.owned.reduce((sum,p)=>sum+n(p.price),0);return{parcels:s.owned.length,areaM2:area,hectares:area/10000,purchaseValue:value,assigned:s.owned.filter(p=>p.assignedCompanyId).length};}
export function runLandPropertyTest(){const farm={type:'Landwirtschaftsbetrieb',money:50000},parcels=generateStarterParcels(farm,'test'),cheap=parcels[0],buy=buyLand(farm,cheap),company={type:'Landwirtschaftsbetrieb',id:'farm-1'},assign=assignLandToCompany(farm,company,cheap.id),build=canBuildBusiness(company);const shop={type:'Einzelhandel',money:50000},shopParcel=generateStarterParcels(shop,'test')[0],shopBuy=buyLand(shop,shopParcel),shopCompany={type:'Einzelhandel',id:'shop-1'},shopAssign=assignLandToCompany(shop,shopCompany,shopParcel.id);const success=buy.success&&assign.success&&build.ok&&shopBuy.success&&shopAssign.success&&farm.money>=0&&shop.money>=0;console[success?'log':'error'](success?'✅ GRUNDSTÜCKSTEST ERFOLGREICH':'❌ GRUNDSTÜCKSTEST FEHLGESCHLAGEN',{farm:{cheap,buy,assign,build,money:farm.money},shop:{shopParcel,shopBuy,shopAssign,money:shop.money}});return{success,farm,shop};}
export const LandZones=ZONES;
if(typeof window!=='undefined'){window.landPropertySystem={propertyNeed,createLandParcel,generateStarterParcels,ensurePropertyState,buyLand,ownedBuildableLand,assignLandToCompany,canBuildBusiness,grandfatherExistingBusiness,landKpis};window.runLandPropertyTest=runLandPropertyTest;}
