// WorldProject – sichtbare Ausbau-/Baustellenansicht im bestehenden Universal-Betriebsdialog.
import { UniversalOperationsDialog } from './UniversalOperationsDialog.js';
import { ensureExpansionState, expansionOverview, availableBuildings, startLandExpansion, ConstructionMaterials, deliverConstructionMaterial, startMachineUpgrade, machineUpgradeQuote } from './LandConstructionExpansionSystem.js';
import { progressiveBuildingQuote, progressiveBuildingMaterialNeed, startProgressiveBuildingConstruction } from './ProgressiveBuildingExpansionSystem.js';
import { constructionSlotState, assertCanStartConstruction, openCoinTimeReductionDialog } from './ConstructionPremiumCoinSystem.js';
const el=(tag,html='')=>{const x=document.createElement(tag);x.innerHTML=html;return x;};
const money=v=>Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const mins=m=>{m=Math.max(0,Math.round(Number(m||0)));return m>=60?`${Math.floor(m/60)} Std. ${m%60} Min.`:`${m} Min.`;};
const materialPrices={concrete:135,steel:950,brick:180,insulation:160,electrical:900,pipes:750,roofing:150};
const account=()=>window.worldCurrentUser||window.worldAccount||{};
const css=(node,styles)=>Object.assign(node.style,styles);
const pill=(text,tone='neutral')=>{const colors={ok:['#052e1a','#4ade80','#166534'],warn:['#3b2505','#fbbf24','#92400e'],bad:['#3b1115','#f87171','#991b1b'],neutral:['#172033','#cbd5e1','#334155']},p=el('span',text),c=colors[tone]||colors.neutral;css(p,{display:'inline-flex',alignItems:'center',padding:'5px 9px',borderRadius:'999px',background:c[0],color:c[1],border:`1px solid ${c[2]}`,fontSize:'12px',fontWeight:'800'});return p;};
const sectionTitle=(icon,title,sub='')=>{const d=el('div',`<div style="font-size:18px;font-weight:900">${icon} ${title}</div>${sub?`<div style="color:#94a3b8;font-size:13px;margin-top:3px">${sub}</div>`:''}`);css(d,{margin:'18px 0 9px'});return d;};

const oldRender=UniversalOperationsDialog.prototype.render;
UniversalOperationsDialog.prototype.render=function(){oldRender.call(this);const bar=this.root?.querySelector('[data-tabs]');if(!bar||bar.querySelector('[data-expansion-tab]'))return;const b=el('button','🏗️ Ausbau');b.dataset.expansionTab='1';b.style.fontWeight=this.tab==='expansion'?'800':'500';b.onclick=()=>{this.tab='expansion';this.render();};bar.append(b);if(this.tab==='expansion')this.render_expansion(this.root.querySelector('[data-body]'),window.worldPlayerCompany||window.worldEconomyGameplay?.company||window.worldEngine?.company);};
UniversalOperationsDialog.prototype.render_expansion=function(body,c){if(!c){body.innerHTML='<p>Kein aktiver Betrieb.</p>';return;}ensureExpansionState(c);const o=expansionOverview(c),slots=constructionSlotState(c,account());body.innerHTML='<h2 style="margin-bottom:4px">🏗️ Gebäude bauen & erweitern</h2><div style="color:#94a3b8;margin-bottom:14px">Plane deine Betriebsfläche, liefere Baumaterial zur Baustelle und starte den Ausbau, sobald alle Voraussetzungen erfüllt sind.</div>';
 const summary=el('div');css(summary,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:'9px',marginBottom:'14px'});for(const [icon,label,value,sub] of [['🌍','Grundstück',`${o.land.totalSqm} m²`,`${o.land.freeSqm} m² frei`],['🏗️','Bauplätze',`${slots.running} / ${slots.limit}`,slots.premium?'⭐ Premium':'Standard'],['🏭','Bebaute Fläche',`${o.land.usedSqm} m²`,'inkl. laufender Bauten']]){const card=el('div',`<div style="color:#94a3b8;font-size:12px;font-weight:800;text-transform:uppercase">${icon} ${label}</div><div style="font-size:22px;font-weight:900;margin:4px 0">${value}</div><div style="font-size:12px;color:#cbd5e1">${sub}</div>`);css(card,{padding:'12px',border:'1px solid #334155',borderRadius:'10px',background:'#101827'});summary.append(card);}body.append(summary);
 const land=el('div',`<div style="font-weight:900;font-size:16px">🌍 Grundstück erweitern</div><div style="display:flex;gap:18px;flex-wrap:wrap;margin:8px 0;color:#cbd5e1"><span><b>+${o.land.next.addSqm} m²</b> neue Fläche</span><span>💶 ${money(o.land.next.cost)}</span><span>⏱️ ${mins(o.land.next.durationMinutes)}</span></div>`);css(land,{padding:'13px',border:'1px solid #334155',borderRadius:'10px',background:'#111827',marginBottom:'15px'});const lb=el('button','Grundstück erweitern');lb.disabled=!slots.allowed;lb.title=!slots.allowed?`Alle ${slots.limit} Bauplätze sind belegt`:'';lb.onclick=()=>{try{assertCanStartConstruction(c,account());const j=startLandExpansion(c);alert(`Grundstückserweiterung beauftragt. Fertig in ca. ${mins(j.durationMinutes)}.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};land.append(lb);body.append(land);
 body.append(sectionTitle('🏭','Gebäude','Jedes Gebäude zeigt Kosten, Bauzeit und Materialfortschritt getrennt statt als lange Textzeile.'));
 const buildings=el('div');css(buildings,{display:'grid',gap:'11px'});for(const b of availableBuildings(c)){const q=progressiveBuildingQuote(c,b.id),need=progressiveBuildingMaterialNeed(c,b.id).map(x=>({...x,label:ConstructionMaterials[x.id]?.label||x.id,unit:ConstructionMaterials[x.id]?.unit||''})),missing=need.filter(x=>x.missing>0),ready=missing.length===0&&slots.allowed,card=el('article');css(card,{padding:'14px',border:`1px solid ${ready?'#166534':'#334155'}`,borderRadius:'12px',background:'linear-gradient(135deg,#111827,#0b1220)',boxShadow:'0 5px 18px rgba(0,0,0,.18)'});
  const head=el('div');css(head,{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:'12px',flexWrap:'wrap'});head.innerHTML=`<div><div style="font-size:17px;font-weight:900">${q.label}</div><div style="color:#94a3b8;font-size:13px;margin-top:2px">Ausbaustufe ${q.stage} · ${q.sqm} m²</div></div><div style="display:flex;gap:6px;flex-wrap:wrap"></div>`;const badges=head.lastElementChild;badges.append(pill(`💶 ${money(q.cost)}`),pill(`⏱️ ${mins(q.durationMinutes)}`),pill(ready?'✓ Baubereit':missing.length?`${missing.length} Materialarten fehlen`:'Bauplätze belegt',ready?'ok':missing.length?'warn':'bad'));card.append(head);
  const matTitle=el('div','Material auf der Baustelle');css(matTitle,{fontSize:'12px',fontWeight:'900',color:'#cbd5e1',margin:'13px 0 7px',textTransform:'uppercase'});card.append(matTitle);const mats=el('div');css(mats,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'7px'});for(const m of need){const complete=m.missing<=0,pct=Math.max(0,Math.min(100,Math.round((Number(m.atSite||0)/Math.max(1,Number(m.required||1)))*100))),box=el('div',`<div style="display:flex;justify-content:space-between;gap:6px"><b>${m.label}</b><span style="color:${complete?'#4ade80':'#fbbf24'}">${m.atSite}/${m.required} ${m.unit}</span></div><div style="height:5px;background:#263244;border-radius:99px;margin-top:6px;overflow:hidden"><div style="width:${pct}%;height:100%;background:${complete?'#22c55e':'#f59e0b'}"></div></div>`);css(box,{padding:'8px',border:'1px solid #263244',borderRadius:'8px',background:'#0b1220',fontSize:'12px'});mats.append(box);}card.append(mats);
  const actions=el('div');css(actions,{display:'flex',gap:'7px',flexWrap:'wrap',alignItems:'center',marginTop:'11px'});for(const m of missing){const buy=el('button',`+ ${m.missing} ${m.unit} ${m.label} liefern`);buy.onclick=()=>{try{const unit=materialPrices[m.id]||100;deliverConstructionMaterial(c,m.id,m.missing,{unitPrice:unit});alert(`${m.label} wurde direkt zur Baustelle geliefert. Kosten: ${money(unit*m.missing)}. Es liegt nicht im normalen Lager.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};actions.append(buy);}const build=el('button',missing.length?'🔒 Material fehlt':!slots.allowed?'🔒 Alle Bauplätze belegt':`🏗️ Ausbaustufe ${q.stage} bauen`);build.disabled=!ready;build.onclick=()=>{try{const j=startProgressiveBuildingConstruction(c,b.id,{account:account()});alert(`${q.label} Ausbaustufe ${q.stage} wird gebaut. Fertig in ca. ${mins(j.durationMinutes)}.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};css(build,{fontWeight:'900'});actions.append(build);card.append(actions);buildings.append(card);}body.append(buildings);
 const active=o.constructionSite.jobs.filter(j=>j.status!=='finished');body.append(sectionTitle('🚧','Laufende Baustellen',active.length?`${active.length} Bauauftrag${active.length===1?'':'e'} aktiv`:'Derzeit keine Bauarbeiten aktiv.'));const site=el('div');if(!active.length){const empty=el('div','✓ Keine laufende Baustelle.');css(empty,{padding:'11px',border:'1px solid #334155',borderRadius:'9px',color:'#94a3b8'});site.append(empty);}for(const j of active){const remaining=mins(Math.max(0,(j.finishAt-Date.now())/60000)),row=el('div',`<div style="display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap"><b>${j.label}</b><span>${j.progress}% · ⏱️ ${remaining}</span></div><div style="height:7px;background:#263244;border-radius:99px;margin:8px 0;overflow:hidden"><div style="width:${Math.max(0,Math.min(100,j.progress))}%;height:100%;background:#22c55e"></div></div>`);css(row,{padding:'11px',border:'1px solid #334155',borderRadius:'9px',margin:'7px 0',background:'#111827'});const shorten=el('button','🪙 Zeit verkürzen');shorten.onclick=()=>{try{openCoinTimeReductionDialog({company:c,job:j,onDone:()=>this.render()});}catch(e){alert(e.message);}};row.append(shorten);site.append(row);}body.append(site);
 const rooms=el('div');body.append(sectionTitle('🏢','Vorhandene Gebäude'));if(!o.buildings.length)rooms.append(el('div','Noch keine zusätzlichen Gebäude gebaut.'));for(const r of o.buildings){const row=el('div',`<b>${r.label||r.id}</b><span>${r.stage?`Stufe ${r.stage} · `:''}${r.sqm} m² · ${r.status==='finished'?'✅ fertig':`🏗️ ${r.progress}%`}</span>`);css(row,{display:'flex',justifyContent:'space-between',gap:'10px',padding:'8px 10px',borderBottom:'1px solid #263244'});rooms.append(row);}body.append(rooms);
 const machines=el('div');body.append(sectionTitle('⚙️','Maschinen einzeln ausbauen'));for(const m of c.buildingState.equipment.filter(x=>typeof x==='object')){const q=machineUpgradeQuote(m),running=c.machineUpgradeJobs.some(j=>j.machineInstanceId===m.instanceId&&j.status==='upgrading'),card=el('div',`<div style="display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap"><b>${m.label||m.id}</b><span>Stufe ${m.level||1} · Kapazität ${m.capacity||1}</span></div><div style="color:#94a3b8;margin-top:5px">${running?'🏗️ Upgrade läuft':`Nächstes Upgrade: ${money(q.cost)} · ${mins(q.durationMinutes)}`}</div>`);css(card,{padding:'11px',border:'1px solid #334155',borderRadius:'9px',margin:'7px 0',background:'#111827'});const up=el('button',running?'Upgrade läuft …':'Upgrade bestellen');up.disabled=running;up.onclick=()=>{try{const j=startMachineUpgrade(c,m);alert(`Upgrade für ${m.label||m.id} bestellt. Die Maschine ist bis zur Fertigstellung nicht verfügbar. Dauer ca. ${mins(j.durationMinutes)}.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};card.append(up);machines.append(card);}body.append(machines);
 const jobs=c.machineUpgradeJobs.filter(j=>j.status==='upgrading');if(jobs.length){body.append(sectionTitle('🔧','Laufende Maschinenupgrades'));const d=el('div');for(const j of jobs){const pct=Math.max(0,Math.min(99,Math.round((Date.now()-j.startedAt)/(j.finishAt-j.startedAt)*100))),row=el('div',`<b>${j.label}</b> · Stufe ${j.fromLevel} → ${j.toLevel} · ${pct}% · verbleibend ${mins(Math.max(0,(j.finishAt-Date.now())/60000))}`);const shorten=el('button','🪙 Zeit verkürzen');shorten.style.marginLeft='8px';shorten.onclick=()=>{try{openCoinTimeReductionDialog({company:c,job:j,onDone:()=>this.render()});}catch(e){alert(e.message);}};row.append(shorten);d.append(row);}body.append(d);}
};
if(typeof window!=='undefined')window.worldLandConstructionExpansionUI=true;
