// WorldProject – Grundstück, Gebäudeausbau, Baustellenmaterial und zeitliche Maschinenupgrades.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const nowId=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
export const START_LAND_SQM=300;
export const LandExpansionTiers=Object.freeze([
 {level:1,addSqm:200,cost:18000,durationMinutes:90},
 {level:2,addSqm:300,cost:42000,durationMinutes:150},
 {level:3,addSqm:500,cost:95000,durationMinutes:240},
 {level:4,addSqm:750,cost:210000,durationMinutes:360},
 {level:5,addSqm:1000,cost:450000,durationMinutes:540}
]);
export const ConstructionMaterials=Object.freeze({concrete:{label:'Beton',unit:'t'},steel:{label:'Baustahl',unit:'t'},brick:{label:'Mauerwerk',unit:'Pal.'},insulation:{label:'Dämmung',unit:'Pal.'},electrical:{label:'Elektromaterial',unit:'Satz'},pipes:{label:'Rohrmaterial',unit:'Satz'},roofing:{label:'Dachmaterial',unit:'Pal.'}});
export const BuildingCatalog=Object.freeze({
 brewhouse:{label:'Sudhaus',sqm:90,cost:28000,durationMinutes:240,materials:{concrete:18,steel:5,brick:10,electrical:2,pipes:3,roofing:6},industryHints:['brewery','brau','bier']},
 fermentation_house:{label:'Gärhaus',sqm:100,cost:32000,durationMinutes:300,materials:{concrete:20,steel:6,brick:12,insulation:5,electrical:2,pipes:4,roofing:7},industryHints:['brewery','brau','bier']},
 production_hall:{label:'Produktionshalle',sqm:120,cost:36000,durationMinutes:300,materials:{concrete:24,steel:8,brick:10,electrical:3,roofing:9}},
 workshop:{label:'Werkstatt',sqm:70,cost:19000,durationMinutes:180,materials:{concrete:12,steel:3,brick:7,electrical:2,roofing:4}},
 warehouse:{label:'Lagerhalle',sqm:120,cost:30000,durationMinutes:270,materials:{concrete:20,steel:7,brick:8,electrical:2,roofing:9}}
});
export function ensureExpansionState(company={}){company.land??={totalSqm:START_LAND_SQM,expansionLevel:0,reservedSqm:0};company.land.totalSqm=Math.max(START_LAND_SQM,n(company.land.totalSqm,START_LAND_SQM));company.land.expansionLevel=Math.max(0,n(company.land.expansionLevel));company.buildingState??={equipment:[],rooms:[]};company.buildingState.rooms??=[];company.buildingState.equipment??=[];company.constructionSite??={materials:{},jobs:[],deliveries:[]};company.constructionSite.materials??={};company.constructionSite.jobs??=[];company.constructionSite.deliveries??=[];company.machineUpgradeJobs??=[];return company;}
export function usedBuildingSqm(company){ensureExpansionState(company);return company.buildingState.rooms.filter(r=>r.status==='finished'||r.status==='building').reduce((s,r)=>s+n(r.sqm),0);}
export function freeLandSqm(company){ensureExpansionState(company);const pendingLand=company.constructionSite.jobs.filter(j=>j.kind==='land'&&j.status==='building').reduce((s,j)=>s+n(j.addSqm),0);return Math.max(0,n(company.land.totalSqm)-usedBuildingSqm(company)-n(company.land.reservedSqm)-pendingLand*0);}
export function nextLandExpansion(company){ensureExpansionState(company);const level=n(company.land.expansionLevel)+1,base=LandExpansionTiers.find(x=>x.level===level);if(base)return{...base};const extra=level-LandExpansionTiers.length,last=LandExpansionTiers.at(-1);return{level,addSqm:Math.round(last.addSqm*Math.pow(1.18,extra)),cost:Math.round(last.cost*Math.pow(1.55,extra)),durationMinutes:Math.round(last.durationMinutes*Math.pow(1.16,extra))};}
export function startLandExpansion(company,{now=Date.now()}={}){ensureExpansionState(company);if(company.constructionSite.jobs.some(j=>j.kind==='land'&&j.status==='building'))throw new Error('Grundstückserweiterung läuft bereits');const tier=nextLandExpansion(company);if(n(company.money)<tier.cost)throw new Error(`Nicht genug Geld. Grundstückserweiterung kostet ${tier.cost.toLocaleString('de-DE')} €`);company.money-=tier.cost;const job={id:nowId('land'),kind:'land',label:`Grundstück +${tier.addSqm} m²`,level:tier.level,addSqm:tier.addSqm,cost:tier.cost,startedAt:now,finishAt:now+tier.durationMinutes*60000,durationMinutes:tier.durationMinutes,status:'building'};company.constructionSite.jobs.push(job);return job;}
export function availableBuildings(company={}){ensureExpansionState(company);const key=String(company.type||company.company_type||company.industry||company.branchKey||'').toLowerCase(),brew=/brau|brew|bier/.test(key);return Object.entries(BuildingCatalog).filter(([id])=>brew||!['brewhouse','fermentation_house'].includes(id)).map(([id,x])=>({id,...x}));}
export function constructionMaterialNeed(company,type){ensureExpansionState(company);const b=BuildingCatalog[type];if(!b)throw new Error('Unbekanntes Gebäude');const site=company.constructionSite.materials;return Object.entries(b.materials).map(([id,required])=>({id,label:ConstructionMaterials[id]?.label||id,unit:ConstructionMaterials[id]?.unit||'',required,atSite:n(site[id]),missing:Math.max(0,required-n(site[id]))}));}
export function deliverConstructionMaterial(company,item,quantity,{unitPrice=0,now=Date.now()}={}){ensureExpansionState(company);if(!ConstructionMaterials[item])throw new Error('Unbekanntes Baumaterial');const q=Math.max(0,n(quantity));if(q<=0)throw new Error('Menge muss größer als 0 sein');const price=Math.max(0,n(unitPrice))*q;if(n(company.money)<price)throw new Error('Nicht genug Betriebsgeld für Baumaterial');company.money-=price;company.constructionSite.materials[item]=n(company.constructionSite.materials[item])+q;const d={id:nowId('site-delivery'),item,quantity:q,cost:price,deliveredAt:now,destination:'construction_site'};company.constructionSite.deliveries.push(d);return d;}
export function transferInventoryMaterialToSite(company,item,quantity){ensureExpansionState(company);const q=Math.max(0,n(quantity));if(q<=0)throw new Error('Menge muss größer als 0 sein');const have=n(company.inventory?.[item]);if(have<q)throw new Error('Nicht genug Material im Lager');company.inventory[item]=have-q;company.constructionSite.materials[item]=n(company.constructionSite.materials[item])+q;return{item,quantity:q,destination:'construction_site'};}
export function startBuildingConstruction(company,type,{now=Date.now()}={}){ensureExpansionState(company);const b=BuildingCatalog[type];if(!b)throw new Error('Unbekanntes Gebäude');if(freeLandSqm(company)<b.sqm)throw new Error(`Nicht genug Grundstücksfläche. Benötigt: ${b.sqm} m², frei: ${freeLandSqm(company)} m²`);const needs=constructionMaterialNeed(company,type),missing=needs.filter(x=>x.missing>0);if(missing.length)throw new Error(`Baumaterial fehlt: ${missing.map(x=>`${x.label} ${x.missing} ${x.unit}`).join(', ')}`);if(n(company.money)<b.cost)throw new Error(`Nicht genug Geld für den Bau. Baukosten: ${b.cost.toLocaleString('de-DE')} €`);company.money-=b.cost;for(const [id,q] of Object.entries(b.materials))company.constructionSite.materials[id]=Math.max(0,n(company.constructionSite.materials[id])-q);const room={instanceId:nowId('building'),id:type,label:b.label,sqm:b.sqm,status:'building',startedAt:now,finishAt:now+b.durationMinutes*60000,level:1};company.buildingState.rooms.push(room);const job={id:nowId('construction'),kind:'building',buildingInstanceId:room.instanceId,type,label:b.label,sqm:b.sqm,cost:b.cost,startedAt:now,finishAt:room.finishAt,durationMinutes:b.durationMinutes,status:'building',materials:{...b.materials}};company.constructionSite.jobs.push(job);return job;}
export function machineFootprint(machine={}){return Math.max(4,n(machine.floorSqm,n(machine.slots,1)*8));}
export function buildingMachineCapacity(company){ensureExpansionState(company);const finished=company.buildingState.rooms.filter(r=>r.status==='finished').reduce((s,r)=>s+n(r.sqm),0);return Math.max(0,Math.floor(finished*.72));}
export function usedMachineSqm(company){ensureExpansionState(company);return company.buildingState.equipment.filter(x=>typeof x==='object'&&x.status!=='sold').reduce((s,m)=>s+machineFootprint(m),0);}
export function canPlaceMachine(company,machineDef={}){const need=machineFootprint(machineDef),capacity=buildingMachineCapacity(company),used=usedMachineSqm(company);return{allowed:used+need<=capacity,need,used,capacity,free:Math.max(0,capacity-used)};}
export function machineUpgradeQuote(machine={}){const level=Math.max(1,n(machine.level,1)),base=Math.max(1000,n(machine.upgradePrice,n(machine.purchasePrice)*.55));return{fromLevel:level,toLevel:level+1,cost:Math.round(base*Math.pow(1.42,Math.max(0,level-1))),durationMinutes:Math.round(45*Math.pow(1.32,Math.max(0,level-1))),capacityFactor:1.25};}
export function startMachineUpgrade(company,machine,{now=Date.now()}={}){ensureExpansionState(company);if(!machine||typeof machine!=='object')throw new Error('Maschine fehlt');if(machine.status&&machine.status!=='available')throw new Error('Maschine ist gerade nicht verfügbar');if(company.machineUpgradeJobs.some(j=>j.machineInstanceId===machine.instanceId&&j.status==='upgrading'))throw new Error('Für diese Maschine läuft bereits ein Upgrade');const q=machineUpgradeQuote(machine);if(n(company.money)<q.cost)throw new Error(`Nicht genug Geld. Upgrade kostet ${q.cost.toLocaleString('de-DE')} €`);company.money-=q.cost;machine.status='upgrade';machine.busyUntil=now+q.durationMinutes*60000;const job={id:nowId('machine-upgrade'),kind:'machine_upgrade',machineInstanceId:machine.instanceId,machineId:machine.id,label:machine.label||machine.id,fromLevel:q.fromLevel,toLevel:q.toLevel,cost:q.cost,startedAt:now,finishAt:machine.busyUntil,durationMinutes:q.durationMinutes,status:'upgrading',capacityFactor:q.capacityFactor};company.machineUpgradeJobs.push(job);return job;}
export function advanceExpansion(company,{now=Date.now()}={}){ensureExpansionState(company);const finished=[];for(const j of company.constructionSite.jobs.filter(j=>j.status==='building'&&n(j.finishAt)<=now)){j.status='finished';j.finishedAt=now;if(j.kind==='land'){company.land.totalSqm+=n(j.addSqm);company.land.expansionLevel=Math.max(n(company.land.expansionLevel),n(j.level));}else if(j.kind==='building'){const room=company.buildingState.rooms.find(r=>r.instanceId===j.buildingInstanceId);if(room){room.status='finished';room.finishedAt=now;}}finished.push(j);}for(const j of company.machineUpgradeJobs.filter(j=>j.status==='upgrading'&&n(j.finishAt)<=now)){const m=company.buildingState.equipment.find(x=>x.instanceId===j.machineInstanceId);j.status='finished';j.finishedAt=now;if(m){m.level=n(m.level,1)+1;m.capacity=Math.round(n(m.capacity,1)*n(j.capacityFactor,1.25)*100)/100;m.upgradePrice=Math.round(n(j.cost)*1.35);m.status='available';m.busyUntil=0;}finished.push(j);}return finished;}
export function expansionOverview(company,{now=Date.now()}={}){advanceExpansion(company,{now});ensureExpansionState(company);return{land:{totalSqm:n(company.land.totalSqm),usedSqm:usedBuildingSqm(company),freeSqm:freeLandSqm(company),level:n(company.land.expansionLevel),next:nextLandExpansion(company)},buildings:company.buildingState.rooms.map(r=>({...r,progress:r.status==='finished'?100:clamp(Math.round((now-n(r.startedAt))/(Math.max(1,n(r.finishAt)-n(r.startedAt)))*100),0,99)})),constructionSite:{materials:{...company.constructionSite.materials},jobs:company.constructionSite.jobs.map(j=>({...j,progress:j.status==='finished'?100:clamp(Math.round((now-n(j.startedAt))/(Math.max(1,n(j.finishAt)-n(j.startedAt)))*100),0,99)}))},machines:{usedSqm:usedMachineSqm(company),capacitySqm:buildingMachineCapacity(company),upgradeJobs:company.machineUpgradeJobs.map(j=>({...j,progress:j.status==='finished'?100:clamp(Math.round((now-n(j.startedAt))/(Math.max(1,n(j.finishAt)-n(j.startedAt)))*100),0,99)}))}};}
export function runLandConstructionExpansionTest(){const c={type:'Brauerei',money:1000000,inventory:{},buildingState:{equipment:[],rooms:[]}};ensureExpansionState(c);if(c.land.totalSqm!==300)throw new Error('Startgrundstück nicht 300 m²');const land=startLandExpansion(c,{now:0});advanceExpansion(c,{now:land.finishAt});if(c.land.totalSqm!==500)throw new Error('Grundstückserweiterung fehlgeschlagen');for(const x of constructionMaterialNeed(c,'brewhouse'))deliverConstructionMaterial(c,x.id,x.required,{unitPrice:0,now:0});const build=startBuildingConstruction(c,'brewhouse',{now:0});if(c.constructionSite.materials.concrete!==0)throw new Error('Baustellenmaterial wurde nicht verbraucht');advanceExpansion(c,{now:build.finishAt});if(!c.buildingState.rooms.some(r=>r.id==='brewhouse'&&r.status==='finished'))throw new Error('Sudhaus nicht fertiggestellt');const machine={id:'fermentation_tank',instanceId:'tank-1',label:'Gärtank',level:1,capacity:50,purchasePrice:10000,upgradePrice:5000,status:'available',floorSqm:12};c.buildingState.equipment.push(machine);const up=startMachineUpgrade(c,machine,{now:0});if(machine.level!==1||machine.status!=='upgrade')throw new Error('Upgrade darf nicht sofort fertig sein');advanceExpansion(c,{now:up.finishAt});if(machine.level!==2||machine.status!=='available'||machine.capacity<=50)throw new Error('Zeitliches Maschinenupgrade fehlgeschlagen');return true;}
if(typeof window!=='undefined')window.worldLandConstructionExpansion={ensureExpansionState,startLandExpansion,startBuildingConstruction,deliverConstructionMaterial,transferInventoryMaterialToSite,startMachineUpgrade,advanceExpansion,overview:expansionOverview,materialNeed:constructionMaterialNeed,canPlaceMachine,runTest:runLandConstructionExpansionTest};
