// WorldProject – sichtbare Ausbau-/Baustellenansicht im bestehenden Universal-Betriebsdialog.
import { UniversalOperationsDialog } from './UniversalOperationsDialog.js';
import { ensureExpansionState, expansionOverview, availableBuildings, startLandExpansion, ConstructionMaterials, deliverConstructionMaterial, startMachineUpgrade, machineUpgradeQuote } from './LandConstructionExpansionSystem.js';
import { progressiveBuildingQuote, progressiveBuildingMaterialNeed, startProgressiveBuildingConstruction } from './ProgressiveBuildingExpansionSystem.js';
const el=(tag,html='')=>{const x=document.createElement(tag);x.innerHTML=html;return x;};
const money=v=>Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const mins=m=>{m=Math.max(0,Math.round(Number(m||0)));return m>=60?`${Math.floor(m/60)} Std. ${m%60} Min.`:`${m} Min.`;};
const materialPrices={concrete:135,steel:950,brick:180,insulation:160,electrical:900,pipes:750,roofing:150};

const oldRender=UniversalOperationsDialog.prototype.render;
UniversalOperationsDialog.prototype.render=function(){oldRender.call(this);const bar=this.root?.querySelector('[data-tabs]');if(!bar||bar.querySelector('[data-expansion-tab]'))return;const b=el('button','🏗️ Ausbau');b.dataset.expansionTab='1';b.style.fontWeight=this.tab==='expansion'?'800':'500';b.onclick=()=>{this.tab='expansion';this.render();};bar.append(b);if(this.tab==='expansion')this.render_expansion(this.root.querySelector('[data-body]'),window.worldPlayerCompany||window.worldEconomyGameplay?.company||window.worldEngine?.company);};
UniversalOperationsDialog.prototype.render_expansion=function(body,c){if(!c){body.innerHTML='<p>Kein aktiver Betrieb.</p>';return;}ensureExpansionState(c);const o=expansionOverview(c);body.innerHTML=`<h2>🏗️ Grundstück, Gebäude & Baustelle</h2><div style="padding:12px;border:1px solid #374151;border-radius:10px;margin-bottom:12px"><b>Grundstück:</b> ${o.land.totalSqm} m² · bebaut/im Bau ${o.land.usedSqm} m² · frei ${o.land.freeSqm} m²<br><small>Neue Flächen und Gebäude sind Investitionen: Bestellung/Bau brauchen Zeit und werden nicht sofort fertig.</small></div>`;
 const land=el('div',`<h3>🌍 Grundstück erweitern</h3><div>Nächste Erweiterung: <b>+${o.land.next.addSqm} m²</b> · ${money(o.land.next.cost)} · Dauer ${mins(o.land.next.durationMinutes)}</div>`);Object.assign(land.style,{padding:'12px',border:'1px solid #374151',borderRadius:'10px',margin:'10px 0'});const lb=el('button','Grundstück erweitern');lb.onclick=()=>{try{const j=startLandExpansion(c);alert(`Grundstückserweiterung beauftragt. Fertig in ca. ${mins(j.durationMinutes)}.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};land.append(lb);body.append(land);
 const buildings=el('div','<h3>🏭 Gebäude bauen / erweitern</h3>');for(const b of availableBuildings(c)){const q=progressiveBuildingQuote(c,b.id),need=progressiveBuildingMaterialNeed(c,b.id).map(x=>({...x,label:ConstructionMaterials[x.id]?.label||x.id,unit:ConstructionMaterials[x.id]?.unit||''})),missing=need.filter(x=>x.missing>0),card=el('div',`<b>${q.label} · Ausbaustufe ${q.stage}</b> · ${q.sqm} m² · Baukosten ${money(q.cost)} · Bauzeit ${mins(q.durationMinutes)}<br><small>Material: ${need.map(x=>`${x.label} ${x.atSite}/${x.required} ${x.unit}`).join(' · ')}</small>`);Object.assign(card.style,{padding:'10px',border:'1px solid #374151',borderRadius:'8px',margin:'8px 0'});for(const m of missing){const buy=el('button',`${m.label} +${m.missing} ${m.unit} zur Baustelle`);buy.onclick=()=>{try{const unit=materialPrices[m.id]||100;deliverConstructionMaterial(c,m.id,m.missing,{unitPrice:unit});alert(`${m.label} wurde direkt zur Baustelle geliefert. Kosten: ${money(unit*m.missing)}. Es liegt nicht im normalen Lager.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};card.append(buy);}const build=el('button',missing.length?'Bau noch nicht möglich':`Ausbaustufe ${q.stage} bauen`);build.disabled=missing.length>0;build.onclick=()=>{try{const j=startProgressiveBuildingConstruction(c,b.id);alert(`${q.label} Ausbaustufe ${q.stage} wird gebaut. Fertig in ca. ${mins(j.durationMinutes)}.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};card.append(build);buildings.append(card);}body.append(buildings);
 const site=el('div','<h3>🚧 Laufende Baustellen</h3>');const active=o.constructionSite.jobs.filter(j=>j.status!=='finished');if(!active.length)site.append(el('div','Keine laufende Baustelle.'));for(const j of active){site.append(el('div',`<b>${j.label}</b> · ${j.progress}% · verbleibend ca. ${mins(Math.max(0,(j.finishAt-Date.now())/60000))}`));}body.append(site);
 const rooms=el('div','<h3>🏢 Vorhandene Gebäude</h3>');if(!o.buildings.length)rooms.append(el('div','Noch keine zusätzlichen Gebäude gebaut.'));for(const r of o.buildings)rooms.append(el('div',`<b>${r.label||r.id}</b>${r.stage?` · Ausbaustufe ${r.stage}`:''} · ${r.sqm} m² · ${r.status==='finished'?'✅ fertig':`🏗️ ${r.progress}%`}`));body.append(rooms);
 const machines=el('div','<h3>⚙️ Maschinen einzeln ausbauen</h3>');for(const m of c.buildingState.equipment.filter(x=>typeof x==='object')){const q=machineUpgradeQuote(m),running=c.machineUpgradeJobs.some(j=>j.machineInstanceId===m.instanceId&&j.status==='upgrading'),card=el('div',`<b>${m.label||m.id}</b> · Stufe ${m.level||1} · Kapazität ${m.capacity||1}<br>${running?'🏗️ Upgrade läuft':`Nächstes Upgrade: ${money(q.cost)} · Dauer ${mins(q.durationMinutes)}`}`);Object.assign(card.style,{padding:'10px',border:'1px solid #374151',borderRadius:'8px',margin:'8px 0'});const up=el('button',running?'Upgrade läuft …':'Upgrade bestellen');up.disabled=running;up.onclick=()=>{try{const j=startMachineUpgrade(c,m);alert(`Upgrade für ${m.label||m.id} bestellt. Die Maschine ist bis zur Fertigstellung nicht verfügbar. Dauer ca. ${mins(j.durationMinutes)}.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};card.append(up);machines.append(card);}body.append(machines);
 const jobs=c.machineUpgradeJobs.filter(j=>j.status==='upgrading');if(jobs.length){const d=el('div','<h3>🔧 Laufende Maschinenupgrades</h3>');for(const j of jobs){const pct=Math.max(0,Math.min(99,Math.round((Date.now()-j.startedAt)/(j.finishAt-j.startedAt)*100)));d.append(el('div',`${j.label}: Stufe ${j.fromLevel} → ${j.toLevel} · ${pct}% · verbleibend ${mins(Math.max(0,(j.finishAt-Date.now())/60000))}`));}body.append(d);}
};
if(typeof window!=='undefined')window.worldLandConstructionExpansionUI=true;
