// WorldProject – verifizierte Live-Verkehrsschicht fuer Lieferungen.
// Grundregel: Niemals Stau, Sperrung, Unfall oder Umleitung erfinden.
// Solche Ereignisse duerfen nur aus einer explizit als live/verifiziert markierten HERE-Antwort stammen.

export const LIVE_TRAFFIC_CONFIG=Object.freeze({
 provider:'HERE',edgeFunction:'world-traffic-route',fallbackEndpoint:'/api/traffic/route',refreshMs:5*60*1000,staleAfterMs:15*60*1000
});
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,text=v=>String(v??'').trim();
const activeStatus=s=>['ordered','in_transit','delayed'].includes(String(s||'').toLowerCase());
const coord=x=>x&&Number.isFinite(Number(x.lat))&&Number.isFinite(Number(x.lng))?{lat:Number(x.lat),lng:Number(x.lng)}:null;
function authApi(){return typeof window!=='undefined'?window.worldAccounts?.authApi:null;}
function endpoint(explicit=null){if(explicit)return explicit;const a=authApi();return a?.baseUrl?`${String(a.baseUrl).replace(/\/$/,'')}/functions/v1/${LIVE_TRAFFIC_CONFIG.edgeFunction}`:LIVE_TRAFFIC_CONFIG.fallbackEndpoint;}
function headers(){const a=authApi(),h={'Content-Type':'application/json'};if(a?.publishableKey)h.apikey=a.publishableKey;if(a?.session?.access_token)h.Authorization=`Bearer ${a.session.access_token}`;return h;}
export function normalizeRoutingPoint(v){if(!v)return null;if(Array.isArray(v)&&v.length>=2)return coord({lat:v[0],lng:v[1]});if(v.coordinates)return normalizeRoutingPoint(v.coordinates);return coord(v);}
export function trafficState(o={}){o.liveTraffic??={provider:'HERE',status:'unconfigured',verifiedLive:false,route:null,incidents:[],messages:[],lastCheckedAt:0,nextCheckAt:0,lastError:null,rerouteCount:0};o.liveTraffic.incidents??=[];o.liveTraffic.messages??=[];return o.liveTraffic;}
export function trafficView(o={},now=Date.now()){const t=trafficState(o),r=t.route||{},age=t.lastCheckedAt?Math.max(0,now-t.lastCheckedAt):null,verified=t.verifiedLive===true&&t.provider==='HERE',stale=verified&&age!==null&&age>LIVE_TRAFFIC_CONFIG.staleAfterMs;return{provider:t.provider||'HERE',status:stale?'stale':t.status,verifiedLive:verified&&!stale,stale,lastCheckedAt:n(t.lastCheckedAt)||null,nextCheckAt:n(t.nextCheckAt)||null,distanceKm:n(r.distanceMeters)/1000,durationSeconds:n(r.durationSeconds),baseDurationSeconds:n(r.baseDurationSeconds),trafficDelaySeconds:Math.max(0,n(r.durationSeconds)-n(r.baseDurationSeconds)),eta:n(r.eta)||n(o.eta)||null,roads:Array.isArray(r.roads)?r.roads:[],incidents:verified&&!stale?(t.incidents||[]):[],rerouted:Boolean(r.rerouted),rerouteCount:n(t.rerouteCount),originLabel:text(r.originLabel||o.routeOrigin?.label),destinationLabel:text(r.destinationLabel||o.routeDestination?.label),lastError:text(t.lastError),message:!verified?(t.status==='loading'?'Live-Verkehr wird geladen':t.lastError||'Live-Verkehr nicht verbunden'):stale?'Live-Verkehrsdaten sind veraltet':'Live-Verkehr aktiv'};}
export function markTrafficUnavailable(o,reason='Live-Verkehr nicht verbunden'){const t=trafficState(o);t.status='unconfigured';t.verifiedLive=false;t.incidents=[];t.lastError=text(reason);t.nextCheckAt=0;return t;}
function verifiedPayload(d){return !!(d&&d.success===true&&d.provider==='HERE'&&d.verifiedLive===true&&d.route&&Number.isFinite(Number(d.route.durationSeconds)));}
function sameRoads(a=[],b=[]){const x=a.map(text).filter(Boolean),y=b.map(text).filter(Boolean);if(!x.length&&!y.length)return true;return x.join('|')===y.join('|');}
export function applyVerifiedTraffic(o,d,{now=Date.now()}={}){if(!verifiedPayload(d))throw new Error('Nicht verifizierte Verkehrsdaten werden nicht uebernommen');const t=trafficState(o),previous=t.route||null,r={...d.route};r.distanceMeters=Math.max(0,n(r.distanceMeters));r.durationSeconds=Math.max(0,n(r.durationSeconds));r.baseDurationSeconds=Math.max(0,n(r.baseDurationSeconds,r.durationSeconds));r.eta=n(r.eta,now+r.durationSeconds*1000);r.roads=Array.isArray(r.roads)?r.roads.map(text).filter(Boolean):[];const distanceChanged=previous&&Math.abs(n(previous.distanceMeters)-r.distanceMeters)>1000;r.rerouted=Boolean(previous&&(!sameRoads(previous.roads||[],r.roads)||distanceChanged));t.provider='HERE';t.status='live';t.verifiedLive=true;t.lastCheckedAt=now;t.nextCheckAt=now+LIVE_TRAFFIC_CONFIG.refreshMs;t.lastError=null;t.route=r;t.incidents=Array.isArray(d.incidents)?d.incidents.map(i=>({id:text(i.id),type:text(i.type),criticality:text(i.criticality),description:text(i.description),road:text(i.road),startTime:i.startTime||null,endTime:i.endTime||null})).filter(i=>i.id||i.description):[];if(r.rerouted){t.rerouteCount=n(t.rerouteCount)+1;t.messages.unshift({at:now,type:'reroute',text:`Route durch Live-Verkehr neu berechnet${r.roads.length?`: ${r.roads.join(' → ')}`:''}`});}const delay=Math.max(0,r.durationSeconds-r.baseDurationSeconds);if(delay>0)t.messages.unshift({at:now,type:'traffic_delay',text:`Live-Verkehr: etwa ${Math.ceil(delay/60)} Min. zusaetzliche Fahrzeit`});for(const incident of t.incidents.slice(0,5))t.messages.unshift({at:now,type:'incident',text:[incident.type,incident.road,incident.description].filter(Boolean).join(' · ')});t.messages=t.messages.slice(0,30);o.trafficEta=r.eta;o.eta=Math.max(n(o.nonTrafficEta||o.plannedEta),r.eta);return trafficView(o,now);}
export class LiveTrafficRoutingSystem{constructor({routeEndpoint=null,fetchImpl=globalThis.fetch}={}){this.routeEndpoint=routeEndpoint;this.fetchImpl=fetchImpl;}canRoute(o={}){return !!(normalizeRoutingPoint(o.routeOrigin)&&normalizeRoutingPoint(o.routeDestination));}async refresh(o,{force=false,now=Date.now(),vehicle={}}={}){const t=trafficState(o);if(!activeStatus(o.status))return trafficView(o,now);if(!this.canRoute(o)){markTrafficUnavailable(o,'Start- oder Zielkoordinaten fehlen');return trafficView(o,now);}if(!force&&t.nextCheckAt&&now<t.nextCheckAt)return trafficView(o,now);if(typeof this.fetchImpl!=='function'){markTrafficUnavailable(o,'Routing-Dienst nicht erreichbar');return trafficView(o,now);}t.status='loading';try{const a=authApi();if(a?.ensureAccessToken)await a.ensureAccessToken();const response=await this.fetchImpl(endpoint(this.routeEndpoint),{method:'POST',headers:headers(),body:JSON.stringify({origin:normalizeRoutingPoint(o.routeOrigin),destination:normalizeRoutingPoint(o.routeDestination),originLabel:text(o.routeOrigin?.label),destinationLabel:text(o.routeDestination?.label),departureTime:new Date(now).toISOString(),vehicle:{grossWeightKg:n(vehicle.grossWeightKg||o.vehicleGrossWeightKg),heightM:n(vehicle.heightM||o.vehicleHeightM),widthM:n(vehicle.widthM||o.vehicleWidthM),lengthM:n(vehicle.lengthM||o.vehicleLengthM),axleWeightKg:n(vehicle.axleWeightKg||o.vehicleAxleWeightKg)}})});const data=await response.json().catch(()=>null);if(!response.ok||!verifiedPayload(data))throw new Error(data?.error||'Keine verifizierte HERE-Antwort');return applyVerifiedTraffic(o,data,{now});}catch(error){t.status=t.verifiedLive?'stale':'unavailable';t.lastError=error?.message||String(error);t.nextCheckAt=now+LIVE_TRAFFIC_CONFIG.refreshMs;return trafficView(o,now);}}async refreshCompany(c={},options={}){const orders=[...(c.operationalSupplyState?.orders||[]),...(c.supplierOrders||[])],seen=new Set(),results=[];for(const o of orders){const key=o?.id||o;if(!o||seen.has(key)||!activeStatus(o.status))continue;seen.add(key);results.push(await this.refresh(o,options));}return results;}}
export function runLiveTrafficRoutingTest(){const now=1000000,o={status:'in_transit',plannedEta:now+7200000,routeOrigin:{lat:50.1,lng:8.6,label:'Frankfurt'},routeDestination:{lat:51.5,lng:9.2,label:'Ziel'}};if(trafficView(o,now).verifiedLive)throw new Error('Unverifizierte Daten duerfen nicht live sein');let rejected=false;try{applyVerifiedTraffic(o,{success:true,provider:'fake',verifiedLive:true,route:{durationSeconds:100}},{now});}catch{rejected=true;}if(!rejected)throw new Error('Fake-Provider wurde akzeptiert');const v=applyVerifiedTraffic(o,{success:true,provider:'HERE',verifiedLive:true,route:{routeId:'r1',durationSeconds:7200,baseDurationSeconds:6000,distanceMeters:120000,eta:now+7200000,roads:['A5','A7']},incidents:[{id:'i1',type:'construction',road:'A7',description:'Baustelle'}]},{now});if(!v.verifiedLive||v.trafficDelaySeconds!==1200||v.incidents.length!==1||o.trafficEta!==now+7200000)throw new Error('Verifizierte Live-Verkehrsdaten fehlerhaft');return true;}
if(typeof window!=='undefined')window.worldLiveTrafficRouting={config:LIVE_TRAFFIC_CONFIG,system:new LiveTrafficRoutingSystem(),view:trafficView,apply:applyVerifiedTraffic,runTest:runLiveTrafficRoutingTest};
