// WorldProject – Live-Ops: Events, Rollouts, Wartung und zeitgesteuerte Weltparameter.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureLiveOps(world={}){world.liveOps??={events:[],rollouts:[],announcements:[],history:[]};return world.liveOps;}
export function createLiveEvent(world,{actor,name,type="bonus",startsAt=Date.now(),endsAt=null,effects={},audience="all"}={}){adminControlSystem.requirePermission(actor,"liveops.write");const s=ensureLiveOps(world),row={id:`live-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name,type,startsAt,endsAt,effects:{...effects},audience,status:"scheduled",createdBy:actor.id,createdAt:Date.now()};s.events.push(row);adminControlSystem.log(actor,"live_event_created",{id:row.id,name,type});return row;}
export function activateLiveEvents(world,{now=Date.now()}={}){const s=ensureLiveOps(world),changed=[];for(const e of s.events){if(e.status==="scheduled"&&e.startsAt<=now&&(!e.endsAt||e.endsAt>now)){e.status="active";changed.push(e);}if(e.status==="active"&&e.endsAt&&e.endsAt<=now){e.status="finished";e.finishedAt=now;changed.push(e);}}return changed;}
export function activeEffects(world,{now=Date.now()}={}){activateLiveEvents(world,{now});const out={demand:1,productionSpeed:1,transportCost:1,xp:1,reputation:1};for(const e of ensureLiveOps(world).events.filter(x=>x.status==="active")){for(const[k,v]of Object.entries(e.effects||{}))if(k in out)out[k]*=n(v,1);}return out;}
export function scheduleRollout(world,{actor,feature,percentage=0,startsAt=Date.now(),endsAt=null,conditions={}}={}){adminControlSystem.requirePermission(actor,"liveops.write");const s=ensureLiveOps(world),row={id:`rollout-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,feature,percentage:Math.max(0,Math.min(100,n(percentage))),startsAt,endsAt,conditions:{...conditions},status:"scheduled",createdBy:actor.id};s.rollouts.push(row);return row;}
export function featureAvailableFor(world,feature,{playerId="",companyLevel=0,country="",now=Date.now()}={}){const rows=ensureLiveOps(world).rollouts.filter(r=>r.feature===feature&&r.startsAt<=now&&(!r.endsAt||r.endsAt>now));if(!rows.length)return false;const r=rows.at(-1);if(r.conditions.minCompanyLevel&&companyLevel<r.conditions.minCompanyLevel)return false;if(r.conditions.country&&r.conditions.country!==country)return false;const hash=[...String(playerId)].reduce((s,ch)=>s+ch.charCodeAt(0),0)%100;return hash<r.percentage;}
export function createLiveAnnouncement(world,{actor,title,message,severity="info",startsAt=Date.now(),endsAt=null}={}){adminControlSystem.requirePermission(actor,"liveops.write");const s=ensureLiveOps(world),row={id:`la-${Date.now()}`,title,message,severity,startsAt,endsAt,status:"scheduled"};s.announcements.push(row);return row;}
export function visibleAnnouncements(world,{now=Date.now()}={}){return ensureLiveOps(world).announcements.filter(a=>a.startsAt<=now&&(!a.endsAt||a.endsAt>now));}
export function setMaintenanceMode(actor,enabled,{message="Wartungsarbeiten"}={}){adminControlSystem.requirePermission(actor,"system.write");adminControlSystem.updateSetting(actor,"maintenanceMode",!!enabled);return{enabled:!!enabled,message};}
export function liveOpsKpis(world){const s=ensureLiveOps(world);return{activeEvents:s.events.filter(x=>x.status==="active").length,scheduledEvents:s.events.filter(x=>x.status==="scheduled").length,rollouts:s.rollouts.length,announcements:s.announcements.length};}
