// WorldProject – Live-Ops: Events, Rollouts, Wartung und zeitgesteuerte Weltparameter.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const trim=(a,max=5000)=>{if(a.length>max)a.splice(0,a.length-max);return a;};
const requireText=(v,label)=>{const s=String(v||"").trim();if(!s)throw new Error(`${label} fehlt`);return s;};
const validWindow=(startsAt,endsAt)=>{const s=n(startsAt,Date.now()),e=endsAt==null?null:n(endsAt);if(e!==null&&e<=s)throw new Error("Endzeit muss nach der Startzeit liegen");return{s,e};};
export function ensureLiveOps(world={}){world.liveOps??={events:[],rollouts:[],announcements:[],history:[]};for(const k of ["events","rollouts","announcements","history"])if(!Array.isArray(world.liveOps[k]))world.liveOps[k]=[];return world.liveOps;}
export function createLiveEvent(world,{actor,name,type="bonus",startsAt=Date.now(),endsAt=null,effects={},audience="all"}={}){adminControlSystem.requirePermission(actor,"liveops.write");const s=ensureLiveOps(world),window=validWindow(startsAt,endsAt),cleanName=requireText(name,"Eventname"),row={id:`live-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:cleanName,type:String(type||"bonus"),startsAt:window.s,endsAt:window.e,effects:{...effects},audience:String(audience||"all"),status:"scheduled",createdBy:actor.id,createdAt:Date.now()};s.events.push(row);trim(s.events);s.history.push({kind:"event_created",id:row.id,actorId:actor.id,at:Date.now()});trim(s.history);adminControlSystem.log(actor,"live_event_created",{id:row.id,name:row.name,type:row.type});return row;}
export function activateLiveEvents(world,{now=Date.now()}={}){const s=ensureLiveOps(world),changed=[];for(const e of s.events){if(e.status==="scheduled"&&e.startsAt<=now&&(!e.endsAt||e.endsAt>now)){e.status="active";e.activatedAt=now;changed.push(e);s.history.push({kind:"event_activated",id:e.id,at:now});}if(e.status==="active"&&e.endsAt&&e.endsAt<=now){e.status="finished";e.finishedAt=now;changed.push(e);s.history.push({kind:"event_finished",id:e.id,at:now});}}trim(s.history);return changed;}
export function cancelLiveEvent(world,{actor,eventId,reason=""}={}){adminControlSystem.requirePermission(actor,"liveops.write");const s=ensureLiveOps(world),e=s.events.find(x=>x.id===eventId);if(!e)throw new Error("Live-Event fehlt");if(e.status==="finished"||e.status==="cancelled")return e;const before=e.status;e.status="cancelled";e.cancelledAt=Date.now();e.cancelledBy=actor.id;e.cancelReason=String(reason||"").trim();s.history.push({kind:"event_cancelled",id:e.id,before,reason:e.cancelReason,actorId:actor.id,at:e.cancelledAt});trim(s.history);adminControlSystem.log(actor,"live_event_cancelled",{id:e.id,before,reason:e.cancelReason});return e;}
export function activeEffects(world,{now=Date.now()}={}){activateLiveEvents(world,{now});const out={demand:1,productionSpeed:1,transportCost:1,xp:1,reputation:1};for(const e of ensureLiveOps(world).events.filter(x=>x.status==="active")){for(const[k,v]of Object.entries(e.effects||{}))if(k in out)out[k]*=n(v,1);}return out;}
export function scheduleRollout(world,{actor,feature,percentage=0,startsAt=Date.now(),endsAt=null,conditions={}}={}){adminControlSystem.requirePermission(actor,"liveops.write");const s=ensureLiveOps(world),window=validWindow(startsAt,endsAt),cleanFeature=requireText(feature,"Feature"),row={id:`rollout-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,feature:cleanFeature,percentage:Math.max(0,Math.min(100,n(percentage))),startsAt:window.s,endsAt:window.e,conditions:{...conditions},status:"scheduled",createdBy:actor.id,createdAt:Date.now()};s.rollouts.push(row);trim(s.rollouts);s.history.push({kind:"rollout_created",id:row.id,feature:row.feature,actorId:actor.id,at:Date.now()});trim(s.history);adminControlSystem.log(actor,"live_rollout_created",{id:row.id,feature:row.feature,percentage:row.percentage});return row;}
export function featureAvailableFor(world,feature,{playerId="",companyLevel=0,country="",now=Date.now()}={}){const rows=ensureLiveOps(world).rollouts.filter(r=>r.feature===feature&&r.status!=="cancelled"&&r.startsAt<=now&&(!r.endsAt||r.endsAt>now));if(!rows.length)return false;const r=rows.at(-1);if(r.conditions.minCompanyLevel&&companyLevel<r.conditions.minCompanyLevel)return false;if(r.conditions.country&&r.conditions.country!==country)return false;const hash=[...String(playerId)].reduce((s,ch)=>s+ch.charCodeAt(0),0)%100;return hash<r.percentage;}
export function createLiveAnnouncement(world,{actor,title,message,severity="info",startsAt=Date.now(),endsAt=null}={}){adminControlSystem.requirePermission(actor,"liveops.write");const s=ensureLiveOps(world),window=validWindow(startsAt,endsAt),row={id:`la-${Date.now()}-${Math.random().toString(36).slice(2,5)}`,title:requireText(title,"Titel"),message:requireText(message,"Nachricht"),severity:String(severity||"info"),startsAt:window.s,endsAt:window.e,status:"scheduled",createdBy:actor.id,createdAt:Date.now()};s.announcements.push(row);trim(s.announcements);s.history.push({kind:"announcement_created",id:row.id,actorId:actor.id,at:Date.now()});trim(s.history);adminControlSystem.log(actor,"live_announcement_created",{id:row.id,title:row.title,severity:row.severity});return row;}
export function visibleAnnouncements(world,{now=Date.now()}={}){return ensureLiveOps(world).announcements.filter(a=>a.status!=="cancelled"&&a.startsAt<=now&&(!a.endsAt||a.endsAt>now));}
export function setMaintenanceMode(actor,enabled,{message="Wartungsarbeiten"}={}){adminControlSystem.requirePermission(actor,"system.write");adminControlSystem.updateSetting(actor,"maintenanceMode",!!enabled);adminControlSystem.log(actor,"maintenance_mode_changed",{enabled:!!enabled,message:String(message||"")});return{enabled:!!enabled,message:String(message||"")};}
export function liveOpsKpis(world){const s=ensureLiveOps(world);return{activeEvents:s.events.filter(x=>x.status==="active").length,scheduledEvents:s.events.filter(x=>x.status==="scheduled").length,cancelledEvents:s.events.filter(x=>x.status==="cancelled").length,rollouts:s.rollouts.length,announcements:s.announcements.length,history:s.history.length};}
