// Koordinator fuer Live-Ops, Support und Moderation. Keine Spieler-UI.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureLiveCoordinator(state={}){state.liveCoordinator??={maintenance:[],announcements:[],rollouts:[],supportSla:{urgentHours:2,highHours:8,normalHours:24,lowHours:72},moderationEscalations:[],events:[]};return state.liveCoordinator;}
export function scheduleMaintenance(state,{startsAt,durationMinutes=30,message='Wartungsarbeiten'}={}){const s=ensureLiveCoordinator(state),row={id:`maint-${Date.now()}`,startsAt:n(startsAt,Date.now()),endsAt:n(startsAt,Date.now())+Math.max(1,n(durationMinutes))*60000,message,status:'scheduled'};s.maintenance.push(row);return row;}
export function publishAnnouncement(state,{title,message,audience='all',startsAt=Date.now(),endsAt=null}={}){const s=ensureLiveCoordinator(state),row={id:`ann-${Date.now()}`,title,message,audience,startsAt,endsAt:endsAt?Number(endsAt):null,status:'active'};s.announcements.push(row);return row;}
export function createFeatureRollout(state,{feature,percentage=0,segments=[]}={}){const s=ensureLiveCoordinator(state),row={id:`roll-${Date.now()}`,feature,percentage:Math.max(0,Math.min(100,n(percentage))),segments:[...segments],status:'active',createdAt:Date.now()};s.rollouts.push(row);return row;}
export function rolloutEnabledFor(state,feature,userKey){const r=ensureLiveCoordinator(state).rollouts.find(x=>x.feature===feature&&x.status==='active');if(!r)return false;let hash=0;for(const ch of String(userKey||''))hash=(hash*31+ch.charCodeAt(0))>>>0;return hash%100<r.percentage;}
export function supportDeadline(state,{priority='normal',createdAt=Date.now()}={}){const s=ensureLiveCoordinator(state),hours=n(s.supportSla[`${priority}Hours`],24);return createdAt+hours*3600000;}
export function escalateModeration(state,{caseId,reason,severity='warning',actorId=null}={}){const s=ensureLiveCoordinator(state),row={id:`esc-${Date.now()}`,caseId,reason,severity,actorId,status:'open',createdAt:Date.now()};s.moderationEscalations.push(row);return row;}
export function liveCoordinatorTick(state,{now=Date.now()}={}){const s=ensureLiveCoordinator(state);for(const m of s.maintenance){if(m.status==='scheduled'&&now>=m.startsAt&&now<m.endsAt)m.status='active';if(['scheduled','active'].includes(m.status)&&now>=m.endsAt)m.status='done';}for(const a of s.announcements){if(a.endsAt&&now>=a.endsAt)a.status='expired';}return s;}
export function liveCoordinatorKpis(state){const s=ensureLiveCoordinator(state);return{maintenanceActive:s.maintenance.filter(x=>x.status==='active').length,announcementsActive:s.announcements.filter(x=>x.status==='active').length,rollouts:s.rollouts.filter(x=>x.status==='active').length,moderationOpen:s.moderationEscalations.filter(x=>x.status==='open').length};}
