// WorldProject – regionale Logistik-Hubs und Cross-Docking.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureHubNetwork(world={}){world.logisticsHubs??={hubs:[],links:[],shipments:[]};return world.logisticsHubs;}
export function createLogisticsHub(world,{id,name,region='central',capacity=10000,handlingCost=.08}={}){const s=ensureHubNetwork(world),hub={id:id||`hub-${Date.now()}`,name:name||'Logistik-Hub',region,capacity:Math.max(1,n(capacity)),used:0,handlingCost:Math.max(0,n(handlingCost)),inventory:{},status:'active'};s.hubs.push(hub);return hub;}
export function connectLogisticsHubs(world,fromId,toId,{distanceKm=100,costPerKm=1.2,transitHours=2}={}){const s=ensureHubNetwork(world);if(!s.hubs.some(x=>x.id===fromId)||!s.hubs.some(x=>x.id===toId))throw new Error('Hub fehlt');const row={id:`link-${fromId}-${toId}`,fromId,toId,distanceKm:n(distanceKm),costPerKm:n(costPerKm),transitHours:n(transitHours),status:'active'};s.links.push(row);return row;}
export function receiveAtHub(world,hubId,{productId,quantity,shipmentId=null}={}){const s=ensureHubNetwork(world),h=s.hubs.find(x=>x.id===hubId);if(!h)throw new Error('Hub fehlt');const q=Math.max(0,n(quantity));if(h.used+q>h.capacity)throw new Error('Hub-Kapazität reicht nicht');h.inventory[productId]=n(h.inventory[productId])+q;h.used+=q;const row={id:shipmentId||`hubin-${Date.now()}`,hubId,productId,quantity:q,status:'at_hub',arrivedAt:Date.now()};s.shipments.push(row);return row;}
export function crossDockShipment(world,fromHubId,toHubId,{productId,quantity,now=Date.now()}={}){const s=ensureHubNetwork(world),from=s.hubs.find(x=>x.id===fromHubId),to=s.hubs.find(x=>x.id===toHubId),link=s.links.find(x=>x.status==='active'&&x.fromId===fromHubId&&x.toId===toHubId);if(!from||!to||!link)throw new Error('Hub-Verbindung fehlt');const q=Math.max(0,n(quantity));if(n(from.inventory[productId])<q)throw new Error('Nicht genug Ware am Quell-Hub');from.inventory[productId]-=q;from.used=Math.max(0,from.used-q);const handling=q*(from.handlingCost+to.handlingCost),transport=link.distanceKm*link.costPerKm,shipment={id:`hubmove-${now}-${Math.random().toString(36).slice(2,6)}`,fromHubId,toHubId,productId,quantity:q,cost:handling+transport,status:'in_transit',departedAt:now,etaAt:now+link.transitHours*3600000};s.shipments.push(shipment);return shipment;}
export function completeHubTransit(world,shipmentId,{now=Date.now(),force=false}={}){const s=ensureHubNetwork(world),x=s.shipments.find(a=>a.id===shipmentId);if(!x)throw new Error('Hub-Sendung fehlt');if(x.status==='received')return{success:true,idempotent:true};if(!force&&now<x.etaAt)throw new Error('Sendung noch unterwegs');const h=s.hubs.find(a=>a.id===x.toHubId);if(!h)throw new Error('Ziel-Hub fehlt');if(h.used+x.quantity>h.capacity)throw new Error('Ziel-Hub voll');h.inventory[x.productId]=n(h.inventory[x.productId])+x.quantity;h.used+=x.quantity;x.status='received';x.receivedAt=now;return{success:true,shipment:x};}
export function hubNetworkKpis(world){const s=ensureHubNetwork(world);return{hubs:s.hubs.length,links:s.links.filter(x=>x.status==='active').length,inTransit:s.shipments.filter(x=>x.status==='in_transit').length,totalCapacity:s.hubs.reduce((a,x)=>a+n(x.capacity),0),used:s.hubs.reduce((a,x)=>a+n(x.used),0)};}
