// ORVUNO – Lieferantenstandorte + skalierende KI-Speditionen.
// KI deckt Transportluecken ab, solange Spieler-Speditionen den Markt noch nicht tragen.
const HUB_POOL=Object.freeze(['Hamburg, Deutschland','Bremen, Deutschland','Hannover, Deutschland','Bielefeld, Deutschland','Kassel, Deutschland','Paderborn, Deutschland','Dortmund, Deutschland','Duesseldorf, Deutschland','Koeln, Deutschland','Frankfurt am Main, Deutschland','Nuernberg, Deutschland','Stuttgart, Deutschland','Muenchen, Deutschland','Leipzig, Deutschland']);
export const FIXED_SUPPLIER_HUBS=Object.freeze({'malt-a':'Hamburg, Deutschland','malt-b':'Koeln, Deutschland','malt-c':'Kassel, Deutschland','hops-a':'Muenchen, Deutschland','hops-b':'Nuernberg, Deutschland','yeast-a':'Hannover, Deutschland','yeast-b':'Duesseldorf, Deutschland','water-a':'Warburg, Deutschland','water-b':'Paderborn, Deutschland','bottle-a':'Frankfurt am Main, Deutschland','bottle-b':'Hamburg, Deutschland','cap-a':'Kassel, Deutschland','cap-b':'Stuttgart, Deutschland','label-a':'Bielefeld, Deutschland','label-b':'Leipzig, Deutschland','wood-spruce-a':'Hameln, Deutschland','wood-spruce-b':'Hannover, Deutschland','wood-oak-a':'Frankfurt am Main, Deutschland','mdf-a':'Kassel, Deutschland','glue-a':'Dortmund, Deutschland','fittings-a':'Duesseldorf, Deutschland',brew_malt_north:'Hamburg, Deutschland',brew_malt_regional:'Kassel, Deutschland',brew_hops:'Muenchen, Deutschland',brew_packaging:'Frankfurt am Main, Deutschland',brew_basics:'Kassel, Deutschland',wood_regional:'Paderborn, Deutschland',wood_fittings:'Hannover, Deutschland',farm_seed:'Hannover, Deutschland',farm_inputs:'Kassel, Deutschland'});
export const AI_CARRIERS=Object.freeze([{id:'ai-freight-north',name:'NordCargo Logistik',hub:'Hamburg, Deutschland',basePrice:18,perKm:.92,reliability:.97,capacity:18},{id:'ai-freight-central',name:'MitteTrans Spedition',hub:'Kassel, Deutschland',basePrice:16,perKm:.88,reliability:.96,capacity:24},{id:'ai-freight-west',name:'Rheinland Fracht',hub:'Duesseldorf, Deutschland',basePrice:20,perKm:.95,reliability:.98,capacity:20},{id:'ai-freight-south',name:'SuedCargo Transporte',hub:'Nuernberg, Deutschland',basePrice:19,perKm:.90,reliability:.97,capacity:22},{id:'ai-freight-east',name:'ElbeLogistik',hub:'Leipzig, Deutschland',basePrice:17,perKm:.89,reliability:.95,capacity:18},{id:'ai-freight-regional',name:'RegionalExpress Fracht',hub:'Paderborn, Deutschland',basePrice:14,perKm:.96,reliability:.94,capacity:14}]);
const hash=s=>{let h=2166136261;for(const c of String(s||'unknown'))h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;};
export function supplierHubFor(source={}){const id=String(source.offerId||source.supplierId||source.id||source.name||'unknown');return source.routingAddress||source.originAddress||FIXED_SUPPLIER_HUBS[id]||HUB_POOL[hash(id)%HUB_POOL.length];}
function playerCarriers(){const market=typeof window!=='undefined'?(window.worldPlayerMarket||window.worldMarket||{}):{};const companies=Array.isArray(market.companies)?market.companies:[];return companies.filter(c=>['spedition','logistics','carrier','transport'].includes(String(c.industry||c.type||'').toLowerCase())&&Math.max(0,Number(c.transportCapacity||c.capacity||c.availableLoads||0))>0);}
export function marketTransportSnapshot(){const market=typeof window!=='undefined'?(window.worldPlayerMarket||window.worldMarket||{}):{};const companies=Array.isArray(market.companies)?market.companies:[];const carriers=playerCarriers();const playerCapacity=carriers.reduce((s,c)=>s+Math.max(0,Number(c.transportCapacity||c.capacity||c.availableLoads||0)),0);const demand=Math.max(1,Number(market.transportDemand||market.openTransportOrders||0)||Math.max(6,companies.length*2));return{playerCarrierCount:carriers.length,playerCapacity,demand,coverage:Math.min(1,playerCapacity/demand),carriers};}
export function activeAiCarriers(snapshot=marketTransportSnapshot()){const coverage=Math.max(0,Math.min(1,Number(snapshot.coverage)||0)),demand=Math.max(1,Number(snapshot.demand)||1),needed=Math.ceil(demand/12),factor=coverage>=.95?.2:coverage>=.75?.4:coverage>=.5?.65:1,count=Math.max(1,Math.min(AI_CARRIERS.length,Math.ceil(needed*factor)));return AI_CARRIERS.slice(0,count);}
function normalizedPlayerCarrier(c){return{type:'player',id:c.id||c.companyId||c.name,name:c.name||c.companyName||'Spieler-Spedition',hub:c.logisticsAddress||c.routingAddress||c.city||null,basePrice:Number(c.basePrice||c.deliveryBase||0),perKm:Number(c.perKm||c.deliveryPerKm||0),reliability:Number(c.reliability||1),capacity:Number(c.transportCapacity||c.capacity||c.availableLoads||0)};}
export function assignCarrier(order={},source={}){if(order.transportMode==='own'&&order.vehicleId)return{type:'player',id:order.vehicleId,name:'Eigener Fuhrpark',hub:null};if(order.carrier?.id)return order.carrier;const snapshot=marketTransportSnapshot(),seed=hash(order.id||order.offerId||order.supplierId||source.id||Date.now()),players=snapshot.carriers||[];let carrier=null;if(players.length&&snapshot.coverage>0){const playerChance=Math.max(.15,Math.min(.95,snapshot.coverage));if((seed%1000)/1000<playerChance)carrier=normalizedPlayerCarrier(players[seed%players.length]);}if(!carrier){const candidates=activeAiCarriers(snapshot),ai=candidates[seed%candidates.length]||AI_CARRIERS[0];carrier={...ai,type:'ai'};}order.carrier=carrier;order.carrierId=carrier.id;order.carrierName=carrier.name;order.transportMode=order.transportMode||'supplier';return carrier;}
export function prepareLogistics(order={},source={}){const supplierHub=supplierHubFor({...source,...order}),carrier=assignCarrier(order,source);order.supplierLogisticsHub=supplierHub;order.routeOrigin=order.routeOrigin||{query:supplierHub,label:supplierHub};order.transportProvider={id:carrier.id,name:carrier.name,type:carrier.type,hub:carrier.hub||supplierHub};return{supplierHub,carrier};}
export function runLogisticsCarrierSystemTest(){const old={id:'legacy-order',supplierId:'brew_basics',status:'in_transit'};const r=prepareLogistics(old,{});if(!r.supplierHub||!old.routeOrigin?.query||!old.carrierName)throw new Error('Legacy-Lieferung wurde nicht logistisch vorbereitet');const unknown=prepareLogistics({id:'x1',supplierId:'new-player-supplier-77'},{});if(!unknown.supplierHub)throw new Error('Neuer Lieferant ohne Standort');const low=activeAiCarriers({coverage:0,demand:48}),high=activeAiCarriers({coverage:1,demand:48});if(!(low.length>high.length))throw new Error('KI-Speditionen skalieren nicht mit Spielerabdeckung');return true;}
if(typeof window!=='undefined'){window.worldLogisticsCarriers={supplierHubFor,assignCarrier,prepareLogistics,activeAiCarriers,marketTransportSnapshot,runTest:runLogisticsCarrierSystemTest};try{window.worldLogisticsCarrierHealth={success:runLogisticsCarrierSystemTest(),snapshot:marketTransportSnapshot()};}catch(error){window.worldLogisticsCarrierHealth={success:false,error:error?.message||String(error)};console.error('❌ HEALTH Logistik/Spedition',error);}}
