// WorldProject – Mehrjahres-Unternehmenssimulation für alle Gewerbe.
import { IndustryProfiles } from "./IndustryCatalog.js";
import { industryRecipes, procureInstantForTest, startIndustryJob, finishIndustryJob, sellIndustryOutput } from "./UniversalIndustryCycle.js";
import { enterpriseValue, addRegion, acquireSite, createExpansionProject, advanceProjects, triggerStrategicEvent, updateMacroEnvironment, strategyKpis } from "./CorporateStrategyAndExpansion.js";
import { closeFinancePeriod, liquidityForecast } from "./IndustryFinanceAndTax.js";
import { addExperience } from "./IndustryGrowthSystem.js";
import { seedCompetitors, marketShare } from "./IndustryCompetitionEngine.js";
import { ensureCustomerLifecycle, upsertCustomer } from "./CustomerOrderLifecycle.js";
import { ensureWorkforceOrganization, definePosition } from "./WorkforceOrganizationSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function seedCompany(type){const p=IndustryProfiles[type];const c={type,branchKey:p.branchKey,money:250000,inventory:{},finishedGoods:{},productionJobs:[],salesLedger:[],costLedger:[],employees:[],customerOrders:[],buildingState:{equipment:(p.equipment||[]).map((x,i)=>({...x,instanceId:`${x.id}-${i}`,condition:100,status:"available",purchasePrice:n(x.price)}))}};for(const m of c.buildingState.equipment)c.money-=n(m.price);addRegion(c,{id:"home",name:"Heimatregion"});ensureCustomerLifecycle(c);upsertCustomer(c,{id:"anchor",name:"Stammkunde",segment:"large_business",creditScore:85});ensureWorkforceOrganization(c);definePosition(c,{role:"operations",department:"operations",target:2,minimum:1,baseMonthly:3200});seedCompetitors(c);return c;}
function cheapestRecipe(c){return industryRecipes(c)[0]||null;}
function procureRecipeInputs(c,r,amount){const factor=amount/Math.max(1,n(r.output,1));for(const[id,q]of Object.entries(r.materials||{})){const need=n(q)*factor,have=n(c.inventory[id]);if(have<need)procureInstantForTest(c,id,need-have);}}
function simulateMonth(c,{year,month,macro=1,crisis=null}={}){updateMacroEnvironment(c,{economy:macro,rawMaterials:1+(1-macro)*.2,energy:1+(1-macro)*.15,interest:1+(1-macro)*.1,season:.9+((month%12)/60)});if(crisis)triggerStrategicEvent(c,{kind:crisis,severity:.4});const r=cheapestRecipe(c);if(!r)return{success:false,reason:"no_recipe"};const base=Math.max(1,n(r.output,1)),share=marketShare(c,{ownPriceIndex:1,ownQuality:80}),demand=Math.max(1,Math.round(base*(.35+share*5)*macro));procureRecipeInputs(c,r,demand);const start=startIndustryJob(c,r.id,demand,{requestId:`sim-${year}-${month}`,now:year*100000000000+month*10000000});finishIndustryJob(c,start.job.id,{force:true,now:start.job.endsAt+1});const unitPrice=Math.max(.01,(start.job.variableCost/Math.max(1,demand)+5)*(1.25+share));const sale=sellIndustryOutput(c,r.product,demand,unitPrice,{requestId:`sim-sale-${year}-${month}`,now:start.job.endsAt+2});addExperience(c,Math.max(10,sale.revenue/20));c.costLedger.push({kind:"monthly_overhead",amount:2500+(c.employees.length*3000),at:start.job.endsAt+3});c.money-=2500+(c.employees.length*3000);return{success:true,revenue:sale.revenue,demand,unitPrice,marketShare:share};}
export function simulateCompanyYears(type,{years=5,expandAfterYear=2,crisisYear=3}={}){const c=seedCompany(type),history=[];let failed=null;for(let year=1;year<=years;year++){let revenue=0;for(let month=1;month<=12;month++){const macro=year===crisisYear?.78:year===crisisYear+1?.9:1+(year>1?.03:0),crisis=year===crisisYear&&month===4?"economic_crisis":null;try{const m=simulateMonth(c,{year,month,macro,crisis});if(!m.success){failed=m.reason;break;}revenue+=n(m.revenue);}catch(e){failed=e.message;break;}}if(failed)break;if(year===expandAfterYear&&c.money>50000){try{const site=acquireSite(c,{name:`Standort ${year}`,regionId:"home",mode:"rent",rentMonthly:3500,capacity:1.2});createExpansionProject(c,{siteId:site.id,kind:"production",cost:20000,durationDays:30,capacityBonus:.2,now:year*31536000000});advanceProjects(c,{now:year*31536000000+60*86400000});}catch{}}
 const from=(year-1)*31536000000,to=year*31536000000;let finance;try{finance=closeFinancePeriod(c,{period:`year-${year}`,from,to,taxRate:.3});}catch{finance={profit:0};}history.push({year,revenue,money:n(c.money),enterpriseValue:enterpriseValue(c).equityValue,profit:n(finance.profit),liquidity:liquidityForecast(c).forecast,sites:strategyKpis(c).sitesActive});}
 return{success:!failed,type,yearsCompleted:history.length,failed,company:c,history,final:history.at(-1)||null};}
export function runLongTermAllIndustrySimulation({years=5}={}){const rows=Object.keys(IndustryProfiles).map(type=>{try{return simulateCompanyYears(type,{years});}catch(e){return{success:false,type,yearsCompleted:0,failed:e.message,history:[]};}}),failed=rows.filter(x=>!x.success),report={success:failed.length===0,total:rows.length,passed:rows.length-failed.length,failed,rows,years,ranAt:Date.now()};if(typeof window!=="undefined")window.worldLongTermCompanySimulation=report;console[report.success?"log":"error"](`WORLDPROJECT LANGZEITSIMULATION ${report.passed}/${report.total} Gewerbe · ${years} Jahre`,report);return report;}
