// Maschinenlebenszyklus fuer alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureMachineLifecycle(c={}){c.machineLifecycle??={spareParts:{},history:[],replacementPlans:[]};return c.machineLifecycle;}
export function machineHealth(machine){const condition=clamp(n(machine.condition,100),0,100),runtime=n(machine.runtimeHours),ageDays=machine.purchasedAt?Math.max(0,(Date.now()-machine.purchasedAt)/86400000):0;const failureRisk=clamp((100-condition)/140+runtime/10000+ageDays/5000,0,.95);return{condition,runtime,ageDays,failureRisk,state:condition>=80?'excellent':condition>=60?'good':condition>=35?'worn':condition>=20?'critical':'failed'};}
export function requiredSpareParts(machine,{repairPoints=25}={}){const severity=Math.max(1,Math.ceil(Math.max(0,n(repairPoints))/20));return[{id:`part-${machine.id||'generic'}`,quantity:severity}];}
export function canRepair(c,machine,opts={}){const life=ensureMachineLifecycle(c),parts=requiredSpareParts(machine,opts);return{ok:parts.every(p=>n(life.spareParts[p.id])>=p.quantity),parts};}
export function repairMachineLifecycle(c,machine,{repairPoints=25,cost=500,now=Date.now()}={}){const life=ensureMachineLifecycle(c),check=canRepair(c,machine,{repairPoints});if(!check.ok)throw new Error('Ersatzteile fehlen');if(n(c.money)<n(cost))throw new Error('Nicht genug Geld');for(const p of check.parts)life.spareParts[p.id]=n(life.spareParts[p.id])-p.quantity;c.money-=n(cost);const before=n(machine.condition,100);machine.condition=clamp(before+n(repairPoints),0,100);machine.status='available';life.history.push({kind:'repair',machineId:machine.instanceId||machine.id,before,after:machine.condition,cost:n(cost),at:now});return machine;}
export function planReplacement(c,machine,{targetDate=Date.now()+30*86400000,budget=null}={}){const life=ensureMachineLifecycle(c),health=machineHealth(machine),row={id:`replace-${Date.now()}`,machineId:machine.instanceId||machine.id,targetDate,budget:n(budget,machine.purchasePrice||0),priority:health.state==='failed'?100:Math.round(health.failureRisk*100),status:'planned'};life.replacementPlans.push(row);return row;}
export function lifecycleUpgrade(machine,{capacityBonus=.15,conditionBonus=5,cost=0}={}){machine.capacity=n(machine.capacity,1)*(1+Math.max(0,n(capacityBonus)));machine.condition=clamp(n(machine.condition,100)+n(conditionBonus),0,100);machine.lifecycleUpgradeLevel=n(machine.lifecycleUpgradeLevel)+1;return{machine,cost:n(cost)};}
export function machineLifecycleKpis(c){const machines=c.buildingState?.equipment||[];const h=machines.map(machineHealth);return{machines:h.length,critical:h.filter(x=>['critical','failed'].includes(x.state)).length,averageCondition:h.length?h.reduce((s,x)=>s+x.condition,0)/h.length:100,averageFailureRisk:h.length?h.reduce((s,x)=>s+x.failureRisk,0)/h.length:0,replacements:ensureMachineLifecycle(c).replacementPlans.filter(x=>x.status==='planned').length};}
