// WorldProject - Wartung direkt im Betriebsdashboard starten und Restzeit sehen.
import { EconomyDashboard } from './EconomyDashboard.js';
import { allMachines,maintenanceQuote,startMachineMaintenance,processMachineMaintenance } from './MachineMaintenanceSystem.js';
import { machineConditionState } from './MachineConditionProductionGuard.js';
const machineName=m=>m?.label||m?.name||String(m?.sourceType||m?.type||m?.equipmentId||m?.id||'Maschine').replace(/_/g,' ');
const remaining=ms=>{const min=Math.max(0,Math.ceil(ms/60000));return min>=60?`${Math.floor(min/60)} Std. ${min%60} Min.`:`${min} Min.`;};
function start(dashboard,panel,machine,full=false){const q=maintenanceQuote(machine,{full}),kind=full?'Vollwartung':'Wartung';if(!confirm(`${kind} für ${machineName(machine)} starten?\nKosten: ${dashboard.money(q.cost)} €\nDauer: ${remaining(q.durationMs)}\nZustand: ${Math.round(q.condition)} % → ${Math.round(q.target)} %`))return;const r=startMachineMaintenance(dashboard.company,machine,{full});if(!r.success){const msg=r.reason==='money'?`Nicht genug Betriebsgeld. Benötigt: ${dashboard.money(r.required)} €`:r.reason==='busy'?'Maschine ist gerade in Benutzung.':r.reason==='already_running'?'Für diese Maschine läuft bereits eine Wartung.':r.reason==='not_needed'?'Diese Wartung würde den Zustand nicht verbessern.':'Wartung konnte nicht gestartet werden.';alert(msg);return;}window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason:'machine-maintenance-start'}}));dashboard.render(panel);}
const p=EconomyDashboard.prototype;
if(!p.__worldMachineMaintenanceUI){p.__worldMachineMaintenanceUI=true;const old=p.render;p.render=function(panel){processMachineMaintenance(this.company);const result=old.call(this,panel),production=panel.querySelector('#dashboard-production');if(!production)return result;production.querySelector('[data-machine-maintenance-ui]')?.remove();const machines=allMachines(this.company),box=this.el('div');box.dataset.machineMaintenanceUi='1';Object.assign(box.style,{margin:'12px 0',padding:'10px',border:'1px solid rgba(255,255,255,.16)',borderRadius:'8px',background:'rgba(0,0,0,.12)'});box.append(this.el('strong','🔧 Maschinenwartung'));if(!machines.length)box.append(this.small('Noch keine Maschine vorhanden.'));for(const m of machines){const state=machineConditionState(m),job=m.maintenanceJob,row=this.el('div');Object.assign(row.style,{marginTop:'8px',padding:'8px',borderRadius:'7px',background:'rgba(255,255,255,.05)'});row.append(this.el('strong',`${machineName(m)} · ${Math.round(state.condition)} %`));if(job&&job.status==='maintenance'&&Number(job.completeAt)>Date.now()){row.append(this.small(`🔧 Wartung läuft · noch ${remaining(Number(job.completeAt)-Date.now())} · Ziel ${Math.round(job.targetCondition)} %`));}else if(state.condition>=100){row.append(this.small('✅ Zustand 100 % · keine Wartung erforderlich.'));}else{const q=maintenanceQuote(m),full=maintenanceQuote(m,{full:true});row.append(this.small(state.state==='critical'?'🔴 Produktion gesperrt, bis der Zustand wieder ausreichend ist.':state.state==='maintenance_due'?'🟠 Wartung empfohlen, bevor die Maschine kritisch wird.':'🟢 Wartung ist freiwillig.'));const buttons=this.el('div');Object.assign(buttons.style,{display:'flex',gap:'6px',flexWrap:'wrap',marginTop:'6px'});const normal=this.button(`Warten → ${Math.round(q.target)} % · ${this.money(q.cost)} €`,()=>start(this,panel,m,false));buttons.append(normal);if(full.target>q.target){const complete=this.button(`Vollwartung → 100 % · ${this.money(full.cost)} €`,()=>start(this,panel,m,true));buttons.append(complete);}row.append(buttons);}box.append(row);}production.append(box);return result;};}
export function runMachineMaintenanceUITest(){return typeof startMachineMaintenance==='function'&&typeof maintenanceQuote==='function';}
