// WorldProject - echte Maschinenwartung: kostet Geld, braucht Zeit und blockiert Nutzung.
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const now=()=>Date.now();
function condition(m){return clamp(Number.isFinite(Number(m?.condition))?Number(m.condition):100,0,100);}
function price(m){return Math.max(500,Number(m?.purchasePrice??m?.price??m?.cost??5000)||5000);}
export function maintenanceQuote(machine,{full=false}={}){const c=condition(machine),missing=100-c,p=price(machine),target=full?100:Math.max(70,c),gain=Math.max(0,target-c),cost=Math.max(75,Math.round(p*(full?.018:.011)*Math.max(.25,gain/50))),minutes=Math.round(clamp((full?45:25)+gain*2.2,20,360));return{condition:c,target,gain,cost,durationMs:minutes*60000,minutes};}
export function startMachineMaintenance(company,machine,{full=false,at=now()}={}){if(!company||!machine)return{success:false,reason:'missing'};if(machine.maintenanceJob&&machine.maintenanceJob.completeAt>at)return{success:false,reason:'already_running',job:machine.maintenanceJob};if(machine.busy||['producing','reserved'].includes(String(machine.status||'')))return{success:false,reason:'busy'};const q=maintenanceQuote(machine,{full});if(q.gain<=0)return{success:false,reason:'not_needed'};if(Number(company.money||0)<q.cost)return{success:false,reason:'money',required:q.cost};company.money=Number(company.money||0)-q.cost;const job={id:`maint_${machine.instanceId??machine.id??'machine'}_${at}`,startedAt:at,completeAt:at+q.durationMs,cost:q.cost,fromCondition:q.condition,targetCondition:q.target,status:'maintenance'};machine.maintenanceJob=job;machine.status='maintenance';company.financialLog??=[];company.financialLog.push({at,type:'expense',category:'maintenance',amount:-q.cost,label:`Maschinenwartung ${machine.label||machine.name||machine.id||''}`.trim()});return{success:true,job,quote:q};}
export function processMachineMaintenance(company,at=now()){let completed=0;for(const machine of allMachines(company)){const j=machine.maintenanceJob;if(!j||j.status!=='maintenance'||Number(j.completeAt)>at)continue;machine.condition=clamp(Number(j.targetCondition)||100,0,100);j.status='completed';j.completedAt=at;machine.status='available';machine.maintenanceJob=null;completed++;}return completed;}
export function allMachines(company={}){const rows=[...(company.productionMachines||[]),...(company.buildingState?.equipment||[]),...(company.workforceState?.machines||[]),...(company.workforceOperationsState?.machines||[]),...(company.machines||[])],seen=new Set(),out=[];for(const m of rows){if(!m||m.status==='sold')continue;const key=String(m.instanceId??m.id??`${m.type||m.sourceType}:${m.label||m.name||''}`);if(seen.has(key))continue;seen.add(key);out.push(m);}return out;}
export function runMachineMaintenanceTest(){const c={money:10000,buildingState:{equipment:[{instanceId:'x',id:'brew',condition:20,purchasePrice:10000,status:'available'}]}},m=c.buildingState.equipment[0],r=startMachineMaintenance(c,m,{at:1000});if(!r.success||c.money>=10000||m.status!=='maintenance')throw new Error('Wartung startet nicht korrekt');if(processMachineMaintenance(c,r.job.completeAt-1)!==0)throw new Error('Wartung endet zu früh');if(processMachineMaintenance(c,r.job.completeAt)!==1||m.condition<70||m.status!=='available')throw new Error('Wartung wird nicht korrekt abgeschlossen');return true;}
if(typeof window!=='undefined')window.worldMachineMaintenance={quote:maintenanceQuote,start:startMachineMaintenance,process:processMachineMaintenance,machines:allMachines,test:runMachineMaintenanceTest};
