// WorldProject - Maschinen, Stellplaetze, Upgrades, Verschleiss und Wartung
export class MachineOperationsSystem{
 constructor({catalog={}}={}){this.catalog=catalog;this.machines=[];this.seq=1;}
 registerType(id,data){this.catalog[id]={id,...data};return this.catalog[id];}
 buy(company,type){const c=this.catalog[type];if(!c)throw new Error("Unbekannter Maschinentyp");if(Number(company.money||0)<Number(c.price||0))throw new Error("Nicht genug Betriebsgeld");company.machineSlots=Number(company.machineSlots||0);const used=this.machines.filter(m=>m.companyId===company.id&&m.status!=="sold").reduce((s,m)=>s+Number(m.slots||1),0);if(used+Number(c.slots||1)>company.machineSlots)throw new Error("Nicht genug Maschinenstellplaetze");company.money-=Number(c.price||0);const m={id:this.seq++,companyId:company.id,type,label:c.label||type,slots:Number(c.slots||1),level:1,hours:0,condition:1,reliability:Number(c.reliability||.98),capacity:Number(c.capacity||1),energy:Number(c.energy||1),status:"available",lastServiceHours:0,nextServiceHours:Number(c.serviceIntervalHours||500)};this.machines.push(m);return m;}
 upgrade(company,id){const m=this.machines.find(x=>x.id===id&&x.status!=="sold");if(!m)throw new Error("Maschine nicht gefunden");const c=this.catalog[m.type]||{},cost=Math.round(Number(c.upgradeBaseCost||c.price*.25||1000)*Math.pow(Number(c.upgradeGrowth||1.18),m.level-1));if(Number(company.money||0)<cost)throw new Error("Nicht genug Betriebsgeld");company.money-=cost;m.level++;m.capacity*=Number(c.capacityPerLevel||1.02);m.reliability=Math.min(.999,m.reliability+Number(c.reliabilityPerLevel||.002));m.energy*=Number(c.energyPerLevel||.995);return{machine:m,cost};}
 operate(id,hours,{random=Math.random}={}){const m=this.machines.find(x=>x.id===id&&x.status!=="sold");if(!m||m.status==="broken")throw new Error("Maschine nicht betriebsbereit");const h=Math.max(0,Number(hours));m.hours+=h;m.condition=Math.max(.05,m.condition-h/20000);const wearRisk=(1-m.condition)*.025*h/8,baseRisk=(1-m.reliability)*h/8;if(random()<Math.min(.75,wearRisk+baseRisk)){m.status="broken";m.failureAtHours=m.hours;}if(m.hours>=m.nextServiceHours)m.serviceDue=true;return{hours:h,capacity:m.capacity*h,condition:m.condition,broken:m.status==="broken",serviceDue:!!m.serviceDue};}
 service(company,id){const m=this.machines.find(x=>x.id===id&&x.status!=="sold");if(!m)throw new Error("Maschine nicht gefunden");const c=this.catalog[m.type]||{},cost=Math.round(Number(c.serviceBaseCost||500)*(1+(1-m.condition)*2));if(Number(company.money||0)<cost)throw new Error("Nicht genug Betriebsgeld");company.money-=cost;m.condition=Math.min(1,m.condition+.2);m.status="available";m.serviceDue=false;m.lastServiceHours=m.hours;m.nextServiceHours=m.hours+Number(c.serviceIntervalHours||500);return{cost,machine:m};}
}
export function runMachineOperationsTest(){const company={id:1,money:100000,machineSlots:3},s=new MachineOperationsSystem({catalog:{filler:{label:"Abfueller",price:10000,slots:2,capacity:100,reliability:.99,serviceIntervalHours:100}}}),m=s.buy(company,"filler"),u=s.upgrade(company,m.id),r=s.operate(m.id,8,{random:()=>1});if(m.level!==2||u.cost<=0||r.capacity<=800)throw new Error("Maschinen-Test fehlgeschlagen");console.log("⚙️ MASCHINEN/STELLPLAETZE/UPGRADES/VERSCHLEISS ERFOLGREICH");return true;}
