// Dynamische Preisstrategie fuer alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureMarketPricing(c={}){c.marketPricing??={products:{},history:[],competitorIndex:1,regionalDemand:{}};return c.marketPricing;}
export function setProductPricing(c,productId,{cost,price,referencePrice=null,elasticity=1,minMargin=.1}={}){const s=ensureMarketPricing(c),row=s.products[productId]??={productId};Object.assign(row,{cost:Math.max(0,n(cost)),price:Math.max(0,n(price)),referencePrice:referencePrice==null?Math.max(0,n(price)):Math.max(0,n(referencePrice)),elasticity:Math.max(.05,n(elasticity,1)),minMargin:clamp(n(minMargin,.1),0,.9)});s.products[productId]=row;return row;}
export function priceFloor(c,productId){const p=ensureMarketPricing(c).products[productId];if(!p)return 0;return p.cost/Math.max(.01,1-p.minMargin);}
export function demandAtPrice(c,productId,{price=null,region='default'}={}){const s=ensureMarketPricing(c),p=s.products[productId];if(!p)return 0;const current=price==null?p.price:n(price),relative=p.referencePrice?current/p.referencePrice:1,base=n(s.regionalDemand[region],1),comp=clamp(2-n(s.competitorIndex,1),.4,1.6);return Math.max(.05,base*Math.pow(Math.max(.1,relative),-p.elasticity)*comp);}
export function recommendPrice(c,productId,{region='default',steps=40,maxMultiplier=1.8}={}){const s=ensureMarketPricing(c),p=s.products[productId];if(!p)throw new Error('Preisprodukt fehlt');const floor=priceFloor(c,productId),ceiling=Math.max(floor,p.referencePrice*maxMultiplier);let best={price:floor,profitIndex:-Infinity,demand:0};for(let i=0;i<=steps;i++){const price=floor+(ceiling-floor)*i/steps,demand=demandAtPrice(c,productId,{price,region}),profit=(price-p.cost)*demand;if(profit>best.profitIndex)best={price,demand,profitIndex:profit};}return best;}
export function applyPromotion(c,productId,{discount=.1,durationDays=7}={}){const s=ensureMarketPricing(c),p=s.products[productId];if(!p)throw new Error('Preisprodukt fehlt');const floor=priceFloor(c,productId),promoPrice=Math.max(floor,p.price*(1-clamp(n(discount,.1),0,.9)));const row={productId,normalPrice:p.price,promoPrice,startsAt:Date.now(),endsAt:Date.now()+Math.max(1,n(durationDays))*86400000};p.promotion=row;s.history.push({kind:'promotion',...row});return row;}
export function competitorReaction(c,{ownPriceChange=0,ownQualityChange=0}={}){const s=ensureMarketPricing(c);s.competitorIndex=clamp(n(s.competitorIndex,1)+n(ownPriceChange)*.2-n(ownQualityChange)*.1,.5,1.7);return s.competitorIndex;}
export function marketPricingKpis(c){const s=ensureMarketPricing(c),products=Object.values(s.products);return{products:products.length,lossRisk:products.filter(p=>p.price<priceFloor(c,p.productId)).length,activePromotions:products.filter(p=>p.promotion&&p.promotion.endsAt>Date.now()).length,competitorIndex:s.competitorIndex};}
