// WorldProject - sichtbarer Markt, Zeitarbeit und Fahrzeugausbau
import { CustomerMarketSystem } from "./MarketSalesSystem.js";
import { TempAgencySystem, applyFleetUpgrade, upgradedVehicleStats, fleetUpgradeCost } from "./TempAgencyAndFleetUpgradeSystem.js";
import { worldContentRegistry } from "./ContentRegistry.js";

export class MarketFleetDialog{
 constructor({parent=document.body}={}){this.parent=parent;this.overlay=null;this.market=new CustomerMarketSystem();this.agency=new TempAgencySystem();this.vehicles=[{id:1,label:"Sattelzug",payloadKg:24000,tankLitres:1000,fuelConsumptionPer100Km:30,reliability:.9,powerHp:450,upgrades:{}}];}
 el(t,x=null){const e=document.createElement(t);if(x!==null)e.textContent=x;return e;}
 button(x,fn){const b=this.el("button",x);Object.assign(b.style,{padding:"8px 10px",margin:"4px",border:0,borderRadius:"7px",fontWeight:"700",cursor:"pointer"});b.onclick=fn;return b;}
 money(v){return Number(v||0).toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
 async open(){if(this.overlay)return;const industry=window.worldActiveServerCompany?.industry||window.worldPlayerCompany?.industry||"brewery",ov=this.el("div");Object.assign(ov.style,{position:"fixed",inset:0,zIndex:23500,background:"rgba(0,0,0,.75)",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px"});const p=this.el("div");Object.assign(p.style,{width:"min(1100px,97vw)",maxHeight:"94vh",overflow:"auto",background:"#fff",color:"#111",borderRadius:"14px",padding:"20px",fontFamily:"Arial,sans-serif"});ov.append(p);this.parent.append(ov);this.overlay=ov;this.render(p,industry);}
 close(){this.overlay?.remove();this.overlay=null;}
 render(p,industry){p.innerHTML="";const h=this.el("div");Object.assign(h.style,{display:"flex",justifyContent:"space-between"});h.append(this.el("h2","💶 Markt, Zeitarbeit & Fuhrpark"),this.button("✕",()=>this.close()));p.append(h);
 const market=this.el("section");market.append(this.el("h3","Kunden & Verkauf"),this.el("div","Kundentypen, Aufträge, Lieferverträge, Nachfrage, Qualität, Reputation und freie Verkaufspreise sind im Marktkern vorbereitet."));const types=worldContentRegistry.list("customerTypes").filter(c=>(c.industries||[]).includes("*")||(c.industries||[]).includes(industry));market.append(this.el("div",`Verfügbare Kundengruppen: ${types.map(x=>x.label).join(", ")||"noch keine branchenspezifischen Kundengruppen"} · Reputation ${this.market.reputation.toFixed(1)}`));p.append(market);
 const temp=this.el("section");temp.append(this.el("h3","Zeitarbeitsfirma"),this.el("div","Fehlt eigenes Personal wegen Schulung oder Auftragsspitze, kann tageweise Ersatz gemietet werden. Zeitarbeit ist teurer als Stammpersonal."));for(const o of this.agency.offers({industry})){const row=this.el("div",`${o.label} · verfügbar ${o.available} · Qualifikation ${o.qualification.toFixed(2)} · ${this.money(o.totalDailyCost)}/Tag`);row.append(this.button("Für heute mieten",()=>{try{this.agency.hire({roleId:o.id,industry,date:new Date(),shiftId:"early"});alert(`${o.label} für heute gemietet.`);this.render(p,industry);}catch(e){alert(e.message);}}));temp.append(row);}temp.append(this.el("div",`Heutige Zeitarbeitskosten: ${this.money(this.agency.dailyCost(new Date()))}`));p.append(temp);
 const fleet=this.el("section");fleet.append(this.el("h3","Fuhrpark-Ausbau"));for(const v of this.vehicles){const s=upgradedVehicleStats(v),box=this.el("div");Object.assign(box.style,{border:"1px solid #ddd",padding:"10px",margin:"8px 0",borderRadius:"8px"});box.append(this.el("strong",v.label),this.el("div",`Verbrauch ${s.fuelConsumptionPer100Km.toFixed(1)} l/100 km · Tank ${s.tankLitres} l · Nutzlast ${Math.round(s.payloadKg)} kg · Motor ${v.powerHp||"–"} PS`));for(const u of worldContentRegistry.list("fleetUpgrades")){const lvl=Number(v.upgrades?.[u.id]||0);if(lvl>=u.maxLevel)continue;box.append(this.button(`${u.label} ${lvl}→${lvl+1} (${this.money(fleetUpgradeCost(u.id,lvl))})`,()=>{try{applyFleetUpgrade(v,u.id);this.render(p,industry);}catch(e){alert(e.message);}}));}fleet.append(box);}p.append(fleet);
 }
}
