// WorldProject - Verkauf, Kunden, Nachfrage, Vertraege und Reputation
import { worldContentRegistry } from "./ContentRegistry.js";
export function customerTypesForIndustry(industry){return worldContentRegistry.list("customerTypes").filter(c=>(c.industries||[]).includes("*")||(c.industries||[]).includes(industry));}
export function regionalDemand({baseDemand=1,regionFactor=1,seasonFactor=1,supplyFactor=1}={}){return Math.max(.05,Number(baseDemand)*Number(regionFactor)*Number(seasonFactor)/Math.max(.25,Number(supplyFactor)));}
export function marketReferencePrice({basePrice,demand=1,supply=1,quality=1}={}){return Math.max(.01,Number(basePrice||0)*Math.max(.5,demand)/Math.max(.5,supply)*Math.max(.75,Math.min(1.3,quality)));}
export function expectedSales({available=0,price,referencePrice,demand=1,quality=1,reputation=50,priceSensitivity=1}={}){const ratio=Math.max(.1,Number(price||0)/Math.max(.01,Number(referencePrice||1))),priceFactor=Math.max(.05,Math.min(2.5,Math.pow(1/ratio,Number(priceSensitivity||1)))),q=Math.max(.5,Math.min(1.5,Number(quality||1))),rep=.6+Math.max(0,Math.min(100,Number(reputation||50)))/125;return Math.max(0,Math.min(Number(available||0),Math.floor(Number(demand||0)*priceFactor*q*rep)));}
export class CustomerMarketSystem{
 constructor(){this.customers=[];this.orders=[];this.contracts=[];this.invoices=[];this.regions={};this.seq=1;this.reputation=50;}
 region(id="default"){return this.regions[id]??=( {id,demandFactor:1,supplyFactor:1,seasonFactor:1,lastSales:0,lastSupply:0} );}
 setRegion(id,patch={}){Object.assign(this.region(id),patch);return this.region(id);}
 quoteMarket({region="default",basePrice=1,baseDemand=1000,quality=1,available=0,price=basePrice,priceSensitivity=1}={}){const r=this.region(region),demand=regionalDemand({baseDemand,regionFactor:r.demandFactor,seasonFactor:r.seasonFactor,supplyFactor:r.supplyFactor}),referencePrice=marketReferencePrice({basePrice,demand:Math.max(.5,demand/baseDemand),supply:r.supplyFactor,quality}),sales=expectedSales({available,price,referencePrice,demand,quality,reputation:this.reputation,priceSensitivity});return {region,demand,referencePrice,expectedSales:sales,regional:r};}
 recordMarketActivity({region="default",sold=0,supplied=0}={}){const r=this.region(region);r.lastSales=Number(sold||0);r.lastSupply=Number(supplied||0);const pressure=(Number(supplied||0)-Number(sold||0))/Math.max(1,Number(sold||0)+Number(supplied||0));r.supplyFactor=Math.max(.65,Math.min(1.6,r.supplyFactor+pressure*.08));r.demandFactor=Math.max(.65,Math.min(1.6,r.demandFactor-pressure*.03));return r;}
 addCustomer({typeId,name,industry,region="default",reputationRequired=0}={}){const type=worldContentRegistry.get("customerTypes",typeId);if(!type)throw new Error("Unbekannter Kundentyp");const c={id:this.seq++,typeId,name:name||type.label,industry,region,reputationRequired:Number(reputationRequired||0),relationship:50,active:true};this.customers.push(c);return c;}
 createOrder({customerId,product,quantity,unitPrice,dueAt,qualityMin=0,penaltyPerMissing=0,region="default",contractId=null,periodNo=null}={}){const c=this.customers.find(x=>x.id===customerId&&x.active);if(!c)throw new Error("Kunde nicht gefunden");if(this.reputation<c.reputationRequired)throw new Error("Reputation reicht fuer diesen Kunden nicht");const o={id:this.seq++,customerId,product,quantity:Number(quantity),delivered:0,unitPrice:Number(unitPrice),dueAt:Number(dueAt||Date.now()),qualityMin:Number(qualityMin||0),penaltyPerMissing:Number(penaltyPerMissing||0),region:c.region||region,status:"open",contractId,periodNo,penaltyBooked:0};this.orders.push(o);return o;}
 createSupplyContract({customerId,product,quantityPerPeriod,unitPrice,periodDays=7,periods=4,penaltyPerMissing=0,startAt=Date.now()}={}){const customer=this.customers.find(x=>x.id===customerId&&x.active);if(!customer)throw new Error("Kunde nicht gefunden");const c={id:this.seq++,customerId,product,quantityPerPeriod:Number(quantityPerPeriod),unitPrice:Number(unitPrice),periodDays:Number(periodDays),periods:Number(periods),penaltyPerMissing:Number(penaltyPerMissing),active:true,completedPeriods:0,generatedPeriods:0,startAt:Number(startAt),nextDueAt:Number(startAt)+Number(periodDays)*86400000};this.contracts.push(c);return c;}
 processContracts(now=Date.now()){const generated=[];for(const c of this.contracts.filter(x=>x.active)){while(c.generatedPeriods<c.periods&&Number(now)>=c.nextDueAt){const periodNo=c.generatedPeriods+1,o=this.createOrder({customerId:c.customerId,product:c.product,quantity:c.quantityPerPeriod,unitPrice:c.unitPrice,dueAt:c.nextDueAt,penaltyPerMissing:c.penaltyPerMissing,contractId:c.id,periodNo});generated.push(o);c.generatedPeriods++;c.nextDueAt=c.startAt+(c.generatedPeriods+1)*c.periodDays*86400000;}if(c.generatedPeriods>=c.periods)c.active=false;}return generated;}
 processOverdue(now=Date.now()){let penalties=0;const affected=[];for(const o of this.orders.filter(x=>x.status!=="fulfilled"&&Number(now)>o.dueAt)){const missing=Math.max(0,o.quantity-o.delivered),target=missing*o.penaltyPerMissing,delta=Math.max(0,target-Number(o.penaltyBooked||0));if(delta>0){o.penaltyBooked+=delta;penalties+=delta;}o.status="late";const customer=this.customers.find(x=>x.id===o.customerId);if(customer)customer.relationship=Math.max(0,customer.relationship-.5);affected.push(o);}if(affected.length)this.reputation=Math.max(0,this.reputation-Math.min(5,affected.length*.25));return {penalties,affected};}
 deliver(orderId,{quantity,quality=1,deliveredAt=Date.now(),transportCost=0}={}){const o=this.orders.find(x=>x.id===orderId);if(!o)throw new Error("Auftrag nicht gefunden");if(Number(quality)<o.qualityMin)throw new Error("Produktqualitaet reicht fuer Auftrag nicht");const q=Math.min(Number(quantity||0),o.quantity-o.delivered);o.delivered+=q;const late=deliveredAt>o.dueAt,missing=Math.max(0,o.quantity-o.delivered),penalty=Math.max(0,(late?missing*o.penaltyPerMissing:0)-Number(o.penaltyBooked||0)),revenue=q*o.unitPrice,net=revenue-penalty-Number(transportCost||0);o.penaltyBooked+=penalty;if(o.delivered>=o.quantity){o.status="fulfilled";if(o.contractId){const c=this.contracts.find(x=>x.id===o.contractId);if(c)c.completedPeriods=Math.max(c.completedPeriods,Number(o.periodNo||0));}}else if(late)o.status="late";const customer=this.customers.find(x=>x.id===o.customerId);if(customer)customer.relationship=Math.max(0,Math.min(100,customer.relationship+(late?-4:2)));this.reputation=Math.max(0,Math.min(100,this.reputation+(late?-1.5:1)));this.recordMarketActivity({region:o.region,sold:q,supplied:q});const invoice={id:this.seq++,orderId:o.id,quantity:q,revenue,penalty,transportCost:Number(transportCost||0),net,status:"paid",paidAt:deliveredAt};this.invoices.push(invoice);return invoice;}
 sellDirect({available,quantity,unitPrice,costPerUnit=0}={}){const q=Math.min(Number(available||0),Number(quantity||0)),revenue=q*Number(unitPrice||0),cost=q*Number(costPerUnit||0);return {quantity:q,revenue,cost,profit:revenue-cost};}
}
export function runMarketSalesTest(){const m=new CustomerMarketSystem(),c=m.addCustomer({typeId:"retailer",industry:"brewery",name:"Testmarkt",region:"north"}),quote=m.quoteMarket({region:"north",basePrice:1,baseDemand:1000,available:1000,price:1}),o=m.createOrder({customerId:c.id,product:"beer",quantity:1000,unitPrice:1.2,dueAt:1000,penaltyPerMissing:.2}),i=m.deliver(o.id,{quantity:1000,quality:1,deliveredAt:900,transportCost:80}),contract=m.createSupplyContract({customerId:c.id,product:"beer",quantityPerPeriod:100,unitPrice:1.1,periodDays:7,periods:2,startAt:0,penaltyPerMissing:.1}),generated=m.processContracts(15*86400000);if(i.net<=0||o.status!=="fulfilled"||m.reputation<=50||generated.length!==2||contract.generatedPeriods!==2||quote.expectedSales<=0||m.region("north").lastSales!==1000)throw new Error("Markt-/Verkaufstest fehlgeschlagen");console.log("✅ KUNDEN-/REGIONALMARKT-/VERKAUFS-/VERTRAGSTEST ERFOLGREICH",{customer:c,order:o,invoice:i,contract,generated,quote});return true;}
