// WorldProject - Markt, Zeitarbeit und Fahrzeugausbau
import { TempAgencySystem, applyFleetUpgrade, upgradedVehicleStats, fleetUpgradeCost } from "./TempAgencyAndFleetUpgradeSystem.js";
import { worldContentRegistry } from "./ContentRegistry.js";

export class MarketFleetDialog{
 constructor({parent=document.body}={}){this.parent=parent;this.overlay=null;this.agency=new TempAgencySystem();this.vehicles=[{id:1,label:"Sattelzug",payloadKg:24000,tankLitres:1000,fuelConsumptionPer100Km:30,reliability:.9,powerHp:450,upgrades:{}}];}
 el(t,x=null){const e=document.createElement(t);if(x!==null)e.textContent=x;return e;}
 button(x,fn){const b=this.el("button",x);Object.assign(b.style,{padding:"8px 10px",margin:"4px",border:0,borderRadius:"7px",fontWeight:"700",cursor:"pointer"});b.onclick=fn;return b;}
 money(v){return Number(v||0).toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
 getCompany(){return window.worldPlayerCompany||window.worldActiveServerCompany||{money:0};}
 async open(){if(this.overlay)return;const industry=window.worldActiveServerCompany?.industry||window.worldPlayerCompany?.industry||"brewery",ov=this.el("div");Object.assign(ov.style,{position:"fixed",inset:0,zIndex:23500,background:"rgba(0,0,0,.75)",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px"});const p=this.el("div");Object.assign(p.style,{width:"min(1150px,97vw)",maxHeight:"94vh",overflow:"auto",background:"#fff",color:"#111",borderRadius:"14px",padding:"20px",fontFamily:"Arial,sans-serif"});ov.append(p);this.parent.append(ov);this.overlay=ov;this.render(p,industry);}
 close(){this.overlay?.remove();this.overlay=null;}
 render(p,industry){p.innerHTML="";const company=this.getCompany(),h=this.el("div");Object.assign(h.style,{display:"flex",justifyContent:"space-between"});h.append(this.el("h2","🤝 Verträge, Zeitarbeit & Fuhrpark"),this.button("✕",()=>this.close()));p.append(h,this.el("div",`Betriebskonto: ${this.money(company.money)}`));

 const temp=this.el("section");Object.assign(temp.style,{margin:"18px 0",padding:"16px",border:"2px solid #f59e0b",borderRadius:"12px",background:"#2b1d08",color:"#fff7ed",boxShadow:"0 0 0 1px rgba(245,158,11,.18), 0 8px 24px rgba(0,0,0,.22)"});
 const tempHead=this.el("div");Object.assign(tempHead.style,{display:"flex",alignItems:"center",justifyContent:"space-between",gap:"12px",flexWrap:"wrap"});const tempTitle=this.el("h2","👷 Zeitarbeitsfirma");Object.assign(tempTitle.style,{margin:"0",fontSize:"24px",color:"#fde68a"});const badge=this.el("strong","SCHNELLHILFE BEI PERSONALAUSFALL");Object.assign(badge.style,{padding:"6px 10px",borderRadius:"999px",background:"#f59e0b",color:"#1f1300",fontSize:"12px",letterSpacing:".4px"});tempHead.append(tempTitle,badge);temp.append(tempHead);
 const help=this.el("div","Fehlt dir kurzfristig Personal für eine Schicht oder einen Arbeitsplatz? Hier kannst du sofort Ersatzkräfte für heute mieten.");Object.assign(help.style,{margin:"8px 0 14px",fontSize:"16px",lineHeight:"1.45",fontWeight:"700"});temp.append(help);
 const offers=this.el("div");Object.assign(offers.style,{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:"10px"});for(const o of this.agency.offers({industry})){const row=this.el("div");Object.assign(row.style,{padding:"12px",border:"1px solid #92400e",borderRadius:"9px",background:"#111827",color:"#f8fafc"});const label=this.el("strong",o.label);Object.assign(label.style,{display:"block",fontSize:"17px",marginBottom:"5px"});row.append(label,this.el("div",`Verfügbar: ${o.available} · Qualifikation: ${o.qualification.toFixed(2)}`),this.el("div",`Kosten: ${this.money(o.totalDailyCost)} pro Tag`));const hire=this.button("👷 Für heute mieten",()=>{try{this.agency.hire({roleId:o.id,industry,date:new Date(),shiftId:"early"});company.money=Number(company.money||0)-o.totalDailyCost;alert(`${o.label} für heute gemietet. Kosten wurden vom Betriebskonto abgezogen.`);this.render(p,industry);}catch(e){alert(e.message);}});Object.assign(hire.style,{margin:"10px 0 0",background:"#f59e0b",color:"#1f1300",padding:"10px 12px",width:"100%"});row.append(hire);offers.append(row);}temp.append(offers);const daily=this.el("div",`Heutige Zeitarbeitskosten: ${this.money(this.agency.dailyCost(new Date()))}`);Object.assign(daily.style,{marginTop:"12px",fontWeight:"800",color:"#fde68a"});temp.append(daily);p.append(temp);

 const info=this.el("section");Object.assign(info.style,{margin:"14px 0",padding:"12px",border:"1px solid #334155",borderRadius:"10px",background:"#111827",color:"#e2e8f0"});info.append(this.el("h3","🤝 Handel & Verträge"),this.el("div","Kunden und Aufträge werden hier nicht mehr manuell angelegt. Spielerhandel läuft über den Markt; direkte Lieferverträge zwischen Spielern werden über Kommunikation und Vertragsangebote abgewickelt."));p.append(info);

 const fleet=this.el("section");fleet.append(this.el("h3","🚚 Fuhrpark-Ausbau"));for(const v of this.vehicles){const s=upgradedVehicleStats(v),box=this.el("div");Object.assign(box.style,{border:"1px solid #ddd",padding:"10px",margin:"8px 0",borderRadius:"8px"});box.append(this.el("strong",v.label),this.el("div",`Verbrauch ${s.fuelConsumptionPer100Km.toFixed(1)} l/100 km · Tank ${s.tankLitres} l · Nutzlast ${Math.round(s.payloadKg)} kg · Motor ${Math.round(s.powerHp||v.powerHp||0)} PS`));for(const u of worldContentRegistry.list("fleetUpgrades")){const lvl=Number(v.upgrades?.[u.id]||0);if(lvl>=u.maxLevel)continue;box.append(this.button(`${u.label} ${lvl}→${lvl+1} (${this.money(fleetUpgradeCost(u.id,lvl))})`,()=>{try{const cost=fleetUpgradeCost(u.id,lvl);if(Number(company.money||0)<cost)throw new Error("Nicht genug Geld für dieses Fahrzeugupgrade");applyFleetUpgrade(v,u.id);company.money-=cost;this.render(p,industry);}catch(e){alert(e.message);}}));}fleet.append(box);}p.append(fleet);}
}
