// WorldProject - sichtbarer Markt, Zeitarbeit und Fahrzeugausbau
import { CustomerMarketSystem, customerTypesForIndustry, marketReferencePrice, expectedSales } from "./MarketSalesSystem.js";
import { TempAgencySystem, applyFleetUpgrade, upgradedVehicleStats, fleetUpgradeCost } from "./TempAgencyAndFleetUpgradeSystem.js";
import { CommercialFulfillmentSystem } from "./CommercialFulfillmentSystem.js";
import { worldContentRegistry } from "./ContentRegistry.js";

export class MarketFleetDialog{
 constructor({parent=document.body}={}){this.parent=parent;this.overlay=null;this.market=new CustomerMarketSystem();this.agency=new TempAgencySystem();this.vehicles=[{id:1,label:"Sattelzug",payloadKg:24000,tankLitres:1000,fuelConsumptionPer100Km:30,reliability:.9,powerHp:450,upgrades:{}}];this.lastDemand=null;}
 el(t,x=null){const e=document.createElement(t);if(x!==null)e.textContent=x;return e;}
 button(x,fn){const b=this.el("button",x);Object.assign(b.style,{padding:"8px 10px",margin:"4px",border:0,borderRadius:"7px",fontWeight:"700",cursor:"pointer"});b.onclick=fn;return b;}
 input(v=""){const i=this.el("input");i.value=v;Object.assign(i.style,{padding:"7px",margin:"4px",border:"1px solid #bbb",borderRadius:"6px"});return i;}
 select(options=[]){const s=this.el("select");Object.assign(s.style,{padding:"7px",margin:"4px"});for(const o of options){const x=this.el("option",o.label||o);x.value=o.id||o;s.append(x);}return s;}
 money(v){return Number(v||0).toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
 getCompany(){return window.worldPlayerCompany||window.worldActiveServerCompany||{money:0};}
 getWarehouse(){return window.worldAccounts?.operationalSupplyChainDialog?.warehouse||null;}
 getFulfillment(){const wh=this.getWarehouse();return wh?new CommercialFulfillmentSystem({market:this.market,warehouse:wh}):null;}
 async open(){if(this.overlay)return;const industry=window.worldActiveServerCompany?.industry||window.worldPlayerCompany?.industry||"brewery",ov=this.el("div");Object.assign(ov.style,{position:"fixed",inset:0,zIndex:23500,background:"rgba(0,0,0,.75)",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px"});const p=this.el("div");Object.assign(p.style,{width:"min(1150px,97vw)",maxHeight:"94vh",overflow:"auto",background:"#fff",color:"#111",borderRadius:"14px",padding:"20px",fontFamily:"Arial,sans-serif"});ov.append(p);this.parent.append(ov);this.overlay=ov;this.render(p,industry);}
 close(){this.overlay?.remove();this.overlay=null;}
 render(p,industry){p.innerHTML="";const company=this.getCompany(),warehouse=this.getWarehouse(),h=this.el("div");Object.assign(h.style,{display:"flex",justifyContent:"space-between"});h.append(this.el("h2","💶 Markt, Kunden, Zeitarbeit & Fuhrpark"),this.button("✕",()=>this.close()));p.append(h,this.el("div",`Betriebskonto: ${this.money(company.money)} · Reputation ${this.market.reputation.toFixed(1)}`));

 const market=this.el("section");market.append(this.el("h3","Kunden & Aufträge"));const types=customerTypesForIndustry(industry);const typeSel=this.select(types),customerName=this.input("Neuer Kunde");market.append(typeSel,customerName,this.button("Kunde anlegen",()=>{try{this.market.addCustomer({typeId:typeSel.value,name:customerName.value,industry});this.render(p,industry);}catch(e){alert(e.message);}}));
 for(const c of this.market.customers.filter(x=>x.active)){const row=this.el("div");Object.assign(row.style,{border:"1px solid #ddd",padding:"8px",margin:"5px 0",borderRadius:"7px"});row.append(this.el("strong",`${c.name} · Beziehung ${c.relationship.toFixed(0)}/100`));market.append(row);}
 const products=worldContentRegistry.list("products").filter(x=>(x.industries||[]).includes(industry)||!(x.industries||[]).length),productSel=this.select(products.length?products:[{id:"test_product",label:"Testprodukt"}]),customerSel=this.select(this.market.customers.map(c=>({id:String(c.id),label:c.name}))),qty=this.input("1000"),price=this.input("1.20"),days=this.input("3"),distance=this.input("50"),weight=this.input("5000");
 market.append(this.el("div","Kunde / Produkt / Menge / Preis pro Einheit / Lieferfrist Tage / Entfernung km / Gewicht kg"),customerSel,productSel,qty,price,days,distance,weight,this.button("Kundenauftrag erstellen",()=>{try{if(!customerSel.value)throw new Error("Erst einen Kunden anlegen");this.market.createOrder({customerId:Number(customerSel.value),product:productSel.value,quantity:Number(qty.value),unitPrice:Number(price.value),dueAt:Date.now()+Number(days.value)*86400000,penaltyPerMissing:.15});this.render(p,industry);}catch(e){alert(e.message);}}));
 const ref=marketReferencePrice({basePrice:Number(price.value||1),demand:1,supply:1,quality:1}),available=Number(warehouse?.stock?.finished?.[productSel.value]||0),sales=expectedSales({available,price:Number(price.value||1),referencePrice:ref,demand:Math.max(1,available),quality:1,reputation:this.market.reputation});this.lastDemand={referencePrice:ref,expectedSales:sales};market.append(this.el("div",`Marktindikator: Referenzpreis ${this.money(ref)} · erwartbarer Absatz bei aktuellem Bestand ca. ${sales}`));

 for(const o of this.market.orders){const row=this.el("div");Object.assign(row.style,{border:"1px solid #aaa",padding:"10px",margin:"7px 0",borderRadius:"8px"});const left=Math.max(0,o.quantity-o.delivered),stock=Number(warehouse?.stock?.finished?.[o.product]||0);row.append(this.el("strong",`Auftrag #${o.id}: ${o.product} · ${o.delivered}/${o.quantity} geliefert · Status ${o.status}`),this.el("div",`Preis ${this.money(o.unitPrice)} · Lager ${stock} · Rest ${left}`));if(left>0&&warehouse)row.append(this.button("Aus Lager reservieren & liefern",async()=>{try{const f=new CommercialFulfillmentSystem({market:this.market,warehouse}),r=f.reserve(o.id,Math.min(left,stock));f.prepareTransport(r.id,{distanceKm:Number(distance.value||0),cargo:{weightKg:Number(weight.value||0),pallets:0,volumeM3:0}});const done=await f.deliver(r.id,{company,quality:1});alert(`Lieferung abgeschlossen. Netto ${this.money(done.invoice.net)} gebucht.`);this.render(p,industry);}catch(e){alert(e.message);}}));row.append(this.button("Liefervertrag",()=>{try{this.market.createSupplyContract({customerId:o.customerId,product:o.product,quantityPerPeriod:o.quantity,unitPrice:o.unitPrice,periodDays:7,periods:4,penaltyPerMissing:o.penaltyPerMissing});alert("Liefervertrag angelegt.");this.render(p,industry);}catch(e){alert(e.message);}}));market.append(row);}
 if(this.market.contracts.length)market.append(this.el("div",`Aktive Lieferverträge: ${this.market.contracts.filter(x=>x.active).length}`));p.append(market);

 const temp=this.el("section");temp.append(this.el("h3","Zeitarbeitsfirma"),this.el("div","Ersatzkräfte können tageweise für Schichten und später konkrete Maschinen gemietet werden."));for(const o of this.agency.offers({industry})){const row=this.el("div",`${o.label} · verfügbar ${o.available} · Qualifikation ${o.qualification.toFixed(2)} · ${this.money(o.totalDailyCost)}/Tag`);row.append(this.button("Für heute mieten",()=>{try{this.agency.hire({roleId:o.id,industry,date:new Date(),shiftId:"early"});alert(`${o.label} für heute gemietet.`);this.render(p,industry);}catch(e){alert(e.message);}}));temp.append(row);}temp.append(this.el("div",`Heutige Zeitarbeitskosten: ${this.money(this.agency.dailyCost(new Date()))}`));p.append(temp);

 const fleet=this.el("section");fleet.append(this.el("h3","Fuhrpark-Ausbau"));for(const v of this.vehicles){const s=upgradedVehicleStats(v),box=this.el("div");Object.assign(box.style,{border:"1px solid #ddd",padding:"10px",margin:"8px 0",borderRadius:"8px"});box.append(this.el("strong",v.label),this.el("div",`Verbrauch ${s.fuelConsumptionPer100Km.toFixed(1)} l/100 km · Tank ${s.tankLitres} l · Nutzlast ${Math.round(s.payloadKg)} kg · Motor ${Math.round(s.powerHp||v.powerHp||0)} PS`));for(const u of worldContentRegistry.list("fleetUpgrades")){const lvl=Number(v.upgrades?.[u.id]||0);if(lvl>=u.maxLevel)continue;box.append(this.button(`${u.label} ${lvl}→${lvl+1} (${this.money(fleetUpgradeCost(u.id,lvl))})`,()=>{try{applyFleetUpgrade(v,u.id);this.render(p,industry);}catch(e){alert(e.message);}}));}fleet.append(box);}p.append(fleet);
 }
}
