// WorldProject - KI-Preisberater fuer den B2B-Spielermarkt.
// Der Vorschlag beruecksichtigt erkannte eigene Stueckkosten, Rezeptkosten und die aktuelle Marktlage.
import { worldContentRegistry } from './ContentRegistry.js';
import { orderBook } from './PlayerMarketExchange.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const roundPrice=v=>{const x=Math.max(.0001,n(v));if(x<.1)return Math.round(x*10000)/10000;if(x<1)return Math.round(x*1000)/1000;return Math.round(x*100)/100;};
const median=a=>{const x=a.map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return 0;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2;};
const ALIASES={beer_lager_033:['lager033_bottle','lager033'],lager033_bottle:['beer_lager_033','lager033'],beer_pils_033:['pils033_bottle','pils033'],pils033_bottle:['beer_pils_033','pils033'],beer_lager_050:['lager050_bottle'],lager050_bottle:['beer_lager_050'],beer_pils_050:['pils050_bottle'],pils050_bottle:['beer_pils_050']};
const idsFor=id=>[id,...(ALIASES[id]||[])];
function storedUnitCost(company,id){for(const candidate of idsFor(id)){const bags=[company?.unitCosts,company?.productUnitCosts,company?.averageCosts,company?.productionCosts,company?.costPerUnit];for(const bag of bags){const v=n(bag?.[candidate]);if(v>0)return v;}const accounting=company?.costAccounting?.productCosts?.[candidate]||company?.cost_accounting?.productCosts?.[candidate];const av=n(typeof accounting==='object'?(accounting.costPerUnit??accounting.unitCost??accounting.averageUnitCost):accounting);if(av>0)return av;const lots=company?.inventoryLots?.[candidate]||company?.finishedGoodsLots?.[candidate];if(Array.isArray(lots)){let qty=0,total=0;for(const lot of lots){const q=n(lot.quantity),u=n(lot.unitCost||lot.costPerUnit);if(q>0&&u>0){qty+=q;total+=q*u;}}if(qty>0)return total/qty;}}return 0;}
function supplierReferencePrice(id){const prices=[];for(const s of worldContentRegistry.list('suppliers')){for(const candidate of idsFor(id)){const p=n(s?.prices?.[candidate]);if(p>0)prices.push(p);}}return median(prices);}
function recipeUnitCost(id){const candidates=new Set(idsFor(id)),recipes=worldContentRegistry.list('recipes').filter(r=>candidates.has(r?.product)&&n(r.output)>0);if(!recipes.length)return 0;const estimates=[];for(const r of recipes){let total=n(r.variableCost);for(const [input,qty] of Object.entries(r.materials||{})){const p=supplierReferencePrice(input);if(p>0)total+=n(qty)*p;}if(total>0)estimates.push(total/n(r.output));}return estimates.length?Math.min(...estimates):0;}
export function estimatedProductUnitCost(company,productId){return roundPrice(storedUnitCost(company,productId)||recipeUnitCost(productId));}
export function marketPriceAdvice(world,company,productId,{targetMargin=.15,minMargin=.05}={}){const own=storedUnitCost(company,productId),recipe=recipeUnitCost(productId),cost=own||recipe;const book=orderBook(world,productId),competitors=book.asks.filter(o=>String(o.companyId)!==String(company?.serverCompanyId||company?.id)).map(o=>n(o.unitPrice)).filter(x=>x>0),trades=(book.lastTrades||[]).map(t=>n(t.unitPrice||t.price)).filter(x=>x>0),market=median(competitors)||median(trades);const floor=cost>0?cost*(1+Math.max(0,minMargin)):0,target=cost>0?cost*(1+Math.max(minMargin,targetMargin)):0;let suggested=0,reason='';if(cost>0&&market>0){suggested=Math.max(floor,Math.min(target,market*.99));if(market<floor){suggested=floor;reason='Der aktuelle Markt liegt sehr niedrig. Der Vorschlag schützt mindestens die erkannte Mindestmarge.';}else if(target<=market){suggested=target;reason='Der Markt lässt die gewünschte Zielmarge zu.';}else{suggested=Math.max(floor,market*.99);reason='Der Vorschlag liegt knapp unter dem typischen Marktpreis, aber nicht unter der Mindestmarge.';}}else if(cost>0){suggested=target;reason='Noch zu wenig Marktdaten. Vorschlag aus erkannten Stückkosten plus Zielmarge.';}else if(market>0){suggested=market*.99;reason='Keine verlässlichen Stückkosten erkannt. Vorschlag orientiert sich knapp unter dem aktuellen Markt.';}else{suggested=1;reason='Noch keine Kosten- oder Marktdaten vorhanden. Dieser Startwert ist nur eine Orientierung und sollte geprüft werden.';}suggested=roundPrice(suggested);return{productId,suggestedPrice:suggested,estimatedUnitCost:roundPrice(cost),marketReference:roundPrice(market),targetMargin,minMargin,estimatedMargin:cost>0?(suggested-cost)/suggested:null,source:own>0?'company-cost':recipe>0?'recipe-cost':market>0?'market-only':'fallback',reason};}
export function runMarketPriceAdvisorTest(){const w={exchange:{orders:[{id:'a',side:'sell',companyId:'other',productId:'test_item',remaining:10,unitPrice:1.2,status:'open'}],trades:[],feesCollected:0,requestIds:[]}},c={id:'mine',unitCosts:{test_item:1}};const a=marketPriceAdvice(w,c,'test_item');if(a.suggestedPrice<1.05||a.suggestedPrice>1.2)throw new Error('KI-Preisberater verletzt Kostenuntergrenze oder Marktbezug');const b=marketPriceAdvice({}, {unitCosts:{solo:2}},'solo');if(b.suggestedPrice<2.1)throw new Error('KI-Preisberater kalkuliert ohne Marktdaten keine Marge');const legacy={costAccounting:{productCosts:{lager033_bottle:{costPerUnit:.55}}}},cst=estimatedProductUnitCost(legacy,'beer_lager_033');if(Math.abs(cst-.55)>.0001)throw new Error('KI-Preisberater liest kanonische/Legacy-Kostenrechnung nicht');return{success:true};}
if(typeof window!=='undefined')window.worldMarketPriceAdvisor={advise:marketPriceAdvice,unitCost:estimatedProductUnitCost};
