// WorldProject - sichtbarer Mikro-Gründerpfad in der bestehenden Betriebsansicht.
import { EconomyDashboard } from './EconomyDashboard.js';
import { BusinessSetupSystem } from './BusinessSetupSystem.js';
const setup=new BusinessSetupSystem(),proto=EconomyDashboard.prototype;
const cash=(ui,v)=>window.worldCurrencyRuntime?.formatMoney?.(v)||window.formatMoney?.(v)||`${ui.money(v)} €`;
const dirty=reason=>window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason}}));
if(!proto.__microSetupIntegrated){proto.__microSetupIntegrated=true;const previous=proto.renderSetup;proto.renderSetup=function(panel){previous.call(this,panel);const state=setup.getState(this.company);if(!state.micro)return;
 const old=[...panel.querySelectorAll('div')].find(e=>e.firstElementChild?.textContent==='⚙️ Benötigte Maschinen & Ausstattung');if(old)old.style.display='none';
 const land=this.card('🗺️ Grundstück / Länderei');if(state.landReady&&state.landProperty){const p=state.landProperty,area=p.zone==='agricultural'?`${Number(p.hectares||0).toLocaleString('de-DE',{maximumFractionDigits:2})} ha`:`${Number(p.areaM2||0).toLocaleString('de-DE')} m²`;land.append(this.el('div',`✓ ${p.zoneLabel||p.zone} · ${area}`),this.small(`Kaufpreis ${cash(this,p.price||0)}`));}else{land.append(this.small('Zuerst ein geeignetes Grundstück kaufen.'));for(const p of (state.propertyMarket||[]).filter(x=>x.status==='for_sale').slice(0,6)){const area=p.zone==='agricultural'?`${Number(p.hectares||0).toLocaleString('de-DE',{maximumFractionDigits:2})} ha`:`${Number(p.areaM2||0).toLocaleString('de-DE')} m²`,row=this.el('div');row.append(this.el('strong',`${p.zoneLabel||p.zone} · ${area}`),this.small(cash(this,p.price)),this.button('Kaufen',()=>{const r=setup.buyStarterLand(this.company,p.id);if(!r.success)return alert(r.reason);dirty('starter-land');this.render(panel);}));land.append(row);}}panel.append(land);
 const gear=this.card('🧰 Kleine Gründer-Ausstattung');const current=setup.getState(this.company);if(!current.landReady)gear.append(this.small('Geräte können nach dem Grundstückskauf gekauft werden.'));else{const owned=new Set((this.company.buildingState?.equipment||[]).map(x=>typeof x==='string'?x:x.id));for(const item of current.equipmentCatalog){const row=this.el('div'),have=owned.has(item.id);row.append(this.el('strong',`${have?'✓ ':''}${item.name||item.id}`),this.small(`${cash(this,item.price)}${item.used?' · klein/gebraucht':''}`));if(!have)row.append(this.button('Kaufen',()=>{const r=setup.buyEquipment(this.company,item.id);if(!r.success)return alert(r.reason);dirty('starter-equipment');this.render(panel);}));gear.append(row);}gear.append(this.small(`Ausstattung ${setup.progress(this.company).percent} %`));}panel.append(gear);
 const open=this.card('🚪 Betrieb eröffnen'),final=setup.getState(this.company);if(final.landReady&&final.progress.complete)open.append(this.button('Kleinen Betrieb eröffnen',()=>{const r=setup.startOperations(this.company);if(!r.success)return alert(r.reason);dirty('micro-business-opened');this.render(panel);}));else open.append(this.small(final.landReady?'Noch nicht alle Startergeräte vorhanden.':'Zuerst Grundstück kaufen.'));panel.append(open);
};}
