// WorldProject – Moderationsfallakten, Sanktionen und Verlauf.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureModerationState(world={}){world.moderationState??={cases:[],sanctions:[],notes:[]};return world.moderationState;}
export function openModerationCase(world,{actor,playerId,category="other",summary="",severity="low",evidence=[],now=Date.now()}={}){adminControlSystem.requirePermission(actor,"moderation.write");const s=ensureModerationState(world),row={id:`mod-${now}-${Math.random().toString(36).slice(2,7)}`,playerId,category,summary,severity,evidence:[...evidence],status:"open",createdAt:now,createdBy:actor.id,history:[]};s.cases.push(row);adminControlSystem.log(actor,"moderation_case_opened",{caseId:row.id,playerId,category,severity});return row;}
export function addModerationNote(world,{actor,caseId,text,internal=true,now=Date.now()}={}){adminControlSystem.requirePermission(actor,"moderation.write");const s=ensureModerationState(world),c=s.cases.find(x=>x.id===caseId);if(!c)throw new Error("Moderationsfall fehlt");const note={id:`modnote-${now}`,caseId,text,internal,actorId:actor.id,at:now};s.notes.push(note);c.history.push({kind:"note",noteId:note.id,at:now});return note;}
export function applySanction(world,{actor,caseId,player,type="warning",durationHours=0,reason="",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"moderation.write");const s=ensureModerationState(world),c=s.cases.find(x=>x.id===caseId);if(!c)throw new Error("Moderationsfall fehlt");const until=durationHours>0?now+n(durationHours)*3600000:null,row={id:`sanction-${now}-${Math.random().toString(36).slice(2,6)}`,caseId,playerId:player.id||player.userId,type,reason,startsAt:now,until,status:"active",actorId:actor.id};s.sanctions.push(row);player.moderation??={};if(type==="mute"){player.moderation.muted=true;player.moderation.mutedUntil=until;}if(type==="suspend"){player.moderation.suspended=true;player.moderation.suspendedUntil=until;}if(type==="warning")player.moderation.warnings=n(player.moderation.warnings)+1;c.history.push({kind:"sanction",sanctionId:row.id,at:now});adminControlSystem.log(actor,"sanction_applied",{caseId,type,playerId:row.playerId,until,reason});return row;}
export function expireSanctions(world,players,{now=Date.now()}={}){const s=ensureModerationState(world),expired=[];for(const x of s.sanctions.filter(x=>x.status==="active"&&x.until&&x.until<=now)){x.status="expired";x.expiredAt=now;const p=players.find(p=>(p.id||p.userId)===x.playerId);if(p?.moderation){if(x.type==="mute"){p.moderation.muted=false;p.moderation.mutedUntil=null;}if(x.type==="suspend"){p.moderation.suspended=false;p.moderation.suspendedUntil=null;}}expired.push(x);}return expired;}
export function closeModerationCase(world,{actor,caseId,resolution="resolved",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"moderation.write");const c=ensureModerationState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Moderationsfall fehlt");c.status="closed";c.resolution=resolution;c.closedAt=now;c.closedBy=actor.id;adminControlSystem.log(actor,"moderation_case_closed",{caseId,resolution});return c;}
export function moderationKpis(world){const s=ensureModerationState(world);return{openCases:s.cases.filter(x=>x.status==="open").length,activeSanctions:s.sanctions.filter(x=>x.status==="active").length,warnings:s.sanctions.filter(x=>x.type==="warning").length,suspensions:s.sanctions.filter(x=>x.type==="suspend"&&x.status==="active").length};}
