// WorldProject – Moderationsfallakten, Sanktionen und Verlauf.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const trim=(a,max)=>{if(a.length>max)a.splice(0,a.length-max);return a;};
const text=(v,label)=>{const s=String(v||"").trim();if(!s)throw new Error(`${label} fehlt`);return s;};
const severities=new Set(["low","medium","high","critical"]),sanctionTypes=new Set(["warning","mute","suspend"]);
export function ensureModerationState(world={}){world.moderationState??={cases:[],sanctions:[],notes:[]};for(const k of ["cases","sanctions","notes"])if(!Array.isArray(world.moderationState[k]))world.moderationState[k]=[];return world.moderationState;}
export function openModerationCase(world,{actor,playerId,category="other",summary="",severity="low",evidence=[],now=Date.now()}={}){adminControlSystem.requirePermission(actor,"moderation.write");const s=ensureModerationState(world),row={id:`mod-${now}-${Math.random().toString(36).slice(2,7)}`,playerId:text(playerId,"Spieler"),category:String(category||"other"),summary:text(summary,"Zusammenfassung"),severity:severities.has(severity)?severity:"low",evidence:Array.isArray(evidence)?[...evidence]:[],status:"open",createdAt:now,createdBy:actor.id,history:[]};s.cases.push(row);trim(s.cases,10000);adminControlSystem.log(actor,"moderation_case_opened",{caseId:row.id,playerId:row.playerId,category:row.category,severity:row.severity});return row;}
export function addModerationNote(world,{actor,caseId,text:noteText,internal=true,now=Date.now()}={}){adminControlSystem.requirePermission(actor,"moderation.write");const s=ensureModerationState(world),c=s.cases.find(x=>x.id===caseId);if(!c)throw new Error("Moderationsfall fehlt");if(c.status==="closed")throw new Error("Moderationsfall ist bereits geschlossen");const note={id:`modnote-${now}-${Math.random().toString(36).slice(2,5)}`,caseId,text:text(noteText,"Notiz"),internal:!!internal,actorId:actor.id,at:now};s.notes.push(note);trim(s.notes,50000);c.history.push({kind:"note",noteId:note.id,at:now,actorId:actor.id});trim(c.history,1000);adminControlSystem.log(actor,"moderation_note_added",{caseId,noteId:note.id,internal:note.internal});return note;}
export function applySanction(world,{actor,caseId,player,type="warning",durationHours=0,reason="",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"moderation.write");const s=ensureModerationState(world),c=s.cases.find(x=>x.id===caseId);if(!c)throw new Error("Moderationsfall fehlt");if(c.status==="closed")throw new Error("Moderationsfall ist geschlossen");if(!player)throw new Error("Spieler fehlt");if(!sanctionTypes.has(type))throw new Error("Unbekannte Sanktion");const playerId=player.id||player.userId;if(String(playerId)!==String(c.playerId))throw new Error("Sanktion gehört nicht zum Spieler des Falls");const hours=Math.max(0,Math.min(24*365,n(durationHours))),until=type==="warning"?null:(hours>0?now+hours*3600000:null),cleanReason=text(reason,"Begründung"),row={id:`sanction-${now}-${Math.random().toString(36).slice(2,6)}`,caseId,playerId,type,reason:cleanReason,startsAt:now,until,status:"active",actorId:actor.id};s.sanctions.push(row);trim(s.sanctions,20000);player.moderation??={};if(type==="mute"){player.moderation.muted=true;player.moderation.mutedUntil=until;}if(type==="suspend"){player.moderation.suspended=true;player.moderation.suspendedUntil=until;}if(type==="warning")player.moderation.warnings=n(player.moderation.warnings)+1;c.history.push({kind:"sanction",sanctionId:row.id,at:now,actorId:actor.id});trim(c.history,1000);adminControlSystem.log(actor,"sanction_applied",{caseId,type,playerId:row.playerId,until,reason:cleanReason});return row;}
export function revokeSanction(world,{actor,sanctionId,player=null,reason="",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"moderation.write");const s=ensureModerationState(world),x=s.sanctions.find(v=>v.id===sanctionId);if(!x)throw new Error("Sanktion fehlt");if(x.status!=="active")return x;x.status="revoked";x.revokedAt=now;x.revokedBy=actor.id;x.revokeReason=text(reason,"Begründung");if(player?.moderation&&(player.id||player.userId)===x.playerId){if(x.type==="mute"){player.moderation.muted=false;player.moderation.mutedUntil=null;}if(x.type==="suspend"){player.moderation.suspended=false;player.moderation.suspendedUntil=null;}}adminControlSystem.log(actor,"sanction_revoked",{sanctionId,playerId:x.playerId,reason:x.revokeReason});return x;}
export function expireSanctions(world,players,{now=Date.now()}={}){const s=ensureModerationState(world),expired=[],list=Array.isArray(players)?players:[];for(const x of s.sanctions.filter(x=>x.status==="active"&&x.until&&x.until<=now)){x.status="expired";x.expiredAt=now;const p=list.find(p=>(p.id||p.userId)===x.playerId);if(p?.moderation){if(x.type==="mute"){p.moderation.muted=false;p.moderation.mutedUntil=null;}if(x.type==="suspend"){p.moderation.suspended=false;p.moderation.suspendedUntil=null;}}expired.push(x);}return expired;}
export function reopenModerationCase(world,{actor,caseId,reason="",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"moderation.write");const c=ensureModerationState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Moderationsfall fehlt");const before=c.status;c.status="open";c.closedAt=null;c.closedBy=null;c.resolution=null;c.history.push({kind:"reopened",reason:String(reason||"").trim(),actorId:actor.id,at:now});trim(c.history,1000);adminControlSystem.log(actor,"moderation_case_reopened",{caseId,before,reason:String(reason||"").trim()});return c;}
export function closeModerationCase(world,{actor,caseId,resolution="resolved",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"moderation.write");const c=ensureModerationState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Moderationsfall fehlt");c.status="closed";c.resolution=text(resolution,"Lösung");c.closedAt=now;c.closedBy=actor.id;c.history.push({kind:"closed",resolution:c.resolution,actorId:actor.id,at:now});trim(c.history,1000);adminControlSystem.log(actor,"moderation_case_closed",{caseId,resolution:c.resolution});return c;}
export function moderationKpis(world){const s=ensureModerationState(world);return{openCases:s.cases.filter(x=>x.status==="open").length,criticalOpen:s.cases.filter(x=>x.status==="open"&&x.severity==="critical").length,activeSanctions:s.sanctions.filter(x=>x.status==="active").length,warnings:s.sanctions.filter(x=>x.type==="warning").length,mutes:s.sanctions.filter(x=>x.type==="mute"&&x.status==="active").length,suspensions:s.sanctions.filter(x=>x.type==="suspend"&&x.status==="active").length};}
