// WorldProject – mehrere Standorte/Betriebe je Unternehmen, interne Waren- und Geldflüsse.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureMultiSite(c={}){c.sites??=[];c.internalTransfers??=[];return c;}
export function createSite(c,{id,name,type,branchKey,money=0,location=null}={}){ensureMultiSite(c);const site={id:id||`site-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,name:name||"Betrieb",type,branchKey,money:n(money),location,inventory:{},finishedGoods:{},productionJobs:[],employees:[],buildingState:{equipment:[]},salesLedger:[],costLedger:[],createdAt:Date.now()};c.sites.push(site);return site;}
export function siteById(c,id){return ensureMultiSite(c).sites.find(x=>x.id===id)||null;}
export function transferGoods(c,{fromSiteId,toSiteId,item,quantity,transferMinutes=60,now=Date.now()}={}){ensureMultiSite(c);const a=siteById(c,fromSiteId),b=siteById(c,toSiteId),q=Math.max(0,n(quantity));if(!a||!b)throw new Error("Standort fehlt");if(n(a.inventory?.[item])+1e-9<q)throw new Error("Nicht genug Bestand am Quellstandort");const row={id:`transfer-${now}-${Math.random().toString(36).slice(2,6)}`,fromSiteId,toSiteId,item,quantity:q,status:"in_transit",createdAt:now,arrivesAt:now+Math.max(1,n(transferMinutes))*60000};a.inventory[item]=n(a.inventory[item])-q;c.internalTransfers.push(row);return row;}
export function completeTransfer(c,id,{now=Date.now(),force=false}={}){const t=ensureMultiSite(c).internalTransfers.find(x=>x.id===id);if(!t)throw new Error("Transfer fehlt");if(t.status==="done")return{success:true,idempotent:true,transfer:t};if(!force&&now<t.arrivesAt)throw new Error("Transfer noch unterwegs");const b=siteById(c,t.toSiteId);b.inventory[t.item]=n(b.inventory[t.item])+n(t.quantity);t.status="done";t.completedAt=now;return{success:true,transfer:t};}
export function transferCash(c,{fromSiteId,toSiteId,amount}={}){const a=siteById(c,fromSiteId),b=siteById(c,toSiteId),q=Math.max(0,n(amount));if(!a||!b)throw new Error("Standort fehlt");if(n(a.money)<q)throw new Error("Nicht genug Standortliquidität");a.money-=q;b.money=n(b.money)+q;return{success:true,amount:q};}
export function siteKpis(c){return ensureMultiSite(c).sites.map(s=>({id:s.id,name:s.name,type:s.type,branchKey:s.branchKey,money:n(s.money),inventoryItems:Object.keys(s.inventory||{}).length,finishedItems:Object.keys(s.finishedGoods||{}).length,employees:(s.employees||[]).length,machines:(s.buildingState?.equipment||[]).length,runningJobs:(s.productionJobs||[]).filter(x=>x.status==="running").length,revenue:(s.salesLedger||[]).reduce((a,x)=>a+n(x.revenue),0),cost:(s.costLedger||[]).reduce((a,x)=>a+n(x.cost??x.amount),0)}));}
export function companyGroupKpis(c){const rows=siteKpis(c),revenue=rows.reduce((s,x)=>s+x.revenue,0),cost=rows.reduce((s,x)=>s+x.cost,0);return{sites:rows.length,cash:rows.reduce((s,x)=>s+x.money,0),employees:rows.reduce((s,x)=>s+x.employees,0),machines:rows.reduce((s,x)=>s+x.machines,0),revenue,cost,profit:revenue-cost,transfersOpen:(c.internalTransfers||[]).filter(x=>x.status==="in_transit").length};}
