// WorldProject – autonome NPC-Unternehmen für eine lebendige Wirtschaft auch bei wenigen Spielern.
import { IndustryProfiles } from './IndustryCatalog.js';
import { industryRecipes } from './UniversalIndustryCycle.js';
import { industryBusinessRules } from './IndustryBusinessRules.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function createNpcCompany({id,name,type,region='central',seed=1}={}){const profile=IndustryProfiles[type]||Object.values(IndustryProfiles)[0];return{id:id||`npc-${type}-${seed}`,name:name||`${profile.label} NPC ${seed}`,type,branchKey:profile.branchKey,region,money:75000+seed*2500,inventory:{},finishedGoods:{},reputation:45+(seed%30),marketShare:.01,employees:3+(seed%8),capacityIndex:.8+(seed%5)*.08,priceIndex:.9+(seed%7)*.04,status:'active',ageDays:0,history:[]};}
export function seedNpcEconomy({perIndustry=3,region='central'}={}){const out=[];let seed=1;for(const type of Object.keys(IndustryProfiles))for(let i=0;i<perIndustry;i++)out.push(createNpcCompany({type,region,seed:seed++}));return out;}
function npcMarginTarget(c){const rules=industryBusinessRules(c);return .12+rules.capitalBinding*.12+rules.qualityRisk*.04;}
export function advanceNpcDay(c,{demandIndex=1,costIndex=1,competition=1}={}){if(c.status!=='active')return c;const recipes=industryRecipes(c),rules=industryBusinessRules(c),baseCapacity=Math.max(1,recipes.reduce((s,r)=>s+n(r.output,1),0)||100),production=baseCapacity*c.capacityIndex*(.45+.55*clamp(n(demandIndex,1),.2,2));const revenue=production*(1.1+npcMarginTarget(c))*n(c.priceIndex,1)*n(demandIndex,1)*.35,cost=production*n(costIndex,1)*(.27+rules.capitalBinding*.08)+n(c.employees)*85,profit=revenue-cost;c.money=n(c.money)+profit;c.ageDays++;c.reputation=clamp(n(c.reputation,50)+(profit>0?.04:-.08),0,100);c.marketShare=clamp(n(c.marketShare,.01)*(1+(profit>0?.0015:-.003))*n(competition,1),.0005,.25);if(profit>0&&c.money>150000)c.capacityIndex=clamp(n(c.capacityIndex,1)+.002,.4,3);if(c.money<-25000)c.status='insolvent';c.history.push({day:c.ageDays,revenue,cost,profit,money:c.money,marketShare:c.marketShare});if(c.history.length>365)c.history.shift();return c;}
export function advanceNpcEconomy(companies,{days=1,world={}}={}){for(let d=0;d<days;d++)for(const c of companies)advanceNpcDay(c,{demandIndex:world.demandIndex||1,costIndex:world.costIndex||1,competition:world.competition||1});return companies;}
export function npcEconomyKpis(companies=[]){const active=companies.filter(x=>x.status==='active'),insolvent=companies.filter(x=>x.status==='insolvent');return{total:companies.length,active:active.length,insolvent:insolvent.length,totalCash:companies.reduce((s,x)=>s+n(x.money),0),averageReputation:active.length?active.reduce((s,x)=>s+n(x.reputation),0)/active.length:0,marketShare:active.reduce((s,x)=>s+n(x.marketShare),0)};}
if(typeof window!=='undefined')window.worldNpcEconomy={create:createNpcCompany,seed:seedNpcEconomy,advance:advanceNpcEconomy,kpis:npcEconomyKpis};
