// WorldProject - NPC-Liquiditaet fuer kleine/ruhige Spielermarkte
// NPCs sind im Profil als systemgesteuerte Unternehmen erkennbar.
export class NpcMarketLiquiditySystem{
 constructor({minDelayHours=1,maxDelayHours=48,lowActivityThreshold=12,maxPriceDeviation=.25,npcCompanies=[]}={}){Object.assign(this,{minDelayHours,maxDelayHours,lowActivityThreshold,maxPriceDeviation,npcCompanies});this.actions=[];}
 delayFor(listing){const span=Math.max(0,this.maxDelayHours-this.minDelayHours),seed=(Number(listing.id||1)*7919)%1000;return(this.minDelayHours+span*seed/999)*3600000;}
 active(context={}){return Number(context.realPlayerTradesLast24h||0)<this.lowActivityThreshold;}
 fairReference(listing,context={}){return Number(context.referencePrices?.[listing.item]||listing.unitPrice||listing.maxUnitPrice||0);}
 acceptable(listing,context={}){const ref=this.fairReference(listing,context);if(!ref)return false;const price=listing.type==="sell"?listing.unitPrice:listing.maxUnitPrice;return Math.abs(price-ref)/ref<=this.maxPriceDeviation;}
 process({market,now=Date.now(),realPlayerTradesLast24h=0,referencePrices={},npcTransfer=null}={}){const actions=[];if(!this.active({realPlayerTradesLast24h}))return{actions,reason:"player_market_liquid"};for(const l of market.active()){if(now-l.createdAt<this.delayFor(l)||!this.acceptable(l,{referencePrices}))continue;const npc=this.npcCompanies[(Number(l.id)-1)%Math.max(1,this.npcCompanies.length)]||{id:"npc_market",name:"Regionaler Handel",systemControlled:true};if(l.type==="sell"){const t=market.settle({listing:l,buyerCompanyId:npc.id,quantity:l.remaining,actorType:"npc",transfer:npcTransfer});actions.push({npc,action:"buy",trade:t});}else{const q=l.remaining,gross=q*l.maxUnitPrice,fee=gross*market.marketFeeRate,t={id:market.trades.length+1,listingId:l.id,sellerCompanyId:npc.id,buyerCompanyId:l.companyId,item:l.item,quality:l.minQuality,quantity:q,unitPrice:l.maxUnitPrice,gross,marketFee:fee,buyerCost:gross+fee,actorType:"npc",createdAt:now};if(typeof npcTransfer==="function")npcTransfer(t);l.remaining=0;l.status="filled";market.trades.push(t);actions.push({npc,action:"sell",trade:t});}}this.actions.push(...actions);return{actions};}
}
export const DefaultNpcMarketCompanies=[{id:"npc_westfalen_rohstoff",name:"Westfalen Rohstoffhandel",systemControlled:true},{id:"npc_nordstern_getraenke",name:"Nordstern Getränkehandel",systemControlled:true},{id:"npc_meyer_baustoffe",name:"Meyer Baustoffe",systemControlled:true}];
