// WorldProject – gemeinsame Actions für bestehende Betriebsfenster. Keine parallele UI.
import { buyIndustryEquipment,persistIndustryEquipment,equipmentSetupVM } from './IndustryEquipmentMarketplace.js';
import { productionReadinessVM,recommendedProductionFixes } from './ProductionReadinessAssistant.js';
import { startIndustryJob,finishIndustryJob } from './UniversalIndustryCycle.js';
const active=company=>company||window.worldPlayerCompany||window.worldEngine?.company;
async function persistState(c){const api=window.worldAccounts?.authApi;if(!api||!c?.serverCompanyId||typeof api.saveBusinessState!=='function')return{persisted:false};const state={};for(const[k,v]of Object.entries(c))if(!['buildingState','gigaTransportService','constructionManagers','market','transportSystem'].includes(k)&&typeof v!=='function')state[k]=v;await api.saveBusinessState(c.serverCompanyId,state);return{persisted:true};}
export async function purchaseEquipmentAction(equipmentId,{company=null,requestId=`equipment-${Date.now()}`}={}){const c=active(company);if(!c)throw new Error('Kein aktiver Betrieb');const result=buyIndustryEquipment(c,equipmentId,{requestId});await persistIndustryEquipment(c);window.dispatchEvent(new CustomEvent('worldproject:operations-changed',{detail:{company:c,kind:'equipment',result}}));return result;}
export function productionReadinessAction(recipeId,amount,{company=null}={}){const c=active(company);if(!c)throw new Error('Kein aktiver Betrieb');return productionReadinessVM(c,recipeId,amount);}
export function productionFixesAction(recipeId,amount,{company=null}={}){const c=active(company);if(!c)throw new Error('Kein aktiver Betrieb');return recommendedProductionFixes(c,recipeId,amount);}
export async function startProductionAction(recipeId,amount,{company=null,requestId=`production-${Date.now()}`}={}){const c=active(company);if(!c)throw new Error('Kein aktiver Betrieb');const readiness=productionReadinessVM(c,recipeId,amount);if(!readiness.ready){const e=new Error(`Produktion nicht startbereit: ${readiness.blockingReasons.join('; ')}`);e.readiness=readiness;throw e;}const result=startIndustryJob(c,recipeId,amount,{requestId});await persistState(c);window.dispatchEvent(new CustomEvent('worldproject:operations-changed',{detail:{company:c,kind:'production_started',result}}));return result;}
export async function finishProductionAction(jobId,{company=null,force=false}={}){const c=active(company);const result=finishIndustryJob(c,jobId,{force});await persistState(c);window.dispatchEvent(new CustomEvent('worldproject:operations-changed',{detail:{company:c,kind:'production_finished',result}}));return result;}
export function equipmentSetupAction({company=null}={}){const c=active(company);if(!c)throw new Error('Kein aktiver Betrieb');return equipmentSetupVM(c);}
if(typeof window!=='undefined')window.worldOperationsActions={purchaseEquipment:purchaseEquipmentAction,productionReadiness:productionReadinessAction,productionFixes:productionFixesAction,startProduction:startProductionAction,finishProduction:finishProductionAction,equipmentSetup:equipmentSetupAction};
