// WorldProject - generische Einkaufs-/Lager-/Produktionsoberflaeche
import { suppliersForCompany,recipesForCompany,quoteSupplier,SupplyOrderSystem,SupplierContractSystem,WarehouseSystem,ProductionPlanner } from "./OperationalSupplyChainSystem.js";

export class OperationalSupplyChainDialog{
 constructor({companyProvider=()=>window.worldPlayerCompany,parent=document.body}={}){this.companyProvider=companyProvider;this.parent=parent;this.overlay=null;this.contracts=new SupplierContractSystem();this.orders=new SupplyOrderSystem({contracts:this.contracts});this.warehouse=new WarehouseSystem();this.planner=new ProductionPlanner({warehouse:this.warehouse,machines:[]});}
 el(tag,text=""){const e=document.createElement(tag);if(text!==null)e.textContent=text;return e;}
 btn(text,fn){const b=this.el("button",text);Object.assign(b.style,{padding:"7px 10px",margin:"3px",cursor:"pointer",borderRadius:"7px",border:"1px solid #bbb"});b.onclick=fn;return b;}
 money(v){return Number(v||0).toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
 async open(){if(this.overlay)return;const o=this.el("div");Object.assign(o.style,{position:"fixed",inset:0,zIndex:22000,background:"rgba(0,0,0,.78)",display:"flex",alignItems:"center",justifyContent:"center",padding:"15px"});const p=this.el("div");Object.assign(p.style,{width:"min(1050px,97vw)",maxHeight:"94vh",overflow:"auto",background:"#fff",color:"#111",borderRadius:"14px",padding:"18px",fontFamily:"Arial,sans-serif"});o.append(p);this.parent.append(o);this.overlay=o;this.render(p);}
 close(){this.overlay?.remove();this.overlay=null;}
 render(panel){const company=this.companyProvider();panel.innerHTML="";const head=this.el("div");Object.assign(head.style,{display:"flex",justifyContent:"space-between",alignItems:"center"});head.append(this.el("h2","📦 Einkauf · Lager · Produktion"),this.btn("✕",()=>this.close()));panel.append(head);if(!company){panel.append(this.el("p","Kein aktiver Betrieb."));return;}
  const suppliers=suppliersForCompany(company),recipes=recipesForCompany(company);panel.append(this.el("p",`${company.name||"Betrieb"} · ${suppliers.length} passende Lieferanten · ${recipes.length} Produktionsrezepte`));
  const supBox=this.el("section");supBox.append(this.el("h3","Lieferantenvergleich"));if(!suppliers.length)supBox.append(this.el("p","Für diese Branche sind noch keine Lieferanten hinterlegt."));
  for(const s of suppliers){const card=this.el("div");Object.assign(card.style,{border:"1px solid #ddd",borderRadius:"9px",padding:"10px",margin:"7px 0"});card.append(this.el("strong",s.label||s.id),this.el("div",`Entfernung ${s.distanceKm||0} km · Qualität ${Math.round((s.quality||0)*100)} % · Zuverlässigkeit ${Math.round((s.reliability||0)*100)} % · Lieferzeit ca. ${s.deliveryHours||0} h`));const material=document.createElement("select");for(const m of s.materials||[]){const op=this.el("option",m);op.value=m;material.append(op);}const qty=document.createElement("input");qty.type="number";qty.min="1";qty.value="100";qty.style.width="100px";const quote=this.el("span","");const calc=()=>{try{const q=quoteSupplier(s,material.value,Number(qty.value));quote.textContent=` ${this.money(q.totalCost)} gesamt`; }catch(e){quote.textContent=` ${e.message}`;}};material.onchange=qty.oninput=calc;calc();card.append(material,qty,quote,this.btn("Beim Lieferanten bestellen",()=>{try{this.orders.createOrder({company,supplier:s,material:material.value,quantity:Number(qty.value)});this.render(panel);}catch(e){alert(e.message);}}),this.btn("Liefervertrag",()=>{const min=Number(prompt("Mindestabnahme pro Bestellung",qty.value)||0);if(min>0){this.contracts.create({supplierId:s.id,material:material.value,minQuantity:min,discount:.03});this.render(panel);}}));supBox.append(card);}panel.append(supBox);
  const orderBox=this.el("section");orderBox.append(this.el("h3","Bestellungen"));this.orders.advance(Date.now());if(!this.orders.orders.length)orderBox.append(this.el("p","Noch keine Bestellungen."));for(const o of this.orders.orders){const row=this.el("div",`#${o.id} · ${o.material} · ${o.quantity} · ${o.status} · ETA ${new Date(o.eta).toLocaleString("de-DE")}`);if(o.status==="arrived")row.append(this.btn("Wareneingang / Einlagern",()=>{try{this.warehouse.receive(o);this.render(panel);}catch(e){alert(e.message);}}));orderBox.append(row);}panel.append(orderBox);
  const wh=this.el("section");wh.append(this.el("h3","Lagerbereiche"));for(const[z,v]of Object.entries(this.warehouse.overview()))wh.append(this.el("div",`${z}: ${v.used} / ${v.capacity} belegt · ${v.free} frei`));panel.append(wh);
  const prod=this.el("section");prod.append(this.el("h3","Produktionsplanung"));if(!recipes.length)prod.append(this.el("p","Für diese Branche sind noch keine Rezepte hinterlegt."));for(const r of recipes){const plan=this.planner.plan(r,1),row=this.el("div");Object.assign(row.style,{border:"1px solid #eee",padding:"8px",margin:"6px 0"});row.append(this.el("strong",r.label||r.id),this.el("div",`Dauer ${plan.durationMinutes} min · Output ${plan.output} · Kosten ca. ${this.money(plan.estimatedCost)} · ${plan.ready?"bereit":"nicht bereit"}`));if(Object.keys(plan.missing||{}).length)row.append(this.el("div",`Fehlt: ${Object.entries(plan.missing).map(([k,v])=>`${k} ${v}`).join(", ")}`));row.append(this.btn("Produktion starten",()=>{try{this.planner.start(r,1);this.render(panel);}catch(e){alert(e.message);}}));prod.append(row);}panel.append(prod);
  const queue=this.el("section");queue.append(this.el("h3","Produktionswarteschlange"));for(const j of this.planner.queue){const row=this.el("div",`#${j.id} · ${j.recipe.label||j.recipe.id} · ${j.status}`);if(j.status==="running")row.append(this.btn("Pausieren",()=>{this.planner.pause(j.id);this.render(panel);}));if(j.status==="paused")row.append(this.btn("Fortsetzen",()=>{this.planner.resume(j.id);this.render(panel);}));if(!["finished","cancelled"].includes(j.status))row.append(this.btn("Abbrechen",()=>{this.planner.cancel(j.id);this.render(panel);}));queue.append(row);}panel.append(queue);
 }
}
