// WorldProject - stille Konsistenzpflege fuer lang laufende Spielstaende.
// Repariert nur eindeutig ableitbare Zustaende; keine erfundenen Mengen/Zeiten.
import { timerEnd } from './TimeValueUtils.js';

const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const active=s=>!['finished','completed','cancelled','admin_cancelled','delivered','received','stored','sold','closed','failed'].includes(String(s||'').toLowerCase());
function allMachines(company={}){const rows=[...(company.productionMachines||[]),...(company.buildingState?.equipment||[]),...(company.workforceState?.machines||[]),...(company.workforceOperationsState?.machines||[]),...(company.machines||[])],seen=new Set(),out=[];for(const m of rows){if(!m||m.status==='sold')continue;const key=String(m.instanceId??m.id??`${m.type||m.sourceType}:${m.label||m.name||''}`);if(seen.has(key))continue;seen.add(key);out.push(m);}return out;}

export function reconcileCustomerReservations(company={}){let repaired=0;for(const o of company.customerOrders||[]){const total=Math.max(0,n(o.quantity??o.amount)),delivered=Math.max(0,n(o.delivered??o.deliveredQuantity??o.fulfilledQuantity??o.deliveredAmount)),maxReserved=Math.max(0,total-delivered),reserved=Math.max(0,n(o.reserved));if(reserved>maxReserved){o.reserved=maxReserved;repaired++;}if(total>0&&delivered>=total&&active(o.status)){o.status='completed';o.completedAt??=Date.now();repaired++;}}return repaired;}
export function reconcileMachineStatuses(company={}){const activeMachineIds=new Set();for(const p of [...(company.productionQueue||[]),...(company.productionJobs||[])])if(active(p?.status)&&p?.machineId)activeMachineIds.add(p.machineId);let repaired=0;for(const m of company.productionMachines||[]){if(['producing','reserved'].includes(String(m?.status||''))&&!activeMachineIds.has(m.id)){m.status=n(m.condition,100)<=25?'workshop_required':'available';repaired++;}}return repaired;}
export function overdueOperations(company={},now=Date.now()){const rows=[],lists=[['production',company.productionQueue||[]],['production',company.productionJobs||[]],['delivery',company.supplierOrders||[]],['delivery',company.operationalSupplyState?.orders||[]],['market_delivery',company.marketDeliveries||[]],['construction',company.constructionSite?.jobs||[]],['warehouse',company.warehouseExpansion?.jobs||[]],['upgrade',company.machineUpgradeJobs||[]],['upgrade',company.upgradeJobs||[]]],seen=new Set();for(const [kind,list] of lists)for(const row of list){if(!row||!active(row.status))continue;const key=`${kind}:${row.id??row.instanceId??row}`;if(seen.has(key))continue;seen.add(key);const end=timerEnd(row)?.value||0;if(end&&end<now)rows.push({kind,row,end,overdueMs:now-end});}return rows;}
export function operationalHealth(company={},now=Date.now()){const overdue=overdueOperations(company,now),machines=allMachines(company),criticalMachines=machines.filter(m=>n(m.condition,100)<=25),maintenanceDue=machines.filter(m=>n(m.condition,100)>25&&n(m.condition,100)<=45),vehicles=company.vehicles||[],criticalVehicles=vehicles.filter(v=>n(v.condition,100)<=25||String(v.status||'')==='workshop_required'),maintenanceVehicles=vehicles.filter(v=>(n(v.condition,100)>25&&n(v.condition,100)<=45)||String(v.status||'')==='maintenance_due'),openCustomers=(company.customerOrders||[]).filter(o=>active(o.status)&&Math.max(0,n(o.quantity??o.amount)-n(o.delivered??o.deliveredQuantity??o.fulfilledQuantity??o.deliveredAmount)-n(o.reserved))>0),lateCustomers=openCustomers.filter(o=>{const due=Number(o.dueAt??o.deliveryDeadline??o.deadline),parsed=Number.isFinite(due)&&due>0?due:Date.parse(o.dueAt??o.deliveryDeadline??o.deadline);return Number.isFinite(parsed)&&parsed<now;});return{overdue,criticalMachines,maintenanceDue,criticalVehicles,maintenanceVehicles,openCustomers,lateCustomers,attentionCount:overdue.length+criticalMachines.length+criticalVehicles.length+lateCustomers.length};}
export function runOperationalConsistency(company={},now=Date.now()){const reservationRepairs=reconcileCustomerReservations(company),machineRepairs=reconcileMachineStatuses(company),health=operationalHealth(company,now);return{success:true,reservationRepairs,machineRepairs,overdueCount:health.overdue.length,overdue:health.overdue,health};}
export function runOperationalConsistencyGuardTest(){const now=Date.parse('2026-08-14T10:00:00Z'),c={customerOrders:[{id:1,status:'open',quantity:100,delivered:100,reserved:20},{id:4,status:'open',quantity:10,delivered:0,dueAt:now-1000}],productionMachines:[{id:'m1',status:'producing',condition:80}],buildingState:{equipment:[{instanceId:'m2',id:'brew',condition:20}]},productionQueue:[{id:2,status:'completed',machineId:'m1',completeAt:now-1000}],supplierOrders:[{id:3,status:'in_transit',arrivalAt:now-5000}],marketDeliveries:[{id:'md',status:'in_transit',arrivalTime:now-3000}]},r=runOperationalConsistency(c,now);if(c.customerOrders[0].reserved!==0||c.customerOrders[0].status!=='completed')throw new Error('Kundenauftrag wurde nicht konsistent repariert');if(c.productionMachines[0].status!=='available')throw new Error('Verwaister Maschinenstatus wurde nicht repariert');if(r.overdueCount!==2||!r.overdue.some(x=>x.kind==='market_delivery'))throw new Error('Ueberfaellige Lieferungen werden nicht vollständig erkannt');if(r.health.criticalMachines.length!==1||r.health.lateCustomers.length!==1)throw new Error('Betriebszustand erkennt kritische Wartung/Auftraege nicht');return true;}
if(typeof window!=='undefined')window.worldOperationalConsistency={run:runOperationalConsistency,health:operationalHealth,overdue:overdueOperations,test:runOperationalConsistencyGuardTest};
