// WorldProject – adaptive Spielerführung aus echtem Betriebszustand.
import { setupProgress } from './IndustryCatalog.js';
import { industryRecipes } from './UniversalIndustryCycle.js';
import { allProductionReadinessVM } from './ProductionReadinessAssistant.js';
import { commandCenterSnapshot,nextBestActions } from './BusinessCommandCenter.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function onboardingState(c){const setup=setupProgress(c),recipes=industryRecipes(c),readiness=allProductionReadinessVM(c,Object.fromEntries(recipes.map(r=>[r.id,r.output||1]))),hasEmployees=(c.employees||[]).length>0,hasInventory=Object.values(c.inventory||{}).some(x=>n(x)>0),hasProduction=(c.productionJobs||[]).length>0,hasSales=(c.salesLedger||[]).length>0,hasOrders=(c.customerOrders||[]).length>0;return{setup,recipes:recipes.length,readyRecipes:readiness.filter(x=>x.ready).length,blockedRecipes:readiness.filter(x=>!x.ready).length,hasEmployees,hasInventory,hasProduction,hasSales,hasOrders,money:n(c.money),phase:!setup.complete?'equipment':!hasEmployees?'workforce':!hasInventory?'procurement':!hasProduction?'production':!hasSales?'sales':'management'};}
export function onboardingRecommendations(c,{limit=6}={}){const s=onboardingState(c),out=[];const add=(priority,code,title,detail,action)=>out.push({priority,code,title,detail,action});if(!s.setup.complete)add(1,'buy_equipment','Pflichtausstattung vervollständigen',`${s.setup.missing.length} Pflichtmaschine(n) fehlen`,'equipment');if(!s.hasEmployees)add(2,'hire_staff','Personal einstellen','Der Betrieb hat noch kein Personal','workforce');if(s.blockedRecipes&&s.readyRecipes===0)add(3,'procure_inputs','Produktionsbedarf beschaffen',`${s.blockedRecipes} Rezept(e) sind blockiert`,'procurement');if(s.readyRecipes>0&&!s.hasProduction)add(4,'start_production','Ersten Produktions-/Leistungsauftrag starten',`${s.readyRecipes} Vorgang/Vorgänge sind startbereit`,'production');if(!s.hasOrders&&s.hasSales===false)add(5,'find_customer','Kundenauftrag oder Marktverkauf vorbereiten','Noch kein Kundenauftrag vorhanden','sales');if((c.finishedGoods&&Object.values(c.finishedGoods).some(x=>n(x)>0))&&!s.hasSales)add(5,'sell_goods','Fertigware verkaufen','Verkaufbare Ware liegt im Lager','sales');for(const a of nextBestActions(c,{limit:5}))add(10+a.priority,`management:${a.code}`,a.title,a.recommendation,a.code);return out.sort((a,b)=>a.priority-b.priority).slice(0,limit);}
export function contextualHelp(c,context){const map={equipment:'Maschinen und Pflichtausstattung bestimmen, welche Leistungen dein Betrieb ausführen kann.',workforce:'Qualifizierte Mitarbeiter beeinflussen Kapazität, Qualität und Schichtplanung.',procurement:'Rohstoffe müssen bestellt, geliefert und eingelagert sein, bevor sie verbraucht werden können.',production:'Die gewünschte Menge skaliert Materialbedarf, Maschinenzeit und Kosten.',sales:'Verkaufe nur tatsächlich vorhandene Ware und achte auf Marge und Liefertermine.',finance:'Liquidität, Forderungen, Kredite, Steuern und laufende Kosten gemeinsam betrachten.'};return{context,text:map[context]||'Prüfe die aktuellen Betriebswarnungen und priorisiere Engpässe.',snapshot:commandCenterSnapshot(c)};}
if(typeof window!=='undefined')window.worldOnboardingAdvisor={state:onboardingState,recommend:onboardingRecommendations,help:contextualHelp};
