// WorldProject - generische Einkaufs-/Lager-/Produktionsoberflaeche
import { suppliersForCompany,recipesForCompany,quoteSupplier,SupplyOrderSystem,SupplierContractSystem,WarehouseSystem,ProductionPlanner } from "./OperationalSupplyChainSystem.js";
import { worldContentRegistry } from "./ContentRegistry.js";

export class OperationalSupplyChainDialog{
 constructor({companyProvider=()=>window.worldPlayerCompany,parent=document.body}={}){this.companyProvider=companyProvider;this.parent=parent;this.overlay=null;this.contracts=new SupplierContractSystem();this.orders=new SupplyOrderSystem({contracts:this.contracts});this.warehouse=new WarehouseSystem();this.planner=new ProductionPlanner({warehouse:this.warehouse,machines:[]});this.timer=null;this.loadedCompanyId=null;}
 el(tag,text=""){const e=document.createElement(tag);if(text!==null)e.textContent=text;return e;}
 btn(text,fn){const b=this.el("button",text);Object.assign(b.style,{padding:"7px 10px",margin:"3px",cursor:"pointer",borderRadius:"7px",border:"1px solid #bbb"});b.onclick=fn;return b;}
 money(v){return Number(v||0).toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
 materialMeta(id){return worldContentRegistry.get("materials",id)||{id,label:id,unit:"Einheit"};}
 remaining(eta,now=Date.now()){const ms=Math.max(0,Number(eta)-now);if(ms<=0)return"angekommen";const min=Math.ceil(ms/60000),d=Math.floor(min/1440),h=Math.floor((min%1440)/60),m=min%60;return[d?`${d} T`:"",h?`${h} Std`:"",`${m} Min`].filter(Boolean).join(" ");}
 stateCompanyId(c){return c?.serverCompanyId||c?.id||null;}
 ensureMachines(company,recipes=[]){const state=company?.workforceOperationsState?.machines||company?.machines||[];if(state.length){this.planner.machines=state.map(m=>({...m,busy:!!m.busy}));return;}const types=[...new Set(recipes.map(r=>r.machineType).filter(Boolean))];this.planner.machines=types.map((type,i)=>({id:i+1,type,busy:false,label:type}));}
 loadState(company){const id=this.stateCompanyId(company);if(!id||this.loadedCompanyId===id)return;const s=company.operationalSupplyState||{};this.contracts.contracts=structuredClone(s.contracts||[]);this.contracts.seq=Number(s.contractSeq||Math.max(0,...this.contracts.contracts.map(x=>Number(x.id)||0))+1);this.orders.orders=structuredClone(s.orders||[]);this.orders.seq=Number(s.orderSeq||Math.max(0,...this.orders.orders.map(x=>Number(x.id)||0))+1);if(s.warehouseStock)this.warehouse.stock=structuredClone(s.warehouseStock);if(s.baseCapacities)this.warehouse.baseCapacities={...s.baseCapacities};this.planner.queue=structuredClone(s.productionQueue||[]);this.planner.seq=Number(s.productionSeq||Math.max(0,...this.planner.queue.map(x=>Number(x.id)||0))+1);this.loadedCompanyId=id;}
 saveState(company){if(!company)return;company.operationalSupplyState={contracts:structuredClone(this.contracts.contracts),contractSeq:this.contracts.seq,orders:structuredClone(this.orders.orders),orderSeq:this.orders.seq,warehouseStock:structuredClone(this.warehouse.stock),baseCapacities:{...this.warehouse.baseCapacities},productionQueue:this.planner.queue.map(j=>({...j,machine:j.machine?{id:j.machine.id,type:j.machine.type,label:j.machine.label,busy:j.machine.busy}:null})),productionSeq:this.planner.seq,updatedAt:Date.now()};window.dispatchEvent(new CustomEvent("world:game-state-dirty",{detail:{reason:"operational-supply-chain"}}));}
 async open(){if(this.overlay)return;const o=this.el("div");Object.assign(o.style,{position:"fixed",inset:0,zIndex:22000,background:"rgba(0,0,0,.78)",display:"flex",alignItems:"center",justifyContent:"center",padding:"15px"});const p=this.el("div");Object.assign(p.style,{width:"min(1180px,97vw)",maxHeight:"94vh",overflow:"auto",background:"#fff",color:"#111",borderRadius:"14px",padding:"18px",fontFamily:"Arial,sans-serif"});o.append(p);this.parent.append(o);this.overlay=o;this.render(p);this.timer=setInterval(()=>{if(this.overlay)this.render(p);},30000);}
 close(){const company=this.companyProvider();this.saveState(company);if(this.timer)clearInterval(this.timer);this.timer=null;this.overlay?.remove();this.overlay=null;}
 render(panel){const company=this.companyProvider();panel.innerHTML="";const head=this.el("div");Object.assign(head.style,{display:"flex",justifyContent:"space-between",alignItems:"center"});head.append(this.el("h2","📦 Einkauf · Lager · Produktion"),this.btn("✕",()=>this.close()));panel.append(head);if(!company){panel.append(this.el("p","Kein aktiver Betrieb."));return;}this.loadState(company);
  const suppliers=suppliersForCompany(company),recipes=recipesForCompany(company);this.ensureMachines(company,recipes);this.orders.advance(Date.now());this.planner.advance(Date.now());panel.append(this.el("p",`${company.name||"Betrieb"} · ${suppliers.length} passende Lieferanten · ${recipes.length} Produktionsrezepte`));

  const buyBox=this.el("section");buyBox.append(this.el("h3","Rohstoffe einkaufen"));const materialIds=[...new Set(suppliers.flatMap(s=>s.materials||[]))];if(!materialIds.length)buyBox.append(this.el("p","Für diese Branche sind noch keine Einkaufsartikel hinterlegt."));
  for(const materialId of materialIds){const meta=this.materialMeta(materialId),block=this.el("div");Object.assign(block.style,{border:"1px solid #d7d7d7",borderRadius:"10px",padding:"11px",margin:"10px 0"});const title=this.el("strong",`${meta.label} · Einheit: ${meta.unit}`),controls=this.el("div");Object.assign(controls.style,{display:"flex",gap:"8px",alignItems:"center",flexWrap:"wrap",margin:"8px 0"});const label=this.el("label",`Menge (${meta.unit})`),qty=this.el("input");qty.type="number";qty.min="0.001";qty.step="any";qty.value="50";Object.assign(qty.style,{width:"120px",padding:"6px"});controls.append(label,qty);block.append(title,controls);
   const offers=this.el("div");const renderOffers=()=>{offers.innerHTML="";for(const s of suppliers.filter(x=>(x.materials||[]).includes(materialId))){let q;try{q=quoteSupplier(s,materialId,Number(qty.value)||0);}catch(e){continue;}const row=this.el("div");Object.assign(row.style,{display:"grid",gridTemplateColumns:"minmax(180px,1.4fr) repeat(5,minmax(95px,1fr)) auto",gap:"8px",alignItems:"center",padding:"8px",borderTop:"1px solid #eee"});row.append(this.el("strong",s.label||s.id),this.el("span",`${this.money(q.unitPrice)}/${meta.unit}`),this.el("span",`Qualität ${Math.round(q.quality*100)} %`),this.el("span",`${q.distanceKm} km`),this.el("span",`ca. ${q.deliveryHours} Std.`),this.el("strong",this.money(q.totalCost)),this.btn("Kaufen",()=>{try{this.orders.createOrder({company,supplier:s,material:materialId,quantity:Number(qty.value)});this.saveState(company);this.render(panel);}catch(e){alert(e.message);}}));offers.append(row);}};qty.oninput=renderOffers;renderOffers();block.append(offers);buyBox.append(block);}panel.append(buyBox);

  const openOrders=this.orders.orders.filter(o=>!["stored","cancelled"].includes(o.status));const orderBox=this.el("section");orderBox.append(this.el("h3",`Laufende Lieferungen (${openOrders.length})`));if(!openOrders.length)orderBox.append(this.el("p","Keine offenen Lieferungen."));for(const o of openOrders){const meta=this.materialMeta(o.material),supplier=suppliers.find(s=>s.id===o.supplierId),row=this.el("div");Object.assign(row.style,{border:"1px solid #e1e1e1",borderRadius:"8px",padding:"9px",margin:"6px 0"});const status=o.status==="in_transit"?"Unterwegs":o.status==="arrived"?"Angekommen":o.status==="delayed"?"Verspätet":o.status;row.append(this.el("strong",`${supplier?.label||o.supplierId} · ${meta.label} · ${o.quantity} ${meta.unit}`),this.el("div",`${status} · Restzeit ${this.remaining(o.eta)} · Ankunft ${new Date(o.eta).toLocaleString("de-DE")}`));if(o.status==="arrived")row.append(this.btn("Wareneingang / Einlagern",()=>{try{this.warehouse.receive(o);this.saveState(company);this.render(panel);}catch(e){alert(e.message);}}));orderBox.append(row);}panel.append(orderBox);

  const wh=this.el("section");wh.append(this.el("h3","Lagerbereiche"));for(const[z,v]of Object.entries(this.warehouse.overview()))wh.append(this.el("div",`${z}: ${v.used} / ${v.capacity} belegt · ${v.free} frei`));panel.append(wh);
  const prod=this.el("section");prod.append(this.el("h3","Produktionsplanung"));if(!recipes.length)prod.append(this.el("p","Für diese Branche sind noch keine Rezepte hinterlegt."));for(const r of recipes){const outputUnit=r.outputUnit||r.unit||"Einheit",row=this.el("div");Object.assign(row.style,{border:"1px solid #eee",padding:"8px",margin:"6px 0"});const desired=this.el("input");desired.type="number";desired.min="0.001";desired.step="any";desired.value=String(Number(r.output||1));Object.assign(desired.style,{width:"120px",padding:"6px",margin:"6px"});const info=this.el("div");const refresh=()=>{let plan;try{plan=this.planner.planForOutput(r,Number(desired.value)||0);}catch(e){info.textContent=e.message;return;}info.textContent=`Für ${Number(desired.value)||0} ${outputUnit}: Dauer ${Math.round(plan.durationMinutes)} min · Kosten ca. ${this.money(plan.estimatedCost)} · ${plan.ready?"bereit":"nicht bereit"}`;let old=row.querySelector(".missing-materials");if(old)old.remove();if(Object.keys(plan.missing||{}).length){const miss=this.el("div",`Fehlt für ${Number(desired.value)||0} ${outputUnit}: ${Object.entries(plan.missing).map(([k,v])=>{const m=this.materialMeta(k);return`${m.label} ${Number(v.toFixed?.(3)??v)} ${m.unit}`;}).join(", ")}`);miss.className="missing-materials";row.append(miss);}};desired.oninput=refresh;row.append(this.el("strong",r.label||r.id),this.el("div",`Gewünschte Produktionsmenge (${outputUnit}):`),desired,info,this.btn("Produktion starten",()=>{try{this.planner.startForOutput(r,Number(desired.value));this.saveState(company);this.render(panel);}catch(e){alert(e.message);}}));refresh();prod.append(row);}panel.append(prod);
  const queue=this.el("section");const activeQueue=this.planner.queue.filter(j=>!["finished","cancelled"].includes(j.status));queue.append(this.el("h3",`Produktionswarteschlange (${activeQueue.length})`));for(const j of this.planner.queue){const output=j.plan?.output??0,unit=j.recipe?.outputUnit||j.recipe?.unit||"Einheit",remaining=j.status==="running"?this.remaining(j.finishAt):"-";const row=this.el("div",`#${j.id} · ${j.recipe.label||j.recipe.id} · ${Number(output.toFixed?.(2)??output)} ${unit} · ${j.status} · Restzeit ${remaining}`);if(j.status==="running")row.append(this.btn("Pausieren",()=>{this.planner.pause(j.id);this.saveState(company);this.render(panel);}));if(j.status==="paused")row.append(this.btn("Fortsetzen",()=>{this.planner.resume(j.id);this.saveState(company);this.render(panel);}));if(!["finished","cancelled"].includes(j.status))row.append(this.btn("Abbrechen",()=>{this.planner.cancel(j.id);this.saveState(company);this.render(panel);}));queue.append(row);}panel.append(queue);this.saveState(company);
 }
}
