// WorldProject - operativer Kern: Einkauf -> Transport -> Wareneingang -> Lager -> Produktion
// Balancingwerte sind bewusst vorlaeufig und werden im spaeteren Spieltest angepasst.

export const IndustryMaterials={
 brewery:["malt","hops","yeast","water","bottles","caps","labels"],
 carpentry:["softwood","hardwood","plywood","glue","screws","varnish","packaging"],
 bakery:["flour","yeast","sugar","salt","butter","packaging"],
 butchery:["meat","spices","salt","casings","packaging"]
};

export const WarehouseAreas={
 raw:{label:"Rohstofflager",baseCapacity:10000},
 packaging:{label:"Verpackungslager",baseCapacity:12000},
 finished:{label:"Fertigwarenlager",baseCapacity:15000},
 chilled:{label:"Kuehllager",baseCapacity:5000}
};

export class OperationsChainSystem{
 constructor({company,transportSystem=null}={}){this.company=company||{};this.transportSystem=transportSystem;this.ensureState();}
 ensureState(){const c=this.company;c.supplierOrders??=[];c.supplierContracts??=[];c.productionQueue??=[];c.warehouse??={raw:{},packaging:{},finished:{},chilled:{}};c.warehouseCapacity??={raw:10000,packaging:12000,finished:15000,chilled:5000};return c;}
 industryKey(){const s=`${this.company.industry||""} ${this.company.type||""}`.toLowerCase();if(s.includes("brau"))return"brewery";if(s.includes("schrein")||s.includes("holz"))return"carpentry";if(s.includes("baeck")||s.includes("bäck"))return"bakery";if(s.includes("metz")||s.includes("fleisch"))return"butchery";return s.trim()||"general";}
 allowedMaterials(){return IndustryMaterials[this.industryKey()]||[];}
 isMaterialAllowed(id){return this.allowedMaterials().includes(id);}
 supplierOffer({supplierId,name,material,basePrice,distanceKm=50,reliability=.9,quality=.8,stock=10000,marketFactor=1,quantity=1}={}){if(!this.isMaterialAllowed(material))throw new Error("Rohstoff gehoert nicht zu diesem Betrieb");const q=Math.max(1,Number(quantity||1)),discount=q>=5000?.08:q>=1000?.05:q>=250?.025:0,unit=Math.round(Number(basePrice||0)*Number(marketFactor||1)*(1-discount)*10000)/10000,transport=Math.round((35+Number(distanceKm||0)*.85)*100)/100;return{supplierId,name,material,quantity:q,unitPrice:unit,goodsCost:unit*q,transportCost:transport,totalCost:Math.round((unit*q+transport)*100)/100,distanceKm,reliability,quality,discount,deliveryHours:Math.max(1,Math.ceil(Number(distanceKm||0)/55+2)),stock};}
 createOrder(offer,{deliveryMode="supplier",vehicle=null}={}){if(offer.quantity>offer.stock)throw new Error("Lieferant hat nicht genug Bestand");if(Number(this.company.money||0)<offer.totalCost)throw new Error("Nicht genug Geld");if(deliveryMode==="own"&&!vehicle)throw new Error("Fuer Eigenabholung muss ein Fahrzeug gewaehlt werden");const order={id:`SO-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,createdAt:Date.now(),status:deliveryMode==="own"?"awaiting_pickup":"ordered",deliveryMode,vehicleId:vehicle?.id||null,...offer};this.company.money=Number(this.company.money||0)-offer.totalCost;this.company.supplierOrders.push(order);return order;}
 orderGroups(){const out={open:[],transit:[],delayed:[],completed:[]};for(const o of this.company.supplierOrders){if(["ordered","awaiting_pickup"].includes(o.status))out.open.push(o);else if(o.status==="in_transit")out.transit.push(o);else if(o.status==="delayed")out.delayed.push(o);else if(o.status==="completed")out.completed.push(o);}return out;}
 dispatch(order,{vehicle=null}={}){if(!order)throw new Error("Bestellung fehlt");if(order.deliveryMode==="own"){const capacity=Number(vehicle?.payloadKg||vehicle?.payload||0);const weight=Number(order.weightKg||order.quantity||0);if(!vehicle||capacity<weight)throw new Error("Fahrzeugkapazitaet reicht nicht");order.vehicleId=vehicle.id;}order.status="in_transit";order.dispatchedAt=Date.now();order.expectedAt=Date.now()+order.deliveryHours*3600000;return order;}
 receive(order,area="raw"){if(!order||!["in_transit","delayed","ordered"].includes(order.status))throw new Error("Bestellung ist nicht im Wareneingang");const used=Object.values(this.company.warehouse[area]||{}).reduce((s,v)=>s+Number(v||0),0),cap=Number(this.company.warehouseCapacity[area]||0);if(used+order.quantity>cap)throw new Error("Lagerkapazitaet reicht nicht");this.company.warehouse[area][order.material]=Number(this.company.warehouse[area][order.material]||0)+order.quantity;order.status="completed";order.receivedAt=Date.now();return order;}
 createSupplierContract({supplierId,material,minQuantity,discount=.03,durationDays=30}={}){const c={id:`SC-${Date.now()}`,supplierId,material,minQuantity:Number(minQuantity||0),discount:Number(discount||0),durationDays,startedAt:Date.now(),active:true};this.company.supplierContracts.push(c);return c;}
 planProduction({product,batches=1,recipe={},machineId,durationMinutes=60,outputPerBatch=1}={}){const b=Math.max(1,Math.floor(Number(batches||1))),missing={};for(const[m,q]of Object.entries(recipe)){const need=Number(q)*b,have=Number(this.company.warehouse.raw[m]||this.company.warehouse.packaging[m]||0);if(have<need)missing[m]=need-have;}return{product,batches:b,recipe,machineId,durationMinutes:Number(durationMinutes)*b,output:Number(outputPerBatch)*b,missing,ready:Object.keys(missing).length===0};}
 enqueueProduction(plan){if(!plan.ready)throw new Error(`Rohstoffe fehlen: ${Object.entries(plan.missing).map(([k,v])=>`${k} ${v}`).join(", ")}`);if(this.company.productionQueue.some(x=>x.machineId===plan.machineId&&["queued","running"].includes(x.status)))throw new Error("Maschine ist bereits belegt");for(const[m,q]of Object.entries(plan.recipe)){let need=Number(q)*plan.batches;for(const area of ["raw","packaging"]){const have=Number(this.company.warehouse[area][m]||0),take=Math.min(have,need);this.company.warehouse[area][m]=have-take;need-=take;if(need<=0)break;}}const job={id:`PJ-${Date.now()}`,status:"queued",createdAt:Date.now(),...plan};this.company.productionQueue.push(job);return job;}
 completeProduction(job,finishedArea="finished"){if(!job)throw new Error("Produktionsauftrag fehlt");const used=Object.values(this.company.warehouse[finishedArea]||{}).reduce((s,v)=>s+Number(v||0),0);if(used+job.output>Number(this.company.warehouseCapacity[finishedArea]||0))throw new Error("Fertigwarenlager voll");this.company.warehouse[finishedArea][job.product]=Number(this.company.warehouse[finishedArea][job.product]||0)+job.output;job.status="completed";job.completedAt=Date.now();return job;}
}

export function runOperationsChainTest(){const company={industry:"brewery",money:100000};const s=new OperationsChainSystem({company});const offer=s.supplierOffer({supplierId:"A",name:"Testlieferant",material:"malt",basePrice:1,distanceKm:50,quantity:1000,stock:5000});const o=s.createOrder(offer);s.dispatch(o);s.receive(o,"raw");company.warehouse.packaging.bottles=2000;const p=s.planProduction({product:"beer",batches:2,recipe:{malt:100,bottles:500},machineId:"brew-1",outputPerBatch:500});const j=s.enqueueProduction(p);s.completeProduction(j);if(company.warehouse.finished.beer!==1000||o.status!=="completed")throw new Error("Operationskette fehlerhaft");console.log("✅ EINKAUF-/LAGER-/PRODUKTIONSKETTE ERFOLGREICH",{offer,o,p,j});}
