// ORVUNO – Startseite als kompakte Unternehmenszentrale im Stil des freigegebenen Entwurfs.
const id='orvuno-command-center-style';
function css(){return `
#world-home-dashboard{max-width:none!important;width:auto!important;margin:0 238px 0 198px!important;padding:84px 18px 36px!important;box-sizing:border-box!important;background:linear-gradient(180deg,#08111f 0%,#07101d 100%)!important;min-height:100vh!important;font-family:Inter,Arial,sans-serif!important;color:#e7edf7!important}
#world-home-dashboard>section{background:linear-gradient(180deg,#0d1828,#0a1422)!important;border:1px solid #293950!important;border-radius:10px!important;padding:16px 17px!important;box-shadow:0 8px 24px #02071155!important;margin-bottom:13px!important}
#world-home-dashboard h1{font-size:22px!important;margin:0!important}#world-home-dashboard h2{font-size:18px!important;margin:0 0 10px!important}#world-home-dashboard h3{color:#eef4fc!important}
#world-home-dashboard button{background:linear-gradient(180deg,#142238,#0f1b2d)!important;border:1px solid #3a4e6b!important;border-radius:7px!important;color:#e8edf5!important;font-weight:750!important;box-shadow:inset 0 1px #ffffff0b!important}
#world-home-dashboard button:hover{border-color:#8b5cf6!important;background:#192942!important}
#world-home-dashboard [style*="background: rgb(17, 24, 39)"],#world-home-dashboard [style*="background:#111827"]{background:#0d1828!important;border-color:#293950!important;box-shadow:none!important}
#world-home-dashboard [style*="background: white"],#world-home-dashboard [style*="background:#fff"],#world-home-dashboard [style*="background: #fff"],#world-home-dashboard [style*="background-color: white"]{background:#0d1828!important;color:#e7edf7!important}
#orvuno-side-nav{position:fixed;z-index:43000;left:0;top:72px;bottom:0;width:186px;background:linear-gradient(180deg,#0a1423,#08111d);border-right:1px solid #293950;padding:20px 10px;box-sizing:border-box;color:#cbd5e1;font-family:Inter,Arial,sans-serif;box-shadow:8px 0 28px #02071155}
#orvuno-side-nav .brand{padding:0 10px 17px;margin-bottom:12px;border-bottom:1px solid #26354a;font-size:17px;font-weight:900;color:#f2f6fc;letter-spacing:.03em}#orvuno-side-nav .brand small{display:block;margin-top:3px;font-size:9px;color:#718099;letter-spacing:.14em;text-transform:uppercase}
#orvuno-side-nav .group{font-size:10px;font-weight:850;color:#75839a;margin:10px 8px 8px;text-transform:uppercase;letter-spacing:.08em}#orvuno-side-nav button{display:flex;width:100%;align-items:center;text-align:left;margin:3px 0;padding:10px 11px;min-height:40px;border:1px solid transparent;border-radius:7px;background:transparent;color:#d9e1ec;cursor:pointer;font-weight:700}#orvuno-side-nav button:hover,#orvuno-side-nav button.active{background:#111f33;border-color:#263b57;box-shadow:inset 3px 0 #8b5cf6;color:#fff}#orvuno-side-nav button:focus-visible{outline:2px solid #a78bfa;outline-offset:1px}
#orvuno-right-rail{position:fixed;z-index:42000;right:14px;top:88px;width:210px;bottom:18px;overflow:auto;font-family:Inter,Arial,sans-serif;color:#dbe5f2;scrollbar-width:thin}#orvuno-right-rail .rail-card{background:linear-gradient(180deg,#0d1828,#0a1422);border:1px solid #293950;border-radius:9px;padding:14px;margin-bottom:11px;box-shadow:0 8px 22px #02071144}#orvuno-right-rail h3{margin:0 0 12px;font-size:15px;color:#f0f5fb}.rail-row{display:flex;justify-content:space-between;gap:8px;padding:7px 0;color:#aeb9c9;font-size:12px;border-bottom:1px solid #1a293d}.rail-row:last-child{border:0}.good{color:#4ade80!important}.warn{color:#f5b942!important}.rail-note{font-size:12px;line-height:1.55;color:#93a3b8}
@media(max-width:1100px){#orvuno-side-nav,#orvuno-right-rail{display:none!important}#world-home-dashboard{width:calc(100% - 24px)!important;margin:0 auto!important;padding:82px 12px 30px!important}}
`;}
function company(){return window.worldPlayerCompany||window.worldActiveServerCompany||window.worldEconomyGameplay?.company||window.worldEngine?.company||{};}
function n(v){const x=Number(v);return Number.isFinite(x)?x:0;}
function setActive(button){const nav=button?.closest?.('#orvuno-side-nav');if(!nav)return;for(const x of nav.querySelectorAll('button'))x.classList.toggle('active',x===button);}
function navButton(label,action){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=async()=>{setActive(b);try{await action();}catch(error){console.error(`ORVUNO Navigation '${label}' konnte nicht geöffnet werden`,error);alert(error?.message||'Dieser Bereich konnte nicht geöffnet werden.');}};return b;}
function clickExisting(text){const all=[...document.querySelectorAll('button')].filter(x=>!x.closest('#orvuno-side-nav'));const b=all.find(x=>x.textContent?.trim().includes(text));if(!b)return false;b.click();return true;}
function openAccountDialog(key,fallbackText){const dialog=window.worldAccounts?.[key];if(dialog?.open)return dialog.open();if(fallbackText&&clickExisting(fallbackText))return;throw new Error('Dieser Bereich ist derzeit noch nicht verfügbar.');}
function renderSide(){let s=document.getElementById('orvuno-side-nav');if(!s){s=document.createElement('aside');s.id='orvuno-side-nav';s.setAttribute('aria-label','ORVUNO Hauptnavigation');document.body.append(s);}s.innerHTML='<div class="brand">◈ ORVUNO<small>Wirtschaftssimulation</small></div>';const g1=document.createElement('div');g1.className='group';g1.textContent='Verwaltung';s.append(g1,navButton('👥  Personal',()=>openAccountDialog('workforceOperationsDialog','Personal')),navButton('🌐  Markt & Fuhrpark',()=>openAccountDialog('marketFleetDialog','Markt & Fuhrpark')),navButton('📦  Einkauf · Lager · Produktion',()=>openAccountDialog('operationalSupplyChainDialog','Betrieb')),navButton('🏢  Betriebe',()=>openAccountDialog('businessPortfolioDialog','Betriebe')));const g2=document.createElement('div');g2.className='group';g2.textContent='Aktionen';g2.style.marginTop='18px';s.append(g2,navButton('📦  Kundenaufträge',()=>window.worldHomeOperationsDashboard?.openCustomers?.()||openAccountDialog('marketFleetDialog','Markt & Fuhrpark')),navButton('📑  Verträge',()=>{if(!clickExisting('Verträge'))return openAccountDialog('marketFleetDialog','Markt & Fuhrpark');}),navButton('📊  Statistiken',()=>{if(!clickExisting('Statistik'))throw new Error('Statistiken sind derzeit noch nicht verfügbar.');}));const g3=document.createElement('div');g3.className='group';g3.textContent='Informationen';g3.style.marginTop='18px';s.append(g3,navButton('✉️  Nachrichten',()=>{if(!clickExisting('Nachrichten'))throw new Error('Nachrichten sind derzeit noch nicht verfügbar.');}),navButton('📅  Ereignisse',()=>{if(window.worldActiveOperationsUI?.open)return window.worldActiveOperationsUI.open();if(!clickExisting('Vorgänge'))throw new Error('Die Vorgangsübersicht ist derzeit noch nicht verfügbar.');}),navButton('❔  Hilfe',()=>{if(!clickExisting('Hilfe'))throw new Error('Die Hilfe ist derzeit noch nicht verfügbar.');}));}
function renderRail(){const c=company();let r=document.getElementById('orvuno-right-rail');if(!r){r=document.createElement('aside');r.id='orvuno-right-rail';document.body.append(r);}const staff=(c.staff||c.employees||[]).length||n(c.employeeCount),vehicles=(c.vehicles||c.fleet||[]).length||n(c.vehicleCount),buildings=(c.buildings||[]).length||n(c.buildingCount),money=n(c.money||c.balance),orders=(c.customerOrders||[]).filter(o=>!['completed','cancelled','delivered','closed'].includes(String(o.status||'').toLowerCase())).length;r.innerHTML=`<div class="rail-card"><h3>🏭 Betriebsstatus</h3><div class="good" style="font-weight:850;margin-bottom:8px">● Betrieb aktiv</div><div class="rail-row"><span>👥 Mitarbeiter</span><b>${staff}</b></div><div class="rail-row"><span>🚚 Fahrzeuge</span><b>${vehicles}</b></div><div class="rail-row"><span>🏢 Gebäude</span><b>${buildings}</b></div><div class="rail-row"><span>📦 offene Aufträge</span><b>${orders}</b></div></div><div class="rail-card"><h3>💶 Finanzen</h3><div class="rail-row"><span>Kontostand</span><b class="${money>=0?'good':'warn'}">${money.toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})} €</b></div><div class="rail-row"><span>🪙 Coins</span><b class="warn">${n(c.coins)}</b></div></div><div class="rail-card"><h3>⚡ Schnellzugriff</h3><div class="rail-note">Laufende Lieferungen können direkt mit Coins oder – sofern verfügbar – per Werbe-Beschleunigung verkürzt werden.</div></div>`;}
function apply(){if(!document.getElementById(id)){const st=document.createElement('style');st.id=id;st.textContent=css();document.head.append(st);}if(!document.getElementById('world-home-dashboard'))return;renderSide();renderRail();}
export function installOrvunoCommandCenterLayout(){if(typeof document==='undefined')return false;let queued=false;const run=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply();});};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();for(const ev of ['worldproject:company-loaded','worldproject:company-activated','worldproject:company-switched','world:game-state-dirty','world:rewarded-ad-updated'])window.addEventListener(ev,run);new MutationObserver(()=>{if(document.getElementById('world-home-dashboard'))run();}).observe(document.documentElement,{childList:true,subtree:true});return true;}
if(typeof window!=='undefined')installOrvunoCommandCenterLayout();
