// ORVUNO – Startseite als kompakte Unternehmenszentrale im Stil des freigegebenen Entwurfs.
const id='orvuno-command-center-style';
function css(){return `
#world-home-dashboard{max-width:1500px!important;width:calc(100% - 220px)!important;margin-left:205px!important;margin-right:15px!important;padding:88px 250px 34px 16px!important;box-sizing:border-box!important;background:#07101d!important;min-height:100vh!important;font-family:Inter,Arial,sans-serif!important}
#world-home-dashboard>section{background:#0b1524!important;border:1px solid #263449!important;border-radius:10px!important;padding:15px!important;box-shadow:none!important;margin-bottom:12px!important}
#world-home-dashboard h1{font-size:22px!important;margin:0!important}#world-home-dashboard h2{font-size:18px!important}
#world-home-dashboard button{background:#101b2b!important;border:1px solid #33445d!important;border-radius:7px!important;color:#e8edf5!important;font-weight:700!important}
#world-home-dashboard button:hover{border-color:#7c3aed!important;background:#172238!important}
#world-home-dashboard [style*="background: rgb(17, 24, 39)"],#world-home-dashboard [style*="background:#111827"]{background:#0d1828!important;border-color:#263449!important;box-shadow:none!important}
#orvuno-side-nav{position:fixed;z-index:43000;left:0;top:72px;bottom:0;width:186px;background:#091321;border-right:1px solid #263449;padding:20px 10px;box-sizing:border-box;color:#cbd5e1;font-family:Inter,Arial,sans-serif}
#orvuno-side-nav .group{font-size:10px;font-weight:800;color:#75839a;margin:8px 8px 10px;text-transform:uppercase;letter-spacing:.05em}#orvuno-side-nav button{display:block;width:100%;text-align:left;margin:3px 0;padding:10px 11px;border:0;border-radius:7px;background:transparent;color:#d9e1ec;cursor:pointer}#orvuno-side-nav button:hover,#orvuno-side-nav button.active{background:#111e31;box-shadow:inset 2px 0 #8b5cf6}
#orvuno-right-rail{position:fixed;z-index:42000;right:14px;top:88px;width:220px;bottom:18px;overflow:auto;font-family:Inter,Arial,sans-serif;color:#dbe5f2}#orvuno-right-rail .rail-card{background:#0b1524;border:1px solid #263449;border-radius:9px;padding:14px;margin-bottom:11px}#orvuno-right-rail h3{margin:0 0 12px;font-size:16px}.rail-row{display:flex;justify-content:space-between;gap:8px;padding:7px 0;color:#aeb9c9;font-size:13px;border-bottom:1px solid #172338}.rail-row:last-child{border:0}.good{color:#4ade80!important}.warn{color:#f59e0b!important}
@media(max-width:1100px){#orvuno-side-nav,#orvuno-right-rail{display:none!important}#world-home-dashboard{width:calc(100% - 24px)!important;margin:0 auto!important;padding:82px 12px 30px!important}}
`;}
function company(){return window.worldPlayerCompany||window.worldActiveServerCompany||window.worldEngine?.company||{};}
function n(v){const x=Number(v);return Number.isFinite(x)?x:0;}
function navButton(label,action,active=false){const b=document.createElement('button');b.textContent=label;if(active)b.className='active';b.onclick=action;return b;}
function clickExisting(text){const all=[...document.querySelectorAll('button')];const b=all.find(x=>x.textContent?.trim().includes(text));b?.click();}
function renderSide(){let s=document.getElementById('orvuno-side-nav');if(!s){s=document.createElement('aside');s.id='orvuno-side-nav';document.body.append(s);}s.innerHTML='';const g1=document.createElement('div');g1.className='group';g1.textContent='Verwaltung';s.append(g1,navButton('👥 Personal',()=>clickExisting('Personal')),navButton('🌐 Markt & Fuhrpark',()=>clickExisting('Markt & Fuhrpark')),navButton('📦 Einkauf · Lager · Produktion',()=>window.worldOperationalSupplyChainDialog?.open?.(),true),navButton('🏢 Betriebe',()=>clickExisting('Betrieb')));const g2=document.createElement('div');g2.className='group';g2.textContent='Aktionen';g2.style.marginTop='20px';s.append(g2,navButton('📦 Kundenaufträge',()=>window.worldHomeOperationsDashboard?.openCustomers?.()),navButton('📑 Verträge',()=>clickExisting('Verträge')),navButton('📊 Statistiken',()=>clickExisting('Statistik')));const g3=document.createElement('div');g3.className='group';g3.textContent='Informationen';g3.style.marginTop='20px';s.append(g3,navButton('✉️ Nachrichten',()=>clickExisting('Nachrichten')),navButton('📅 Ereignisse',()=>window.worldActiveOperationsUI?.open?.()),navButton('❔ Hilfe',()=>clickExisting('Hilfe')));}
function renderRail(){const c=company();let r=document.getElementById('orvuno-right-rail');if(!r){r=document.createElement('aside');r.id='orvuno-right-rail';document.body.append(r);}const staff=(c.staff||c.employees||[]).length||n(c.employeeCount),vehicles=(c.vehicles||c.fleet||[]).length||n(c.vehicleCount),buildings=(c.buildings||[]).length||n(c.buildingCount),money=n(c.money||c.balance),orders=(c.customerOrders||[]).filter(o=>!['completed','cancelled','delivered','closed'].includes(String(o.status||'').toLowerCase())).length;r.innerHTML=`<div class="rail-card"><h3>Betriebsstatus</h3><div class="good" style="font-weight:800;margin-bottom:8px">● Aktiv</div><div class="rail-row"><span>👥 Mitarbeiter</span><b>${staff}</b></div><div class="rail-row"><span>🚚 Fahrzeuge</span><b>${vehicles}</b></div><div class="rail-row"><span>📦 offene Aufträge</span><b>${orders}</b></div></div><div class="rail-card"><h3>Finanzübersicht</h3><div class="rail-row"><span>Kontostand</span><b class="${money>=0?'good':'warn'}">${money.toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})} €</b></div><div class="rail-row"><span>Coins</span><b class="warn">${n(c.coins)}</b></div></div><div class="rail-card"><h3>Nächste Schritte</h3><div style="font-size:13px;line-height:1.55;color:#9eabc0">Laufende Vorgänge, Lieferungen und Produktionszeiten stehen zentral auf der Startseite. Dringende Aktionen bleiben dadurch sofort sichtbar.</div></div>`;}
function apply(){if(!document.getElementById(id)){const st=document.createElement('style');st.id=id;st.textContent=css();document.head.append(st);}if(!document.getElementById('world-home-dashboard'))return;renderSide();renderRail();}
export function installOrvunoCommandCenterLayout(){if(typeof document==='undefined')return false;const run=()=>requestAnimationFrame(apply);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();for(const ev of ['worldproject:company-loaded','worldproject:company-activated','worldproject:company-switched','world:game-state-dirty'])window.addEventListener(ev,run);new MutationObserver(()=>{if(document.getElementById('world-home-dashboard'))run();}).observe(document.documentElement,{childList:true,subtree:true});return true;}
if(typeof window!=='undefined')installOrvunoCommandCenterLayout();
