// WorldProject - persistenter Fuhrpark, Kauf/Verkauf, Kilometer, Zustand und Wartung
export const VehicleCatalog={van:{label:"Transporter",price:32000,payloadKg:1200,powerHp:170,tankLitres:70,fuelConsumptionPer100Km:9},truck75:{label:"7,5-t-LKW",price:65000,payloadKg:3500,powerHp:250,tankLitres:180,fuelConsumptionPer100Km:18},truck12:{label:"12-t-LKW",price:95000,payloadKg:6500,powerHp:320,tankLitres:300,fuelConsumptionPer100Km:23},truck18:{label:"18-t-LKW",price:135000,payloadKg:10000,powerHp:400,tankLitres:400,fuelConsumptionPer100Km:27},semi:{label:"Sattelzug",price:190000,payloadKg:24000,powerHp:500,tankLitres:800,fuelConsumptionPer100Km:30}};
export class PersistentFleetSystem{
 constructor({catalog=VehicleCatalog}={}){this.catalog=catalog;this.vehicles=[];this.seq=1;this.transactions=[];}
 buy(company,type,now=Date.now()){const c=this.catalog[type];if(!c)throw new Error("Unbekannter Fahrzeugtyp");if(Number(company.money||0)<c.price)throw new Error("Nicht genug Betriebsgeld");company.money-=c.price;const v={id:this.seq++,type,label:c.label,purchasePrice:c.price,purchasedAt:now,odometerKm:0,condition:1,fuelLitres:c.tankLitres,payloadKg:c.payloadKg,powerHp:c.powerHp,tankLitres:c.tankLitres,fuelConsumptionPer100Km:c.fuelConsumptionPer100Km,upgrades:{},lastServiceKm:0,nextServiceKm:30000,status:"available"};this.vehicles.push(v);this.transactions.push({type:"buy",vehicleId:v.id,value:c.price,at:now});return v;}
 sell(company,id,now=Date.now()){const v=this.vehicles.find(x=>x.id===id&&x.status!=="sold");if(!v)throw new Error("Fahrzeug nicht gefunden");const value=Math.max(500,Math.round(v.purchasePrice*Math.max(.18,v.condition)*Math.max(.35,1-v.odometerKm/800000)));v.status="sold";company.money=Number(company.money||0)+value;this.transactions.push({type:"sell",vehicleId:v.id,value,at:now});return{vehicle:v,value};}
 drive(id,km){const v=this.vehicles.find(x=>x.id===id&&x.status!=="sold");if(!v)throw new Error("Fahrzeug nicht gefunden");const d=Math.max(0,Number(km||0)),fuel=d/100*v.fuelConsumptionPer100Km;if(v.fuelLitres<fuel)throw new Error("Tankinhalt reicht fuer Strecke nicht");v.fuelLitres-=fuel;v.odometerKm+=d;v.condition=Math.max(.05,v.condition-d/900000);if(v.odometerKm>=v.nextServiceKm)v.serviceDue=true;return{km:d,fuelUsed:fuel,odometerKm:v.odometerKm,condition:v.condition,serviceDue:!!v.serviceDue};}
 service(company,id){const v=this.vehicles.find(x=>x.id===id&&x.status!=="sold");if(!v)throw new Error("Fahrzeug nicht gefunden");const cost=Math.round(500+(1-v.condition)*2500);if(Number(company.money||0)<cost)throw new Error("Nicht genug Betriebsgeld");company.money-=cost;v.condition=Math.min(1,v.condition+.18);v.lastServiceKm=v.odometerKm;v.nextServiceKm=v.odometerKm+30000;v.serviceDue=false;return{cost,vehicle:v};}
 exportState(){return{vehicles:this.vehicles,transactions:this.transactions,seq:this.seq};}importState(s={}){this.vehicles=Array.isArray(s.vehicles)?s.vehicles:[];this.transactions=Array.isArray(s.transactions)?s.transactions:[];this.seq=Number(s.seq||1);return this;}
}
export function runPersistentFleetTest(){const c={money:300000},f=new PersistentFleetSystem(),v=f.buy(c,"semi");v.fuelLitres=800;f.drive(v.id,1000);if(v.odometerKm!==1000||v.condition>=1)throw new Error("Fuhrpark-Fahrtest fehlgeschlagen");const state=f.exportState(),g=new PersistentFleetSystem().importState(state);if(g.vehicles[0].odometerKm!==1000)throw new Error("Fuhrpark-Persistenztest fehlgeschlagen");console.log("✅ FUHRPARK KAUF/VERKAUF/KM/ZUSTAND/WARTUNG/PERSISTENZ ERFOLGREICH");return true;}
