// WorldProject - persistenter Fuhrpark inkl. Streckenprofilen und Tankstopps
export const VehicleCatalog={van:{label:"Transporter",price:32000,payloadKg:1200,powerHp:170,tankLitres:70,fuelConsumptionPer100Km:9},truck75:{label:"7,5-t-LKW",price:65000,payloadKg:3500,powerHp:250,tankLitres:180,fuelConsumptionPer100Km:18},truck12:{label:"12-t-LKW",price:95000,payloadKg:6500,powerHp:320,tankLitres:300,fuelConsumptionPer100Km:23},truck18:{label:"18-t-LKW",price:135000,payloadKg:10000,powerHp:400,tankLitres:400,fuelConsumptionPer100Km:27},semi:{label:"Sattelzug",price:190000,payloadKg:24000,powerHp:500,tankLitres:800,fuelConsumptionPer100Km:30}};
export class PersistentFleetSystem{
 constructor({catalog=VehicleCatalog}={}){this.catalog=catalog;this.vehicles=[];this.seq=1;this.transactions=[];}
 buy(company,type,now=Date.now()){const c=this.catalog[type];if(!c)throw new Error("Unbekannter Fahrzeugtyp");if(Number(company.money||0)<c.price)throw new Error("Nicht genug Betriebsgeld");company.money-=c.price;const v={id:this.seq++,type,label:c.label,purchasePrice:c.price,purchasedAt:now,odometerKm:0,condition:1,fuelLitres:c.tankLitres,payloadKg:c.payloadKg,powerHp:c.powerHp,tankLitres:c.tankLitres,fuelConsumptionPer100Km:c.fuelConsumptionPer100Km,upgrades:{},lastServiceKm:0,nextServiceKm:30000,status:"available"};this.vehicles.push(v);this.transactions.push({type:"buy",vehicleId:v.id,value:c.price,at:now});return v;}
 sell(company,id,now=Date.now()){const v=this.vehicles.find(x=>x.id===id&&x.status!=="sold");if(!v)throw new Error("Fahrzeug nicht gefunden");const value=Math.max(500,Math.round(v.purchasePrice*Math.max(.18,v.condition)*Math.max(.35,1-v.odometerKm/800000)));v.status="sold";company.money=Number(company.money||0)+value;this.transactions.push({type:"sell",vehicleId:v.id,value,at:now});return{vehicle:v,value};}
 routeProfile({distanceKm=0,motorwayPct=0.6,countryPct=0.25,cityPct=0.15,hills=[]}={}){const total=Math.max(0,Number(distanceKm)),sum=Math.max(.01,motorwayPct+countryPct+cityPct),m=motorwayPct/sum,c=countryPct/sum,u=cityPct/sum;return{distanceKm:total,motorwayKm:total*m,countryKm:total*c,cityKm:total*u,hills:[...hills]};}
 estimateRoute(id,profile,grossWeightKg=40000){const v=this.vehicles.find(x=>x.id===id&&x.status!=="sold");if(!v)throw new Error("Fahrzeug nicht gefunden");const p=profile.distanceKm===undefined?this.routeProfile(profile):profile,baseHours=p.motorwayKm/80+p.countryKm/65+p.cityKm/35;let hillHours=0,hillFuel=0;for(const h of p.hills||[]){const gradient=Math.max(0,Number(h.gradientPct||0)),km=Math.max(0,Number(h.distanceKm||0)),hp=Math.max(1,v.powerHp),weightT=Math.max(1,grossWeightKg/1000),speed=Math.max(25,80/(1+gradient*Math.max(.25,55/(hp/weightT))*.055));hillHours+=km/speed;hillFuel+=km/100*v.fuelConsumptionPer100Km*(1+gradient*.035);}const normalKm=Math.max(0,p.distanceKm-(p.hills||[]).reduce((s,h)=>s+Number(h.distanceKm||0),0)),normalFuel=normalKm/100*v.fuelConsumptionPer100Km*(p.motorwayKm*.98+p.countryKm*1.02+p.cityKm*1.18)/Math.max(1,p.distanceKm),fuelNeeded=normalFuel+hillFuel;return{distanceKm:p.distanceKm,hours:baseHours+hillHours,fuelNeeded,profile:p};}
 planFuelStops(id,estimate,{reservePct=.1}={}){const v=this.vehicles.find(x=>x.id===id&&x.status!=="sold");const usableTank=v.tankLitres*(1-Math.max(0,Math.min(.4,reservePct))),available=Math.max(0,v.fuelLitres-v.tankLitres*reservePct),needed=estimate.fuelNeeded,stops=[];if(needed<=available)return{stops,fuelToBuy:0};let remaining=needed-available,kmPerTank=usableTank/Math.max(.01,v.fuelConsumptionPer100Km)*100,distance=kmPerTank;while(remaining>0){const litres=Math.min(usableTank,remaining);stops.push({atKm:Math.min(estimate.distanceKm,Math.round(distance)),litres});remaining-=litres;distance+=kmPerTank;}return{stops,fuelToBuy:stops.reduce((s,x)=>s+x.litres,0)};}
 executeRoute(company,id,profile,{grossWeightKg=40000,dieselPrice=1.65,stopMinutes=15}={}){const v=this.vehicles.find(x=>x.id===id&&x.status!=="sold");const e=this.estimateRoute(id,profile,grossWeightKg),fp=this.planFuelStops(id,e),fuelCost=fp.fuelToBuy*dieselPrice;if(Number(company.money||0)<fuelCost)throw new Error("Nicht genug Betriebsgeld fuer notwendige Tankstopps");company.money-=fuelCost;v.fuelLitres=Math.min(v.tankLitres,v.fuelLitres+fp.fuelToBuy);const r=this.drive(id,e.distanceKm,e.fuelNeeded);return{...e,...fp,fuelCost,totalHours:e.hours+fp.stops.length*stopMinutes/60,drive:r};}
 drive(id,km,forcedFuel=null){const v=this.vehicles.find(x=>x.id===id&&x.status!=="sold");if(!v)throw new Error("Fahrzeug nicht gefunden");const d=Math.max(0,Number(km)),fuel=forcedFuel===null?d/100*v.fuelConsumptionPer100Km:Number(forcedFuel);if(v.fuelLitres<fuel)throw new Error("Tankinhalt reicht fuer Strecke nicht");v.fuelLitres-=fuel;v.odometerKm+=d;v.condition=Math.max(.05,v.condition-d/900000);if(v.odometerKm>=v.nextServiceKm)v.serviceDue=true;return{km:d,fuelUsed:fuel,odometerKm:v.odometerKm,condition:v.condition,serviceDue:!!v.serviceDue};}
 service(company,id){const v=this.vehicles.find(x=>x.id===id&&x.status!=="sold");if(!v)throw new Error("Fahrzeug nicht gefunden");const cost=Math.round(500+(1-v.condition)*2500);if(Number(company.money||0)<cost)throw new Error("Nicht genug Betriebsgeld");company.money-=cost;v.condition=Math.min(1,v.condition+.18);v.lastServiceKm=v.odometerKm;v.nextServiceKm=v.odometerKm+30000;v.serviceDue=false;return{cost,vehicle:v};}exportState(){return{vehicles:this.vehicles,transactions:this.transactions,seq:this.seq};}importState(s={}){this.vehicles=Array.isArray(s.vehicles)?s.vehicles:[];this.transactions=Array.isArray(s.transactions)?s.transactions:[];this.seq=Number(s.seq||1);return this;}}
export function runPersistentFleetTest(){const c={money:500000},f=new PersistentFleetSystem(),v=f.buy(c,"semi");v.fuelLitres=80;const p=f.routeProfile({distanceKm:1000,hills:[{distanceKm:20,gradientPct:7}]}),r=f.executeRoute(c,v.id,p);if(v.odometerKm!==1000||v.condition>=1||!r.stops.length)throw new Error("Fuhrpark-/Tankstopp-Test fehlgeschlagen");const g=new PersistentFleetSystem().importState(f.exportState());if(g.vehicles[0].odometerKm!==1000)throw new Error("Fuhrpark-Persistenztest fehlgeschlagen");console.log("✅ FUHRPARK/STRECKENPROFILE/TANKSTOPPS ERFOLGREICH");return true;}
