// Persistenz V3: versionierte Migration, Recovery und Integritaetsbericht.
const VERSION=3,n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function snapshotV3(company={}){const data={money:n(company.money),inventory:company.inventory||{},finishedGoods:company.finishedGoods||{},productionJobs:company.productionJobs||[],deliveries:company.deliveries||company.activeDeliveries||[],employees:company.employees||[],vehicles:company.vehicles||company.fleet||[],buildingState:company.buildingState||{},finance:company.finance||null,accounting:company.accounting||null,marketState:company.marketState||null,growth:company.growth||null,customerOrders:company.customerOrders||[],meta:{companyId:company.id||null,type:company.type||null}};return{version:VERSION,savedAt:Date.now(),data:JSON.parse(JSON.stringify(data))};}
function migrateV1toV2(s){s.data.inventory??={};s.data.finishedGoods??={};s.data.productionJobs??=[];s.data.deliveries??=[];s.version=2;return s;}
function migrateV2toV3(s){s.data.employees??=[];s.data.vehicles??=[];s.data.customerOrders??=[];s.data.meta??={};s.version=3;return s;}
export function migrateSnapshotV3(snapshot){const s=JSON.parse(JSON.stringify(snapshot||{version:1,data:{}}));s.version=n(s.version,1);while(s.version<VERSION){if(s.version===1)migrateV1toV2(s);else if(s.version===2)migrateV2toV3(s);else throw new Error(`Keine Migration fuer Version ${s.version}`);}return s;}
export function persistenceRepair(data){const repairs=[];for(const bagName of ['inventory','finishedGoods']){const bag=data[bagName]??={};data[bagName]=bag;for(const[k,v]of Object.entries(bag)){const before=v,after=Math.max(0,n(v));if(before!==after){bag[k]=after;repairs.push({kind:'numeric_repair',bag:bagName,key:k,before,after});}}}const dedupe=(arr,keyFn,label)=>{const seen=new Set(),out=[];for(const x of arr||[]){const key=keyFn(x);if(key&&seen.has(key)){repairs.push({kind:'duplicate_removed',label,key});continue;}if(key)seen.add(key);out.push(x);}return out;};data.productionJobs=dedupe(data.productionJobs,x=>x.requestId||x.id,'productionJob');data.deliveries=dedupe(data.deliveries,x=>x.requestId||x.id,'delivery');data.customerOrders=dedupe(data.customerOrders,x=>x.id,'customerOrder');for(const j of data.productionJobs){if(j.status==='running'&&!Number.isFinite(Number(j.endsAt))){j.status='recovery_required';repairs.push({kind:'job_recovery',id:j.id});}}return repairs;}
export function hydrateV3(company,snapshot){const s=migrateSnapshotV3(snapshot),data=s.data,repairs=persistenceRepair(data);Object.assign(company,data);company.persistenceMeta={version:VERSION,loadedAt:Date.now(),repairs};return{company,repairs,version:VERSION};}
export function persistenceIntegrityV3(company){const issues=[];for(const[bagName,bag]of Object.entries({inventory:company.inventory||{},finishedGoods:company.finishedGoods||{}}))for(const[k,v]of Object.entries(bag))if(!Number.isFinite(Number(v))||Number(v)<0)issues.push({kind:'invalid_number',bag:bagName,key:k,value:v});const checkDup=(arr,keyFn,label)=>{const seen=new Set();for(const x of arr||[]){const key=keyFn(x);if(key&&seen.has(key))issues.push({kind:'duplicate',label,key});if(key)seen.add(key);}};checkDup(company.productionJobs,x=>x.requestId||x.id,'productionJob');checkDup(company.deliveries||company.activeDeliveries,x=>x.requestId||x.id,'delivery');return{success:!issues.length,version:VERSION,issues};}
export function recoverySnapshot(company){const snap=snapshotV3(company);snap.recovery=true;snap.reason='manual_recovery_point';return snap;}
