// WorldProject - Spielermarkt: Waren anbieten und Gesuche einstellen
export class PlayerMarketplaceSystem{
 constructor(){this.listings=[];this.seq=1;this.trades=[];}
 sell({sellerCompanyId,item,quality="standard",quantity,unitPrice,expiresAt=null}={}){const l={id:this.seq++,type:"sell",companyId:sellerCompanyId,item,quality,quantity:Number(quantity),remaining:Number(quantity),unitPrice:Number(unitPrice),expiresAt,status:"active",createdAt:Date.now()};if(l.quantity<=0||l.unitPrice<=0)throw new Error("Menge und Preis muessen positiv sein");this.listings.push(l);return l;}
 wanted({buyerCompanyId,item,minQuality="economy",quantity,maxUnitPrice,expiresAt=null}={}){const l={id:this.seq++,type:"wanted",companyId:buyerCompanyId,item,minQuality,quantity:Number(quantity),remaining:Number(quantity),maxUnitPrice:Number(maxUnitPrice),expiresAt,status:"active",createdAt:Date.now()};if(l.quantity<=0||l.maxUnitPrice<=0)throw new Error("Menge und Hoechstpreis muessen positiv sein");this.listings.push(l);return l;}
 active({type=null,item=null}={}){const now=Date.now();for(const l of this.listings)if(l.status==="active"&&l.expiresAt&&now>=l.expiresAt)l.status="expired";return this.listings.filter(l=>l.status==="active"&&(!type||l.type===type)&&(!item||l.item===item));}
 buy({listingId,buyerCompanyId,quantity,transfer=null}={}){const l=this.listings.find(x=>x.id===listingId&&x.type==="sell"&&x.status==="active");if(!l)throw new Error("Angebot nicht verfuegbar");if(l.companyId===buyerCompanyId)throw new Error("Eigene Ware kann nicht gekauft werden");const q=Math.min(Number(quantity),l.remaining);if(q<=0)throw new Error("Ungueltige Menge");const trade={id:this.trades.length+1,listingId:l.id,sellerCompanyId:l.companyId,buyerCompanyId,item:l.item,quality:l.quality,quantity:q,unitPrice:l.unitPrice,total:q*l.unitPrice,createdAt:Date.now()};if(typeof transfer==="function")transfer(trade);l.remaining-=q;if(l.remaining<=0)l.status="filled";this.trades.push(trade);return trade;}
 cancel(id,companyId){const l=this.listings.find(x=>x.id===id&&x.companyId===companyId&&x.status==="active");if(!l)return false;l.status="cancelled";return true;}
}
export function runPlayerMarketplaceTest(){const m=new PlayerMarketplaceSystem(),l=m.sell({sellerCompanyId:1,item:"malt",quality:"premium",quantity:100,unitPrice:1.5}),t=m.buy({listingId:l.id,buyerCompanyId:2,quantity:40});m.wanted({buyerCompanyId:3,item:"malt",minQuality:"standard",quantity:500,maxUnitPrice:1.3});if(t.quantity!==40||l.remaining!==60||m.active({type:"wanted"}).length!==1)throw new Error("Spielermarkt-Test fehlgeschlagen");console.log("🛒 SPIELERMARKT ANGEBOTE/GESUCHE ERFOLGREICH");return true;}
