// WorldProject – moderner B2B-Warenmarktplatz nach dem Prinzip klassischer Wirtschaftsspiele.
// Nutzt ausschließlich die bestehende PlayerMarketExchange-Logik; kein paralleles Marktsystem.
import { ensureExchange, placeSellOrder, cancelMarketOrder, orderBook, marketStock } from './PlayerMarketExchange.js';
import { worldContentRegistry } from './ContentRegistry.js';
import { formatMoney } from './CurrencyPresentationBridge.js';

const n=v=>Number(v||0);
const company=()=>window.worldPlayerCompany||window.worldActiveServerCompany||null;
const world=()=>window.worldProjectWorld||window.worldWorld||window.worldGameState||window;
const meta=id=>worldContentRegistry.get('products',id)||worldContentRegistry.get('materials',id)||null;
const label=id=>meta(id)?.label||String(id).replace(/_/g,' ');
const sellerName=o=>o.companyRef?.name||o.companyRef?.companyName||o.companyRef?.company_name||`Firma ${o.companyId??'–'}`;
const productIds=()=>[...new Set([...worldContentRegistry.list('products'),...worldContentRegistry.list('materials')].filter(x=>x.sellable!==false).map(x=>x.id))].sort((a,b)=>label(a).localeCompare(label(b),'de'));
const BRANCH_LABELS={brewery:'Brauerei & Getränke',beverage:'Getränkeherstellung',bakery:'Bäckerei',butcher:'Metzgerei',carpentry:'Schreinerei',farm:'Landwirtschaft',livestock:'Tierhaltung',orchard:'Obstbau',mechanical:'Maschinenbau',metal:'Metallverarbeitung',plastic:'Kunststoff',retail:'Einzelhandel',wholesale:'Großhandel',online_retail:'Onlinehandel',food:'Lebensmittel'};
const branchKeysFor=id=>{const row=meta(id),industries=Array.isArray(row?.industries)?row.industries:[];return industries.length?industries:['other'];};
const branchLabel=id=>BRANCH_LABELS[id]||worldContentRegistry.get('industries',id)?.label||String(id).replace(/_/g,' ');

export function marketCategories(ids=productIds()){
 const groups=new Map();
 for(const id of ids)for(const key of branchKeysFor(id)){if(!groups.has(key))groups.set(key,[]);if(!groups.get(key).includes(id))groups.get(key).push(id);}
 return [...groups.entries()].map(([id,items])=>({id,label:branchLabel(id),items:items.sort((a,b)=>label(a).localeCompare(label(b),'de'))})).sort((a,b)=>a.label.localeCompare(b.label,'de'));
}

export class PlayerMarketDialog{
 constructor({parent=document.body}={}){this.parent=parent;this.overlay=null;this.selected=null;this.sort='price';this.category=null;}
 el(t,x=null){const e=document.createElement(t);if(x!==null)e.textContent=x;return e;}
 button(x,fn){const b=this.el('button',x);Object.assign(b.style,{padding:'8px 11px',border:'1px solid #4b5563',borderRadius:'8px',background:'#374151',color:'#fff',fontWeight:'700',cursor:'pointer'});b.onclick=fn;return b;}
 input(v='',type='text'){const i=this.el('input');i.type=type;i.value=v;Object.assign(i.style,{padding:'8px',border:'1px solid #6b7280',borderRadius:'7px',background:'#111827',color:'#fff',width:'110px'});return i;}
 open(){if(this.overlay)return;const ov=this.el('div');Object.assign(ov.style,{position:'fixed',inset:0,zIndex:24500,background:'rgba(0,0,0,.76)',display:'flex',justifyContent:'center',alignItems:'center',padding:'18px'});const p=this.el('div');p.dataset.worldPlayerMarketDialog='1';Object.assign(p.style,{width:'min(1220px,98vw)',maxHeight:'94vh',overflow:'auto',background:'#1f2937',color:'#f9fafb',borderRadius:'14px',fontFamily:'Arial,sans-serif',boxShadow:'0 18px 55px rgba(0,0,0,.45)'});ov.append(p);this.parent.append(ov);this.overlay=ov;this.render(p);}
 close(){this.overlay?.remove();this.overlay=null;}
 render(p){p.innerHTML='';const c=company(),w=world();ensureExchange(w);const head=this.el('div');Object.assign(head.style,{position:'sticky',top:'0',zIndex:'4',display:'flex',justifyContent:'space-between',alignItems:'center',padding:'16px 20px',background:'#111827',borderBottom:'1px solid #4b5563'});head.append(this.el('h2','🌐 Marktplatz'),this.button('✕ Schließen',()=>this.close()));p.append(head);const body=this.el('div');body.style.padding='18px 20px';p.append(body);const nav=this.el('div');Object.assign(nav.style,{display:'flex',gap:'8px',flexWrap:'wrap',marginBottom:'16px'});nav.append(this.button('🛒 Waren kaufen',()=>{this.selected=null;this.render(p);}),this.button('💶 Waren verkaufen',()=>{this.selected='__sell';this.render(p);}),this.button('📋 Meine Angebote',()=>{this.selected='__offers';this.render(p);}));body.append(nav);
 if(this.selected==='__sell')return this.renderSell(body,p,c,w);
 if(this.selected==='__offers')return this.renderOffers(body,p,c,w);
 if(this.selected)return this.renderBook(body,p,c,w,this.selected);
 this.renderProducts(body,p,w);
 }
 renderProducts(body,p,w){const ids=productIds(),ex=ensureExchange(w),open=ex.orders.filter(o=>['open','partial'].includes(o.status)&&o.side==='sell'),cats=marketCategories(ids);body.append(this.el('h3','Warenmarkt nach Gewerbe'));body.append(this.el('div','Wähle zuerst eine Branche und danach die gewünschte Ware.'));const tabs=this.el('div');Object.assign(tabs.style,{display:'flex',gap:'7px',flexWrap:'wrap',margin:'14px 0'});tabs.append(this.button('Alle Branchen',()=>{this.category=null;this.render(p);}));for(const cat of cats)tabs.append(this.button(cat.label,()=>{this.category=cat.id;this.render(p);}));body.append(tabs);const shown=this.category?cats.filter(c=>c.id===this.category):cats;for(const cat of shown){const sec=this.el('section');const h=this.el('h3',cat.label);Object.assign(h.style,{margin:'18px 0 8px'});sec.append(h);const grid=this.el('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(210px,1fr))',gap:'8px'});for(const id of cat.items){const count=open.filter(o=>o.productId===id).length,b=this.button(`${label(id)}${count?` · ${count} Angebot${count===1?'':'e'}`:''}`,()=>{this.selected=id;this.render(p);});Object.assign(b.style,{textAlign:'left',background:'#293548'});grid.append(b);}sec.append(grid);body.append(sec);}}
 renderBook(body,p,c,w,id){const book=orderBook(w,id);body.append(this.button('← Produktübersicht',()=>{this.selected=null;this.render(p);}),this.el('h3',`Angebote: ${label(id)}`));const sort=this.el('div','Sortieren: ');for(const [key,name] of [['price','Preis'],['quantity','Menge'],['company','Firma'],['time','Zeit']]){const b=this.button(name,()=>{this.sort=key;this.render(p);});b.style.margin='4px';sort.append(b);}body.append(sort);let rows=[...book.asks];rows.sort(this.sort==='quantity'?(a,b)=>b.remaining-a.remaining:this.sort==='company'?(a,b)=>sellerName(a).localeCompare(sellerName(b),'de'):this.sort==='time'?(a,b)=>a.createdAt-b.createdAt:(a,b)=>a.unitPrice-b.unitPrice);const table=this.el('table');Object.assign(table.style,{width:'100%',borderCollapse:'collapse',marginTop:'10px'});const tr=this.el('tr');for(const x of ['Firma','Menge','Preis / Einheit','Gesamtpreis','Aktion']){const th=this.el('th',x);Object.assign(th.style,{textAlign:'left',padding:'9px',borderBottom:'1px solid #6b7280'});tr.append(th);}table.append(tr);for(const o of rows){const r=this.el('tr'),q=this.input(String(Math.min(1,o.remaining)),'number');q.min='0.01';q.max=String(o.remaining);const vals=[sellerName(o),n(o.remaining).toLocaleString('de-DE'),formatMoney(o.unitPrice),formatMoney(o.remaining*o.unitPrice)];for(const x of vals){const td=this.el('td',x);td.style.padding='9px';r.append(td);}const td=this.el('td');td.style.padding='9px';if(String(o.companyId)===String(c?.serverCompanyId||c?.id))td.append(this.el('span','Eigenes Angebot'));else{td.append(q,this.button('Teilkauf vorbereiten',()=>alert(`Kauf von ${q.value} × ${label(id)} zu ${formatMoney(o.unitPrice)} wird im nächsten Marktblock mit Transport und sicherer Transaktion verdrahtet.`)));}r.append(td);table.append(r);}if(!rows.length){const r=this.el('tr'),td=this.el('td','Noch keine Verkaufsangebote für diese Ware.');td.colSpan=5;td.style.padding='16px';r.append(td);table.append(r);}body.append(table);}
 renderSell(body,p,c,w){body.append(this.el('h3','💶 Eigene Waren am Markt anbieten'));body.append(this.el('div','Hier kannst du Rohstoffe, Verpackung und Fertigwaren aus deinem tatsächlichen Lager anbieten. Die Menge wird reserviert, bis sie verkauft oder das Angebot zurückgezogen wird.'));if(!c)return body.append(this.el('div','Kein aktiver Betrieb.'));const ids=productIds().filter(id=>marketStock(c,id)>0);if(!ids.length)return body.append(this.el('div','Aktuell ist keine frei verfügbare Ware im Lager, die am Markt angeboten werden kann.'));const table=this.el('table');Object.assign(table.style,{width:'100%',borderCollapse:'collapse',marginTop:'14px'});let h=this.el('tr');for(const x of ['Ware','Gewerbe','Frei verfügbar','Verkaufsmenge','Preis / Einheit','Aktion']){const th=this.el('th',x);th.style.padding='8px';th.style.textAlign='left';th.style.borderBottom='1px solid #6b7280';h.append(th);}table.append(h);for(const id of ids){const r=this.el('tr'),qty=this.input('','number'),price=this.input('','number');qty.min='0.01';qty.max=String(marketStock(c,id));qty.placeholder='Menge';price.min='0.01';price.step='0.01';price.placeholder='Preis';const industries=branchKeysFor(id).map(branchLabel).join(', ');for(const x of [label(id),industries,marketStock(c,id).toLocaleString('de-DE')]){const td=this.el('td',x);td.style.padding='8px';r.append(td);}let td=this.el('td');td.append(qty);r.append(td);td=this.el('td');td.append(price);r.append(td);td=this.el('td');td.append(this.button('Am Markt anbieten',()=>{try{const q=n(qty.value),pr=n(price.value);if(q<=0)throw new Error('Bitte Verkaufsmenge eingeben');if(pr<=0)throw new Error('Bitte Verkaufspreis eingeben');placeSellOrder(w,c,{productId:id,quantity:q,unitPrice:pr});this.selected='__offers';this.render(p);}catch(e){alert(e.message);}}));r.append(td);table.append(r);}body.append(table);}
 renderOffers(body,p,c,w){body.append(this.el('h3','📋 Meine aktiven Marktangebote'));if(!c)return body.append(this.el('div','Kein aktiver Betrieb.'));const mine=ensureExchange(w).orders.filter(o=>String(o.companyId)===String(c.serverCompanyId||c.id)&&['open','partial'].includes(o.status));if(!mine.length){body.append(this.el('div','Du hast derzeit keine aktiven Angebote.'));body.append(this.button('💶 Waren verkaufen',()=>{this.selected='__sell';this.render(p);}));return;}for(const o of mine){const row=this.el('div');Object.assign(row.style,{display:'grid',gridTemplateColumns:'1fr auto',gap:'10px',alignItems:'center',padding:'10px',borderBottom:'1px solid #4b5563'});const info=this.el('div');info.append(this.el('strong',label(o.productId)),this.el('div',`${n(o.remaining).toLocaleString('de-DE')} von ${n(o.quantity).toLocaleString('de-DE')} verfügbar · ${formatMoney(o.unitPrice)} / Einheit · Gesamt ${formatMoney(o.remaining*o.unitPrice)}`));row.append(info,this.button('Angebot zurückziehen',()=>{cancelMarketOrder(w,o.id);this.render(p);}));body.append(row);}}
}

export function runPlayerMarketDialogShapeTest(){const ids=productIds(),cats=marketCategories(ids);if(!Array.isArray(ids)||!Array.isArray(cats)||cats.some(c=>!Array.isArray(c.items)))throw new Error('Markt-Kategorisierung ungültig');return true;}
if(typeof window!=='undefined'){window.worldPlayerMarketDialog=window.worldPlayerMarketDialog||new PlayerMarketDialog();window.openWorldPlayerMarket=()=>window.worldPlayerMarketDialog.open();}
