// WorldProject – B2B-Marktplatz zwischen Spieler-/NPC-Betrieben.
// Physische Waren werden ausschliesslich ueber den transportfaehigen Direktkauf abgewickelt.
import { worldCurrency } from './WorldCurrencySystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const dirty=(reason,detail={})=>{if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('world:player-market-dirty',{detail:{reason,...detail}}));};
export function ensureExchange(world={}){world.exchange??={orders:[],trades:[],feesCollected:0,requestIds:[]};return world.exchange;}
function operationalBags(company){const stock=company?.operationalSupplyState?.warehouseStock||{};return ['raw','packaging','cold','finished'].map(zone=>stock?.[zone]).filter(Boolean);}
function hasOperationalStock(company){return Boolean(company?.operationalSupplyState?.warehouseStock);}
export function marketStock(company,productId){const op=operationalBags(company).reduce((sum,bag)=>sum+n(bag?.[productId]),0),legacy=hasOperationalStock(company)?0:n(company?.inventory?.[productId])+n(company?.finishedGoods?.[productId]);return Math.max(0,op+legacy-n(company?.marketReserved?.[productId]));}
export function placeSellOrder(world,company,{productId,quantity,unitPrice,expiresAt=null,requestId=null}={}){const ex=ensureExchange(world),q=Math.max(0,n(quantity)),p=Math.max(0,n(unitPrice));if(!productId||q<=0||p<=0)throw new Error('Ungültige Verkaufsorder');if(requestId&&ex.requestIds.includes(requestId))return{success:true,idempotent:true};company.marketReserved??={};const have=marketStock(company,productId);if(have<q)throw new Error('Nicht genug freie Ware');company.marketReserved[productId]=n(company.marketReserved[productId])+q;const order={id:`ask-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,side:'sell',companyId:company.serverCompanyId||company.id,companyRef:company,productId,quantity:q,remaining:q,unitPrice:p,createdAt:Date.now(),expiresAt,status:'open'};ex.orders.push(order);if(requestId)ex.requestIds.push(requestId);dirty('sell-order',{orderId:order.id});return{success:true,order};}
export function placeBuyOrder(){throw new Error('Automatische Kauforders für physische Ware sind deaktiviert. Ware wird über bestätigten Direktkauf mit Transport gekauft.');}
export function placeLocalSellOrder(world,company,args={}){const local=n(args.unitPrice),base=worldCurrency.toBase(local,args.currency||worldCurrency.currency);return placeSellOrder(world,company,{...args,unitPrice:base});}
export function placeLocalBuyOrder(){return placeBuyOrder();}
function releaseSellReservation(o){const release=Math.max(0,n(o?.remaining));if(o?.side==='sell'&&o.companyRef&&release>0){o.companyRef.marketReserved??={};o.companyRef.marketReserved[o.productId]=Math.max(0,n(o.companyRef.marketReserved[o.productId])-release);}return release;}
export function cancelMarketOrder(world,orderId){const ex=ensureExchange(world),o=ex.orders.find(x=>x.id===orderId);if(!o)throw new Error('Order fehlt');if(o.status!=='open'&&o.status!=='partial')return{success:true,idempotent:true};const release=releaseSellReservation(o);o.remaining=0;o.status='cancelled';o.cancelledAt=Date.now();dirty('cancel-order',{orderId,releasedQuantity:release});return{success:true,order:o,releasedQuantity:release};}
export function expireMarketOrders(world,now=Date.now()){const ex=ensureExchange(world),expired=[];for(const o of ex.orders){if(!['open','partial'].includes(o.status))continue;const expiry=Number(o.expiresAt)||Date.parse(o.expiresAt);if(!Number.isFinite(expiry)||expiry<=0||expiry>now)continue;const releasedQuantity=releaseSellReservation(o);o.status='expired';o.expiredAt=now;expired.push({order:o,releasedQuantity});}if(expired.length)dirty('expire-orders',{count:expired.length});return expired;}
export function orderBook(world,productId){expireMarketOrders(world);const ex=ensureExchange(world);return{asks:ex.orders.filter(x=>x.productId===productId&&x.side==='sell'&&['open','partial'].includes(x.status)&&n(x.remaining)>0).sort((a,b)=>a.unitPrice-b.unitPrice),bids:[],lastTrades:ex.trades.filter(x=>x.productId===productId).slice(-20)};}
export function runPlayerMarketOperationalStockTest(){const c={operationalSupplyState:{warehouseStock:{raw:{malt:100},packaging:{caps:2000},cold:{},finished:{beer:50}}},inventory:{malt:100},finishedGoods:{beer:50},marketReserved:{}};if(marketStock(c,'caps')!==2000||marketStock(c,'malt')!==100||marketStock(c,'beer')!==50)throw new Error('Operativer Marktbestand wird falsch ermittelt oder doppelt gezählt');const w={};placeSellOrder(w,c,{productId:'caps',quantity:1000,unitPrice:.02});if(c.marketReserved.caps!==1000)throw new Error('Operative Ware kann nicht am Markt reserviert werden');const o=w.exchange.orders[0];o.remaining=400;o.status='partial';c.marketReserved.caps=400;const cancelled=cancelMarketOrder(w,o.id);if(c.marketReserved.caps!==0||cancelled.releasedQuantity!==400||o.remaining!==0)throw new Error('Teilverkauf wird beim Zurückziehen nicht korrekt freigegeben');if(marketStock(c,'caps')!==2000)throw new Error('Freigegebene Restmenge ist danach nicht wieder verfügbar');const w2={},c2={id:'x',inventory:{malt:50},finishedGoods:{},marketReserved:{}};placeSellOrder(w2,c2,{productId:'malt',quantity:20,unitPrice:1,expiresAt:500});const expired=expireMarketOrders(w2,1000);if(expired.length!==1||c2.marketReserved.malt!==0||w2.exchange.orders[0].status!=='expired')throw new Error('Abgelaufenes Angebot blockiert weiterhin Ware');let blocked=false;try{placeBuyOrder(w,c,{productId:'caps',quantity:10,maxUnitPrice:.03});}catch{blocked=true;}if(!blocked)throw new Error('Unsicherer automatischer Warenkauf ist noch aktiv');return true;}
if(typeof window!=='undefined')window.worldPlayerMarket={ensure:ensureExchange,sell:placeSellOrder,buy:placeBuyOrder,sellLocal:placeLocalSellOrder,buyLocal:placeLocalBuyOrder,cancel:cancelMarketOrder,expire:expireMarketOrders,book:orderBook,stock:marketStock};