// ORVUNO – Nachrichten, Statistiken, Hilfe und Rechtliches.
// Ergänzt die bestehende Hauptnavigation ohne die vorhandenen Spielmodule zu ersetzen.

const LEGAL_PLACEHOLDER='Vor Veröffentlichung ergänzen';
const state={messages:[],overview:null,active:null,loading:false};

function api(){return window.worldAccounts?.authApi||null;}
function user(){return window.worldCurrentUser||null;}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmtMoney(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('de-DE');}
function button(id,text,handler){
  const nav=document.getElementById('world-main-nav');if(!nav)return null;
  let b=document.getElementById(id);if(b)return b;
  b=document.createElement('button');b.id=id;b.textContent=text;
  Object.assign(b.style,{position:'static',flex:'0 0 auto',whiteSpace:'nowrap',border:'1px solid #32445e',borderRadius:'10px',padding:'12px 16px',fontWeight:'800',cursor:'pointer',boxShadow:'0 5px 18px rgba(0,0,0,.35)',pointerEvents:'auto',background:'#101a2b',color:'#edf3ff'});
  b.onclick=handler;nav.append(b);return b;
}
function ensureStyles(){if(document.getElementById('orvuno-info-hub-style'))return;const s=document.createElement('style');s.id='orvuno-info-hub-style';s.textContent=`
.orvuno-hub-backdrop{position:fixed;inset:0;z-index:85000;background:rgba(2,7,14,.82);backdrop-filter:blur(4px);display:flex;align-items:center;justify-content:center;padding:22px;font-family:Arial,sans-serif;color:#edf3ff}
.orvuno-hub{width:min(1120px,96vw);max-height:92vh;overflow:hidden;background:#0c1523;border:1px solid #2b405f;border-radius:18px;box-shadow:0 30px 90px rgba(0,0,0,.65);display:flex;flex-direction:column}
.orvuno-hub-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:18px 20px;border-bottom:1px solid #24334b;background:#101c2e}.orvuno-hub-head h2{margin:0;font-size:22px}.orvuno-hub-close,.orvuno-hub-action{border:1px solid #365070;background:#16263d;color:#fff;border-radius:9px;padding:9px 13px;font-weight:800;cursor:pointer}.orvuno-hub-close{background:#35161b;border-color:#7c3038}
.orvuno-hub-tabs{display:flex;gap:8px;flex-wrap:wrap;padding:12px 18px;border-bottom:1px solid #24334b;background:#0d1828}.orvuno-hub-tab{border:1px solid #304665;background:#142238;color:#cfe0f8;border-radius:9px;padding:9px 12px;font-weight:800;cursor:pointer}.orvuno-hub-tab.active{background:#254f9d;color:#fff;border-color:#4d7bd3}
.orvuno-hub-body{overflow:auto;padding:20px}.orvuno-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.orvuno-card{background:#111e31;border:1px solid #263a56;border-radius:13px;padding:15px}.orvuno-card h3{margin:0 0 9px}.orvuno-muted{color:#9fb0c8}.orvuno-kpi{font-size:26px;font-weight:900;margin-top:6px}.orvuno-form{display:grid;gap:10px}.orvuno-form input,.orvuno-form textarea{width:100%;box-sizing:border-box;background:#08111e;border:1px solid #314766;color:#fff;border-radius:9px;padding:11px}.orvuno-form textarea{min-height:130px;resize:vertical}.orvuno-message{border:1px solid #2d415f;border-radius:12px;padding:13px;margin-bottom:10px;background:#0f1b2d;cursor:pointer}.orvuno-message.unread{border-color:#4b82df;background:#122744}.orvuno-message-meta{display:flex;justify-content:space-between;gap:12px;color:#a9bad1;font-size:12px}.orvuno-faq details{background:#111e31;border:1px solid #263a56;border-radius:11px;padding:12px 14px;margin-bottom:9px}.orvuno-faq summary{cursor:pointer;font-weight:900}.orvuno-legal{line-height:1.6}.orvuno-legal h3{margin-top:24px}.orvuno-warning{background:#322715;border:1px solid #735a25;color:#ffe8ad;border-radius:10px;padding:12px;margin-bottom:16px}@media(max-width:700px){.orvuno-hub-backdrop{padding:8px}.orvuno-hub{max-height:96vh}.orvuno-hub-body{padding:13px}}
`;document.head.append(s);}
function shell(title){ensureStyles();document.querySelector('.orvuno-hub-backdrop')?.remove();const back=document.createElement('div');back.className='orvuno-hub-backdrop';back.innerHTML=`<div class="orvuno-hub"><div class="orvuno-hub-head"><h2>${esc(title)}</h2><button class="orvuno-hub-close">✕ Schließen</button></div><div class="orvuno-hub-tabs"></div><div class="orvuno-hub-body"></div></div>`;document.body.append(back);back.querySelector('.orvuno-hub-close').onclick=()=>back.remove();back.addEventListener('click',e=>{if(e.target===back)back.remove();});return{back,tabs:back.querySelector('.orvuno-hub-tabs'),body:back.querySelector('.orvuno-hub-body')};}
function addTab(tabs,label,key,activate){const b=document.createElement('button');b.className='orvuno-hub-tab';b.dataset.key=key;b.textContent=label;b.onclick=()=>activate(key);tabs.append(b);return b;}

async function loadMessages(){const a=api();if(!a||!user())return[];try{const rows=await a.rpc('get_player_messages',{p_limit:150});state.messages=Array.isArray(rows)?rows:[];}catch(error){console.warn('Nachrichten konnten nicht geladen werden',error);state.messages=[];}refreshMessageBadge();return state.messages;}
function unreadCount(){const me=Number(user()?.id||0);return state.messages.filter(m=>Number(m.recipient_user_id)===me&&!m.read_at).length;}
function refreshMessageBadge(){const b=document.getElementById('world-messages-button');if(!b)return;const n=unreadCount();b.textContent=n?`💬 Nachrichten (${n})`:'💬 Nachrichten';}
async function markRead(m){if(m.read_at||Number(m.recipient_user_id)!==Number(user()?.id))return;try{await api()?.rpc('mark_player_message_read',{p_message_id:Number(m.id)});m.read_at=new Date().toISOString();refreshMessageBadge();}catch(e){console.warn('Nachricht konnte nicht als gelesen markiert werden',e);}}
async function sendMessage(form,status){const to=form.querySelector('[name=to]').value.trim(),subject=form.querySelector('[name=subject]').value.trim(),body=form.querySelector('[name=body]').value.trim();if(!to||!body){status.textContent='Empfänger und Nachricht sind erforderlich.';return;}status.textContent='Wird gesendet …';try{await api().rpc('send_player_message',{p_recipient_username:to,p_subject:subject,p_body:body});form.reset();status.textContent='✅ Nachricht wurde gesendet.';await loadMessages();}catch(error){status.textContent=`❌ ${error.message}`;}}
function renderMessages(root){const me=Number(user()?.id||0);root.innerHTML=`<div class="orvuno-grid"><div class="orvuno-card"><h3>Neue Nachricht</h3><form class="orvuno-form" id="orvuno-message-form"><input name="to" maxlength="80" placeholder="Spielername" required><input name="subject" maxlength="160" placeholder="Betreff"><textarea name="body" maxlength="5000" placeholder="Nachricht" required></textarea><button class="orvuno-hub-action" type="submit">Senden</button><div id="orvuno-message-status" class="orvuno-muted"></div></form></div><div class="orvuno-card"><h3>Postfach</h3><div id="orvuno-message-list"></div></div></div>`;
  const list=root.querySelector('#orvuno-message-list');if(!state.messages.length)list.innerHTML='<div class="orvuno-muted">Noch keine Nachrichten.</div>';else for(const m of state.messages){const incoming=Number(m.recipient_user_id)===me,box=document.createElement('div');box.className=`orvuno-message ${incoming&&!m.read_at?'unread':''}`;box.innerHTML=`<div class="orvuno-message-meta"><span>${incoming?'Von':'An'}: <b>${esc(incoming?m.sender_username:m.recipient_username)}</b></span><span>${fmtDate(m.created_at)}</span></div><h3>${esc(m.subject||'(ohne Betreff)')}</h3><div>${esc(m.body).replace(/\n/g,'<br>')}</div>`;box.onclick=()=>{markRead(m).then(()=>box.classList.remove('unread'));};list.append(box);}
  const form=root.querySelector('#orvuno-message-form'),status=root.querySelector('#orvuno-message-status');form.onsubmit=e=>{e.preventDefault();sendMessage(form,status).then(()=>renderMessages(root));};
}
async function loadOverview(){const a=api();if(!a||!user())return null;try{state.overview=await a.accountOverview();}catch(error){console.warn('Statistik konnte nicht geladen werden',error);state.overview=null;}return state.overview;}
function renderStats(root){const o=state.overview;if(!o){root.innerHTML='<div class="orvuno-warning">Statistiken konnten momentan nicht geladen werden.</div>';return;}const cs=o.companies||[],money=cs.reduce((s,c)=>s+Number(c.money||0),0),assets=cs.reduce((s,c)=>s+Number(c.asset_value||0),0),debt=cs.reduce((s,c)=>s+Number(c.debt||0),0),net=money+assets-debt;root.innerHTML=`<div class="orvuno-grid"><div class="orvuno-card"><div class="orvuno-muted">Betriebe</div><div class="orvuno-kpi">${cs.length}</div></div><div class="orvuno-card"><div class="orvuno-muted">Liquidität gesamt</div><div class="orvuno-kpi">${fmtMoney(money)}</div></div><div class="orvuno-card"><div class="orvuno-muted">Anlagenwert</div><div class="orvuno-kpi">${fmtMoney(assets)}</div></div><div class="orvuno-card"><div class="orvuno-muted">Schulden</div><div class="orvuno-kpi">${fmtMoney(debt)}</div></div><div class="orvuno-card"><div class="orvuno-muted">Netto-Unternehmenswert</div><div class="orvuno-kpi">${fmtMoney(net)}</div></div><div class="orvuno-card"><div class="orvuno-muted">Coins</div><div class="orvuno-kpi">${Number(o.wallet?.balance||0).toLocaleString('de-DE')}</div></div></div><h3 style="margin-top:22px">Betriebe</h3><div class="orvuno-grid">${cs.map(c=>`<div class="orvuno-card"><h3>${esc(c.name||'Betrieb')}</h3><div class="orvuno-muted">${esc(c.industry||c.company_type||'Gewerbe')}</div><p>Geld: <b>${fmtMoney(c.money)}</b><br>Anlagen: <b>${fmtMoney(c.asset_value)}</b><br>Schulden: <b>${fmtMoney(c.debt)}</b><br>Gegründet: <b>${fmtDate(c.founded_at||c.created_at)}</b></p></div>`).join('')}</div>`;}
const FAQ=[
 ['Wie gründe ich einen weiteren Betrieb?','Öffne „Betriebe“. Dort siehst du freie Betriebsslots und die Voraussetzungen für eine Erweiterung.'],
 ['Wie kaufe ich Rohstoffe und Waren?','Nutze den Betriebsbereich für Einkauf und Lager. Je nach Ware stehen KI-Lieferanten, Spielermarkt oder verbundene Betriebe zur Verfügung.'],
 ['Wie funktioniert Produktion?','Eine Produktion benötigt passende Rohstoffe, eine geeignete Maschine, ausreichende Lagerfläche und – sofern vorgesehen – zugewiesenes Personal.'],
 ['Warum startet eine Produktion nicht?','Prüfe Rohstoffe, freie Lagerkapazität, Maschinenzustand, Personalzuweisung und die Produktionswarteschlange.'],
 ['Wie funktionieren Lieferungen?','Waren müssen je nach Vorgang einem passenden Fahrzeug zugewiesen werden. Fahrzeit, Treibstoff und Fahrzeugkapazität werden berücksichtigt.'],
 ['Was bringt Premium?','Premium erweitert Komfort und parallele Möglichkeiten, beispielsweise zusätzliche Warteschlangen oder Automatisierung. Laufende Vorgänge werden bei Ablauf nicht einfach gelöscht.'],
 ['Was sind Coins?','Coins sind die zusätzliche Spielwährung für dafür vorgesehene Komfort- und Beschleunigungsfunktionen.'],
 ['Wie funktioniert der Spielermarkt?','Spieler können Waren zu eigenen Preisen anbieten. Marktgebühren und Verfügbarkeit werden im jeweiligen Marktdialog angezeigt.'],
 ['Kann ich mehrere Gewerbe verbinden?','Ja. Das Spiel unterstützt mehrere Betriebe und vertikale Lieferketten, sodass ein eigener Betrieb einen anderen beliefern kann.'],
 ['Was passiert bei zu wenig Lagerplatz?','Neue Waren oder Produktion können blockiert werden. Lagerausbau oder Bestandsabbau schafft wieder Kapazität.'],
 ['Wie erkenne ich wichtige Probleme?','Dashboard und Betriebsübersicht markieren laufende Vorgänge, Engpässe und Handlungsbedarf.'],
 ['Wie schreibe ich einem anderen Spieler?','Öffne „Nachrichten“, gib den exakten Spielernamen ein und sende deine Nachricht.'],
 ['Wie melde ich ein Problem?','Für technische oder spielbezogene Probleme kann der Support-/Adminbereich Fälle aufnehmen. Ein eigener Spieler-Supportdialog wird später noch erweitert.'],
 ['Werden meine Daten online gespeichert?','Kontodaten und zentrale Spielstände werden über Supabase synchronisiert. Lokale Komfortdaten können zusätzlich im Browser gespeichert werden.']
];
function renderHelp(root){root.innerHTML=`<div class="orvuno-card"><h3>ORVUNO Hilfe</h3><p class="orvuno-muted">Die häufigsten Fragen zum Spiel. Dieser Bereich wird mit neuen Spielsystemen weiter ergänzt.</p></div><div class="orvuno-faq" style="margin-top:12px">${FAQ.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</div>`;}
const legal={
 impressum:`<div class="orvuno-warning"><b>Hinweis für die Entwicklungsphase:</b> Vor einer öffentlichen Veröffentlichung müssen die echten Anbieterangaben ergänzt und geprüft werden.</div><h3>Impressum</h3><p><b>Anbieter / Verantwortlicher:</b> ${LEGAL_PLACEHOLDER}<br><b>Anschrift:</b> ${LEGAL_PLACEHOLDER}<br><b>E-Mail:</b> ${LEGAL_PLACEHOLDER}</p><h3>Kontakt</h3><p>Kontaktmöglichkeit und gegebenenfalls weitere gesetzlich vorgeschriebene Angaben werden vor Veröffentlichung ergänzt.</p><h3>Haftung für Inhalte</h3><p>Die Inhalte des Spiels und dieser Website werden sorgfältig gepflegt. Für externe Inhalte und Verlinkungen gelten die jeweils einschlägigen gesetzlichen Regelungen.</p>`,
 datenschutz:`<div class="orvuno-warning"><b>Entwurf:</b> Dieser Text beschreibt die aktuell im Projekt erkennbaren Datenflüsse und ersetzt vor Veröffentlichung keine abschließende rechtliche Prüfung.</div><h3>Datenschutzerklärung</h3><p>ORVUNO verarbeitet Kontodaten und Spieldaten, soweit dies für Anmeldung, Spielbetrieb, Synchronisation, Sicherheit und Support erforderlich ist.</p><h3>Verarbeitete Daten</h3><p>Dazu können insbesondere Benutzername, E-Mail-Adresse, Länder-/Spracheinstellung, technische Login- und Sicherheitsdaten, Spielstände, Firmen- und Wirtschaftsdaten, Nachrichten sowie Premium-/Coin-Status gehören.</p><h3>Zwecke</h3><p>Die Daten werden zur Bereitstellung des Spiels, zur Kontoverwaltung, zur Speicherung und Synchronisation des Spielstands, zur Missbrauchsprävention, für Support und zur Durchführung spielinterner Funktionen verarbeitet.</p><h3>Technischer Dienstleister</h3><p>Für Authentifizierung und Datenbankfunktionen wird Supabase eingesetzt. Vor Veröffentlichung sind die konkreten Betreiberangaben, Rechtsgrundlagen, Aufbewahrungsfristen, Empfänger, Drittlandtransfers und Betroffenenrechte vollständig zu dokumentieren.</p><h3>Spielernachrichten</h3><p>Spielernachrichten werden serverseitig gespeichert. Zugriff ist für Sender und Empfänger vorgesehen; berechtigte Admin-/Supportrollen können sie im erforderlichen Umfang für Moderation und Support einsehen.</p><h3>Deine Rechte</h3><p>Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch richten sich nach den anwendbaren Datenschutzvorschriften. Kontaktdaten des Verantwortlichen werden vor Veröffentlichung ergänzt.</p>`,
 agb:`<div class="orvuno-warning"><b>Entwurf:</b> Vor öffentlichem Start, Echtgeldverkauf oder kostenpflichtigem Premium müssen diese Bedingungen juristisch final geprüft werden.</div><h3>Allgemeine Nutzungsbedingungen</h3><p>ORVUNO ist ein Wirtschaftssimulationsspiel. Mit Nutzung des Spiels gelten die jeweils veröffentlichten Spielregeln und Nutzungsbedingungen.</p><h3>Spielkonto</h3><p>Jeder Nutzer ist für die Sicherheit seiner Zugangsdaten verantwortlich. Automatisierter Missbrauch, Manipulation, Exploits, Mehrfachkonten zum Umgehen von Regeln und Eingriffe in den Spielbetrieb können eingeschränkt oder sanktioniert werden.</p><h3>Virtuelle Güter, Coins und Premium</h3><p>Virtuelle Währungen, Gegenstände und Premiumfunktionen bestehen ausschließlich innerhalb des Spiels. Ein Anspruch auf einen realen Geldwert oder eine Auszahlung besteht nur, wenn dies ausdrücklich angeboten und rechtlich geregelt wird.</p><h3>Fair Play</h3><p>Fehler oder Exploits dürfen nicht vorsätzlich zur Schädigung anderer Spieler oder der Spielwirtschaft ausgenutzt werden. Auffällige Vorgänge können protokolliert und geprüft werden.</p><h3>Verfügbarkeit und Änderungen</h3><p>Spielinhalte, Balancing und Funktionen können weiterentwickelt werden. Bei wesentlichen Änderungen werden Spieler in geeigneter Form informiert.</p><h3>Kommunikation</h3><p>Beleidigende, rechtswidrige, bedrohend wirkende oder missbräuchliche Inhalte sind in der Spielerkommunikation nicht erlaubt und können moderiert werden.</p>`
};
function renderLegal(root,key='impressum'){root.innerHTML=`<div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px"><button class="orvuno-hub-action" data-legal="impressum">Impressum</button><button class="orvuno-hub-action" data-legal="datenschutz">Datenschutz</button><button class="orvuno-hub-action" data-legal="agb">AGB</button></div><div class="orvuno-card orvuno-legal">${legal[key]}</div>`;for(const b of root.querySelectorAll('[data-legal]'))b.onclick=()=>renderLegal(root,b.dataset.legal);}

async function openHub(initial='messages'){
  const ui=shell('ORVUNO – Spielerzentrum');const tabs=[['💬 Nachrichten','messages'],['📊 Statistiken','stats'],['❓ Hilfe','help'],['⚖ Rechtliches','legal']];
  const activate=async key=>{state.active=key;for(const b of ui.tabs.querySelectorAll('.orvuno-hub-tab'))b.classList.toggle('active',b.dataset.key===key);ui.body.innerHTML='<div class="orvuno-muted">Laden …</div>';if(key==='messages'){await loadMessages();renderMessages(ui.body);}else if(key==='stats'){await loadOverview();renderStats(ui.body);}else if(key==='help')renderHelp(ui.body);else renderLegal(ui.body);};
  for(const [label,key] of tabs)addTab(ui.tabs,label,key,activate);await activate(initial);return ui;
}
function mount(){if(window.__orvunoInfoHubMounted)return;window.__orvunoInfoHubMounted=true;button('world-messages-button','💬 Nachrichten',()=>openHub('messages'));button('world-statistics-button','📊 Statistik',()=>openHub('stats'));button('world-help-button','❓ Hilfe',()=>openHub('help'));button('world-legal-button','⚖ Rechtliches',()=>openHub('legal'));const refresh=()=>{loadMessages().catch(()=>{});};for(const ev of ['world:user-login','world:access-granted','world:server-balances-changed','worldproject:company-switched'])window.addEventListener(ev,refresh);setTimeout(refresh,500);}
if(typeof window!=='undefined'){
  window.worldPlayerInfoHub={open:openHub,loadMessages,loadOverview,state};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,0),{once:true});else setTimeout(mount,0);
}
export {openHub,loadMessages,loadOverview};
