// WorldProject – zentrale priorisierte Benachrichtigungen für den Spieler.
const rank={critical:0,warning:1,info:2,success:3};
export function ensureNotifications(c={}){c.notifications??={items:[],readIds:[],dismissedIds:[]};return c.notifications;}
export function pushNotification(c,{severity='info',code,title,detail='',action=null,dedupeKey=null,expiresAt=null}={}){const s=ensureNotifications(c),key=dedupeKey||`${code}:${title}`;const existing=s.items.find(x=>x.dedupeKey===key&&!s.dismissedIds.includes(x.id));if(existing){existing.detail=detail;existing.severity=severity;existing.updatedAt=Date.now();return existing;}const row={id:`note-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,severity,code,title,detail,action,dedupeKey:key,createdAt:Date.now(),expiresAt};s.items.push(row);return row;}
export function markNotificationRead(c,id){const s=ensureNotifications(c);if(!s.readIds.includes(id))s.readIds.push(id);return true;}
export function dismissNotification(c,id){const s=ensureNotifications(c);if(!s.dismissedIds.includes(id))s.dismissedIds.push(id);return true;}
export function activeNotifications(c,{now=Date.now(),limit=50}={}){const s=ensureNotifications(c);return s.items.filter(x=>!s.dismissedIds.includes(x.id)&&(!x.expiresAt||x.expiresAt>now)).sort((a,b)=>(rank[a.severity]??9)-(rank[b.severity]??9)||b.createdAt-a.createdAt).slice(0,limit).map(x=>({...x,read:s.readIds.includes(x.id)}));}
export function syncBusinessNotifications(c,{commandCenter=null,tax=null,insurance=null,brand=null,progression=null}={}){const add=x=>pushNotification(c,x);for(const a of commandCenter?.alerts||[])add({severity:a.severity,code:a.code,title:a.title,detail:a.detail,action:a.action,dedupeKey:`cc:${a.code}`});if(tax?.overdue)add({severity:'critical',code:'tax_overdue',title:'Steuerzahlung überfällig',detail:`${tax.overdue} Steuerperiode(n) überfällig`,action:'finance',dedupeKey:'tax:overdue'});if(tax?.reserve>0)add({severity:'info',code:'tax_reserve',title:'Steuerreserve berücksichtigen',detail:`${Math.round(tax.reserve)} € reserviert`,action:'finance',dedupeKey:'tax:reserve'});if(insurance?.open)add({severity:'info',code:'insurance_claim',title:'Versicherungsfälle offen',detail:`${insurance.open} Vorgang/Vorgänge`,action:'insurance',dedupeKey:'insurance:open'});if(brand&&brand.score<40)add({severity:'warning',code:'brand_weak',title:'Markenimage schwach',detail:`Markenscore ${Math.round(brand.score)}`,action:'marketing',dedupeKey:'brand:weak'});for(const a of progression?.newAchievements||[])add({severity:'success',code:'achievement',title:`Erfolg erreicht: ${a.label}`,detail:'Neue Unternehmensleistung freigeschaltet',action:'progression',dedupeKey:`achievement:${a.id}`});return activeNotifications(c);}
export function notificationKpis(c){const a=activeNotifications(c);return{active:a.length,unread:a.filter(x=>!x.read).length,critical:a.filter(x=>x.severity==='critical').length,warnings:a.filter(x=>x.severity==='warning').length};}
if(typeof window!=='undefined')window.worldNotifications={push:pushNotification,read:markNotificationRead,dismiss:dismissNotification,active:activeNotifications,sync:syncBusinessNotifications,kpis:notificationKpis};
