// WorldProject – B2B-Warenmarktplatz. Physische Käufe werden bezahlt, transportiert und erst bei Ankunft eingelagert.
import { ensureExchange, placeSellOrder, cancelMarketOrder, orderBook, marketStock } from './PlayerMarketExchange.js';
import { buyGoodsFromSellOrder, goodsPurchaseQuote } from './PlayerMarketDirectGoodsPurchase.js';
import { marketPriceAdvice } from './MarketPriceAdvisor.js';
import { worldContentRegistry } from './ContentRegistry.js';
import { formatMoney } from './CurrencyPresentationBridge.js';
const n=v=>Number(v||0),company=()=>window.worldPlayerCompany||window.worldActiveServerCompany||null,world=()=>window.worldProjectWorld||window.worldWorld||window.worldGameState||window;
const meta=id=>worldContentRegistry.get('products',id)||worldContentRegistry.get('materials',id)||null,label=id=>meta(id)?.label||String(id).replace(/_/g,' '),sellerName=o=>o.companyRef?.name||o.companyRef?.companyName||o.companyRef?.company_name||`Firma ${o.companyId??'–'}`;
const registryTradableIds=()=>[...new Set([...worldContentRegistry.list('products'),...worldContentRegistry.list('materials')].filter(x=>x.sellable!==false).map(x=>x.id))],companyStockIds=c=>{const ids=new Set();for(const zone of Object.values(c?.operationalSupplyState?.warehouseStock||{}))for(const id of Object.keys(zone||{}))if(meta(id)?.sellable!==false)ids.add(id);for(const bag of [c?.inventory,c?.finishedGoods])for(const id of Object.keys(bag||{}))if(meta(id)?.sellable!==false)ids.add(id);return [...ids];};
const marketTradableIds=(w=world(),c=company())=>[...new Set([...registryTradableIds(),...companyStockIds(c),...ensureExchange(w).orders.filter(o=>o?.productId).map(o=>o.productId)])].filter(id=>meta(id)?.sellable!==false).sort((a,b)=>label(a).localeCompare(label(b),'de'));
const BRANCH_LABELS={brewery:'Brauerei & Getränke',beverage:'Getränkeherstellung',bakery:'Bäckerei',butcher:'Metzgerei',carpentry:'Schreinerei',farm:'Landwirtschaft',livestock:'Tierhaltung',orchard:'Obstbau',forestry:'Forstwirtschaft',sawmill:'Sägewerke',mill:'Mühlen',maltster:'Mälzereien',hops_farm:'Hopfenbau',sugar_factory:'Zuckerindustrie',feed_mill:'Futtermühlen',dairy:'Molkereien',slaughterhouse:'Schlachthöfe',glassworks:'Glas & Flaschen',closures:'Verschlüsse',paper_mill:'Papierindustrie',label_print:'Etikettendruck',packaging_maker:'Verpackungen',steelworks:'Stahlindustrie',polymer:'Kunststoffrohstoffe',food_chemicals:'Lebensmittelchemie',agri_chemicals:'Agrarchemie',mechanical:'Maschinenbau',metal:'Metallverarbeitung',plastic:'Kunststoff',retail:'Einzelhandel',wholesale:'Großhandel',online_retail:'Onlinehandel',food:'Lebensmittel',other:'Sonstige Waren'};
const branchKeysFor=id=>{const x=meta(id),a=Array.isArray(x?.industries)?x.industries:[];return a.length?a:['other'];},branchLabel=id=>BRANCH_LABELS[id]||worldContentRegistry.get('industries',id)?.label||'Sonstige Waren';
export function marketCategories(ids=marketTradableIds()){const g=new Map();for(const id of ids)for(const k of branchKeysFor(id)){if(!g.has(k))g.set(k,[]);if(!g.get(k).includes(id))g.get(k).push(id);}return[...g.entries()].map(([id,items])=>({id,label:branchLabel(id),items:items.sort((a,b)=>label(a).localeCompare(label(b),'de'))})).sort((a,b)=>a.label.localeCompare(b.label,'de'));}
export function filterMarketIds(ids,query=''){const q=String(query||'').trim().toLocaleLowerCase('de');return q?ids.filter(id=>`${label(id)} ${id} ${branchKeysFor(id).map(branchLabel).join(' ')}`.toLocaleLowerCase('de').includes(q)):[...ids];}
export class PlayerMarketDialog{
 constructor({parent=document.body}={}){this.parent=parent;this.overlay=null;this.selected=null;this.sort='price';this.category=null;this.search='';}el(t,x=null){const e=document.createElement(t);if(x!==null)e.textContent=x;return e;}button(x,fn){const b=this.el('button',x);Object.assign(b.style,{padding:'8px 11px',border:'1px solid #4b5563',borderRadius:'8px',background:'#374151',color:'#fff',fontWeight:'700',cursor:'pointer'});b.onclick=fn;return b;}input(v='',type='text'){const i=this.el('input');i.type=type;i.value=v;Object.assign(i.style,{padding:'8px',border:'1px solid #6b7280',borderRadius:'7px',background:'#111827',color:'#fff',width:'110px'});return i;}
 open(){if(this.overlay)return;const ov=this.el('div');Object.assign(ov.style,{position:'fixed',inset:0,zIndex:60000,background:'rgba(0,0,0,.76)',display:'flex',justifyContent:'center',alignItems:'center',padding:'18px'});const p=this.el('div');p.dataset.worldPlayerMarketDialog='1';Object.assign(p.style,{position:'relative',width:'min(1220px,98vw)',maxHeight:'94vh',overflow:'auto',background:'#1f2937',color:'#f9fafb',borderRadius:'14px',fontFamily:'Arial,sans-serif',isolation:'isolate'});ov.append(p);this.parent.append(ov);this.overlay=ov;this.render(p);}close(){this.overlay?.remove();this.overlay=null;}
 render(p){p.innerHTML='';const c=company(),w=world();ensureExchange(w);const close=this.button('✕ Schließen',()=>this.close());Object.assign(close.style,{position:'sticky',top:'10px',float:'right',margin:'10px 12px -48px 0',zIndex:'2147483647',flex:'0 0 auto',boxShadow:'0 4px 14px rgba(0,0,0,.55)'});p.append(close);const h=this.el('div');Object.assign(h.style,{position:'sticky',top:'0',zIndex:'60010',display:'flex',justifyContent:'flex-start',alignItems:'center',padding:'16px 150px 16px 20px',background:'#111827',boxShadow:'0 2px 8px rgba(0,0,0,.45)'});h.append(this.el('h2','🌐 Marktplatz'));p.append(h);const b=this.el('div');b.style.padding='18px 20px';p.append(b);const nav=this.el('div');Object.assign(nav.style,{display:'flex',gap:'8px',flexWrap:'wrap',marginBottom:'16px'});nav.append(this.button('🛒 Waren kaufen',()=>{this.selected=null;this.render(p);}),this.button('💶 Waren verkaufen',()=>{this.selected='__sell';this.render(p);}),this.button('📋 Meine Angebote',()=>{this.selected='__offers';this.render(p);}));b.append(nav);if(this.selected==='__sell')return this.renderSell(b,p,c,w);if(this.selected==='__offers')return this.renderOffers(b,p,c,w);if(this.selected)return this.renderBook(b,p,c,w,this.selected);this.renderProducts(b,p,w,c);}
 renderSearch(body,onFilter){const w=this.el('div'),s=this.input(this.search,'search');s.placeholder='Ware suchen …';Object.assign(w.style,{display:'flex',gap:'8px',margin:'12px 0'});Object.assign(s.style,{width:'min(430px,100%)'});s.oninput=()=>{this.search=s.value;onFilter();};w.append(this.el('strong','🔎 Suche'),s);body.append(w);}
 renderProducts(body,p,w,c){const ids=marketTradableIds(w,c),open=ensureExchange(w).orders.filter(o=>['open','partial'].includes(o.status)&&o.side==='sell'&&n(o.remaining)>0);body.append(this.el('h3','Warenmarkt nach Gewerbe'),this.el('div','Physische Ware wird nach dem Kauf transportiert und erst bei Ankunft eingelagert.'));const out=this.el('div'),tabs=this.el('div');Object.assign(tabs.style,{display:'flex',gap:'7px',flexWrap:'wrap',margin:'14px 0'});const paint=()=>{out.innerHTML='';const cats=marketCategories(filterMarketIds(ids,this.search)),shown=this.category?cats.filter(x=>x.id===this.category):cats;for(const cat of shown){out.append(this.el('h3',cat.label));const g=this.el('div');Object.assign(g.style,{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(210px,1fr))',gap:'8px'});for(const id of cat.items){const count=open.filter(o=>o.productId===id).length;g.append(this.button(`${label(id)}${count?` · ${count} Angebot${count===1?'':'e'}`:''}`,()=>{this.selected=id;this.render(p);}));}out.append(g);}};this.renderSearch(body,paint);tabs.append(this.button('Alle Branchen',()=>{this.category=null;paint();}));for(const cat of marketCategories(ids))tabs.append(this.button(cat.label,()=>{this.category=cat.id;paint();}));body.append(tabs,out);paint();}
 renderBook(body,p,c,w,id){const book=orderBook(w,id);body.append(this.button('← Produktübersicht',()=>{this.selected=null;this.render(p);}),this.el('h3',`Angebote: ${label(id)}`));let rows=[...book.asks];rows.sort(this.sort==='quantity'?(a,b)=>b.remaining-a.remaining:this.sort==='company'?(a,b)=>sellerName(a).localeCompare(sellerName(b),'de'):(a,b)=>a.unitPrice-b.unitPrice);for(const o of rows){const row=this.el('div');Object.assign(row.style,{padding:'12px',borderBottom:'1px solid #4b5563'});row.append(this.el('strong',sellerName(o)),this.el('div',`${n(o.remaining).toLocaleString('de-DE')} verfügbar · ${formatMoney(o.unitPrice)} / Einheit`));if(String(o.companyId)===String(c?.serverCompanyId||c?.id)){row.append(this.el('div','Eigenes Angebot'));body.append(row);continue;}const q=this.input(String(o.remaining),'number'),sum=this.el('div'),buy=this.button('Kauf prüfen',()=>{try{const quote=goodsPurchaseQuote(o,c,q.value);sum.textContent=`${quote.quantity.toLocaleString('de-DE')} × ${formatMoney(quote.unitPrice)} = ${formatMoney(quote.total)} · Spielgeld: ${formatMoney(quote.balance)}${quote.limitedByAvailability?' · Menge auf verfügbaren Rest begrenzt':''}`;const confirm=this.button('Kauf verbindlich bestätigen',()=>{try{const r=buyGoodsFromSellOrder(w,c,o.id,{quantity:q.value,confirmed:true});alert(`Kauf abgeschlossen. ${r.quote.quantity.toLocaleString('de-DE')} × ${label(id)} sind jetzt unterwegs. Ankunft: ${r.delivery.arrivalTime.toLocaleString('de-DE')}`);this.render(p);}catch(e){alert(e.message);}});sum.append(document.createElement('br'),confirm);}catch(e){alert(e.message);}});q.min='.01';q.max=String(o.remaining);q.step='.01';row.append(q,buy,sum);body.append(row);}if(!rows.length)body.append(this.el('div','Noch keine Verkaufsangebote für diese Ware.'));}
 renderSell(body,p,c,w){body.append(this.el('h3','💶 Eigene Waren am Markt anbieten'),this.el('div','Die KI schlägt einen Preis aus erkannten Stückkosten und Marktlage vor. Du kannst ihn übernehmen oder völlig frei ändern.'));if(!c)return;const ids=marketTradableIds(w,c).filter(id=>marketStock(c,id)>0);if(!ids.length)return body.append(this.el('div','Derzeit ist keine frei verfügbare Ware zum Verkaufen vorhanden.'));for(const id of ids){const row=this.el('div'),qty=this.input('','number'),price=this.input('','number'),preview=this.el('div'),adviceBox=this.el('div');Object.assign(row.style,{padding:'12px 10px',borderBottom:'1px solid #4b5563',display:'grid',gridTemplateColumns:'minmax(190px,1fr) 120px 150px minmax(260px,1.3fr)',gap:'8px',alignItems:'center'});qty.min='.01';qty.max=String(marketStock(c,id));qty.step='.01';qty.placeholder='Menge';price.min='.0001';price.step='.001';price.placeholder='Preis / Einheit';let advice;try{advice=marketPriceAdvice(w,c,id);}catch{advice=null;}const refresh=()=>{const q=n(qty.value),pr=n(price.value);preview.textContent=q>0&&pr>0?`Gesamtwert: ${formatMoney(q*pr)}`:'';};qty.oninput=price.oninput=refresh;const product=this.el('div');product.append(this.el('strong',`${label(id)} · frei ${marketStock(c,id).toLocaleString('de-DE')}`));if(advice){const cost=advice.estimatedUnitCost>0?` · erkannte Kosten ${formatMoney(advice.estimatedUnitCost)}`:'',market=advice.marketReference>0?` · Markt ca. ${formatMoney(advice.marketReference)}`:'';adviceBox.append(this.el('div',`🤖 KI-Vorschlag: ${formatMoney(advice.suggestedPrice)}${cost}${market}`),this.el('div',advice.reason));adviceBox.lastElementChild.style.fontSize='11px';adviceBox.lastElementChild.style.opacity='.8';const use=this.button('🤖 Preis übernehmen',()=>{price.value=String(advice.suggestedPrice);refresh();});adviceBox.append(use);}row.append(product,qty,price);const action=this.el('div');if(adviceBox.childNodes.length)action.append(adviceBox);action.append(preview,this.button('Am Markt anbieten',()=>{try{if(n(qty.value)<=0||n(price.value)<=0)throw new Error('Bitte gültige Menge und gültigen Preis eingeben');placeSellOrder(w,c,{productId:id,quantity:n(qty.value),unitPrice:n(price.value)});this.selected='__offers';this.render(p);}catch(e){alert(e.message);}}));row.append(action);body.append(row);}}
 renderOffers(body,p,c,w){body.append(this.el('h3','📋 Meine aktiven Marktangebote'));if(!c)return;const mine=ensureExchange(w).orders.filter(o=>String(o.companyId)===String(c.serverCompanyId||c.id)&&['open','partial'].includes(o.status)&&n(o.remaining)>0);if(!mine.length)return body.append(this.el('div','Du hast derzeit keine aktiven Angebote.'));for(const o of mine){const row=this.el('div');Object.assign(row.style,{padding:'10px',borderBottom:'1px solid #4b5563'});row.append(this.el('strong',label(o.productId)),this.el('div',`${n(o.remaining).toLocaleString('de-DE')} verfügbar · ${formatMoney(o.unitPrice)} / Einheit · Gesamtwert ${formatMoney(n(o.remaining)*n(o.unitPrice))}`),this.button('Angebot zurückziehen',()=>{const r=cancelMarketOrder(w,o.id);alert(`${r.releasedQuantity.toLocaleString('de-DE')} Einheiten wurden wieder freigegeben.`);this.render(p);}));body.append(row);}}
}
export function runPlayerMarketDialogShapeTest(){const ids=marketTradableIds({},null),cats=marketCategories(ids);if(!Array.isArray(ids)||!Array.isArray(cats))throw new Error('Markt-Kategorisierung ungültig');if(filterMarketIds(['caps'],'kron').length!==1||filterMarketIds(['yeast'],'hefe').length!==1)throw new Error('Marktsuche fehlerhaft');if(branchLabel('glassworks')!=='Glas & Flaschen'||branchLabel('maltster')!=='Mälzereien')throw new Error('Neue Lieferketten-Branchen fehlen im Marktkatalog');return true;}
if(typeof window!=='undefined'){window.worldPlayerMarketDialog=window.worldPlayerMarketDialog||new PlayerMarketDialog();window.openWorldPlayerMarket=()=>window.worldPlayerMarketDialog.open();}
