// WorldProject - Entwicklungs-Fallback fuer den Spielermarkt ueber Reload/F5.
// Wird ignoriert, sobald ein echter serverseitiger Marktadapter aktiv ist.
import { ensureExchange } from './PlayerMarketExchange.js';
const KEY='worldproject:player-market:v1';
const world=()=>window.worldProjectWorld||window.worldWorld||window.worldGameState||window;
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function serverMarketActive(){return Boolean(window.worldServerMarket?.active||window.worldMarketApi?.isServerBacked);}
function serializableExchange(ex={}){return{orders:(ex.orders||[]).map(o=>{const {companyRef,...rest}=o;return rest;}),trades:ex.trades||[],feesCollected:Number(ex.feesCollected||0),requestIds:ex.requestIds||[]};}
function knownCompanies(){const out=[],push=x=>{if(x&&typeof x==='object'&&!out.includes(x))out.push(x);};push(window.worldPlayerCompany);push(window.worldActiveServerCompany);for(const x of window.worldProjectWorld?.companies||[])push(x);for(const x of window.worldWorld?.companies||[])push(x);for(const x of window.worldGameState?.companies||[])push(x);return out;}
function rebindCompanyRefs(ex){const companies=knownCompanies(),byId=new Map(companies.map(c=>[String(c.serverCompanyId||c.id||''),c]));for(const o of ex.orders||[]){const c=byId.get(String(o.companyId||''));if(c)o.companyRef=c;}return companies;}
export function reconcileLocalExchange(ex,now=Date.now()){let repaired=0;for(const o of ex?.orders||[]){if(!o)continue;const status=String(o.status||'').toLowerCase(),remaining=Math.max(0,n(o.remaining));if(['open','partial'].includes(status)&&remaining<=0){o.remaining=0;o.status='filled';repaired++;continue;}const expiry=Number(o.expiresAt)||Date.parse(o.expiresAt);if(['open','partial'].includes(status)&&Number.isFinite(expiry)&&expiry>0&&expiry<=now){o.status='expired';o.expiredAt=now;repaired++;}}
 return repaired;}
export function rebuildLocalMarketReservations(ex,companies=knownCompanies()){const byId=new Map(companies.map(c=>[String(c.serverCompanyId||c.id||''),c]));for(const c of companies)c.marketReserved={};for(const o of ex?.orders||[]){if(o.side!=='sell'||!['open','partial'].includes(String(o.status||''))||n(o.remaining)<=0)continue;const c=o.companyRef||byId.get(String(o.companyId||''));if(!c)continue;c.marketReserved??={};c.marketReserved[o.productId]=n(c.marketReserved[o.productId])+n(o.remaining);o.companyRef=c;}return true;}
export function saveLocalPlayerMarket(){if(typeof localStorage==='undefined'||serverMarketActive())return false;try{const ex=ensureExchange(world());reconcileLocalExchange(ex);localStorage.setItem(KEY,JSON.stringify(serializableExchange(ex)));return true;}catch{return false;}}
export function restoreLocalPlayerMarket(){if(typeof localStorage==='undefined'||serverMarketActive())return false;try{const raw=localStorage.getItem(KEY);if(!raw)return false;const data=JSON.parse(raw),ex=ensureExchange(world());ex.orders=Array.isArray(data.orders)?data.orders:[];ex.trades=Array.isArray(data.trades)?data.trades:[];ex.feesCollected=Number(data.feesCollected||0);ex.requestIds=Array.isArray(data.requestIds)?data.requestIds:[];reconcileLocalExchange(ex);const companies=rebindCompanyRefs(ex);rebuildLocalMarketReservations(ex,companies);return true;}catch{return false;}}
export function installLocalPlayerMarketPersistence(){if(typeof window==='undefined'||window.__worldLocalMarketPersistence)return false;window.__worldLocalMarketPersistence=true;window.addEventListener('world:player-market-dirty',saveLocalPlayerMarket);window.addEventListener('worldproject:company-switched',()=>{const ex=ensureExchange(world());reconcileLocalExchange(ex);const companies=rebindCompanyRefs(ex);rebuildLocalMarketReservations(ex,companies);});restoreLocalPlayerMarket();return true;}
export function runLocalPlayerMarketPersistenceTest(){const company={id:'1',marketReserved:{malt:999}},ex={orders:[{id:'a',companyId:'1',companyRef:company,productId:'malt',side:'sell',status:'open',remaining:0},{id:'b',companyId:'1',companyRef:company,productId:'caps',side:'sell',status:'open',remaining:10,expiresAt:500},{id:'c',companyId:'1',companyRef:company,productId:'malt',side:'sell',status:'partial',remaining:7}],trades:[{id:'t'}],feesCollected:2,requestIds:['r']};const repaired=reconcileLocalExchange(ex,1000);rebuildLocalMarketReservations(ex,[company]);const clean=serializableExchange(ex);if(repaired!==2||ex.orders[0].status!=='filled'||ex.orders[1].status!=='expired'||company.marketReserved.malt!==7||company.marketReserved.caps||clean.orders[0].companyRef!==undefined||clean.orders.length!==3||clean.trades.length!==1||clean.feesCollected!==2)return false;return true;}
if(typeof window!=='undefined'){window.worldLocalPlayerMarketPersistence={save:saveLocalPlayerMarket,restore:restoreLocalPlayerMarket,reconcile:reconcileLocalExchange,rebuildReservations:rebuildLocalMarketReservations,test:runLocalPlayerMarketPersistenceTest};installLocalPlayerMarketPersistence();}
