// WorldProject - sichtbarer Coin-Spielermarkt mit bestätigtem Sofortkauf gegen Spielgeld.
import { PlayerMarketDialog } from './PlayerMarketDialog.js';
import { ensureCoinExchange,placeCoinSellOrder,cancelCoinOrder,coinOrderBook,buyFromCoinSellOrder } from './PlayerCoinMarketExchange.js';
import { COIN_STORE_PACKAGES,beginCoinStoreCheckout } from './CoinStoreCatalog.js';
import { formatMoney } from './CurrencyPresentationBridge.js';
const company=()=>window.worldPlayerCompany||window.worldActiveServerCompany||null;
const world=()=>window.worldProjectWorld||window.worldWorld||window.worldGameState||window;
const n=v=>Number(v||0);
function sellerName(o){return o.companyRef?.name||o.companyRef?.companyName||`Firma ${o.companyId??'–'}`;}
function closeOverlay(x){x?.remove?.();}
function purchaseDialog(dialog,parent,w,c,order){const quote=buyFromCoinSellOrder(w,c,{orderId:order.id,quantity:order.remaining}).quote,ov=dialog.el('div'),box=dialog.el('div');Object.assign(ov.style,{position:'fixed',inset:0,zIndex:35000,background:'rgba(0,0,0,.76)',display:'flex',alignItems:'center',justifyContent:'center',padding:'18px'});Object.assign(box.style,{width:'min(480px,94vw)',background:'#111827',color:'#fff',padding:'18px',border:'1px solid #4b5563',borderRadius:'12px',boxShadow:'0 18px 55px rgba(0,0,0,.45)'});box.append(dialog.el('h2','🪙 Coins kaufen'),dialog.el('div',`Verkäufer: ${sellerName(order)}`));const qty=dialog.input(String(quote.available),'number');qty.min='1';qty.max=String(quote.available);qty.step='1';qty.style.width='100%';const info=dialog.el('div');info.style.margin='12px 0';const refresh=()=>{let q=Math.floor(n(qty.value));if(q<1)q=1;if(q>quote.available)q=quote.available;const total=q*order.unitPrice;info.innerHTML=`Verfügbar: <b>${quote.available} Coins</b><br>Stückpreis: <b>${formatMoney(order.unitPrice)}</b><br>Gewählte Menge: <b>${q} Coins</b><br>Gesamtpreis: <b>${formatMoney(total)}</b><br>Dein Spielgeld: <b>${formatMoney(c.money)}</b>`;buy.disabled=c.money<total;buy.style.opacity=buy.disabled?'.55':'1';};box.append(dialog.el('div','Menge:'),qty,info);const actions=dialog.el('div');Object.assign(actions.style,{display:'flex',gap:'8px',justifyContent:'flex-end'});const cancel=dialog.button('Abbrechen',()=>closeOverlay(ov)),buy=dialog.button('Kauf verbindlich bestätigen',()=>{try{const q=Math.floor(n(qty.value));const result=buyFromCoinSellOrder(w,c,{orderId:order.id,quantity:q,confirmed:true});closeOverlay(ov);alert(`${result.quantity} Coins gekauft.\nSpielgeld bezahlt: ${formatMoney(result.total)}\nNeuer Coin-Bestand: ${result.buyerCoins}`);window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason:'player-coin-market-buy'}}));dialog.render(parent);}catch(e){alert(e.message);dialog.render(parent);}});actions.append(cancel,buy);box.append(actions);ov.append(box);document.body.append(ov);qty.oninput=refresh;refresh();}
const p=PlayerMarketDialog.prototype;
if(!p.__worldCoinMarketUI){p.__worldCoinMarketUI=true;const old=p.render;p.render=function(root){old.call(this,root);const body=root.children?.[1];if(!body)return;const nav=body.firstElementChild;if(nav&&!nav.querySelector('[data-coin-market-btn]')){const b=this.button('🪙 Coins',()=>{this.selected='__coins';this.render(root);});b.dataset.coinMarketBtn='1';nav.append(b);}if(this.selected==='__coins'){body.querySelectorAll(':scope > *:not(:first-child)').forEach(x=>x.remove());this.renderCoinMarket(body,root,company(),world());}};
p.renderCoinMarket=function(body,root,c,w){ensureCoinExchange(w);body.append(this.el('h3','🪙 Coin-Markt'),this.el('div','Coins werden digital sofort übertragen. Spielgeld wird erst nach deiner ausdrücklichen Kaufbestätigung abgezogen.'));if(!c)return body.append(this.el('div','Kein aktiver Betrieb.'));
 const store=this.el('section');Object.assign(store.style,{margin:'14px 0',padding:'12px',border:'1px solid #4b5563',borderRadius:'10px'});store.append(this.el('h3','💳 Coins mit Echtgeld kaufen'),this.el('div','Coin-Gutschrift erfolgt erst nach bestätigter Zahlung durch den späteren Zahlungsanbieter/App-Store.'));const packs=this.el('div');Object.assign(packs.style,{display:'flex',gap:'8px',flexWrap:'wrap',marginTop:'9px'});for(const pack of COIN_STORE_PACKAGES){const text=`${pack.label} · ${pack.priceEuro.toFixed(2).replace('.',',')} €${pack.bonusCoins?` · inkl. ${pack.bonusCoins} Bonus`:''}`;packs.append(this.button(text,()=>{const r=beginCoinStoreCheckout(pack.id,{accountId:window.worldCurrentUser?.id||null,companyId:c.serverCompanyId||c.id||null});if(r?.pendingPaymentIntegration)alert('Das Coin-Paket ist vorbereitet. Die echte Zahlungsanbindung wird vor dem Release angeschlossen; aktuell werden keine Coins oder Euro gebucht.');}));}store.append(packs);body.append(store);
 const book=coinOrderBook(w),asks=book.asks.filter(o=>String(o.companyId)!==String(c.serverCompanyId||c.id));const table=this.el('table');Object.assign(table.style,{width:'100%',borderCollapse:'collapse',marginTop:'12px'});let h=this.el('tr');for(const x of ['Verkäufer','Verfügbare Coins','Preis / Coin','Gesamtwert','Aktion']){const th=this.el('th',x);Object.assign(th.style,{textAlign:'left',padding:'8px',borderBottom:'1px solid #6b7280'});h.append(th);}table.append(h);for(const o of asks){const r=this.el('tr');for(const x of [sellerName(o),String(o.remaining),formatMoney(o.unitPrice),formatMoney(o.remaining*o.unitPrice)]){const td=this.el('td',x);td.style.padding='8px';r.append(td);}const td=this.el('td');td.style.padding='8px';td.append(this.button('Coins kaufen',()=>purchaseDialog(this,root,w,c,o)));r.append(td);table.append(r);}if(!asks.length){const r=this.el('tr'),td=this.el('td','Aktuell bietet kein anderer Spieler Coins an.');td.colSpan=5;td.style.padding='14px';r.append(td);table.append(r);}body.append(table);const sell=this.el('section');sell.style.marginTop='18px';sell.append(this.el('h3','Eigene Coins anbieten'),this.el('div',`Coin-Bestand: ${n(c.coins)} · davon reserviert: ${n(c.marketCoinsReserved)}`));const q=this.input('','number'),price=this.input('','number');q.min='1';q.step='1';q.placeholder='Coins';price.min='.01';price.step='.01';price.placeholder='Spielgeld / Coin';const add=this.button('Coins am Markt anbieten',()=>{try{placeCoinSellOrder(w,c,{quantity:Math.floor(n(q.value)),unitPrice:n(price.value)});this.render(root);window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason:'player-coin-market-sell'}}));}catch(e){alert(e.message);}});sell.append(q,price,add);const mine=ensureCoinExchange(w).orders.filter(o=>o.side==='sell'&&String(o.companyId)===String(c.serverCompanyId||c.id)&&['open','partial'].includes(o.status));for(const o of mine){const row=this.el('div');Object.assign(row.style,{marginTop:'8px',padding:'8px',borderTop:'1px solid #374151'});row.append(this.el('span',`${o.remaining}/${o.quantity} Coins · ${formatMoney(o.unitPrice)} je Coin `),this.button('Angebot zurückziehen',()=>{cancelCoinOrder(w,o.id);this.render(root);window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason:'player-coin-market-cancel'}}));}));sell.append(row);}body.append(sell);};}
export function runPlayerCoinMarketUITest(){return typeof buyFromCoinSellOrder==='function'&&typeof coinOrderBook==='function'&&COIN_STORE_PACKAGES.length>=3;}
