// WorldProject - Spielermarkt fuer Coins gegen Spielgeld. Keine Echtgeld-Auszahlung.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureCoinExchange(world={}){world.coinExchange??={orders:[],trades:[],feesCollected:0,requestIds:[]};return world.coinExchange;}
function freeCoins(company){return Math.max(0,n(company?.coins)-n(company?.marketCoinsReserved));}
export function placeCoinSellOrder(world,company,{quantity,unitPrice,requestId=null}={}){const ex=ensureCoinExchange(world),q=Math.floor(Math.max(0,n(quantity))),p=Math.max(0,n(unitPrice));if(q<=0||p<=0)throw new Error('Ungültige Coin-Verkaufsorder');if(requestId&&ex.requestIds.includes(requestId))return{success:true,idempotent:true};if(freeCoins(company)<q)throw new Error('Nicht genug freie Coins');company.marketCoinsReserved=n(company.marketCoinsReserved)+q;const o={id:`coin-ask-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,side:'sell',companyId:company.serverCompanyId||company.id,companyRef:company,quantity:q,remaining:q,unitPrice:p,status:'open',createdAt:Date.now()};ex.orders.push(o);if(requestId)ex.requestIds.push(requestId);matchCoins(world);return{success:true,order:o};}
export function placeCoinBuyOrder(world,company,{quantity,maxUnitPrice,requestId=null}={}){const ex=ensureCoinExchange(world),q=Math.floor(Math.max(0,n(quantity))),p=Math.max(0,n(maxUnitPrice));if(q<=0||p<=0)throw new Error('Ungültige Coin-Kauforder');if(requestId&&ex.requestIds.includes(requestId))return{success:true,idempotent:true};const reserve=q*p;if(n(company.money)<reserve)throw new Error('Nicht genug Spielgeld für diese Coin-Kauforder');company.marketCashReserved=n(company.marketCashReserved)+reserve;const o={id:`coin-bid-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,side:'buy',companyId:company.serverCompanyId||company.id,companyRef:company,quantity:q,remaining:q,unitPrice:p,status:'open',createdAt:Date.now()};ex.orders.push(o);if(requestId)ex.requestIds.push(requestId);matchCoins(world);return{success:true,order:o};}
export function cancelCoinOrder(world,id){const ex=ensureCoinExchange(world),o=ex.orders.find(x=>x.id===id);if(!o)throw new Error('Coin-Order fehlt');if(!['open','partial'].includes(o.status))return{success:true,idempotent:true};if(o.side==='sell')o.companyRef.marketCoinsReserved=Math.max(0,n(o.companyRef.marketCoinsReserved)-o.remaining);else o.companyRef.marketCashReserved=Math.max(0,n(o.companyRef.marketCashReserved)-o.remaining*o.unitPrice);o.status='cancelled';return{success:true,order:o};}
export function matchCoins(world,{feeRate=.01}={}){const ex=ensureCoinExchange(world),asks=ex.orders.filter(x=>x.side==='sell'&&['open','partial'].includes(x.status)).sort((a,b)=>a.unitPrice-b.unitPrice||a.createdAt-b.createdAt),bids=ex.orders.filter(x=>x.side==='buy'&&['open','partial'].includes(x.status)).sort((a,b)=>b.unitPrice-a.unitPrice||a.createdAt-b.createdAt);while(asks.length&&bids.length&&bids[0].unitPrice>=asks[0].unitPrice){const ask=asks[0],bid=bids[0],seller=ask.companyRef,buyer=bid.companyRef,q=Math.min(ask.remaining,bid.remaining),price=ask.createdAt<=bid.createdAt?ask.unitPrice:bid.unitPrice,total=q*price,fee=total*feeRate;if(freeCoins(seller)+n(seller.marketCoinsReserved)<q){ask.status='cancelled';asks.shift();continue;}if(n(buyer.money)<total){bid.status='cancelled';bids.shift();continue;}seller.coins=Math.max(0,n(seller.coins)-q);seller.marketCoinsReserved=Math.max(0,n(seller.marketCoinsReserved)-q);buyer.coins=n(buyer.coins)+q;buyer.money=n(buyer.money)-total;buyer.marketCashReserved=Math.max(0,n(buyer.marketCashReserved)-q*bid.unitPrice);seller.money=n(seller.money)+total-fee;ex.feesCollected+=fee;ask.remaining-=q;bid.remaining-=q;ask.status=ask.remaining?'partial':'filled';bid.status=bid.remaining?'partial':'filled';const trade={id:`coin-trade-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,quantity:q,unitPrice:price,total,fee,buyerId:bid.companyId,sellerId:ask.companyId,at:Date.now()};ex.trades.push(trade);seller.coinLedger??=[];buyer.coinLedger??=[];seller.coinLedger.push({at:trade.at,type:'market_sell',amount:-q,balance:seller.coins,unitPrice:price});buyer.coinLedger.push({at:trade.at,type:'market_buy',amount:q,balance:buyer.coins,unitPrice:price});if(!ask.remaining)asks.shift();if(!bid.remaining)bids.shift();}return ex;}
export function coinOrderBook(world){const ex=ensureCoinExchange(world);return{asks:ex.orders.filter(x=>x.side==='sell'&&['open','partial'].includes(x.status)).sort((a,b)=>a.unitPrice-b.unitPrice),bids:ex.orders.filter(x=>x.side==='buy'&&['open','partial'].includes(x.status)).sort((a,b)=>b.unitPrice-a.unitPrice),lastTrades:ex.trades.slice(-20)};}
export function runPlayerCoinMarketTest(){const w={},seller={id:'s',coins:100,money:0},buyer={id:'b',coins:0,money:1000};placeCoinSellOrder(w,seller,{quantity:20,unitPrice:5});placeCoinBuyOrder(w,buyer,{quantity:20,maxUnitPrice:5});if(seller.coins!==80||buyer.coins!==20||buyer.money!==900||seller.money<=0)throw new Error('Coin-Spielermarkt bucht falsch');return true;}
if(typeof window!=='undefined')window.worldPlayerCoinMarket={ensure:ensureCoinExchange,sell:placeCoinSellOrder,buy:placeCoinBuyOrder,cancel:cancelCoinOrder,match:matchCoins,book:coinOrderBook,test:runPlayerCoinMarketTest};
