// WorldProject - verbindlicher Direktkauf physischer Ware aus einer Spieler-Verkaufsorder.
import { ensureExchange } from './PlayerMarketExchange.js';
import { createMarketGoodsDelivery } from './PlayerMarketGoodsDelivery.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const dirty=(reason,detail={})=>{if(typeof window==='undefined')return;window.dispatchEvent(new CustomEvent('world:player-market-dirty',{detail:{reason,...detail}}));window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason,...detail}}));};
function takeGoods(c,id,q){let left=q,operational=Boolean(c?.operationalSupplyState?.warehouseStock);for(const bag of Object.values(c?.operationalSupplyState?.warehouseStock||{})){if(left<=0)break;const have=n(bag?.[id]),take=Math.min(left,have);if(take>0){bag[id]=have-take;left-=take;}}if(operational)return;c.finishedGoods??={};c.inventory??={};if(left>0){const take=Math.min(left,n(c.finishedGoods[id]));c.finishedGoods[id]=n(c.finishedGoods[id])-take;left-=take;}if(left>0){c.inventory[id]=Math.max(0,n(c.inventory[id])-left);}}
export function goodsPurchaseQuote(order,buyer,quantity){if(!order||order.side!=='sell'||!['open','partial'].includes(order.status))throw new Error('Angebot nicht mehr verfuegbar');const q=Math.min(Math.max(.01,n(quantity)),n(order.remaining)),total=q*n(order.unitPrice);return{quantity:q,unitPrice:n(order.unitPrice),total,balance:n(buyer?.money),canAfford:n(buyer?.money)>=total,available:n(order.remaining)};}
export function buyGoodsFromSellOrder(world,buyer,orderId,{quantity,confirmed=false,distanceKm=80,now=Date.now(),feeRate=.01}={}){const ex=ensureExchange(world),o=ex.orders.find(x=>x.id===orderId),q=goodsPurchaseQuote(o,buyer,quantity);if(!confirmed)return{success:false,requiresConfirmation:true,quote:q};if(!q.canAfford)throw new Error('Nicht genug Spielgeld');const seller=o.companyRef;if(!seller)throw new Error('Verkaeuferbetrieb nicht verfuegbar');const fee=q.total*feeRate;buyer.money=n(buyer.money)-q.total;seller.money=n(seller.money)+q.total-fee;takeGoods(seller,o.productId,q.quantity);seller.marketReserved??={};seller.marketReserved[o.productId]=Math.max(0,n(seller.marketReserved[o.productId])-q.quantity);o.remaining=Math.max(0,n(o.remaining)-q.quantity);o.status=o.remaining?'partial':'filled';ex.feesCollected=n(ex.feesCollected)+fee;const trade={id:`trade-${now}-${Math.random().toString(36).slice(2,6)}`,productId:o.productId,quantity:q.quantity,unitPrice:q.unitPrice,total:q.total,fee,buyerId:buyer.serverCompanyId||buyer.id,sellerId:o.companyId,at:now,status:'transporting'};ex.trades.push(trade);const delivery=createMarketGoodsDelivery(buyer,{trade,productId:o.productId,quantity:q.quantity,distanceKm,now});trade.deliveryId=delivery.id;dirty('player-market-direct-purchase',{tradeId:trade.id,deliveryId:delivery.id,orderId:o.id});return{success:true,trade,delivery,quote:q};}
export function runPlayerMarketDirectGoodsPurchaseTest(){const w={},seller={id:'s',money:0,inventory:{malt:100},marketReserved:{malt:100}},buyer={id:'b',money:1000,inventory:{}},ex=ensureExchange(w);ex.orders.push({id:'ask1',side:'sell',companyId:'s',companyRef:seller,productId:'malt',quantity:100,remaining:100,unitPrice:2,status:'open'});const preview=buyGoodsFromSellOrder(w,buyer,'ask1',{quantity:25});if(!preview.requiresConfirmation||buyer.money!==1000||buyer.inventory.malt)throw new Error('Marktkauf bucht vor Bestaetigung');const r=buyGoodsFromSellOrder(w,buyer,'ask1',{quantity:25,confirmed:true,now:1000});if(buyer.money!==950||buyer.inventory.malt||seller.inventory.malt!==75||r.delivery.status!=='in_transit'||ex.orders[0].remaining!==75)throw new Error('Direktkauf/Transport fehlerhaft');const w2={},seller2={id:'s2',money:0,operationalSupplyState:{warehouseStock:{raw:{malt:100},packaging:{},cold:{},finished:{}}},inventory:{malt:100},marketReserved:{malt:25}},buyer2={id:'b2',money:1000,inventory:{}},ex2=ensureExchange(w2);ex2.orders.push({id:'ask2',side:'sell',companyId:'s2',companyRef:seller2,productId:'malt',quantity:25,remaining:25,unitPrice:2,status:'open'});buyGoodsFromSellOrder(w2,buyer2,'ask2',{quantity:25,confirmed:true,now:2000});if(seller2.operationalSupplyState.warehouseStock.raw.malt!==75||seller2.inventory.malt!==100)throw new Error('Operativer Bestand wird beim Direktkauf doppelt abgezogen');return true;}
if(typeof window!=='undefined')window.worldPlayerMarketDirectGoodsPurchase={quote:goodsPurchaseQuote,buy:buyGoodsFromSellOrder,test:runPlayerMarketDirectGoodsPurchaseTest};