// WorldProject - physische Marktware wird nach dem Kauf transportiert und erst bei Ankunft eingelagert.
// Wichtig: Marktlieferungen leben nur in marketDeliveries. So kann der allgemeine Lieferantenprozessor
// dieselbe Ware nicht ein zweites Mal einlagern.
import { hasOperationalStock, addOperational, stockZoneFor } from './UnifiedOperationalStockBridge.js';
import { timeMs } from './TimeValueUtils.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const active=s=>['paid','in_transit','transporting'].includes(String(s||'').toLowerCase());
const arrivalMs=d=>timeMs(d?.arrivalTime)||timeMs(d?.arrivalAt);
function markTradeDelivered(delivery,now){if(typeof window==='undefined'||!delivery?.tradeId)return;const w=window.worldProjectWorld||window.worldWorld||window.worldGameState||window,trade=w?.exchange?.trades?.find?.(x=>x.id===delivery.tradeId);if(trade){trade.status='delivered';trade.deliveredAt=now;}}
export function createMarketGoodsDelivery(company,{trade,productId,quantity,distanceKm=80,now=Date.now(),hours=null}={}){if(!company||!productId||n(quantity)<=0)throw new Error('Marktlieferung unvollstaendig');company.marketDeliveries??=[];const totalHours=Math.max(.25,n(hours,Math.max(.5,n(distanceKm)/60+.5))),arrivalTime=new Date(now+totalHours*3600000),delivery={id:`market-delivery-${trade?.id||Date.now()}-${Math.random().toString(36).slice(2,6)}`,kind:'market_goods',tradeId:trade?.id||null,productId,material:productId,itemId:productId,label:`Marktkauf: ${productId}`,quantity:n(quantity),amount:n(quantity),distanceKm:n(distanceKm),orderedAt:now,departureTime:new Date(now),arrivalTime,totalHours,status:'in_transit',receivedQuantity:0,remainingQuantity:n(quantity)};company.marketDeliveries.push(delivery);return delivery;}
export function receiveArrivedMarketGoods(company,delivery,{now=Date.now()}={}){if(!company||!delivery)throw new Error('Marktlieferung fehlt');if(delivery.status==='stored')return{success:true,deduplicated:true,received:0};const end=arrivalMs(delivery);if(end>now)throw new Error('Marktware ist noch unterwegs');if(!end)throw new Error('Marktlieferung hat keine gültige Ankunftszeit');const q=Math.max(0,n(delivery.quantity)-n(delivery.receivedQuantity));let zone='legacy';if(hasOperationalStock(company)){zone=stockZoneFor(delivery.productId);addOperational(company,delivery.productId,q);}else{company.inventory??={};company.inventory[delivery.productId]=n(company.inventory[delivery.productId])+q;}delivery.receivedQuantity=n(delivery.receivedQuantity)+q;delivery.remainingQuantity=0;delivery.status='stored';delivery.storedAt=now;delivery.storageZone=zone;markTradeDelivered(delivery,now);return{success:true,deduplicated:false,received:q,productId:delivery.productId,zone};}
export function processArrivedMarketGoods(company={},now=Date.now()){const results=[];for(const d of company.marketDeliveries||[]){if(!active(d.status))continue;const end=arrivalMs(d);if(end&&end<=now)results.push(receiveArrivedMarketGoods(company,d,{now}));}if(results.length&&typeof window!=='undefined'){window.dispatchEvent(new CustomEvent('world:player-market-dirty',{detail:{reason:'market-goods-arrived',count:results.length}}));window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason:'market-goods-arrived',count:results.length}}));}return results;}
let timer=null;export function installMarketGoodsDeliveryRuntime(){if(typeof window==='undefined'||timer)return false;const run=()=>{const c=window.worldPlayerCompany||window.worldActiveServerCompany;if(c)processArrivedMarketGoods(c,Date.now());};timer=setInterval(run,15000);window.addEventListener('worldproject:company-switched',run);setTimeout(run,0);return true;}
export function runPlayerMarketGoodsDeliveryTest(){const now=1000000,c={inventory:{},supplierOrders:[],operationalSupplyState:{warehouseStock:{raw:{},packaging:{},cold:{},finished:{}}}},d=createMarketGoodsDelivery(c,{productId:'malt',quantity:100,distanceKm:60,now,hours:2});if(c.supplierOrders.length)throw new Error('Marktlieferung wurde unsicher in Lieferantenaufträge gespiegelt');if(c.inventory.malt||c.operationalSupplyState.warehouseStock.raw.malt)throw new Error('Marktware wurde vor Ankunft eingelagert');let early=false;try{receiveArrivedMarketGoods(c,d,{now:now+1000});}catch{early=true;}if(!early)throw new Error('Vorzeitiger Wareneingang erlaubt');d.arrivalTime=d.arrivalTime.toISOString();const r=receiveArrivedMarketGoods(c,d,{now:now+2*3600000});if(r.received!==100||c.operationalSupplyState.warehouseStock.raw.malt!==100||c.inventory.malt||d.status!=='stored')throw new Error('Persistierter Markt-Wareneingang fehlerhaft');const again=receiveArrivedMarketGoods(c,d,{now:now+3*3600000});if(!again.deduplicated||c.operationalSupplyState.warehouseStock.raw.malt!==100)throw new Error('Marktware wird bei Wiederholung doppelt eingelagert');return true;}
if(typeof window!=='undefined'){window.worldPlayerMarketGoodsDelivery={create:createMarketGoodsDelivery,receive:receiveArrivedMarketGoods,process:processArrivedMarketGoods,test:runPlayerMarketGoodsDeliveryTest};installMarketGoodsDeliveryRuntime();}