// WorldProject - physische Marktware wird nach dem Kauf transportiert und erst bei Ankunft eingelagert.
import { hasOperationalStock, addOperational, stockZoneFor } from './UnifiedOperationalStockBridge.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const active=s=>['paid','in_transit','transporting'].includes(String(s||'').toLowerCase());
export function createMarketGoodsDelivery(company,{trade,productId,quantity,distanceKm=80,now=Date.now(),hours=null}={}){if(!company||!productId||n(quantity)<=0)throw new Error('Marktlieferung unvollstaendig');company.marketDeliveries??=[];const totalHours=Math.max(.25,n(hours,Math.max(.5,n(distanceKm)/60+.5))),arrivalTime=new Date(now+totalHours*3600000),delivery={id:`market-delivery-${trade?.id||Date.now()}-${Math.random().toString(36).slice(2,6)}`,kind:'market_goods',tradeId:trade?.id||null,productId,material:productId,label:`Marktkauf: ${productId}`,quantity:n(quantity),distanceKm:n(distanceKm),orderedAt:now,departureTime:new Date(now),arrivalTime,totalHours,status:'in_transit',receivedQuantity:0,remainingQuantity:n(quantity)};company.marketDeliveries.push(delivery);company.supplierOrders??=[];company.supplierOrders.push(delivery);return delivery;}
export function receiveArrivedMarketGoods(company,delivery,{now=Date.now()}={}){if(!company||!delivery)throw new Error('Marktlieferung fehlt');if(delivery.status==='stored')return{success:true,deduplicated:true,received:0};const end=delivery.arrivalTime instanceof Date?delivery.arrivalTime.getTime():n(delivery.arrivalTime??delivery.arrivalAt);if(end>now)throw new Error('Marktware ist noch unterwegs');const q=Math.max(0,n(delivery.quantity)-n(delivery.receivedQuantity));let zone='legacy';if(hasOperationalStock(company)){zone=stockZoneFor(delivery.productId);addOperational(company,delivery.productId,q);}else{company.inventory??={};company.inventory[delivery.productId]=n(company.inventory[delivery.productId])+q;}delivery.receivedQuantity=n(delivery.receivedQuantity)+q;delivery.remainingQuantity=0;delivery.status='stored';delivery.storedAt=now;delivery.storageZone=zone;return{success:true,deduplicated:false,received:q,productId:delivery.productId,zone};}
export function processArrivedMarketGoods(company={},now=Date.now()){const results=[];for(const d of company.marketDeliveries||[]){if(!active(d.status))continue;const end=d.arrivalTime instanceof Date?d.arrivalTime.getTime():n(d.arrivalTime??d.arrivalAt);if(end&&end<=now)results.push(receiveArrivedMarketGoods(company,d,{now}));}if(results.length&&typeof window!=='undefined')window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason:'market-goods-arrived',count:results.length}}));return results;}
let timer=null;export function installMarketGoodsDeliveryRuntime(){if(typeof window==='undefined'||timer)return false;const run=()=>{const c=window.worldPlayerCompany||window.worldActiveServerCompany;if(c)processArrivedMarketGoods(c,Date.now());};timer=setInterval(run,15000);window.addEventListener('worldproject:company-switched',run);setTimeout(run,0);return true;}
export function runPlayerMarketGoodsDeliveryTest(){const now=1000000,c={inventory:{},operationalSupplyState:{warehouseStock:{raw:{},packaging:{},cold:{},finished:{}}}},d=createMarketGoodsDelivery(c,{productId:'malt',quantity:100,distanceKm:60,now,hours:2});if(c.inventory.malt||c.operationalSupplyState.warehouseStock.raw.malt)throw new Error('Marktware wurde vor Ankunft eingelagert');let early=false;try{receiveArrivedMarketGoods(c,d,{now:now+1000});}catch{early=true;}if(!early)throw new Error('Vorzeitiger Wareneingang erlaubt');const r=receiveArrivedMarketGoods(c,d,{now:now+2*3600000});if(r.received!==100||c.operationalSupplyState.warehouseStock.raw.malt!==100||c.inventory.malt||d.status!=='stored')throw new Error('Markt-Wareneingang fehlerhaft');return true;}
if(typeof window!=='undefined'){window.worldPlayerMarketGoodsDelivery={create:createMarketGoodsDelivery,receive:receiveArrivedMarketGoods,process:processArrivedMarketGoods,test:runPlayerMarketGoodsDeliveryTest};installMarketGoodsDeliveryRuntime();}
