// WorldProject – B2B-Marktplatz zwischen Spieler-/NPC-Betrieben.
import { worldCurrency } from './WorldCurrencySystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const dirty=(reason,detail={})=>{if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('world:player-market-dirty',{detail:{reason,...detail}}));};
export function ensureExchange(world={}){world.exchange??={orders:[],trades:[],feesCollected:0,requestIds:[]};return world.exchange;}
function operationalBags(company){const stock=company?.operationalSupplyState?.warehouseStock||{};return ['raw','packaging','cold','finished'].map(zone=>stock?.[zone]).filter(Boolean);}
function hasOperationalStock(company){return Boolean(company?.operationalSupplyState?.warehouseStock);}
export function marketStock(company,productId){const op=operationalBags(company).reduce((sum,bag)=>sum+n(bag?.[productId]),0),legacy=hasOperationalStock(company)?0:n(company?.inventory?.[productId])+n(company?.finishedGoods?.[productId]);return Math.max(0,op+legacy-n(company?.marketReserved?.[productId]));}
export function placeSellOrder(world,company,{productId,quantity,unitPrice,expiresAt=null,requestId=null}={}){const ex=ensureExchange(world),q=Math.max(0,n(quantity)),p=Math.max(0,n(unitPrice));if(!productId||q<=0||p<=0)throw new Error('Ungültige Verkaufsorder');if(requestId&&ex.requestIds.includes(requestId))return{success:true,idempotent:true};company.marketReserved??={};const have=marketStock(company,productId);if(have<q)throw new Error('Nicht genug freie Ware');company.marketReserved[productId]=n(company.marketReserved[productId])+q;const order={id:`ask-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,side:'sell',companyId:company.serverCompanyId||company.id,companyRef:company,productId,quantity:q,remaining:q,unitPrice:p,createdAt:Date.now(),expiresAt,status:'open'};ex.orders.push(order);if(requestId)ex.requestIds.push(requestId);matchProduct(world,productId);dirty('sell-order',{orderId:order.id});return{success:true,order};}
export function placeBuyOrder(world,company,{productId,quantity,maxUnitPrice,expiresAt=null,requestId=null}={}){const ex=ensureExchange(world),q=Math.max(0,n(quantity)),p=Math.max(0,n(maxUnitPrice));if(!productId||q<=0||p<=0)throw new Error('Ungültige Kauforder');if(n(company.money)<q*p)throw new Error('Kauforder übersteigt Liquidität');company.marketCashReserved=n(company.marketCashReserved)+q*p;const order={id:`bid-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,side:'buy',companyId:company.serverCompanyId||company.id,companyRef:company,productId,quantity:q,remaining:q,unitPrice:p,createdAt:Date.now(),expiresAt,status:'open'};ex.orders.push(order);if(requestId)ex.requestIds.push(requestId);matchProduct(world,productId);dirty('buy-order',{orderId:order.id});return{success:true,order};}
export function placeLocalSellOrder(world,company,args={}){const local=n(args.unitPrice),base=worldCurrency.toBase(local,args.currency||worldCurrency.currency);return placeSellOrder(world,company,{...args,unitPrice:base});}
export function placeLocalBuyOrder(world,company,args={}){const local=n(args.maxUnitPrice),base=worldCurrency.toBase(local,args.currency||worldCurrency.currency);return placeBuyOrder(world,company,{...args,maxUnitPrice:base});}
export function cancelMarketOrder(world,orderId){const ex=ensureExchange(world),o=ex.orders.find(x=>x.id===orderId);if(!o)throw new Error('Order fehlt');if(o.status!=='open'&&o.status!=='partial')return{success:true,idempotent:true};if(o.side==='sell')o.companyRef.marketReserved[o.productId]=Math.max(0,n(o.companyRef.marketReserved[o.productId])-o.remaining);else o.companyRef.marketCashReserved=Math.max(0,n(o.companyRef.marketCashReserved)-o.remaining*o.unitPrice);o.status='cancelled';dirty('cancel-order',{orderId});return{success:true,order:o};}
function takeGoods(c,id,q){let left=q;for(const bag of operationalBags(c)){if(left<=0)break;const available=n(bag[id]),take=Math.min(left,available);if(take>0){bag[id]=available-take;left-=take;}}if(hasOperationalStock(c))return;c.finishedGoods??={};c.inventory??={};if(left>0){const take=Math.min(left,n(c.finishedGoods[id]));c.finishedGoods[id]=n(c.finishedGoods[id])-take;left-=take;}if(left>0){c.inventory[id]=Math.max(0,n(c.inventory[id])-left);left=0;}}
function matchProduct(world,productId,{feeRate=.01}={}){const ex=ensureExchange(world),asks=ex.orders.filter(x=>x.productId===productId&&x.side==='sell'&&['open','partial'].includes(x.status)).sort((a,b)=>a.unitPrice-b.unitPrice||a.createdAt-b.createdAt),bids=ex.orders.filter(x=>x.productId===productId&&x.side==='buy'&&['open','partial'].includes(x.status)).sort((a,b)=>b.unitPrice-a.unitPrice||a.createdAt-b.createdAt);let matched=false;while(asks.length&&bids.length&&bids[0].unitPrice>=asks[0].unitPrice){matched=true;const ask=asks[0],bid=bids[0],q=Math.min(ask.remaining,bid.remaining),price=ask.createdAt<=bid.createdAt?ask.unitPrice:bid.unitPrice,buyer=bid.companyRef,seller=ask.companyRef,total=q*price,fee=total*feeRate;if(n(buyer.money)<total){bid.status='cancelled';bids.shift();continue;}takeGoods(seller,productId,q);seller.marketReserved[productId]=Math.max(0,n(seller.marketReserved[productId])-q);buyer.marketCashReserved=Math.max(0,n(buyer.marketCashReserved)-q*bid.unitPrice);buyer.money=n(buyer.money)-total;buyer.inventory??={};buyer.inventory[productId]=n(buyer.inventory[productId])+q;seller.money=n(seller.money)+total-fee;ex.feesCollected+=fee;ask.remaining-=q;bid.remaining-=q;ask.status=ask.remaining?'partial':'filled';bid.status=bid.remaining?'partial':'filled';ex.trades.push({id:`trade-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,productId,quantity:q,unitPrice:price,total,fee,buyerId:bid.companyId,sellerId:ask.companyId,at:Date.now()});if(!ask.remaining)asks.shift();if(!bid.remaining)bids.shift();}if(matched)dirty('match',{productId});return ex;}
export function orderBook(world,productId){const ex=ensureExchange(world);return{asks:ex.orders.filter(x=>x.productId===productId&&x.side==='sell'&&['open','partial'].includes(x.status)).sort((a,b)=>a.unitPrice-b.unitPrice),bids:ex.orders.filter(x=>x.productId===productId&&x.side==='buy'&&['open','partial'].includes(x.status)).sort((a,b)=>b.unitPrice-a.unitPrice),lastTrades:ex.trades.filter(x=>x.productId===productId).slice(-20)};}
export function runPlayerMarketOperationalStockTest(){const c={operationalSupplyState:{warehouseStock:{raw:{malt:100},packaging:{caps:2000},cold:{},finished:{beer:50}}},inventory:{malt:100},finishedGoods:{beer:50},marketReserved:{}};if(marketStock(c,'caps')!==2000||marketStock(c,'malt')!==100||marketStock(c,'beer')!==50)throw new Error('Operativer Marktbestand wird falsch ermittelt oder doppelt gezählt');const w={};placeSellOrder(w,c,{productId:'caps',quantity:1000,unitPrice:.02});if(c.marketReserved.caps!==1000)throw new Error('Operative Ware kann nicht am Markt reserviert werden');cancelMarketOrder(w,w.exchange.orders[0].id);if(c.marketReserved.caps!==0)throw new Error('Marktreservierung wird nicht korrekt aufgehoben');return true;}
if(typeof window!=='undefined')window.worldPlayerMarket={ensure:ensureExchange,sell:placeSellOrder,buy:placeBuyOrder,sellLocal:placeLocalSellOrder,buyLocal:placeLocalBuyOrder,cancel:cancelMarketOrder,book:orderBook,stock:marketStock};