// WorldProject - Premium Mindestbestand / automatische Nachbestellung
// Datengetrieben und spaeter um weitere Regeln erweiterbar.
export class PremiumInventoryAutomationSystem{
 constructor({premium,contentRegistry=null}={}){this.premium=premium;this.registry=contentRegistry;this.rules=[];this.seq=1;this.orders=[];}
 addRule({account,material,minStock,reorderTo,supplierId,maxOrderValue=0,enabled=true}={}){if(!this.premium.benefit(account,"automaticReorder"))throw new Error("Automatische Nachbestellung ist nur mit Premium verfuegbar");const rule={id:this.seq++,material,minStock:Math.max(0,Number(minStock||0)),reorderTo:Math.max(Number(minStock||0),Number(reorderTo||minStock||0)),supplierId,maxOrderValue:Math.max(0,Number(maxOrderValue||0)),enabled:Boolean(enabled),pausedPremium:false};this.rules.push(rule);return rule;}
 syncPremium(account){const active=Boolean(this.premium.benefit(account,"automaticReorder"));for(const r of this.rules)r.pausedPremium=!active;return {active,paused:this.rules.filter(r=>r.pausedPremium).length};}
 supplier(id){return this.registry?.get?.("suppliers",id)||this.registry?.list?.("suppliers")?.find?.(x=>x.id===id)||null;}
 evaluate({account,stock={},company=null,placeOrder=null}={}){this.syncPremium(account);const made=[];if(!this.premium.benefit(account,"automaticReorder"))return {orders:made,reason:"premium_inactive"};for(const r of this.rules.filter(x=>x.enabled&&!x.pausedPremium)){const current=Number(stock[r.material]||0);if(current>=r.minStock)continue;const qty=Math.max(0,r.reorderTo-current),s=this.supplier(r.supplierId),unit=Number(s?.prices?.[r.material]||0),value=qty*unit;if(!s||!s.materials?.includes(r.material)){r.lastError="Lieferant fuehrt Rohstoff nicht";continue;}if(r.maxOrderValue>0&&value>r.maxOrderValue){r.lastError=`Budgetgrenze ${r.maxOrderValue.toFixed(2)} EUR ueberschritten`;continue;}if(company&&Number(company.money||0)<value){r.lastError="Nicht genug Betriebsgeld";continue;}const order={id:`AUTO-${Date.now()}-${r.id}`,ruleId:r.id,material:r.material,quantity:qty,supplierId:r.supplierId,estimatedValue:value,status:"created",createdAt:Date.now()};if(typeof placeOrder==="function")placeOrder(order);this.orders.push(order);r.lastOrderAt=order.createdAt;r.lastError=null;made.push(order);}return {orders:made};}
}

export function runPremiumInventoryAutomationTest(premium,registry){const a={premiumUntil:Date.now()+86400000},s=new PremiumInventoryAutomationSystem({premium,contentRegistry:registry}),sup=registry.list("suppliers").find(x=>x.materials?.includes("malt"));if(!sup)return true;s.addRule({account:a,material:"malt",minStock:100,reorderTo:500,supplierId:sup.id,maxOrderValue:1000});const r=s.evaluate({account:a,stock:{malt:50},company:{money:10000}});if(r.orders.length!==1||r.orders[0].quantity!==450)throw new Error("Premium-Nachbestellung fehlerhaft");a.premiumUntil=0;if(s.evaluate({account:a,stock:{malt:0},company:{money:10000}}).orders.length)throw new Error("Nachbestellung lief ohne Premium weiter");console.log("✅ PREMIUM MINDESTBESTAND/NACHBESTELLUNG/BUDGET TEST ERFOLGREICH");return true;}
