// WorldProject - Premium-Produktionswarteschlange
// Standard: keine Vorausplanung. Premium: bis zu drei Folgeauftraege.
import { PremiumEntitlementSystem } from "./PremiumEntitlementSystem.js";

export class PremiumProductionQueueSystem{
 constructor({premium=new PremiumEntitlementSystem(),planner=null,workforceCheck=null}={}){this.premium=premium;this.planner=planner;this.workforceCheck=workforceCheck;this.entries=[];this.seq=1;}
 queued(){return this.entries.filter(e=>e.status==="queued");}
 pausedPremium(){return this.entries.filter(e=>e.status==="paused_premium");}
 add({account,recipe,batches=1,metadata={}}={}){const limit=this.premium.productionQueueLimit(account);if(limit<=0)throw new Error("Produktionswarteschlange ist nur mit Premium verfuegbar");if(this.queued().length>=limit)throw new Error(`Maximal ${limit} vorausgeplante Produktionen erlaubt`);const e={id:this.seq++,recipe,batches:Math.max(1,Number(batches||1)),metadata,status:"queued",createdAt:Date.now(),lastBlockReason:null,startedJobId:null};this.entries.push(e);return e;}
 remove(id){const e=this.entries.find(x=>x.id===id&&["queued","paused_premium"].includes(x.status));if(!e)return false;e.status="removed";e.removedAt=Date.now();return true;}
 syncPremium(account){if(this.premium.productionQueueLimit(account)>0)return {paused:0};let paused=0;for(const e of this.queued()){e.status="paused_premium";e.pausedAt=Date.now();paused++;}return {paused};}
 restoreAfterPremium(account,{confirm=false}={}){if(this.premium.productionQueueLimit(account)<=0)return {restored:[],reason:"premium_inactive"};if(!confirm)return {restored:[],needsConfirmation:this.pausedPremium().length>0};const restored=[];let free=Math.max(0,this.premium.productionQueueLimit(account)-this.queued().length);for(const e of this.pausedPremium()){if(free<=0)break;e.status="queued";e.restoredAt=Date.now();restored.push(e);free--;}return {restored,needsConfirmation:false};}
 canStartEntry(entry,context={}){if(typeof this.workforceCheck==="function"){const r=this.workforceCheck(entry,context);if(r===false)return {ok:false,reason:"Personal nicht verfuegbar"};if(r&&r.ok===false)return r;}return {ok:true};}
 process({account,now=Date.now(),context={}}={}){this.syncPremium(account);if(this.premium.productionQueueLimit(account)<=0)return {started:null,reason:"premium_inactive"};if(!this.planner)throw new Error("ProductionPlanner fehlt");const running=this.planner.queue?.find(j=>j.status==="running");if(running)return {started:null,reason:"production_running",running};const entry=this.queued()[0];if(!entry)return {started:null,reason:"queue_empty"};const staff=this.canStartEntry(entry,context);if(!staff.ok){entry.lastBlockReason=staff.reason||"Personal fehlt";return {started:null,reason:entry.lastBlockReason};}try{const job=this.planner.start(entry.recipe,entry.batches,now);entry.status="started";entry.startedAt=now;entry.startedJobId=job.id;entry.lastBlockReason=null;return {started:job,entry};}catch(e){entry.lastBlockReason=e.message;return {started:null,reason:e.message,entry};}}
 advance({account,now=Date.now(),context={}}={}){if(!this.planner)throw new Error("ProductionPlanner fehlt");this.planner.advance(now);for(const e of this.entries.filter(x=>x.status==="started")){const job=this.planner.queue.find(j=>j.id===e.startedJobId);if(job?.status==="finished"){e.status="finished";e.finishedAt=now;}}return this.process({account,now,context});}
}

export function runPremiumProductionQueueTest(){const premium=new PremiumEntitlementSystem(),account={premiumUntil:Date.now()+86400000},warehouse={stock:{raw:{malt:300},packaging:{},finished:{},cold:{}},zoneFor(){return "raw";},has(req){const missing={};for(const[k,v]of Object.entries(req))if(Number(this.stock.raw[k]||0)<v)missing[k]=v-Number(this.stock.raw[k]||0);return {ok:!Object.keys(missing).length,missing};},consume(req){const c=this.has(req);if(!c.ok)return c;for(const[k,v]of Object.entries(req))this.stock.raw[k]-=v;return {ok:true,missing:{}};},free(){return 10000;},addFinished(p,q){this.stock.finished[p]=Number(this.stock.finished[p]||0)+q;}},machine={id:1,type:"brewhouse",busy:false},planner={queue:[],seq:1,start(recipe,batches,now){if(machine.busy)throw new Error("Maschine belegt");const req={malt:100*batches},c=warehouse.consume(req);if(!c.ok)throw new Error("Rohstoffe fehlen");machine.busy=true;const j={id:this.seq++,recipe,plan:{output:1000*batches},machine,status:"running",finishAt:now+60000};this.queue.push(j);return j;},advance(now){for(const j of this.queue)if(j.status==="running"&&now>=j.finishAt){j.status="finished";machine.busy=false;warehouse.addFinished(j.recipe.product,j.plan.output);}return this.queue;}},q=new PremiumProductionQueueSystem({premium,planner,workforceCheck:()=>({ok:true})}),recipe={id:"beer",product:"beer"};q.add({account,recipe});q.add({account,recipe});q.add({account,recipe});let blocked=false;try{q.add({account,recipe});}catch{blocked=true;}if(!blocked)throw new Error("Premium-Queue-Limit fehlerhaft");const first=q.process({account,now:0});if(!first.started)throw new Error("Erste Queue-Produktion startete nicht");q.advance({account,now:60000});q.advance({account,now:120000});q.advance({account,now:180000});if(warehouse.stock.finished.beer!==3000)throw new Error("Produktionswarteschlange arbeitete nicht automatisch ab");const q2=new PremiumProductionQueueSystem({premium,planner:{queue:[]}});q2.add({account,recipe});account.premiumUntil=0;q2.syncPremium(account);if(q2.pausedPremium().length!==1)throw new Error("Queue wurde bei Premiumende nicht pausiert");console.log("✅ PREMIUM-PRODUKTIONSWARTESCHLANGE 0→3 + AUTO-FOLGESTART + PAUSE BEI ABLAUF ERFOLGREICH");return true;}
