// ORVUNO – zentrale Premium-, Coin- und Bonusansicht.
import { PremiumEntitlementSystem } from './PremiumEntitlementSystem.js';
const premium=new PremiumEntitlementSystem();
const account=()=>window.worldCurrentUser||window.worldAccount||{};
const euro=n=>Number(n||0).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
const num=n=>Number(n||0).toLocaleString('de-DE');
export const PremiumOffers=Object.freeze([{id:'premium_4w',label:'4 Wochen Premium',sub:'Ideal zum Ausprobieren',priceEuro:3.99,durationDays:28,icon:'⭐',badge:'TESTEN'},{id:'premium_3m',label:'3 Monate Premium',sub:'Spare gegenüber 4 Wochen',priceEuro:9.99,durationDays:90,icon:'🏆',badge:'BELIEBT'},{id:'premium_6m',label:'6 Monate Premium',sub:'Für aktive Unternehmer',priceEuro:17.99,durationDays:180,icon:'👑',badge:'TOP'},{id:'premium_12m',label:'12 Monate Premium',sub:'Ein ganzes Jahr Komfort',priceEuro:29.99,durationDays:365,icon:'💎',badge:'BESTER WERT'}]);
export const CoinOffers=Object.freeze([{id:'coins_100',coins:100,base:100,bonus:0,priceEuro:.99,icon:'🪙',badge:'STARTER'},{id:'coins_550',coins:550,base:500,bonus:50,priceEuro:4.99,icon:'💰',badge:'KLEIN'},{id:'coins_1200',coins:1200,base:1000,bonus:200,priceEuro:9.99,icon:'📦',badge:'BELIEBT'},{id:'coins_2600',coins:2600,base:2000,bonus:600,priceEuro:19.99,icon:'💼',badge:'VIEL'},{id:'coins_6000',coins:6000,base:4000,bonus:2000,priceEuro:39.99,icon:'🗄️',badge:'TOP ANGEBOT'},{id:'coins_13000',coins:13000,base:8000,bonus:5000,priceEuro:79.99,icon:'🧳',badge:'BESTER DEAL'},{id:'coins_26000',coins:26000,base:15000,bonus:11000,priceEuro:149.99,icon:'🏗️',badge:'EXTRA VIEL'},{id:'coins_50000',coins:50000,base:25000,bonus:25000,priceEuro:249.99,icon:'🏦',badge:'MAXIMUM'}]);
export const MoneyOffers=Object.freeze([{id:'money_65000',money:65000,coins:200,icon:'🪙',badge:'KLEIN'},{id:'money_200000',money:200000,coins:525,icon:'💰',badge:'START'},{id:'money_450000',money:450000,coins:1150,icon:'💼',badge:'BELIEBT'},{id:'money_1000000',money:1000000,coins:2400,icon:'💵',badge:'GROSS'},{id:'money_2800000',money:2800000,coins:6500,icon:'🏦',badge:'PROFI'},{id:'money_7500000',money:7500000,coins:15000,icon:'🏭',badge:'MAXIMUM'}]);
function feedback(text,type='info',title='Premium & Coins'){const api=window.worldActionFeedback;if(api?.show)return api.show(text,{type,title});if(api?.feedback)return api.feedback(text,{type,title});console[type==='error'?'error':'log'](text);}
async function rpc(name,args={}){const a=window.worldAccounts?.authApi;if(!a)throw new Error('Serververbindung ist noch nicht bereit');const token=await a.ensureAccessToken();if(!token)throw new Error('Bitte zuerst anmelden');const r=await fetch(`${a.baseUrl}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:a.publishableKey,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(args)});const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.message||body?.error||`Serverfehler (${r.status})`);return body;}
async function refreshBalances(){try{await window.worldAccounts?.gameStateSync?.refreshBalances?.();await window.worldAccounts?.premiumLifecycle?.refreshAccount?.(window.worldAccounts?.authApi);}catch(e){console.warn('Monetarisierungsstatus konnte nicht sofort aktualisiert werden',e);}}
const card=(body,accent='#38bdf8')=>`<article style="position:relative;min-width:0;padding:16px;border:1px solid #40516a;border-radius:15px;background:linear-gradient(155deg,#152744,#0c1728);box-shadow:0 10px 28px rgba(0,0,0,.24);overflow:hidden"><span style="position:absolute;inset:0 auto auto 0;width:100%;height:3px;background:${accent}"></span>${body}</article>`;
const badge=t=>`<span style="position:absolute;right:10px;top:10px;padding:3px 7px;border-radius:999px;background:#8b2cf5;color:#fff;font-size:9px;font-weight:900">${t}</span>`;
const button=(attrs,label)=>`<button type="button" ${attrs} style="width:100%;min-height:40px;margin-top:11px;border:0;border-radius:9px;background:linear-gradient(90deg,#d7ff2f,#f4e92a);color:#18210a;font-weight:900;cursor:pointer">${label}</button>`;
const grid=(html,min=210)=>`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(${min}px,1fr));gap:13px">${html}</div>`;
function premiumCards(state){return PremiumOffers.map((p,i)=>card(`${badge(p.badge)}<div style="font-size:38px;margin:10px 0;text-align:center">${p.icon}</div><h3 style="margin:0;text-align:center">${p.label}</h3><p style="margin:5px 0 12px;text-align:center;opacity:.72;font-size:12px">${p.sub}</p><div style="font-size:24px;font-weight:950;text-align:center">${euro(p.priceEuro)} €</div>${button(`data-premium-offer="${p.id}"`,state.active?'Premium verlängern':'Premium wählen')}`,i===3?'#a78bfa':'#b8f33d')).join('');}
function coinCards(){return CoinOffers.map((p,i)=>card(`${badge(p.badge)}<h3 style="margin:0">${num(p.coins)} Coins</h3><div style="font-size:38px;text-align:center;margin:18px 0 8px">${p.icon}</div><div style="text-align:center;font-weight:900;color:#facc15">${p.bonus?`+${num(p.bonus)} Bonus`:'Ohne Bonus'}</div>${button(`data-coin-offer="${p.id}"`,`${euro(p.priceEuro)} €`)}<small style="display:block;text-align:center;margin-top:8px;opacity:.75">${p.bonus?`${num(p.base)} + ${num(p.bonus)} Bonus`:`${num(p.coins)} Coins gesamt`}</small>`,i>5?'#c084fc':'#38bdf8')).join('');}
function moneyCards(){return MoneyOffers.map((p,i)=>card(`${badge(p.badge)}<div style="font-size:38px;text-align:center;margin:12px">${p.icon}</div><h3 style="margin:0;text-align:center;font-size:22px">${num(p.money)} €</h3><div style="text-align:center;opacity:.75;font-size:12px">Firmengeld</div>${button(`data-money-offer="${p.id}"`,`🪙 ${num(p.coins)} Coins`)}`,i>3?'#34d399':'#60a5fa')).join('');}
function wire(section){section.querySelectorAll('[data-premium-offer]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const p=PremiumOffers.find(x=>x.id===b.dataset.premiumOffer);if(p)window.worldPaymentCheckout?.beginPremiumPurchase?.(p).catch(e=>feedback(e.message,'error'));});section.querySelectorAll('[data-coin-offer]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const p=CoinOffers.find(x=>x.id===b.dataset.coinOffer);if(p)window.worldPaymentCheckout?.beginCoinPurchase?.({packageId:p.id,coins:p.coins,priceEuro:p.priceEuro}).catch(e=>feedback(e.message,'error'));});section.querySelectorAll('[data-money-offer]').forEach(b=>b.onclick=async e=>{e.preventDefault();e.stopPropagation();const p=MoneyOffers.find(x=>x.id===b.dataset.moneyOffer);if(!p||!confirm(`${num(p.coins)} Coins gegen ${num(p.money)} € Firmengeld tauschen?`))return;b.disabled=true;try{const r=await rpc('exchange_coins_for_company_money',{p_tier:p.id});feedback(`✅ ${num(r.moneyCredited)} € Firmengeld gutgeschrieben. Neuer Coinstand: ${num(r.coins)}.`,'success');await refreshBalances();await updateState(section);}catch(e){feedback(e.message,'error');}finally{b.disabled=false;}});const ad=section.querySelector('[data-surprise-ad]');if(ad)ad.onclick=async()=>{try{if(!window.worldAdProvider?.showRewardedAd&&!window.worldRewardedAdProvider?.showRewardedAd)throw new Error('Der Reward-Werbeanbieter ist noch nicht verbunden.');await window.worldRewardedAdUI?.watchGeneral?.();}catch(e){feedback(e.message,'warning','Freiwillige Werbung');}};}
async function updateState(section){try{const s=await rpc('get_orvuno_monetization_state');const c=section.querySelector('[data-coin-balance]'),m=section.querySelector('[data-money-balance]');if(c)c.textContent=num(s.coins);if(m)m.textContent=`${num(s.money)} €`;return s;}catch(e){console.warn('Monetarisierungsstatus nicht geladen',e);return null;}}
export function renderPremiumPlans(mount,{accountData=account()}={}){if(!mount)return false;mount.querySelector('[data-premium-plans]')?.remove();const state=premium.state(accountData),section=document.createElement('section');section.dataset.premiumPlans='1';section.style.cssText='color:#f8fafc;padding:2px 0 20px';section.innerHTML=`<div style="padding:18px;border:1px solid #31533c;border-radius:15px;background:linear-gradient(100deg,#173425,#112c38);margin-bottom:14px"><small style="font-weight:900;color:#b8f33d">ORVUNO FÜR DEIN UNTERNEHMEN</small><h2 style="margin:5px 0">Premium & Coins</h2><p style="margin:0;opacity:.82">Mehr Komfort und Möglichkeiten. Keine gekauften Siege.</p><div style="margin-top:10px;font-weight:850">🪙 Coins: <span data-coin-balance>…</span> · 💶 Firmengeld: <span data-money-balance>…</span>${state.active?` · ⭐ Premium bis ${new Date(state.until).toLocaleDateString('de-DE')}`:''}</div></div><section><h2>⭐ Premium</h2>${grid(premiumCards(state),225)}</section><section style="margin-top:24px"><h2>🪙 Coins kaufen</h2>${grid(coinCards(),205)}</section><section style="margin-top:24px"><h2>💶 Firmengeld mit Coins</h2>${grid(moneyCards(),245)}</section><section style="margin-top:24px;padding:16px;border:1px solid #394c65;border-radius:15px;background:#17243a"><h2>🎁 Überraschungsbonus</h2><p>Freiwillige Werbung: Zeitbonus, Coin, kleines Firmengeld oder Premium-Jackpot.</p>${button('data-surprise-ad="1"','Werbung ansehen')}</section>`;mount.prepend(section);wire(section);updateState(section);return true;}
export function openPremiumCoinsHub(){document.querySelector('[data-orvuno-premium-coins-overlay]')?.remove();const ov=document.createElement('div');ov.dataset.orvunoPremiumCoinsOverlay='1';ov.style.cssText='position:fixed;inset:0;z-index:65000;background:rgba(2,6,23,.84);padding:60px 18px 24px;overflow:auto';const box=document.createElement('section');box.style.cssText='position:relative;width:min(1100px,96vw);margin:auto;padding:18px;background:#0f172a;border:1px solid #334155;border-radius:16px';const close=document.createElement('button');close.type='button';close.textContent='✕ Schließen';close.style.cssText='position:sticky;top:0;float:right;z-index:3;padding:9px 12px;border-radius:8px;cursor:pointer';close.onclick=e=>{e.preventDefault();e.stopPropagation();ov.remove();};box.append(close);ov.append(box);ov.onclick=e=>{if(e.target===ov)ov.remove();};document.body.append(ov);renderPremiumPlans(box);return ov;}
export function installPremiumPlanUI(){if(typeof window==='undefined')return false;window.addEventListener('world:open-premium',e=>e.detail?.mount?renderPremiumPlans(e.detail.mount):openPremiumCoinsHub());return true;}
if(typeof window!=='undefined'){window.worldPremiumPlanUI={render:renderPremiumPlans,open:openPremiumCoinsHub,install:installPremiumPlanUI,PremiumOffers,CoinOffers,MoneyOffers};installPremiumPlanUI();}
