// WorldProject - sichtbarer Premiumstatus, Bauprojekte und Produktionsplanung
export class PremiumStatusDialog{
 constructor({premium,constructionQueue=null,productionQueue=null,parent=document.body}={}){this.premium=premium;this.constructionQueue=constructionQueue;this.productionQueue=productionQueue;this.parent=parent;this.overlay=null;this.account=null;}
 el(tag,text=null){const e=document.createElement(tag);if(text!==null)e.textContent=text;return e;}
 button(text,fn){const b=this.el("button",text);Object.assign(b.style,{padding:"7px 11px",margin:"3px",fontWeight:"700",cursor:"pointer",border:0,borderRadius:"7px"});b.onclick=fn;return b;}
 duration(ms){let m=Math.max(0,Math.ceil(Number(ms||0)/60000)),d=Math.floor(m/1440);m-=d*1440;const h=Math.floor(m/60),min=m%60;return [d?`${d} T`:null,h?`${h} Std`:null,`${min} Min`].filter(Boolean).join(" ");}
 money(v){return Number(v||0).toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
 open(account=window.worldCurrentUser||{}){if(this.overlay)return;this.account=account;const ov=this.el("div"),p=this.el("div");Object.assign(ov.style,{position:"fixed",inset:0,zIndex:24000,background:"rgba(0,0,0,.72)",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px"});Object.assign(p.style,{width:"min(760px,94vw)",maxHeight:"90vh",overflow:"auto",background:"#fff",color:"#111",borderRadius:"14px",padding:"20px",fontFamily:"Arial,sans-serif"});ov.append(p);this.parent.append(ov);this.overlay=ov;this.render(p);}
 render(p){p.innerHTML="";const account=this.account||{},state=this.premium.state(account);p.append(this.el("h2","⭐ Premium"),this.el("p",state.active?`Aktiv bis ${new Date(state.until).toLocaleString("de-DE")}`:state.status==="expired"?"Premium ist abgelaufen. Gespeicherte Premium-Inhalte bleiben erhalten; zusätzliche Funktionen werden bis zur Reaktivierung gesperrt.":"Kein Premium aktiv."));for(const b of this.premium.listBenefits(account)){const row=this.el("div",`${b.label}: Standard ${String(b.standardValue)} · Premium ${String(b.premiumValue)}`);Object.assign(row.style,{padding:"8px",margin:"4px 0",border:"1px solid #ddd",borderRadius:"8px"});p.append(row);}
 if(this.constructionQueue){const view=this.constructionQueue.status(account),running=Number(view.active||0),limit=Number(view.limit||0);p.append(this.el("h3","🏗️ Bauaufträge"));const row=this.el("div",`${running}/${limit} reguläre Bauplätze belegt${view.overLimit?" · laufende Premium-Aufträge über Standardlimit laufen bis zur Fertigstellung weiter":""}.`);Object.assign(row.style,{padding:"10px",margin:"6px 0",border:"1px solid #d8b24c",borderRadius:"8px"});p.append(row);if(view.overLimit&&!state.active)p.append(this.el("div","Es wird nichts pausiert oder abgebrochen. Ein neuer Bauauftrag ist erst möglich, wenn wieder weniger als 3 Bauaufträge gleichzeitig laufen."));}
 if(this.productionQueue){const view=this.productionQueue.view(account);p.append(this.el("h3","⚙️ Produktionswarteschlange"));if(!state.active)p.append(this.el("div","Nur mit aktivem Premium planbar. Gespeicherte Aufträge bleiben erhalten."));for(const s of view.slots){const row=this.el("div");Object.assign(row.style,{padding:"9px",margin:"5px 0",border:"1px solid #bbb",borderRadius:"8px"});row.append(this.el("strong",`Slot ${s.slot}: ${s.label}`));if(s.entry){row.append(this.el("div",`Chargen: ${s.batches}${s.blockReason?` · ⚠ ${s.blockReason}`:""}`),this.button("↑",()=>{this.productionQueue.moveUp(s.entry.id);this.render(p);}),this.button("↓",()=>{this.productionQueue.moveDown(s.entry.id);this.render(p);}),this.button("Entfernen",()=>{this.productionQueue.remove(s.entry.id);this.render(p);}));}p.append(row);}const pp=this.productionQueue.pausedPremium();if(pp.length){p.append(this.el("div",`⏸ ${pp.length} Produktionsauftrag/-aufträge wegen Premium pausiert.`));if(state.active)p.append(this.button("Produktionsplanung fortsetzen",()=>{if(confirm("Pausierte Produktionsplanung wieder freigeben?")){this.productionQueue.restoreAfterPremium(account,{confirm:true});this.render(p);}}));}}
 p.append(this.el("p","Premium-Inhalte werden bei Ablauf niemals gelöscht. Bereits gestartete Bauaufträge laufen weiter; zusätzliche Premium-Kapazitäten und Automatisierungen werden lediglich gesperrt oder inaktiv."),this.button("Schließen",()=>this.close()));}
 close(){this.overlay?.remove();this.overlay=null;}
}
