// WorldProject – sichtbare Vorbereitung des separaten Zusatzpaket-Markts.
import './PremiumExtraPackageBootstrapIntegration.js';
import './PremiumExtraPackageServerSync.js';
import { PremiumExtraPackageCatalog, extraPackageCatalog, packageStatus, ensureExtraPackageState } from './PremiumExtraPackageSystem.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>v?new Date(Number(v)).toLocaleString('de-DE'):'—';
function materialText(materials={}){const names={concrete:'Beton',steel:'Baustahl',brick:'Mauerwerk',insulation:'Dämmung',electrical:'Elektromaterial',pipes:'Rohrmaterial',roofing:'Dachmaterial'};return Object.entries(materials).map(([k,v])=>`${names[k]||k}: ${v}`).join(' · ');}
export function renderPremiumExtraPackages({account=window.worldCurrentUser||{},mount}={}){
 if(!mount)return;const catalog=extraPackageCatalog(),active=packageStatus(account),state=ensureExtraPackageState(account),credits=state.history.filter(x=>x.event==='daily_credit').slice(-10).reverse();
 mount.innerHTML=`<section data-premium-extra-packages><h2>🎁 Extra-Premium-Pakete</h2><p>Diese Pakete sind <b>separat kaufbar</b> und verändern deine normale Premiumzeit nicht.</p>${catalog.map(p=>`<article style="padding:12px;border:1px solid #374151;border-radius:10px;margin:10px 0"><h3>${esc(p.label)}</h3><p>${esc(p.description)}</p><div><b>Laufzeiten:</b> ${p.durations.map(d=>`${d} Tage`).join(' · ')}</div><div><b>Status:</b> ${p.enabled?'verfügbar':'🔒 noch nicht zum Kauf freigegeben'}</div><div style="margin-top:8px"><small>Preis und tägliche Mengen werden vor der Freigabe im Balancing festgelegt.</small></div></article>`).join('')}${active.length?`<h3>Aktive Zusatzpakete</h3>${active.map(x=>`<div style="padding:8px;border-bottom:1px solid #374151"><b>${esc(PremiumExtraPackageCatalog[x.packageId]?.label||x.packageId)}</b> · noch ${x.remainingDays} Tage${x.server?' · ☁ servergespeichert':''}<br><small>Nächste mögliche Gutschrift: ${fmtDate(x.nextClaimAt)} · Ende: ${fmtDate(x.endsAt)}</small></div>`).join('')}:''}${credits.length?`<h3>Letzte Tagesgutschriften</h3>${credits.map(x=>`<div style="padding:6px 0"><b>${fmtDate(x.at)}</b> · ${esc(materialText(x.materials))}</div>`).join('')}:''}</section>`;
}
function toast(text){const t=document.createElement('div');t.textContent=text;Object.assign(t.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:60000,background:'#176b36',color:'#fff',padding:'11px 14px',borderRadius:'9px',fontWeight:'800',boxShadow:'0 5px 18px rgba(0,0,0,.35)'});document.body.append(t);setTimeout(()=>t.remove(),4500);}
export function installPremiumExtraPackageTab(){if(typeof document==='undefined')return false;window.addEventListener('world:open-premium-extra-packages',e=>{const mount=e.detail?.mount||document.querySelector('[data-premium-extra-mount]');if(mount)renderPremiumExtraPackages({account:window.worldCurrentUser||{},mount});});window.addEventListener('world:premium-extra-credited',e=>{const rows=e.detail?.credited||[];if(rows.length)toast(`🎁 Extra-Premium: heutige Baustoffe wurden gutgeschrieben (${rows.length} Paket${rows.length===1?'':'e'}).`);});window.addEventListener('world:premium-extra-synced',()=>{const mount=document.querySelector('[data-premium-extra-mount]');if(mount)renderPremiumExtraPackages({account:window.worldCurrentUser||{},mount});});return true;}
if(typeof window!=='undefined'){window.worldPremiumExtraPackageUI={render:renderPremiumExtraPackages,install:installPremiumExtraPackageTab};installPremiumExtraPackageTab();}
