// WorldProject – Preissteuerung, Rabatte, Aktionen und Margenschutz.
import { profitabilityAtPrice, minimumSalePrice } from "./IndustryEconomicsEngine.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensurePricing(c={}){c.pricing??={prices:{},promotions:[],history:[],policies:{minimumMargin:.08,targetMargin:.25,maxDiscount:.2}};return c.pricing;}
export function setBasePrice(c,productId,price,{recipeId=null,at=Date.now()}={}){const p=ensurePricing(c),q=Math.max(0,n(price));p.prices[productId]={productId,price:q,recipeId,updatedAt:at};p.history.push({kind:"base_price",productId,price:q,at});return p.prices[productId];}
export function createPromotion(c,{productId,discountRate=.05,startsAt=Date.now(),endsAt=Date.now()+7*86400000,minQuantity=1,maxQuantity=null,label="Aktion"}={}){const p=ensurePricing(c),row={id:`promo-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,productId,discountRate:clamp(n(discountRate,.05),0,p.policies.maxDiscount),startsAt:n(startsAt),endsAt:n(endsAt),minQuantity:Math.max(1,n(minQuantity,1)),maxQuantity:maxQuantity==null?null:Math.max(1,n(maxQuantity)),label,status:"active"};p.promotions.push(row);return row;}
export function volumeDiscount(quantity){const q=Math.max(0,n(quantity));if(q>=1000)return .08;if(q>=500)return .05;if(q>=100)return .03;if(q>=50)return .015;return 0;}
export function activePromotion(c,productId,quantity,{now=Date.now()}={}){const p=ensurePricing(c);return p.promotions.filter(x=>x.status==="active"&&x.productId===productId&&x.startsAt<=now&&x.endsAt>=now&&quantity>=x.minQuantity&&(x.maxQuantity==null||quantity<=x.maxQuantity)).sort((a,b)=>b.discountRate-a.discountRate)[0]||null;}
export function quotePrice(c,{productId,quantity=1,customerDiscount=0,now=Date.now()}={}){const p=ensurePricing(c),base=p.prices[productId];if(!base)throw new Error("Kein Basispreis gesetzt");const promo=activePromotion(c,productId,quantity,{now}),discount=clamp(volumeDiscount(quantity)+n(customerDiscount)+(promo?.discountRate||0),0,p.policies.maxDiscount),unitPrice=base.price*(1-discount);let marginGuard=null;if(base.recipeId){const min=minimumSalePrice(c,base.recipeId,Math.max(1,n(quantity)),{targetMargin:p.policies.minimumMargin});marginGuard={minimumUnitPrice:min.minimumUnitPrice,violates:unitPrice+1e-9<min.minimumUnitPrice};}return{productId,quantity:n(quantity),basePrice:base.price,discount,promotion:promo?.id||null,unitPrice,total:unitPrice*n(quantity),marginGuard};}
export function safeQuote(c,args){const q=quotePrice(c,args);if(q.marginGuard?.violates)return{...q,approved:false,reason:"minimum_margin",safeUnitPrice:q.marginGuard.minimumUnitPrice,safeTotal:q.marginGuard.minimumUnitPrice*q.quantity};return{...q,approved:true};}
export function priceExperiment(c,{productId,recipeId,amount=100,prices=[]}={}){return prices.map(price=>{const p=profitabilityAtPrice(c,recipeId,amount,price),demand=clamp((p.unitCost/Math.max(.01,price))*1.2,.25,2),expectedQuantity=amount*demand,expectedProfit=(price-p.unitCost)*expectedQuantity;return{price,demandIndex:demand,expectedQuantity,unitCost:p.unitCost,expectedProfit};}).sort((a,b)=>b.expectedProfit-a.expectedProfit);}
export function pricingKpis(c){const p=ensurePricing(c),active=p.promotions.filter(x=>x.status==="active"&&x.endsAt>=Date.now());return{products:Object.keys(p.prices).length,activePromotions:active.length,averagePrice:Object.values(p.prices).length?Object.values(p.prices).reduce((s,x)=>s+n(x.price),0)/Object.values(p.prices).length:0,minimumMargin:p.policies.minimumMargin,targetMargin:p.policies.targetMargin,maxDiscount:p.policies.maxDiscount};}
