// WorldProject – Beschaffungsauktionen / RFQ für größere Einkaufsvolumina.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureProcurementAuctions(c={}){c.procurementAuctions??={requests:[],awards:[],history:[]};return c.procurementAuctions;}
export function createProcurementRequest(c,{item,quantity,maxUnitPrice=null,requiredBy=null,minQuality=.8}={}){const s=ensureProcurementAuctions(c),row={id:`rfq-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,item,quantity:Math.max(0,n(quantity)),maxUnitPrice:maxUnitPrice==null?null:n(maxUnitPrice),requiredBy, minQuality:n(minQuality,.8),offers:[],status:'open',createdAt:Date.now()};s.requests.push(row);return row;}
export function submitSupplierOffer(c,requestId,{supplierId,unitPrice,deliveryHours,quality=1,reliability=1,minimumQuantity=0}={}){const s=ensureProcurementAuctions(c),r=s.requests.find(x=>x.id===requestId&&x.status==='open');if(!r)throw new Error('RFQ nicht offen');if(n(quality)<r.minQuality)throw new Error('Qualität unter Mindestanforderung');const offer={id:`offer-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,supplierId,unitPrice:Math.max(0,n(unitPrice)),deliveryHours:Math.max(0,n(deliveryHours)),quality:n(quality,1),reliability:n(reliability,1),minimumQuantity:Math.max(0,n(minimumQuantity)),createdAt:Date.now()};offer.score=offer.unitPrice*.55+offer.deliveryHours*.05+(1-offer.quality)*50+(1-offer.reliability)*40;r.offers.push(offer);return offer;}
export function rankProcurementOffers(c,requestId){const s=ensureProcurementAuctions(c),r=s.requests.find(x=>x.id===requestId);if(!r)throw new Error('RFQ fehlt');return r.offers.filter(o=>(r.maxUnitPrice==null||o.unitPrice<=r.maxUnitPrice)&&r.quantity>=o.minimumQuantity).sort((a,b)=>a.score-b.score);}
export function awardProcurement(c,requestId,offerId=null){const s=ensureProcurementAuctions(c),r=s.requests.find(x=>x.id===requestId);if(!r)throw new Error('RFQ fehlt');const ranked=rankProcurementOffers(c,requestId),offer=offerId?r.offers.find(x=>x.id===offerId):ranked[0];if(!offer)throw new Error('Kein geeignetes Lieferantenangebot');const total=r.quantity*offer.unitPrice;if(n(c.money)<total)throw new Error('Liquidität reicht nicht');c.money-=total;const award={id:`award-${Date.now()}`,requestId:r.id,offerId:offer.id,supplierId:offer.supplierId,item:r.item,quantity:r.quantity,unitPrice:offer.unitPrice,total,etaAt:Date.now()+offer.deliveryHours*3600000,status:'ordered'};s.awards.push(award);r.status='awarded';r.awardId=award.id;return award;}
export function receiveProcurementAward(c,awardId,{quantity=null,accepted=true}={}){const s=ensureProcurementAuctions(c),a=s.awards.find(x=>x.id===awardId);if(!a)throw new Error('Bestellung fehlt');if(a.status==='received')return{success:true,idempotent:true};if(!accepted){a.status='rejected';c.money=n(c.money)+a.total;return{success:false,rejected:true,refund:a.total};}const q=quantity==null?a.quantity:Math.min(a.quantity,Math.max(0,n(quantity)));c.inventory??={};c.inventory[a.item]=n(c.inventory[a.item])+q;a.received=q;a.status=q>=a.quantity?'received':'partial';return{success:true,quantity:q,status:a.status};}
export function procurementAuctionKpis(c){const s=ensureProcurementAuctions(c);return{open:s.requests.filter(x=>x.status==='open').length,awarded:s.requests.filter(x=>x.status==='awarded').length,orders:s.awards.length,spend:s.awards.reduce((a,x)=>a+n(x.total),0)};}
