// Einkaufsverhandlung und Lieferanten-SLA fuer alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureNegotiation(c={}){c.procurementNegotiation??={negotiations:[],contracts:[],performance:[]};return c.procurementNegotiation;}
export function startSupplierNegotiation(c,{supplierId,item,basePrice,targetPrice,quantity=0,targetDeliveryHours=null,targetQuality=.95}={}){const s=ensureNegotiation(c),row={id:`neg-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,supplierId,item,basePrice:n(basePrice),targetPrice:n(targetPrice,basePrice),quantity:Math.max(0,n(quantity)),targetDeliveryHours:targetDeliveryHours==null?null:n(targetDeliveryHours),targetQuality:clamp(n(targetQuality,.95),0,1),status:'open',round:1,history:[],createdAt:Date.now()};s.negotiations.push(row);return row;}
export function counterOffer(c,id,{unitPrice,deliveryHours,quality,minimumQuantity=0}={}){const x=ensureNegotiation(c).negotiations.find(a=>a.id===id);if(!x)throw new Error('Verhandlung fehlt');if(x.status!=='open')throw new Error('Verhandlung geschlossen');const offer={round:x.round,unitPrice:n(unitPrice),deliveryHours:n(deliveryHours),quality:clamp(n(quality,1),0,1),minimumQuantity:Math.max(0,n(minimumQuantity)),at:Date.now()};x.history.push(offer);x.round++;return offer;}
export function scoreNegotiationOffer(x,offer){const price=x.basePrice?clamp(x.targetPrice/n(offer.unitPrice,x.basePrice),.4,1.6):1,delivery=x.targetDeliveryHours?clamp(x.targetDeliveryHours/Math.max(1,n(offer.deliveryHours)),.4,1.5):1,quality=clamp(n(offer.quality,1)/Math.max(.1,x.targetQuality),.5,1.2),quantityPenalty=x.quantity&&offer.minimumQuantity>x.quantity?.75:1;return price*.55+delivery*.2+quality*.25-quantityPenalty;}
export function acceptNegotiation(c,id,{durationDays=90}={}){const s=ensureNegotiation(c),x=s.negotiations.find(a=>a.id===id);if(!x)throw new Error('Verhandlung fehlt');const offer=x.history.at(-1);if(!offer)throw new Error('Kein Angebot vorhanden');x.status='accepted';const contract={id:`pc-${Date.now()}`,supplierId:x.supplierId,item:x.item,unitPrice:offer.unitPrice,deliveryHours:offer.deliveryHours,qualityTarget:offer.quality,minimumQuantity:offer.minimumQuantity,startsAt:Date.now(),endsAt:Date.now()+Math.max(1,n(durationDays))*86400000,status:'active'};s.contracts.push(contract);return contract;}
export function recordSupplierSla(c,{supplierId,onTime=true,quality=1,priceDeviation=0}={}){const s=ensureNegotiation(c),row={supplierId,onTime:!!onTime,quality:clamp(n(quality,1),0,1),priceDeviation:n(priceDeviation),at:Date.now()};s.performance.push(row);return row;}
export function supplierSlaScore(c,supplierId,{last=20}={}){const rows=ensureNegotiation(c).performance.filter(x=>x.supplierId===supplierId).slice(-last);if(!rows.length)return null;return rows.reduce((sum,x)=>sum+(x.onTime?0.45:0)+x.quality*.45+clamp(1-Math.abs(x.priceDeviation),0,1)*.1,0)/rows.length;}
export function negotiationKpis(c){const s=ensureNegotiation(c);return{open:s.negotiations.filter(x=>x.status==='open').length,contractsActive:s.contracts.filter(x=>x.status==='active'&&x.endsAt>Date.now()).length,performanceRecords:s.performance.length};}
