// WorldProject – Chargen-Genealogie von Lieferant -> Produktion -> Kunde.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureTraceability(c={}){c.traceability??={lots:{},links:[],shipments:[],recalls:[]};return c.traceability;}
export function registerTraceLot(c,{lotId,item,quantity,sourceType='supplier',sourceId=null,parentLots=[],qualityStatus='released',createdAt=Date.now()}={}){const t=ensureTraceability(c),id=lotId||`trace-${createdAt}-${Math.random().toString(36).slice(2,6)}`;t.lots[id]={id,item,quantity:n(quantity),sourceType,sourceId,parentLots:[...parentLots],qualityStatus,createdAt};for(const p of parentLots)t.links.push({from:p,to:id,kind:'consumed_into'});return t.lots[id];}
export function registerProductionGenealogy(c,{jobId,productId,quantity,inputLotIds=[],outputLotId=null,now=Date.now()}={}){return registerTraceLot(c,{lotId:outputLotId,item:productId,quantity,sourceType:'production',sourceId:jobId,parentLots:inputLotIds,createdAt:now});}
export function registerCustomerShipment(c,{customerId,lotId,quantity,orderId,now=Date.now()}={}){const t=ensureTraceability(c);if(!t.lots[lotId])throw new Error('Charge fehlt');const row={id:`ship-${now}-${Math.random().toString(36).slice(2,6)}`,customerId,lotId,quantity:n(quantity),orderId,at:now};t.shipments.push(row);return row;}
export function traceBackward(c,lotId){const t=ensureTraceability(c),seen=new Set(),out=[];function walk(id){if(seen.has(id)||!t.lots[id])return;seen.add(id);const x=t.lots[id];out.push(x);for(const p of x.parentLots||[])walk(p);}walk(lotId);return out;}
export function traceForward(c,lotId){const t=ensureTraceability(c),seen=new Set([lotId]),queue=[lotId],lots=[];while(queue.length){const id=queue.shift();for(const link of t.links.filter(x=>x.from===id)){if(seen.has(link.to))continue;seen.add(link.to);queue.push(link.to);lots.push(t.lots[link.to]);}}return{lots:lots.filter(Boolean),shipments:t.shipments.filter(s=>seen.has(s.lotId)||s.lotId===lotId)};}
export function initiateTraceRecall(c,lotId,{reason='Qualitätsabweichung',now=Date.now()}={}){const t=ensureTraceability(c),forward=traceForward(c,lotId),affectedLots=[lotId,...forward.lots.map(x=>x.id)],customers=[...new Set(forward.shipments.map(x=>x.customerId))];for(const id of affectedLots)if(t.lots[id])t.lots[id].qualityStatus='recalled';const row={id:`trace-recall-${now}`,originLotId:lotId,affectedLots,customers,reason,at:now,status:'open'};t.recalls.push(row);return row;}
export function traceabilityKpis(c){const t=ensureTraceability(c);return{lots:Object.keys(t.lots).length,links:t.links.length,shipments:t.shipments.length,openRecalls:t.recalls.filter(x=>x.status==='open').length};}
