// WorldProject – Produktions-/Leistungswarteschlange für alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureScheduler(c={}){c.productionScheduler??={queue:[],history:[],locks:{}};return c.productionScheduler;}
export function enqueueJob(c,{id,recipeId,productId,quantity,durationMinutes,machineId=null,requiredSkills=[],priority=0,dueAt=null,dependsOn=[],earliestStart=Date.now()}={}){const s=ensureScheduler(c),row={id:id||`sched-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,recipeId,productId,quantity:Math.max(0,n(quantity)),durationMinutes:Math.max(1,n(durationMinutes,1)),machineId,requiredSkills:[...requiredSkills],priority:n(priority),dueAt:dueAt?Number(dueAt):null,dependsOn:[...dependsOn],earliestStart:n(earliestStart,Date.now()),status:"queued",createdAt:Date.now(),startAt:null,endAt:null};s.queue.push(row);return row;}
function dependenciesDone(queue,job){return(job.dependsOn||[]).every(id=>queue.find(x=>x.id===id)?.status==="done");}
function machineFreeAt(queue,machineId,from){if(!machineId)return from;const ends=queue.filter(x=>x.machineId===machineId&&["planned","running"].includes(x.status)&&n(x.endAt)>from).map(x=>n(x.endAt));return ends.length?Math.max(from,...ends):from;}
export function scheduleQueue(c,{now=Date.now()}={}){const s=ensureScheduler(c),queued=s.queue.filter(x=>x.status==="queued").sort((a,b)=>b.priority-a.priority||(a.dueAt??Infinity)-(b.dueAt??Infinity)||a.createdAt-b.createdAt);for(const job of queued){if(!dependenciesDone(s.queue,job))continue;let start=Math.max(now,n(job.earliestStart,now));start=machineFreeAt(s.queue,job.machineId,start);job.startAt=start;job.endAt=start+job.durationMinutes*60000;job.status="planned";}return s.queue;}
export function startScheduledJob(c,id,{now=Date.now()}={}){const s=ensureScheduler(c),j=s.queue.find(x=>x.id===id);if(!j)throw new Error("Geplanter Auftrag fehlt");if(j.status==="running")return{success:true,idempotent:true,job:j};if(j.status!=="planned"||now<n(j.startAt))throw new Error("Auftrag noch nicht startbereit");j.status="running";j.actualStartAt=now;return{success:true,job:j};}
export function finishScheduledJob(c,id,{now=Date.now(),force=false}={}){const s=ensureScheduler(c),j=s.queue.find(x=>x.id===id);if(!j)throw new Error("Geplanter Auftrag fehlt");if(j.status==="done")return{success:true,idempotent:true,job:j};if(j.status!=="running")throw new Error("Auftrag läuft nicht");if(!force&&now<n(j.endAt))throw new Error("Auftrag noch nicht fertig");j.status="done";j.actualEndAt=now;s.history.push({...j});scheduleQueue(c,{now});return{success:true,job:j};}
export function delayJob(c,id,minutes){const s=ensureScheduler(c),j=s.queue.find(x=>x.id===id);if(!j)throw new Error("Auftrag fehlt");const delta=Math.max(0,n(minutes))*60000;j.earliestStart=Math.max(n(j.earliestStart),Date.now())+delta;if(["planned","queued"].includes(j.status)){j.status="queued";j.startAt=null;j.endAt=null;}scheduleQueue(c);return j;}
export function cancelScheduledJob(c,id){const s=ensureScheduler(c),j=s.queue.find(x=>x.id===id);if(!j)throw new Error("Auftrag fehlt");if(j.status==="done")throw new Error("Fertiger Auftrag kann nicht storniert werden");j.status="cancelled";j.cancelledAt=Date.now();scheduleQueue(c);return j;}
export function schedulerKpis(c){const s=ensureScheduler(c),q=s.queue;return{total:q.length,queued:q.filter(x=>x.status==="queued").length,planned:q.filter(x=>x.status==="planned").length,running:q.filter(x=>x.status==="running").length,done:q.filter(x=>x.status==="done").length,cancelled:q.filter(x=>x.status==="cancelled").length,late:q.filter(x=>x.dueAt&&!["done","cancelled"].includes(x.status)&&n(x.endAt||Infinity)>n(x.dueAt)).length};}
