// Multi-Step-Produktionsgraph fuer alle produzierenden Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureProductionGraph(c={}){c.productionGraph??={routes:{},runs:[],buffers:{}};return c.productionGraph;}
export function defineProductionRoute(c,{id,productId,steps=[]}={}){const g=ensureProductionGraph(c);if(!id||!productId||!steps.length)throw new Error('Produktionsroute unvollstaendig');const normalized=steps.map((s,i)=>({id:s.id||`${id}-step-${i+1}`,index:i,recipeId:s.recipeId||null,machineType:s.machineType||null,input:s.input||{},output:s.output||{},durationMinutes:Math.max(1,n(s.durationMinutes,1)),setupMinutes:Math.max(0,n(s.setupMinutes)),qualityGate:!!s.qualityGate}));g.routes[id]={id,productId,steps:normalized};return g.routes[id];}
export function startProductionRoute(c,routeId,quantity,{now=Date.now(),requestId}={}){const g=ensureProductionGraph(c),route=g.routes[routeId];if(!route)throw new Error('Produktionsroute fehlt');if(requestId){const existing=g.runs.find(x=>x.requestId===requestId);if(existing)return{success:true,idempotent:true,run:existing};}const run={id:`prun-${now}-${Math.random().toString(36).slice(2,6)}`,requestId,routeId,productId:route.productId,quantity:Math.max(0,n(quantity)),currentStep:0,status:'running',startedAt:now,stepRuns:[]};g.runs.push(run);return{success:true,run};}
export function currentProductionStep(c,runId){const g=ensureProductionGraph(c),run=g.runs.find(x=>x.id===runId);if(!run)return null;const route=g.routes[run.routeId];return route?.steps?.[run.currentStep]||null;}
export function completeProductionStep(c,runId,{yieldRate=1,qualityPassed=true,now=Date.now()}={}){const g=ensureProductionGraph(c),run=g.runs.find(x=>x.id===runId);if(!run)throw new Error('Produktionslauf fehlt');if(run.status!=='running')return run;const route=g.routes[run.routeId],step=route.steps[run.currentStep];if(!step)throw new Error('Produktionsschritt fehlt');if(step.qualityGate&&!qualityPassed){run.status='quality_hold';run.stepRuns.push({stepId:step.id,status:'blocked',at:now});return run;}const produced=run.quantity*Math.max(0,Math.min(1,n(yieldRate,1)));for(const[id,q]of Object.entries(step.output||{}))g.buffers[id]=n(g.buffers[id])+n(q)*produced;run.stepRuns.push({stepId:step.id,status:'done',produced,at:now});run.currentStep++;if(run.currentStep>=route.steps.length){run.status='done';run.completedAt=now;}return run;}
export function releaseQualityHold(c,runId){const run=ensureProductionGraph(c).runs.find(x=>x.id===runId);if(!run)throw new Error('Produktionslauf fehlt');if(run.status==='quality_hold')run.status='running';return run;}
export function productionGraphKpis(c){const g=ensureProductionGraph(c);return{routes:Object.keys(g.routes).length,running:g.runs.filter(x=>x.status==='running').length,qualityHolds:g.runs.filter(x=>x.status==='quality_hold').length,done:g.runs.filter(x=>x.status==='done').length,buffers:Object.keys(g.buffers).length};}
