// WorldProject - Sicherheits- und Kostenebene fuer Produktion.
function positive(v,label){const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new Error(`${label} muss groesser als 0 sein`);return n;}
export function validateProductionAmount(value,{max=100000,allowDecimal=true}={}){const n=positive(value,"Produktionsmenge");if(!allowDecimal&&!Number.isInteger(n))throw new Error("Produktionsmenge muss ganzzahlig sein");if(n>max)throw new Error(`Produktionsmenge ueber Maximum ${max}`);return n;}
export function productionRequirements(recipe,targetOutput){const output=positive(recipe?.output,"Rezeptausgabe"),target=validateProductionAmount(targetOutput),factor=target/output,requirements={};for(const[id,q]of Object.entries(recipe?.materials||{}))requirements[id]=positive(q,`Rezeptmenge ${id}`)*factor;return{factor,requirements,targetOutput:target};}
export function productionShortfall(warehouse,requirements={}){const missing={};for(const[id,needed]of Object.entries(requirements)){const zone=warehouse.zoneFor(id),have=Math.max(0,Number(warehouse.stock?.[zone]?.[id])||0);if(have+1e-9<needed)missing[id]=needed-have;}return{ready:Object.keys(missing).length===0,missing};}
export function atomicallyStartProduction({planner,recipe,targetOutput,requestId,now=Date.now()}={}){if(!planner||!recipe)throw new Error("Produktionsplaner oder Rezept fehlt");const key=String(requestId??"").trim();if(!key)throw new Error("Produktions-requestId fehlt");planner.productionRequestLedger??={};if(planner.productionRequestLedger[key])return{success:true,deduplicated:true,job:planner.productionRequestLedger[key]};const p=planner.planForOutput(recipe,validateProductionAmount(targetOutput));if(!p.ready)return{success:false,deduplicated:false,plan:p,reason:Object.keys(p.missing||{}).length?"Rohstoffe fehlen":"Maschine fehlt oder ist belegt"};const job=planner.startForOutput(recipe,targetOutput,now);planner.productionRequestLedger[key]=job;return{success:true,deduplicated:false,job};}
export function productionTimeState(job,now=Date.now()){const finish=Number(job?.finishAt)||Date.parse(job?.finishAt),current=Number(now)||Date.now(),remainingMs=Math.max(0,(Number.isFinite(finish)?finish:current)-current);return{status:job?.status||"unknown",remainingMs,remainingMinutes:Math.ceil(remainingMs/60000),finished:remainingMs<=0&&job?.status!=="queued"};}
export function restoreProductionJobs(planner,rows=[],now=Date.now()){planner.queue=[];let max=0;for(const raw of rows||[]){if(!raw)continue;const job={...raw};if(job.status==="running"&&productionTimeState(job,now).finished)job.pendingCompletion=true;planner.queue.push(job);max=Math.max(max,Number(job.id)||0);}planner.seq=max+1;return planner.queue;}
export function machineAvailable(machine){return !!machine&&!machine.busy&&!['broken','sold','maintenance','workshop_required'].includes(machine.status)&&Number(machine.condition??100)>20;}
export function applyMachineWear(machine,{hours=0,batches=1,wearPerHour=.15,wearPerBatch=.25}={}){if(!machine)throw new Error("Maschine fehlt");const wear=Math.max(0,Number(hours)||0)*Math.max(0,Number(wearPerHour)||0)+Math.max(0,Number(batches)||0)*Math.max(0,Number(wearPerBatch)||0);machine.condition=Math.max(0,Math.min(100,Number(machine.condition??100)-wear));if(machine.condition<=20)machine.status="maintenance";return{wear,condition:machine.condition,status:machine.status};}
export function productionCostBreakdown({liters=0,units=0,materials=0,packaging=0,energy=0,labour=0,machine=0,transport=0,revenue=0}={}){const total=[materials,packaging,energy,labour,machine,transport].reduce((s,v)=>s+Math.max(0,Number(v)||0),0),l=Math.max(0,Number(liters)||0),u=Math.max(0,Number(units)||0),rev=Math.max(0,Number(revenue)||0);return{materials,packaging,energy,labour,machine,transport,total,costPerLiter:l>0?total/l:0,costPerUnit:u>0?total/u:0,revenue:rev,contribution:rev-total,marginPercent:rev>0?(rev-total)/rev*100:0,minimumUnitPrice:u>0?total/u:0};}
export function runProductionSafetyTest({ProductionPlanner,WarehouseSystem}={}){if(!ProductionPlanner||!WarehouseSystem)throw new Error("Testabhaengigkeiten fehlen");const warehouse=new WarehouseSystem({raw:1000,packaging:1000,finished:1000,cold:1000});warehouse.stock.raw.malt=500;const machine={id:1,type:"brewhouse",status:"available",busy:false,capacity:1000,condition:100},planner=new ProductionPlanner({warehouse,machines:[machine]}),recipe={id:"safe",product:"safe_bulk",materials:{malt:100},machineType:"brewhouse",durationMinutes:60,output:1000};if(validateProductionAmount("100.5")!==100.5)throw new Error("Dezimale Menge abgelehnt");let huge=false;try{validateProductionAmount(100001);}catch{huge=true;}if(!huge)throw new Error("Extremmenge nicht blockiert");const req=productionRequirements(recipe,500);if(req.requirements.malt!==50)throw new Error("Live-Bedarf falsch");const before=warehouse.stock.raw.malt,first=atomicallyStartProduction({planner,recipe,targetOutput:500,requestId:"p1",now:1000}),again=atomicallyStartProduction({planner,recipe,targetOutput:500,requestId:"p1",now:1001});if(!first.success||!again.deduplicated||warehouse.stock.raw.malt!==before-50)throw new Error("Produktions-Doppelklickschutz fehlgeschlagen");const state=productionTimeState(first.job,1000);if(!(state.remainingMinutes>0))throw new Error("Restzeit fehlt");const snapshot=JSON.parse(JSON.stringify(planner.queue)),restored=new ProductionPlanner({warehouse,machines:[machine]});restoreProductionJobs(restored,snapshot,first.job.finishAt+1);if(!restored.queue[0].pendingCompletion)throw new Error("Reload-Abschlussmarkierung fehlt");const wear=applyMachineWear(machine,{hours:2,batches:1});if(!(wear.condition<100))throw new Error("Maschinenverschleiss fehlt");const costs=productionCostBreakdown({liters:100,units:304,materials:20,packaging:10,energy:5,labour:10,machine:5,revenue:100});if(costs.total!==50||costs.costPerLiter!==.5||!(costs.contribution>0))throw new Error("Produktionskosten falsch");console.log("✅ PRODUCTION-SAFETY-TEST ERFOLGREICH");return{success:true};}
