// WorldProject – progressive Kosten für jedes weitere Gebäude derselben Art.
import { BuildingCatalog, startBuildingConstruction, ensureExpansionState, freeLandSqm } from './LandConstructionExpansionSystem.js';
import { assertCanStartConstruction } from './ConstructionPremiumCoinSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function buildingExpansionStage(company,type){ensureExpansionState(company);const existing=company.buildingState.rooms.filter(r=>r.id===type&&['finished','building'].includes(r.status)).length;return existing+1;}
export function progressiveBuildingQuote(company,type){ensureExpansionState(company);const base=BuildingCatalog[type];if(!base)throw new Error('Unbekanntes Gebäude');const stage=buildingExpansionStage(company,type),step=stage-1,costFactor=Math.pow(1.48,step),materialFactor=Math.pow(1.25,step),timeFactor=Math.pow(1.12,step);return{type,label:base.label,stage,sqm:base.sqm,cost:Math.round(base.cost*costFactor),durationMinutes:Math.round(base.durationMinutes*timeFactor),materials:Object.fromEntries(Object.entries(base.materials).map(([id,q])=>[id,Math.ceil(q*materialFactor)])),costFactor,materialFactor,timeFactor};}
export function progressiveBuildingMaterialNeed(company,type){const q=progressiveBuildingQuote(company,type),site=company.constructionSite?.materials||{};return Object.entries(q.materials).map(([id,required])=>({id,required,atSite:n(site[id]),missing:Math.max(0,required-n(site[id]))}));}
export function constructionCrewForBuilding(company,{now=Date.now()}={}){ensureExpansionState(company);const bookings=company.warehouseExpansion?.crewBookings||[],crew=bookings.find(x=>x.status==='booked');if(!crew)throw new Error('Kein gebuchter Bautrupp verfügbar. Bitte zuerst einen Bautrupp auswählen.');if(n(crew.availableAt)>now)throw new Error(`Bautrupp ist noch unterwegs. Verfügbar in ca. ${Math.ceil((n(crew.availableAt)-now)/60000)} Minuten`);if(n(crew.assignedUntil)>now)throw new Error(`Bautrupp ist noch auf einer anderen Baustelle. Verfügbar in ca. ${Math.ceil((n(crew.assignedUntil)-now)/60000)} Minuten`);return crew;}
export function progressiveBuildingQuoteWithCrew(company,type,{now=Date.now()}={}){const q=progressiveBuildingQuote(company,type),crew=constructionCrewForBuilding(company,{now}),durationMinutes=Math.max(30,Math.round(q.durationMinutes/Math.max(.1,n(crew.speedFactor,1)))),crewCost=Math.round(n(crew.dailyCost)*Math.max(1,durationMinutes/1440));return{...q,durationMinutes,baseDurationMinutes:q.durationMinutes,crewCost,totalCost:q.cost+crewCost,crew};}
export function startProgressiveBuildingConstruction(company,type,{now=Date.now(),account=(typeof window!=='undefined'?(window.worldCurrentUser||window.worldAccount||{}):{})}={}){ensureExpansionState(company);assertCanStartConstruction(company,account,now);const q=progressiveBuildingQuoteWithCrew(company,type,{now}),base=BuildingCatalog[type];if(freeLandSqm(company)<q.sqm)throw new Error(`Nicht genug Grundstücksfläche. Benötigt: ${q.sqm} m², frei: ${freeLandSqm(company)} m². Bitte zuerst mehr Land kaufen/erweitern.`);const extraMaterials={};for(const [id,total] of Object.entries(q.materials)){const extra=Math.max(0,total-n(base.materials[id]));if(extra>0)extraMaterials[id]=extra;const have=n(company.constructionSite.materials?.[id]);if(have<total)throw new Error(`Baumaterial fehlt: ${id} ${total-have}`);}const extraCost=Math.max(0,q.cost-base.cost),precharge=extraCost+q.crewCost;if(n(company.money)<q.totalCost)throw new Error(`Nicht genug Geld. Bau + Bautrupp kosten ${q.totalCost.toLocaleString('de-DE')} €`);for(const [id,extra] of Object.entries(extraMaterials))company.constructionSite.materials[id]-=extra;company.money-=precharge;let job;try{job=startBuildingConstruction(company,type,{now});}catch(error){company.money+=precharge;for(const [id,extra] of Object.entries(extraMaterials))company.constructionSite.materials[id]=n(company.constructionSite.materials[id])+extra;throw error;}job.durationMinutes=q.durationMinutes;job.finishAt=now+q.durationMinutes*60000;job.buildCost=q.cost;job.crewCost=q.crewCost;job.cost=q.totalCost;job.stage=q.stage;job.materials={...q.materials};job.crewBookingId=q.crew.id;job.crewLabel=q.crew.label;const room=company.buildingState.rooms.find(r=>r.instanceId===job.buildingInstanceId);if(room){room.finishAt=job.finishAt;room.stage=q.stage;}q.crew.assignedUntil=job.finishAt;q.crew.assignedBuildingJobId=job.id;return job;}
export function runProgressiveBuildingExpansionTest(){const c={type:'Brauerei',money:1000000,land:{totalSqm:2000},buildingState:{rooms:[],equipment:[]},constructionSite:{materials:{concrete:1000,steel:1000,brick:1000,electrical:1000,pipes:1000,roofing:1000,insulation:1000},jobs:[],deliveries:[]},warehouseExpansion:{level:0,extraSlots:0,jobs:[],crewBookings:[{id:'crew-test',label:'Test-Bautrupp',workers:8,dailyCost:3400,speedFactor:1.25,availableAt:0,status:'booked'}]}};const q1=progressiveBuildingQuote(c,'fermentation_house'),j1=startProgressiveBuildingConstruction(c,'fermentation_house',{now:0}),q2=progressiveBuildingQuote(c,'fermentation_house');if(q1.stage!==1||q2.stage!==2||q2.cost<=q1.cost||q2.materials.concrete<=q1.materials.concrete||q2.durationMinutes<=q1.durationMinutes)throw new Error('Gebäudestaffelung fehlerhaft');if(j1.buildCost!==q1.cost||j1.crewCost<=0||j1.cost!==j1.buildCost+j1.crewCost)throw new Error('Gebäude-/Bautruppkosten falsch berechnet');if(j1.durationMinutes>=q1.durationMinutes)throw new Error('Bautrupp-Geschwindigkeit wird nicht auf Bauzeit angewendet');if(c.warehouseExpansion.crewBookings[0].assignedUntil!==j1.finishAt)throw new Error('Bautrupp wurde der Baustelle nicht reserviert');let blocked=false;try{startProgressiveBuildingConstruction(c,'workshop',{now:1});}catch(e){blocked=/anderen Baustelle/.test(e.message);}if(!blocked)throw new Error('Bautrupp darf nicht parallel auf zwei Baustellen arbeiten');return true;}
if(typeof window!=='undefined')window.worldProgressiveBuildingExpansion={quote:progressiveBuildingQuote,quoteWithCrew:progressiveBuildingQuoteWithCrew,materialNeed:progressiveBuildingMaterialNeed,crew:constructionCrewForBuilding,start:startProgressiveBuildingConstruction,runTest:runProgressiveBuildingExpansionTest};
