// WorldProject – progressive Kosten für jedes weitere Gebäude derselben Art.
import { BuildingCatalog, constructionMaterialNeed, startBuildingConstruction, ensureExpansionState, freeLandSqm } from './LandConstructionExpansionSystem.js';
import { assertCanStartConstruction } from './ConstructionPremiumCoinSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function buildingExpansionStage(company,type){ensureExpansionState(company);const existing=company.buildingState.rooms.filter(r=>r.id===type&&['finished','building'].includes(r.status)).length;return existing+1;}
export function progressiveBuildingQuote(company,type){ensureExpansionState(company);const base=BuildingCatalog[type];if(!base)throw new Error('Unbekanntes Gebäude');const stage=buildingExpansionStage(company,type),step=stage-1,costFactor=Math.pow(1.48,step),materialFactor=Math.pow(1.25,step),timeFactor=Math.pow(1.12,step);return{type,label:base.label,stage,sqm:base.sqm,cost:Math.round(base.cost*costFactor),durationMinutes:Math.round(base.durationMinutes*timeFactor),materials:Object.fromEntries(Object.entries(base.materials).map(([id,q])=>[id,Math.ceil(q*materialFactor)])),costFactor,materialFactor,timeFactor};}
export function progressiveBuildingMaterialNeed(company,type){const q=progressiveBuildingQuote(company,type),site=company.constructionSite?.materials||{};return Object.entries(q.materials).map(([id,required])=>({id,required,atSite:n(site[id]),missing:Math.max(0,required-n(site[id]))}));}
export function startProgressiveBuildingConstruction(company,type,{now=Date.now(),account=(typeof window!=='undefined'?(window.worldCurrentUser||window.worldAccount||{}):{})}={}){ensureExpansionState(company);assertCanStartConstruction(company,account,now);const q=progressiveBuildingQuote(company,type),base=BuildingCatalog[type];if(freeLandSqm(company)<q.sqm)throw new Error(`Nicht genug Grundstücksfläche. Benötigt: ${q.sqm} m², frei: ${freeLandSqm(company)} m². Bitte zuerst mehr Land kaufen/erweitern.`);const extraMaterials={};for(const [id,total] of Object.entries(q.materials)){const extra=Math.max(0,total-n(base.materials[id]));if(extra>0)extraMaterials[id]=extra;const have=n(company.constructionSite.materials?.[id]);if(have<total)throw new Error(`Baumaterial fehlt: ${id} ${total-have}`);}const extraCost=Math.max(0,q.cost-base.cost);if(n(company.money)<q.cost)throw new Error(`Nicht genug Geld. Ausbaustufe ${q.stage} kostet ${q.cost.toLocaleString('de-DE')} €`);for(const [id,extra] of Object.entries(extraMaterials))company.constructionSite.materials[id]-=extra;company.money-=extraCost;let job;try{job=startBuildingConstruction(company,type,{now});}catch(error){company.money+=extraCost;for(const [id,extra] of Object.entries(extraMaterials))company.constructionSite.materials[id]=n(company.constructionSite.materials[id])+extra;throw error;}const extraDuration=Math.max(0,q.durationMinutes-base.durationMinutes);if(extraDuration>0){job.durationMinutes=q.durationMinutes;job.finishAt=now+q.durationMinutes*60000;job.cost=q.cost;job.stage=q.stage;job.materials={...q.materials};const room=company.buildingState.rooms.find(r=>r.instanceId===job.buildingInstanceId);if(room){room.finishAt=job.finishAt;room.stage=q.stage;}}return job;}
export function runProgressiveBuildingExpansionTest(){const c={type:'Brauerei',money:1000000,land:{totalSqm:2000},buildingState:{rooms:[],equipment:[]},constructionSite:{materials:{concrete:1000,steel:1000,brick:1000,electrical:1000,pipes:1000,roofing:1000,insulation:1000},jobs:[],deliveries:[]}};const q1=progressiveBuildingQuote(c,'fermentation_house'),j1=startProgressiveBuildingConstruction(c,'fermentation_house',{now:0}),q2=progressiveBuildingQuote(c,'fermentation_house');if(q1.stage!==1||q2.stage!==2||q2.cost<=q1.cost||q2.materials.concrete<=q1.materials.concrete||q2.durationMinutes<=q1.durationMinutes)throw new Error('Gebäudestaffelung fehlerhaft');if(j1.cost!==q1.cost)throw new Error('Erste Gebäudestufe falsch berechnet');return true;}
if(typeof window!=='undefined')window.worldProgressiveBuildingExpansion={quote:progressiveBuildingQuote,materialNeed:progressiveBuildingMaterialNeed,start:startProgressiveBuildingConstruction,runTest:runProgressiveBuildingExpansionTest};
