// WorldProject - Qualitaetswirtschaft und faire Monats-Awards
export const QualityGrades={economy:{label:"Economy",factor:.88,priceFactor:.82},standard:{label:"Standard",factor:1,priceFactor:1},premium:{label:"Premium",factor:1.10,priceFactor:1.22},elite:{label:"Elite",factor:1.18,priceFactor:1.48}};
export class QualityEconomySystem{
 constructor({grades=QualityGrades}={}){this.grades=grades;this.batches=[];this.awards=[];}
 supplierOffer(supplier,material,grade="standard"){const g=this.grades[grade];if(!g)throw new Error("Unbekannte Qualitaetsstufe");const base=Number(supplier?.prices?.[material]||0);if(!base)throw new Error("Lieferant fuehrt Rohstoff nicht");return{supplierId:supplier.id,material,grade,quality:Math.min(1.25,Number(supplier.quality||1)*g.factor),unitPrice:base*g.priceFactor,label:g.label};}
 recordBatch({companyId,industry,product,quantity,rawQuality=1,machineQuality=1,employeeQuality=1,processQuality=1,finishedAt=Date.now()}={}){const quality=Math.max(0,Math.min(1.25,rawQuality*.42+machineQuality*.23+employeeQuality*.20+processQuality*.15)),b={companyId,industry,product,quantity:Number(quantity||0),quality,finishedAt};this.batches.push(b);return b;}
 monthlyAwards({year,month,coinReward=5}={}){const from=new Date(Date.UTC(year,month-1,1)).getTime(),to=new Date(Date.UTC(year,month,1)).getTime(),eligible=this.batches.filter(b=>b.finishedAt>=from&&b.finishedAt<to&&b.quantity>0),groups=new Map();for(const b of eligible){const key=`${b.industry}:${b.product}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(b);}const winners=[];for(const[key,rows]of groups){const byCompany=new Map();for(const b of rows){const x=byCompany.get(b.companyId)||{weighted:0,qty:0,best:0};x.weighted+=b.quality*b.quantity;x.qty+=b.quantity;x.best=Math.max(x.best,b.quality);byCompany.set(b.companyId,x);}const ranked=[...byCompany.entries()].map(([companyId,x])=>({companyId,quality:x.weighted/x.qty,bestBatchQuality:x.best,quantity:x.qty})).sort((a,b)=>b.quality-a.quality||b.bestBatchQuality-a.bestBatchQuality);if(ranked.length){const[industry,product]=key.split(":");winners.push({year,month,industry,product,...ranked[0],coinReward});}}this.awards.push(...winners);return winners;}
}
export function runQualityEconomyTest(){const q=new QualityEconomySystem(),supplier={id:"s",quality:.98,prices:{malt:1}},cheap=q.supplierOffer(supplier,"malt","economy"),elite=q.supplierOffer(supplier,"malt","elite");if(!(elite.quality>cheap.quality&&elite.unitPrice>cheap.unitPrice))throw new Error("Qualitaetseinkauf fehlerhaft");const now=Date.UTC(2026,7,10);q.recordBatch({companyId:1,industry:"brewery",product:"beer",quantity:10,rawQuality:1.2,machineQuality:1.1,employeeQuality:1.1,processQuality:1.1,finishedAt:now});q.recordBatch({companyId:2,industry:"brewery",product:"beer",quantity:10000,rawQuality:.95,machineQuality:1,employeeQuality:1,processQuality:1,finishedAt:now});const w=q.monthlyAwards({year:2026,month:8});if(w[0].companyId!==1)throw new Error("Award bevorzugt faelschlich Produktionsmenge");console.log("🏆 QUALITAETSEINKAUF + FAIRE MONATSAWARDS ERFOLGREICH");return true;}
