// WorldProject - normale Kundenauftraege sind der sichere Weg, Ruf aufzubauen.
// Keine Strafe fuer nicht angenommene Angebote; Ruf wird erst bei vollstaendiger Lieferung bewertet.
import { AdvancedEconomySystem } from './AdvancedEconomySystem.js';
import { ensureReputation,changeReputation } from './ReputationSystem.js';
function ts(v){if(v instanceof Date)return v.getTime();const n=Number(v);if(Number.isFinite(n)&&n>0)return n;const p=Date.parse(v);return Number.isFinite(p)?p:null;}
export function settleRegularCustomerReputation(company,order,{at=Date.now()}={}){ensureReputation(company);if(!order||order.reputationSettled||String(order.status)!=='completed')return null;const due=ts(order.dueAt??order.deliveryDeadline??order.deadline),onTime=!due||at<=due;order.reputationSettled=true;order.reputationOutcome=onTime?'on_time':'late';const delta=onTime?Math.max(1,Math.min(3,Math.round(Number(order.amount||order.quantity||0)/1500)+1)):0;if(delta<=0){order.reputationDelta=0;return{score:company.reputation.score,delta:0,onTime:false};}const result=changeReputation(company,delta,'Normalen Kundenauftrag pünktlich erfüllt');order.reputationDelta=result.delta;return{...result,onTime:true};}
const p=AdvancedEconomySystem.prototype;
if(!p.__worldRegularCustomerReputation){p.__worldRegularCustomerReputation=true;const old=p.deliverCustomerOrder;p.deliverCustomerOrder=function(company,orderId,amount){const result=old.call(this,company,orderId,amount);if(result?.success&&result?.completed){result.reputation=settleRegularCustomerReputation(company,result.order,{at:Date.now()});}return result;};}
export function runRegularCustomerReputationTest(){const now=100000,c={reputation:{score:30,history:[]}},o={status:'completed',amount:1000,dueAt:now+1000};const r=settleRegularCustomerReputation(c,o,{at:now});if(!r||r.delta<=0||c.reputation.score<=30)throw new Error('Pünktlicher Normalauftrag erhöht Ruf nicht');const late={status:'completed',amount:1000,dueAt:now-1};const before=c.reputation.score,r2=settleRegularCustomerReputation(c,late,{at:now});if(!r2||r2.delta!==0||c.reputation.score!==before)throw new Error('Verspäteter Normalauftrag darf keinen Pünktlichkeitsbonus geben');return true;}
if(typeof window!=='undefined')window.worldRegularCustomerReputation={settle:settleRegularCustomerReputation,test:runRegularCustomerReputationTest};
