// WorldProject - zentraler Unternehmensruf fuer Auftraege und Freischaltungen.
export const REPUTATION_MIN=0,REPUTATION_MAX=100;
export const REPUTATION_UNLOCKS=[{score:20,id:'basic_orders',label:'Normale Kundenaufträge'},{score:40,id:'urgent_orders',label:'Eilaufträge'},{score:60,id:'better_customers',label:'Bessere Geschäftskunden'},{score:80,id:'large_contracts',label:'Großaufträge & bevorzugte Kunden'},{score:95,id:'elite_contracts',label:'Premium-Verträge'}];
export function ensureReputation(company={}){company.reputation??={score:50,history:[]};company.reputation.score=Math.max(REPUTATION_MIN,Math.min(REPUTATION_MAX,Number(company.reputation.score)||0));company.reputation.history??=[];return company.reputation;}
export function reputationLevel(score=0){const n=Math.max(0,Math.min(100,Number(score)||0));if(n>=95)return{id:'excellent',label:'Ausgezeichnet'};if(n>=80)return{id:'very_good',label:'Sehr gut'};if(n>=60)return{id:'good',label:'Gut'};if(n>=40)return{id:'solid',label:'Solide'};if(n>=20)return{id:'weak',label:'Schwach'};return{id:'critical',label:'Kritisch'};}
export function reputationBenefits(score=0){const n=Math.max(0,Math.min(100,Number(score)||0)),unlocked=REPUTATION_UNLOCKS.filter(x=>n>=x.score),next=REPUTATION_UNLOCKS.find(x=>n<x.score)||null;return{unlocked,next,pointsToNext:next?next.score-n:0,priceFactor:n>=95?1.12:n>=80?1.08:n>=60?1.04:1,urgentOrderFactor:n>=95?1.35:n>=80?1.2:n>=60?1.1:1};}
export function hasReputation(company,required=0){return ensureReputation(company).score>=Number(required||0);}
export function changeReputation(company,delta,reason=''){const r=ensureReputation(company),before=r.score,requested=Number(delta)||0;r.score=Math.max(0,Math.min(100,before+requested));const applied=r.score-before;if(applied)r.history.push({at:Date.now(),delta:applied,reason,score:r.score});return{before,score:r.score,delta:applied,level:reputationLevel(r.score),benefits:reputationBenefits(r.score)};}
export function reputationSummary(company){const r=ensureReputation(company);return{score:r.score,level:reputationLevel(r.score),history:r.history,benefits:reputationBenefits(r.score)};}
export function runReputationSystemTest(){const c={},a=reputationSummary(c);if(a.score!==50||a.level.id!=='solid'||a.benefits.next?.score!==60)throw new Error('Ruf-Startwert fehlerhaft');changeReputation(c,20,'test');if(c.reputation.score!==70||reputationLevel(70).id!=='good'||reputationBenefits(70).priceFactor<=1)throw new Error('Rufsteigerung/Vorteil fehlerhaft');changeReputation(c,-100,'test');if(c.reputation.score!==0||hasReputation(c,20))throw new Error('Rufuntergrenze fehlerhaft');return true;}
if(typeof window!=='undefined')window.worldReputation={ensure:ensureReputation,change:changeReputation,summary:reputationSummary,level:reputationLevel,benefits:reputationBenefits,has:hasReputation,test:runReputationSystemTest};
