// Forschung & Entwicklung fuer alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureResearchDevelopment(c={}){c.researchDevelopment??={points:0,projects:[],unlocks:[],prototypes:[],branches:{}};return c.researchDevelopment;}
export function defineResearchBranch(c,{id,label,nodes=[]}={}){const r=ensureResearchDevelopment(c);r.branches[id]={id,label:label||id,nodes:nodes.map(x=>({id:x.id,label:x.label||x.id,cost:Math.max(0,n(x.cost)),durationHours:Math.max(1,n(x.durationHours,24)),prerequisites:x.prerequisites||[],bonus:x.bonus||{},unlock:x.unlock||null}))};return r.branches[id];}
export function addResearchPoints(c,points,source='operations'){const r=ensureResearchDevelopment(c);r.points+=Math.max(0,n(points));r.projects.push({kind:'points',points:n(points),source,at:Date.now()});return r.points;}
export function startResearchProject(c,branchId,nodeId,{now=Date.now()}={}){const r=ensureResearchDevelopment(c),branch=r.branches[branchId],node=branch?.nodes?.find(x=>x.id===nodeId);if(!node)throw new Error('Forschungsprojekt fehlt');if(r.unlocks.includes(nodeId))return{success:true,idempotent:true};if(!node.prerequisites.every(x=>r.unlocks.includes(x)))throw new Error('Voraussetzung fehlt');if(r.points<node.cost)throw new Error('Nicht genug Forschungspunkte');r.points-=node.cost;const p={id:`rd-${Date.now()}`,branchId,nodeId,status:'running',startedAt:now,endsAt:now+node.durationHours*3600000,cost:node.cost};r.projects.push(p);return{success:true,project:p};}
export function finishResearchProject(c,projectId,{now=Date.now(),force=false}={}){const r=ensureResearchDevelopment(c),p=r.projects.find(x=>x.id===projectId&&x.status==='running');if(!p)throw new Error('Forschungsprojekt fehlt');if(!force&&now<p.endsAt)throw new Error('Forschung laeuft noch');const node=r.branches[p.branchId].nodes.find(x=>x.id===p.nodeId);p.status='done';p.finishedAt=now;if(!r.unlocks.includes(node.id))r.unlocks.push(node.id);if(node.unlock&&!r.unlocks.includes(node.unlock))r.unlocks.push(node.unlock);return{project:p,bonus:node.bonus,unlock:node.unlock};}
export function createPrototype(c,{productId,cost=1000,durationHours=8,successChance=.8}={}){const r=ensureResearchDevelopment(c);if(n(c.money)<n(cost))throw new Error('Nicht genug Kapital');c.money-=n(cost);const p={id:`proto-${Date.now()}`,productId,cost:n(cost),durationHours:n(durationHours),successChance:clamp(n(successChance,.8),0,1),status:'running',startedAt:Date.now(),endsAt:Date.now()+n(durationHours)*3600000};r.prototypes.push(p);return p;}
export function resolvePrototype(c,id,{roll=.5,now=Date.now()}={}){const r=ensureResearchDevelopment(c),p=r.prototypes.find(x=>x.id===id);if(!p)throw new Error('Prototyp fehlt');if(now<p.endsAt)throw new Error('Prototyp noch nicht fertig');p.status=n(roll)<=p.successChance?'success':'failed';p.finishedAt=now;return p;}
export function researchBonuses(c){const r=ensureResearchDevelopment(c),out={capacityMultiplier:1,costMultiplier:1,qualityBonus:0};for(const id of r.unlocks){for(const b of Object.values(r.branches)){const node=b.nodes.find(x=>x.id===id);if(!node)continue;for(const[k,v]of Object.entries(node.bonus||{})){if(k.endsWith('Multiplier'))out[k]=n(out[k],1)*n(v,1);else out[k]=n(out[k])+n(v);}}}return out;}
