// WorldProject – Vertriebskanäle mit Gebühren, Reichweite, Marge und Zahlungsziel.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export const SalesChannels={direct:{label:'Direktverkauf',feeRate:.01,reach:.35,paymentDays:0,marginFactor:1.15},retail:{label:'Einzelhandel',feeRate:.04,reach:.7,paymentDays:14,marginFactor:1},wholesale:{label:'Großhandel',feeRate:.025,reach:.8,paymentDays:21,marginFactor:.88},online:{label:'Onlinehandel',feeRate:.08,reach:.9,paymentDays:7,marginFactor:1.06},marketplace:{label:'Plattform',feeRate:.12,reach:1,paymentDays:7,marginFactor:1.02},b2b:{label:'B2B-Vertrag',feeRate:.015,reach:.55,paymentDays:30,marginFactor:.95}};
export function ensureSalesChannels(c={}){c.salesChannels??={enabled:['direct'],history:[]};return c.salesChannels;}
export function enableSalesChannel(c,id){const s=ensureSalesChannels(c);if(!SalesChannels[id])throw new Error('Vertriebskanal fehlt');if(!s.enabled.includes(id))s.enabled.push(id);return s.enabled;}
export function disableSalesChannel(c,id){const s=ensureSalesChannels(c);s.enabled=s.enabled.filter(x=>x!==id);return s.enabled;}
export function channelQuote(c,{channelId='direct',baseUnitPrice,quantity=1}={}){const ch=SalesChannels[channelId];if(!ch)throw new Error('Vertriebskanal fehlt');const unit=n(baseUnitPrice)*n(ch.marginFactor,1),gross=unit*Math.max(0,n(quantity)),fee=gross*n(ch.feeRate),net=gross-fee;return{channelId,unitPrice:unit,quantity:n(quantity),gross,fee,net,paymentDays:ch.paymentDays,reach:ch.reach};}
export function recordChannelSale(c,{channelId='direct',baseUnitPrice,quantity=1,productId,now=Date.now()}={}){const s=ensureSalesChannels(c);if(!s.enabled.includes(channelId))throw new Error('Vertriebskanal nicht freigeschaltet');const q=channelQuote(c,{channelId,baseUnitPrice,quantity});s.history.push({...q,productId,at:now});c.salesLedger??=[];c.salesLedger.push({kind:'channel_sale',channelId,productId,revenue:q.net,fee:q.fee,at:now});return q;}
export function salesChannelKpis(c){const s=ensureSalesChannels(c),byChannel={};for(const row of s.history){const x=byChannel[row.channelId]??={sales:0,revenue:0,fees:0};x.sales++;x.revenue+=n(row.net);x.fees+=n(row.fee);byChannel[row.channelId]=x;}return{enabled:s.enabled.length,sales:s.history.length,byChannel,totalRevenue:s.history.reduce((a,x)=>a+n(x.net),0),totalFees:s.history.reduce((a,x)=>a+n(x.fee),0)};}
