// WorldProject – Saisonkalender für Nachfrage, Landwirtschaft, Personal und Logistik.
import { worldContentRegistry } from './ContentRegistry.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const CLIMATE={cool_temperate:{rain:.72},temperate:{rain:.62},warm_temperate:{rain:.50},continental:{rain:.45},mediterranean:{rain:.32},subtropical:{rain:.55},tropical:{rain:.82},dry_irrigated:{rain:.12}};
const SOIL={loam:{fertility:1,water:.82},sandy:{fertility:.78,water:.48},clay:{fertility:.94,water:.92},silt:{fertility:1.03,water:.78},peat:{fertility:.88,water:1},calcareous:{fertility:.86,water:.58}};
const BASE_CROPS={grow_wheat:{climateZones:['cool_temperate','temperate','warm_temperate','continental'],sowMonths:[3,4,9,10],harvestMonths:[7,8,9],waterNeed:'medium'},grow_barley:{climateZones:['cool_temperate','temperate','continental'],sowMonths:[3,4,9,10],harvestMonths:[7,8],waterNeed:'low'}};
const WATER={low:.36,medium:.58,high:.78};
export function ensureSeasonCalendar(c={}){c.seasonCalendar??={events:[],history:[]};return c.seasonCalendar;}
export function seasonForDate(date=new Date()){const m=date.getMonth()+1;return m<=2||m===12?'winter':m<=5?'spring':m<=8?'summer':'autumn';}
export function addSeasonEvent(c,{id,label,month,day=1,durationDays=1,demandMultiplier=1,staffMultiplier=1,transportMultiplier=1,harvestFor=[],nowYear=new Date().getFullYear()}={}){const s=ensureSeasonCalendar(c),start=new Date(nowYear,Math.max(0,n(month,1)-1),Math.max(1,n(day,1))).getTime(),row={id:id||`season-${start}`,label,startAt:start,endAt:start+Math.max(1,n(durationDays))*86400000,demandMultiplier:n(demandMultiplier,1),staffMultiplier:n(staffMultiplier,1),transportMultiplier:n(transportMultiplier,1),harvestFor:[...harvestFor]};s.events.push(row);return row;}
export function calendarModifiers(c,{now=Date.now()}={}){const s=ensureSeasonCalendar(c),active=s.events.filter(x=>x.startAt<=now&&x.endAt>=now);return{season:seasonForDate(new Date(now)),activeEvents:active,demandMultiplier:active.reduce((v,x)=>v*n(x.demandMultiplier,1),1),staffMultiplier:active.reduce((v,x)=>v*n(x.staffMultiplier,1),1),transportMultiplier:active.reduce((v,x)=>v*n(x.transportMultiplier,1),1),harvestProducts:[...new Set(active.flatMap(x=>x.harvestFor||[]))]};}
export function isHarvestWindow(c,productId,{now=Date.now()}={}){return calendarModifiers(c,{now}).harvestProducts.includes(productId);}
export function seasonalCalendarKpis(c){const s=ensureSeasonCalendar(c),m=calendarModifiers(c);return{events:s.events.length,active:m.activeEvents.length,season:m.season,demandMultiplier:m.demandMultiplier,transportMultiplier:m.transportMultiplier};}
export function agricultureEnvironment(c={}){const s=c.agricultureState||c.locationState||{};return{climateZone:s.climateZone||c.climateZone||'temperate',soilType:s.soilType||c.soilType||'loam',irrigation:Math.max(0,Math.min(1,n(s.irrigation??c.irrigation,0))),rainfallFactor:Math.max(.4,n(s.rainfallFactor,1))};}
export function cropMeta(recipe){return recipe?.cropMeta||BASE_CROPS[recipe?.id]||null;}
export function cropFamily(id=''){if(/wheat|barley|rye|oats|spelt|triticale/.test(id))return'cereal';if(/rapeseed|sunflower|flax/.test(id))return'oilseed';if(/peas|field_beans|soy|alfalfa/.test(id))return'legume';if(/potato|sugar_beet/.test(id))return'root';if(/corn/.test(id))return'corn';return id;}
export function cropSuitability(c,recipe,{month=(new Date()).getMonth()+1,previousCrop=null}={}){const meta=cropMeta(recipe);if(!meta)return{allowed:true,score:1,sowing:true,harvest:true,reasons:[]};const env=agricultureEnvironment(c),cl=CLIMATE[env.climateZone]||CLIMATE.temperate,soil=SOIL[env.soilType]||SOIL.loam,reasons=[],climateOk=(meta.climateZones||[]).includes(env.climateZone),sowing=(meta.sowMonths||[]).includes(Number(month)),harvest=(meta.harvestMonths||[]).includes(Number(month));if(!climateOk)reasons.push('Klima nur bedingt geeignet');if(!sowing&&!harvest)reasons.push('Außerhalb des Kulturfensters');const need=WATER[meta.waterNeed]??WATER.medium,available=Math.min(1.2,cl.rain*env.rainfallFactor+env.irrigation*.55),waterFactor=Math.max(.55,Math.min(1.08,available/need)),soilFactor=Math.max(.72,Math.min(1.08,soil.fertility*(meta.waterNeed==='high'?(.82+soil.water*.2):1))),rotationFactor=previousCrop&&cropFamily(previousCrop)===cropFamily(recipe.id)?.84:1;if(rotationFactor<1)reasons.push('Ungünstige Fruchtfolge');const score=Math.max(.25,Math.min(1.15,(climateOk?1:.68)*(sowing||harvest?1:.72)*waterFactor*soilFactor*rotationFactor));return{allowed:climateOk&&sowing,score,sowing,harvest,climateOk,waterFactor,soilFactor,rotationFactor,reasons,environment:env};}
export function availableFarmCrops(c,{month=(new Date()).getMonth()+1,previousCrop=null,includeMarginal=true}={}){return worldContentRegistry.list('recipes').filter(r=>(r.industries||[]).includes('farm')&&!r.deprecated).map(recipe=>({recipe,...cropSuitability(c,recipe,{month,previousCrop})})).filter(x=>includeMarginal?x.score>=.45:x.allowed).sort((a,b)=>b.score-a.score);}
export function expectedFarmYield(c,recipe,batches=1,options={}){const s=cropSuitability(c,recipe,options),base=Math.max(0,n(recipe?.output))*Math.max(0,n(batches));return{baseOutput:base,expectedOutput:Math.round(base*s.score),yieldFactor:s.score,suitability:s};}
export function runAgricultureSeasonTest(){const c={agricultureState:{climateZone:'temperate',soilType:'loam',irrigation:.2}},corn=worldContentRegistry.get('recipes','grow_corn'),rye=worldContentRegistry.get('recipes','grow_rye');if(!corn||!rye)throw new Error('Erweiterte Feldfrüchte fehlen');const may=cropSuitability(c,corn,{month:5}),jan=cropSuitability(c,corn,{month:1}),sep=cropSuitability(c,rye,{month:9,previousCrop:'grow_wheat'});if(!may.allowed||jan.allowed||!sep.allowed||!(sep.rotationFactor<1))throw new Error('Landwirtschafts-Saison-/Regionaltest fehlgeschlagen');return{success:true,may,jan,sep};}
