// Sicherheits-/Integritaetsschicht. Kritische Daten muessen serverseitig validiert werden.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureSecurityState(state={}){state.security??={requests:{},rate:{},audit:[],nonces:{}};return state.security;}
export function requestKey({actorId,action,requestId}={}){if(!actorId||!action||!requestId)throw new Error('Request-Identitaet unvollstaendig');return `${actorId}:${action}:${requestId}`;}
export function claimIdempotentRequest(state,request){const s=ensureSecurityState(state),key=requestKey(request);if(s.requests[key])return{accepted:false,idempotent:true,result:s.requests[key].result};s.requests[key]={at:Date.now(),status:'claimed',result:null};return{accepted:true,idempotent:false,key};}
export function completeIdempotentRequest(state,key,result){const s=ensureSecurityState(state);if(!s.requests[key])throw new Error('Request nicht geclaimt');s.requests[key].status='done';s.requests[key].result=result;return result;}
export function checkRateLimit(state,{actorId,bucket='default',limit=20,windowMs=60000,now=Date.now()}={}){const s=ensureSecurityState(state),key=`${actorId}:${bucket}`,row=s.rate[key]??={windowStart:now,count:0};if(now-row.windowStart>=windowMs){row.windowStart=now;row.count=0;}row.count++;s.rate[key]=row;return{ok:row.count<=Math.max(1,n(limit,20)),remaining:Math.max(0,n(limit,20)-row.count),resetAt:row.windowStart+windowMs};}
export function requireRole(actor,roles=[]){if(!actor||!roles.includes(actor.role))throw new Error('Berechtigung verweigert');return true;}
export function requireOwnership(actor,resource){if(actor?.role==='owner'||actor?.role==='admin')return true;if(!resource||String(resource.ownerId||resource.userId)!==String(actor?.id))throw new Error('Ressource gehoert anderem Spieler');return true;}
export function auditSecurityAction(state,{actorId,role,action,targetId=null,before=null,after=null,reason=null}={}){const s=ensureSecurityState(state),row={id:`sec-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,actorId,role,action,targetId,before,after,reason,at:Date.now()};s.audit.push(row);if(s.audit.length>10000)s.audit.splice(0,s.audit.length-10000);return row;}
export function validateMoneyMutation({before,delta,after,maxAbsDelta=1e9}={}){const b=n(before),d=n(delta),a=n(after);if(!Number.isFinite(b)||!Number.isFinite(d)||!Number.isFinite(a))return{ok:false,reason:'not_finite'};if(Math.abs(d)>maxAbsDelta)return{ok:false,reason:'delta_too_large'};if(Math.abs((b+d)-a)>.0001)return{ok:false,reason:'balance_mismatch'};return{ok:true};}
export function validateInventoryMutation({before,delta,after,allowNegative=false}={}){const b=n(before),d=n(delta),a=n(after);if(Math.abs((b+d)-a)>.0001)return{ok:false,reason:'quantity_mismatch'};if(!allowNegative&&a<0)return{ok:false,reason:'negative_inventory'};return{ok:true};}
export function issueNonce(state,{actorId,purpose,ttlMs=300000}={}){const s=ensureSecurityState(state),nonce=`${actorId}-${Date.now()}-${Math.random().toString(36).slice(2)}`;s.nonces[nonce]={actorId,purpose,expiresAt:Date.now()+ttlMs,used:false};return nonce;}
export function consumeNonce(state,nonce,{actorId,purpose}={}){const s=ensureSecurityState(state),row=s.nonces[nonce];if(!row||row.used||row.expiresAt<Date.now()||String(row.actorId)!==String(actorId)||row.purpose!==purpose)throw new Error('Ungueltiger Sicherheits-Nonce');row.used=true;row.usedAt=Date.now();return true;}
export function securityKpis(state){const s=ensureSecurityState(state);return{requests:Object.keys(s.requests).length,rateBuckets:Object.keys(s.rate).length,auditEntries:s.audit.length,activeNonces:Object.values(s.nonces).filter(x=>!x.used&&x.expiresAt>Date.now()).length};}
