// WorldProject - Personalbedarf, Schichten, Ueberstunden und Arbeitsplatzbesetzung
export class ShiftWorkforceSystem{
 constructor({vacationSystem=null}={}){this.vacationSystem=vacationSystem;this.shifts=[];this.assignments=[];this.seq=1;}
 createShift({companyId,name="Tagschicht",startHour=6,endHour=14,requiredWorkers=1}={}){const s={id:this.seq++,companyId,name,startHour,endHour,requiredWorkers:Number(requiredWorkers)};this.shifts.push(s);return s;}
 assign({shiftId,employeeId,workplaceId,skill=1}={}){const a={id:this.seq++,shiftId,employeeId,workplaceId,skill:Number(skill),active:true};this.assignments.push(a);return a;}
 staffing(shiftId,at=Date.now()){const shift=this.shifts.find(s=>s.id===shiftId);if(!shift)throw new Error("Schicht nicht gefunden");const assigned=this.assignments.filter(a=>a.shiftId===shiftId&&a.active),available=assigned.filter(a=>!this.vacationSystem||this.vacationSystem.isAvailable(a.employeeId,at));return{required:shift.requiredWorkers,assigned:assigned.length,available:available.length,missing:Math.max(0,shift.requiredWorkers-available.length),canOperate:available.length>=shift.requiredWorkers,workers:available};}
 overtime({employeeId,hours,hourlyWage,multiplier=1.25}={}){const h=Math.max(0,Number(hours)),cost=h*Number(hourlyWage)*Number(multiplier);return{employeeId,hours:h,multiplier,cost,capacityFactor:1+Math.min(.35,h*.04)};}
 requiredWorkers({baseWorkers=1,plannedOutput=0,baseOutput=1}={}){return Math.max(Number(baseWorkers),Math.ceil(Number(plannedOutput)/Math.max(1,Number(baseOutput))*Number(baseWorkers)));}
}
export function runShiftWorkforceTest(){const v={isAvailable:id=>id!==2},s=new ShiftWorkforceSystem({vacationSystem:v}),shift=s.createShift({companyId:1,requiredWorkers:2});s.assign({shiftId:shift.id,employeeId:1,workplaceId:"filler"});s.assign({shiftId:shift.id,employeeId:2,workplaceId:"filler"});if(s.staffing(shift.id).canOperate)throw new Error("Urlaub wurde bei Schichtbesetzung ignoriert");const o=s.overtime({employeeId:1,hours:2,hourlyWage:20});if(o.cost!==50)throw new Error("Ueberstunden-Test fehlgeschlagen");console.log("👷 SCHICHTEN/PERSONALBEDARF/UEBERSTUNDEN ERFOLGREICH");return true;}
