// WorldProject – sichtbarer KI-Investitionsmarkt fuer Solaranlagen.
import { SolarOffers,solarState,buySolar,electricityQuote } from './SolarInvestmentSystem.js';
const money=v=>Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
function company(){return window.worldPlayerCompany||window.worldActiveServerCompany||null;}
export class SolarInvestmentDialog{
 constructor(){this.overlay=null;}
 open(){if(this.overlay)return;const c=company();if(!c)return alert('Kein aktiver Betrieb');const ov=document.createElement('div');Object.assign(ov.style,{position:'fixed',inset:0,zIndex:26000,background:'rgba(0,0,0,.78)',display:'flex',alignItems:'center',justifyContent:'center',padding:'18px'});const p=document.createElement('div');Object.assign(p.style,{width:'min(1100px,98vw)',maxHeight:'94vh',overflow:'auto',background:'#1f2937',color:'#fff',padding:'20px',borderRadius:'14px',fontFamily:'Arial,sans-serif'});ov.append(p);document.body.append(ov);this.overlay=ov;this.render(p,c);}
 close(){this.overlay?.remove();this.overlay=null;}
 button(text,fn){const b=document.createElement('button');b.textContent=text;Object.assign(b.style,{padding:'9px 12px',border:0,borderRadius:'8px',fontWeight:'700',cursor:'pointer',margin:'4px'});b.onclick=fn;return b;}
 render(p,c){p.innerHTML='';const s=solarState(c),head=document.createElement('div');Object.assign(head.style,{display:'flex',justifyContent:'space-between',alignItems:'center'});const h=document.createElement('h2');h.textContent='☀️ KI-Markt · Solaranlagen';head.append(h,this.button('✕ Schließen',()=>this.close()));p.append(head);const summary=document.createElement('div');summary.textContent=`Installiert: ${s.installedKwp.toLocaleString('de-DE')} kWp · bisher investiert: ${money(s.invested)} · Spielgeld: ${money(c.money)}`;p.append(summary);const hint=document.createElement('div');hint.textContent='Anlagen sind additiv: Kleine Spieler können klein anfangen und später beliebig erweitern. Die tatsächliche Ersparnis hängt von Strombedarf und später auch Tageszeit/Wetter ab.';Object.assign(hint.style,{padding:'10px',margin:'10px 0',background:'#374151',borderRadius:'8px'});p.append(hint);const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(230px,1fr))',gap:'10px'});for(const o of SolarOffers){const card=document.createElement('div');Object.assign(card.style,{background:'#111827',padding:'13px',borderRadius:'10px',border:'1px solid #4b5563'});const title=document.createElement('strong');title.textContent=o.label;const info=document.createElement('div');info.innerHTML=`${o.kwp.toLocaleString('de-DE')} kWp<br>${money(o.price)}<br>Flächenbedarf ca. ${o.areaM2.toLocaleString('de-DE')} m²`;const example=electricityQuote({...c,solar:{...s,installedKwp:o.kwp,installations:[],invested:0}},{demandKw:o.kwp,hours:1,gridPricePerKwh:.30,productionFactor:1});const saving=document.createElement('div');saving.textContent=`Max. Beispielersparnis bei 0,30 €/kWh: ${money(example.savedCost)} je voller Erzeugungsstunde`;saving.style.fontSize='12px';saving.style.marginTop='7px';card.append(title,info,saving,this.button('Anlage kaufen',()=>{try{buySolar(c,o.id);this.render(p,c);}catch(e){alert(e.message);}}));grid.append(card);}p.append(grid);}
}
if(typeof window!=='undefined'){window.worldSolarInvestmentDialog=window.worldSolarInvestmentDialog||new SolarInvestmentDialog();window.openWorldSolarMarket=()=>window.worldSolarInvestmentDialog.open();}
