// WorldProject – Supportfälle mit internen Notizen, Eskalation und Kulanz.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const trim=(a,max)=>{if(a.length>max)a.splice(0,a.length-max);return a;};
const text=(v,label)=>{const s=String(v||"").trim();if(!s)throw new Error(`${label} fehlt`);return s;};
const priorities=new Set(["low","normal","high","urgent"]);
export function ensureSupportState(world={}){world.supportState??={cases:[],messages:[],compensations:[]};for(const k of ["cases","messages","compensations"])if(!Array.isArray(world.supportState[k]))world.supportState[k]=[];return world.supportState;}
export function openSupportCase(world,{playerId,subject,category="gameplay",description="",priority="normal",now=Date.now()}={}){const s=ensureSupportState(world),cleanPriority=priorities.has(priority)?priority:"normal",row={id:`support-${now}-${Math.random().toString(36).slice(2,7)}`,playerId:text(playerId,"Spieler"),subject:text(subject,"Betreff"),category:String(category||"gameplay"),description:String(description||"").trim(),priority:cleanPriority,status:"open",assignedTo:null,createdAt:now,updatedAt:now};s.cases.push(row);trim(s.cases,10000);return row;}
export function assignSupportCase(world,{actor,caseId,staffId=null,now=Date.now()}={}){adminControlSystem.requirePermission(actor,"support.write");const c=ensureSupportState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");c.assignedTo=staffId||actor.id;c.status="in_progress";c.updatedAt=now;adminControlSystem.log(actor,"support_assigned",{caseId,staffId:c.assignedTo});return c;}
export function addSupportMessage(world,{actor=null,playerId=null,caseId,text:message,internal=false,now=Date.now()}={}){const s=ensureSupportState(world),c=s.cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");if(c.status==="closed")throw new Error("Supportfall ist bereits geschlossen");if(internal){adminControlSystem.requirePermission(actor,"support.write");}else if(actor){adminControlSystem.requirePermission(actor,"support.write");}else if(c.playerId!==playerId)throw new Error("Supportfall gehört anderem Spieler");const row={id:`supportmsg-${now}-${Math.random().toString(36).slice(2,5)}`,caseId,text:text(message,"Nachricht"),internal:!!internal,authorType:actor?"staff":"player",authorId:actor?.id||playerId,at:now};s.messages.push(row);trim(s.messages,50000);c.updatedAt=now;if(!internal)c.status=actor?"waiting_player":"waiting_staff";if(actor)adminControlSystem.log(actor,internal?"support_internal_note":"support_reply",{caseId,messageId:row.id});return row;}
export function setSupportPriority(world,{actor,caseId,priority}={}){adminControlSystem.requirePermission(actor,"support.write");if(!priorities.has(priority))throw new Error("Unbekannte Support-Priorität");const c=ensureSupportState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");const before=c.priority;c.priority=priority;c.updatedAt=Date.now();adminControlSystem.log(actor,"support_priority_changed",{caseId,before,after:priority});return c;}
export function reopenSupportCase(world,{actor,caseId,reason="",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"support.write");const c=ensureSupportState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");const before=c.status;c.status="in_progress";c.closedAt=null;c.closedBy=null;c.resolution=null;c.updatedAt=now;adminControlSystem.log(actor,"support_reopened",{caseId,before,reason:String(reason||"").trim()});return c;}
export function closeSupportCase(world,{actor,caseId,resolution="resolved",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"support.write");const c=ensureSupportState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");c.status="closed";c.resolution=text(resolution,"Lösung");c.closedAt=now;c.closedBy=actor.id;c.updatedAt=now;adminControlSystem.log(actor,"support_closed",{caseId,resolution:c.resolution});return c;}
export function compensatePlayer(world,{actor,caseId,player=null,company=null,money=0,coins=0,item=null,quantity=0,reason="Kulanz",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"support.write");const s=ensureSupportState(world),c=s.cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");const cleanReason=text(reason,"Begründung"),m=Math.max(0,n(money)),co=Math.max(0,n(coins)),q=Math.max(0,n(quantity));if(!m&&!co&&!(item&&q))throw new Error("Keine Kulanzleistung angegeben");const comp={id:`comp-${now}-${Math.random().toString(36).slice(2,6)}`,caseId,playerId:c.playerId,money:m,coins:co,item:item||null,quantity:q,reason:cleanReason,actorId:actor.id,at:now};if(company&&comp.money)company.money=n(company.money)+comp.money;if(player&&comp.coins)player.coins=n(player.coins)+comp.coins;if(company&&comp.item&&comp.quantity){company.inventory??={};company.inventory[comp.item]=n(company.inventory[comp.item])+comp.quantity;}s.compensations.push(comp);trim(s.compensations,20000);c.updatedAt=now;adminControlSystem.log(actor,"support_compensation",comp);return comp;}
export function linkSupportToModeration(world,{actor,caseId,moderationCaseId}={}){adminControlSystem.requirePermission(actor,"support.write");const c=ensureSupportState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");c.moderationCaseId=text(moderationCaseId,"Moderationsfall");c.updatedAt=Date.now();adminControlSystem.log(actor,"support_moderation_linked",{caseId,moderationCaseId:c.moderationCaseId});return c;}
export function supportKpis(world){const s=ensureSupportState(world);return{open:s.cases.filter(x=>x.status!=="closed").length,waitingStaff:s.cases.filter(x=>x.status==="waiting_staff").length,waitingPlayer:s.cases.filter(x=>x.status==="waiting_player").length,urgent:s.cases.filter(x=>x.status!=="closed"&&["high","urgent"].includes(x.priority)).length,compensations:s.compensations.length};}
