// WorldProject - Liefervertraege zwischen Spielerbetrieben
export class SupplyContractSystem{
 constructor(){this.contracts=[];this.deliveries=[];this.seq=1;}
 create({supplierCompanyId,buyerCompanyId,item,quality="standard",quantity,unitPrice,intervalDays=7,startAt=Date.now(),endAt=null,penaltyRate=.05}={}){if(supplierCompanyId===buyerCompanyId)throw new Error("Liefervertrag mit eigenem Betrieb nicht erlaubt");if(Number(quantity)<=0||Number(unitPrice)<=0||Number(intervalDays)<=0)throw new Error("Ungueltige Vertragswerte");const c={id:this.seq++,supplierCompanyId,buyerCompanyId,item,quality,quantity:Number(quantity),unitPrice:Number(unitPrice),intervalDays:Number(intervalDays),startAt:Number(startAt),endAt:endAt?Number(endAt):null,penaltyRate:Number(penaltyRate),status:"active",nextDueAt:Number(startAt),fulfilled:0,missed:0,createdAt:Date.now()};this.contracts.push(c);return c;}
 due(now=Date.now()){return this.contracts.filter(c=>c.status==="active"&&c.nextDueAt<=now&&(!c.endAt||now<=c.endAt));}
 fulfill(id,{now=Date.now(),transfer=null}={}){const c=this.contracts.find(x=>x.id===id&&x.status==="active");if(!c)throw new Error("Liefervertrag nicht aktiv");const total=c.quantity*c.unitPrice,d={contractId:c.id,supplierCompanyId:c.supplierCompanyId,buyerCompanyId:c.buyerCompanyId,item:c.item,quality:c.quality,quantity:c.quantity,unitPrice:c.unitPrice,total,deliveredAt:now};if(typeof transfer==="function")transfer(d);this.deliveries.push(d);c.fulfilled++;c.nextDueAt+=c.intervalDays*86400000;if(c.endAt&&c.nextDueAt>c.endAt)c.status="completed";return d;}
 miss(id,{now=Date.now(),applyPenalty=null}={}){const c=this.contracts.find(x=>x.id===id&&x.status==="active");if(!c)throw new Error("Liefervertrag nicht aktiv");const penalty=c.quantity*c.unitPrice*c.penaltyRate;c.missed++;if(typeof applyPenalty==="function")applyPenalty({contract:c,penalty,at:now});c.nextDueAt+=c.intervalDays*86400000;return{contractId:id,penalty,at:now};}
 cancel(id,companyId){const c=this.contracts.find(x=>x.id===id&&x.status==="active"&&(x.supplierCompanyId===companyId||x.buyerCompanyId===companyId));if(!c)return false;c.status="cancelled";return true;}
}
export function runSupplyContractTest(){const s=new SupplyContractSystem(),c=s.create({supplierCompanyId:1,buyerCompanyId:2,item:"wood",quality:"premium",quantity:100,unitPrice:5,intervalDays:7,startAt:0});const d=s.fulfill(c.id,{now:0});if(d.total!==500||c.nextDueAt!==604800000||c.fulfilled!==1)throw new Error("Liefervertrag-Test fehlgeschlagen");console.log("📑 SPIELER-LIEFERVERTRAEGE ERFOLGREICH");return true;}
