// WorldProject - Einkauf -> Lieferung -> Lager -> Produktion
// Balancingwerte sind bewusst vorläufig und werden im Spieltest angepasst.

export const IndustryMaterials={
 brewery:["malt","hops","yeast","water","bottles","caps","labels"],
 carpentry:["softwood","hardwood","plywood","glue","varnish","screws","packaging"],
 bakery:["flour","yeast","sugar","salt","butter","packaging"],
 butcher:["meat","spices","salt","casings","packaging"],
 general:["packaging"]
};

export function materialsForIndustry(industry="general"){return IndustryMaterials[industry]||IndustryMaterials.general;}

export class SupplyProductionChainSystem{
 constructor(company={}){this.company=company;this.orders=company.supplyOrders||[];this.warehouse=company.warehouseZones||{raw:{capacity:1000,stock:{}},packaging:{capacity:1000,stock:{}},finished:{capacity:1000,stock:{}}};this.queue=company.productionQueue||[];}
 suppliersFor(material,suppliers=[]){return suppliers.filter(s=>(s.materials||[]).includes(material)).map(s=>this.quote(s,material,1));}
 quote(supplier,material,qty){const q=Math.max(1,Number(qty||1)),base=Number(supplier.prices?.[material]||0),market=Number(supplier.marketFactor||1),discount=q>=1000?.10:q>=500?.06:q>=100?.03:0,goods=base*market*q*(1-discount),transport=Number(supplier.deliveryBase||0)+Number(supplier.distanceKm||0)*Number(supplier.deliveryPerKm||0);return {supplierId:supplier.id,material,qty,unitPrice:base*market*(1-discount),goodsCost:goods,transportCost:transport,totalCost:goods+transport,discount,distanceKm:Number(supplier.distanceKm||0),leadHours:Number(supplier.leadHours||1),reliability:Number(supplier.reliability??1),quality:Number(supplier.quality??1)};}
 createOrder({supplier,material,qty,mode="delivery",vehicle=null}){if(!materialsForIndustry(this.company.industry).includes(material))throw new Error("Rohstoff passt nicht zur Branche");const quote=this.quote(supplier,material,qty);if(mode==="pickup"&&!vehicle)throw new Error("Für Eigenabholung muss ein Fahrzeug gewählt werden");const order={id:`ord_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,status:mode==="pickup"?"awaiting_pickup":"ordered",mode,vehicleId:vehicle?.id||null,quote,createdAt:Date.now(),eta:Date.now()+quote.leadHours*3600000};this.orders.push(order);this.sync();return order;}
 progressOrders(now=Date.now()){for(const o of this.orders){if(["received","cancelled"].includes(o.status))continue;if(now>=o.eta)o.status="arrived";else if(o.status==="ordered")o.status="in_transit";}this.sync();return this.orders;}
 receive(orderId,zone="raw"){const o=this.orders.find(x=>x.id===orderId);if(!o||o.status!=="arrived")throw new Error("Lieferung ist noch nicht im Wareneingang");const z=this.warehouse[zone];if(!z)throw new Error("Lagerbereich fehlt");const used=Object.values(z.stock).reduce((a,b)=>a+Number(b||0),0);if(used+o.quote.qty>z.capacity)throw new Error("Nicht genügend Lagerkapazität");z.stock[o.quote.material]=Number(z.stock[o.quote.material]||0)+o.quote.qty;o.status="received";o.receivedAt=Date.now();this.sync();return o;}
 planProduction({product,batches=1,recipe,machine}){const b=Math.max(1,Number(batches||1)),missing={};for(const [m,q] of Object.entries(recipe.inputs||{})){const need=q*b,have=Number(this.warehouse.raw.stock[m]||this.warehouse.packaging.stock[m]||0);if(have<need)missing[m]=need-have;}return {product,batches,durationMinutes:Number(recipe.minutes||0)*b,machineId:machine?.id||null,inputs:Object.fromEntries(Object.entries(recipe.inputs||{}).map(([m,q])=>[m,q*b])),missing,ready:Object.keys(missing).length===0,cost:Number(recipe.cost||0)*b};}
 enqueueProduction(plan){if(!plan.ready)throw new Error(`Fehlende Rohstoffe: ${Object.entries(plan.missing).map(([k,v])=>`${k} ${v}`).join(", ")}`);if(!plan.machineId)throw new Error("Keine Produktionsmaschine gewählt");if(this.queue.some(x=>x.machineId===plan.machineId&&x.status==="running"))throw new Error("Maschine ist bereits belegt");for(const[m,q]of Object.entries(plan.inputs)){const z=this.warehouse.raw.stock[m]!=null?this.warehouse.raw:this.warehouse.packaging;z.stock[m]=Number(z.stock[m]||0)-q;}const job={...plan,id:`prod_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,status:"queued",createdAt:Date.now()};this.queue.push(job);this.sync();return job;}
 startNext(machineId,now=Date.now()){if(this.queue.some(x=>x.machineId===machineId&&x.status==="running"))return null;const j=this.queue.find(x=>x.machineId===machineId&&x.status==="queued");if(!j)return null;j.status="running";j.startedAt=now;j.endsAt=now+j.durationMinutes*60000;this.sync();return j;}
 finishProduction(now=Date.now()){for(const j of this.queue.filter(x=>x.status==="running"&&x.endsAt<=now)){const z=this.warehouse.finished,used=Object.values(z.stock).reduce((a,b)=>a+Number(b||0),0),qty=j.batches;if(used+qty>z.capacity){j.status="waiting_storage";continue;}z.stock[j.product]=Number(z.stock[j.product]||0)+qty;j.status="finished";j.finishedAt=now;}this.sync();return this.queue;}
 sync(){this.company.supplyOrders=this.orders;this.company.warehouseZones=this.warehouse;this.company.productionQueue=this.queue;return this.company;}
}

export function validateVehicleCapacity(vehicle,{weightKg=0,pallets=0,volumeM3=0}={}){const reasons=[];if(weightKg>Number(vehicle?.payloadKg||0))reasons.push("Nutzlast");if(pallets>Number(vehicle?.palletCapacity||0))reasons.push("Palettenplätze");if(volumeM3>Number(vehicle?.volumeM3||Infinity))reasons.push("Volumen");return {allowed:reasons.length===0,reasons};}

export function runSupplyProductionChainTest(){const c={industry:"brewery"},s=new SupplyProductionChainSystem(c),supplier={id:"malzwerk",materials:["malt"],prices:{malt:1},distanceKm:20,deliveryBase:10,deliveryPerKm:.5,leadHours:1,reliability:.98,quality:.95};const o=s.createOrder({supplier,material:"malt",qty:100});o.eta=0;s.progressOrders(1);s.receive(o.id);const p=s.planProduction({product:"beer",batches:2,recipe:{inputs:{malt:10},minutes:60,cost:25},machine:{id:"brew1"}});s.enqueueProduction(p);s.startNext("brew1",0);s.finishProduction(99999999);if(s.warehouse.finished.stock.beer!==2)throw new Error("Supply-/Produktionskette fehlerhaft");console.log("✅ EINKAUF-/LAGER-/PRODUKTIONSKETTEN-TEST ERFOLGREICH");}
