// WorldProject – Supportfälle mit internen Notizen, Eskalation und Kulanz.
import { adminControlSystem } from "./AdminControlSystem.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureSupportState(world={}){world.supportState??={cases:[],messages:[],compensations:[]};return world.supportState;}
export function openSupportCase(world,{playerId,subject,category="gameplay",description="",priority="normal",now=Date.now()}={}){const s=ensureSupportState(world),row={id:`support-${now}-${Math.random().toString(36).slice(2,7)}`,playerId,subject,category,description,priority,status:"open",assignedTo:null,createdAt:now,updatedAt:now};s.cases.push(row);return row;}
export function assignSupportCase(world,{actor,caseId,staffId=null,now=Date.now()}={}){adminControlSystem.requirePermission(actor,"support.write");const c=ensureSupportState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");c.assignedTo=staffId||actor.id;c.status="in_progress";c.updatedAt=now;adminControlSystem.log(actor,"support_assigned",{caseId,staffId:c.assignedTo});return c;}
export function addSupportMessage(world,{actor=null,playerId=null,caseId,text,internal=false,now=Date.now()}={}){const s=ensureSupportState(world),c=s.cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");if(internal){adminControlSystem.requirePermission(actor,"support.write");}else if(actor){adminControlSystem.requirePermission(actor,"support.write");}else if(c.playerId!==playerId)throw new Error("Supportfall gehört anderem Spieler");const row={id:`supportmsg-${now}-${Math.random().toString(36).slice(2,5)}`,caseId,text,internal,authorType:actor?"staff":"player",authorId:actor?.id||playerId,at:now};s.messages.push(row);c.updatedAt=now;if(!internal)c.status=actor?"waiting_player":"waiting_staff";return row;}
export function setSupportPriority(world,{actor,caseId,priority}={}){adminControlSystem.requirePermission(actor,"support.write");const c=ensureSupportState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");c.priority=priority;c.updatedAt=Date.now();return c;}
export function closeSupportCase(world,{actor,caseId,resolution="resolved",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"support.write");const c=ensureSupportState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");c.status="closed";c.resolution=resolution;c.closedAt=now;c.closedBy=actor.id;c.updatedAt=now;adminControlSystem.log(actor,"support_closed",{caseId,resolution});return c;}
export function compensatePlayer(world,{actor,caseId,player=null,company=null,money=0,coins=0,item=null,quantity=0,reason="Kulanz",now=Date.now()}={}){adminControlSystem.requirePermission(actor,"support.write");const s=ensureSupportState(world),c=s.cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");const comp={id:`comp-${now}-${Math.random().toString(36).slice(2,6)}`,caseId,playerId:c.playerId,money:Math.max(0,n(money)),coins:Math.max(0,n(coins)),item,quantity:Math.max(0,n(quantity)),reason,actorId:actor.id,at:now};if(company&&comp.money)company.money=n(company.money)+comp.money;if(player&&comp.coins)player.coins=n(player.coins)+comp.coins;if(company&&item&&comp.quantity){company.inventory??={};company.inventory[item]=n(company.inventory[item])+comp.quantity;}s.compensations.push(comp);adminControlSystem.log(actor,"support_compensation",comp);return comp;}
export function linkSupportToModeration(world,{actor,caseId,moderationCaseId}={}){adminControlSystem.requirePermission(actor,"support.write");const c=ensureSupportState(world).cases.find(x=>x.id===caseId);if(!c)throw new Error("Supportfall fehlt");c.moderationCaseId=moderationCaseId;return c;}
export function supportKpis(world){const s=ensureSupportState(world);return{open:s.cases.filter(x=>x.status!=="closed").length,waitingStaff:s.cases.filter(x=>x.status==="waiting_staff").length,urgent:s.cases.filter(x=>x.status!=="closed"&&["high","urgent"].includes(x.priority)).length,compensations:s.compensations.length};}
