// WorldProject – Lieferantenmanagement: Score, Ausfallrisiko, Alternativen, Historie, Eskalation.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureSupplierManagement(c={}){c.supplierManagement??={suppliers:{},history:[],incidents:[]};return c.supplierManagement;}
export function registerSupplier(c,supplier){const s=ensureSupplierManagement(c),id=supplier.id;if(!id)throw new Error("Lieferanten-ID fehlt");s.suppliers[id]??={id,label:supplier.label||id,quality:n(supplier.quality,.9),reliability:n(supplier.reliability,.9),priceIndex:1,deliveries:0,lateDeliveries:0,rejections:0,active:true,blockedUntil:0};return s.suppliers[id];}
export function recordSupplierDelivery(c,supplierId,{onTime=true,quality=1,priceIndex=1,rejected=false,at=Date.now()}={}){const s=ensureSupplierManagement(c),r=s.suppliers[supplierId]||registerSupplier(c,{id:supplierId});r.deliveries++;if(!onTime)r.lateDeliveries++;if(rejected)r.rejections++;r.quality=clamp(r.quality*.9+n(quality,1)*.1,0,1);r.reliability=clamp(r.reliability*.9+(onTime?1:.2)*.1,0,1);r.priceIndex=clamp(r.priceIndex*.85+n(priceIndex,1)*.15,.2,5);s.history.push({supplierId,onTime,quality:n(quality,1),priceIndex:n(priceIndex,1),rejected,at});return r;}
export function supplierScore(c,supplierId){const r=ensureSupplierManagement(c).suppliers[supplierId];if(!r)return 0;const onTimeRate=r.deliveries?(r.deliveries-r.lateDeliveries)/r.deliveries:r.reliability,rejectRate=r.deliveries?r.rejections/r.deliveries:0;return clamp((r.quality*.35+onTimeRate*.35+(1-Math.min(1,Math.max(0,r.priceIndex-1)))*.2+(1-rejectRate)*.1)*100,0,100);}
export function supplierRisk(c,supplierId){const r=ensureSupplierManagement(c).suppliers[supplierId];if(!r)return 1;return clamp((1-r.reliability)*.45+(1-r.quality)*.3+Math.min(1,r.lateDeliveries/Math.max(1,r.deliveries))*.2+(r.active?0:.5),0,1);}
export function blockSupplier(c,supplierId,{days=7,reason="Qualitäts-/Lieferproblem",now=Date.now()}={}){const s=ensureSupplierManagement(c),r=s.suppliers[supplierId]||registerSupplier(c,{id:supplierId});r.active=false;r.blockedUntil=now+Math.max(1,n(days))*86400000;s.incidents.push({supplierId,reason,blockedUntil:r.blockedUntil,at:now});return r;}
export function refreshSupplierBlocks(c,{now=Date.now()}={}){const s=ensureSupplierManagement(c);for(const r of Object.values(s.suppliers))if(!r.active&&r.blockedUntil&&r.blockedUntil<=now){r.active=true;r.blockedUntil=0;}return s;}
export function rankedSuppliers(c,supplierIds=[]){refreshSupplierBlocks(c);return supplierIds.map(id=>({id,score:supplierScore(c,id),risk:supplierRisk(c,id),supplier:ensureSupplierManagement(c).suppliers[id]})).filter(x=>x.supplier?.active).sort((a,b)=>b.score-a.score||a.risk-b.risk);}
export function chooseFallbackSupplier(c,primaryId,candidateIds=[]){const rows=rankedSuppliers(c,candidateIds.filter(id=>id!==primaryId));return rows[0]||null;}
export function supplierKpis(c){const s=ensureSupplierManagement(c),rows=Object.values(s.suppliers);return{suppliers:rows.length,active:rows.filter(x=>x.active).length,blocked:rows.filter(x=>!x.active).length,averageScore:rows.length?rows.reduce((a,x)=>a+supplierScore(c,x.id),0)/rows.length:0,highRisk:rows.filter(x=>supplierRisk(c,x.id)>=.5).length,incidents:s.incidents.length};}
