// WorldProject – zentraler Systemmonitor für Betriebs-/Releasegesundheit.
import { equipmentSetupVM } from './IndustryEquipmentMarketplace.js';
import { missingRequiredRoles } from './IndustryRecruitmentAvailability.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureSystemMonitor(world={}){world.systemMonitor??={events:[],modules:{},alerts:[]};return world.systemMonitor;}
export function recordModuleHealth(world,module,{healthy=true,detail=null,latencyMs=null}={}){const m=ensureSystemMonitor(world),row={module,healthy:!!healthy,detail,latencyMs:latencyMs==null?null:n(latencyMs),at:Date.now()};m.modules[module]=row;m.events.push(row);if(!row.healthy)m.alerts.push({kind:'module_unhealthy',module,detail,at:row.at,severity:'high'});if(row.latencyMs!=null&&row.latencyMs>1000)m.alerts.push({kind:'module_slow',module,latencyMs:row.latencyMs,at:row.at,severity:'medium'});if(m.events.length>5000)m.events.splice(0,m.events.length-5000);return row;}
export function recordOperationalAlert(world,{kind,module='unknown',severity='medium',detail=null}={}){const m=ensureSystemMonitor(world),row={kind,module,severity,detail,at:Date.now(),resolved:false};m.alerts.push(row);return row;}
export function resolveOperationalAlert(world,index){const m=ensureSystemMonitor(world),a=m.alerts[index];if(a){a.resolved=true;a.resolvedAt=Date.now();}return a;}
export function companyOperationalHealth(company,{now=Date.now()}={}){const deliveries=company?.operationalSupplyState?.orders||company?.inboundDeliveries||company?.deliveries||[],jobs=company?.operationalSupplyState?.productionQueue||company?.productionJobs||[],overdueDeliveries=deliveries.filter(x=>{const eta=Number(x.eta||x.arrivalAt||x.expectedAt);return Number.isFinite(eta)&&eta<now&&!['arrived','ready_for_receipt','received','stored','completed','cancelled'].includes(x.status);}),awaitingReceipt=deliveries.filter(x=>['arrived','ready_for_receipt'].includes(x.status)),blockedProduction=jobs.filter(x=>x.storageBlocked||x.status==='blocked'),invalidMoney=!Number.isFinite(Number(company?.money)),missingEquipment=equipmentSetupVM(company).missingRequired||[],missingSpecialists=missingRequiredRoles(company);return{healthy:!invalidMoney&&!overdueDeliveries.length&&!blockedProduction.length&&!missingEquipment.length&&!missingSpecialists.length,invalidMoney,overdueDeliveries:overdueDeliveries.length,awaitingReceipt:awaitingReceipt.length,blockedProduction:blockedProduction.length,missingEquipment:missingEquipment.length,missingSpecialists:missingSpecialists.length,openDeliveries:deliveries.filter(x=>!['received','stored','completed','cancelled'].includes(x.status)).length,runningProduction:jobs.filter(x=>x.status==='running').length};}
export function systemHealthSummary(world){const m=ensureSystemMonitor(world),mods=Object.values(m.modules),active=m.alerts.filter(x=>!x.resolved),healthy=mods.filter(x=>x.healthy).length;return{modules:mods.length,healthy,unhealthy:mods.length-healthy,activeAlerts:active.length,critical:active.filter(x=>x.severity==='critical').length,high:active.filter(x=>x.severity==='high').length,score:mods.length?Math.max(0,Math.round(100-(mods.length-healthy)/mods.length*60-active.length*2)):100};}
if(typeof window!=='undefined')window.worldSystemOperationsMonitor={ensure:ensureSystemMonitor,record:recordModuleHealth,alert:recordOperationalAlert,resolve:resolveOperationalAlert,company:companyOperationalHealth,summary:systemHealthSummary};
