// WorldProject – vereinfachte Steuer-/Regulatoriklogik für Langzeitwirtschaft.
import { getIndustryProfile } from './IndustryCatalog.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const REG={brewery:.18,beverage:.15,bakery:.12,butcher:.2,food:.18,farm:.08,livestock:.14,orchard:.09,carpentry:.08,mechanical:.1,metal:.11,plastic:.13,retail:.07,wholesale:.06,online_retail:.05};
export function ensureTax(c={}){c.taxState??={periods:[],payments:[],audits:[],arrears:0,reserve:0,lastFiledAt:null};return c.taxState;}
export function regulatoryLoad(c){const k=c.branchKey||getIndustryProfile(c).branchKey;return REG[k]??.1;}
export function estimateTaxLiability(c,{revenue=0,profit=0,vatRate=.19,profitTaxRate=.3}={}){const load=regulatoryLoad(c),vat=Math.max(0,n(revenue))*n(vatRate),profitTax=Math.max(0,n(profit))*n(profitTaxRate),complianceCost=Math.max(0,n(revenue))*load*.002;return{vat,profitTax,complianceCost,total:vat+profitTax+complianceCost};}
export function fileTaxPeriod(c,{from,to,revenue,profit,dueAt=Date.now()+14*86400000}={}){const s=ensureTax(c),liability=estimateTaxLiability(c,{revenue,profit}),row={id:`tax-${to||Date.now()}`,from:n(from),to:n(to,Date.now()),revenue:n(revenue),profit:n(profit),dueAt:n(dueAt),...liability,paid:0,status:'filed',filedAt:Date.now()};s.periods.push(row);s.reserve+=row.total;s.lastFiledAt=Date.now();return row;}
export function payTax(c,periodId,amount){const s=ensureTax(c),p=s.periods.find(x=>x.id===periodId);if(!p)throw new Error('Steuerperiode fehlt');const q=Math.min(Math.max(0,n(amount)),Math.max(0,p.total-p.paid));if(n(c.money)<q)throw new Error('Liquidität reicht nicht');c.money-=q;p.paid+=q;s.reserve=Math.max(0,s.reserve-q);p.status=p.paid+1e-9>=p.total?'paid':'partial';s.payments.push({periodId,amount:q,at:Date.now()});return{success:true,amount:q,remaining:Math.max(0,p.total-p.paid)};}
export function accrueTaxArrears(c,{now=Date.now(),dailyPenalty=.0008}={}){const s=ensureTax(c);for(const p of s.periods.filter(x=>x.status!=='paid'&&x.dueAt<now)){const days=Math.max(1,Math.floor((now-p.dueAt)/86400000)),base=Math.max(0,p.total-p.paid),penalty=base*dailyPenalty*days;if(!p.lastPenaltyAt||p.lastPenaltyAt<p.dueAt){p.total+=penalty;s.arrears+=penalty;p.lastPenaltyAt=now;p.status='overdue';}}return s.arrears;}
export function startTaxAudit(c,{periodIds=[],risk=.1}={}){const s=ensureTax(c),row={id:`audit-${Date.now()}`,periodIds,status:'open',risk:clamp(n(risk,.1),0,1),startedAt:Date.now()};s.audits.push(row);return row;}
export function completeTaxAudit(c,auditId,{adjustment=0,penaltyRate=.1}={}){const s=ensureTax(c),a=s.audits.find(x=>x.id===auditId);if(!a)throw new Error('Prüfung fehlt');const adj=Math.max(0,n(adjustment)),penalty=adj*n(penaltyRate,.1);s.arrears+=adj+penalty;a.status='closed';a.adjustment=adj;a.penalty=penalty;a.closedAt=Date.now();return a;}
export function taxKpis(c){const s=ensureTax(c);return{reserve:s.reserve,arrears:s.arrears,openPeriods:s.periods.filter(x=>x.status!=='paid').length,overdue:s.periods.filter(x=>x.status==='overdue').length,audits:s.audits.filter(x=>x.status==='open').length,regulatoryLoad:regulatoryLoad(c)};}
