// WorldProject - Zeitarbeit und erweiterbare Fahrzeugausbauten
import { worldContentRegistry } from "./ContentRegistry.js";

function stamp(date){const d=new Date(date);return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;}
export class TempAgencySystem{
 constructor(){this.hires=[];this.seq=1;}
 offers({industry,date=new Date()}={}){const seed=new Date(date).getDate();return worldContentRegistry.list("tempAgencyRoles").filter(r=>!(r.industries?.length)||r.industries.includes(industry)).map((r,i)=>({...r,available:1+((seed+i*3)%4),qualification:.85+((seed+i)%5)*.08,totalDailyCost:Math.round(r.dailyCost*(1+r.agencyMarkup))}));}
 hire({roleId,industry,date=new Date(),shiftId="early",machineId=null}={}){const offer=this.offers({industry,date}).find(x=>x.id===roleId);if(!offer||offer.available<1)throw new Error("Keine passende Zeitarbeitskraft verfuegbar");const h={id:this.seq++,roleId,date:stamp(date),shiftId,machineId,skills:[...(offer.skills||[])],qualification:offer.qualification,cost:offer.totalDailyCost,active:true,temporary:true,name:offer.label};this.hires.push(h);return h;}
 availableFor({date=new Date(),shiftId,skill,machineId=null}={}){const s=stamp(date);return this.hires.filter(h=>h.active&&h.date===s&&h.shiftId===shiftId&&(!skill||h.skills.includes(skill))&&(!machineId||h.machineId===machineId));}
 dailyCost(date=new Date()){const s=stamp(date);return this.hires.filter(h=>h.date===s).reduce((sum,h)=>sum+h.cost,0);}
 staffingFor({workforce,date=new Date(),shiftId,skill,machineId=null,hour=null}={}){const permanent=workforce?.availableFor?.({date,shiftId,skill,machineId,hour})||[],temporary=this.availableFor({date,shiftId,skill,machineId});return {permanent,temporary,all:[...permanent,...temporary],temporaryCost:this.dailyCost(date)};}
 createWorkforceAdapter(workforce){
   return {availableFor:opts=>this.staffingFor({workforce,...opts}).all};
 }
}

export function fleetUpgradeCost(id,level=0){const u=worldContentRegistry.get("fleetUpgrades",id);if(!u)throw new Error("Unbekanntes Fahrzeugupgrade");return Math.round(u.baseCost*Math.pow(u.costGrowth,Math.max(0,Number(level||0))));}
export function applyFleetUpgrade(vehicle,id){const u=worldContentRegistry.get("fleetUpgrades",id);if(!u)throw new Error("Unbekanntes Fahrzeugupgrade");vehicle.upgrades=vehicle.upgrades||{};const level=Number(vehicle.upgrades[id]||0);if(level>=u.maxLevel)throw new Error("Maximale Ausbaustufe erreicht");const cost=fleetUpgradeCost(id,level);vehicle.upgrades[id]=level+1;return {id,level:level+1,cost};}
export function upgradedVehicleStats(vehicle={}){const out={...vehicle},levels=vehicle.upgrades||{};let fuelFactor=1,powerFactor=1,reliability=Number(vehicle.reliability||1),tank=Number(vehicle.tankLitres||vehicle.tankCapacity||0),extraWeight=0,hillFactor=1;for(const[id,levelRaw]of Object.entries(levels)){const u=worldContentRegistry.get("fleetUpgrades",id),level=Number(levelRaw||0);if(!u)continue;fuelFactor-=Number(u.fuelReductionPerLevel||0)*level;powerFactor+=Number(u.powerGainPerLevel||0)*level;reliability+=Number(u.reliabilityGainPerLevel||0)*level;tank+=Number(u.tankGainLitresPerLevel||0)*level;extraWeight+=Number(u.weightGainKgPerLevel||0)*level;hillFactor-=Number(u.hillTimeReductionPerLevel||0)*level;}out.fuelConsumptionPer100Km=Number(vehicle.fuelConsumptionPer100Km||vehicle.consumption||0)*Math.max(.65,fuelFactor);out.powerFactor=powerFactor;out.powerHp=Number(vehicle.powerHp||0)*powerFactor;out.reliability=Math.min(1.25,reliability);out.tankLitres=tank;out.extraUpgradeWeightKg=extraWeight;out.payloadKg=Math.max(0,Number(vehicle.payloadKg||vehicle.payload||0)-extraWeight);out.hillTimeFactor=Math.max(.8,hillFactor);return out;}
export function estimateHillPerformance(vehicle,{grossWeightKg=40000,gradientPct=0,hillDistanceKm=0,flatSpeedKmh=80}={}){const s=upgradedVehicleStats(vehicle),hp=Math.max(1,Number(s.powerHp||vehicle.powerHp||300)),weightT=Math.max(1,Number(grossWeightKg||0)/1000),gradient=Math.max(0,Number(gradientPct||0)),distance=Math.max(0,Number(hillDistanceKm||0));const loadPower=hp/weightT,severity=gradient*Math.max(.25,55/loadPower),speed=Math.max(25,Math.min(Number(flatSpeedKmh||80),Number(flatSpeedKmh||80)/(1+severity*.055)));const hours=distance/Math.max(1,speed);return {speedKmh:speed,hours,minutes:hours*60,powerHp:hp,grossWeightKg:Number(grossWeightKg),gradientPct:gradient,payloadKg:s.payloadKg};}
export function estimateRouteTime(vehicle,{flatDistanceKm=0,hills=[]}={}){const flatHours=Number(flatDistanceKm||0)/80;let hillHours=0;for(const h of hills)hillHours+=estimateHillPerformance(vehicle,h).hours;return {hours:flatHours+hillHours,minutes:(flatHours+hillHours)*60};}

export function runTempAgencyFleetTest(){const a=new TempAgencySystem(),date=new Date(2026,7,12),h=a.hire({roleId:"temp_machine",industry:"brewery",date,shiftId:"early",machineId:1}),fakeWorkforce={availableFor(){return [];}};const adapter=a.createWorkforceAdapter(fakeWorkforce);const replacement=adapter.availableFor({date,shiftId:"early",skill:"machine",machineId:1});const v300={payloadKg:24000,tankLitres:800,fuelConsumptionPer100Km:30,reliability:.9,powerHp:300,upgrades:{}},v600={...v300,powerHp:600,upgrades:{}};applyFleetUpgrade(v300,"eco_engine");applyFleetUpgrade(v300,"tank");const s=upgradedVehicleStats(v300),slow=estimateHillPerformance(v300,{grossWeightKg:40000,gradientPct:7,hillDistanceKm:10}),fast=estimateHillPerformance(v600,{grossWeightKg:40000,gradientPct:7,hillDistanceKm:10});if(replacement.length!==1||replacement[0].id!==h.id||s.fuelConsumptionPer100Km>=30||s.tankLitres<=800||s.payloadKg>=24000||fast.minutes>=slow.minutes||fast.payloadKg!==v600.payloadKg)throw new Error("Zeitarbeit-/Fahrzeugupgrade-Test fehlgeschlagen");console.log("✅ ZEITARBEIT-ERSATZ-/FAHRZEUGUPGRADE-/BERGLEISTUNGS-TEST ERFOLGREICH",{hire:h,vehicle:s,hill300:slow,hill600:fast});return true;}
