// WorldProject – Tourenplanung mit mehreren Stopps, Fahrzeugen, Zeitfenstern und Auslastung.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureTransportNetwork(c={}){c.transportNetwork??={routes:[],depots:[],history:[]};c.vehicles??=[];return c.transportNetwork;}
export function addDepot(c,{id,name,location}={}){const t=ensureTransportNetwork(c),d={id:id||`depot-${Date.now()}`,name:name||"Depot",location};t.depots.push(d);return d;}
export function vehicleCapacity(vehicle){return{weightKg:Math.max(0,n(vehicle.payloadKg??vehicle.capacityKg)),volumeM3:Math.max(0,n(vehicle.volumeM3)),pallets:Math.max(0,n(vehicle.pallets))};}
export function routeLoad(stops=[]){return stops.reduce((a,s)=>({weightKg:a.weightKg+n(s.weightKg),volumeM3:a.volumeM3+n(s.volumeM3),pallets:a.pallets+n(s.pallets)}),{weightKg:0,volumeM3:0,pallets:0});}
export function canVehicleHandleRoute(vehicle,stops=[]){const cap=vehicleCapacity(vehicle),load=routeLoad(stops),issues=[];if(cap.weightKg&&load.weightKg>cap.weightKg+1e-9)issues.push("weight");if(cap.volumeM3&&load.volumeM3>cap.volumeM3+1e-9)issues.push("volume");if(cap.pallets&&load.pallets>cap.pallets+1e-9)issues.push("pallets");return{ok:!issues.length,issues,capacity:cap,load,utilization:{weight:cap.weightKg?load.weightKg/cap.weightKg:0,volume:cap.volumeM3?load.volumeM3/cap.volumeM3:0,pallets:cap.pallets?load.pallets/cap.pallets:0}};}
export function routeDistance(stops=[]){return stops.reduce((s,x)=>s+Math.max(0,n(x.distanceFromPreviousKm)),0);}
export function routeDurationMinutes(stops=[],{averageSpeedKmh=60,serviceMinutes=15}={}){const drive=routeDistance(stops)/Math.max(1,n(averageSpeedKmh))*60,service=stops.length*Math.max(0,n(serviceMinutes));return drive+service;}
export function routeCost(vehicle,stops=[],{dieselPrice=1.7,driverHourly=24,maintenancePerKm=.14}={}){const km=routeDistance(stops),liters=km*Math.max(0,n(vehicle.consumptionLPer100Km,25))/100,fuel=liters*n(dieselPrice),driver=routeDurationMinutes(stops)/60*n(driverHourly),maintenance=km*n(maintenancePerKm);return{km,liters,fuel,driver,maintenance,total:fuel+driver+maintenance};}
export function createRoute(c,{vehicleId,depotId,stops=[],startsAt=Date.now(),averageSpeedKmh=60}={}){const t=ensureTransportNetwork(c),v=c.vehicles.find(x=>(x.id||x.vehicleId)===vehicleId);if(!v)throw new Error("Fahrzeug fehlt");const suitability=canVehicleHandleRoute(v,stops);if(!suitability.ok)throw Object.assign(new Error("Fahrzeug ungeeignet"),{suitability});const durationMinutes=routeDurationMinutes(stops,{averageSpeedKmh}),row={id:`route-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,vehicleId,depotId,stops:stops.map((s,i)=>({...s,sequence:i+1})),startsAt:n(startsAt),endsAt:n(startsAt)+durationMinutes*60000,durationMinutes,status:"planned",cost:routeCost(v,stops),suitability};t.routes.push(row);return row;}
export function startRoute(c,id,{now=Date.now()}={}){const t=ensureTransportNetwork(c),r=t.routes.find(x=>x.id===id);if(!r)throw new Error("Tour fehlt");if(r.status!=="planned")return{success:true,idempotent:true,route:r};r.status="running";r.startedAt=now;const v=c.vehicles.find(x=>(x.id||x.vehicleId)===r.vehicleId);if(v){v.status="on_route";v.busyUntil=r.endsAt;}return{success:true,route:r};}
export function completeRoute(c,id,{now=Date.now(),force=false}={}){const t=ensureTransportNetwork(c),r=t.routes.find(x=>x.id===id);if(!r)throw new Error("Tour fehlt");if(r.status==="done")return{success:true,idempotent:true,route:r};if(!force&&now<r.endsAt)throw new Error("Tour noch nicht fertig");r.status="done";r.completedAt=now;const v=c.vehicles.find(x=>(x.id||x.vehicleId)===r.vehicleId);if(v){v.status="available";v.busyUntil=0;v.mileageKm=n(v.mileageKm)+n(r.cost.km);}t.history.push({...r});return{success:true,route:r};}
export function transportNetworkKpis(c){const t=ensureTransportNetwork(c),routes=t.routes,done=routes.filter(x=>x.status==="done");return{routes:routes.length,planned:routes.filter(x=>x.status==="planned").length,running:routes.filter(x=>x.status==="running").length,done:done.length,totalKm:done.reduce((s,x)=>s+n(x.cost?.km),0),totalCost:done.reduce((s,x)=>s+n(x.cost?.total),0),averageStops:routes.length?routes.reduce((s,x)=>s+(x.stops?.length||0),0)/routes.length:0};}
