// ORVUNO - ein gemeinsamer Lagerbestand fuer alte Economy-Funktionen und das operative Lager.
// Moderne Betriebe verwenden operationalSupplyState.warehouseStock als Wahrheit; Legacy-Bags bleiben nur Fallback.
import { AdvancedEconomySystem } from './AdvancedEconomySystem.js';
import { worldContentRegistry } from './ContentRegistry.js';
import { canonicalMaterialId } from './OperationalInventoryBridge.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const DISCRETE_FINISHED=new Set(['beer_lager_033','beer_pils_033','beer_lager_050','beer_pils_050']);
export function isDiscreteFinishedProduct(id){return DISCRETE_FINISHED.has(canonicalMaterialId(id));}
export function normalizeFinishedQuantity(id,value){const q=Math.max(0,n(value));return isDiscreteFinishedProduct(id)?Math.floor(q+1e-9):q;}
export function hasOperationalStock(company){return !!company?.operationalSupplyState?.warehouseStock;}
function ensureZones(company){company.operationalSupplyState??={};company.operationalSupplyState.warehouseStock??={raw:{},packaging:{},cold:{},finished:{}};const s=company.operationalSupplyState.warehouseStock;for(const z of ['raw','packaging','cold','finished'])s[z]??={};return s;}
export function stockZoneFor(id,{finished=false}={}){if(finished)return'finished';const canonical=canonicalMaterialId(id),meta=worldContentRegistry.get('materials',canonical)||worldContentRegistry.get('products',canonical)||worldContentRegistry.get('materials',id)||worldContentRegistry.get('products',id);return meta?.storageZone||(['bottles','clean_bottles','caps','labels','packaging'].includes(canonical)?'packaging':'raw');}
export function normalizeOperationalFinishedStock(company){if(!company)return 0;const s=ensureZones(company),source=s.finished||{},groups=new Map();for(const[key,value]of Object.entries(source)){const canonical=canonicalMaterialId(key),q=normalizeFinishedQuantity(canonical,value),prev=groups.get(canonical);groups.set(canonical,prev===undefined?q:Math.max(prev,q));}let changed=0;for(const key of Object.keys(source)){const canonical=canonicalMaterialId(key);if(key!==canonical){delete source[key];changed++;}}for(const[canonical,value]of groups){if(n(source[canonical])!==value){source[canonical]=value;changed++;}}if(company.finishedGoods&&typeof company.finishedGoods==='object'){for(const[key,value]of Object.entries(company.finishedGoods)){const canonical=canonicalMaterialId(key),q=normalizeFinishedQuantity(canonical,value),wanted=Math.max(q,n(source[canonical]));if(n(source[canonical])!==wanted){source[canonical]=wanted;changed++;}if(key!==canonical)delete company.finishedGoods[key];company.finishedGoods[canonical]=wanted;}}return changed;}
export function operationalAmount(company,id,{finished=false}={}){const s=ensureZones(company),canonical=canonicalMaterialId(id);if(finished)normalizeOperationalFinishedStock(company);const zones=finished?[s.finished]:[s.raw,s.packaging,s.cold];let value=0;for(const zone of zones){if(!zone||typeof zone!=='object')continue;for(const[key,raw]of Object.entries(zone)){if(canonicalMaterialId(key)!==canonical)continue;const q=finished?normalizeFinishedQuantity(canonical,raw):Math.max(0,n(raw));value=finished?Math.max(value,q):value+q;}}if(finished&&company?.finishedGoods){for(const[key,raw]of Object.entries(company.finishedGoods))if(canonicalMaterialId(key)===canonical)value=Math.max(value,normalizeFinishedQuantity(canonical,raw));}return Math.max(0,value);}
export function addOperational(company,id,amount,{finished=false}={}){const s=ensureZones(company),canonical=canonicalMaterialId(id),z=stockZoneFor(canonical,{finished}),next=n(s[z][canonical])+n(amount);s[z][canonical]=finished?normalizeFinishedQuantity(canonical,next):Math.max(0,next);if(finished)normalizeOperationalFinishedStock(company);return{zone:z,amount:operationalAmount(company,canonical,{finished}),material:canonical};}
function setOperationalAmount(company,key,value,{finished=false}={}){const zones=ensureZones(company),canonical=canonicalMaterialId(key),target=stockZoneFor(canonical,{finished}),wanted=finished?normalizeFinishedQuantity(canonical,value):Math.max(0,n(value)),searchZones=finished?[zones.finished]:[zones.raw,zones.packaging,zones.cold];for(const zone of searchZones){if(!zone||typeof zone!=='object')continue;for(const id of Object.keys(zone))if(id!==canonical&&canonicalMaterialId(id)===canonical)delete zone[id];}zones[target][canonical]=wanted;if(finished&&company.finishedGoods&&typeof company.finishedGoods==='object')company.finishedGoods[canonical]=wanted;return true;}
function legacyProxy(company,{finished=false}={}){const zones=ensureZones(company);return new Proxy({}, {get(_t,key){if(typeof key!=='string')return undefined;return operationalAmount(company,key,{finished});},set(_t,key,value){if(typeof key!=='string')return true;return setOperationalAmount(company,key,value,{finished});},ownKeys(){const source=finished?[zones.finished]:[zones.raw,zones.packaging,zones.cold];return[...new Set(source.flatMap(zone=>Object.keys(zone||{})).map(canonicalMaterialId))];},getOwnPropertyDescriptor(){return{enumerable:true,configurable:true};}});}
function withOperationalBags(company,fn){if(!hasOperationalStock(company))return fn();normalizeOperationalFinishedStock(company);const oldInventory=company.inventory,oldFinished=company.finishedGoods;company.inventory=legacyProxy(company);company.finishedGoods=legacyProxy(company,{finished:true});try{return fn();}finally{company.inventory=oldInventory??{};company.finishedGoods=oldFinished??{};normalizeOperationalFinishedStock(company);}}
const p=AdvancedEconomySystem.prototype;
if(!p.__worldUnifiedOperationalStockBridge){p.__worldUnifiedOperationalStockBridge=true;for(const name of ['startProduction','processProduction','processSupplierDeliveries','deliverCustomerOrder','getStorageUsed','getStorageStatus','getStorageAreas','canStore']){const original=p[name];if(typeof original!=='function')continue;p[name]=function(company,...args){return withOperationalBags(company,()=>original.call(this,company,...args));};}}
export function runUnifiedOperationalStockBridgeTest(){const now=new Date('2026-08-14T12:00:00Z'),s=new AdvancedEconomySystem(),c={name:'Testbrauerei',type:'Brauerei',setupPhase:'operating',money:1000,operationalSupplyState:{warehouseStock:{raw:{malt_kg:60,hops_kg:1,yeast_kg:1,water_l:400},packaging:{bottle_033:1100,crown_cap:1100,label_033:1100},cold:{},finished:{lager033_bottle:99.84}}},supplierOrders:[],vehicles:[],inventory:{},finishedGoods:{lager033_bottle:99.84},productionQueue:[],productionHistory:[],productionMachines:[{id:'line1',status:'available',condition:100,speedMultiplier:1}],productionState:{slots:1},storageState:{capacityUnits:25000},storageAreas:{raw:{capacity:10000},packaging:{capacity:10000},finished:{capacity:10000}},customerOrders:[],completedCustomerOrders:[],financialLog:[],costAccounting:{productCosts:{},priceHistory:{}},salesPrices:{},competitorHistory:{},coinLedger:[],coins:0};normalizeOperationalFinishedStock(c);if(operationalAmount(c,'lager033_bottle',{finished:true})!==99||operationalAmount(c,'beer_lager_033',{finished:true})!==99)throw new Error('Fertigware muss ganze alias-sichere Stückzahlen liefern');c.customerOrders.push({id:'cust',productId:'lager033_bottle',amount:50,delivered:0,unitPrice:1,status:'open'});const sale=s.deliverCustomerOrder(c,'cust',50);if(!sale.success||operationalAmount(c,'beer_lager_033',{finished:true})!==49)throw new Error('Kundenbelieferung nutzt kanonischen Fertigwarenbestand nicht');c.supplierOrders.push({id:'x',itemId:'malt_kg',amount:5,status:'in_transit',arrivalAt:new Date(now.getTime()-1000)});const delivered=s.processSupplierDeliveries(c,now);if(delivered.length!==1)throw new Error('Lieferung wird nicht verarbeitet');return true;}
if(typeof window!=='undefined')window.worldUnifiedOperationalStock={has:hasOperationalStock,amount:operationalAmount,add:addOperational,zoneFor:stockZoneFor,normalizeFinished:normalizeOperationalFinishedStock,isDiscreteFinished:isDiscreteFinishedProduct,test:runUnifiedOperationalStockBridgeTest};
