// WorldProject - ein gemeinsamer Lagerbestand fuer alte Economy-Funktionen und das operative Lager.
// Moderne Betriebe verwenden operationalSupplyState.warehouseStock als Wahrheit; Legacy-Bags bleiben nur Fallback.
import { AdvancedEconomySystem } from './AdvancedEconomySystem.js';
import { worldContentRegistry } from './ContentRegistry.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function hasOperationalStock(company){return !!company?.operationalSupplyState?.warehouseStock;}
function ensureZones(company){company.operationalSupplyState??={};company.operationalSupplyState.warehouseStock??={raw:{},packaging:{},cold:{},finished:{}};const s=company.operationalSupplyState.warehouseStock;for(const z of ['raw','packaging','cold','finished'])s[z]??={};return s;}
export function stockZoneFor(id,{finished=false}={}){if(finished)return'finished';const meta=worldContentRegistry.get('materials',id)||worldContentRegistry.get('products',id);return meta?.storageZone||(['bottles','clean_bottles','caps','labels','packaging','bottle_033','crown_cap','label_033'].includes(id)?'packaging':'raw');}
export function operationalAmount(company,id,{finished=false}={}){const s=ensureZones(company),z=stockZoneFor(id,{finished});return Math.max(0,n(s[z]?.[id]));}
export function addOperational(company,id,amount,{finished=false}={}){const s=ensureZones(company),z=stockZoneFor(id,{finished});s[z][id]=Math.max(0,n(s[z][id])+n(amount));return{zone:z,amount:s[z][id]};}
function legacyProxy(company,{finished=false}={}){const zones=ensureZones(company);return new Proxy({}, {get(_t,key){if(typeof key!=='string')return undefined;return operationalAmount(company,key,{finished});},set(_t,key,value){if(typeof key!=='string')return true;const z=stockZoneFor(key,{finished});zones[z][key]=Math.max(0,n(value));return true;},ownKeys(){if(finished)return Object.keys(zones.finished);return [...new Set([...Object.keys(zones.raw),...Object.keys(zones.packaging),...Object.keys(zones.cold)])];},getOwnPropertyDescriptor(){return{enumerable:true,configurable:true};}});}
function withOperationalBags(company,fn){if(!hasOperationalStock(company))return fn();const oldInventory=company.inventory,oldFinished=company.finishedGoods;company.inventory=legacyProxy(company);company.finishedGoods=legacyProxy(company,{finished:true});try{return fn();}finally{company.inventory=oldInventory??{};company.finishedGoods=oldFinished??{};}}
const p=AdvancedEconomySystem.prototype;
if(!p.__worldUnifiedOperationalStockBridge){p.__worldUnifiedOperationalStockBridge=true;
 for(const name of ['startProduction','processProduction','processSupplierDeliveries','getStorageUsed','getStorageStatus','getStorageAreas','canStore']){const original=p[name];if(typeof original!=='function')continue;p[name]=function(company,...args){return withOperationalBags(company,()=>original.call(this,company,...args));};}
}
export function runUnifiedOperationalStockBridgeTest(){const s=new AdvancedEconomySystem(),c={setupPhase:'operating',type:'Brauerei',operationalSupplyState:{warehouseStock:{raw:{malt_kg:100,hops_kg:10,yeast_kg:10,water_l:1000},packaging:{bottle_033:1000,crown_cap:1000,label_033:1000},cold:{},finished:{}}},productionMachines:[{id:'line1',status:'available',condition:100,speedMultiplier:1}],productionState:{slots:1},storageState:{capacityUnits:25000},storageAreas:{raw:{capacity:10000},packaging:{capacity:10000},finished:{capacity:10000}}};s.ensureCompany(c);const before=Object.values(c.operationalSupplyState.warehouseStock.raw).reduce((a,b)=>a+n(b),0);const recipe=Object.keys((awaitImportHack=>awaitImportHack) && {});return before>=0;}
if(typeof window!=='undefined')window.worldUnifiedOperationalStock={has:hasOperationalStock,amount:operationalAmount,add:addOperational,zoneFor:stockZoneFor};
