// WorldProject - universelle Einkaufs-, Transport- und Lagerdiagnostik fuer alle Gewerbe.
import { worldContentRegistry } from "./ContentRegistry.js";
import { getIndustryProfile } from "./IndustryCatalog.js";
import { rankSuppliers, buildPurchaseList } from "./UniversalPlanningAndProcurement.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const MATERIAL_UNITS={malt:'kg',hops:'kg',yeast:'kg',water:'l',bottles:'Stk',caps:'Stk',labels:'Stk',softwood:'m3',hardwood:'m3',plywood:'m2',glue:'kg',screws:'Set',varnish:'l',packaging:'Stk',seed_wheat:'kg',seed_barley:'kg',fertilizer:'kg',diesel:'l'};
function all(kind){try{return worldContentRegistry.list(kind)||[];}catch{return[];}}
export function suppliersForCompany(company){const key=getIndustryProfile(company).branchKey;return all('suppliers').filter(s=>(s.industries||[]).includes(key));}
export function materialMeta(id){const x=all('materials').find(m=>m.id===id)||{};return{id,label:x.label||id,unit:x.unit||MATERIAL_UNITS[id]||'Einheit',storageZone:x.storageZone||'raw'};}
export function procurementOptions(company,item,quantity){const suppliers=suppliersForCompany(company),ranked=rankSuppliers(item,quantity,suppliers);return ranked.map((x,i)=>({...x,rank:i+1,isCheapest:x.total===Math.min(...ranked.map(r=>r.total)),isFastest:n(x.deliveryHours,999)===Math.min(...ranked.map(r=>n(r.deliveryHours,999))),isBest:i===0}));}
export function vehicleSuitability(vehicle,cargo={}){const reasons=[];if(n(vehicle?.payloadKg,Infinity)<n(cargo.weightKg))reasons.push('Nutzlast zu klein');if(n(vehicle?.volumeM3,Infinity)<n(cargo.volumeM3))reasons.push('Volumen zu klein');if(n(vehicle?.palletCapacity,Infinity)<n(cargo.pallets))reasons.push('Palettenkapazitaet zu klein');if(['broken','maintenance','repair'].includes(vehicle?.status))reasons.push('Fahrzeug nicht verfuegbar');return{vehicle,ok:reasons.length===0,reasons};}
export function transportPreview({supplier,quantity,unitWeightKg=1,vehicle=null,dieselPrice=1.45}={}){const distance=n(supplier?.distanceKm),weight=n(quantity)*n(unitWeightKg,1),own=vehicle?vehicleSuitability(vehicle,{weightKg:weight,volumeM3:weight/500,pallets:Math.ceil(weight/700)}):null,trips=vehicle&&n(vehicle.payloadKg)>0?Math.max(1,Math.ceil(weight/n(vehicle.payloadKg))):1,totalKm=distance*2*trips,liters=vehicle?n(vehicle.consumptionLPer100Km,28)*totalKm/100:0,ownCost=vehicle?liters*n(dieselPrice)+totalKm*.18:Infinity,supplierCost=n(supplier?.deliveryBase)+n(supplier?.deliveryPerKm)*distance,etaHours=n(supplier?.deliveryHours,8)+(trips-1)*Math.max(1,distance/60*2);return{distanceKm:distance,weightKg:weight,trips,totalKm,dieselLiters:liters,ownCost,supplierCost,recommended:vehicle&&own?.ok&&ownCost<supplierCost?'own':'supplier',etaHours,vehicleSuitability:own};}
export function incomingQuantity(company,item){return (company?.supplierOrders||company?.operationalSupplyState?.orders||[]).filter(o=>(o.itemId||o.material)===item&&!['stored','cancelled','delivered'].includes(o.status)).reduce((s,o)=>s+n(o.amount??o.quantity),0);}
export function consolidatedNeeds(company,requirements=[]){const map={};for(const req of requirements){for(const [item,q] of Object.entries(req.materials||req.requirements||{}))map[item]=n(map[item])+n(q);}return Object.entries(map).map(([item,needed])=>{const have=n(company?.inventory?.[item]),incoming=incomingQuantity(company,item);return{item,needed,have,incoming,missing:Math.max(0,needed-have-incoming),meta:materialMeta(item)};}).filter(x=>x.missing>0);}
export function storageWarnings(company){const state=company?.operationalSupplyState||{},caps=state.baseCapacities||company?.warehouseCapacities||{},stock=state.warehouseStock||{};const out=[];for(const zone of ['raw','packaging','finished','cold']){const used=Object.values(stock[zone]||{}).reduce((s,v)=>s+n(v),0),cap=n(caps[zone],0),ratio=cap>0?used/cap:0;out.push({zone,used,capacity:cap,percent:Math.round(ratio*100),severity:ratio>=1?'full':ratio>=.95?'critical':ratio>=.8?'warning':'ok'});}return out;}
export function receiptProgress(order){const total=n(order?.quantity??order?.amount),received=n(order?.receivedQuantity),remaining=Math.max(0,total-received);return{total,received,remaining,percent:total?Math.round(received/total*100):0,status:order?.status||'unknown'};}
export function universalPurchaseSuggestions(company){const policy=buildPurchaseList(company),requirements=consolidatedNeeds(company,company?.plannedRequirements||[]);const map=new Map();for(const row of [...policy,...requirements]){const item=row.item,qty=n(row.quantity??row.missing);map.set(item,{item,quantity:n(map.get(item)?.quantity)+qty,meta:materialMeta(item)});}return [...map.values()];}
export function runUniversalProcurementInsightsTest(){const company={type:'Schreinerei',inventory:{softwood:1},plannedRequirements:[{materials:{softwood:2,glue:1}}],supplierOrders:[]},needs=consolidatedNeeds(company,company.plannedRequirements),suppliers=suppliersForCompany(company),opts=procurementOptions(company,'softwood',1);const checks=[needs.some(x=>x.item==='softwood'&&x.missing===1),suppliers.length>0,opts.length>0,opts[0].isBest===true,receiptProgress({quantity:100,receivedQuantity:40}).remaining===60];return{success:checks.every(Boolean),checks};}
