// WorldProject - universelle Planung fuer Einkauf, Lager, Produktion/Leistung und KPI.
// Funktioniert auch bei Gewerben ohne klassische Produktion.
import { getIndustryProfile } from "./IndustryCatalog.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function inventoryQuantity(company,item){return n(company?.inventory?.[item]??company?.stock?.[item]??company?.tradeInventory?.[item]);}
export function consumptionRate(company,item,days=30){const rows=(company?.consumptionHistory||[]).filter(x=>x.item===item&&Date.now()-n(x.at)<=days*86400000);return rows.reduce((s,x)=>s+n(x.quantity),0)/Math.max(1,days);}
export function stockCoverageDays(company,item){const rate=consumptionRate(company,item);return rate>0?inventoryQuantity(company,item)/rate:Infinity;}
export function setStockPolicy(company,item,{minimum=0,target=0,safety=0}={}){company.stockPolicies??={};company.stockPolicies[item]={minimum:Math.max(0,n(minimum)),target:Math.max(0,n(target)),safety:Math.max(0,n(safety))};return company.stockPolicies[item];}
export function reorderSuggestion(company,item){const p=company?.stockPolicies?.[item];if(!p)return null;const have=inventoryQuantity(company,item),threshold=p.minimum+p.safety;if(have>threshold)return null;return{item,have,minimum:p.minimum,safety:p.safety,target:p.target,quantity:Math.max(0,p.target+p.safety-have),coverageDays:stockCoverageDays(company,item)};}
export function buildPurchaseList(company){return Object.keys(company.stockPolicies||{}).map(i=>reorderSuggestion(company,i)).filter(Boolean);}
export function groupPurchasesBySupplier(list,suppliers=[]){const groups={};for(const row of list){const candidates=suppliers.filter(s=>(s.materials||[]).includes(row.item));if(!candidates.length){(groups.unassigned??=[]).push(row);continue;}const ranked=candidates.map(s=>({...s,total:n(s.prices?.[row.item])*row.quantity+n(s.deliveryBase)+n(s.deliveryPerKm)*n(s.distanceKm)})).sort((a,b)=>a.total-b.total);const s=ranked[0];(groups[s.id]??=[]).push({...row,supplierId:s.id,estimatedTotal:s.total});}return groups;}
export function rankSuppliers(item,quantity,suppliers=[]){return suppliers.filter(s=>(s.materials||[]).includes(item)).map(s=>{const goods=n(s.prices?.[item])*n(quantity),transport=n(s.deliveryBase)+n(s.deliveryPerKm)*n(s.distanceKm),score=goods+transport+n(s.deliveryHours)*2+(1-n(s.reliability,1))*500+(1-n(s.quality,1))*300;return{...s,goods,transport,total:goods+transport,score};}).sort((a,b)=>a.score-b.score);}
export function recordSupplierResult(company,{supplierId,item,unitPrice,onTime=true,quality=1}={}){company.supplierHistory??=[];company.priceHistory??={};company.supplierHistory.push({supplierId,item,onTime,quality:n(quality,1),at:Date.now()});(company.priceHistory[item]??=[]).push({price:n(unitPrice),at:Date.now(),supplierId});return company.supplierHistory.at(-1);}
export function priceChangeWarning(company,item,threshold=.15){const h=company?.priceHistory?.[item]||[];if(h.length<2)return null;const prev=n(h.at(-2).price),cur=n(h.at(-1).price),change=prev?((cur-prev)/prev):0;return Math.abs(change)>=threshold?{item,previous:prev,current:cur,change}:null;}
export function scheduleJob(company,job){company.productionCalendar??=[];const start=n(job.startAt,Date.now()),end=n(job.endAt,start+n(job.durationMinutes)*60000);const conflicts=company.productionCalendar.filter(x=>x.status!=="done"&&start<n(x.endAt)&&end>n(x.startAt)&&(x.machineId&&x.machineId===job.machineId||x.employeeId&&x.employeeId===job.employeeId));const row={...job,id:job.id||`plan-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,startAt:start,endAt:end,status:conflicts.length?"conflict":"planned",conflicts:conflicts.map(x=>x.id)};company.productionCalendar.push(row);return row;}
export function dueOrderPriority(order,now=Date.now()){const due=n(order.dueAt,now+7*86400000),late=Math.max(0,now-due)/86400000,urgency=Math.max(0,7-(due-now)/86400000);return n(order.priority)*100+late*200+urgency*10;}
export function sortCustomerOrders(orders=[]){return [...orders].sort((a,b)=>dueOrderPriority(b)-dueOrderPriority(a));}
export function customerSatisfaction(relation={},event={}){let score=n(relation.score,75);if(event.onTime===true)score+=2;if(event.onTime===false)score-=7;if(event.complete===true)score+=2;if(event.complete===false)score-=4;return Math.max(0,Math.min(100,score));}
export function businessKpis(company,{period="day"}={}){const revenue=n(company.revenue?.[period]??company.salesToday),cost=n(company.costs?.[period]??company.costToday),profit=revenue-cost,inventoryValue=Object.values(company.inventoryValue||{}).reduce((s,v)=>s+n(v),0),orders=(company.customerOrders||[]);return{revenue,cost,profit,margin:revenue?profit/revenue:0,inventoryValue,openOrders:orders.filter(o=>!['done','completed'].includes(o.status)).length,overdueOrders:orders.filter(o=>n(o.dueAt)>0&&n(o.dueAt)<Date.now()&&!['done','completed'].includes(o.status)).length,employees:(company.employees||[]).length,machines:(company.buildingState?.equipment||[]).length,branchKey:getIndustryProfile(company).branchKey};}
export function periodClose(company,period="day"){company.financialClosings??=[];const kpi=businessKpis(company,{period});const row={id:`close-${period}-${Date.now()}`,period,at:Date.now(),...kpi};company.financialClosings.push(row);return row;}
export function runUniversalPlanningTest(){const c={type:"Einzelhandel",inventory:{x:5},consumptionHistory:Array.from({length:10},(_,i)=>({item:"x",quantity:2,at:Date.now()-i*86400000}))};setStockPolicy(c,"x",{minimum:10,target:30,safety:5});const s=reorderSuggestion(c,"x"),p=scheduleJob(c,{machineId:"m1",startAt:100,endAt:200}),q=scheduleJob(c,{machineId:"m1",startAt:150,endAt:250});const checks=[s?.quantity===30,p.status==="planned",q.status==="conflict",Number.isFinite(stockCoverageDays(c,"x")),businessKpis(c).branchKey==="retail"];return{success:checks.every(Boolean),checks};}
