// WorldProject – universeller Betriebszyklus für alle Gewerbe.
import { getIndustryProfile } from "./IndustryCatalog.js";
import { worldContentRegistry } from "./ContentRegistry.js";
import { machineRequirementSatisfied, machineRequirementDetails } from "./IndustryMachineCompatibility.js";
import { operationalStockAmount,consumeOperationalStock,syncOperationalWarehouse } from "./OperationalInventoryBridge.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const branch=c=>c?.branchKey||getIndustryProfile(c).branchKey;
const list=(t,k)=>worldContentRegistry.list(t).filter(x=>(x.industries||[]).includes(k));
export function ensureIndustryState(c={}){c.inventory??={};c.finishedGoods??={};c.productionJobs??=[];c.salesLedger??=[];c.costLedger??=[];c.operationRequestIds??=[];if(c.operationalSupplyState?.warehouseStock)syncOperationalWarehouse(c);return c;}
function materialHave(c,id){const op=operationalStockAmount(c,id);return op===null?n(c.inventory[id])+n(c.finishedGoods[id]):op+n(c.finishedGoods[id]);}
function consumeMaterial(c,id,q){let left=Math.max(0,n(q));const op=operationalStockAmount(c,id);if(op!==null){const take=Math.min(left,op);if(take>0&&!consumeOperationalStock(c,id,take)?.success)return false;left-=take;}else{const take=Math.min(left,n(c.inventory[id]));c.inventory[id]=n(c.inventory[id])-take;left-=take;}if(left>1e-9){const take=Math.min(left,n(c.finishedGoods[id]));c.finishedGoods[id]=n(c.finishedGoods[id])-take;left-=take;}return left<=1e-9;}
export function industryRecipes(c){return list("recipes",branch(c)).filter(r=>!r.deprecated);}
export function industryProducts(c){return list("products",branch(c));}
export function industrySuppliers(c){return list("suppliers",branch(c));}
export function recipeScale(recipe,amount){const base=Math.max(1,n(recipe.output,1)),wanted=Math.max(0,n(amount));const factor=wanted/base;return Object.fromEntries(Object.entries(recipe.materials||{}).map(([id,q])=>[id,n(q)*factor]));}
export function productionReadiness(c,recipeId,amount){ensureIndustryState(c);const recipe=industryRecipes(c).find(r=>r.id===recipeId);if(!recipe)throw new Error("Rezept/Leistung nicht verfügbar");const need=recipeScale(recipe,amount),missing={};for(const[id,q]of Object.entries(need)){const have=materialHave(c,id);if(have+1e-9<q)missing[id]=q-have;}const machine=machineRequirementDetails(c,recipe.machineType),machineMissing=!machineRequirementSatisfied(c,recipe.machineType);return{recipe,amount:n(amount),need,missing,machine,machineMissing,ready:Object.keys(missing).length===0&&!machineMissing};}
export function startIndustryJob(c,recipeId,amount,{requestId,now=Date.now()}={}){ensureIndustryState(c);if(requestId&&c.operationRequestIds.includes(requestId))return{success:true,idempotent:true,job:c.productionJobs.find(x=>x.requestId===requestId)||null};const r=productionReadiness(c,recipeId,amount);if(!r.ready)throw Object.assign(new Error("Produktion/Leistung nicht startbereit"),{readiness:r});for(const[id,q]of Object.entries(r.need))if(!consumeMaterial(c,id,q))throw new Error(`Rohstoff konnte nicht verbraucht werden: ${id}`);const duration=Math.max(1,n(r.recipe.durationMinutes,1)*(n(amount)/Math.max(1,n(r.recipe.output,1))));const job={id:`job-${now}-${Math.random().toString(36).slice(2,7)}`,requestId:requestId||null,recipeId,product:r.recipe.product,amount:n(amount),startedAt:now,endsAt:now+duration*60000,status:"running",variableCost:n(r.recipe.variableCost)*(n(amount)/Math.max(1,n(r.recipe.output,1)))};c.productionJobs.push(job);c.costLedger.push({kind:"production",jobId:job.id,amount:job.variableCost,at:now});c.money=n(c.money)-job.variableCost;if(requestId)c.operationRequestIds.push(requestId);return{success:true,job};}
export function finishIndustryJob(c,jobId,{now=Date.now(),force=false}={}){ensureIndustryState(c);const job=c.productionJobs.find(x=>x.id===jobId);if(!job)throw new Error("Auftrag nicht gefunden");if(job.status==="done")return{success:true,idempotent:true,job};if(!force&&now<job.endsAt)throw new Error("Auftrag noch nicht fertig");c.finishedGoods[job.product]=n(c.finishedGoods[job.product])+job.amount;job.status="done";job.finishedAt=now;return{success:true,job};}
export function sellIndustryOutput(c,productId,quantity,unitPrice,{requestId,now=Date.now()}={}){ensureIndustryState(c);const q=n(quantity);if(q<=0||n(unitPrice)<0)throw new Error("Ungültige Verkaufsdaten");c.saleRequestIds??=[];if(requestId&&c.saleRequestIds.includes(requestId))return{success:true,idempotent:true};const have=n(c.finishedGoods[productId])+n(c.inventory[productId]);if(have<q)throw new Error("Nicht genug verkaufbare Ware");let left=q,take=Math.min(left,n(c.finishedGoods[productId]));c.finishedGoods[productId]=n(c.finishedGoods[productId])-take;left-=take;if(left>0)c.inventory[productId]=n(c.inventory[productId])-left;const revenue=q*n(unitPrice);c.money=n(c.money)+revenue;c.salesLedger.push({productId,quantity:q,unitPrice:n(unitPrice),revenue,at:now,requestId:requestId||null});if(requestId)c.saleRequestIds.push(requestId);return{success:true,revenue,balance:c.money};}
export function supplierCanProvide(c,item){return industrySuppliers(c).filter(s=>(s.materials||[]).includes(item)).sort((a,b)=>n(a.prices?.[item])-n(b.prices?.[item]));}
export function procureInstantForTest(c,item,quantity){ensureIndustryState(c);const s=supplierCanProvide(c,item)[0];if(!s)throw new Error(`Kein Lieferant für ${item}`);const q=n(quantity),cost=q*n(s.prices?.[item]);if(q<=0||n(c.money)<cost)throw new Error("Beschaffung nicht möglich");c.money-=cost;c.inventory[item]=n(c.inventory[item])+q;c.costLedger.push({kind:"procurement",item,quantity:q,cost,supplierId:s.id,at:Date.now()});return{success:true,cost,supplier:s};}
