// WorldProject - Kundenauftrag -> Material/Maschine/Personal/Liefertermin fuer alle Gewerbe.
import { getIndustryProfile } from "./IndustryCatalog.js";
import { machineCatalogFor, chooseFreeMachine } from "./UniversalBusinessOperations.js";
import { missingWorkforce } from "./UniversalWorkforceMarket.js";
import { consolidatedNeeds, suppliersForCompany } from "./UniversalProcurementInsights.js";
import { worldContentRegistry } from "./ContentRegistry.js";
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function all(kind){try{return worldContentRegistry.list(kind)||[];}catch{return[];}}
function recipesFor(company){const key=getIndustryProfile(company).branchKey;return all('recipes').filter(r=>(r.industries||[]).includes(key)&&!r.deprecated);}
function productsFor(company){const key=getIndustryProfile(company).branchKey;return all('products').filter(p=>(p.industries||[]).includes(key)&&p.sellable!==false);}
function recipeForProduct(company,productId){return recipesFor(company).find(r=>r.product===productId)||null;}
function defaultSkillsFor(company,recipe){const key=getIndustryProfile(company).branchKey,skills=[];if(recipe?.machineType)skills.push(recipe.machineType);if(key==='retail'||key==='wholesale')skills.push('sales');if(key==='online_retail')skills.push('packing');if(key==='farm')skills.push('field_line');if(key==='carpentry')skills.push('woodshop');return skills;}
export function orderProductionPlan(company,order){const qty=Math.max(0,n(order.amount??order.quantity)),productId=order.productId||order.product;const recipe=recipeForProduct(company,productId);if(!recipe)return{mode:'trade',productId,quantity:qty,recipe:null,requirements:{}};const perOutput=Math.max(1,n(recipe.output,1)),batches=Math.max(1,Math.ceil(qty/perOutput)),requirements={};for(const [id,v] of Object.entries(recipe.materials||recipe.inputs||{}))requirements[id]=n(v)*batches;return{mode:'production',productId,quantity:qty,recipe,batches,requirements,machineType:recipe.machineType,durationMinutes:n(recipe.durationMinutes)*batches,output:n(recipe.output)*batches};}
export function orderReadiness(company,order,now=Date.now()){const plan=orderProductionPlan(company,order),finished=n(company?.finishedGoods?.[plan.productId]??company?.inventory?.[plan.productId]),shortage=Math.max(0,plan.quantity-finished);if(shortage<=0)return{ready:true,reason:'Ware bereits vorhanden',plan,finished,earliestAt:now,missingMaterials:[],missingSkills:[],machineMissing:false};if(plan.mode==='trade'){const incoming=(company?.supplierOrders||[]).filter(o=>(o.itemId||o.material)===plan.productId&&!['stored','cancelled'].includes(o.status)).reduce((s,o)=>s+n(o.amount??o.quantity),0),missing=Math.max(0,shortage-incoming);const supplier=suppliersForCompany(company).find(s=>(s.materials||[]).includes(plan.productId));const eta=missing>0&&supplier?now+n(supplier.deliveryHours,8)*3600000:now;return{ready:missing<=0,reason:missing<=0?'Ware unterwegs':'Handelsware muss beschafft werden',plan,finished,missingTradeQuantity:missing,earliestAt:eta,missingMaterials:[],missingSkills:[],machineMissing:false};}
 const reqPlan={materials:plan.requirements},missingMaterials=consolidatedNeeds(company,[reqPlan]),machine=chooseFreeMachine(company,plan.machineType,now),machineMissing=!machine,machineCatalog=machineCatalogFor(company).filter(m=>m.id===plan.machineType),skills=defaultSkillsFor(company,plan.recipe),missingSkills=missingWorkforce(company,skills);let procurementHours=0;for(const row of missingMaterials){const supplier=suppliersForCompany(company).find(s=>(s.materials||[]).includes(row.item));procurementHours=Math.max(procurementHours,n(supplier?.deliveryHours,24));}const machineDelay=machine?0:machineCatalog.length?4:24,staffDelay=missingSkills.length?8:0,earliestAt=now+(procurementHours+machineDelay+staffDelay)*3600000+n(plan.durationMinutes)*60000;return{ready:!missingMaterials.length&&!machineMissing&&!missingSkills.length,reason:!missingMaterials.length&&!machineMissing&&!missingSkills.length?'Startbereit':'Voraussetzungen fehlen',plan,finished,missingMaterials,machineMissing,machineCatalog,missingSkills,earliestAt};}
export function readinessSummary(r){return{ready:r.ready,missingMaterialCount:r.missingMaterials?.length||0,machine:r.machineMissing?'fehlt':'ok',missingSkills:r.missingSkills||[],earliestDelivery:new Date(r.earliestAt).toISOString()};}
export function runUniversalOrderReadinessTest(){const c={type:'Schreinerei',inventory:{softwood:100,glue:100,screws:100,varnish:100,packaging:100},finishedGoods:{},buildingState:{equipment:[{id:'woodshop',status:'available',condition:100}]},employees:[{skills:['woodshop'],status:'available'}]},product=productsFor(c)[0]?.id||'table_basic',r=orderReadiness(c,{productId:product,amount:1},0),trade=orderProductionPlan({type:'Einzelhandel'},{productId:'retail_item',amount:4});const checks=[r.plan.mode==='production',r.machineMissing===false,r.missingSkills.length===0,trade.mode==='trade'];return{success:checks.every(Boolean),checks};}
