// WorldProject - sichtbarer Universal-Dialog fuer alle Gewerbe.
import { machineCatalogFor, ownedMachines, buyMachine, serviceMachine, upgradeMachine, sellMachine, machineUtilization } from "./UniversalBusinessOperations.js";
import { jobsFor, generateApplicants, hireApplicant, assignShift } from "./UniversalWorkforceMarket.js";
import { buildPurchaseList, stockCoverageDays, businessKpis } from "./UniversalPlanningAndProcurement.js";
import { getIndustryProfile } from "./IndustryCatalog.js";
import { playerMoneyDisplay, formatCurrency } from "./CurrencyLocalizationSystem.js";
const company=()=>window.worldPlayerCompany||window.worldEconomyGameplay?.company||window.worldEngine?.company;
const player=()=>window.worldPlayer||window.currentPlayer||window.worldAccount?.player||window.worldSession?.player||{};
const world=()=>window.worldEngine?.world||window.worldProjectWorld||window.worldState||{};
const money=v=>{try{return playerMoneyDisplay(Number(v||0),{player:player(),world:world(),baseCurrency:'EUR'}).formatted;}catch{return formatCurrency(Number(v||0),{currency:'EUR',locale:'de-DE'});}};
function el(tag,html=""){const x=document.createElement(tag);x.innerHTML=html;return x;}function pct(v){return `${Math.round(Number(v||0))}%`;}
export class UniversalOperationsDialog{
 constructor(){this.root=null;this.tab="machines";this.applicants=[];}
 open(tab="machines"){this.tab=tab;this.close();this.root=el("div");this.root.id="world-universal-ops";Object.assign(this.root.style,{position:"fixed",inset:"5vh 4vw",zIndex:22000,background:"#111827",color:"#f3f4f6",border:"2px solid #d4a72c",borderRadius:"14px",boxShadow:"0 20px 70px rgba(0,0,0,.6)",overflow:"hidden",fontFamily:"system-ui,sans-serif"});document.body.append(this.root);this.render();return this;}
 close(){document.getElementById("world-universal-ops")?.remove();this.root=null;}
 render(){if(!this.root)return;const c=company();if(!c){this.root.innerHTML="<p>Kein aktiver Betrieb.</p>";return;}const p=getIndustryProfile(c);this.root.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;padding:14px 18px;background:#0b1220"><div><b style="font-size:20px">🏭 Betrieb – ${p.label}</b><div style="opacity:.75">${c.name||"Aktiver Betrieb"} · Konto ${money(c.money)}</div></div><button data-close style="font-size:22px">✕</button></div><div data-tabs style="display:flex;gap:8px;padding:10px 18px;background:#182235"></div><div data-body style="padding:16px 18px;overflow:auto;height:calc(90vh - 115px)"></div>`;this.root.querySelector("[data-close]").onclick=()=>this.close();const tabs=[['machines','⚙️ Maschinen'],['workforce','👥 Personal'],['procurement','🛒 Einkauf'],['storage','📦 Lager'],['kpi','📊 Kennzahlen']];const bar=this.root.querySelector('[data-tabs]');for(const [id,label] of tabs){const b=el('button',label);b.style.fontWeight=this.tab===id?'800':'500';b.onclick=()=>{this.tab=id;this.render();};bar.append(b);}this[`render_${this.tab}`]?.(this.root.querySelector('[data-body]'),c,p);}
 render_machines(body,c,p){const catalog=machineCatalogFor(c),owned=ownedMachines(c);body.innerHTML=`<h2>Maschinen & Ausstattung</h2><p>Nur Ausstattung fuer <b>${p.label}</b>. Fehlende Pflichtausstattung ist markiert.</p>`;const required=new Set(p.requiredEquipment||[]);for(const m of catalog){const list=owned.filter(x=>(typeof x==='string'?x:x.id)===m.id),card=el('div',`<h3>${m.name||m.label} ${required.has(m.id)?'⚠️ Pflicht':''}</h3><div>Preis: <b>${money(m.price)}</b> · Kapazitaet: ${m.capacity||1} ${m.capacityUnit||'Einheit/h'} · vorhanden: ${list.length}</div>`);Object.assign(card.style,{padding:'12px',margin:'10px 0',border:'1px solid #374151',borderRadius:'10px'});const buy=el('button','Kaufen');buy.onclick=()=>{try{buyMachine(c,m.id,{requestId:`ui-${m.id}-${Date.now()}`});window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};card.append(buy);for(const inst of list.filter(x=>typeof x==='object')){const row=el('div',`<div style="margin-top:8px">Zustand ${pct(inst.condition??100)} · Stufe ${inst.level||1} · Auslastung ${pct(machineUtilization(inst))} · Status ${inst.status||'available'}</div>`),maint=el('button','Wartung'),up=el('button','Upgrade'),sell=el('button','Verkaufen');maint.onclick=()=>{serviceMachine(inst);this.render();};up.onclick=()=>{try{upgradeMachine(c,inst);this.render();}catch(e){alert(e.message);}};sell.onclick=()=>{if(confirm('Maschine wirklich verkaufen?')){sellMachine(c,inst);this.render();}};row.append(maint,up,sell);card.append(row);}body.append(card);}}
 render_workforce(body,c,p){if(!this.applicants.length)this.applicants=generateApplicants(c,{count:10});body.innerHTML=`<h2>Personalmarkt</h2><p>Passende Rollen fuer <b>${p.label}</b>: ${jobsFor(c).map(x=>x.label).join(', ')}</p><h3>Bewerber</h3>`;for(const a of this.applicants.filter(x=>x.available)){const card=el('div',`<b>${a.role}</b> · Qualifikation ${pct(a.qualification*100)} · ${money(a.wageMonthly)}/Monat<br><small>${(a.skills||[]).join(', ')}</small>`),b=el('button','Einstellen');Object.assign(card.style,{padding:'10px',margin:'8px 0',border:'1px solid #374151'});b.onclick=()=>{hireApplicant(c,a,{requestId:`hire-${a.id}`});window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();};card.append(b);body.append(card);}body.append(el('h3','Mitarbeiter'));for(const e of c.employees||[]){const r=el('div',`<b>${e.role||e.jobId}</b> · ${money(e.wageMonthly)}/Monat · Schicht ${e.shift||'early'} `);for(const s of ['early','late','night']){const b=el('button',s);b.onclick=()=>{assignShift(e,s);this.render();};r.append(b);}body.append(r);}}
 render_procurement(body,c){const list=buildPurchaseList(c);body.innerHTML=`<h2>🛒 Einkauf</h2><section style="padding:14px;margin-bottom:14px;border:1px solid #3b5068;border-radius:12px;background:#101827"><h3 style="margin:0 0 6px">🏞️ Grundstück & Betriebsgelände</h3><p style="margin:0 0 10px;color:#cbd5e1">Betriebsfläche kaufen, Gebäude erweitern und laufende Baustellen verwalten.</p><button type="button" data-open-expansion style="font-weight:900;padding:9px 13px">Grundstück & Ausbau öffnen</button></section><h3>📋 Bestellvorschläge</h3><p>Bestellvorschläge werden <b>nicht automatisch ausgeführt</b>.</p>`;body.querySelector('[data-open-expansion]').onclick=()=>{this.tab='expansion';this.render();};if(!list.length)body.append(el('p','Keine Mindestbestands-Unterschreitungen.'));for(const x of list)body.append(el('div',`<b>${x.item}</b>: Bestand ${x.have}, Vorschlag ${x.quantity}, Reichweite ${Number.isFinite(x.coverageDays)?x.coverageDays.toFixed(1)+' Tage':'keine Verbrauchsdaten'}`));}
 render_storage(body,c){body.innerHTML='<h2>Lageruebersicht</h2>';const inv=c.inventory||{};for(const [id,q] of Object.entries(inv).sort(([a],[b])=>a.localeCompare(b))){const days=stockCoverageDays(c,id);body.append(el('div',`<b>${id}</b>: ${Number(q||0).toLocaleString('de-DE')} · Reichweite ${Number.isFinite(days)?days.toFixed(1)+' Tage':'∞'}`));}if(!Object.keys(inv).length)body.append(el('p','Kein Bestand vorhanden.'));}
 render_kpi(body,c){const k=businessKpis(c);body.innerHTML=`<h2>Betriebskennzahlen</h2><div>Umsatz: <b>${money(k.revenue)}</b></div><div>Kosten: <b>${money(k.cost)}</b></div><div>Gewinn: <b>${money(k.profit)}</b></div><div>Marge: <b>${pct(k.margin*100)}</b></div><div>Offene Auftraege: ${k.openOrders}</div><div>Ueberfaellig: ${k.overdueOrders}</div><div>Mitarbeiter: ${k.employees}</div><div>Maschinen/Ausstattung: ${k.machines}</div>`;}
}
export const universalOperationsDialog=new UniversalOperationsDialog();if(typeof window!=="undefined")window.worldUniversalOperations=universalOperationsDialog;
