// WorldProject - zusaetzliche Eilauftraege getrennt von normalen Kundenauftraegen.
import { getIndustryProfile } from './IndustryCatalog.js';
import { ensureReputation,changeReputation } from './ReputationSystem.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureUrgentOrders(company={}){company.urgentCustomerOrders??=[];company.completedUrgentCustomerOrders??=[];company.financialLog??=[];company.finishedGoods??={};ensureReputation(company);return company.urgentCustomerOrders;}
function productCandidates(company){const p=getIndustryProfile(company);return (p.products||[]).filter(Boolean);}
function capacityEstimate(company){const machines=company.productionMachines||[],base=Math.max(100,Number(company.production?.capacity??company.productionCapacity??1000)||1000),speed=machines.length?machines.reduce((s,m)=>s+Math.max(.25,Number(m.speedMultiplier)||1),0):1,slots=Math.max(1,Number(company.productionState?.slots)||1);return Math.max(100,Math.round(base*speed*slots));}
export function urgentOrderFeasibility(company,{dueHours=24}={}){const daily=capacityEstimate(company),hours=clamp(Number(dueHours)||24,12,72),possible=Math.max(50,Math.floor(daily*(hours/24)*.72));return{dailyCapacity:daily,dueHours:hours,maxRecommended:possible};}
export function createUrgentOrder(company,{productId=null,dueHours=null,amount=null,customer=null,unitPrice=null,now=Date.now()}={}){const list=ensureUrgentOrders(company),products=productCandidates(company);if(!products.length)return{success:false,reason:'Keine passenden Produkte für dieses Gewerbe'};if(list.some(o=>o.status==='open'||o.status==='accepted'))return{success:false,reason:'Es gibt bereits einen aktiven Eilauftrag'};const hours=clamp(Number(dueHours)||([24,36,48][Math.floor(Math.random()*3)]),18,48),feasible=urgentOrderFeasibility(company,{dueHours:hours}),qty=Math.max(25,Math.min(Number(amount)||Math.round(feasible.maxRecommended*(.45+Math.random()*.35)),feasible.maxRecommended)),product=productId&&products.includes(productId)?productId:products[Math.floor(Math.random()*products.length)],base=Math.max(.01,Number(unitPrice??company.salesPrices?.[product]??1)||1),price=Math.round(base*1.18*100)/100,rep=ensureReputation(company).score,order={id:`urgent_${now}_${Math.floor(Math.random()*10000)}`,kind:'urgent',customer:customer||'Eilkundschaft',productId:product,amount:qty,delivered:0,unitPrice:price,status:'open',createdAt:now,dueAt:now+hours*3600000,reputationReward:Math.max(2,Math.round(2+qty/Math.max(feasible.dailyCapacity,1)*4)),reputationPenalty:Math.max(3,Math.round(4+(100-rep)/35)),feasibility:feasible};list.push(order);return{success:true,order};}
export function acceptUrgentOrder(company,id,at=Date.now()){const o=ensureUrgentOrders(company).find(x=>x.id===id);if(!o||o.status!=='open')return{success:false,reason:'Eilauftrag nicht verfügbar'};if(at>=Number(o.dueAt))return{success:false,reason:'Annahmefrist abgelaufen'};o.status='accepted';o.acceptedAt=at;return{success:true,order:o};}
export function settleUrgentOrder(company,order,at=Date.now()){if(!order||order.reputationSettled)return null;const complete=Number(order.delivered||0)>=Number(order.amount||0),onTime=complete&&at<=Number(order.dueAt);if(onTime){order.status='completed';order.completedAt=at;order.reputationSettled=true;const result=changeReputation(company,Number(order.reputationReward)||2,'Eilauftrag pünktlich erfüllt');if(!company.completedUrgentCustomerOrders.includes(order))company.completedUrgentCustomerOrders.push(order);return result;}if(at>Number(order.dueAt)&&order.status==='accepted'){order.status=complete?'completed_late':'failed';order.completedAt=complete?at:null;order.reputationSettled=true;const result=changeReputation(company,-Math.abs(Number(order.reputationPenalty)||4),'Eilauftrag nicht pünktlich erfüllt');if(complete&&!company.completedUrgentCustomerOrders.includes(order))company.completedUrgentCustomerOrders.push(order);return result;}return null;}
export function deliverUrgentOrder(company,id,amount,{at=Date.now()}={}){const orders=ensureUrgentOrders(company),o=orders.find(x=>x.id===id);if(!o)return{success:false,reason:'Eilauftrag fehlt'};if(o.status!=='accepted')return{success:false,reason:o.status==='open'?'Eilauftrag muss zuerst angenommen werden':'Eilauftrag ist nicht mehr lieferbar'};if(at>Number(o.dueAt)){settleUrgentOrder(company,o,at);return{success:false,reason:'Lieferfrist ist bereits abgelaufen',order:o};}const available=Math.max(0,Number(company.finishedGoods?.[o.productId])||0),remaining=Math.max(0,Number(o.amount||0)-Number(o.delivered||0)),qty=Math.min(Math.max(0,Number(amount)||0),available,remaining);if(!(qty>0))return{success:false,reason:available<=0?'Keine fertige Ware im Lager':'Keine offene Liefermenge',available,remaining};company.finishedGoods[o.productId]=available-qty;o.delivered=Number(o.delivered||0)+qty;const revenue=qty*Number(o.unitPrice||0);company.money=Number(company.money||0)+revenue;company.financialLog.push({id:`urgent_sale_${at}_${Math.random()}`,time:new Date(at),type:'urgent_customer_sale',amount:revenue,details:{orderId:o.id,productId:o.productId,qty,unitPrice:o.unitPrice}});const completed=o.delivered>=o.amount;if(completed)settleUrgentOrder(company,o,at);if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('world:game-state-dirty',{detail:{reason:'urgent-customer-delivery'}}));return{success:true,accepted:qty,revenue,completed,remaining:Math.max(0,o.amount-o.delivered),order:o,reputation:ensureReputation(company).score};}
export function processUrgentOrders(company,at=Date.now()){let changed=0;for(const o of ensureUrgentOrders(company)){if(o.status==='open'&&at>Number(o.dueAt)){o.status='expired';changed++;continue;}if(settleUrgentOrder(company,o,at))changed++;}return changed;}
export function runUrgentCustomerOrderTest(){const c={type:'Brauerei',money:100,finishedGoods:{lager033_bottle:600},salesPrices:{lager033_bottle:1},production:{capacity:1000},productionState:{slots:1}},r=createUrgentOrder(c,{productId:'lager033_bottle',dueHours:24,amount:500,unitPrice:1,now:1000});if(!r.success||r.order.amount>r.order.feasibility.maxRecommended)throw new Error('Eilauftrag nicht machbar erzeugt');acceptUrgentOrder(c,r.order.id,1100);const part=deliverUrgentOrder(c,r.order.id,200,{at:1200});if(!part.success||part.completed||c.finishedGoods.lager033_bottle!==400||c.money!==300)throw new Error('Teillieferung bucht Lager oder Umsatz falsch');const done=deliverUrgentOrder(c,r.order.id,300,{at:1300});if(!done.success||!done.completed||c.finishedGoods.lager033_bottle!==100||c.money!==600||c.reputation.score<=50||r.order.status!=='completed')throw new Error('Eilauftrag schließt Lager, Umsatz oder Ruf nicht korrekt ab');const late=createUrgentOrder(c,{productId:'lager033_bottle',dueHours:24,amount:50,now:2000});acceptUrgentOrder(c,late.order.id,2100);const before=c.reputation.score;processUrgentOrders(c,late.order.dueAt+1);if(late.order.status!=='failed'||c.reputation.score>=before)throw new Error('Versäumter angenommener Eilauftrag senkt Ruf nicht');return true;}
if(typeof window!=='undefined')window.worldUrgentOrders={ensure:ensureUrgentOrders,create:createUrgentOrder,accept:acceptUrgentOrder,deliver:deliverUrgentOrder,process:processUrgentOrders,settle:settleUrgentOrder,feasibility:urgentOrderFeasibility,test:runUrgentCustomerOrderTest};
