// WorldProject - zusaetzliche Eilauftraege getrennt von normalen Kundenauftraegen.
import { getIndustryProfile } from './IndustryCatalog.js';
import { ensureReputation,changeReputation } from './ReputationSystem.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureUrgentOrders(company={}){company.urgentCustomerOrders??=[];ensureReputation(company);return company.urgentCustomerOrders;}
function productCandidates(company){const p=getIndustryProfile(company);return (p.products||[]).filter(Boolean);}
function capacityEstimate(company){const machines=company.productionMachines||[],base=Math.max(100,Number(company.production?.capacity??company.productionCapacity??1000)||1000),speed=machines.length?machines.reduce((s,m)=>s+Math.max(.25,Number(m.speedMultiplier)||1),0):1,slots=Math.max(1,Number(company.productionState?.slots)||1);return Math.max(100,Math.round(base*speed*slots));}
export function urgentOrderFeasibility(company,{dueHours=24}={}){const daily=capacityEstimate(company),hours=clamp(Number(dueHours)||24,12,72),possible=Math.max(50,Math.floor(daily*(hours/24)*.72));return{dailyCapacity:daily,dueHours:hours,maxRecommended:possible};}
export function createUrgentOrder(company,{productId=null,dueHours=null,amount=null,customer=null,unitPrice=null,now=Date.now()}={}){const list=ensureUrgentOrders(company),products=productCandidates(company);if(!products.length)return{success:false,reason:'Keine passenden Produkte für dieses Gewerbe'};if(list.some(o=>o.status==='open'||o.status==='accepted'))return{success:false,reason:'Es gibt bereits einen aktiven Eilauftrag'};const hours=clamp(Number(dueHours)||([24,36,48][Math.floor(Math.random()*3)]),18,48),feasible=urgentOrderFeasibility(company,{dueHours:hours}),qty=Math.max(25,Math.min(Number(amount)||Math.round(feasible.maxRecommended*(.45+Math.random()*.35)),feasible.maxRecommended)),product=productId&&products.includes(productId)?productId:products[Math.floor(Math.random()*products.length)],base=Math.max(.01,Number(unitPrice??company.salesPrices?.[product]??1)||1),price=Math.round(base*1.18*100)/100,rep=ensureReputation(company).score,order={id:`urgent_${now}_${Math.floor(Math.random()*10000)}`,kind:'urgent',customer:customer||'Eilkundschaft',productId:product,amount:qty,delivered:0,unitPrice:price,status:'open',createdAt:now,dueAt:now+hours*3600000,reputationReward:Math.max(2,Math.round(2+qty/Math.max(feasible.dailyCapacity,1)*4)),reputationPenalty:Math.max(3,Math.round(4+(100-rep)/35)),feasibility:feasible};list.push(order);return{success:true,order};}
export function acceptUrgentOrder(company,id,at=Date.now()){const o=ensureUrgentOrders(company).find(x=>x.id===id);if(!o||o.status!=='open')return{success:false,reason:'Eilauftrag nicht verfügbar'};if(at>=Number(o.dueAt))return{success:false,reason:'Annahmefrist abgelaufen'};o.status='accepted';o.acceptedAt=at;return{success:true,order:o};}
export function settleUrgentOrder(company,order,at=Date.now()){if(!order||order.reputationSettled)return null;const complete=Number(order.delivered||0)>=Number(order.amount||0),onTime=complete&&at<=Number(order.dueAt);if(onTime){order.reputationSettled=true;return changeReputation(company,Number(order.reputationReward)||2,'Eilauftrag pünktlich erfüllt');}if(at>Number(order.dueAt)&&order.status==='accepted'){order.status=complete?'completed_late':'failed';order.reputationSettled=true;return changeReputation(company,-Math.abs(Number(order.reputationPenalty)||4),'Eilauftrag nicht pünktlich erfüllt');}return null;}
export function processUrgentOrders(company,at=Date.now()){let changed=0;for(const o of ensureUrgentOrders(company)){if(o.status==='open'&&at>Number(o.dueAt)){o.status='expired';changed++;continue;}if(settleUrgentOrder(company,o,at))changed++;}return changed;}
export function runUrgentCustomerOrderTest(){const c={type:'Brauerei',salesPrices:{lager033_bottle:1},production:{capacity:1000},productionState:{slots:1}},r=createUrgentOrder(c,{productId:'lager033_bottle',dueHours:24,amount:500,now:1000});if(!r.success||r.order.amount>r.order.feasibility.maxRecommended)throw new Error('Eilauftrag nicht machbar erzeugt');acceptUrgentOrder(c,r.order.id,1100);r.order.delivered=r.order.amount;const rep=settleUrgentOrder(c,r.order,1200);if(!rep||c.reputation.score<=50)throw new Error('Pünktlicher Eilauftrag erhöht Ruf nicht');return true;}
if(typeof window!=='undefined')window.worldUrgentOrders={ensure:ensureUrgentOrders,create:createUrgentOrder,accept:acceptUrgentOrder,process:processUrgentOrders,settle:settleUrgentOrder,feasibility:urgentOrderFeasibility,test:runUrgentCustomerOrderTest};
