// WorldProject - eigener kompakter Eilauftragsbereich unter normalen Kundenauftraegen.
import { EconomyDashboard } from './EconomyDashboard.js';
import { ensureUrgentOrders,createUrgentOrder,acceptUrgentOrder,deliverUrgentOrder,processUrgentOrders } from './UrgentCustomerOrderSystem.js';
function left(ms){let m=Math.max(0,Math.ceil(ms/60000));if(m>=1440)return`${Math.floor(m/1440)} T ${Math.ceil((m%1440)/60)} Std.`;if(m>=60)return`${Math.floor(m/60)} Std. ${m%60} Min.`;return`${m} Min.`;}
function maybeGenerate(company){const rows=ensureUrgentOrders(company),active=rows.some(o=>['open','accepted'].includes(o.status));if(active)return;const last=Math.max(0,...rows.map(o=>Number(o.createdAt)||0));if(!last||Date.now()-last>18*3600000)createUrgentOrder(company);}
function deliveryDialog(dashboard,panel,order){const company=dashboard.company,available=Math.max(0,Number(company.finishedGoods?.[order.productId])||0),remaining=Math.max(0,Number(order.amount)-Number(order.delivered||0)),maximum=Math.min(available,remaining);const requested=prompt(`Eilauftrag liefern\nOffen: ${dashboard.amount(remaining)}\nFertige Ware im Lager: ${dashboard.amount(available)}\nMaximal lieferbar: ${dashboard.amount(maximum)}\n\nLiefermenge:`,String(maximum));if(requested===null)return;const qty=Number(String(requested).replace(',','.'));if(!(qty>0)||qty>maximum){alert(`Ungültige Liefermenge. Maximal ${dashboard.amount(maximum)} lieferbar.`);return;}const r=deliverUrgentOrder(company,order.id,qty);if(!r.success){alert(r.reason);return;}alert(r.completed?`Eilauftrag vollständig geliefert. Umsatz ${dashboard.money(r.revenue)} €. Ruf jetzt ${Math.round(r.reputation)}/100.`:`Teillieferung ${dashboard.amount(r.accepted)}. Umsatz ${dashboard.money(r.revenue)} €. Noch ${dashboard.amount(r.remaining)} offen.`);dashboard.render(panel);}
const p=EconomyDashboard.prototype;
if(!p.__worldUrgentOrderUI){p.__worldUrgentOrderUI=true;const old=p.render;p.render=function(panel){const result=old.call(this,panel);if(this.company?.setupPhase&&this.company.setupPhase!=='operating')return result;processUrgentOrders(this.company);maybeGenerate(this.company);const normal=panel.querySelector('#dashboard-customer-orders');if(!normal)return result;let area=panel.querySelector('[data-urgent-orders]');if(area)area.remove();area=this.el('div');area.dataset.urgentOrders='1';Object.assign(area.style,{marginTop:'14px',paddingTop:'12px',borderTop:'1px solid rgba(255,255,255,.2)'});const title=this.el('strong','⚡ Eilaufträge');title.style.fontSize='16px';area.append(title,this.small('Zusätzliche kurzfristige Aufträge. Annahme ist freiwillig; nach Annahme zählt die Lieferfrist für deinen Ruf.'));const rows=ensureUrgentOrders(this.company).filter(o=>['open','accepted'].includes(o.status));if(!rows.length)area.append(this.small('Aktuell kein Eilauftrag verfügbar.'));for(const o of rows){const box=this.el('div');Object.assign(box.style,{marginTop:'9px',padding:'10px',borderRadius:'8px',background:'rgba(255,193,7,.10)',border:'1px solid rgba(255,193,7,.4)'});const remaining=Math.max(0,Number(o.amount)-Number(o.delivered||0)),available=Math.max(0,Number(this.company.finishedGoods?.[o.productId])||0),time=Number(o.dueAt)-Date.now();box.append(this.el('strong',`⚡ ${o.customer} · ${this.label(o.productId)}`),this.small(`${this.amount(remaining)} von ${this.amount(o.amount)} noch zu liefern · Frist ${left(time)}`),this.small(`💶 ${this.money(o.unitPrice)} € je Einheit · ⭐ pünktlich +${o.reputationReward} Ruf · verspätet −${o.reputationPenalty} Ruf`));if(o.status==='open'){const b=this.button('Eilauftrag annehmen',()=>{const r=acceptUrgentOrder(this.company,o.id);if(!r.success)alert(r.reason);this.render(panel);});box.append(b);}else{const tag=this.small(`✅ Angenommen · Fertige Ware im Lager: ${this.amount(available)}`);tag.style.fontWeight='800';box.append(tag);const deliver=this.button(available>0?'Ware ausliefern':'Keine fertige Ware',()=>deliveryDialog(this,panel,o));if(!(available>0)){deliver.disabled=true;deliver.style.opacity='.5';}box.append(deliver);if(available<remaining&&typeof this.produceCustomerShortfall==='function')box.append(this.button('Fehlmenge produzieren',()=>this.produceCustomerShortfall(o)));}area.append(box);}normal.append(area);return result;};}
export function runUrgentOrderUITest(){return typeof ensureUrgentOrders==='function'&&typeof deliverUrgentOrder==='function';}
