// WorldProject – zeigt im Warenmarkt, ob ein eigener Vorstufenbetrieb günstiger produzieren könnte.
import { PlayerMarketDialog } from './PlayerMarketDialog.js';
import { orderBook } from './PlayerMarketExchange.js';
import { verticalIntegrationAdvice } from './VerticalIntegrationAdvisor.js';
import { formatMoney } from './CurrencyPresentationBridge.js';
const world=()=>window.worldProjectWorld||window.worldWorld||window.worldGameState||window;
const proto=PlayerMarketDialog.prototype;
if(!proto.__verticalIntegrationAdviceIntegrated){proto.__verticalIntegrationAdviceIntegrated=true;const original=proto.renderBook;proto.renderBook=function(body,p,c,w,id){const result=original.call(this,body,p,c,w,id);try{const asks=orderBook(w||world(),id).asks.filter(o=>String(o.companyId)!==String(c?.serverCompanyId||c?.id)),external=asks.length?Number(asks[0].unitPrice||0):0,advice=verticalIntegrationAdvice(w||world(),window.worldServerAccountOverview||{},id,{externalUnitPrice:external});if(advice.hasOwnProducer){const box=document.createElement('div');Object.assign(box.style,{padding:'10px 12px',margin:'10px 0',border:'1px solid #2563eb',borderRadius:'9px',background:'rgba(30,64,175,.18)'});if(advice.bestOwn){box.textContent=`🏭 Eigene Vorstufe vorhanden: ${advice.bestOwn.name} · erkannte Eigenkosten ca. ${formatMoney(advice.bestOwn.unitCost)} / Einheit${external>0?` · günstigster Fremdkauf ${formatMoney(external)}${advice.savingPerUnit>0?` · mögliche Ersparnis ${formatMoney(advice.savingPerUnit)} / Einheit`:' · Fremdkauf ist derzeit nicht teurer'}`:''}. Die Eigenkosten bleiben bestehen; eingespart wird nur die fremde Marge bzw. Differenz.`;}else box.textContent=`🏭 Du besitzt einen Betrieb, der diese Ware herstellen kann. Für einen belastbaren Kostenvergleich fehlen dort noch Stückkostendaten.`;const h=[...body.querySelectorAll('h3')].find(x=>String(x.textContent).startsWith('Angebote:'));if(h?.nextSibling)body.insertBefore(box,h.nextSibling);else body.prepend(box);}}catch(e){console.warn('Eigenproduktionsvergleich nicht verfügbar',e);}return result;};}
export function runVerticalIntegrationMarketUITest(){return proto.__verticalIntegrationAdviceIntegrated===true;}
