// WorldProject – ergänzt den bestehenden Ausbau-Reiter um Lagerausbau + progressive Gebäudestufen.
import { UniversalOperationsDialog } from './UniversalOperationsDialog.js';
import { warehouseExpansionOverview, startWarehouseExpansion } from './WarehouseConstructionExpansionSystem.js';
import { progressiveBuildingQuote } from './ProgressiveBuildingExpansionSystem.js';
import { deliverConstructionMaterial } from './LandConstructionExpansionSystem.js';
import { generatedCrewOffers, bookGeneratedCrew } from './GeneratedConstructionCrewMarket.js';
const money=v=>Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const mins=m=>{m=Math.max(0,Math.round(Number(m||0)));return m>=60?`${Math.floor(m/60)} Std. ${m%60} Min.`:`${m} Min.`;};
const prices={concrete:135,steel:950,brick:180,insulation:160,electrical:900,pipes:750,roofing:150};
const old=UniversalOperationsDialog.prototype.render_expansion;
UniversalOperationsDialog.prototype.render_expansion=function(body,c){old.call(this,body,c);if(!c)return;const section=document.createElement('section');section.style.marginTop='16px';section.innerHTML='<h2>🏬 Lagerausbau</h2>';const o=warehouseExpansionOverview(c),q=o.next,card=document.createElement('div');Object.assign(card.style,{padding:'12px',border:'1px solid #374151',borderRadius:'10px'});card.innerHTML=`<b>Nächste Lagerstufe ${q.level}</b>: +${q.addSlots} Palettenplätze<br>Benötigte Fläche: ${q.requiredSqm} m² · frei: ${q.freeSqm} m²<br>Baukosten ab ${money(q.buildCost)} zzgl. Bautrupp · Bauzeit ca. ${mins(q.baseDurationMinutes)}<br>${q.landAvailable?'✅ Grundstücksfläche reicht':'❌ Nicht genug Grundstücksfläche – zuerst mehr Land kaufen/erweitern.'}`;
 const mat=document.createElement('div');mat.style.marginTop='8px';mat.textContent='Baumaterial: '+o.materials.map(x=>`${x.label} ${x.atSite}/${x.required} ${x.unit}`).join(' · ');card.append(mat);
 for(const m of o.materials.filter(x=>x.missing>0)){const b=document.createElement('button');b.textContent=`${m.label} +${m.missing} ${m.unit} zur Baustelle`;b.onclick=()=>{try{deliverConstructionMaterial(c,m.material,m.missing,{unitPrice:prices[m.material]||100});alert(`${m.label} wurde zur Baustelle geliefert.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};card.append(b);}
 const crewBox=document.createElement('div');crewBox.style.marginTop='10px';const activeBooking=o.bookings.find(x=>x.status==='booked');if(activeBooking){crewBox.innerHTML=`<b>Bautrupp gebucht:</b> ${activeBooking.label} · ${activeBooking.workers} Pers. · ${money(activeBooking.dailyCost)}/Tag · verfügbar in ca. ${mins(Math.max(0,(activeBooking.availableAt-Date.now())/60000))}`;}else{crewBox.innerHTML='<b>Aktuelle Bautrupp-Angebote:</b><br><small>Die Angebote wechseln regelmäßig. Preis, Geschwindigkeit, Anfahrt und Zuverlässigkeit unterscheiden sich.</small>';for(const crew of generatedCrewOffers(c)){const b=document.createElement('button');b.style.display='block';b.style.margin='5px 0';b.textContent=`${crew.label} · ${crew.workers} Pers. · ${money(crew.dailyCost)}/Tag · Tempo ${Math.round(crew.speedFactor*100)}% · Zuverlässigkeit ${Math.round(crew.reliability*100)}% · Anfahrt ${crew.availabilityMinutes} Min.`;b.onclick=()=>{try{bookGeneratedCrew(c,crew);alert(`${crew.label} wurde gebucht und ist unterwegs.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};crewBox.append(b);}}card.append(crewBox);
 const currentBooking=o.bookings.find(x=>x.status==='booked'),start=document.createElement('button');start.textContent=o.active?'Lagerausbau läuft …':'Lagerausbau starten';start.disabled=!!o.active||!currentBooking||!q.landAvailable||o.materials.some(x=>x.missing>0);start.onclick=()=>{try{const j=startWarehouseExpansion(c,{crewBookingId:currentBooking.id});alert(`Lagerausbau gestartet. +${j.addSlots} Plätze nach Fertigstellung.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};card.append(start);if(o.active){const p=document.createElement('div');p.style.marginTop='8px';p.textContent=`🏗️ Fortschritt ${o.active.progress}% · verbleibend ca. ${mins(Math.max(0,(o.active.finishAt-Date.now())/60000))}`;card.append(p);}section.append(card);body.append(section);
 const headers=[...body.querySelectorAll('h3')].find(h=>h.textContent.includes('Gebäude bauen'));const parent=headers?.parentElement;if(parent){for(const id of ['brewhouse','fermentation_house','production_hall','workshop','warehouse']){try{const pq=progressiveBuildingQuote(c,id),note=document.createElement('div');note.style.fontSize='12px';note.style.opacity='.8';note.textContent=`${pq.label}: nächste Ausbaustufe ${pq.stage} · ${money(pq.cost)} · ${mins(pq.durationMinutes)}`;parent.append(note);}catch{}}}
};
if(typeof window!=='undefined')window.worldWarehouseExpansionUIIntegration=true;
