// ORVUNO – ergänzt den Ausbau-Reiter um Lagerausbau.
import { UniversalOperationsDialog } from './UniversalOperationsDialog.js';
import { warehouseExpansionOverview, startWarehouseExpansion } from './WarehouseConstructionExpansionSystem.js';
import { progressiveBuildingQuote } from './ProgressiveBuildingExpansionSystem.js';
import { orderConstructionMaterial, pendingConstructionMaterial, processConstructionMaterialDeliveries } from './ConstructionMaterialLogisticsSystem.js';
const money=v=>Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const mins=m=>{m=Math.max(0,Math.round(Number(m||0)));return m>=60?`${Math.floor(m/60)} Std. ${m%60} Min.`:`${m} Min.`;};
const prices={concrete:135,steel:950,brick:180,insulation:160,electrical:900,pipes:750,roofing:150};
const old=UniversalOperationsDialog.prototype.render_expansion;
UniversalOperationsDialog.prototype.render_expansion=function(body,c){old.call(this,body,c);if(!c)return;processConstructionMaterialDeliveries(c);const section=document.createElement('section');section.style.marginTop='16px';section.innerHTML='<h2>🏬 Lagerausbau</h2>';const o=warehouseExpansionOverview(c),q=o.next,card=document.createElement('div');Object.assign(card.style,{padding:'12px',border:'1px solid #374151',borderRadius:'10px'});card.innerHTML=`<b>Nächste Lagerstufe ${q.level}</b>: +${q.addSlots} Palettenplätze<br>Benötigte Fläche: ${q.requiredSqm} m² · frei: ${q.freeSqm} m²<br>Baukosten ab ${money(q.buildCost)} zzgl. Bautrupp · Bauzeit ca. ${mins(q.baseDurationMinutes)}<br>${q.landAvailable?'✅ Grundstücksfläche reicht':'❌ Nicht genug Grundstücksfläche – zuerst mehr Land kaufen/erweitern.'}`;
 const mat=document.createElement('div');mat.style.marginTop='8px';mat.textContent='Baumaterial: '+o.materials.map(x=>`${x.label} ${x.atSite}/${x.required} ${x.unit}${pendingConstructionMaterial(c,x.material)?` (${pendingConstructionMaterial(c,x.material)} unterwegs)`:''}`).join(' · ');card.append(mat);
 for(const m of o.materials.filter(x=>x.missing>0)){const pending=pendingConstructionMaterial(c,m.material),qty=Math.max(0,m.missing-pending);if(!qty)continue;const b=document.createElement('button');b.textContent=`🚚 ${m.label} +${qty} ${m.unit} bestellen`;b.onclick=()=>{try{const d=orderConstructionMaterial(c,m.material,qty,{unitPrice:prices[m.material]||100});alert(`${m.label} bestellt. Lieferung in ca. ${mins(d.etaMinutes)}.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};card.append(b);}
 const bookings=o.bookings||[],freeCrew=bookings.find(x=>x.status==='booked'&&Number(x.availableAt||0)<=Date.now()&&Number(x.assignedUntil||0)<=Date.now());const crewInfo=document.createElement('div');crewInfo.style.marginTop='10px';const activeCrews=bookings.filter(x=>['booked','assigned'].includes(x.status));crewInfo.innerHTML=activeCrews.length?`<b>Bautrupps:</b> ${activeCrews.map(x=>`${x.label} (${x.status==='assigned'?'im Einsatz':'gebucht'})`).join(' · ')}`:'<b>Kein Bautrupp gebucht.</b> Weitere Bautrupps findest du oben im Abschnitt „Bautrupp-Markt“.';card.append(crewInfo);
 const start=document.createElement('button');start.textContent=o.active?'Lagerausbau läuft …':!freeCrew?'Kein freier Bautrupp':'Lagerausbau starten';start.disabled=!!o.active||!freeCrew||!q.landAvailable||o.materials.some(x=>x.missing>0);start.onclick=()=>{try{const j=startWarehouseExpansion(c,{crewBookingId:freeCrew.id});alert(`Lagerausbau gestartet. +${j.addSlots} Plätze nach Fertigstellung.`);window.dispatchEvent(new CustomEvent('world:game-state-dirty'));this.render();}catch(e){alert(e.message);}};card.append(start);if(o.active){const p=document.createElement('div');p.style.marginTop='8px';p.textContent=`🏗️ Fortschritt ${o.active.progress}% · verbleibend ca. ${mins(Math.max(0,(o.active.finishAt-Date.now())/60000))}`;card.append(p);}section.append(card);body.append(section);
 const headers=[...body.querySelectorAll('h3')].find(h=>h.textContent.includes('Gebäude bauen'));const parent=headers?.parentElement;if(parent){const crewNote=document.createElement('div');crewNote.style.cssText='margin:8px 0;padding:8px;border:1px solid #374151;border-radius:8px;font-size:12px';crewNote.textContent='👷 Gebäudebau benötigt einen gebuchten und freien Bautrupp. Mehrere Bautrupps können parallel eingesetzt werden, soweit freie Bauplätze vorhanden sind.';parent.insertBefore(crewNote,headers.nextSibling);for(const id of ['brewhouse','fermentation_house','production_hall','workshop','warehouse']){try{const pq=progressiveBuildingQuote(c,id),note=document.createElement('div');note.style.fontSize='12px';note.style.opacity='.8';note.textContent=`${pq.label}: nächste Ausbaustufe ${pq.stage} · ${money(pq.cost)} zzgl. Bautrupp · Grundbauzeit ${mins(pq.durationMinutes)}`;parent.append(note);}catch{}}}
};
if(typeof window!=='undefined')window.worldWarehouseExpansionUIIntegration=true;
