// WorldProject - Lagergesundheit, Zonenpruefung und Altbestandsbereinigung.
import { worldContentRegistry } from "./ContentRegistry.js";

const unitFallback={malt:"kg",hops:"kg",yeast:"kg",water:"l",bottles:"Stk",clean_bottles:"Stk",caps:"Stk",labels:"Stk",beer_bulk_pils:"l",beer_bulk_lager:"l"};
function unitFor(id){return worldContentRegistry.get("materials",id)?.unit||unitFallback[id]||"Einheiten";}
function cleanNumber(value){const n=Number(value);return Number.isFinite(n)&&n>0?n:0;}
export function normalizeWarehouseStock(stock={}){const repaired=[];for(const[zone,items]of Object.entries(stock)){if(!items||typeof items!=="object"){stock[zone]={};repaired.push(`${zone}:reset`);continue;}for(const[id,value]of Object.entries(items)){const next=cleanNumber(value);if(next!==Number(value)){items[id]=next;repaired.push(`${zone}.${id}`);}if(id==="undefined"||id==="materials.undefined"){delete items[id];repaired.push(`${zone}.${id}:removed`);}}}return repaired;}
export function expectedZone(material){return worldContentRegistry.get("materials",material)?.storageZone||(["bottles","clean_bottles","caps","labels","packaging"].includes(material)?"packaging":["beer_bulk_pils","beer_bulk_lager"].includes(material)?"finished":["yeast"].includes(material)?"cold":"raw");}
export function auditWarehouse(warehouse){if(!warehouse)throw new Error("Lager fehlt");normalizeWarehouseStock(warehouse.stock||{});const issues=[],zones={};for(const zone of Object.keys(warehouse.stock||{})){const used=Object.values(warehouse.stock[zone]||{}).reduce((s,v)=>s+cleanNumber(v),0),capacity=Number(warehouse.capacity?.(zone)??warehouse.capacities?.[zone]??0)||0,percent=capacity>0?used/capacity*100:(used>0?Infinity:0);zones[zone]={used,capacity,free:Math.max(0,capacity-used),percent,warning:percent>=95?"critical":percent>=80?"warning":"ok"};for(const[id,value]of Object.entries(warehouse.stock[zone]||{})){const expected=expectedZone(id);if(expected!==zone&&cleanNumber(value)>0)issues.push({type:"wrong_zone",material:id,zone,expected,quantity:cleanNumber(value)});}}return{success:issues.length===0,issues,zones};}
export function moveMisplacedStock(warehouse){const audit=auditWarehouse(warehouse),moved=[];for(const issue of audit.issues.filter(x=>x.type==="wrong_zone")){const qty=cleanNumber(warehouse.stock[issue.zone]?.[issue.material]);if(!(qty>0))continue;warehouse.stock[issue.expected]??={};const capacity=Number(warehouse.capacity?.(issue.expected)??warehouse.capacities?.[issue.expected]??0)||0,used=Object.values(warehouse.stock[issue.expected]).reduce((s,v)=>s+cleanNumber(v),0);if(capacity>0&&used+qty>capacity)continue;delete warehouse.stock[issue.zone][issue.material];warehouse.stock[issue.expected][issue.material]=cleanNumber(warehouse.stock[issue.expected][issue.material])+qty;moved.push(issue);}return moved;}
export function warehouseRows(warehouse){const rows=[];for(const[zone,items]of Object.entries(warehouse?.stock||{}))for(const[id,value]of Object.entries(items||{})){const amount=cleanNumber(value);if(amount>0)rows.push({zone,material:id,amount,unit:unitFor(id)});}return rows.sort((a,b)=>a.zone.localeCompare(b.zone)||a.material.localeCompare(b.material));}
export function deliveryReceiptStatus(order){const total=cleanNumber(order?.quantity??order?.amount),received=cleanNumber(order?.receivedQuantity),remaining=Math.max(0,total-received);return{total,received,remaining,status:order?.status||"unknown",receivedPercent:total>0?Math.min(100,received/total*100):0,lastReceiptAt:order?.lastReceiptAt||order?.storedAt||null};}
export function runWarehouseHealthTest(){const warehouse={stock:{raw:{malt:500,bottles:10,bad:NaN,"materials.undefined":5},packaging:{caps:950},finished:{beer_bulk_pils:20},cold:{}},capacities:{raw:1000,packaging:1000,finished:100,cold:100},capacity(z){return this.capacities[z]||0;}};const repaired=normalizeWarehouseStock(warehouse.stock);if(!repaired.length||warehouse.stock.raw.bad!==0||warehouse.stock.raw["materials.undefined"]!==undefined)throw new Error("Altbestandsbereinigung fehlgeschlagen");let audit=auditWarehouse(warehouse);if(!audit.issues.some(x=>x.material==="bottles")||audit.zones.packaging.warning!=="critical")throw new Error("Lagerzonen-/Warnpruefung fehlgeschlagen");const moved=moveMisplacedStock(warehouse);if(moved.length!==1||warehouse.stock.packaging.bottles!==10)throw new Error("Fehlbestand wurde nicht korrekt umgelagert");const rows=warehouseRows(warehouse);if(!rows.some(r=>r.material==="malt"&&r.unit==="kg"))throw new Error("Lagereinheit fehlt");const status=deliveryReceiptStatus({quantity:500,receivedQuantity:300,status:"partially_stored"});if(status.remaining!==200||status.receivedPercent!==60)throw new Error("Teil-Wareneingangsstatus falsch");console.log("✅ WAREHOUSE-HEALTH-TEST ERFOLGREICH");return{success:true};}
