// WorldProject – Lagerausbau in festen 500-Palettenplatz-Schritten mit externem Bautrupp.
import { ensureExpansionState, ConstructionMaterials } from './LandConstructionExpansionSystem.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const id=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
export const WAREHOUSE_STEP=500;
export const ConstructionCrewCatalog=Object.freeze([
 {id:'crew_small',label:'Kleiner Bautrupp',workers:4,dailyCost:1800,speedFactor:1,availabilityMinutes:20},
 {id:'crew_standard',label:'Standard-Bautrupp',workers:8,dailyCost:3400,speedFactor:1.25,availabilityMinutes:15},
 {id:'crew_large',label:'Großer Bautrupp',workers:14,dailyCost:5900,speedFactor:1.55,availabilityMinutes:10}
]);
export function ensureWarehouseExpansion(company={}){ensureExpansionState(company);company.warehouseExpansion??={level:0,extraSlots:0,jobs:[],crewBookings:[]};company.warehouseExpansion.jobs??=[];company.warehouseExpansion.crewBookings??=[];return company;}
export function warehouseExpansionQuote(company={}){ensureWarehouseExpansion(company);const level=n(company.warehouseExpansion.level)+1,growth=Math.pow(1.55,Math.max(0,level-1)),materialGrowth=Math.pow(1.32,Math.max(0,level-1));return{level,addSlots:WAREHOUSE_STEP,buildCost:Math.round(12000*growth),baseDurationMinutes:Math.round(180*Math.pow(1.18,Math.max(0,level-1))),materials:{concrete:Math.ceil(10*materialGrowth),steel:Math.ceil(3*materialGrowth),brick:Math.ceil(5*materialGrowth),electrical:Math.ceil(1*materialGrowth),roofing:Math.ceil(4*materialGrowth)}};}
export function warehouseMaterialNeed(company={}){ensureWarehouseExpansion(company);const q=warehouseExpansionQuote(company),site=company.constructionSite.materials;return Object.entries(q.materials).map(([material,required])=>({material,label:ConstructionMaterials[material]?.label||material,unit:ConstructionMaterials[material]?.unit||'',required,atSite:n(site[material]),missing:Math.max(0,required-n(site[material]))}));}
export function availableConstructionCrews(){return ConstructionCrewCatalog.map(x=>({...x}));}
export function hireConstructionCrew(company,crewId,{now=Date.now()}={}){ensureWarehouseExpansion(company);const crew=ConstructionCrewCatalog.find(x=>x.id===crewId);if(!crew)throw new Error('Unbekannter Bautrupp');if(company.warehouseExpansion.crewBookings.some(x=>x.status==='booked'))throw new Error('Es ist bereits ein Bautrupp gebucht');const booking={id:id('crew'),crewId:crew.id,label:crew.label,workers:crew.workers,dailyCost:crew.dailyCost,speedFactor:crew.speedFactor,bookedAt:now,availableAt:now+crew.availabilityMinutes*60000,status:'booked'};company.warehouseExpansion.crewBookings.push(booking);return booking;}
export function startWarehouseExpansion(company,{crewBookingId,now=Date.now()}={}){ensureWarehouseExpansion(company);if(company.warehouseExpansion.jobs.some(j=>j.status==='building'))throw new Error('Lagerausbau läuft bereits');const quote=warehouseExpansionQuote(company),crew=company.warehouseExpansion.crewBookings.find(x=>x.id===crewBookingId&&x.status==='booked');if(!crew)throw new Error('Kein gebuchter Bautrupp verfügbar');if(n(crew.availableAt)>now)throw new Error(`Bautrupp ist noch unterwegs. Verfügbar in ca. ${Math.ceil((crew.availableAt-now)/60000)} Minuten`);const missing=warehouseMaterialNeed(company).filter(x=>x.missing>0);if(missing.length)throw new Error(`Baumaterial fehlt: ${missing.map(x=>`${x.label} ${x.missing} ${x.unit}`).join(', ')}`);const durationMinutes=Math.max(30,Math.round(quote.baseDurationMinutes/n(crew.speedFactor,1))),days=Math.max(1,durationMinutes/1440),crewCost=Math.round(n(crew.dailyCost)*days),totalCost=quote.buildCost+crewCost;if(n(company.money)<totalCost)throw new Error(`Nicht genug Geld. Bau + Bautrupp kosten ${totalCost.toLocaleString('de-DE')} €`);company.money-=totalCost;for(const [material,qty] of Object.entries(quote.materials))company.constructionSite.materials[material]=Math.max(0,n(company.constructionSite.materials[material])-qty);crew.status='assigned';crew.assignedAt=now;const job={id:id('warehouse-expansion'),kind:'warehouse_expansion',label:`Lagerausbau +${WAREHOUSE_STEP} Palettenplätze`,level:quote.level,addSlots:WAREHOUSE_STEP,buildCost:quote.buildCost,crewCost,totalCost,crewBookingId:crew.id,materials:{...quote.materials},startedAt:now,finishAt:now+durationMinutes*60000,durationMinutes,status:'building'};company.warehouseExpansion.jobs.push(job);return job;}
export function advanceWarehouseExpansion(company,{now=Date.now()}={}){ensureWarehouseExpansion(company);const done=[];for(const j of company.warehouseExpansion.jobs.filter(x=>x.status==='building'&&n(x.finishAt)<=now)){j.status='finished';j.finishedAt=now;company.warehouseExpansion.level=Math.max(n(company.warehouseExpansion.level),n(j.level));company.warehouseExpansion.extraSlots=n(company.warehouseExpansion.extraSlots)+n(j.addSlots);company.warehouseCapacity=n(company.warehouseCapacity)+n(j.addSlots);const crew=company.warehouseExpansion.crewBookings.find(x=>x.id===j.crewBookingId);if(crew){crew.status='completed';crew.completedAt=now;}done.push(j);}return done;}
export function warehouseExpansionOverview(company,{now=Date.now()}={}){advanceWarehouseExpansion(company,{now});ensureWarehouseExpansion(company);const active=company.warehouseExpansion.jobs.find(x=>x.status==='building')||null;return{level:n(company.warehouseExpansion.level),extraSlots:n(company.warehouseExpansion.extraSlots),next:warehouseExpansionQuote(company),materials:warehouseMaterialNeed(company),crews:availableConstructionCrews(),bookings:company.warehouseExpansion.crewBookings,active:active?{...active,progress:Math.max(0,Math.min(99,Math.round((now-active.startedAt)/(active.finishAt-active.startedAt)*100)))}:null};}
export function runWarehouseConstructionExpansionTest(){const c={money:1000000,warehouseCapacity:1000,constructionSite:{materials:{concrete:100,steel:100,brick:100,electrical:100,roofing:100},jobs:[],deliveries:[]}};ensureWarehouseExpansion(c);const crew=hireConstructionCrew(c,'crew_standard',{now:0});const j=startWarehouseExpansion(c,{crewBookingId:crew.id,now:crew.availableAt});if(c.warehouseCapacity!==1000)throw new Error('Lager darf nicht sofort größer werden');advanceWarehouseExpansion(c,{now:j.finishAt});if(c.warehouseCapacity!==1500||c.warehouseExpansion.level!==1)throw new Error('Lagerausbau +500 fehlgeschlagen');return true;}
if(typeof window!=='undefined')window.worldWarehouseConstructionExpansion={ensureWarehouseExpansion,quote:warehouseExpansionQuote,materialNeed:warehouseMaterialNeed,crews:availableConstructionCrews,hireCrew:hireConstructionCrew,start:startWarehouseExpansion,advance:advanceWarehouseExpansion,overview:warehouseExpansionOverview,runTest:runWarehouseConstructionExpansionTest};
