// WorldProject – Lagerautomatisierung: Slotting, Nachschub, Picking, Quarantäne.
import { ensureWarehouse,zoneUsage } from './IndustryWarehouseEngine.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureWarehouseAutomation(c={}){ensureWarehouse(c);c.warehouseAutomation??={policies:{},tasks:[],history:[]};return c.warehouseAutomation;}
export function setWarehousePolicy(c,item,{pickZone='finished',reserveZone='raw',minPick=10,targetPick=50,strategy='FEFO'}={}){const s=ensureWarehouseAutomation(c);s.policies[item]={pickZone,reserveZone,minPick:Math.max(0,n(minPick)),targetPick:Math.max(0,n(targetPick)),strategy};return s.policies[item];}
export function suggestSlotting(c){const s=ensureWarehouseAutomation(c),lots=c.warehouse.lots||[],moves=[];for(const lot of lots.filter(x=>x.quantity>0)){const p=s.policies[lot.item];if(!p)continue;if(lot.zone!==p.reserveZone&&lot.zone!==p.pickZone)moves.push({lotId:lot.id,item:lot.item,from:lot.zone,to:p.reserveZone,quantity:lot.quantity,reason:'slotting'});}return moves;}
export function generateReplenishmentTasks(c){const s=ensureWarehouseAutomation(c),lots=c.warehouse.lots||[],tasks=[];for(const[item,p]of Object.entries(s.policies)){const pick=lots.filter(x=>x.item===item&&x.zone===p.pickZone&&x.quantity>0).reduce((a,x)=>a+n(x.quantity),0),reserve=lots.filter(x=>x.item===item&&x.zone===p.reserveZone&&x.quantity>0).reduce((a,x)=>a+n(x.quantity),0);if(pick<p.minPick&&reserve>0){const q=Math.min(reserve,Math.max(0,p.targetPick-pick)),task={id:`replen-${Date.now()}-${item}`,kind:'replenish',item,from:p.reserveZone,to:p.pickZone,quantity:q,status:'open',createdAt:Date.now()};tasks.push(task);}}s.tasks.push(...tasks);return tasks;}
export function executeWarehouseMove(c,taskId){const s=ensureWarehouseAutomation(c),t=s.tasks.find(x=>x.id===taskId);if(!t)throw new Error('Lageraufgabe fehlt');if(t.status==='done')return{success:true,idempotent:true};let left=n(t.quantity);const lots=(c.warehouse.lots||[]).filter(x=>x.item===t.item&&x.zone===t.from&&x.quantity>0).sort((a,b)=>(a.expiresAt||Infinity)-(b.expiresAt||Infinity)||a.receivedAt-b.receivedAt);for(const lot of lots){const take=Math.min(left,n(lot.quantity));lot.quantity-=take;left-=take;const target={...lot,id:`${lot.id}-move-${Date.now()}`,quantity:take,zone:t.to,receivedAt:Date.now()};c.warehouse.lots.push(target);if(left<=1e-9)break;}if(left>1e-9)throw new Error('Nicht genug Bestand für Umlagerung');t.status='done';t.finishedAt=Date.now();s.history.push({...t});return{success:true,task:t};}
export function quarantineLot(c,lotId,{reason='Qualitätsprüfung'}={}){ensureWarehouseAutomation(c);const lot=c.warehouse.lots.find(x=>x.id===lotId);if(!lot)throw new Error('Charge fehlt');lot.previousZone=lot.zone;lot.zone='quarantine';lot.quarantineReason=reason;lot.quarantinedAt=Date.now();return lot;}
export function releaseQuarantine(c,lotId){const lot=c.warehouse?.lots?.find(x=>x.id===lotId);if(!lot||lot.zone!=='quarantine')throw new Error('Charge nicht in Quarantäne');lot.zone=lot.previousZone||'raw';delete lot.previousZone;delete lot.quarantineReason;lot.releasedAt=Date.now();return lot;}
export function warehouseAutomationKpis(c){const s=ensureWarehouseAutomation(c),zones=Object.keys(c.warehouse.zones||{}).map(z=>zoneUsage(c,z));return{policies:Object.keys(s.policies).length,openTasks:s.tasks.filter(x=>x.status==='open').length,doneTasks:s.history.length,quarantine:(c.warehouse.lots||[]).filter(x=>x.zone==='quarantine'&&x.quantity>0).length,criticalZones:zones.filter(x=>x.utilization>=.9).map(x=>x.zone)};}
