// Lager-Rueckverfolgbarkeit, Sperrbestand und Inventur fuer alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function ensureTraceability(c={}){c.traceability??={lots:[],holds:[],audits:[],moves:[]};return c.traceability;}
export function registerTraceLot(c,{item,quantity,batchId,sourceId,zone='raw',expiresAt=null,parentLots=[]}={}){const t=ensureTraceability(c),row={id:`trace-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,item,quantity:Math.max(0,n(quantity)),batchId:batchId||null,sourceId:sourceId||null,zone,expiresAt:expiresAt?Number(expiresAt):null,parentLots:[...parentLots],status:'available',createdAt:Date.now()};t.lots.push(row);return row;}
export function placeQualityHold(c,lotId,{reason='quality_check'}={}){const t=ensureTraceability(c),lot=t.lots.find(x=>x.id===lotId);if(!lot)throw new Error('Charge fehlt');lot.status='hold';const h={id:`hold-${Date.now()}`,lotId,reason,status:'active',at:Date.now()};t.holds.push(h);return h;}
export function releaseQualityHoldLot(c,lotId){const t=ensureTraceability(c),lot=t.lots.find(x=>x.id===lotId);if(!lot)throw new Error('Charge fehlt');lot.status='available';for(const h of t.holds.filter(x=>x.lotId===lotId&&x.status==='active')){h.status='released';h.releasedAt=Date.now();}return lot;}
export function selectableLots(c,item,{mode='FEFO',now=Date.now()}={}){let rows=ensureTraceability(c).lots.filter(x=>x.item===item&&x.status==='available'&&x.quantity>0&&(!x.expiresAt||x.expiresAt>now));return rows.sort(mode==='FIFO'?(a,b)=>a.createdAt-b.createdAt:(a,b)=>(a.expiresAt||Infinity)-(b.expiresAt||Infinity)||a.createdAt-b.createdAt);}
export function moveTraceLot(c,lotId,toZone,{quantity=null}={}){const t=ensureTraceability(c),lot=t.lots.find(x=>x.id===lotId);if(!lot)throw new Error('Charge fehlt');const q=Math.min(lot.quantity,Math.max(0,n(quantity,lot.quantity)));if(q===lot.quantity){const from=lot.zone;lot.zone=toZone;t.moves.push({lotId,from,to:toZone,quantity:q,at:Date.now()});return lot;}lot.quantity-=q;const split={...lot,id:`${lot.id}-split-${Date.now()}`,quantity:q,zone:toZone,createdAt:Date.now()};t.lots.push(split);t.moves.push({lotId:split.id,from:lot.zone,to:toZone,quantity:q,at:Date.now()});return split;}
export function inventoryAudit(c,physical={}){const t=ensureTraceability(c),book={};for(const lot of t.lots.filter(x=>x.quantity>0))book[lot.item]=n(book[lot.item])+lot.quantity;const differences=[];for(const item of new Set([...Object.keys(book),...Object.keys(physical)])){const expected=n(book[item]),actual=n(physical[item]),diff=actual-expected;if(Math.abs(diff)>1e-9)differences.push({item,expected,actual,difference:diff});}const audit={id:`inv-${Date.now()}`,at:Date.now(),differences};t.audits.push(audit);return audit;}
export function traceOrigins(c,lotId){const t=ensureTraceability(c),seen=new Set(),out=[];const visit=id=>{if(seen.has(id))return;seen.add(id);const lot=t.lots.find(x=>x.id===id);if(!lot)return;out.push(lot);for(const p of lot.parentLots||[])visit(p);};visit(lotId);return out;}
export function traceabilityKpis(c){const t=ensureTraceability(c),now=Date.now();return{lots:t.lots.filter(x=>x.quantity>0).length,onHold:t.lots.filter(x=>x.status==='hold'&&x.quantity>0).length,expiringSoon:t.lots.filter(x=>x.quantity>0&&x.expiresAt&&x.expiresAt>now&&x.expiresAt<now+7*86400000).length,audits:t.audits.length,moves:t.moves.length};}
