// WorldProject - Personal, Schichten, Schulungen, Maschinenverschleiss, Energie und Betriebskosten
import { worldContentRegistry } from "./ContentRegistry.js";

export function jobsForIndustry(industry){return worldContentRegistry.list("jobs").filter(j=>(j.industries||[]).includes("*")||(j.industries||[]).includes(industry));}
export function shifts(){return worldContentRegistry.list("shifts");}
export function trainingCoursesForIndustry(industry){return worldContentRegistry.list("trainingCourses").filter(c=>(c.industries||[]).includes("*")||(c.industries||[]).includes(industry));}
export function energyType(id){return worldContentRegistry.get("energyTypes",id);}
export function maintenanceRule(id="standard"){return worldContentRegistry.get("maintenanceRules",id)||worldContentRegistry.get("maintenanceRules","standard");}
export function shiftContainsHour(shiftId,hour=new Date().getHours()){const s=worldContentRegistry.get("shifts",shiftId);if(!s)return false;const h=((Number(hour)%24)+24)%24;return s.startHour<s.endHour?h>=s.startHour&&h<s.endHour:h>=s.startHour||h<s.endHour;}
function dayStamp(date){const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function addDays(date,days){const d=new Date(date);d.setDate(d.getDate()+days);return d;}

export class WorkforceSystem{
 constructor(){this.employees=[];this.seq=1;this.assignments=[];this.trainings=[];this.trainingSeq=1;this.trainingCosts=0;}
 hire({jobId,name=null,qualification=1,wageMonthly=null,industry="*"}){const job=worldContentRegistry.get("jobs",jobId);if(!job)throw new Error("Unbekannter Beruf");if(!(job.industries||[]).includes("*")&&!(job.industries||[]).includes(industry))throw new Error("Beruf passt nicht zur Branche");const e={id:this.seq++,name:name||`${job.label} ${this.seq}`,jobId,qualification:Math.max(.5,Math.min(2,Number(qualification||1))),wageMonthly:Number(wageMonthly||job.baseWageMonthly||0),industry,active:true,satisfaction:75,overtimeHours:0,workload:0,extraSkills:[]};this.employees.push(e);return e;}
 fire(employeeId){const e=this.employees.find(x=>x.id===employeeId);if(!e)throw new Error("Mitarbeiter nicht gefunden");e.active=false;this.assignments=this.assignments.filter(x=>x.employeeId!==employeeId);return e;}
 assign(employeeId,{shiftId,machineId=null,area=null}={}){const e=this.employees.find(x=>x.id===employeeId&&x.active);if(!e)throw new Error("Mitarbeiter nicht gefunden");if(!worldContentRegistry.get("shifts",shiftId))throw new Error("Unbekannte Schicht");const a={employeeId,shiftId,machineId,area};this.assignments=this.assignments.filter(x=>x.employeeId!==employeeId);this.assignments.push(a);return a;}
 employeeSkills(employee){return [...new Set([...(worldContentRegistry.get("jobs",employee.jobId)?.skills||[]),...(employee.extraSkills||[])])];}
 isTrainingDay(employeeId,date=new Date()){const stamp=dayStamp(date);return this.trainings.some(t=>t.employeeId===employeeId&&t.status==="active"&&(t.schoolDates||[]).includes(stamp));}
 availableFor({shiftId,skill,machineId=null,hour=null,date=new Date()}={}){return this.assignments.map(a=>({a,e:this.employees.find(x=>x.id===a.employeeId)})).filter(({a,e})=>e?.active&&!this.isTrainingDay(e.id,date)&&a.shiftId===shiftId&&(hour===null||shiftContainsHour(a.shiftId,hour))&&(!machineId||a.machineId===machineId)&&(!skill||this.employeeSkills(e).includes(skill))).map(x=>x.e);}
 startTraining(employeeId,courseId,{startDate=new Date()}={}){const e=this.employees.find(x=>x.id===employeeId&&x.active);if(!e)throw new Error("Mitarbeiter nicht gefunden");if(this.trainings.some(t=>t.employeeId===employeeId&&t.status==="active"))throw new Error("Mitarbeiter nimmt bereits an einer Schulung teil");const c=worldContentRegistry.get("trainingCourses",courseId);if(!c)throw new Error("Unbekannte Schulung");if(!(c.industries||[]).includes("*")&&!(c.industries||[]).includes(e.industry))throw new Error("Schulung passt nicht zur Branche");const weeks=Math.max(1,Number(c.weeks||1)),daysPerWeek=Math.max(1,Number(c.schoolDaysPerWeek||1)),weekdays=Array.isArray(c.schoolWeekdays)&&c.schoolWeekdays.length?c.schoolWeekdays:[Number(c.schoolWeekday??1)];const schoolDates=[];let cursor=new Date(startDate);for(let w=0;w<weeks;w++){for(let n=0;n<daysPerWeek;n++){const target=weekdays[n%weekdays.length];let d=addDays(cursor,w*7);while(d.getDay()!==target)d=addDays(d,1);schoolDates.push(dayStamp(d));}}const cost=schoolDates.length*Number(c.costPerSchoolDay||0);const t={id:this.trainingSeq++,employeeId,courseId,status:"active",startedAt:dayStamp(startDate),schoolDates,totalSchoolDays:schoolDates.length,attendedSchoolDays:0,cost,qualificationGain:Number(c.qualificationGain||0),skills:[...(c.skills||[])]};this.trainings.push(t);this.trainingCosts+=cost;return t;}
 processTrainingDate(date=new Date()){const stamp=dayStamp(date),completed=[];for(const t of this.trainings.filter(x=>x.status==="active")){if((t.schoolDates||[]).includes(stamp)&&!(t.attendedDates||[]).includes(stamp)){t.attendedDates=[...(t.attendedDates||[]),stamp];t.attendedSchoolDays++;}if(t.attendedSchoolDays>=t.totalSchoolDays){t.status="completed";t.completedAt=stamp;const e=this.employees.find(x=>x.id===t.employeeId);if(e){e.qualification=Math.min(2,Number(e.qualification||1)+t.qualificationGain);e.extraSkills=[...new Set([...(e.extraSkills||[]),...t.skills])];}completed.push(t);}}return completed;}
 trainingOverview(employeeId=null){return this.trainings.filter(t=>employeeId===null||t.employeeId===employeeId).map(t=>({...t,course:worldContentRegistry.get("trainingCourses",t.courseId)}));}
 setOvertime(employeeId,hours=0){const e=this.employees.find(x=>x.id===employeeId&&x.active);if(!e)throw new Error("Mitarbeiter nicht gefunden");e.overtimeHours=Math.max(0,Number(hours||0));this.recalculateSatisfaction(e);return e;}
 setWorkload(employeeId,value=0){const e=this.employees.find(x=>x.id===employeeId&&x.active);if(!e)throw new Error("Mitarbeiter nicht gefunden");e.workload=Math.max(0,Math.min(100,Number(value||0)));this.recalculateSatisfaction(e);return e;}
 recalculateSatisfaction(employee){const job=worldContentRegistry.get("jobs",employee.jobId),base=Number(job?.baseWageMonthly||employee.wageMonthly||1),wageBonus=Math.max(-20,Math.min(20,(employee.wageMonthly/base-1)*50)),overtimePenalty=Math.min(28,employee.overtimeHours*1.5),workloadPenalty=Math.max(0,(employee.workload-70)*.4);employee.satisfaction=Math.max(0,Math.min(100,75+wageBonus-overtimePenalty-workloadPenalty));return employee.satisfaction;}
 resignationRisk(employeeId){const e=this.employees.find(x=>x.id===employeeId);if(!e)return 0;return Math.max(0,Math.min(.65,(55-Number(e.satisfaction||0))/100));}
 monthlyPayroll(){let gross=0,overtime=0;for(const e of this.employees.filter(x=>x.active)){const a=this.assignments.find(x=>x.employeeId===e.id),shift=worldContentRegistry.get("shifts",a?.shiftId)||{wageFactor:1};gross+=e.wageMonthly*Number(shift.wageFactor||1);overtime+=e.overtimeHours*(e.wageMonthly/173)*1.25;}const employerCosts=(gross+overtime)*.22;return {gross,overtime,employerCosts,trainingCosts:this.trainingCosts,total:gross+overtime+employerCosts+this.trainingCosts};}
}

export class MachineOperationsSystem{
 constructor(){this.machines=[];this.seq=1;}
 addMachine({type,label=null,maintenanceClass="standard",energyTypeId="electricity",energyPerHour=0,requiredSkill="machine",requiredWorkers=1}){const m={id:this.seq++,type,label:label||type,maintenanceClass,energyTypeId,energyPerHour:Number(energyPerHour||0),requiredSkill,requiredWorkers:Number(requiredWorkers||1),wear:0,hours:0,status:"idle",lastServiceHours:0,currentJob:null};this.machines.push(m);return m;}
 canRun(machine,workforce,{shiftId,hour=null,date=new Date()}={}){const staff=workforce.availableFor({shiftId,skill:machine.requiredSkill,machineId:machine.id,hour,date});return {ok:staff.length>=machine.requiredWorkers,required:machine.requiredWorkers,available:staff.length,staff};}
 run(machineId,hours,workforce,{shiftId,hour=null,date=new Date(),jobLabel=null}={}){const m=this.machines.find(x=>x.id===machineId);if(!m)throw new Error("Maschine nicht gefunden");if(m.status==="broken")throw new Error("Maschine ist defekt");const staffing=this.canRun(m,workforce,{shiftId,hour,date});if(!staffing.ok)throw new Error(`Zu wenig qualifiziertes Personal: ${staffing.available}/${staffing.required}`);const h=Math.max(0,Number(hours||0)),rule=maintenanceRule(m.maintenanceClass);m.status="running";m.currentJob=jobLabel||"Produktion";m.hours+=h;m.wear=Math.min(1,m.wear+h*Number(rule.wearPerHour||0));const energy=energyType(m.energyTypeId);const energyUnits=h*m.energyPerHour,energyCost=energyUnits*Number(energy?.pricePerUnit||0);const avgQualification=staffing.staff.reduce((s,e)=>s+Number(e.qualification||1),0)/staffing.staff.length;const satisfactionFactor=staffing.staff.reduce((s,e)=>s+Number(e.satisfaction||75),0)/(staffing.staff.length*75);const performanceFactor=Math.max(.7,Math.min(1.3,(.9+avgQualification*.1)*Math.max(.85,Math.min(1.08,satisfactionFactor))));const qualityFactor=Math.max(.88,Math.min(1.12,.95+avgQualification*.05));for(const e of staffing.staff){e.workload=Math.min(100,Number(e.workload||0)+h*5);workforce.recalculateSatisfaction(e);}if(m.wear>=Number(rule.failureAtWear||1))m.status="broken";else m.status="idle";m.currentJob=null;return {hours:h,energyUnits,energyCost,wear:m.wear,status:m.status,performanceFactor,qualityFactor,serviceDue:m.wear>=Number(rule.serviceAtWear||.5)};}
 service(machineId){const m=this.machines.find(x=>x.id===machineId);if(!m)throw new Error("Maschine nicht gefunden");const rule=maintenanceRule(m.maintenanceClass);m.status="maintenance";m.wear=Math.max(0,m.wear*.35);m.lastServiceHours=m.hours;m.status="idle";return {cost:Number(rule.serviceCost||0),wear:m.wear};}
 repair(machineId){const m=this.machines.find(x=>x.id===machineId);if(!m)throw new Error("Maschine nicht gefunden");const rule=maintenanceRule(m.maintenanceClass);m.status="repair";m.wear=.25;m.status="idle";m.lastServiceHours=m.hours;return {cost:Number(rule.repairCost||0),wear:m.wear,status:m.status};}
}

export function fixedOperatingCosts({rent=0,insurance=0,administration=0,baseEnergy=0,other=0}={}){const total=[rent,insurance,administration,baseEnergy,other].reduce((s,v)=>s+Number(v||0),0);return {rent:Number(rent||0),insurance:Number(insurance||0),administration:Number(administration||0),baseEnergy:Number(baseEnergy||0),other:Number(other||0),total};}
export function calculateProductEconomics({quantity=1,revenue=0,materials=0,packaging=0,energy=0,labour=0,machine=0,transport=0,fixedAllocated=0}={}){const q=Math.max(1,Number(quantity||1)),costTotal=[materials,packaging,energy,labour,machine,transport,fixedAllocated].reduce((s,v)=>s+Number(v||0),0),revenueTotal=Number(revenue||0),profit=revenueTotal-costTotal;return {quantity:q,revenue:revenueTotal,costTotal,unitCost:costTotal/q,unitRevenue:revenueTotal/q,contribution:profit,contributionPerUnit:profit/q,marginPct:revenueTotal?profit/revenueTotal*100:0,breakdown:{materials,packaging,energy,labour,machine,transport,fixedAllocated}};}

export function runWorkforceOperationsTest(){const wf=new WorkforceSystem(),operator=wf.hire({jobId:"machine_operator",industry:"brewery",qualification:1.2});const machines=new MachineOperationsSystem(),m=machines.addMachine({type:"filling_line",energyPerHour:18,requiredSkill:"machine",requiredWorkers:1});wf.assign(operator.id,{shiftId:"early",machineId:m.id});wf.setOvertime(operator.id,2);const training=wf.startTraining(operator.id,"machine_basic",{startDate:new Date(2026,7,10)}),schoolDate=new Date(`${training.schoolDates[0]}T08:00:00`);if(wf.availableFor({shiftId:"early",skill:"machine",machineId:m.id,hour:8,date:schoolDate}).length!==0)throw new Error("Mitarbeiter darf am Schulungstag nicht im Betrieb verfuegbar sein");for(const d of training.schoolDates)wf.processTrainingDate(new Date(`${d}T12:00:00`));const run=machines.run(m.id,8,wf,{shiftId:"early",hour:8,date:addDays(schoolDate,1)}),payroll=wf.monthlyPayroll(),econ=calculateProductEconomics({quantity:1000,revenue:1500,materials:500,packaging:180,energy:run.energyCost,labour:100,machine:50,transport:40});if(run.energyUnits<=0||payroll.total<=0||payroll.trainingCosts<=0||training.status!=="completed"||!Number.isFinite(econ.unitCost)||!Number.isFinite(operator.satisfaction))throw new Error("Personal-/Betriebskostentest fehlgeschlagen");console.log("✅ PERSONAL-/SCHICHT-/SCHULUNGS-/MASCHINEN-/KOSTENTEST ERFOLGREICH",{run,payroll,econ,employee:operator,training});return true;}
