// WorldProject - Personal, Schichten, Maschinenverschleiss, Energie und Betriebskosten
import { worldContentRegistry } from "./ContentRegistry.js";

export function jobsForIndustry(industry){return worldContentRegistry.list("jobs").filter(j=>(j.industries||[]).includes("*")||(j.industries||[]).includes(industry));}
export function shifts(){return worldContentRegistry.list("shifts");}
export function energyType(id){return worldContentRegistry.get("energyTypes",id);}
export function maintenanceRule(id="standard"){return worldContentRegistry.get("maintenanceRules",id)||worldContentRegistry.get("maintenanceRules","standard");}

export class WorkforceSystem{
 constructor(){this.employees=[];this.seq=1;this.assignments=[];}
 hire({jobId,name=null,qualification=1,wageMonthly=null,industry="*"}){const job=worldContentRegistry.get("jobs",jobId);if(!job)throw new Error("Unbekannter Beruf");if(!(job.industries||[]).includes("*")&&!(job.industries||[]).includes(industry))throw new Error("Beruf passt nicht zur Branche");const e={id:this.seq++,name:name||`${job.label} ${this.seq}`,jobId,qualification:Math.max(.5,Math.min(2,Number(qualification||1))),wageMonthly:Number(wageMonthly||job.baseWageMonthly||0),industry,active:true};this.employees.push(e);return e;}
 assign(employeeId,{shiftId,machineId=null,area=null}={}){const e=this.employees.find(x=>x.id===employeeId&&x.active);if(!e)throw new Error("Mitarbeiter nicht gefunden");if(!worldContentRegistry.get("shifts",shiftId))throw new Error("Unbekannte Schicht");const a={employeeId,shiftId,machineId,area};this.assignments=this.assignments.filter(x=>x.employeeId!==employeeId);this.assignments.push(a);return a;}
 availableFor({shiftId,skill,machineId=null}={}){return this.assignments.map(a=>({a,e:this.employees.find(x=>x.id===a.employeeId)})).filter(({a,e})=>e?.active&&a.shiftId===shiftId&&(!machineId||a.machineId===machineId)&&(!skill||(worldContentRegistry.get("jobs",e.jobId)?.skills||[]).includes(skill))).map(x=>x.e);}
 monthlyPayroll(){let gross=0;for(const e of this.employees.filter(x=>x.active)){const a=this.assignments.find(x=>x.employeeId===e.id),shift=worldContentRegistry.get("shifts",a?.shiftId)||{wageFactor:1};gross+=e.wageMonthly*Number(shift.wageFactor||1);}const employerCosts=gross*.22;return {gross,employerCosts,total:gross+employerCosts};}
}

export class MachineOperationsSystem{
 constructor(){this.machines=[];this.seq=1;}
 addMachine({type,label=null,maintenanceClass="standard",energyTypeId="electricity",energyPerHour=0,requiredSkill="machine",requiredWorkers=1}){const m={id:this.seq++,type,label:label||type,maintenanceClass,energyTypeId,energyPerHour:Number(energyPerHour||0),requiredSkill,requiredWorkers:Number(requiredWorkers||1),wear:0,hours:0,status:"idle",lastServiceHours:0};this.machines.push(m);return m;}
 canRun(machine,workforce,{shiftId}={}){const staff=workforce.availableFor({shiftId,skill:machine.requiredSkill,machineId:machine.id});return {ok:staff.length>=machine.requiredWorkers,required:machine.requiredWorkers,available:staff.length,staff};}
 run(machineId,hours,workforce,{shiftId}={}){const m=this.machines.find(x=>x.id===machineId);if(!m)throw new Error("Maschine nicht gefunden");if(m.status==="broken")throw new Error("Maschine ist defekt");const staffing=this.canRun(m,workforce,{shiftId});if(!staffing.ok)throw new Error(`Zu wenig qualifiziertes Personal: ${staffing.available}/${staffing.required}`);const h=Math.max(0,Number(hours||0)),rule=maintenanceRule(m.maintenanceClass);m.hours+=h;m.wear=Math.min(1,m.wear+h*Number(rule.wearPerHour||0));const energy=energyType(m.energyTypeId);const energyUnits=h*m.energyPerHour,energyCost=energyUnits*Number(energy?.pricePerUnit||0);const avgQualification=staffing.staff.reduce((s,e)=>s+Number(e.qualification||1),0)/staffing.staff.length;const performanceFactor=Math.max(.75,Math.min(1.25,.9+avgQualification*.1));const qualityFactor=Math.max(.9,Math.min(1.1,.95+avgQualification*.05));if(m.wear>=Number(rule.failureAtWear||1))m.status="broken";else m.status="idle";return {hours:h,energyUnits,energyCost,wear:m.wear,status:m.status,performanceFactor,qualityFactor,serviceDue:m.wear>=Number(rule.serviceAtWear||.5)};}
 service(machineId){const m=this.machines.find(x=>x.id===machineId);if(!m)throw new Error("Maschine nicht gefunden");const rule=maintenanceRule(m.maintenanceClass);m.wear=Math.max(0,m.wear*.35);m.lastServiceHours=m.hours;if(m.status!=="broken")m.status="idle";return {cost:Number(rule.serviceCost||0),wear:m.wear};}
 repair(machineId){const m=this.machines.find(x=>x.id===machineId);if(!m)throw new Error("Maschine nicht gefunden");const rule=maintenanceRule(m.maintenanceClass);m.wear=.25;m.status="idle";m.lastServiceHours=m.hours;return {cost:Number(rule.repairCost||0),wear:m.wear,status:m.status};}
}

export function fixedOperatingCosts({rent=0,insurance=0,administration=0,baseEnergy=0,other=0}={}){const total=[rent,insurance,administration,baseEnergy,other].reduce((s,v)=>s+Number(v||0),0);return {rent:Number(rent||0),insurance:Number(insurance||0),administration:Number(administration||0),baseEnergy:Number(baseEnergy||0),other:Number(other||0),total};}

export function calculateProductEconomics({quantity=1,revenue=0,materials=0,packaging=0,energy=0,labour=0,machine=0,transport=0,fixedAllocated=0}={}){const q=Math.max(1,Number(quantity||1)),costTotal=[materials,packaging,energy,labour,machine,transport,fixedAllocated].reduce((s,v)=>s+Number(v||0),0),revenueTotal=Number(revenue||0),profit=revenueTotal-costTotal;return {quantity:q,revenue:revenueTotal,costTotal,unitCost:costTotal/q,unitRevenue:revenueTotal/q,contribution:profit,contributionPerUnit:profit/q,marginPct:revenueTotal?profit/revenueTotal*100:0,breakdown:{materials,packaging,energy,labour,machine,transport,fixedAllocated}};}

export function runWorkforceOperationsTest(){
 const wf=new WorkforceSystem(),operator=wf.hire({jobId:"machine_operator",industry:"brewery",qualification:1.2});const machines=new MachineOperationsSystem(),m=machines.addMachine({type:"filling_line",energyPerHour:18,requiredSkill:"machine",requiredWorkers:1});wf.assign(operator.id,{shiftId:"early",machineId:m.id});const run=machines.run(m.id,8,wf,{shiftId:"early"}),payroll=wf.monthlyPayroll(),econ=calculateProductEconomics({quantity:1000,revenue:1500,materials:500,packaging:180,energy:run.energyCost,labour:100,machine:50,transport:40});if(run.energyUnits<=0||payroll.total<=0||!Number.isFinite(econ.unitCost))throw new Error("Personal-/Betriebskostentest fehlgeschlagen");console.log("✅ PERSONAL-/SCHICHT-/MASCHINEN-/KOSTENTEST ERFOLGREICH",{run,payroll,econ});return true;
}
