// WorldProject - sichtbare Personal-, Schicht- und Maschinensteuerung
import { jobsForIndustry, shifts, WorkforceSystem, MachineOperationsSystem, calculateProductEconomics } from "./WorkforceOperationsSystem.js";
import { availableCandidates, missingRequiredRoles } from "./IndustryRecruitmentAvailability.js";

export class WorkforceOperationsDialog{
 constructor({parent=document.body}={}){this.parent=parent;this.overlay=null;this.workforce=new WorkforceSystem();this.machines=new MachineOperationsSystem();this.lastEconomics=null;this.loadedCompanyId=null;}
 el(tag,text=null){const e=document.createElement(tag);if(text!==null)e.textContent=text;return e;}
 button(text,fn){const b=this.el("button",text);Object.assign(b.style,{padding:"8px 10px",margin:"4px",border:0,borderRadius:"7px",fontWeight:"700",cursor:"pointer"});b.onclick=fn;return b;}
 input(value=""){const i=this.el("input");i.value=value;Object.assign(i.style,{padding:"7px",margin:"4px",border:"1px solid #bbb",borderRadius:"6px"});return i;}
 select(options=[]){const s=this.el("select");Object.assign(s.style,{padding:"7px",margin:"4px"});for(const o of options){const el=this.el("option",o.label||o);el.value=o.id||o;s.append(el);}return s;}
 money(v){return Number(v||0).toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
 company(){return window.worldPlayerCompany||null;}
 branchKey(){const c=this.company(),raw=c?.branchKey||c?.type||c?.company_type||window.worldActiveServerCompany?.company_type||c?.industry||window.worldActiveServerCompany?.industry||"brewery";const map={Brauerei:"brewery",Getränke:"brewery",Getränkehersteller:"beverage",Mineralbrunnen:"beverage",Schreinerei:"carpentry",Tischlerei:"carpentry",Landwirtschaftsbetrieb:"farm",Landwirtschaft:"farm"};return map[raw]||raw;}
 loadState(){const c=this.company();if(!c)return;const id=c.serverCompanyId||c.id||"local";if(this.loadedCompanyId===id)return;this.loadedCompanyId=id;const s=c.workforceState||{};this.workforce=new WorkforceSystem();this.machines=new MachineOperationsSystem();if(Array.isArray(s.employees))this.workforce.employees=structuredClone(s.employees);if(Array.isArray(s.assignments))this.workforce.assignments=structuredClone(s.assignments);if(Array.isArray(s.trainings))this.workforce.trainings=structuredClone(s.trainings);this.workforce.seq=Number(s.seq||((this.workforce.employees.reduce((m,e)=>Math.max(m,Number(e.id)||0),0))+1));this.workforce.trainingSeq=Number(s.trainingSeq||((this.workforce.trainings.reduce((m,t)=>Math.max(m,Number(t.id)||0),0))+1));this.workforce.trainingCosts=Number(s.trainingCosts||0);if(Array.isArray(s.machines))this.machines.machines=structuredClone(s.machines);this.machines.seq=Number(s.machineSeq||((this.machines.machines.reduce((m,x)=>Math.max(m,Number(x.id)||0),0))+1));}
 persist(){const c=this.company();if(!c)return;c.workforceState={employees:structuredClone(this.workforce.employees),assignments:structuredClone(this.workforce.assignments),trainings:structuredClone(this.workforce.trainings),seq:this.workforce.seq,trainingSeq:this.workforce.trainingSeq,trainingCosts:this.workforce.trainingCosts,machines:structuredClone(this.machines.machines),machineSeq:this.machines.seq};window.dispatchEvent(new CustomEvent("world:state-dirty"));}
 ensureStarterState(industry){const defaults={brewery:[{type:"brewhouse",label:"Sudhaus",skill:"brewhouse",energy:24},{type:"filling_line",label:"Abfüllanlage",skill:"machine",energy:18}],beverage:[{type:"mixing_tank",label:"Mischtank",skill:"machine",energy:16},{type:"filling_line",label:"Abfüllanlage",skill:"machine",energy:18}],carpentry:[{type:"woodshop",label:"Werkstattlinie",skill:"woodshop",energy:12}],farm:[{type:"field_line",label:"Ackerbau-Maschinenkette",skill:"field_line",energy:20,energyTypeId:"diesel"}]};const wanted=defaults[industry]||[{type:"production_line",label:"Produktionslinie",skill:"machine",energy:10}];let changed=false;for(const d of wanted){if(this.machines.machines.some(m=>m?.type===d.type&&m.status!=="sold"))continue;this.machines.addMachine({type:d.type,label:d.label,requiredSkill:d.skill,energyPerHour:d.energy,energyTypeId:d.energyTypeId||"electricity"});changed=true;}if(changed)this.persist();}
 async open(){if(this.overlay)return;this.loadState();const industry=this.branchKey();this.ensureStarterState(industry);const ov=this.el("div");Object.assign(ov.style,{position:"fixed",inset:0,zIndex:23000,background:"rgba(0,0,0,.75)",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px"});const panel=this.el("div");Object.assign(panel.style,{width:"min(1050px,97vw)",maxHeight:"94vh",overflow:"auto",background:"#fff",color:"#111",borderRadius:"14px",padding:"20px",fontFamily:"Arial,sans-serif"});ov.append(panel);this.parent.append(ov);this.overlay=ov;this.render(panel,industry);}
 close(){this.overlay?.remove();this.overlay=null;}
 render(panel,industry){panel.innerHTML="";const head=this.el("div");Object.assign(head.style,{display:"flex",justifyContent:"space-between",alignItems:"center"});head.append(this.el("h2","👷 Personal & Maschinen"),this.button("✕",()=>this.close()));panel.append(head,this.el("div",`Branche: ${industry} · erweiterbares Personal-/Schichtsystem`));
 const hire=this.el("section");hire.append(this.el("h3","Mitarbeiter einstellen"));const jobs=jobsForIndustry(industry),company=this.company(),missing=missingRequiredRoles(company),candidates=availableCandidates(company,{count:8});if(missing.length){const warning=this.el("div",`Für den Betrieb fehlen Pflichtfachkräfte: ${candidates.filter(c=>c.required).map(c=>c.label).join(", ")||missing.join(", ")}. Diese Berufe werden im Personalmarkt bevorzugt angeboten.`);Object.assign(warning.style,{padding:"10px",margin:"8px 0",border:"1px solid #d69e00",background:"#fff7d6",borderRadius:"8px"});hire.append(warning);}const jobSel=this.select(jobs.map(j=>({id:j.id,label:`${j.label} – ${this.money(j.baseWageMonthly)}/Monat`}))),name=this.input("Name"),qual=this.input("1.0");const preferred=candidates.find(c=>c.required&&jobs.some(j=>j.id===c.role));if(preferred)jobSel.value=preferred.role;hire.append(jobSel,name,qual,this.button("Einstellen",()=>{try{this.workforce.hire({jobId:jobSel.value,name:name.value||null,qualification:Number(qual.value||1),industry});this.persist();this.render(panel,industry);}catch(e){alert(e.message);}}));panel.append(hire);
 const staff=this.el("section");staff.append(this.el("h3","Mitarbeiter & Schichtplan"));for(const e of this.workforce.employees.filter(x=>x.active)){const job=jobsForIndustry(industry).find(j=>j.id===e.jobId)||{label:e.jobId};const row=this.el("div");Object.assign(row.style,{border:"1px solid #ddd",padding:"10px",margin:"6px 0",borderRadius:"8px"});const shiftSel=this.select(shifts()),machineSel=this.select([{id:"",label:"Keiner Maschine zugewiesen"},...this.machines.machines.map(m=>({id:String(m.id),label:m.label}))]),ot=this.input(String(e.overtimeHours||0));const current=this.workforce.assignments.find(a=>a.employeeId===e.id);if(current){shiftSel.value=current.shiftId;machineSel.value=current.machineId?String(current.machineId):"";}row.append(this.el("strong",`${e.name} · ${job.label} · Qualifikation ${e.qualification.toFixed(2)}`),this.el("div",`Zufriedenheit ${Math.round(e.satisfaction)} % · Kündigungsrisiko ${(this.workforce.resignationRisk(e.id)*100).toFixed(1)} %`),shiftSel,machineSel,this.el("span","Überstunden:"),ot,this.button("Zuweisen",()=>{try{this.workforce.assign(e.id,{shiftId:shiftSel.value,machineId:machineSel.value?Number(machineSel.value):null});this.workforce.setOvertime(e.id,Number(ot.value||0));this.persist();this.render(panel,industry);}catch(err){alert(err.message);}}),this.button("Entlassen",()=>{this.workforce.fire(e.id);this.persist();this.render(panel,industry);}));staff.append(row);}const pay=this.workforce.monthlyPayroll();staff.append(this.el("div",`Monatliche Personalkosten: ${this.money(pay.total)} (Brutto ${this.money(pay.gross)}, Überstunden ${this.money(pay.overtime)}, AG-Kosten ${this.money(pay.employerCosts)})`));panel.append(staff);
 const machines=this.el("section");machines.append(this.el("h3","Maschinenübersicht"));for(const m of this.machines.machines){const ruleLine=`${m.label} · Status ${m.status} · Laufzeit ${m.hours.toFixed(1)} h · Verschleiß ${(m.wear*100).toFixed(1)} %`;const row=this.el("div");Object.assign(row.style,{border:"1px solid #ddd",padding:"10px",margin:"6px 0",borderRadius:"8px"});const sh=this.select(shifts()),hours=this.input("1");row.append(this.el("strong",ruleLine),this.el("div",`Energie ${m.energyPerHour}/h · Bedarf ${m.requiredWorkers} Mitarbeiter · Skill ${m.requiredSkill}`),sh,hours,this.button("Probelauf",()=>{try{const r=this.machines.run(m.id,Number(hours.value||1),this.workforce,{shiftId:sh.value,hour:worldHourForShift(sh.value),jobLabel:"Testproduktion"});this.persist();alert(`Lauf erfolgreich. Energie: ${r.energyUnits.toFixed(1)}, Kosten: ${this.money(r.energyCost)}, Verschleiß ${(r.wear*100).toFixed(1)} %`);this.render(panel,industry);}catch(e){alert(e.message);}}),this.button("Warten",()=>{const r=this.machines.service(m.id);this.persist();alert(`Wartung abgeschlossen: ${this.money(r.cost)}`);this.render(panel,industry);}),this.button("Reparieren",()=>{const r=this.machines.repair(m.id);this.persist();alert(`Reparatur abgeschlossen: ${this.money(r.cost)}`);this.render(panel,industry);}));machines.append(row);}panel.append(machines);
 const econ=this.el("section");econ.append(this.el("h3","Produktkosten / Deckungsbeitrag"));const qty=this.input("1000"),revenue=this.input("1500"),materials=this.input("500"),packaging=this.input("180"),energy=this.input("80"),labour=this.input("120"),machine=this.input("60"),transport=this.input("40");econ.append(this.el("div","Menge / Umsatz / Rohstoffe / Verpackung / Energie / Personal / Maschine / Transport"),qty,revenue,materials,packaging,energy,labour,machine,transport,this.button("Berechnen",()=>{this.lastEconomics=calculateProductEconomics({quantity:Number(qty.value),revenue:Number(revenue.value),materials:Number(materials.value),packaging:Number(packaging.value),energy:Number(energy.value),labour:Number(labour.value),machine:Number(machine.value),transport:Number(transport.value)});this.render(panel,industry);}));if(this.lastEconomics)econ.append(this.el("div",`Stückkosten ${this.money(this.lastEconomics.unitCost)} · Erlös/Stk ${this.money(this.lastEconomics.unitRevenue)} · Deckungsbeitrag ${this.money(this.lastEconomics.contribution)} · Marge ${this.lastEconomics.marginPct.toFixed(1)} %`));panel.append(econ);
 }
}
function worldHourForShift(id){const map={early:8,late:16,night:23};return map[id]??12;}
