// WorldProject – Organisation, Besetzung, Fehlzeiten, Zuschläge und Personalprognose für alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureWorkforceOrganization(c={}){c.workforceOrganization??={positions:[],absences:[],overtime:[],bonuses:[],forecasts:[],events:[]};c.employees??=[];return c.workforceOrganization;}
export function definePosition(c,{role,department="operations",target=1,minimum=1,baseMonthly=3000,employerCostRate=.22,certifications=[]}={}){const s=ensureWorkforceOrganization(c),existing=s.positions.find(x=>x.role===role&&x.department===department),row={role,department,target:Math.max(0,n(target)),minimum:Math.max(0,n(minimum)),baseMonthly:Math.max(0,n(baseMonthly)),employerCostRate:Math.max(0,n(employerCostRate,.22)),certifications:[...certifications]};if(existing)Object.assign(existing,row);else s.positions.push(row);return existing||row;}
export function staffingStatus(c){const s=ensureWorkforceOrganization(c),active=c.employees.filter(e=>!["terminated","notice"].includes(e.status));return s.positions.map(p=>{const assigned=active.filter(e=>(e.role||e.jobId)===p.role||e.department===p.department&&e.primaryRole===p.role).length;return{...p,assigned,shortage:Math.max(0,p.target-assigned),critical:assigned<p.minimum,overstaffed:assigned>p.target};});}
export function departmentPayroll(c){const s=ensureWorkforceOrganization(c),rows={};for(const e of c.employees.filter(x=>x.status!=="terminated")){const dep=e.department||"operations",base=Math.max(0,n(e.wageMonthly??e.baseMonthly)),employerRate=n(e.employerCostRate,.22),allowances=n(e.allowancesMonthly),cost=base*(1+employerRate)+allowances;(rows[dep]??={department:dep,employees:0,gross:0,totalCost:0}).employees++;rows[dep].gross+=base;rows[dep].totalCost+=cost;}return Object.values(rows);}
export function createAbsence(c,employeeId,{kind="vacation",startsAt=Date.now(),endsAt=Date.now()+86400000,paid=true}={}){const s=ensureWorkforceOrganization(c),e=c.employees.find(x=>x.id===employeeId);if(!e)throw new Error("Mitarbeiter fehlt");if(endsAt<=startsAt)throw new Error("Ungültiger Zeitraum");const conflict=s.absences.some(a=>a.employeeId===employeeId&&a.status!=="cancelled"&&startsAt<a.endsAt&&endsAt>a.startsAt);if(conflict)throw new Error("Abwesenheit überschneidet sich");const row={id:`absence-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,employeeId,kind,startsAt,endsAt,paid,status:"planned"};s.absences.push(row);return row;}
export function employeeAvailable(c,employeeId,at=Date.now()){const s=ensureWorkforceOrganization(c),e=c.employees.find(x=>x.id===employeeId);if(!e||["terminated","notice","sick","training"].includes(e.status))return false;return !s.absences.some(a=>a.employeeId===employeeId&&a.status!=="cancelled"&&at>=a.startsAt&&at<a.endsAt);}
export function accrueOvertime(c,employeeId,hours,{kind="overtime",rate=1.25,now=Date.now()}={}){const s=ensureWorkforceOrganization(c),e=c.employees.find(x=>x.id===employeeId);if(!e)throw new Error("Mitarbeiter fehlt");const h=Math.max(0,n(hours)),hourly=n(e.wageMonthly)/173.33,multiplier=kind==="night"?1.25:kind==="sunday"?1.5:kind==="holiday"?2:Math.max(1,n(rate,1.25)),cost=h*hourly*multiplier,row={id:`ot-${now}-${Math.random().toString(36).slice(2,6)}`,employeeId,hours:h,kind,multiplier,cost,at:now};s.overtime.push(row);e.overtimeHours=n(e.overtimeHours)+h;return row;}
export function payPerformanceBonus(c,employeeId,amount,{reason="performance",now=Date.now()}={}){const s=ensureWorkforceOrganization(c),e=c.employees.find(x=>x.id===employeeId);if(!e)throw new Error("Mitarbeiter fehlt");const q=Math.max(0,n(amount));if(n(c.money)<q)throw new Error("Nicht genug Liquidität");c.money-=q;const row={id:`bonus-${now}-${Math.random().toString(36).slice(2,6)}`,employeeId,amount:q,reason,at:now};s.bonuses.push(row);e.morale=clamp(n(e.morale,75)+Math.min(8,q/100),0,100);return row;}
export function turnoverRisk(employee){const morale=clamp(n(employee.morale,75),0,100),fatigue=clamp(n(employee.fatigue),0,100),skill=n(employee.skillLevel,1),payIndex=n(employee.payIndex,1);return clamp((100-morale)/160+fatigue/250+(skill>=4&&payIndex<.95?.18:0),.01,.85);}
export function forecastWorkforce(c,{orderHours=0,growthRate=0,monthlyHoursPerEmployee=160}={}){const s=ensureWorkforceOrganization(c),needed=Math.ceil(Math.max(0,n(orderHours))*(1+Math.max(-.5,n(growthRate)))/Math.max(1,n(monthlyHoursPerEmployee,160))),active=c.employees.filter(x=>!["terminated","notice"].includes(x.status)).length,row={at:Date.now(),needed,active,gap:needed-active,growthRate:n(growthRate),orderHours:n(orderHours)};s.forecasts.push(row);return row;}
export function prioritizeVacancies(c){return staffingStatus(c).filter(x=>x.shortage>0).sort((a,b)=>(Number(b.critical)-Number(a.critical))||b.shortage-a.shortage).map((x,i)=>({...x,priority:i+1}));}
export function workforceOrganizationKpis(c){const s=ensureWorkforceOrganization(c),status=staffingStatus(c),active=c.employees.filter(x=>x.status!=="terminated");return{employees:active.length,positions:s.positions.length,shortages:status.reduce((a,x)=>a+x.shortage,0),criticalPositions:status.filter(x=>x.critical).length,overstaffedPositions:status.filter(x=>x.overstaffed).length,payroll:departmentPayroll(c).reduce((a,x)=>a+x.totalCost,0),plannedAbsences:s.absences.filter(x=>x.status==="planned").length,overtimeHours:s.overtime.reduce((a,x)=>a+n(x.hours),0),overtimeCost:s.overtime.reduce((a,x)=>a+n(x.cost),0),averageTurnoverRisk:active.length?active.reduce((a,x)=>a+turnoverRisk(x),0)/active.length:0};}
