// Qualifikations-/Fuehrungsmatrix fuer alle Gewerbe.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureCapabilityMatrix(c={}){c.workforceCapability??={roles:{},reviews:[],succession:[],trainingNeeds:[]};c.employees??=[];return c.workforceCapability;}
export function defineRoleCapability(c,role,{skills=[],minLevel=1,leadership=false,requiredCerts=[]}={}){const m=ensureCapabilityMatrix(c);m.roles[role]={skills:[...skills],minLevel:n(minLevel,1),leadership:!!leadership,requiredCerts:[...requiredCerts]};return m.roles[role];}
export function employeeCapability(c,e,role){const spec=ensureCapabilityMatrix(c).roles[role]||{skills:[],minLevel:1,requiredCerts:[]},skills=e.skills||[],certs=e.certificates||[],skillMatch=spec.skills.length?spec.skills.filter(s=>skills.includes(s)).length/spec.skills.length:1,certMatch=spec.requiredCerts.every(x=>certs.includes(x)),level=n(e.skillLevel,1),available=!['sick','vacation','training','notice'].includes(e.status);return{employeeId:e.id,role,skillMatch,certMatch,level,available,qualified:available&&certMatch&&skillMatch>=.75&&level>=spec.minLevel,score:clamp(skillMatch*.5+Math.min(1,level/spec.minLevel)*.3+(certMatch?.2:0),0,1)};}
export function bestEmployeesForRole(c,role,{limit=5}={}){return(c.employees||[]).map(e=>({...employeeCapability(c,e,role),employee:e})).sort((a,b)=>b.score-a.score).slice(0,limit);}
export function reviewEmployee(c,employeeId,{performance=.75,potential=.75,notes=''}={}){const m=ensureCapabilityMatrix(c),e=c.employees.find(x=>x.id===employeeId);if(!e)throw new Error('Mitarbeiter fehlt');const row={id:`review-${Date.now()}`,employeeId,performance:clamp(n(performance,.75),0,1),potential:clamp(n(potential,.75),0,1),notes,at:Date.now()};m.reviews.push(row);e.lastReview=row;return row;}
export function identifyTrainingNeeds(c){const m=ensureCapabilityMatrix(c),needs=[];for(const[role]of Object.entries(m.roles)){const candidates=bestEmployeesForRole(c,role,{limit:3});if(!candidates.some(x=>x.qualified))needs.push({role,reason:'no_qualified_employee',priority:100});else if(candidates[0].score<.9)needs.push({role,reason:'skill_gap',priority:Math.round((1-candidates[0].score)*100)});}m.trainingNeeds=needs;return needs;}
export function planSuccession(c,leadRole){const m=ensureCapabilityMatrix(c),candidates=bestEmployeesForRole(c,leadRole,{limit:3}).map(x=>({employeeId:x.employeeId,score:x.score,ready:x.score>=.9}));const row={role:leadRole,candidates,at:Date.now()};m.succession=m.succession.filter(x=>x.role!==leadRole);m.succession.push(row);return row;}
export function workforceCapabilityKpis(c){const m=ensureCapabilityMatrix(c),roles=Object.keys(m.roles),needs=identifyTrainingNeeds(c);return{roles:roles.length,trainingNeeds:needs.length,leadershipRoles:roles.filter(r=>m.roles[r].leadership).length,reviews:m.reviews.length,successionPlans:m.succession.length};}
