// WorldProject - zentrale Waehrungsschicht. Interne Wirtschaftswerte bleiben in EUR.
export const BASE_CURRENCY="EUR";
export const CurrencyMeta={EUR:{digits:2},USD:{digits:2},GBP:{digits:2},CHF:{digits:2},PLN:{digits:2},CZK:{digits:2},DKK:{digits:2},SEK:{digits:2},NOK:{digits:2},CNY:{digits:2},JPY:{digits:0},KRW:{digits:0},INR:{digits:2},AUD:{digits:2},CAD:{digits:2},BRL:{digits:2},MXN:{digits:2},ZAR:{digits:2},TRY:{digits:2},UAH:{digits:2},NZD:{digits:2},SGD:{digits:2},HKD:{digits:2},TWD:{digits:0},THB:{digits:2},IDR:{digits:0},MYR:{digits:2},PHP:{digits:2},VND:{digits:0},AED:{digits:2},SAR:{digits:2},ILS:{digits:2},EGP:{digits:2},MAD:{digits:2},NGN:{digits:2},KES:{digits:2},ARS:{digits:2},CLP:{digits:0},COP:{digits:2},PEN:{digits:2}};
export const CountryCurrency={DE:"EUR",AT:"EUR",BE:"EUR",ES:"EUR",FI:"EUR",FR:"EUR",GR:"EUR",HR:"EUR",IE:"EUR",IT:"EUR",NL:"EUR",PT:"EUR",SK:"EUR",SI:"EUR",LU:"EUR",MT:"EUR",CY:"EUR",EE:"EUR",LV:"EUR",LT:"EUR",US:"USD",GB:"GBP",CH:"CHF",PL:"PLN",CZ:"CZK",DK:"DKK",SE:"SEK",NO:"NOK",CN:"CNY",JP:"JPY",KR:"KRW",IN:"INR",AU:"AUD",CA:"CAD",BR:"BRL",MX:"MXN",ZA:"ZAR",TR:"TRY",UA:"UAH",NZ:"NZD",SG:"SGD",HK:"HKD",TW:"TWD",TH:"THB",ID:"IDR",MY:"MYR",PH:"PHP",VN:"VND",AE:"AED",SA:"SAR",IL:"ILS",EG:"EGP",MA:"MAD",NG:"NGN",KE:"KES",AR:"ARS",CL:"CLP",CO:"COP",PE:"PEN"};
export const DefaultExchangeRates={EUR:1,USD:1.17,GBP:.87,CHF:.93,PLN:4.26,CZK:24.5,DKK:7.46,SEK:11.1,NOK:11.8,CNY:8.39,JPY:173,KRW:1620,INR:102,AUD:1.8,CAD:1.61,BRL:6.35,MXN:21.8,ZAR:20.8,TRY:47.8,UAH:48.3,NZD:1.97,SGD:1.50,HKD:9.15,TWD:35.4,THB:37.7,IDR:19000,MYR:5.02,PHP:67.1,VND:30700,AED:4.30,SAR:4.39,ILS:3.78,EGP:56.5,MAD:10.6,NGN:1850,KES:151,ARS:1510,CLP:1120,COP:4700,PEN:4.22};
const valid=c=>CurrencyMeta[String(c||"").toUpperCase()]?String(c).toUpperCase():BASE_CURRENCY;
export function countryFromLocale(locale=""){const p=String(locale).replace("_","-").split("-");const r=p.find((x,i)=>i>0&&/^[A-Za-z]{2}$/.test(x));return r?r.toUpperCase():null;}
export function currencyForCountry(country="DE"){return CountryCurrency[String(country).toUpperCase()]||BASE_CURRENCY;}
export function detectPlayerCountry(nav=globalThis.navigator){for(const l of [...(nav?.languages||[]),nav?.language].filter(Boolean)){const c=countryFromLocale(l);if(c)return c;}return"DE";}
export class WorldCurrencySystem{
 constructor({country=null,currency=null,locale="de-DE",rates=null}={}){this.baseCurrency=BASE_CURRENCY;this.country=String(country||detectPlayerCountry()).toUpperCase();this.currency=valid(currency||currencyForCountry(this.country));this.locale=locale;this.rates={...DefaultExchangeRates,...(rates||{}),EUR:1};this.ratesUpdatedAt=0;this.rateSource="fallback";}
 setLocale(locale){this.locale=String(locale||"en");return this.locale;}
 setCountry(country,{keepCurrency=false}={}){this.country=String(country||"DE").toUpperCase();if(!keepCurrency)this.currency=currencyForCountry(this.country);this.savePreference();return this.country;}
 setCurrency(currency){this.currency=valid(currency);this.savePreference();return this.currency;}
 updateRates(rates={},updatedAt=Date.now(),source="server"){for(const[k,v]of Object.entries(rates)){const c=valid(k),n=Number(v);if(c===String(k).toUpperCase()&&Number.isFinite(n)&&n>0)this.rates[c]=n;}this.rates.EUR=1;this.ratesUpdatedAt=Number(updatedAt)||Date.now();this.rateSource=String(source||"server");return this.rates;}
 convert(value,{from=BASE_CURRENCY,to=this.currency}={}){const n=Number(value||0),f=valid(from),t=valid(to);if(!Number.isFinite(n))return 0;return n/Number(this.rates[f]||1)*Number(this.rates[t]||1);}
 toBase(value,currency=this.currency){return this.convert(value,{from:currency,to:BASE_CURRENCY});}
 format(value,{from=BASE_CURRENCY,currency=this.currency,locale=this.locale,showCode=false}={}){const c=valid(currency),digits=CurrencyMeta[c].digits,n=this.convert(value,{from,to:c});return new Intl.NumberFormat(locale||"en",{style:"currency",currency:c,currencyDisplay:showCode?"code":"symbol",minimumFractionDigits:digits,maximumFractionDigits:digits}).format(n);}
 savePreference(){try{localStorage.setItem("worldproject.currency",JSON.stringify({country:this.country,currency:this.currency}));}catch{}return{country:this.country,currency:this.currency};}
 loadPreference(){try{const p=JSON.parse(localStorage.getItem("worldproject.currency")||"null");if(p?.country)this.country=String(p.country).toUpperCase();if(p?.currency)this.currency=valid(p.currency);}catch{}return{country:this.country,currency:this.currency};}
 snapshot(){return{baseCurrency:BASE_CURRENCY,country:this.country,currency:this.currency,rates:{...this.rates},ratesUpdatedAt:this.ratesUpdatedAt,rateSource:this.rateSource};}
}
export const worldCurrency=new WorldCurrencySystem();worldCurrency.loadPreference();if(typeof window!=="undefined")window.worldCurrency=worldCurrency;
