// WorldProject – Weltwirtschaft: Konjunktur, Preise, Regionen und Schocks.
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureWorldEconomy(world={}){world.economy??={day:0,gdpIndex:1,inflation:.02,interestRate:.03,energyIndex:1,commodityIndex:1,consumerConfidence:1,regions:{},history:[],events:[]};return world.economy;}
export function ensureRegion(world,id){const e=ensureWorldEconomy(world);e.regions[id]??={demandIndex:1,wageIndex:1,landIndex:1,logisticsIndex:1,competitionIndex:1};return e.regions[id];}
export function applyEconomicEvent(world,{kind='shock',magnitude=.1,durationDays=30,region=null,at=Date.now()}={}){const e=ensureWorldEconomy(world),row={id:`econ-${at}-${Math.random().toString(36).slice(2,6)}`,kind,magnitude:n(magnitude),durationDays:Math.max(1,n(durationDays)),region,startsAt:e.day,endsAt:e.day+Math.max(1,n(durationDays)),at};e.events.push(row);return row;}
export function tickEconomy(world,{days=1}={}){const e=ensureWorldEconomy(world);for(let i=0;i<Math.max(1,n(days));i++){e.day++;const active=e.events.filter(x=>x.startsAt<=e.day&&x.endsAt>=e.day),shock=active.reduce((s,x)=>s+n(x.magnitude)*(x.kind==='boom'?1:-1),0);e.gdpIndex=clamp(e.gdpIndex+(e.consumerConfidence-1)*.002+shock*.003,.5,1.8);e.inflation=clamp(e.inflation+(e.energyIndex-1)*.0002+shock*.0001,-.02,.2);e.interestRate=clamp(e.interestRate+(e.inflation-.02)*.01,0,.25);e.energyIndex=clamp(e.energyIndex+(Math.sin(e.day/31)*.002)+shock*.005,.45,3);e.commodityIndex=clamp(e.commodityIndex+(Math.sin(e.day/47)*.0025)+shock*.004,.5,3);e.consumerConfidence=clamp(e.consumerConfidence+((e.gdpIndex-1)*.001)-shock*.003,.45,1.6);for(const r of Object.values(e.regions)){r.demandIndex=clamp(r.demandIndex+(e.gdpIndex-1)*.001+shock*.001,.5,1.8);r.wageIndex=clamp(r.wageIndex+e.inflation/365, .7,2.5);r.landIndex=clamp(r.landIndex+(e.gdpIndex-1)*.0005,.6,3);r.logisticsIndex=clamp(r.logisticsIndex+(e.energyIndex-1)*.0008,.6,2.5);}if(e.day%30===0)e.history.push({day:e.day,gdpIndex:e.gdpIndex,inflation:e.inflation,interestRate:e.interestRate,energyIndex:e.energyIndex,commodityIndex:e.commodityIndex,consumerConfidence:e.consumerConfidence});}return e;}
export function regionalEconomy(world,regionId){const e=ensureWorldEconomy(world),r=ensureRegion(world,regionId);return{regionId,...r,gdpIndex:e.gdpIndex,inflation:e.inflation,interestRate:e.interestRate,energyIndex:e.energyIndex,commodityIndex:e.commodityIndex,consumerConfidence:e.consumerConfidence};}
export function adjustedInputPrice(world,basePrice,{commodityWeight=.6,energyWeight=.2,inflationWeight=.2}={}){const e=ensureWorldEconomy(world);return n(basePrice)*(n(commodityWeight)*e.commodityIndex+n(energyWeight)*e.energyIndex+n(inflationWeight)*(1+e.inflation));}
export function worldEconomyKpis(world){const e=ensureWorldEconomy(world);return{day:e.day,gdpIndex:e.gdpIndex,inflation:e.inflation,interestRate:e.interestRate,energyIndex:e.energyIndex,commodityIndex:e.commodityIndex,consumerConfidence:e.consumerConfidence,regions:Object.keys(e.regions).length,activeEvents:e.events.filter(x=>x.startsAt<=e.day&&x.endsAt>=e.day).length};}
