-- Snapshot Stripe Checkout entitlements at session creation so later catalog edits
-- cannot turn an already-paid Checkout Session into an unfulfillable purchase.

CREATE TABLE IF NOT EXISTS public.payment_checkout_intents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider text NOT NULL,
  provider_session_id text NOT NULL,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  sku text NOT NULL,
  amount_eur numeric(10,2) NOT NULL,
  currency text NOT NULL DEFAULT 'EUR',
  kind text NOT NULL,
  coin_amount bigint,
  premium_plan text,
  duration_days integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  fulfilled_at timestamptz,
  CONSTRAINT payment_checkout_intents_provider_check CHECK (provider IN ('stripe')),
  CONSTRAINT payment_checkout_intents_currency_check CHECK (currency = 'EUR'),
  CONSTRAINT payment_checkout_intents_kind_check CHECK (kind IN ('coins','premium')),
  CONSTRAINT payment_checkout_intents_amount_check CHECK (amount_eur > 0),
  CONSTRAINT payment_checkout_intents_session_unique UNIQUE (provider, provider_session_id)
);

ALTER TABLE public.payment_checkout_intents ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.payment_checkout_intents FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.payment_checkout_intents TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.payment_checkout_intents_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.fulfill_stripe_checkout_intent(
  p_user_id bigint,
  p_provider_session_id text,
  p_provider_transaction_id text,
  p_amount_eur numeric,
  p_currency text,
  p_status text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
declare
  v_intent public.payment_checkout_intents;
  v_balance bigint;
  v_until timestamptz;
  v_purchase_id bigint;
  v_status text := lower(coalesce(p_status,''));
begin
  if current_setting('request.jwt.claim.role', true) is distinct from 'service_role' then
    raise exception 'Service role required';
  end if;
  if p_user_id is null or p_user_id <= 0 then raise exception 'Invalid user'; end if;
  if coalesce(p_provider_session_id,'')='' then raise exception 'Missing checkout session id'; end if;
  if coalesce(p_provider_transaction_id,'')='' then raise exception 'Missing transaction id'; end if;
  if upper(coalesce(p_currency,'')) <> 'EUR' then raise exception 'Invalid currency'; end if;
  if v_status not in ('paid','succeeded') then raise exception 'Payment not eligible for fulfillment'; end if;

  select * into v_intent
  from public.payment_checkout_intents
  where provider='stripe'
    and provider_session_id=p_provider_session_id
    and user_id=p_user_id
  for update;
  if not found then raise exception 'Unknown Stripe checkout intent'; end if;

  if round(p_amount_eur,2) <> round(v_intent.amount_eur,2) then raise exception 'Amount mismatch'; end if;
  if upper(v_intent.currency) <> 'EUR' then raise exception 'Intent currency mismatch'; end if;
  if v_intent.kind='coins' and coalesce(v_intent.coin_amount,0) <= 0 then raise exception 'Invalid coin entitlement snapshot'; end if;
  if v_intent.kind='premium' and (coalesce(v_intent.premium_plan,'')='' or coalesce(v_intent.duration_days,0) <= 0) then
    raise exception 'Invalid premium entitlement snapshot';
  end if;

  insert into public.payment_purchases(user_id,provider,provider_transaction_id,sku,amount_eur,currency,status)
  values(p_user_id,'stripe',p_provider_transaction_id,v_intent.sku,round(v_intent.amount_eur,2),'EUR',v_status)
  on conflict(provider,provider_transaction_id) do nothing
  returning id into v_purchase_id;

  if v_purchase_id is null then
    update public.payment_checkout_intents
    set fulfilled_at=coalesce(fulfilled_at,now())
    where id=v_intent.id;
    return jsonb_build_object('success',true,'duplicate',true,'transactionId',p_provider_transaction_id,'provider','stripe','sessionId',p_provider_session_id);
  end if;

  if v_intent.kind='coins' then
    insert into public.coin_wallets(user_id,balance,updated_at)
    values(p_user_id,v_intent.coin_amount,now())
    on conflict(user_id) do update
      set balance=public.coin_wallets.balance+excluded.balance,updated_at=now()
    returning balance into v_balance;

    insert into public.coin_transactions(user_id,amount,balance_after,transaction_type,reference_type,reference_id,note)
    values(p_user_id,v_intent.coin_amount,v_balance,'purchase','stripe_transaction',p_provider_transaction_id,'Echtgeld-Coinpaket '||v_intent.sku);

    update public.payment_checkout_intents set fulfilled_at=now() where id=v_intent.id;
    return jsonb_build_object('success',true,'kind','coins','coins',v_intent.coin_amount,'balance',v_balance,'transactionId',p_provider_transaction_id,'provider','stripe','sessionId',p_provider_session_id);
  end if;

  update public.users
  set premium_plan=v_intent.premium_plan,
      premium_until=(greatest(coalesce(premium_until,now()),now()) + make_interval(days=>v_intent.duration_days)),
      premium_auto_renew=false
  where id=p_user_id
  returning premium_until into v_until;

  update public.payment_checkout_intents set fulfilled_at=now() where id=v_intent.id;
  return jsonb_build_object('success',true,'kind','premium','plan',v_intent.premium_plan,'premiumUntil',v_until,'transactionId',p_provider_transaction_id,'provider','stripe','sessionId',p_provider_session_id);
end;
$function$;

REVOKE EXECUTE ON FUNCTION public.fulfill_stripe_checkout_intent(bigint,text,text,numeric,text,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fulfill_stripe_checkout_intent(bigint,text,text,numeric,text,text) TO service_role;
